In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

SEARCH_DIRS = [
    PROJECT_ROOT / "data" / "processed",
    PROJECT_ROOT / "data" / "audit",
]

REQUIRED_GROUPS = {
    "implied_variance": [
        "implied_variance",
        "vix_style_vol",
        "tenor",
        "trade_date",
    ],
    "forecast_denominator": [
        "forecast_variance_candidate",
        "predicted_log_variance_candidate",
        "model_vrp_log",
        "tenor",
        "trade_date",
    ],
    "z_scores": [
        "model_vrp_z_3m",
        "model_vrp_z_1y",
        "z_3m",
        "z_1y",
        "trade_date",
        "tenor",
    ],
    "rsi": [
        "rsi14",
        "rsi_14",
        "trade_date",
    ],
    "rv21d": [
        "rv21d_vol_pct",
        "spy_close",
        "trade_date",
    ],
    "sizing_lock": [
        "selected_size_pct",
        "locked_size",
        "sleeve",
        "layer",
        "bucket",
        "dte",
    ],
    "selection_rule": [
        "selection_rule",
        "final_one_trade_per_day",
        "naked_put",
    ],
}

def get_columns(path: Path):
    try:
        if path.suffix.lower() == ".parquet":
            return list(pd.read_parquet(path, engine="pyarrow").columns)
        if path.suffix.lower() == ".csv":
            return list(pd.read_csv(path, nrows=5).columns)
        return []
    except Exception as e:
        return [f"ERROR: {type(e).__name__}: {e}"]

def score_file(cols, terms):
    cols_lower = [str(c).lower() for c in cols]
    score = 0
    hits = []
    for term in terms:
        term_lower = term.lower()
        matched = any(term_lower in c for c in cols_lower)
        if matched:
            score += 1
            hits.append(term)
    return score, hits

all_files = []

for search_dir in SEARCH_DIRS:
    if not search_dir.exists():
        continue

    for path in search_dir.rglob("*"):
        if path.suffix.lower() not in [".parquet", ".csv", ".json"]:
            continue

        all_files.append(path)

print("=" * 100)
print("Files scanned")
print("=" * 100)
print(f"Total files: {len(all_files)}")

results = []

for path in all_files:
    suffix = path.suffix.lower()

    if suffix == ".json":
        cols = []
        text = ""
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")[:5000].lower()
        except Exception:
            text = ""

        for group, terms in REQUIRED_GROUPS.items():
            hits = [t for t in terms if t.lower() in text]
            if hits:
                results.append(
                    {
                        "group": group,
                        "score": len(hits),
                        "hits": ", ".join(hits),
                        "rows": None,
                        "cols": None,
                        "path": str(path),
                    }
                )
        continue

    cols = get_columns(path)

    rows = None
    try:
        if suffix == ".parquet":
            rows = len(pd.read_parquet(path, columns=[]))
        elif suffix == ".csv":
            rows = sum(1 for _ in open(path, "r", encoding="utf-8", errors="ignore")) - 1
    except Exception:
        rows = None

    for group, terms in REQUIRED_GROUPS.items():
        score, hits = score_file(cols, terms)
        if score > 0:
            results.append(
                {
                    "group": group,
                    "score": score,
                    "hits": ", ".join(hits),
                    "rows": rows,
                    "cols": len(cols),
                    "path": str(path),
                }
            )

results_df = pd.DataFrame(results)

if results_df.empty:
    print("No candidate files found.")
else:
    results_df = results_df.sort_values(["group", "score", "path"], ascending=[True, False, True])

    for group in sorted(results_df["group"].unique()):
        print("\n" + "=" * 100)
        print(group)
        print("=" * 100)

        display(
            results_df[results_df["group"] == group]
            .head(25)
            .reset_index(drop=True)
        )

====================================================================================================
Files scanned
====================================================================================================
Total files: 2190

====================================================================================================
forecast_denominator
====================================================================================================

,group,score,hits,rows,cols,path
0,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",3112.0,129.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
1,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",7502.0,124.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
2,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",1029.0,127.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
3,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",2663.0,129.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
4,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",2663.0,150.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
5,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",365.0,156.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
6,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",20838.0,142.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
7,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",20838.0,142.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
8,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",150.0,147.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
9,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",150.0,147.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
10,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",3912.0,147.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
11,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",3912.0,147.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
12,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",13684.0,146.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
13,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",13684.0,146.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
14,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",14688.0,128.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
15,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",14688.0,128.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
16,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",1965.0,139.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
17,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",1965.0,139.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
18,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",77166.0,165.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
19,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",37126.0,165.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
20,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",6326.0,148.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
21,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",434368.0,192.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
22,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",218152.0,192.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
23,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",105.0,140.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...
24,forecast_denominator,5,"forecast_variance_candidate, predicted_log_var...",12437.0,150.0,C:\Users\patri\vrp_project\data\audit\vrp_unif...

====================================================================================================
implied_variance
====================================================================================================

,group,score,hits,rows,cols,path
0,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",1000.0,65.0,C:\Users\patri\vrp_project\data\audit\forecast...
1,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",25.0,56.0,C:\Users\patri\vrp_project\data\audit\forecast...
2,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",50.0,46.0,C:\Users\patri\vrp_project\data\audit\forecast...
3,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",75.0,50.0,C:\Users\patri\vrp_project\data\audit\forecast...
4,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",75.0,61.0,C:\Users\patri\vrp_project\data\audit\forecast...
5,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",500.0,46.0,C:\Users\patri\vrp_project\data\audit\forecast...
6,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",500.0,395.0,C:\Users\patri\vrp_project\data\audit\forecast...
7,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",1000.0,61.0,C:\Users\patri\vrp_project\data\audit\forecast...
8,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",750.0,50.0,C:\Users\patri\vrp_project\data\audit\forecast...
9,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",1000.0,37.0,C:\Users\patri\vrp_project\data\audit\forecast...
10,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",2000.0,50.0,C:\Users\patri\vrp_project\data\audit\forecast...
11,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",2000.0,106.0,C:\Users\patri\vrp_project\data\audit\forecast...
12,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",1000.0,25.0,C:\Users\patri\vrp_project\data\audit\forecast...
13,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",605.0,112.0,C:\Users\patri\vrp_project\data\audit\put_bala...
14,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",2000.0,79.0,C:\Users\patri\vrp_project\data\audit\put_cham...
15,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",3025.0,112.0,C:\Users\patri\vrp_project\data\audit\put_core...
16,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",319.0,87.0,C:\Users\patri\vrp_project\data\audit\put_exec...
17,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",2420.0,112.0,C:\Users\patri\vrp_project\data\audit\put_open...
18,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",605.0,112.0,C:\Users\patri\vrp_project\data\audit\put_phas...
19,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",378.0,112.0,C:\Users\patri\vrp_project\data\audit\put_phas...
20,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",378.0,107.0,C:\Users\patri\vrp_project\data\audit\put_phas...
21,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",378.0,106.0,C:\Users\patri\vrp_project\data\audit\put_phas...
22,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",378.0,146.0,C:\Users\patri\vrp_project\data\audit\put_phas...
23,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",1000.0,39.0,C:\Users\patri\vrp_project\data\audit\put_vol_...
24,implied_variance,4,"implied_variance, vix_style_vol, tenor, trade_...",1000.0,48.0,C:\Users\patri\vrp_project\data\audit\signal_d...

====================================================================================================
rsi
====================================================================================================

,group,score,hits,rows,cols,path
0,rsi,3,"rsi14, rsi_14, trade_date",NaN,NaN,C:\Users\patri\vrp_project\data\audit\producti...
1,rsi,3,"rsi14, rsi_14, trade_date",1112.0,89.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
2,rsi,3,"rsi14, rsi_14, trade_date",9.0,57.0,C:\Users\patri\vrp_project\data\processed\back...
3,rsi,3,"rsi14, rsi_14, trade_date",18144.0,57.0,C:\Users\patri\vrp_project\data\processed\back...
4,rsi,3,"rsi14, rsi_14, trade_date",0.0,57.0,C:\Users\patri\vrp_project\data\processed\back...
5,rsi,3,"rsi14, rsi_14, trade_date",0.0,71.0,C:\Users\patri\vrp_project\data\processed\old\...
6,rsi,3,"rsi14, rsi_14, trade_date",2.0,72.0,C:\Users\patri\vrp_project\data\processed\old\...
7,rsi,3,"rsi14, rsi_14, trade_date",0.0,72.0,C:\Users\patri\vrp_project\data\processed\old\...
8,rsi,3,"rsi14, rsi_14, trade_date",9.0,67.0,C:\Users\patri\vrp_project\data\processed\old\...
9,rsi,3,"rsi14, rsi_14, trade_date",0.0,67.0,C:\Users\patri\vrp_project\data\processed\old\...
10,rsi,3,"rsi14, rsi_14, trade_date",9.0,67.0,C:\Users\patri\vrp_project\data\processed\old\...
11,rsi,3,"rsi14, rsi_14, trade_date",0.0,67.0,C:\Users\patri\vrp_project\data\processed\old\...
12,rsi,3,"rsi14, rsi_14, trade_date",9.0,57.0,C:\Users\patri\vrp_project\data\processed\prod...
13,rsi,3,"rsi14, rsi_14, trade_date",18144.0,57.0,C:\Users\patri\vrp_project\data\processed\prod...
14,rsi,3,"rsi14, rsi_14, trade_date",0.0,57.0,C:\Users\patri\vrp_project\data\processed\prod...
15,rsi,3,"rsi14, rsi_14, trade_date",9.0,67.0,C:\Users\patri\vrp_project\data\processed\sign...
16,rsi,3,"rsi14, rsi_14, trade_date",0.0,67.0,C:\Users\patri\vrp_project\data\processed\sign...
17,rsi,3,"rsi14, rsi_14, trade_date",9.0,57.0,C:\Users\patri\vrp_project\data\processed\stag...
18,rsi,3,"rsi14, rsi_14, trade_date",18144.0,57.0,C:\Users\patri\vrp_project\data\processed\stag...
19,rsi,3,"rsi14, rsi_14, trade_date",0.0,57.0,C:\Users\patri\vrp_project\data\processed\stag...
20,rsi,3,"rsi14, rsi_14, trade_date",0.0,73.0,C:\Users\patri\vrp_project\data\processed\vrp_...
21,rsi,3,"rsi14, rsi_14, trade_date",0.0,85.0,C:\Users\patri\vrp_project\data\processed\vrp_...
22,rsi,2,"rsi14, trade_date",100.0,16.0,C:\Users\patri\vrp_project\data\audit\corsi_pa...
23,rsi,2,"rsi14, trade_date",11296.0,28.0,C:\Users\patri\vrp_project\data\audit\corsi_pa...
24,rsi,2,"rsi_14, trade_date",1969.0,13.0,C:\Users\patri\vrp_project\data\audit\endpoint...

====================================================================================================
rv21d
====================================================================================================

,group,score,hits,rows,cols,path
0,rv21d,3,"rv21d_vol_pct, spy_close, trade_date",NaN,NaN,C:\Users\patri\vrp_project\data\audit\market_d...
1,rv21d,3,"rv21d_vol_pct, spy_close, trade_date",NaN,NaN,C:\Users\patri\vrp_project\data\audit\market_d...
2,rv21d,3,"rv21d_vol_pct, spy_close, trade_date",0.0,29.0,C:\Users\patri\vrp_project\data\processed\mark...
3,rv21d,3,"rv21d_vol_pct, spy_close, trade_date",0.0,25.0,C:\Users\patri\vrp_project\data\processed\mark...
4,rv21d,2,"spy_close, trade_date",1.0,11.0,C:\Users\patri\vrp_project\data\audit\market_d...
5,rv21d,2,"spy_close, trade_date",1.0,11.0,C:\Users\patri\vrp_project\data\audit\market_d...
6,rv21d,2,"spy_close, trade_date",1.0,11.0,C:\Users\patri\vrp_project\data\audit\market_d...
7,rv21d,2,"spy_close, trade_date",5.0,12.0,C:\Users\patri\vrp_project\data\audit\market_d...
8,rv21d,2,"spy_close, trade_date",5.0,12.0,C:\Users\patri\vrp_project\data\audit\market_d...
9,rv21d,2,"spy_close, trade_date",5.0,12.0,C:\Users\patri\vrp_project\data\audit\market_d...
10,rv21d,2,"rv21d_vol_pct, trade_date",20.0,12.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
11,rv21d,2,"rv21d_vol_pct, trade_date",1612.0,27.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
12,rv21d,2,"rv21d_vol_pct, trade_date",20.0,12.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
13,rv21d,2,"rv21d_vol_pct, trade_date",1612.0,35.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
14,rv21d,2,"rv21d_vol_pct, trade_date",240.0,44.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
15,rv21d,2,"rv21d_vol_pct, trade_date",140.0,42.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
16,rv21d,2,"rv21d_vol_pct, trade_date",23.0,18.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
17,rv21d,2,"rv21d_vol_pct, trade_date",279.0,18.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
18,rv21d,2,"rv21d_vol_pct, trade_date",40.0,44.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
19,rv21d,2,"rv21d_vol_pct, trade_date",16.0,18.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
20,rv21d,2,"rv21d_vol_pct, trade_date",3112.0,129.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
21,rv21d,2,"rv21d_vol_pct, trade_date",16.0,115.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
22,rv21d,2,"rv21d_vol_pct, trade_date",16.0,138.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
23,rv21d,2,"rv21d_vol_pct, trade_date",16.0,162.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
24,rv21d,2,"rv21d_vol_pct, trade_date",6.0,100.0,C:\Users\patri\vrp_project\data\audit\vrp_core...

====================================================================================================
selection_rule
====================================================================================================

,group,score,hits,rows,cols,path
0,selection_rule,3,"selection_rule, final_one_trade_per_day, naked...",NaN,NaN,C:\Users\patri\vrp_project\data\audit\vrp_core...
1,selection_rule,2,"final_one_trade_per_day, naked_put",NaN,NaN,C:\Users\patri\vrp_project\data\audit\vrp_core...
2,selection_rule,2,"final_one_trade_per_day, naked_put",NaN,NaN,C:\Users\patri\vrp_project\data\audit\vrp_core...
3,selection_rule,1,selection_rule,577.0,66.0,C:\Users\patri\vrp_project\data\audit\locked_2...
4,selection_rule,1,selection_rule,577.0,60.0,C:\Users\patri\vrp_project\data\audit\locked_2...
5,selection_rule,1,selection_rule,577.0,38.0,C:\Users\patri\vrp_project\data\audit\locked_2...
6,selection_rule,1,selection_rule,25.0,38.0,C:\Users\patri\vrp_project\data\audit\locked_2...
7,selection_rule,1,selection_rule,10.0,38.0,C:\Users\patri\vrp_project\data\audit\locked_2...
8,selection_rule,1,selection_rule,577.0,58.0,C:\Users\patri\vrp_project\data\audit\locked_2...
9,selection_rule,1,selection_rule,577.0,51.0,C:\Users\patri\vrp_project\data\audit\locked_2...
10,selection_rule,1,selection_rule,577.0,54.0,C:\Users\patri\vrp_project\data\audit\locked_2...
11,selection_rule,1,selection_rule,577.0,50.0,C:\Users\patri\vrp_project\data\audit\locked_2...
12,selection_rule,1,selection_rule,577.0,52.0,C:\Users\patri\vrp_project\data\audit\locked_2...
13,selection_rule,1,selection_rule,577.0,70.0,C:\Users\patri\vrp_project\data\audit\locked_2...
14,selection_rule,1,selection_rule,577.0,37.0,C:\Users\patri\vrp_project\data\audit\locked_2...
15,selection_rule,1,selection_rule,577.0,60.0,C:\Users\patri\vrp_project\data\audit\locked_2...
16,selection_rule,1,selection_rule,20.0,37.0,C:\Users\patri\vrp_project\data\audit\locked_2...
17,selection_rule,1,selection_rule,20.0,37.0,C:\Users\patri\vrp_project\data\audit\locked_2...
18,selection_rule,1,selection_rule,399.0,48.0,C:\Users\patri\vrp_project\data\audit\vol_of_v...
19,selection_rule,1,selection_rule,6347.0,48.0,C:\Users\patri\vrp_project\data\audit\vol_of_v...
20,selection_rule,1,selection_rule,8386.0,63.0,C:\Users\patri\vrp_project\data\audit\vol_of_v...
21,selection_rule,1,selection_rule,59277.0,63.0,C:\Users\patri\vrp_project\data\audit\vol_of_v...
22,selection_rule,1,selection_rule,16.0,31.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
23,selection_rule,1,selection_rule,3.0,31.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
24,selection_rule,1,selection_rule,39.0,33.0,C:\Users\patri\vrp_project\data\audit\vrp_core...

====================================================================================================
sizing_lock
====================================================================================================

,group,score,hits,rows,cols,path
0,sizing_lock,4,"sleeve, layer, bucket, dte",3112.0,129.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
1,sizing_lock,4,"sleeve, layer, bucket, dte",7502.0,124.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
2,sizing_lock,4,"sleeve, layer, bucket, dte",1029.0,127.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
3,sizing_lock,4,"sleeve, layer, bucket, dte",2663.0,129.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
4,sizing_lock,4,"sleeve, layer, bucket, dte",2663.0,150.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
5,sizing_lock,4,"sleeve, layer, bucket, dte",NaN,NaN,C:\Users\patri\vrp_project\data\audit\vrp_core...
6,sizing_lock,4,"sleeve, layer, bucket, dte",365.0,156.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
7,sizing_lock,4,"locked_size, sleeve, layer, bucket",13.0,43.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
8,sizing_lock,4,"locked_size, sleeve, layer, bucket",365.0,18.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
9,sizing_lock,4,"locked_size, sleeve, layer, bucket",13.0,35.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
10,sizing_lock,4,"sleeve, layer, bucket, dte",0.0,129.0,C:\Users\patri\vrp_project\data\processed\vrp_...
11,sizing_lock,4,"sleeve, layer, bucket, dte",0.0,124.0,C:\Users\patri\vrp_project\data\processed\vrp_...
12,sizing_lock,4,"sleeve, layer, bucket, dte",0.0,127.0,C:\Users\patri\vrp_project\data\processed\vrp_...
13,sizing_lock,4,"sleeve, layer, bucket, dte",0.0,129.0,C:\Users\patri\vrp_project\data\processed\vrp_...
14,sizing_lock,4,"sleeve, layer, bucket, dte",0.0,156.0,C:\Users\patri\vrp_project\data\processed\vrp_...
15,sizing_lock,4,"locked_size, sleeve, layer, bucket",0.0,43.0,C:\Users\patri\vrp_project\data\processed\vrp_...
16,sizing_lock,4,"locked_size, sleeve, layer, bucket",0.0,18.0,C:\Users\patri\vrp_project\data\processed\vrp_...
17,sizing_lock,4,"locked_size, sleeve, layer, bucket",0.0,35.0,C:\Users\patri\vrp_project\data\processed\vrp_...
18,sizing_lock,3,"layer, bucket, dte",333504.0,17.0,C:\Users\patri\vrp_project\data\audit\corsi_pa...
19,sizing_lock,3,"layer, bucket, dte",100.0,16.0,C:\Users\patri\vrp_project\data\audit\corsi_pa...
20,sizing_lock,3,"layer, bucket, dte",577.0,66.0,C:\Users\patri\vrp_project\data\audit\locked_2...
21,sizing_lock,3,"layer, bucket, dte",577.0,60.0,C:\Users\patri\vrp_project\data\audit\locked_2...
22,sizing_lock,3,"layer, bucket, dte",577.0,28.0,C:\Users\patri\vrp_project\data\audit\locked_2...
23,sizing_lock,3,"layer, bucket, dte",308.0,33.0,C:\Users\patri\vrp_project\data\audit\locked_2...
24,sizing_lock,3,"layer, bucket, dte",6.0,17.0,C:\Users\patri\vrp_project\data\audit\locked_2...

====================================================================================================
z_scores
====================================================================================================

,group,score,hits,rows,cols,path
0,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",240.0,44.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
1,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",140.0,42.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
2,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",40.0,44.0,C:\Users\patri\vrp_project\data\audit\vrp_30d_...
3,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",17568.0,9.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
4,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",17568.0,9.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
5,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",21448.0,28.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
6,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",13369.0,31.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
7,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",21428.0,31.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
8,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",3346.0,31.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
9,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",1975.0,31.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
10,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",1112.0,89.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
11,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",16.0,18.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
12,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",3112.0,129.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
13,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",16.0,115.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
14,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",16.0,138.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
15,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",16.0,162.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
16,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",7502.0,124.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
17,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",77.0,111.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
18,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",1029.0,127.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
19,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",13.0,20.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
20,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",2663.0,129.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
21,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",13.0,144.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
22,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",13.0,180.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
23,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",13.0,180.0,C:\Users\patri\vrp_project\data\audit\vrp_core...
24,z_scores,6,"model_vrp_z_3m, model_vrp_z_1y, z_3m, z_1y, tr...",2663.0,150.0,C:\Users\patri\vrp_project\data\audit\vrp_core...

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np
from datetime import datetime

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", 200)

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

SEARCH_ROOTS = [
    PROJECT_ROOT / "data" / "processed",
    PROJECT_ROOT / "data" / "audit",
]

KEY_PATTERNS = [
    "07A",
    "unified_fds_no_min_return",
    "oos_forecast_panel",
    "forecast_panel",
    "core_secondary_consistent_secondary",
    "final_one_trade_per_day",
    "naked_put",
    "15S_final_one_trade_per_day",
    "sizing_lock",
    "selection_rule",
    "16S_locked",
    "cumulative_pnl",
]

KEY_COLUMNS = [
    "trade_date",
    "tenor",
    "implied_variance",
    "vix_style_vol",
    "forecast_variance_candidate",
    "predicted_log_variance_candidate",
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14",
    "rsi14",
    "rv21d_vol_pct",
    "selected_size_pct",
    "locked_size",
    "sleeve",
    "signal_layer",
    "signal_bucket",
    "selected_layer",
    "selected_tenor",
]

def file_matches(path: Path):
    s = str(path).lower()
    return any(p.lower() in s for p in KEY_PATTERNS)

def safe_read_cols(path: Path):
    try:
        if path.suffix.lower() == ".parquet":
            df = pd.read_parquet(path)
        elif path.suffix.lower() == ".csv":
            df = pd.read_csv(path)
        else:
            return None, []
        return df, list(df.columns)
    except Exception as e:
        return None, [f"ERROR: {type(e).__name__}: {e}"]

rows = []

for root in SEARCH_ROOTS:
    if not root.exists():
        continue

    for path in root.rglob("*"):
        if path.suffix.lower() not in [".parquet", ".csv", ".json"]:
            continue

        if not file_matches(path):
            continue

        stat = path.stat()
        mtime = datetime.fromtimestamp(stat.st_mtime)

        if path.suffix.lower() == ".json":
            text = path.read_text(encoding="utf-8", errors="ignore")[:10000].lower()
            hits = [p for p in KEY_PATTERNS if p.lower() in text or p.lower() in str(path).lower()]
            rows.append({
                "path": str(path),
                "suffix": path.suffix,
                "modified": mtime,
                "rows": None,
                "cols": None,
                "min_date": None,
                "max_date": None,
                "tenors": None,
                "key_col_hits": None,
                "pattern_hits": ", ".join(hits),
            })
            continue

        df, cols = safe_read_cols(path)

        if df is None:
            rows.append({
                "path": str(path),
                "suffix": path.suffix,
                "modified": mtime,
                "rows": None,
                "cols": None,
                "min_date": None,
                "max_date": None,
                "tenors": None,
                "key_col_hits": "; ".join(cols),
                "pattern_hits": None,
            })
            continue

        min_date = None
        max_date = None
        tenors = None

        if "trade_date" in df.columns and len(df) > 0:
            d = pd.to_datetime(df["trade_date"], errors="coerce")
            if d.notna().any():
                min_date = str(d.min().date())
                max_date = str(d.max().date())

        if "tenor" in df.columns and len(df) > 0:
            try:
                tenors = sorted(pd.Series(df["tenor"]).dropna().astype(int).unique().tolist())
            except Exception:
                tenors = sorted(pd.Series(df["tenor"]).dropna().astype(str).unique().tolist())

        key_col_hits = [c for c in KEY_COLUMNS if c in df.columns]
        pattern_hits = [p for p in KEY_PATTERNS if p.lower() in str(path).lower()]

        rows.append({
            "path": str(path),
            "suffix": path.suffix,
            "modified": mtime,
            "rows": len(df),
            "cols": len(df.columns),
            "min_date": min_date,
            "max_date": max_date,
            "tenors": tenors,
            "key_col_hits": ", ".join(key_col_hits),
            "pattern_hits": ", ".join(pattern_hits),
        })

inventory = pd.DataFrame(rows)

if inventory.empty:
    print("No targeted candidate files found.")
else:
    inventory["score"] = (
        inventory["key_col_hits"].fillna("").str.count(",") + 1
        + inventory["pattern_hits"].fillna("").str.count(",") + 1
        + inventory["rows"].fillna(0).clip(upper=10000) / 10000
    )

    inventory = inventory.sort_values(
        ["score", "modified", "rows"],
        ascending=[False, False, False],
    ).reset_index(drop=True)

    out_path = PROJECT_ROOT / "data" / "audit" / "vrp_final_signal_source_inventory_targeted.csv"
    inventory.to_csv(out_path, index=False)

    print("Saved targeted inventory:")
    print(out_path)

    display(
        inventory[
            [
                "path",
                "modified",
                "rows",
                "cols",
                "min_date",
                "max_date",
                "tenors",
                "key_col_hits",
                "pattern_hits",
                "score",
            ]
        ].head(100)
    )

Saved targeted inventory:
C:\Users\patri\vrp_project\data\audit\vrp_final_signal_source_inventory_targeted.csv

,path,modified,rows,cols,min_date,max_date,tenors,key_col_hits,pattern_hits,score
0,C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_fds_no_min_return_oos_forecast_panel_20200102_20260701_20260704_203242.parquet,2026-07-04 20:32:49.275804,31140.0,89.0,2019-01-02,2026-07-01,"[9, 12, 15, 18, 21, 24, 27, 30, 33]","trade_date, tenor, implied_variance, vix_style_vol, forecast_variance_candidate, predicted_log_variance_candidate, model_vrp_log, model_vrp_z_3m, model_vrp_z_1y, RSI14","07A, unified_fds_no_min_return, oos_forecast_panel, forecast_panel",15.0000
1,C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\06C_back_model_spec_oos_forecast_panel_20200102_20260701_20260704_202315.parquet,2026-07-04 20:23:37.614007,49212.0,93.0,2019-01-02,2026-07-01,"[27, 30, 33]","trade_date, tenor, implied_variance, vix_style_vol, forecast_variance_candidate, predicted_log_variance_candidate, model_vrp_log, model_vrp_z_3m, model_vrp_z_1y, RSI14","oos_forecast_panel, forecast_panel",13.0000
2,C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\06B_back_unfreeze_oos_forecast_panel_20200102_20260701_20260704_200958.parquet,2026-07-04 20:10:06.902388,24732.0,89.0,2019-01-02,2026-07-01,"[27, 30, 33]","trade_date, tenor, implied_variance, vix_style_vol, forecast_variance_candidate, predicted_log_variance_candidate, model_vrp_log, model_vrp_z_3m, model_vrp_z_1y, RSI14","oos_forecast_panel, forecast_panel",13.0000
3,C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_signal_threshold_diagnostic_panel_20200102_20260701_20260704_203242.parquet,2026-07-04 20:32:49.632170,29376.0,99.0,2020-01-02,2026-07-01,"[9, 12, 15, 18, 21, 24, 27, 30, 33]","trade_date, tenor, implied_variance, vix_style_vol, forecast_variance_candidate, predicted_log_variance_candidate, model_vrp_log, model_vrp_z_3m, model_vrp_z_1y, RSI14",07A,12.0000
4,C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_common_row_panel_20200102_20260701_20260704_203242.parquet,2026-07-04 20:32:49.448847,29376.0,93.0,2020-01-02,2026-07-01,"[9, 12, 15, 18, 21, 24, 27, 30, 33]","trade_date, tenor, implied_variance, vix_style_vol, forecast_variance_candidate, predicted_log_variance_candidate, model_vrp_log, model_vrp_z_3m, model_vrp_z_1y, RSI14",07A,12.0000
5,C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_qualified_trade_diagnostic_panel_20200102_20260701_20260704_203242.parquet,2026-07-04 20:32:49.668527,3361.0,99.0,2020-01-03,2026-05-04,"[9, 12, 15, 18, 21, 24, 27, 30, 33]","trade_date, tenor, implied_variance, vix_style_vol, forecast_variance_candidate, predicted_log_variance_candidate, model_vrp_log, model_vrp_z_3m, model_vrp_z_1y, RSI14",07A,11.3361
6,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\16S_locked_dte_performance_manifest_20260706_143802.json,2026-07-06 14:38:02.754414,NaN,NaN,None,None,None,None,"final_one_trade_per_day, naked_put, 15S_final_one_trade_per_day, sizing_lock, 16S_locked, cumulative_pnl",7.0000
7,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_sizing_lock_manifest_20260706_142800.json,2026-07-06 14:28:00.582081,NaN,NaN,None,None,None,None,"core_secondary_consistent_secondary, final_one_trade_per_day, naked_put, 15S_final_one_trade_per_day, sizing_lock, selection_rule",7.0000
8,C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_sizing_lock_rules_20260706_142800.parquet,2026-07-06 14:28:00.540486,13.0,43.0,None,None,"[12, 15, 18, 21, 24, 27, 30, 33]","tenor, signal_layer","final_one_trade_per_day, naked_put, 15S_final_one_trade_per_day, sizing_lock",6.0013
9,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_sizing_lock_rules_20260706_142800.csv,2026-07-06 14:28:00.529046,13.0,43.0,None,None,"[12, 15, 18, 21, 24, 27, 30, 33]","tenor, signal_layer","final_one_trade_per_day, naked_put, 15S_final_one_trade_per_day, sizing_lock",6.0013
10,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_selection_rule_20260706_142800.json,2026-07-06 14:28:00.540486,NaN,NaN,None,None,None,None,"final_one_trade_per_day, naked_put, 15S_final_one_trade_per_day, sizing_lock, selection_rule",6.0000
11,C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1\16S_locked_cumulative_pnl_timeseries_20260706_143802.parquet,2026-07-06 14:38:02.750885,365.0,18.0,2020-12-31,2026-05-13,"[12, 15, 18, 21, 24, 27, 30, 33]","trade_date, tenor, signal_layer","16S_locked, cumulative_pnl",5.0365
12,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\16S_locked_cumulative_pnl_timeseries_20260706_143802.csv,2026-07-06 14:38:02.742467,365.0,18.0,2020-12-31,2026-05-13,"[12, 15, 18, 21, 24, 27, 30, 33]","trade_date, tenor, signal_layer","16S_locked, cumulative_pnl",5.0365
13,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_sizing_lock_validation_20260706_142800.csv,2026-07-06 14:28:00.573040,18.0,3.0,None,None,None,,"final_one_trade_per_day, naked_put, 15S_final_one_trade_per_day, sizing_lock",5.0018
14,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_selected_sleeve_distribution_20260706_142800.csv,2026-07-06 14:28:00.573040,13.0,11.0,None,None,"[12, 15, 18, 21, 24, 27, 30, 33]","tenor, signal_layer","final_one_trade_per_day, naked_put, 15S_final_one_trade_per_day",5.0013
15,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_selected_size_distribution_20260706_142800.csv,2026-07-06 14:28:00.573040,10.0,5.0,None,None,None,,"final_one_trade_per_day, naked_put, 15S_final_one_trade_per_day",4.0010
16,C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_program_summary_20260706_142800.parquet,2026-07-06 14:28:00.569386,2.0,103.0,None,None,None,,"final_one_trade_per_day, naked_put, 15S_final_one_trade_per_day",4.0002
17,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_program_summary_20260706_142800.csv,2026-07-06 14:28:00.540486,2.0,103.0,None,None,None,,"final_one_trade_per_day, naked_put, 15S_final_one_trade_per_day",4.0002
18,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\09S_core_secondary_consistent_secondary_lock_manifest_20260705_221829.json,2026-07-05 22:18:29.119797,NaN,NaN,None,None,None,None,"unified_fds_no_min_return, core_secondary_consistent_secondary, selection_rule",4.0000
19,C:\Users\patri\vrp_project\data\processed\vrp_30d_corsi_v1\03_30d_corsi_oos_forecast_panel_long_20200102_20260602_20260704_140452.parquet,2026-07-04 14:04:57.949009,12096.0,13.0,1970-01-01,1970-01-01,None,trade_date,"oos_forecast_panel, forecast_panel",4.0000
20,C:\Users\patri\vrp_project\data\audit\locked_2621_constant_1mm_nav_cumulative_pnl_trade_level_v0_1.csv,2026-07-03 12:09:02.622724,577.0,60.0,None,None,None,"rsi14, selected_tenor",cumulative_pnl,3.0577
21,C:\Users\patri\vrp_project\data\audit\locked_2621_constant_1mm_nav_cumulative_pnl_realized_curve_v0_1.csv,2026-07-03 12:09:02.585615,577.0,66.0,None,None,None,"rsi14, selected_tenor",cumulative_pnl,3.0577
22,C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1\09S_core_secondary_consistent_secondary_locked_rules_long_20260705_221829.parquet,2026-07-05 22:18:29.110229,19.0,33.0,None,None,"[12, 15, 18, 21, 24, 27, 30, 33]","tenor, signal_layer",core_secondary_consistent_secondary,3.0019
23,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\09S_core_secondary_consistent_secondary_locked_rules_long_20260705_221829.csv,2026-07-05 22:18:29.099487,19.0,33.0,None,None,"[12, 15, 18, 21, 24, 27, 30, 33]","tenor, signal_layer",core_secondary_consistent_secondary,3.0019
24,C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1\16S_locked_dte_performance_table_20260706_143802.parquet,2026-07-06 14:38:02.732500,13.0,35.0,None,None,"[12, 15, 18, 21, 24, 27, 30, 33]","tenor, signal_layer",16S_locked,3.0013
25,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\16S_locked_dte_performance_table_20260706_143802.csv,2026-07-06 14:38:02.722290,13.0,35.0,None,None,"[12, 15, 18, 21, 24, 27, 30, 33]","tenor, signal_layer",16S_locked,3.0013
26,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\09S_core_secondary_consistent_secondary_exclusions_20260705_221829.csv,2026-07-05 22:18:29.119797,6.0,33.0,None,None,"[12, 15, 18]","tenor, signal_layer",core_secondary_consistent_secondary,3.0006
27,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\09S_core_secondary_consistent_secondary_threshold_diffs_20260705_221829.csv,2026-07-05 22:18:29.119797,6.0,5.0,None,None,"[21, 24]","tenor, signal_layer",core_secondary_consistent_secondary,3.0006
28,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_manifest_20260704_203242.json,2026-07-04 20:32:49.703960,NaN,NaN,None,None,None,None,"07A, unified_fds_no_min_return",3.0000
29,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_inner_cv_20260704_203242.csv,2026-07-04 20:32:49.702958,945.0,10.0,None,None,None,,07A,2.0945
30,C:\Users\patri\vrp_project\data\audit\vrp_core_bucket_parameters_v1\07_core_v1_daily_cumulative_pnl_fixed_5pct_1mm_20180924_20260701_20260704_191616.csv,2026-07-04 19:16:17.073438,246.0,10.0,2020-02-24,2026-05-04,None,trade_date,cumulative_pnl,2.0246
31,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_fit_log_20260704_203242.csv,2026-07-04 20:32:49.694829,81.0,8.0,None,None,"[9, 12, 15, 18, 21, 24, 27, 30, 33]",tenor,07A,2.0081
32,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_common_row_metrics_by_year_vs_existing_20260704_203242.csv,2026-07-04 20:32:49.682662,42.0,37.0,None,None,None,,07A,2.0042
33,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_common_row_metrics_by_year_20260704_203242.csv,2026-07-04 20:32:49.675526,42.0,21.0,None,None,None,,07A,2.0042
34,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\09S_core_secondary_consistent_secondary_lock_validation_20260705_221829.csv,2026-07-05 22:18:29.119797,22.0,3.0,None,None,None,,core_secondary_consistent_secondary,2.0022
35,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\16S_locked_dte_performance_validation_20260706_143802.csv,2026-07-06 14:38:02.753907,19.0,4.0,None,None,None,,16S_locked,2.0019
36,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_signal_pass_diagnostics_20260704_203242.csv,2026-07-04 20:32:49.689829,18.0,11.0,None,None,"[9, 12, 15, 18, 21, 24, 27, 30, 33]",tenor,07A,2.0018
37,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_common_row_metrics_by_tenor_vs_existing_20260704_203242.csv,2026-07-04 20:32:49.679666,18.0,37.0,None,None,"[9, 12, 15, 18, 21, 24, 27, 30, 33]",tenor,07A,2.0018
38,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_common_row_metrics_by_tenor_20260704_203242.csv,2026-07-04 20:32:49.672527,18.0,21.0,None,None,"[9, 12, 15, 18, 21, 24, 27, 30, 33]",tenor,07A,2.0018
39,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\09S_core_secondary_consistent_secondary_lock_decision_summary_20260705_221829.csv,2026-07-05 22:18:29.119797,17.0,2.0,None,None,None,,core_secondary_consistent_secondary,2.0017
40,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_validation_20260704_203242.csv,2026-07-04 20:32:49.695829,14.0,3.0,None,None,None,,07A,2.0014
41,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_trade_summary_by_bucket_vs_existing_20260704_203242.csv,2026-07-04 20:32:49.687828,14.0,30.0,None,None,None,,07A,2.0014
42,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_trade_summary_by_bucket_20260704_203242.csv,2026-07-04 20:32:49.686664,14.0,19.0,None,None,None,,07A,2.0014
43,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_prior_front_middle_candidate_comparison_20260704_203242.csv,2026-07-04 20:32:49.684666,10.0,36.0,None,None,None,,07A,2.0010
44,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_common_row_metrics_by_bucket_vs_existing_20260704_203242.csv,2026-07-04 20:32:49.677663,6.0,36.0,None,None,None,,07A,2.0006
45,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_common_row_metrics_by_bucket_20260704_203242.csv,2026-07-04 20:32:49.671527,6.0,20.0,None,None,None,,07A,2.0006
46,C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1\09S_core_secondary_consistent_secondary_locked_rules_wide_20260705_221829.parquet,2026-07-05 22:18:29.119090,5.0,19.0,None,None,None,signal_layer,core_secondary_consistent_secondary,2.0005
47,C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\09S_core_secondary_consistent_secondary_locked_rules_wide_20260705_221829.csv,2026-07-05 22:18:29.112243,5.0,19.0,None,None,None,signal_layer,core_secondary_consistent_secondary,2.0005
48,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_model_recommendation_20260704_203242.csv,2026-07-04 20:32:49.691828,3.0,21.0,None,None,None,,07A,2.0003
49,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_diagnostic_core_thresholds_used_20260704_203242.csv,2026-07-04 20:32:49.690829,3.0,6.0,None,None,None,,07A,2.0003
50,C:\Users\patri\vrp_project\data\audit\vrp_front_middle_corsi_forecast_repair_v1\07A_overall_recommendation_20260704_203242.csv,2026-07-04 20:32:49.692833,1.0,3.0,None,None,None,,07A,2.0001
51,C:\Users\patri\vrp_project\data\audit\locked_2621_constant_1mm_nav_cumulative_pnl_summary_v0_1.csv,2026-07-03 12:09:02.622724,1.0,16.0,None,None,None,,cumulative_pnl,2.0001

In [3]:
from pathlib import Path
import json
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", None)

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

FORECAST_PANEL_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1"
    r"\07A_unified_fds_no_min_return_oos_forecast_panel_20200102_20260701_20260704_203242.parquet"
)

SIGNAL_RULES_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1"
    r"\09S_core_secondary_consistent_secondary_locked_rules_long_20260705_221829.parquet"
)

SIZING_RULES_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1"
    r"\15S_final_one_trade_per_day_naked_put_sizing_lock_rules_20260706_142800.parquet"
)

SELECTION_RULE_PATH = Path(
    r"C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1"
    r"\15S_final_one_trade_per_day_naked_put_selection_rule_20260706_142800.json"
)

RV21D_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\market_data\spy_realized_vol_history_v1.parquet"
)

paths = {
    "forecast_panel": FORECAST_PANEL_PATH,
    "signal_rules": SIGNAL_RULES_PATH,
    "sizing_rules": SIZING_RULES_PATH,
    "selection_rule": SELECTION_RULE_PATH,
    "rv21d": RV21D_PATH,
}

print("=" * 100)
print("Source file existence check")
print("=" * 100)

for name, path in paths.items():
    print(f"{name:20s} exists={path.exists()}  path={path}")

missing = [name for name, path in paths.items() if not path.exists()]
if missing:
    raise FileNotFoundError(f"Missing source files: {missing}")

# ======================================================================================
# Load sources
# ======================================================================================

forecast = pd.read_parquet(FORECAST_PANEL_PATH)
signal_rules = pd.read_parquet(SIGNAL_RULES_PATH)
sizing_rules = pd.read_parquet(SIZING_RULES_PATH)
rv21d = pd.read_parquet(RV21D_PATH)

with open(SELECTION_RULE_PATH, "r", encoding="utf-8") as f:
    selection_rule = json.load(f)

# Normalize dates for inspection
for df_name, df in [
    ("forecast", forecast),
    ("rv21d", rv21d),
]:
    if "trade_date" in df.columns:
        df["trade_date"] = pd.to_datetime(df["trade_date"], errors="coerce")

# ======================================================================================
# Basic summaries
# ======================================================================================

def summarize_panel(name, df):
    print("\n" + "=" * 100)
    print(name)
    print("=" * 100)
    print(f"Rows: {len(df):,}")
    print(f"Cols: {len(df.columns):,}")
    
    if "trade_date" in df.columns:
        d = pd.to_datetime(df["trade_date"], errors="coerce")
        print(f"Date range: {d.min().date()} to {d.max().date()}")
        print(f"Unique dates: {d.nunique():,}")
    
    if "tenor" in df.columns:
        try:
            tenors = sorted(pd.Series(df["tenor"]).dropna().astype(int).unique().tolist())
        except Exception:
            tenors = sorted(pd.Series(df["tenor"]).dropna().astype(str).unique().tolist())
        print(f"Tenors: {tenors}")
        print(f"Unique tenors: {len(tenors)}")
    
    print("\nColumns:")
    for c in df.columns:
        print(f"  {c}")

summarize_panel("FORECAST PANEL — 07A unified FDS no-min-return OOS forecast panel", forecast)
summarize_panel("SIGNAL RULES — 09S Core/Secondary locked rules long", signal_rules)
summarize_panel("SIZING RULES — 15S final naked-put sizing lock rules", sizing_rules)
summarize_panel("RV21D — canonical SPY realized-vol history", rv21d)

print("\n" + "=" * 100)
print("SELECTION RULE JSON")
print("=" * 100)
print(json.dumps(selection_rule, indent=2)[:5000])

# ======================================================================================
# Forecast panel contract checks
# ======================================================================================

print("\n" + "=" * 100)
print("Forecast panel contract checks")
print("=" * 100)

required_forecast_cols = [
    "trade_date",
    "tenor",
    "implied_variance",
    "vix_style_vol",
    "forecast_variance_candidate",
    "predicted_log_variance_candidate",
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14",
]

forecast_col_check = pd.DataFrame({
    "column": required_forecast_cols,
    "exists": [c in forecast.columns for c in required_forecast_cols],
})

display(forecast_col_check)

if not forecast_col_check["exists"].all():
    missing = forecast_col_check.loc[~forecast_col_check["exists"], "column"].tolist()
    raise RuntimeError(f"Forecast panel missing required columns: {missing}")

# One row per trade_date x tenor?
dup_mask = forecast.duplicated(["trade_date", "tenor"], keep=False)
dup_count = int(dup_mask.sum())

tenor_counts = (
    forecast.groupby("trade_date")["tenor"]
    .nunique()
    .reset_index(name="unique_tenors")
)

print(f"Duplicate trade_date x tenor rows: {dup_count:,}")
print("\nTenor count distribution by date:")
display(tenor_counts["unique_tenors"].value_counts().sort_index().reset_index().rename(
    columns={"index": "unique_tenors", "unique_tenors": "date_count"}
))

if dup_count > 0:
    print("\nSample duplicate rows:")
    display(
        forecast.loc[
            dup_mask,
            [
                "trade_date",
                "tenor",
                "implied_variance",
                "forecast_variance_candidate",
                "model_vrp_log",
                "model_vrp_z_3m",
                "model_vrp_z_1y",
                "RSI14",
            ],
        ]
        .sort_values(["trade_date", "tenor"])
        .head(50)
    )

# Expected tenor grid
expected_tenors = [9, 12, 15, 18, 21, 24, 27, 30, 33]

actual_tenors = sorted(forecast["tenor"].dropna().astype(int).unique().tolist())
print(f"\nExpected tenors: {expected_tenors}")
print(f"Actual tenors:   {actual_tenors}")

# Reconstruct forecast vol and model_vrp_log
calc = forecast.copy()

calc["forecast_vol_recalc"] = np.sqrt(calc["forecast_variance_candidate"]) * 100.0
calc["model_vrp_log_recalc"] = np.log(calc["implied_variance"] / calc["forecast_variance_candidate"])

calc["forecast_vol_recalc_finite"] = np.isfinite(calc["forecast_vol_recalc"])
calc["model_vrp_log_diff"] = calc["model_vrp_log"] - calc["model_vrp_log_recalc"]

print("\nForecast variance checks:")
print("forecast_variance_candidate positive:",
      bool((calc["forecast_variance_candidate"] > 0).all()))
print("implied_variance positive:",
      bool((calc["implied_variance"] > 0).all()))
print("forecast_vol_recalc finite:",
      bool(calc["forecast_vol_recalc_finite"].all()))

print("\nmodel_vrp_log reconstruction error:")
display(
    calc["model_vrp_log_diff"]
    .abs()
    .describe(percentiles=[0.5, 0.9, 0.99, 0.999])
    .to_frame("abs_diff")
)

bad_vrp = calc[calc["model_vrp_log_diff"].abs() > 1e-10]

print(f"Rows where model_vrp_log differs from log(implied/forecast) by > 1e-10: {len(bad_vrp):,}")

if len(bad_vrp) > 0:
    display(
        bad_vrp[
            [
                "trade_date",
                "tenor",
                "implied_variance",
                "forecast_variance_candidate",
                "model_vrp_log",
                "model_vrp_log_recalc",
                "model_vrp_log_diff",
            ]
        ].head(50)
    )

# ======================================================================================
# RV21D join inspection
# ======================================================================================

print("\n" + "=" * 100)
print("RV21D join inspection")
print("=" * 100)

required_rv_cols = ["trade_date", "spy_close", "rv21d_vol_pct"]

rv_col_check = pd.DataFrame({
    "column": required_rv_cols,
    "exists": [c in rv21d.columns for c in required_rv_cols],
})

display(rv_col_check)

if not rv_col_check["exists"].all():
    missing = rv_col_check.loc[~rv_col_check["exists"], "column"].tolist()
    raise RuntimeError(f"RV21D file missing required columns: {missing}")

rv_join = forecast[["trade_date", "tenor"]].drop_duplicates().merge(
    rv21d[["trade_date", "spy_close", "rv21d_vol_pct"]],
    on="trade_date",
    how="left",
)

missing_rv = rv_join["rv21d_vol_pct"].isna().sum()

print(f"Forecast date-tenor rows: {len(rv_join):,}")
print(f"Missing rv21d after join: {missing_rv:,}")

if missing_rv > 0:
    print("\nMissing RV21D sample:")
    display(rv_join[rv_join["rv21d_vol_pct"].isna()].head(50))

print("\nLatest joined RV21D rows:")
display(
    rv_join.sort_values(["trade_date", "tenor"])
    .tail(18)
)

# ======================================================================================
# Signal rules and sizing rules inspection
# ======================================================================================

print("\n" + "=" * 100)
print("Signal rules inspection")
print("=" * 100)

display(signal_rules.head(50))

print("\nSignal rules columns:")
for c in signal_rules.columns:
    print(f"  {c}")

print("\n" + "=" * 100)
print("Sizing rules inspection")
print("=" * 100)

display(sizing_rules.head(50))

print("\nSizing rules columns:")
for c in sizing_rules.columns:
    print(f"  {c}")

# Guess likely sizing columns
possible_size_cols = [
    c for c in sizing_rules.columns
    if any(x in c.lower() for x in ["size", "sizing", "locked"])
]

print("\nPossible sizing columns:")
print(possible_size_cols)

# ======================================================================================
# Suggested source contract summary
# ======================================================================================

print("\n" + "=" * 100)
print("Suggested final source contract summary")
print("=" * 100)

summary = {
    "forecast_panel_path": str(FORECAST_PANEL_PATH),
    "forecast_rows": int(len(forecast)),
    "forecast_min_date": str(forecast["trade_date"].min().date()),
    "forecast_max_date": str(forecast["trade_date"].max().date()),
    "forecast_tenors": actual_tenors,
    "forecast_duplicate_trade_date_tenor_rows": dup_count,
    "rv21d_path": str(RV21D_PATH),
    "rv21d_rows": int(len(rv21d)),
    "rv21d_min_date": str(rv21d["trade_date"].min().date()),
    "rv21d_max_date": str(rv21d["trade_date"].max().date()),
    "missing_rv21d_after_join": int(missing_rv),
    "signal_rules_path": str(SIGNAL_RULES_PATH),
    "signal_rules_rows": int(len(signal_rules)),
    "sizing_rules_path": str(SIZING_RULES_PATH),
    "sizing_rules_rows": int(len(sizing_rules)),
    "selection_rule_path": str(SELECTION_RULE_PATH),
}

print(json.dumps(summary, indent=2))

====================================================================================================
Source file existence check
====================================================================================================
forecast_panel       exists=True  path=C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_fds_no_min_return_oos_forecast_panel_20200102_20260701_20260704_203242.parquet
signal_rules         exists=True  path=C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1\09S_core_secondary_consistent_secondary_locked_rules_long_20260705_221829.parquet
sizing_rules         exists=True  path=C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_sizing_lock_rules_20260706_142800.parquet
selection_rule       exists=True  path=C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_selection_rule_20260706_142800.json
rv21d                exists=True  path=C:\Users\patri\vrp_project\data\processed\market_data\spy_realized_vol_history_v1.parquet

====================================================================================================
FORECAST PANEL — 07A unified FDS no-min-return OOS forecast panel
====================================================================================================
Rows: 31,140
Cols: 89
Date range: 2019-01-02 to 2026-07-01
Unique dates: 1,884
Tenors: [9, 12, 15, 18, 21, 24, 27, 30, 33]
Unique tenors: 9

Columns:
  trade_date
  date
  tenor
  target_log_variance
  last_forward_rv_date
  forward_realized_variance_corsi
  log_forward_realized_variance_corsi
  log_rv_1d
  log_rv_std_5d
  log_rv_std_21d
  log_rv_std_63d
  log_downside_rv_5d
  log_downside_rv_21d
  log_downside_rv_63d
  downside_share_21d
  negative_return_count_21d
  forecast_variance_har_downside_v1
  forecast_vol_har_downside_v1
  predicted_log_variance_har_downside_v1
  implied_variance
  vix_style_vol
  fit_status
  selected_alpha
  train_rows_used
  test_year
  tenor_bucket
  model_vrp_log
  model_vrp_z_3m
  model_vrp_z_1y
  RSI14
  actual_dte
  win
  normalized_pnl_dollars
  normalized_pnl_pct
  entry_credit_points
  short_option_pnl_points
  is_research_tenor
  is_back_frozen
  forecast_repair_scope
  target_realized_variance
  baseline_forecast_variance
  baseline_forecast_vol_pct
  target_realized_vol_pct
  baseline_log_error_pred_minus_actual
  baseline_underforecast_flag
  baseline_actual_to_forecast_var_ratio
  target_window_overlaps_trade_date
  target_window_missing
  spx_close_for_features
  spx_log_return
  candidate_log_rv_2d
  candidate_log_rv_3d
  candidate_log_rv_5d
  candidate_log_rv_10d
  candidate_log_rv_21d
  candidate_log_rv_63d
  candidate_log_downside_rv_2d
  candidate_log_downside_rv_3d
  candidate_log_downside_rv_5d
  candidate_log_downside_rv_10d
  candidate_log_downside_rv_21d
  candidate_log_downside_rv_63d
  candidate_abs_return_1d
  candidate_max_abs_return_3d
  candidate_max_abs_return_5d
  candidate_max_abs_return_10d
  candidate_min_return_3d
  candidate_min_return_5d
  candidate_min_return_10d
  candidate_log_rv_3d_minus_21d
  candidate_log_rv_5d_minus_21d
  candidate_log_rv_10d_minus_63d
  candidate_log_downside_rv_5d_minus_21d
  candidate_log_downside_rv_10d_minus_63d
  candidate_negative_return_count_5d
  candidate_negative_return_count_10d
  candidate_downside_share_5d
  candidate_downside_share_10d
  model_spec
  model_source
  selected_alpha_candidate
  train_rows_used_candidate
  test_year_candidate
  fit_status_candidate
  predicted_log_variance_candidate
  forecast_variance_candidate
  candidate_forecast_vol_pct
  log_error_pred_minus_actual
  actual_to_forecast_var_ratio

====================================================================================================
SIGNAL RULES — 09S Core/Secondary locked rules long
====================================================================================================
Rows: 19
Cols: 33
Tenors: [12, 15, 18, 21, 24, 27, 30, 33]
Unique tenors: 8

Columns:
  stack_lock_version
  stack_lock_decision_id
  model_spec
  signal_layer
  signal_priority
  lock_version
  lock_decision_id
  supersedes_lock_version
  supersedes_lock_decision_id
  tenor
  tenor_bucket
  tenor_bucket_order
  include_tenor
  model_vrp_log_min
  model_vrp_z_3m_min
  model_vrp_z_1y_min
  RSI14_max
  rv21d_vol_pct_min
  comparison_operator_model_vrp_log
  comparison_operator_model_vrp_z_3m
  comparison_operator_model_vrp_z_1y
  comparison_operator_RSI14
  comparison_operator_rv21d_vol_pct
  vrp_measure
  forecast_model
  rv_floor_contract
  selection_rule
  source_cell
  source_candidate_id
  exclusion_reason
  created_timestamp
  supersedes_stack_lock_version
  supersedes_stack_lock_decision_id

====================================================================================================
SIZING RULES — 15S final naked-put sizing lock rules
====================================================================================================
Rows: 13
Cols: 43
Tenors: [12, 15, 18, 21, 24, 27, 30, 33]
Unique tenors: 8

Columns:
  sleeve_id
  locked_size_pct
  signal_layer
  tenor_bucket
  tenor
  model_size_pct_label
  manual_size_pct_label
  manual_minus_model_size_pct
  tail_budget_rounded_size_pct
  final_recommended_size_pct
  sizing_quality_score
  win_rate
  avg_pnl_per_day
  profit_factor_pnl_per_day
  pnl_per_day_expected_loss_1pct_positive
  worst20_loss_positive
  avg_pnl_per_day_2026
  primary_size_bottleneck
  locked_size_label
  parsed_signal_layer
  parsed_tenor_bucket
  parsed_tenor
  sizing_lock_version
  sizing_lock_decision_id
  program_type
  program_label
  signal_stack_lock_version
  signal_stack_lock_decision_id
  is_locked
  is_final_sizing_lock
  locked_at
  max_trades_per_day
  selection_primary_key
  tie_break_1
  tie_break_2
  tie_break_3
  tie_break_4
  tie_break_5
  pricing_basis_label
  not_defined_spread_sizing
  signal_layer_order
  tenor_bucket_order
  display_order

====================================================================================================
RV21D — canonical SPY realized-vol history
====================================================================================================
Rows: 2,135
Cols: 25
Date range: 2018-01-02 to 2026-07-01
Unique dates: 2,135

Columns:
  trade_date
  spy_open
  spy_high
  spy_low
  spy_close
  spy_volume
  source
  source_symbol
  source_date_column
  source_run_timestamp
  clean_run_timestamp
  final_clean_run_timestamp
  spy_log_return
  spy_rv_1d
  spy_vol_1d_pct
  spy_rv_5d
  spy_vol_5d_pct
  spy_rv_10d
  spy_vol_10d_pct
  spy_rv_21d
  spy_vol_21d_pct
  spy_rv_63d
  spy_vol_63d_pct
  rv21d_vol_pct
  rv21d_source

====================================================================================================
SELECTION RULE JSON
====================================================================================================
{
  "program_version": "final_one_trade_per_day_naked_put_sizing_locked_v1",
  "program_decision_id": "final_one_trade_per_day_naked_put_sizing_locked_001",
  "program_type": "naked_short_put_tenor_selection_and_sizing",
  "program_label": "Final one-trade-per-day naked short put sizing program",
  "max_trades_per_day": 1,
  "candidate_source": "Final Core / Secondary independent qualifying sleeves",
  "selection_steps": [
    {
      "step": 1,
      "rule": "Attach locked size to every qualifying sleeve candidate."
    },
    {
      "step": 2,
      "rule": "Select the candidate with the highest locked size."
    },
    {
      "step": 3,
      "rule": "If same locked size, Core beats Secondary."
    },
    {
      "step": 4,
      "rule": "If still tied, higher Cell 12S sizing quality score wins."
    },
    {
      "step": 5,
      "rule": "If still tied, higher sleeve win rate wins."
    },
    {
      "step": 6,
      "rule": "If still tied, lower 1% expected loss wins."
    },
    {
      "step": 7,
      "rule": "If still tied, longer DTE wins."
    }
  ],
  "not_a_defined_spread_program": true,
  "pricing_basis_note": "Current branch uses entry_credit_points from the upstream short-put candidate pricing source. Based on the Cell 14S audit output and available columns, treat the program as naked short put bid-credit based until a deeper quote-construction audit says otherwise."
}

====================================================================================================
Forecast panel contract checks
====================================================================================================

                             column  exists
0                        trade_date    True
1                             tenor    True
2                  implied_variance    True
3                     vix_style_vol    True
4       forecast_variance_candidate    True
5  predicted_log_variance_candidate    True
6                     model_vrp_log    True
7                    model_vrp_z_3m    True
8                    model_vrp_z_1y    True
9                             RSI14    True

Duplicate trade_date x tenor rows: 29,376

Tenor count distribution by date:

   date_count  count
0           7    252
1           9   1632

Sample duplicate rows:

,trade_date,tenor,implied_variance,forecast_variance_candidate,model_vrp_log,model_vrp_z_3m,model_vrp_z_1y,RSI14
1764,2020-01-02,9,0.011050,0.008121,0.308033,2.469983,1.623281,75.483183
16452,2020-01-02,9,0.011050,0.008154,0.308033,2.469983,1.623281,75.483183
1765,2020-01-02,12,0.012187,0.009070,0.295337,2.683891,1.694199,75.483183
18084,2020-01-02,12,0.012187,0.009013,0.295337,2.683891,1.694199,75.483183
1766,2020-01-02,15,0.012860,0.010899,0.165473,3.569221,2.126314,75.483183
19716,2020-01-02,15,0.012860,0.010799,0.165473,3.569221,2.126314,75.483183
1767,2020-01-02,18,0.013239,0.011652,0.127681,4.609155,2.381386,75.483183
21348,2020-01-02,18,0.013239,0.011473,0.127681,4.609155,2.381386,75.483183
1768,2020-01-02,21,0.013509,0.012913,0.045141,4.772079,2.386813,75.483183
22980,2020-01-02,21,0.013509,0.012752,0.045141,4.772079,2.386813,75.483183
1769,2020-01-02,24,0.014163,0.013624,0.038741,4.734995,2.302298,75.483183
24612,2020-01-02,24,0.014163,0.013507,0.038741,4.734995,2.302298,75.483183
1770,2020-01-02,27,0.014872,0.014635,0.016044,4.471784,2.231622,75.483183
26244,2020-01-02,27,0.014872,0.014456,0.016044,4.471784,2.231622,75.483183
1771,2020-01-02,30,0.015482,0.016487,-0.062855,NaN,NaN,75.483183
27876,2020-01-02,30,0.015482,0.015641,-0.062855,NaN,NaN,75.483183
1772,2020-01-02,33,0.016062,0.017896,-0.108109,NaN,NaN,75.483183
29508,2020-01-02,33,0.016062,0.015978,-0.108109,NaN,NaN,75.483183
1773,2020-01-03,9,0.016851,0.008864,0.642397,2.931604,2.117419,65.738991
16453,2020-01-03,9,0.016851,0.010528,0.642397,2.931604,2.117419,65.738991
1774,2020-01-03,12,0.017392,0.009848,0.568787,3.035715,2.098811,65.738991
18085,2020-01-03,12,0.017392,0.011360,0.568787,3.035715,2.098811,65.738991
1775,2020-01-03,15,0.017795,0.011739,0.415994,3.879557,2.594436,65.738991
19717,2020-01-03,15,0.017795,0.013368,0.415994,3.879557,2.594436,65.738991
1776,2020-01-03,18,0.018153,0.012458,0.376484,4.767208,2.886981,65.738991
21349,2020-01-03,18,0.018153,0.013959,0.376484,4.767208,2.886981,65.738991
1777,2020-01-03,21,0.018409,0.013710,0.294715,4.923121,2.919286,65.738991
22981,2020-01-03,21,0.018409,0.015252,0.294715,4.923121,2.919286,65.738991
1778,2020-01-03,24,0.019191,0.014429,0.285202,4.810095,2.788136,65.738991
24613,2020-01-03,24,0.019191,0.015959,0.285202,4.810095,2.788136,65.738991
1779,2020-01-03,27,0.019799,0.015461,0.247310,4.597748,2.690014,65.738991
26245,2020-01-03,27,0.019799,0.016850,0.247310,4.597748,2.690014,65.738991
1780,2020-01-03,30,0.020285,0.018428,0.096040,NaN,NaN,65.738991
27877,2020-01-03,30,0.020285,0.018187,0.096040,NaN,NaN,65.738991
1781,2020-01-03,33,0.020682,0.019834,0.041881,NaN,NaN,65.738991
29509,2020-01-03,33,0.020682,0.018456,0.041881,NaN,NaN,65.738991
1782,2020-01-06,9,0.015154,0.008893,0.533024,2.539225,1.939086,67.953032
16454,2020-01-06,9,0.015154,0.010440,0.533024,2.539225,1.939086,67.953032
1783,2020-01-06,12,0.015421,0.009891,0.444151,2.589025,1.896861,67.953032
18086,2020-01-06,12,0.015421,0.011265,0.444151,2.589025,1.896861,67.953032
1784,2020-01-06,15,0.015746,0.011889,0.281028,3.147403,2.317238,67.953032
19718,2020-01-06,15,0.015746,0.013256,0.281028,3.147403,2.317238,67.953032
1785,2020-01-06,18,0.015963,0.012656,0.232122,3.684027,2.572012,67.953032
21350,2020-01-06,18,0.015963,0.013851,0.232122,3.684027,2.572012,67.953032
1786,2020-01-06,21,0.016924,0.014006,0.189215,3.865109,2.677929,67.953032
22982,2020-01-06,21,0.016924,0.015141,0.189215,3.865109,2.677929,67.953032
1787,2020-01-06,24,0.017645,0.014827,0.173988,3.800360,2.552042,67.953032
24614,2020-01-06,24,0.017645,0.015852,0.173988,3.800360,2.552042,67.953032
1788,2020-01-06,27,0.018258,0.015934,0.136112,3.680510,2.456431,67.953032
26246,2020-01-06,27,0.018258,0.016725,0.136112,3.680510,2.456431,67.953032

Expected tenors: [9, 12, 15, 18, 21, 24, 27, 30, 33]
Actual tenors:   [9, 12, 15, 18, 21, 24, 27, 30, 33]

Forecast variance checks:
forecast_variance_candidate positive: True
implied_variance positive: True
forecast_vol_recalc finite: True

model_vrp_log reconstruction error:

           abs_diff
count  31140.000000
mean       0.082304
std        0.169618
min        0.000000
50%        0.000000
90%        0.242892
99%        0.704221
99.9%      1.943374
max        2.596017

Rows where model_vrp_log differs from log(implied/forecast) by > 1e-10: 14,688

,trade_date,tenor,implied_variance,forecast_variance_candidate,model_vrp_log,model_vrp_log_recalc,model_vrp_log_diff
16452,2020-01-02,9,0.011050,0.008154,0.308033,0.303980,0.004053
16453,2020-01-03,9,0.016851,0.010528,0.642397,0.470342,0.172056
16454,2020-01-06,9,0.015154,0.010440,0.533024,0.372603,0.160421
16455,2020-01-07,9,0.014890,0.010327,0.487150,0.365936,0.121214
16456,2020-01-08,9,0.016191,0.009610,0.572555,0.521592,0.050964
16457,2020-01-09,9,0.012087,0.009513,0.378664,0.239505,0.139158
16458,2020-01-10,9,0.011347,0.008714,0.429082,0.264020,0.165062
16459,2020-01-13,9,0.010295,0.008375,0.295742,0.206349,0.089393
16460,2020-01-14,9,0.011051,0.007754,0.346700,0.354413,-0.007713
16461,2020-01-15,9,0.009610,0.007818,0.213464,0.206437,0.007027
16462,2020-01-16,9,0.009283,0.007968,0.136552,0.152758,-0.016206
16463,2020-01-17,9,0.008271,0.006507,0.150558,0.239938,-0.089380
16464,2020-01-21,9,0.013095,0.007103,0.527204,0.611730,-0.084526
16465,2020-01-22,9,0.011973,0.006541,0.492836,0.604641,-0.111805
16466,2020-01-23,9,0.013223,0.006502,0.566707,0.709846,-0.143139
16467,2020-01-24,9,0.022580,0.012873,0.764033,0.561928,0.202105
16468,2020-01-27,9,0.044543,0.022299,1.095653,0.691912,0.403741
16469,2020-01-28,9,0.034498,0.019784,0.785759,0.556027,0.229732
16470,2020-01-29,9,0.033638,0.019777,0.740592,0.531165,0.209427
16471,2020-01-30,9,0.028664,0.018671,0.632052,0.428690,0.203362
16472,2020-01-31,9,0.047490,0.025694,0.848870,0.614250,0.234620
16473,2020-02-03,9,0.036392,0.023389,0.638421,0.442091,0.196330
16474,2020-02-04,9,0.025770,0.020436,0.378936,0.231931,0.147005
16475,2020-02-05,9,0.018791,0.018680,0.074187,0.005915,0.068272
16476,2020-02-06,9,0.016447,0.018624,0.020016,-0.124306,0.144321
16477,2020-02-07,9,0.019138,0.014440,0.307070,0.281648,0.025422
16478,2020-02-10,9,0.017096,0.012633,0.191361,0.302505,-0.111143
16479,2020-02-11,9,0.016688,0.012666,0.306006,0.275761,0.030245
16480,2020-02-12,9,0.012100,0.012354,0.018743,-0.020711,0.039454
16481,2020-02-13,9,0.014677,0.012494,0.212671,0.161041,0.051630
16482,2020-02-14,9,0.012321,0.007921,0.222206,0.441779,-0.219573
16483,2020-02-18,9,0.016850,0.008518,0.408323,0.682141,-0.273818
16484,2020-02-19,9,0.014580,0.008317,0.234079,0.561371,-0.327292
16485,2020-02-20,9,0.018629,0.009886,0.479234,0.633627,-0.154393
16486,2020-02-21,9,0.026470,0.016504,0.534905,0.472439,0.062466
16487,2020-02-24,9,0.101088,0.053002,1.271920,0.645659,0.626261
16488,2020-02-25,9,0.137696,0.058242,1.450451,0.860435,0.590016
16489,2020-02-26,9,0.121288,0.058328,1.402481,0.732092,0.670389
16490,2020-02-27,9,0.259345,0.091266,1.887542,1.044383,0.843159
16491,2020-02-28,9,0.279841,0.091423,1.979081,1.118722,0.860360
16492,2020-03-02,9,0.146099,0.067485,1.262143,0.772386,0.489757
16493,2020-03-03,9,0.227350,0.069457,1.688785,1.185779,0.503006
16494,2020-03-04,9,0.128777,0.061461,1.123347,0.739676,0.383672
16495,2020-03-05,9,0.234953,0.060339,1.646067,1.359414,0.286653
16496,2020-03-06,9,0.220911,0.061481,1.514820,1.279028,0.235792
16497,2020-03-09,9,0.491322,0.257571,2.007314,0.645802,1.361512
16498,2020-03-10,9,0.282300,0.226386,1.508501,0.220728,1.287773
16499,2020-03-11,9,0.460422,0.252905,1.918874,0.599130,1.319744
16500,2020-03-12,9,1.072467,0.567697,2.513078,0.636129,1.876949
16501,2020-03-13,9,0.417767,0.476319,1.555363,-0.131164,1.686527

====================================================================================================
RV21D join inspection
====================================================================================================

          column  exists
0     trade_date    True
1      spy_close    True
2  rv21d_vol_pct    True

Forecast date-tenor rows: 16,452
Missing rv21d after join: 0

Latest joined RV21D rows:

      trade_date  tenor  spy_close  rv21d_vol_pct
16434 2026-06-30      9     746.77      17.726787
16435 2026-06-30     12     746.77      17.726787
16436 2026-06-30     15     746.77      17.726787
16437 2026-06-30     18     746.77      17.726787
16438 2026-06-30     21     746.77      17.726787
16439 2026-06-30     24     746.77      17.726787
16440 2026-06-30     27     746.77      17.726787
16441 2026-06-30     30     746.77      17.726787
16442 2026-06-30     33     746.77      17.726787
16443 2026-07-01      9     745.76      17.686351
16444 2026-07-01     12     745.76      17.686351
16445 2026-07-01     15     745.76      17.686351
16446 2026-07-01     18     745.76      17.686351
16447 2026-07-01     21     745.76      17.686351
16448 2026-07-01     24     745.76      17.686351
16449 2026-07-01     27     745.76      17.686351
16450 2026-07-01     30     745.76      17.686351
16451 2026-07-01     33     745.76      17.686351

====================================================================================================
Signal rules inspection
====================================================================================================

,stack_lock_version,stack_lock_decision_id,model_spec,signal_layer,signal_priority,lock_version,lock_decision_id,supersedes_lock_version,supersedes_lock_decision_id,tenor,tenor_bucket,tenor_bucket_order,include_tenor,model_vrp_log_min,model_vrp_z_3m_min,model_vrp_z_1y_min,RSI14_max,rv21d_vol_pct_min,comparison_operator_model_vrp_log,comparison_operator_model_vrp_z_3m,comparison_operator_model_vrp_z_1y,comparison_operator_RSI14,comparison_operator_rv21d_vol_pct,vrp_measure,forecast_model,rv_floor_contract,selection_rule,source_cell,source_candidate_id,exclusion_reason,created_timestamp,supersedes_stack_lock_version,supersedes_stack_lock_decision_id
0,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Core,1,core_middle_back_only_locked_v1,core_middle_back_only_locked_001,core_repaired_v1,core_repaired_v1_locked_001,12,Front,1,False,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 7S — Front taxonomy architecture review,C_revised_front_as_secondary_stack,Core Front removed after Cell 7S architecture review. Front exposure is handled by Secondary Front only.,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
1,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Core,1,core_middle_back_only_locked_v1,core_middle_back_only_locked_001,core_repaired_v1,core_repaired_v1_locked_001,15,Front,1,False,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 7S — Front taxonomy architecture review,C_revised_front_as_secondary_stack,Core Front removed after Cell 7S architecture review. Front exposure is handled by Secondary Front only.,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
2,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Core,1,core_middle_back_only_locked_v1,core_middle_back_only_locked_001,core_repaired_v1,core_repaired_v1_locked_001,18,Front,1,False,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 7S — Front taxonomy architecture review,C_revised_front_as_secondary_stack,Core Front removed after Cell 7S architecture review. Front exposure is handled by Secondary Front only.,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
3,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Core,1,core_middle_back_only_locked_v1,core_middle_back_only_locked_001,core_repaired_v1,core_repaired_v1_locked_001,21,Middle,2,True,0.65,0.7,0.7,70.0,8.5,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 11R — Core repaired v1 lock; taxonomy revised by Cell 7S,core_repaired_v1_locked_001,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
4,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Core,1,core_middle_back_only_locked_v1,core_middle_back_only_locked_001,core_repaired_v1,core_repaired_v1_locked_001,24,Middle,2,True,0.65,0.7,0.7,70.0,8.5,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 11R — Core repaired v1 lock; taxonomy revised by Cell 7S,core_repaired_v1_locked_001,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
5,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Core,1,core_middle_back_only_locked_v1,core_middle_back_only_locked_001,core_repaired_v1,core_repaired_v1_locked_001,27,Back,3,True,0.70,0.7,0.7,70.0,8.5,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 11R — Core repaired v1 lock; taxonomy revised by Cell 7S,core_repaired_v1_locked_001,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
6,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Core,1,core_middle_back_only_locked_v1,core_middle_back_only_locked_001,core_repaired_v1,core_repaired_v1_locked_001,30,Back,3,True,0.70,0.7,0.7,70.0,8.5,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 11R — Core repaired v1 lock; taxonomy revised by Cell 7S,core_repaired_v1_locked_001,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
7,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Core,1,core_middle_back_only_locked_v1,core_middle_back_only_locked_001,core_repaired_v1,core_repaired_v1_locked_001,33,Back,3,True,0.70,0.7,0.7,70.0,8.5,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 11R — Core repaired v1 lock; taxonomy revised by Cell 7S,core_repaired_v1_locked_001,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
8,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Secondary,2,secondary_consistent_front_middle_back_locked_v1,secondary_consistent_front_middle_back_locked_001,secondary_front_middle_back_locked_v1,secondary_front_middle_back_locked_001,12,Front,1,True,0.65,0.2,0.2,75.0,7.0,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 22R-FIX — Tertiary Front Combined Comparison Repair; Cell 7S — Front taxonomy architecture review; carried forward by Cell 9S consistency fix,promoted_from_tertiary_front_LOG065_Z020_RSI75_RV70,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
9,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Secondary,2,secondary_consistent_front_middle_back_locked_v1,secondary_consistent_front_middle_back_locked_001,secondary_front_middle_back_locked_v1,secondary_front_middle_back_locked_001,15,Front,1,True,0.65,0.2,0.2,75.0,7.0,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 22R-FIX — Tertiary Front Combined Comparison Repair; Cell 7S — Front taxonomy architecture review; carried forward by Cell 9S consistency fix,promoted_from_tertiary_front_LOG065_Z020_RSI75_RV70,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
10,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Secondary,2,secondary_consistent_front_middle_back_locked_v1,secondary_consistent_front_middle_back_locked_001,secondary_front_middle_back_locked_v1,secondary_front_middle_back_locked_001,18,Front,1,True,0.65,0.2,0.2,75.0,7.0,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 22R-FIX — Tertiary Front Combined Comparison Repair; Cell 7S — Front taxonomy architecture review; carried forward by Cell 9S consistency fix,promoted_from_tertiary_front_LOG065_Z020_RSI75_RV70,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
11,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Secondary,2,secondary_consistent_front_middle_back_locked_v1,secondary_consistent_front_middle_back_locked_001,secondary_front_middle_back_locked_v1,secondary_front_middle_back_locked_001,21,Middle,2,True,0.65,0.2,0.2,76.0,7.0,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 9S — Secondary consistency fix,secondary_middle_LOG065_Z020_consistency_fix,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
12,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Secondary,2,secondary_consistent_front_middle_back_locked_v1,secondary_consistent_front_middle_back_locked_001,secondary_front_middle_back_locked_v1,secondary_front_middle_back_locked_001,24,Middle,2,True,0.65,0.2,0.2,76.0,7.0,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 9S — Secondary consistency fix,secondary_middle_LOG065_Z020_consistency_fix,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
13,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Secondary,2,secondary_consistent_front_middle_back_locked_v1,secondary_consistent_front_middle_back_locked_001,secondary_front_middle_back_locked_v1,secondary_front_middle_back_locked_001,27,Back,3,True,0.65,0.0,0.0,77.0,6.5,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 20R — Secondary Frequency Unlock Confirmation; taxonomy revised by Cell 7S; carried forward by Cell 9S consistency fix,secondary_confirm_pair_0028__BEST_SIGNAL_RANK,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
14,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Secondary,2,secondary_consistent_front_middle_back_locked_v1,secondary_consistent_front_middle_back_locked_001,secondary_front_middle_back_locked_v1,secondary_front_middle_back_locked_001,30,Back,3,True,0.65,0.0,0.0,77.0,6.5,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 20R — Secondary Frequency Unlock Confirmation; taxonomy revised by Cell 7S; carried forward by Cell 9S consistency fix,secondary_confirm_pair_0028__BEST_SIGNAL_RANK,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
15,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Secondary,2,secondary_consistent_front_middle_back_locked_v1,secondary_consistent_front_middle_back_locked_001,secondary_front_middle_back_locked_v1,secondary_front_middle_back_locked_001,33,Back,3,True,0.65,0.0,0.0,77.0,6.5,>,>,>,<,>,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 20R — Secondary Frequency Unlock Confirmation; taxonomy revised by Cell 7S; carried forward by Cell 9S consistency fix,secondary_confirm_pair_0028__BEST_SIGNAL_RANK,None,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
16,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Tertiary,3,tertiary_removed_inactive_v1,tertiary_removed_inactive_001,tertiary_front_cleaner_quality_locked_v1,tertiary_front_cleaner_quality_locked_001,12,Front,1,False,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 7S — Front taxonomy architecture review,C_revised_front_as_secondary_stack,Tertiary layer removed after Cell 7S architecture review. Former Tertiary Front is promoted to Secondary Front.,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001
17,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,unified_fds_no_min_return,Tertiary,3,tertiary_removed_inactive_v1,tertiary_removed_inactive_001,tertiary_front_cleaner_quality_locked_v1,tertiary_front_cleaner_quality_locked_001,15,Front,1,False,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,model_vrp_log = log(implied_variance / forecast_variance),har_total_simple / unified_fds_no_min_return,rv21d_vol_pct > threshold,"Core Middle/Back first. If any locked Core Middle/Back tenor qualifies on a date, select Core and ignore Secondary. If no Core tenor qualifies, evaluate Secondary Front/Middle/Back. If multiple Secondary tenors qualify, select by BEST_SIGNAL_RANK. No active Tertiary layer.",Cell 7S — Front taxonomy architecture review,C_revised_front_as_secondary_stack,Tertiary layer removed after Cell 7S architecture review. Former Tertiary Front is promoted to Secondary Front.,20260705_221829,core_secondary_front_taxonomy_signal_stack_locked_v1,core_secondary_front_taxonomy_signal_stack_locked_001

Signal rules columns:
  stack_lock_version
  stack_lock_decision_id
  model_spec
  signal_layer
  signal_priority
  lock_version
  lock_decision_id
  supersedes_lock_version
  supersedes_lock_decision_id
  tenor
  tenor_bucket
  tenor_bucket_order
  include_tenor
  model_vrp_log_min
  model_vrp_z_3m_min
  model_vrp_z_1y_min
  RSI14_max
  rv21d_vol_pct_min
  comparison_operator_model_vrp_log
  comparison_operator_model_vrp_z_3m
  comparison_operator_model_vrp_z_1y
  comparison_operator_RSI14
  comparison_operator_rv21d_vol_pct
  vrp_measure
  forecast_model
  rv_floor_contract
  selection_rule
  source_cell
  source_candidate_id
  exclusion_reason
  created_timestamp
  supersedes_stack_lock_version
  supersedes_stack_lock_decision_id

====================================================================================================
Sizing rules inspection
====================================================================================================

,sleeve_id,locked_size_pct,signal_layer,tenor_bucket,tenor,model_size_pct_label,manual_size_pct_label,manual_minus_model_size_pct,tail_budget_rounded_size_pct,final_recommended_size_pct,sizing_quality_score,win_rate,avg_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_expected_loss_1pct_positive,worst20_loss_positive,avg_pnl_per_day_2026,primary_size_bottleneck,locked_size_label,parsed_signal_layer,parsed_tenor_bucket,parsed_tenor,sizing_lock_version,sizing_lock_decision_id,program_type,program_label,signal_stack_lock_version,signal_stack_lock_decision_id,is_locked,is_final_sizing_lock,locked_at,max_trades_per_day,selection_primary_key,tie_break_1,tie_break_2,tie_break_3,tie_break_4,tie_break_5,pricing_basis_label,not_defined_spread_sizing,signal_layer_order,tenor_bucket_order,display_order
0,Core_Middle_21D,0.0350,Core,Middle,21,3.50%,3.50%,0.0000,0.0350,0.0350,0.791050,0.849315,582.804165,3.813833,3935.354296,12713.840942,-63.750780,worst_trade,3.50%,Core,Middle,21,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,1,2,1
1,Core_Middle_24D,0.0425,Core,Middle,24,4.25%,4.25%,0.0000,0.0425,0.0425,0.789258,0.851351,522.835118,3.814531,3122.894260,10768.622387,-4.426712,quality_cap,4.25%,Core,Middle,24,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,1,2,2
2,Core_Back_27D,0.0450,Core,Back,27,4.50%,4.50%,0.0000,0.0450,0.0450,0.850288,0.875000,567.163740,4.335512,3429.035282,5706.090687,154.602927,quality_cap,4.50%,Core,Back,27,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,1,3,3
3,Core_Back_30D,0.0475,Core,Back,30,5.00%,4.75%,-0.0025,0.0500,0.0475,0.924325,0.902985,600.006302,5.756158,3270.987604,1174.786905,255.213286,max_size_cap,4.75%,Core,Back,30,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,1,3,4
4,Core_Back_33D,0.0500,Core,Back,33,5.00%,5.00%,0.0000,0.0500,0.0500,0.942536,0.926471,610.808698,8.306366,2478.940162,0.000000,358.706507,max_size_cap,5.00%,Core,Back,33,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,1,3,5
5,Secondary_Front_12D,0.0150,Secondary,Front,12,1.50%,1.50%,0.0000,0.0150,0.0150,0.444253,0.779661,352.413327,1.725481,8265.349476,27863.104003,-232.559072,1pct_expected_loss,1.50%,Secondary,Front,12,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,2,1,6
6,Secondary_Front_15D,0.0200,Secondary,Front,15,2.00%,2.00%,0.0000,0.0200,0.0200,0.563784,0.795556,456.246988,2.243698,6625.789218,22649.524964,-255.910828,1pct_expected_loss,2.00%,Secondary,Front,15,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,2,1,7
7,Secondary_Front_18D,0.0275,Secondary,Front,18,3.00%,2.75%,-0.0025,0.0300,0.0275,0.616805,0.805085,437.899405,2.597047,5205.437870,17284.664317,-103.890230,worst_trade,2.75%,Secondary,Front,18,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,2,1,8
8,Secondary_Middle_21D,0.0350,Secondary,Middle,21,3.75%,3.50%,-0.0025,0.0375,0.0350,0.637433,0.800885,431.606391,2.654362,3746.893390,12944.532018,93.735045,quality_cap,3.50%,Secondary,Middle,21,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,2,2,9
9,Secondary_Middle_24D,0.0375,Secondary,Middle,24,3.75%,3.75%,0.0000,0.0375,0.0375,0.640723,0.801762,390.746909,2.702089,3057.750821,11314.826638,128.490636,quality_cap,3.75%,Secondary,Middle,24,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,2,2,10
10,Secondary_Back_27D,0.0400,Secondary,Back,27,3.75%,4.00%,0.0025,0.0375,0.0400,0.643219,0.809524,377.258363,2.674932,3232.669486,11924.980481,286.206940,quality_cap,4.00%,Secondary,Back,27,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,2,3,11
11,Secondary_Back_30D,0.0425,Secondary,Back,30,4.25%,4.25%,0.0000,0.0425,0.0425,0.733903,0.846774,423.107915,3.378701,3300.432417,8314.739278,332.445843,quality_cap,4.25%,Secondary,Back,30,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,2,3,12
12,Secondary_Back_33D,0.0450,Secondary,Back,33,4.25%,4.50%,0.0025,0.0425,0.0450,0.797547,0.874016,432.869534,3.954979,3228.046660,9426.293260,367.730756,quality_cap,4.50%,Secondary,Back,33,final_one_trade_per_day_naked_put_sizing_locked_v1,final_one_trade_per_day_naked_put_sizing_locked_001,naked_short_put_tenor_selection_and_sizing,Final one-trade-per-day naked short put sizing program,core_secondary_consistent_secondary_signal_stack_locked_v1,core_secondary_consistent_secondary_signal_stack_locked_001,True,True,20260706_142800,1,highest_locked_size_pct,Core beats Secondary,higher sizing_quality_score,higher sleeve win_rate,lower 1pct_expected_loss,longer DTE,short_put_entry_credit_points,True,2,3,13

Sizing rules columns:
  sleeve_id
  locked_size_pct
  signal_layer
  tenor_bucket
  tenor
  model_size_pct_label
  manual_size_pct_label
  manual_minus_model_size_pct
  tail_budget_rounded_size_pct
  final_recommended_size_pct
  sizing_quality_score
  win_rate
  avg_pnl_per_day
  profit_factor_pnl_per_day
  pnl_per_day_expected_loss_1pct_positive
  worst20_loss_positive
  avg_pnl_per_day_2026
  primary_size_bottleneck
  locked_size_label
  parsed_signal_layer
  parsed_tenor_bucket
  parsed_tenor
  sizing_lock_version
  sizing_lock_decision_id
  program_type
  program_label
  signal_stack_lock_version
  signal_stack_lock_decision_id
  is_locked
  is_final_sizing_lock
  locked_at
  max_trades_per_day
  selection_primary_key
  tie_break_1
  tie_break_2
  tie_break_3
  tie_break_4
  tie_break_5
  pricing_basis_label
  not_defined_spread_sizing
  signal_layer_order
  tenor_bucket_order
  display_order

Possible sizing columns:
['locked_size_pct', 'model_size_pct_label', 'manual_size_pct_label', 'manual_minus_model_size_pct', 'tail_budget_rounded_size_pct', 'final_recommended_size_pct', 'sizing_quality_score', 'primary_size_bottleneck', 'locked_size_label', 'sizing_lock_version', 'sizing_lock_decision_id', 'is_locked', 'is_final_sizing_lock', 'locked_at', 'not_defined_spread_sizing']

====================================================================================================
Suggested final source contract summary
====================================================================================================
{
  "forecast_panel_path": "C:\\Users\\patri\\vrp_project\\data\\processed\\vrp_front_middle_corsi_forecast_repair_v1\\07A_unified_fds_no_min_return_oos_forecast_panel_20200102_20260701_20260704_203242.parquet",
  "forecast_rows": 31140,
  "forecast_min_date": "2019-01-02",
  "forecast_max_date": "2026-07-01",
  "forecast_tenors": [
    9,
    12,
    15,
    18,
    21,
    24,
    27,
    30,
    33
  ],
  "forecast_duplicate_trade_date_tenor_rows": 29376,
  "rv21d_path": "C:\\Users\\patri\\vrp_project\\data\\processed\\market_data\\spy_realized_vol_history_v1.parquet",
  "rv21d_rows": 2135,
  "rv21d_min_date": "2018-01-02",
  "rv21d_max_date": "2026-07-01",
  "missing_rv21d_after_join": 0,
  "signal_rules_path": "C:\\Users\\patri\\vrp_project\\data\\processed\\vrp_core_secondary_tertiary_independent_sizing_research_v1\\09S_core_secondary_consistent_secondary_locked_rules_long_20260705_221829.parquet",
  "signal_rules_rows": 19,
  "sizing_rules_path": "C:\\Users\\patri\\vrp_project\\data\\processed\\vrp_core_secondary_tertiary_independent_sizing_research_v1\\15S_final_one_trade_per_day_naked_put_sizing_lock_rules_20260706_142800.parquet",
  "sizing_rules_rows": 13,
  "selection_rule_path": "C:\\Users\\patri\\vrp_project\\data\\audit\\vrp_core_secondary_tertiary_independent_sizing_research_v1\\15S_final_one_trade_per_day_naked_put_selection_rule_20260706_142800.json"
}

In [4]:
from pathlib import Path
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", None)

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

FORECAST_PANEL_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1"
    r"\07A_unified_fds_no_min_return_oos_forecast_panel_20200102_20260701_20260704_203242.parquet"
)

COMMON_ROW_PANEL_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1"
    r"\07A_unified_common_row_panel_20200102_20260701_20260704_203242.parquet"
)

DIAGNOSTIC_PANEL_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1"
    r"\07A_unified_signal_threshold_diagnostic_panel_20200102_20260701_20260704_203242.parquet"
)

paths = {
    "forecast_panel": FORECAST_PANEL_PATH,
    "common_row_panel": COMMON_ROW_PANEL_PATH,
    "diagnostic_panel": DIAGNOSTIC_PANEL_PATH,
}

print("=" * 100)
print("07A duplicate-block diagnostic — source existence")
print("=" * 100)

for name, path in paths.items():
    print(f"{name:20s} exists={path.exists()}  path={path}")

missing = [name for name, path in paths.items() if not path.exists()]
if missing:
    raise FileNotFoundError(f"Missing source files: {missing}")

# ======================================================================================
# Load panels
# ======================================================================================

forecast = pd.read_parquet(FORECAST_PANEL_PATH)
common = pd.read_parquet(COMMON_ROW_PANEL_PATH)
diagnostic = pd.read_parquet(DIAGNOSTIC_PANEL_PATH)

for df in [forecast, common, diagnostic]:
    if "trade_date" in df.columns:
        df["trade_date"] = pd.to_datetime(df["trade_date"], errors="coerce")
    if "tenor" in df.columns:
        df["tenor"] = pd.to_numeric(df["tenor"], errors="coerce").astype("Int64")

# ======================================================================================
# Helper functions
# ======================================================================================

def panel_summary(name, df):
    print("\n" + "=" * 100)
    print(name)
    print("=" * 100)
    print(f"Rows: {len(df):,}")
    print(f"Cols: {len(df.columns):,}")
    if "trade_date" in df.columns:
        print(f"Date range: {df['trade_date'].min().date()} to {df['trade_date'].max().date()}")
        print(f"Unique dates: {df['trade_date'].nunique():,}")
    if "tenor" in df.columns:
        print(f"Tenors: {sorted(df['tenor'].dropna().astype(int).unique().tolist())}")
    if {"trade_date", "tenor"}.issubset(df.columns):
        dup_rows = int(df.duplicated(["trade_date", "tenor"], keep=False).sum())
        unique_keys = int(df[["trade_date", "tenor"]].drop_duplicates().shape[0])
        print(f"Unique trade_date × tenor keys: {unique_keys:,}")
        print(f"Duplicate trade_date × tenor rows: {dup_rows:,}")
        tenor_counts = (
            df.groupby("trade_date")["tenor"]
            .nunique()
            .value_counts()
            .sort_index()
            .reset_index()
        )
        tenor_counts.columns = ["unique_tenors_per_date", "date_count"]
        print("\nTenor-count distribution:")
        display(tenor_counts)

def add_reconstruction_checks(df, label):
    out = df.copy()

    var_cols = [
        "forecast_variance_candidate",
        "forecast_variance_har_downside_v1",
        "baseline_forecast_variance",
    ]

    for col in var_cols:
        if col in out.columns:
            out[f"{label}_vrp_log_using_{col}"] = np.log(out["implied_variance"] / out[col])
            out[f"{label}_abs_diff_using_{col}"] = (
                out["model_vrp_log"] - out[f"{label}_vrp_log_using_{col}"]
            ).abs()

    if "candidate_forecast_vol_pct" in out.columns and "forecast_variance_candidate" in out.columns:
        out[f"{label}_candidate_vol_recalc"] = np.sqrt(out["forecast_variance_candidate"]) * 100
        out[f"{label}_candidate_vol_abs_diff"] = (
            out["candidate_forecast_vol_pct"] - out[f"{label}_candidate_vol_recalc"]
        ).abs()

    return out

def summarize_categorical(df, cols, title):
    print("\n" + "=" * 100)
    print(title)
    print("=" * 100)

    for col in cols:
        if col not in df.columns:
            print(f"\n{col}: MISSING")
            continue

        print(f"\n{col}:")
        display(
            df[col]
            .astype("string")
            .fillna("<NA>")
            .value_counts(dropna=False)
            .reset_index()
            .rename(columns={"index": col, col: "count"})
            .head(50)
        )

def summarize_reconstruction(df, title):
    print("\n" + "=" * 100)
    print(title)
    print("=" * 100)

    diff_cols = [c for c in df.columns if c.endswith("_abs_diff_using_forecast_variance_candidate")]

    all_diff_cols = [c for c in df.columns if "_abs_diff_using_" in c]
    all_diff_cols += [c for c in df.columns if c.endswith("_candidate_vol_abs_diff")]

    for col in all_diff_cols:
        print(f"\n{col}:")
        display(
            df[col]
            .describe(percentiles=[0.5, 0.9, 0.99, 0.999])
            .to_frame()
        )
        print(f"Rows <= 1e-10: {(df[col] <= 1e-10).sum():,} / {len(df):,}")
        print(f"Rows >  1e-10: {(df[col] > 1e-10).sum():,} / {len(df):,}")

# ======================================================================================
# Basic panel summaries
# ======================================================================================

panel_summary("FORECAST — 07A unified_fds_no_min_return_oos_forecast_panel", forecast)
panel_summary("COMMON — 07A unified_common_row_panel", common)
panel_summary("DIAGNOSTIC — 07A unified_signal_threshold_diagnostic_panel", diagnostic)

# ======================================================================================
# Forecast duplicate diagnostics
# ======================================================================================

forecast_checked = add_reconstruction_checks(forecast, "forecast")
forecast_checked["_key_count"] = forecast_checked.groupby(["trade_date", "tenor"])["tenor"].transform("size")
forecast_checked["_is_duplicate_key"] = forecast_checked["_key_count"] > 1

dup = forecast_checked[forecast_checked["_is_duplicate_key"]].copy()
nondup = forecast_checked[~forecast_checked["_is_duplicate_key"]].copy()

print("\n" + "=" * 100)
print("FORECAST duplicate vs non-duplicate split")
print("=" * 100)
print(f"Forecast total rows:      {len(forecast_checked):,}")
print(f"Duplicate-key rows:       {len(dup):,}")
print(f"Non-duplicate-key rows:   {len(nondup):,}")
print(f"Duplicate unique keys:    {dup[['trade_date', 'tenor']].drop_duplicates().shape[0]:,}")
print(f"Non-duplicate unique keys:{nondup[['trade_date', 'tenor']].drop_duplicates().shape[0]:,}")

diagnostic_cols = [
    "model_spec",
    "model_source",
    "fit_status_candidate",
    "fit_status",
    "forecast_repair_scope",
    "is_back_frozen",
    "is_research_tenor",
    "tenor_bucket",
    "test_year",
    "test_year_candidate",
    "selected_alpha",
    "selected_alpha_candidate",
    "train_rows_used",
    "train_rows_used_candidate",
]

summarize_categorical(forecast_checked, diagnostic_cols, "FORECAST categorical diagnostics — all rows")
summarize_categorical(dup, diagnostic_cols, "FORECAST categorical diagnostics — duplicate-key rows only")
summarize_categorical(nondup, diagnostic_cols, "FORECAST categorical diagnostics — non-duplicate-key rows only")

summarize_reconstruction(forecast_checked, "FORECAST reconstruction diagnostics — all rows")
summarize_reconstruction(dup, "FORECAST reconstruction diagnostics — duplicate-key rows only")
summarize_reconstruction(nondup, "FORECAST reconstruction diagnostics — non-duplicate-key rows only")

# ======================================================================================
# Pair-level duplicate comparison
# ======================================================================================

print("\n" + "=" * 100)
print("Pair-level duplicate comparison")
print("=" * 100)

sort_cols = ["trade_date", "tenor"]

rank_cols = [
    "forecast_abs_diff_using_forecast_variance_candidate",
    "forecast_candidate_vol_abs_diff",
]

rank_col = "forecast_abs_diff_using_forecast_variance_candidate"

dup_sorted = dup.sort_values(sort_cols + [rank_col]).copy()
dup_sorted["_within_key_rank_by_candidate_vrp_diff"] = (
    dup_sorted.groupby(["trade_date", "tenor"]).cumcount() + 1
)

pair_summary = (
    dup_sorted
    .groupby("_within_key_rank_by_candidate_vrp_diff")
    .agg(
        rows=("tenor", "size"),
        min_date=("trade_date", "min"),
        max_date=("trade_date", "max"),
        avg_candidate_vrp_abs_diff=(rank_col, "mean"),
        median_candidate_vrp_abs_diff=(rank_col, "median"),
        max_candidate_vrp_abs_diff=(rank_col, "max"),
        avg_forecast_variance_candidate=("forecast_variance_candidate", "mean"),
        avg_candidate_forecast_vol_pct=("candidate_forecast_vol_pct", "mean"),
    )
    .reset_index()
)

pair_summary["min_date"] = pair_summary["min_date"].dt.date.astype(str)
pair_summary["max_date"] = pair_summary["max_date"].dt.date.astype(str)

display(pair_summary)

print("\nSample duplicated keys, ranked by candidate VRP reconstruction closeness:")
sample_cols = [
    "trade_date",
    "tenor",
    "_within_key_rank_by_candidate_vrp_diff",
    "model_spec",
    "model_source",
    "fit_status_candidate",
    "fit_status",
    "forecast_repair_scope",
    "is_back_frozen",
    "implied_variance",
    "forecast_variance_candidate",
    "forecast_variance_har_downside_v1",
    "baseline_forecast_variance",
    "model_vrp_log",
    "forecast_vrp_log_using_forecast_variance_candidate",
    "forecast_abs_diff_using_forecast_variance_candidate",
    "candidate_forecast_vol_pct",
    "forecast_candidate_vol_recalc",
    "forecast_candidate_vol_abs_diff",
    "predicted_log_variance_candidate",
    "candidate_log_rv_21d",
    "target_realized_variance",
]

sample_cols = [c for c in sample_cols if c in dup_sorted.columns]

display(
    dup_sorted[sample_cols]
    .sort_values(["trade_date", "tenor", "_within_key_rank_by_candidate_vrp_diff"])
    .head(100)
)

# ======================================================================================
# Check whether common/diagnostic panels are already deduped and internally consistent
# ======================================================================================

for name, df in [
    ("COMMON", common),
    ("DIAGNOSTIC", diagnostic),
]:
    checked = add_reconstruction_checks(df, name.lower())

    print("\n" + "=" * 100)
    print(f"{name} panel reconstruction and duplicate checks")
    print("=" * 100)

    dup_rows = int(checked.duplicated(["trade_date", "tenor"], keep=False).sum())
    print(f"Duplicate trade_date × tenor rows: {dup_rows:,}")

    if f"{name.lower()}_abs_diff_using_forecast_variance_candidate" in checked.columns:
        diff = checked[f"{name.lower()}_abs_diff_using_forecast_variance_candidate"]
        print(f"Rows where model_vrp_log matches candidate forecast variance <= 1e-10: {(diff <= 1e-10).sum():,} / {len(checked):,}")
        print(f"Rows where model_vrp_log differs candidate forecast variance >  1e-10: {(diff > 1e-10).sum():,} / {len(checked):,}")
        display(diff.describe(percentiles=[0.5, 0.9, 0.99, 0.999]).to_frame("abs_diff"))

    print("\nCategorical diagnostics:")
    for col in diagnostic_cols:
        if col in checked.columns:
            print(f"\n{name} — {col}:")
            display(
                checked[col]
                .astype("string")
                .fillna("<NA>")
                .value_counts(dropna=False)
                .reset_index()
                .rename(columns={"index": col, col: "count"})
                .head(20)
            )

# ======================================================================================
# Compare candidate deduped forecast rows to common and diagnostic panels
# ======================================================================================

print("\n" + "=" * 100)
print("Candidate dedupe methods")
print("=" * 100)

# Method A: choose row per date-tenor where model_vrp_log best matches log(implied / forecast_variance_candidate)
dedup_by_candidate_vrp = (
    forecast_checked
    .sort_values(["trade_date", "tenor", "forecast_abs_diff_using_forecast_variance_candidate"])
    .drop_duplicates(["trade_date", "tenor"], keep="first")
    .copy()
)

# Method B: choose row per date-tenor where candidate_forecast_vol_pct best matches sqrt(forecast_variance_candidate) * 100
if "forecast_candidate_vol_abs_diff" in forecast_checked.columns:
    dedup_by_candidate_vol = (
        forecast_checked
        .sort_values(["trade_date", "tenor", "forecast_candidate_vol_abs_diff"])
        .drop_duplicates(["trade_date", "tenor"], keep="first")
        .copy()
    )
else:
    dedup_by_candidate_vol = None

for name, df in [
    ("dedup_by_candidate_vrp", dedup_by_candidate_vrp),
    ("dedup_by_candidate_vol", dedup_by_candidate_vol),
]:
    if df is None:
        continue

    print("\n" + "-" * 100)
    print(name)
    print("-" * 100)
    print(f"Rows: {len(df):,}")
    print(f"Duplicate keys: {df.duplicated(['trade_date', 'tenor'], keep=False).sum():,}")
    print(f"Date range: {df['trade_date'].min().date()} to {df['trade_date'].max().date()}")
    print(f"Tenors: {sorted(df['tenor'].dropna().astype(int).unique().tolist())}")

    diff = df["forecast_abs_diff_using_forecast_variance_candidate"]
    print(f"VRP candidate reconstruction rows <= 1e-10: {(diff <= 1e-10).sum():,} / {len(df):,}")
    print(f"VRP candidate reconstruction rows >  1e-10: {(diff > 1e-10).sum():,} / {len(df):,}")
    display(diff.describe(percentiles=[0.5, 0.9, 0.99, 0.999]).to_frame("abs_diff"))

# ======================================================================================
# Save audit candidate for review
# ======================================================================================

audit_dir = PROJECT_ROOT / "data" / "audit" / "vrp_final_signal"
audit_dir.mkdir(parents=True, exist_ok=True)

audit_path = audit_dir / "07A_duplicate_block_diagnostic_preview.csv"

preview_cols = [
    "trade_date",
    "tenor",
    "_key_count",
    "_within_key_rank_by_candidate_vrp_diff",
    "model_spec",
    "model_source",
    "fit_status_candidate",
    "fit_status",
    "forecast_repair_scope",
    "is_back_frozen",
    "is_research_tenor",
    "implied_variance",
    "forecast_variance_candidate",
    "forecast_variance_har_downside_v1",
    "baseline_forecast_variance",
    "model_vrp_log",
    "forecast_vrp_log_using_forecast_variance_candidate",
    "forecast_abs_diff_using_forecast_variance_candidate",
    "candidate_forecast_vol_pct",
    "forecast_candidate_vol_recalc",
    "forecast_candidate_vol_abs_diff",
    "predicted_log_variance_candidate",
    "candidate_log_rv_21d",
    "target_realized_variance",
]

preview_cols = [c for c in preview_cols if c in dup_sorted.columns]

dup_sorted[preview_cols].head(5000).to_csv(audit_path, index=False)

print("\n" + "=" * 100)
print("Saved duplicate diagnostic preview")
print("=" * 100)
print(audit_path)

====================================================================================================
07A duplicate-block diagnostic — source existence
====================================================================================================
forecast_panel       exists=True  path=C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_fds_no_min_return_oos_forecast_panel_20200102_20260701_20260704_203242.parquet
common_row_panel     exists=True  path=C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_common_row_panel_20200102_20260701_20260704_203242.parquet
diagnostic_panel     exists=True  path=C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_signal_threshold_diagnostic_panel_20200102_20260701_20260704_203242.parquet

====================================================================================================
FORECAST — 07A unified_fds_no_min_return_oos_forecast_panel
====================================================================================================
Rows: 31,140
Cols: 89
Date range: 2019-01-02 to 2026-07-01
Unique dates: 1,884
Tenors: [9, 12, 15, 18, 21, 24, 27, 30, 33]
Unique trade_date × tenor keys: 16,452
Duplicate trade_date × tenor rows: 29,376

Tenor-count distribution:

   unique_tenors_per_date  date_count
0                       7         252
1                       9        1632

====================================================================================================
COMMON — 07A unified_common_row_panel
====================================================================================================
Rows: 29,376
Cols: 93
Date range: 2020-01-02 to 2026-07-01
Unique dates: 1,632
Tenors: [9, 12, 15, 18, 21, 24, 27, 30, 33]
Unique trade_date × tenor keys: 14,688
Duplicate trade_date × tenor rows: 29,376

Tenor-count distribution:

   unique_tenors_per_date  date_count
0                       9        1632

====================================================================================================
DIAGNOSTIC — 07A unified_signal_threshold_diagnostic_panel
====================================================================================================
Rows: 29,376
Cols: 99
Date range: 2020-01-02 to 2026-07-01
Unique dates: 1,632
Tenors: [9, 12, 15, 18, 21, 24, 27, 30, 33]
Unique trade_date × tenor keys: 14,688
Duplicate trade_date × tenor rows: 29,376

Tenor-count distribution:

   unique_tenors_per_date  date_count
0                       9        1632

====================================================================================================
FORECAST duplicate vs non-duplicate split
====================================================================================================
Forecast total rows:      31,140
Duplicate-key rows:       29,376
Non-duplicate-key rows:   1,764
Duplicate unique keys:    14,688
Non-duplicate unique keys:1,764

====================================================================================================
FORECAST categorical diagnostics — all rows
====================================================================================================

model_spec:

                       count  count
0   existing_har_downside_v1  16452
1  unified_fds_no_min_return  14688

model_source:

                                 count  count
0    existing_har_downside_v1_forecast  16452
1  unified_fds_no_min_return_oos_refit  14688

fit_status_candidate:

               count  count
0  existing_forecast  16452
1      candidate_fit  14688

fit_status:

    count  count
0  FIT_OK  31140

forecast_repair_scope:

                      count  count
0            RESEARCH_FRONT  10548
1           RESEARCH_MIDDLE  10548
2  UNFROZEN_BACK_DIAGNOSTIC  10044

is_back_frozen:

   count  count
0  False  21096
1   True  10044

is_research_tenor:

   count  count
0   True  21096
1  False  10044

tenor_bucket:

    count  count
0   Front  10548
1  Middle  10548
2    Back  10044

test_year:

    count  count
0  2020.0   4554
1  2021.0   4536
2  2024.0   4536
3  2022.0   4518
4  2025.0   4500
5  2023.0   4500
6  2026.0   2232
7  2019.0   1764

test_year_candidate:

   count  count
0   2020   4554
1   2021   4536
2   2024   4536
3   2022   4518
4   2025   4500
5   2023   4500
6   2026   2232
7   2019   1764

selected_alpha:

   count  count
0  100.0  28364
1    1.0   2776

selected_alpha_candidate:

   count  count
0  100.0  23850
1  300.0   3511
2    1.0   2270
3   10.0   1509

train_rows_used:

     count  count
0    307.0    506
1    304.0    506
2    309.0    506
3    311.0    506
4    314.0    506
5    315.0    506
6    299.0    506
7    300.0    506
8    303.0    506
9    555.0    504
10  1307.0    504
11  1322.0    504
12  1312.0    504
13  1309.0    504
14   552.0    504
15   565.0    504
16   569.0    504
17   567.0    504
18   560.0    504
19   563.0    504
20   559.0    504
21   556.0    504
22  1316.0    504
23  1313.0    504
24  1320.0    504
25  1305.0    504
26  1317.0    504
27   816.0    502
28   818.0    502
29   806.0    502
30   811.0    502
31   803.0    502
32   807.0    502
33   810.0    502
34   814.0    502
35   820.0    502
36  1072.0    500
37  1066.0    500
38  1561.0    500
39  1567.0    500
40  1565.0    500
41  1562.0    500
42  1557.0    500
43  1558.0    500
44  1070.0    500
45  1067.0    500
46  1569.0    500
47  1055.0    500
48  1059.0    500
49  1057.0    500

train_rows_used_candidate:

     count  count
0    307.0    506
1    304.0    506
2    309.0    506
3    311.0    506
4    314.0    506
5    315.0    506
6    299.0    506
7    300.0    506
8    303.0    506
9    555.0    504
10  1307.0    504
11  1322.0    504
12  1312.0    504
13  1309.0    504
14   552.0    504
15   565.0    504
16   569.0    504
17   567.0    504
18   560.0    504
19   563.0    504
20   559.0    504
21   556.0    504
22  1316.0    504
23  1313.0    504
24  1320.0    504
25  1305.0    504
26  1317.0    504
27   816.0    502
28   818.0    502
29   806.0    502
30   811.0    502
31   803.0    502
32   807.0    502
33   810.0    502
34   814.0    502
35   820.0    502
36  1072.0    500
37  1066.0    500
38  1561.0    500
39  1567.0    500
40  1565.0    500
41  1562.0    500
42  1557.0    500
43  1558.0    500
44  1070.0    500
45  1067.0    500
46  1569.0    500
47  1055.0    500
48  1059.0    500
49  1057.0    500

====================================================================================================
FORECAST categorical diagnostics — duplicate-key rows only
====================================================================================================

model_spec:

                       count  count
0   existing_har_downside_v1  14688
1  unified_fds_no_min_return  14688

model_source:

                                 count  count
0    existing_har_downside_v1_forecast  14688
1  unified_fds_no_min_return_oos_refit  14688

fit_status_candidate:

               count  count
0  existing_forecast  14688
1      candidate_fit  14688

fit_status:

    count  count
0  FIT_OK  29376

forecast_repair_scope:

                      count  count
0            RESEARCH_FRONT   9792
1           RESEARCH_MIDDLE   9792
2  UNFROZEN_BACK_DIAGNOSTIC   9792

is_back_frozen:

   count  count
0  False  19584
1   True   9792

is_research_tenor:

   count  count
0   True  19584
1  False   9792

tenor_bucket:

    count  count
0   Front   9792
1  Middle   9792
2    Back   9792

test_year:

    count  count
0  2020.0   4554
1  2021.0   4536
2  2024.0   4536
3  2022.0   4518
4  2023.0   4500
5  2025.0   4500
6  2026.0   2232

test_year_candidate:

   count  count
0   2020   4554
1   2021   4536
2   2024   4536
3   2022   4518
4   2023   4500
5   2025   4500
6   2026   2232

selected_alpha:

   count  count
0  100.0  28364
1    1.0   1012

selected_alpha_candidate:

   count  count
0  100.0  23850
1  300.0   3511
2   10.0   1509
3    1.0    506

train_rows_used:

     count  count
0    315.0    506
1    314.0    506
2    311.0    506
3    309.0    506
4    307.0    506
5    304.0    506
6    303.0    506
7    300.0    506
8    299.0    506
9    569.0    504
10   567.0    504
11   565.0    504
12   563.0    504
13   560.0    504
14   559.0    504
15   556.0    504
16   555.0    504
17   552.0    504
18  1309.0    504
19  1307.0    504
20  1322.0    504
21  1317.0    504
22  1305.0    504
23  1316.0    504
24  1313.0    504
25  1312.0    504
26  1320.0    504
27   818.0    502
28   816.0    502
29   814.0    502
30   820.0    502
31   811.0    502
32   806.0    502
33   807.0    502
34   810.0    502
35   803.0    502
36  1067.0    500
37  1070.0    500
38  1072.0    500
39  1066.0    500
40  1055.0    500
41  1059.0    500
42  1057.0    500
43  1063.0    500
44  1062.0    500
45  1573.0    500
46  1572.0    500
47  1569.0    500
48  1567.0    500
49  1565.0    500

train_rows_used_candidate:

     count  count
0    315.0    506
1    314.0    506
2    311.0    506
3    309.0    506
4    307.0    506
5    304.0    506
6    303.0    506
7    300.0    506
8    299.0    506
9    569.0    504
10   567.0    504
11   565.0    504
12   563.0    504
13   560.0    504
14   559.0    504
15   556.0    504
16   555.0    504
17   552.0    504
18  1309.0    504
19  1307.0    504
20  1322.0    504
21  1317.0    504
22  1305.0    504
23  1316.0    504
24  1313.0    504
25  1312.0    504
26  1320.0    504
27   818.0    502
28   816.0    502
29   814.0    502
30   820.0    502
31   811.0    502
32   806.0    502
33   807.0    502
34   810.0    502
35   803.0    502
36  1067.0    500
37  1070.0    500
38  1072.0    500
39  1066.0    500
40  1055.0    500
41  1059.0    500
42  1057.0    500
43  1063.0    500
44  1062.0    500
45  1573.0    500
46  1572.0    500
47  1569.0    500
48  1567.0    500
49  1565.0    500

====================================================================================================
FORECAST categorical diagnostics — non-duplicate-key rows only
====================================================================================================

model_spec:

                      count  count
0  existing_har_downside_v1   1764

model_source:

                               count  count
0  existing_har_downside_v1_forecast   1764

fit_status_candidate:

               count  count
0  existing_forecast   1764

fit_status:

    count  count
0  FIT_OK   1764

forecast_repair_scope:

                      count  count
0            RESEARCH_FRONT    756
1           RESEARCH_MIDDLE    756
2  UNFROZEN_BACK_DIAGNOSTIC    252

is_back_frozen:

   count  count
0  False   1512
1   True    252

is_research_tenor:

   count  count
0   True   1512
1  False    252

tenor_bucket:

    count  count
0   Front    756
1  Middle    756
2    Back    252

test_year:

    count  count
0  2019.0   1764

test_year_candidate:

   count  count
0   2019   1764

selected_alpha:

   count  count
0    1.0   1764

selected_alpha_candidate:

   count  count
0    1.0   1764

train_rows_used:

   count  count
0   63.0    252
1   62.0    252
2   59.0    252
3   58.0    252
4   55.0    252
5   53.0    252
6   51.0    252

train_rows_used_candidate:

   count  count
0   63.0    252
1   62.0    252
2   59.0    252
3   58.0    252
4   55.0    252
5   53.0    252
6   51.0    252

====================================================================================================
FORECAST reconstruction diagnostics — all rows
====================================================================================================

forecast_abs_diff_using_forecast_variance_candidate:

       forecast_abs_diff_using_forecast_variance_candidate
count                                         31140.000000
mean                                              0.082304
std                                               0.169618
min                                               0.000000
50%                                               0.000000
90%                                               0.242892
99%                                               0.704221
99.9%                                             1.943374
max                                               2.596017

Rows <= 1e-10: 16,452 / 31,140
Rows >  1e-10: 14,688 / 31,140

forecast_abs_diff_using_forecast_variance_har_downside_v1:

       forecast_abs_diff_using_forecast_variance_har_downside_v1
count                                                    31140.0
mean                                                         0.0
std                                                          0.0
min                                                          0.0
50%                                                          0.0
90%                                                          0.0
99%                                                          0.0
99.9%                                                        0.0
max                                                          0.0

Rows <= 1e-10: 31,140 / 31,140
Rows >  1e-10: 0 / 31,140

forecast_abs_diff_using_baseline_forecast_variance:

       forecast_abs_diff_using_baseline_forecast_variance
count                                             31140.0
mean                                                  0.0
std                                                   0.0
min                                                   0.0
50%                                                   0.0
90%                                                   0.0
99%                                                   0.0
99.9%                                                 0.0
max                                                   0.0

Rows <= 1e-10: 31,140 / 31,140
Rows >  1e-10: 0 / 31,140

forecast_candidate_vol_abs_diff:

       forecast_candidate_vol_abs_diff
count                          31140.0
mean                               0.0
std                                0.0
min                                0.0
50%                                0.0
90%                                0.0
99%                                0.0
99.9%                              0.0
max                                0.0

Rows <= 1e-10: 31,140 / 31,140
Rows >  1e-10: 0 / 31,140

====================================================================================================
FORECAST reconstruction diagnostics — duplicate-key rows only
====================================================================================================

forecast_abs_diff_using_forecast_variance_candidate:

       forecast_abs_diff_using_forecast_variance_candidate
count                                         2.937600e+04
mean                                          8.724609e-02
std                                           1.733978e-01
min                                           0.000000e+00
50%                                           8.459571e-07
90%                                           2.508973e-01
99%                                           7.334173e-01
99.9%                                         1.960430e+00
max                                           2.596017e+00

Rows <= 1e-10: 14,688 / 29,376
Rows >  1e-10: 14,688 / 29,376

forecast_abs_diff_using_forecast_variance_har_downside_v1:

       forecast_abs_diff_using_forecast_variance_har_downside_v1
count                                                    29376.0
mean                                                         0.0
std                                                          0.0
min                                                          0.0
50%                                                          0.0
90%                                                          0.0
99%                                                          0.0
99.9%                                                        0.0
max                                                          0.0

Rows <= 1e-10: 29,376 / 29,376
Rows >  1e-10: 0 / 29,376

forecast_abs_diff_using_baseline_forecast_variance:

       forecast_abs_diff_using_baseline_forecast_variance
count                                             29376.0
mean                                                  0.0
std                                                   0.0
min                                                   0.0
50%                                                   0.0
90%                                                   0.0
99%                                                   0.0
99.9%                                                 0.0
max                                                   0.0

Rows <= 1e-10: 29,376 / 29,376
Rows >  1e-10: 0 / 29,376

forecast_candidate_vol_abs_diff:

       forecast_candidate_vol_abs_diff
count                          29376.0
mean                               0.0
std                                0.0
min                                0.0
50%                                0.0
90%                                0.0
99%                                0.0
99.9%                              0.0
max                                0.0

Rows <= 1e-10: 29,376 / 29,376
Rows >  1e-10: 0 / 29,376

====================================================================================================
FORECAST reconstruction diagnostics — non-duplicate-key rows only
====================================================================================================

forecast_abs_diff_using_forecast_variance_candidate:

       forecast_abs_diff_using_forecast_variance_candidate
count                                               1764.0
mean                                                   0.0
std                                                    0.0
min                                                    0.0
50%                                                    0.0
90%                                                    0.0
99%                                                    0.0
99.9%                                                  0.0
max                                                    0.0

Rows <= 1e-10: 1,764 / 1,764
Rows >  1e-10: 0 / 1,764

forecast_abs_diff_using_forecast_variance_har_downside_v1:

       forecast_abs_diff_using_forecast_variance_har_downside_v1
count                                                     1764.0
mean                                                         0.0
std                                                          0.0
min                                                          0.0
50%                                                          0.0
90%                                                          0.0
99%                                                          0.0
99.9%                                                        0.0
max                                                          0.0

Rows <= 1e-10: 1,764 / 1,764
Rows >  1e-10: 0 / 1,764

forecast_abs_diff_using_baseline_forecast_variance:

       forecast_abs_diff_using_baseline_forecast_variance
count                                              1764.0
mean                                                  0.0
std                                                   0.0
min                                                   0.0
50%                                                   0.0
90%                                                   0.0
99%                                                   0.0
99.9%                                                 0.0
max                                                   0.0

Rows <= 1e-10: 1,764 / 1,764
Rows >  1e-10: 0 / 1,764

forecast_candidate_vol_abs_diff:

       forecast_candidate_vol_abs_diff
count                           1764.0
mean                               0.0
std                                0.0
min                                0.0
50%                                0.0
90%                                0.0
99%                                0.0
99.9%                              0.0
max                                0.0

Rows <= 1e-10: 1,764 / 1,764
Rows >  1e-10: 0 / 1,764

====================================================================================================
Pair-level duplicate comparison
====================================================================================================

,_within_key_rank_by_candidate_vrp_diff,rows,min_date,max_date,avg_candidate_vrp_abs_diff,median_candidate_vrp_abs_diff,max_candidate_vrp_abs_diff,avg_forecast_variance_candidate,avg_candidate_forecast_vol_pct
0,1,14688,2020-01-02,2026-07-01,0.000000,0.000000,0.000000,0.022623,14.596968
1,2,14688,2020-01-02,2026-07-01,0.174492,0.124514,2.596017,0.025504,14.951647

Sample duplicated keys, ranked by candidate VRP reconstruction closeness:

,trade_date,tenor,_within_key_rank_by_candidate_vrp_diff,model_spec,model_source,fit_status_candidate,fit_status,forecast_repair_scope,is_back_frozen,implied_variance,forecast_variance_candidate,forecast_variance_har_downside_v1,baseline_forecast_variance,model_vrp_log,forecast_vrp_log_using_forecast_variance_candidate,forecast_abs_diff_using_forecast_variance_candidate,candidate_forecast_vol_pct,forecast_candidate_vol_recalc,forecast_candidate_vol_abs_diff,predicted_log_variance_candidate,candidate_log_rv_21d,target_realized_variance
1764,2020-01-02,9,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.011050,0.008121,0.008121,0.008121,0.308033,0.308033,0.000000,9.011415,9.011415,0.0,-4.813356,-5.124781,0.013370
16452,2020-01-02,9,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.011050,0.008154,0.008121,0.008121,0.308033,0.303980,0.004053,9.029693,9.029693,0.0,-4.809304,-5.124781,0.013370
1765,2020-01-02,12,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.012187,0.009070,0.009070,0.009070,0.295337,0.295337,0.000000,9.523761,9.523761,0.0,-4.702761,-5.124781,0.010885
18084,2020-01-02,12,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.012187,0.009013,0.009070,0.009070,0.295337,0.301689,0.006352,9.493562,9.493562,0.0,-4.709113,-5.124781,0.010885
1766,2020-01-02,15,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.012860,0.010899,0.010899,0.010899,0.165473,0.165473,0.000000,10.439731,10.439731,0.0,-4.519103,-5.124781,0.010206
19716,2020-01-02,15,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.012860,0.010799,0.010899,0.010899,0.165473,0.174642,0.009169,10.391981,10.391981,0.0,-4.528271,-5.124781,0.010206
1767,2020-01-02,18,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.013239,0.011652,0.011652,0.011652,0.127681,0.127681,0.000000,10.794297,10.794297,0.0,-4.452304,-5.124781,0.008505
21348,2020-01-02,18,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.013239,0.011473,0.011652,0.011652,0.127681,0.143148,0.015467,10.711141,10.711141,0.0,-4.467772,-5.124781,0.008505
1768,2020-01-02,21,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.013509,0.012913,0.012913,0.012913,0.045141,0.045141,0.000000,11.363384,11.363384,0.0,-4.349548,-5.124781,0.008611
22980,2020-01-02,21,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.013509,0.012752,0.012913,0.012913,0.045141,0.057671,0.012531,11.292412,11.292412,0.0,-4.362078,-5.124781,0.008611
1769,2020-01-02,24,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.014163,0.013624,0.013624,0.013624,0.038741,0.038741,0.000000,11.672396,11.672396,0.0,-4.295887,-5.124781,0.008925
24612,2020-01-02,24,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.014163,0.013507,0.013624,0.013624,0.038741,0.047399,0.008658,11.621973,11.621973,0.0,-4.304545,-5.124781,0.008925
1770,2020-01-02,27,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.014872,0.014635,0.014635,0.014635,0.016044,0.016044,0.000000,12.097483,12.097483,0.0,-4.224346,-5.124781,0.013998
26244,2020-01-02,27,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.014872,0.014456,0.014635,0.014635,0.016044,0.028319,0.012275,12.023463,12.023463,0.0,-4.236620,-5.124781,0.013998
1771,2020-01-02,30,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.015482,0.016487,0.016487,0.016487,-0.062855,-0.062855,0.000000,12.840121,12.840121,0.0,-4.105191,-5.124781,0.014919
27876,2020-01-02,30,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.015482,0.015641,0.016487,0.016487,-0.062855,-0.010161,0.052695,12.506237,12.506237,0.0,-4.157885,-5.124781,0.014919
1772,2020-01-02,33,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.016062,0.017896,0.017896,0.017896,-0.108109,-0.108109,0.000000,13.377432,13.377432,0.0,-4.023202,-5.124781,0.016084
29508,2020-01-02,33,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.016062,0.015978,0.017896,0.017896,-0.108109,0.005222,0.113331,12.640470,12.640470,0.0,-4.136533,-5.124781,0.016084
1773,2020-01-03,9,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.016851,0.008864,0.008864,0.008864,0.642397,0.642397,0.000000,9.414998,9.414998,0.0,-4.725733,-5.113071,0.006385
16453,2020-01-03,9,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.016851,0.010528,0.008864,0.008864,0.642397,0.470342,0.172056,10.260810,10.260810,0.0,-4.553677,-5.113071,0.006385
1774,2020-01-03,12,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.017392,0.009848,0.009848,0.009848,0.568787,0.568787,0.000000,9.923474,9.923474,0.0,-4.620534,-5.113071,0.006156
18085,2020-01-03,12,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.017392,0.011360,0.009848,0.009848,0.568787,0.425898,0.142889,10.658393,10.658393,0.0,-4.477645,-5.113071,0.006156
1775,2020-01-03,15,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.017795,0.011739,0.011739,0.011739,0.415994,0.415994,0.000000,10.834750,10.834750,0.0,-4.444823,-5.113071,0.006015
19717,2020-01-03,15,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.017795,0.013368,0.011739,0.011739,0.415994,0.286066,0.129929,11.561989,11.561989,0.0,-4.314895,-5.113071,0.006015
1776,2020-01-03,18,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.018153,0.012458,0.012458,0.012458,0.376484,0.376484,0.000000,11.161548,11.161548,0.0,-4.385391,-5.113071,0.005566
21349,2020-01-03,18,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.018153,0.013959,0.012458,0.012458,0.376484,0.262734,0.113749,11.814758,11.814758,0.0,-4.271642,-5.113071,0.005566
1777,2020-01-03,21,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.018409,0.013710,0.013710,0.013710,0.294715,0.294715,0.000000,11.708963,11.708963,0.0,-4.289631,-5.113071,0.007207
22981,2020-01-03,21,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.018409,0.015252,0.013710,0.013710,0.294715,0.188130,0.106585,12.349889,12.349889,0.0,-4.183046,-5.113071,0.007207
1778,2020-01-03,24,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.019191,0.014429,0.014429,0.014429,0.285202,0.285202,0.000000,12.012080,12.012080,0.0,-4.238515,-5.113071,0.011716
24613,2020-01-03,24,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.019191,0.015959,0.014429,0.014429,0.285202,0.184435,0.100767,12.632796,12.632796,0.0,-4.137748,-5.113071,0.011716
1779,2020-01-03,27,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.019799,0.015461,0.015461,0.015461,0.247310,0.247310,0.000000,12.434318,12.434318,0.0,-4.169420,-5.113071,0.013140
26245,2020-01-03,27,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.019799,0.016850,0.015461,0.015461,0.247310,0.161273,0.086037,12.980897,12.980897,0.0,-4.083383,-5.113071,0.013140
1780,2020-01-03,30,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.020285,0.018428,0.018428,0.018428,0.096040,0.096040,0.000000,13.574846,13.574846,0.0,-3.993903,-5.113071,0.012824
27877,2020-01-03,30,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.020285,0.018187,0.018428,0.018428,0.096040,0.109178,0.013139,13.485961,13.485961,0.0,-4.007042,-5.113071,0.012824
1781,2020-01-03,33,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.020682,0.019834,0.019834,0.019834,0.041881,0.041881,0.000000,14.083374,14.083374,0.0,-3.920350,-5.113071,0.015528
29509,2020-01-03,33,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.020682,0.018456,0.019834,0.019834,0.041881,0.113890,0.072009,13.585328,13.585328,0.0,-3.992360,-5.113071,0.015528
1782,2020-01-06,9,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.015154,0.008893,0.008893,0.008893,0.533024,0.533024,0.000000,9.430215,9.430215,0.0,-4.722503,-5.169039,0.005973
16454,2020-01-06,9,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.015154,0.010440,0.008893,0.008893,0.533024,0.372603,0.160421,10.217780,10.217780,0.0,-4.562082,-5.169039,0.005973
1783,2020-01-06,12,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.015421,0.009891,0.009891,0.009891,0.444151,0.444151,0.000000,9.945271,9.945271,0.0,-4.616146,-5.169039,0.005843
18086,2020-01-06,12,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.015421,0.011265,0.009891,0.009891,0.444151,0.314053,0.130097,10.613703,10.613703,0.0,-4.486049,-5.169039,0.005843
1784,2020-01-06,15,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.015746,0.011889,0.011889,0.011889,0.281028,0.281028,0.000000,10.903539,10.903539,0.0,-4.432166,-5.169039,0.005339
19718,2020-01-06,15,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.015746,0.013256,0.011889,0.011889,0.281028,0.172137,0.108891,11.513646,11.513646,0.0,-4.323274,-5.169039,0.005339
1785,2020-01-06,18,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.015963,0.012656,0.012656,0.012656,0.232122,0.232122,0.000000,11.250064,11.250064,0.0,-4.369593,-5.169039,0.007290
21350,2020-01-06,18,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.015963,0.013851,0.012656,0.012656,0.232122,0.141945,0.090177,11.768924,11.768924,0.0,-4.279415,-5.169039,0.007290
1786,2020-01-06,21,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.016924,0.014006,0.014006,0.014006,0.189215,0.189215,0.000000,11.834878,11.834878,0.0,-4.268239,-5.169039,0.012431
22982,2020-01-06,21,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.016924,0.015141,0.014006,0.014006,0.189215,0.111334,0.077882,12.304828,12.304828,0.0,-4.190357,-5.169039,0.012431
1787,2020-01-06,24,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.017645,0.014827,0.014827,0.014827,0.173988,0.173988,0.000000,12.176570,12.176570,0.0,-4.211313,-5.169039,0.013944
24614,2020-01-06,24,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.017645,0.015852,0.014827,0.014827,0.173988,0.107154,0.066833,12.590346,12.590346,0.0,-4.144480,-5.169039,0.013944
1788,2020-01-06,27,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.018258,0.015934,0.015934,0.015934,0.136112,0.136112,0.000000,12.623093,12.623093,0.0,-4.139285,-5.169039,0.013503
26246,2020-01-06,27,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.018258,0.016725,0.015934,0.015934,0.136112,0.087675,0.048437,12.932538,12.932538,0.0,-4.090847,-5.169039,0.013503
1789,2020-01-06,30,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.018772,0.020756,0.020756,0.020756,-0.100461,-0.100461,0.000000,14.406770,14.406770,0.0,-3.874944,-5.169039,0.016410
27878,2020-01-06,30,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.018772,0.018049,0.020756,0.020756,-0.100461,0.039246,0.139707,13.434750,13.434750,0.0,-4.014651,-5.169039,0.016410
1790,2020-01-06,33,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.019208,0.022245,0.022245,0.022245,-0.146794,-0.146794,0.000000,14.914909,14.914909,0.0,-3.805618,-5.169039,0.015696
29510,2020-01-06,33,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.019208,0.018328,0.022245,0.022245,-0.146794,0.046900,0.193694,13.538186,13.538186,0.0,-3.999312,-5.169039,0.015696
1791,2020-01-07,9,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.014890,0.009148,0.009148,0.009148,0.487150,0.487150,0.000000,9.564460,9.564460,0.0,-4.694232,-5.157230,0.006490
16455,2020-01-07,9,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.014890,0.010327,0.009148,0.009148,0.487150,0.365936,0.121214,10.162061,10.162061,0.0,-4.573018,-5.157230,0.006490
1792,2020-01-07,12,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.015349,0.010141,0.010141,0.010141,0.414466,0.414466,0.000000,10.070130,10.070130,0.0,-4.591193,-5.157230,0.005363
18087,2020-01-07,12,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.015349,0.011099,0.010141,0.010141,0.414466,0.324209,0.090257,10.534989,10.534989,0.0,-4.500936,-5.157230,0.005363
1793,2020-01-07,15,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.015759,0.012188,0.012188,0.012188,0.256937,0.256937,0.000000,11.040040,11.040040,0.0,-4.407283,-5.157230,0.005468
19719,2020-01-07,15,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.015759,0.013079,0.012188,0.012188,0.256937,0.186389,0.070548,11.436416,11.436416,0.0,-4.336735,-5.157230,0.005468
1794,2020-01-07,18,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.016286,0.012961,0.012961,0.012961,0.228332,0.228332,0.000000,11.384670,11.384670,0.0,-4.345805,-5.157230,0.006970
21351,2020-01-07,18,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.016286,0.013695,0.012961,0.012961,0.228332,0.173269,0.055063,11.702459,11.702459,0.0,-4.290742,-5.157230,0.006970
1795,2020-01-07,21,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.017096,0.014312,0.014312,0.014312,0.177744,0.177744,0.000000,11.963190,11.963190,0.0,-4.246672,-5.157230,0.012946
22983,2020-01-07,21,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.017096,0.014987,0.014312,0.014312,0.177744,0.131638,0.046106,12.242180,12.242180,0.0,-4.200566,-5.157230,0.012946
1796,2020-01-07,24,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.017703,0.015138,0.015138,0.015138,0.156556,0.156556,0.000000,12.303572,12.303572,0.0,-4.190561,-5.157230,0.014952
24615,2020-01-07,24,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_MIDDLE,False,0.017703,0.015710,0.015138,0.015138,0.156556,0.119423,0.037133,12.534141,12.534141,0.0,-4.153428,-5.157230,0.014952
1797,2020-01-07,27,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.018310,0.016204,0.016204,0.016204,0.122233,0.122233,0.000000,12.729371,12.729371,0.0,-4.122516,-5.157230,0.014145
26247,2020-01-07,27,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.018310,0.016519,0.016204,0.016204,0.122233,0.102983,0.019250,12.852485,12.852485,0.0,-4.103266,-5.157230,0.014145
1798,2020-01-07,30,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.018796,0.020511,0.020511,0.020511,-0.087316,-0.087316,0.000000,14.321720,14.321720,0.0,-3.886786,-5.157230,0.016589
27879,2020-01-07,30,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.018796,0.017858,0.020511,0.020511,-0.087316,0.051212,0.138528,13.363315,13.363315,0.0,-4.025314,-5.157230,0.016589
1799,2020-01-07,33,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.019221,0.021942,0.021942,0.021942,-0.132362,-0.132362,0.000000,14.812728,14.812728,0.0,-3.819367,-5.157230,0.015522
29511,2020-01-07,33,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,UNFROZEN_BACK_DIAGNOSTIC,True,0.019221,0.018221,0.021942,0.021942,-0.132362,0.053473,0.185835,13.498375,13.498375,0.0,-4.005202,-5.157230,0.015522
1800,2020-01-08,9,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.016191,0.009133,0.009133,0.009133,0.572555,0.572555,0.000000,9.556578,9.556578,0.0,-4.695881,-5.287940,0.006114
16456,2020-01-08,9,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.016191,0.009610,0.009133,0.009133,0.572555,0.521592,0.050964,9.803227,9.803227,0.0,-4.644917,-5.287940,0.006114
1801,2020-01-08,12,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.016585,0.010274,0.010274,0.010274,0.478937,0.478937,0.000000,10.135829,10.135829,0.0,-4.578187,-5.287940,0.004585
18088,2020-01-08,12,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.016585,0.010535,0.010274,0.010274,0.478937,0.453815,0.025122,10.263951,10.263951,0.0,-4.553065,-5.287940,0.004585
1802,2020-01-08,15,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_FRONT,False,0.016822,0.012540,0.012540,0.012540,0.293771,0.293771,0.000000,11.198119,11.198119,0.0,-4.378849,-5.287940,0.005517
19720,2020-01-08,15,2,unified_fds_no_min_return,unified_fds_no_min_return_oos_refit,candidate_fit,FIT_OK,RESEARCH_FRONT,False,0.016822,0.012745,0.012540,0.012540,0.293771,0.277547,0.016224,11.289328,11.289328,0.0,-4.362625,-5.287940,0.005517
1803,2020-01-08,18,1,existing_har_downside_v1,existing_har_downside_v1_forecast,existing_forecast,FIT_OK,RESEARCH_MIDDLE,False,0.017320,0.013511,0.013511,0.013511,0.248350,0.248350,0.000000,11.623734,11.623734,0.0,-4.304242,-5.287940,0.006452

====================================================================================================
COMMON panel reconstruction and duplicate checks
====================================================================================================
Duplicate trade_date × tenor rows: 29,376
Rows where model_vrp_log matches candidate forecast variance <= 1e-10: 14,688 / 29,376
Rows where model_vrp_log differs candidate forecast variance >  1e-10: 14,688 / 29,376

           abs_diff
count  2.937600e+04
mean   8.724609e-02
std    1.733978e-01
min    0.000000e+00
50%    8.459571e-07
90%    2.508973e-01
99%    7.334173e-01
99.9%  1.960430e+00
max    2.596017e+00

Categorical diagnostics:

COMMON — model_spec:

                       count  count
0   existing_har_downside_v1  14688
1  unified_fds_no_min_return  14688

COMMON — model_source:

                                 count  count
0    existing_har_downside_v1_forecast  14688
1  unified_fds_no_min_return_oos_refit  14688

COMMON — fit_status_candidate:

               count  count
0  existing_forecast  14688
1      candidate_fit  14688

COMMON — fit_status:

    count  count
0  FIT_OK  29376

COMMON — forecast_repair_scope:

                      count  count
0            RESEARCH_FRONT   9792
1           RESEARCH_MIDDLE   9792
2  UNFROZEN_BACK_DIAGNOSTIC   9792

COMMON — is_back_frozen:

   count  count
0  False  19584
1   True   9792

COMMON — is_research_tenor:

   count  count
0   True  19584
1  False   9792

COMMON — tenor_bucket:

    count  count
0   Front   9792
1  Middle   9792
2    Back   9792

COMMON — test_year:

    count  count
0  2020.0   4554
1  2021.0   4536
2  2024.0   4536
3  2022.0   4518
4  2023.0   4500
5  2025.0   4500
6  2026.0   2232

COMMON — test_year_candidate:

   count  count
0   2020   4554
1   2021   4536
2   2024   4536
3   2022   4518
4   2023   4500
5   2025   4500
6   2026   2232

COMMON — selected_alpha:

   count  count
0  100.0  28364
1    1.0   1012

COMMON — selected_alpha_candidate:

   count  count
0  100.0  23850
1  300.0   3511
2   10.0   1509
3    1.0    506

COMMON — train_rows_used:

     count  count
0    315.0    506
1    314.0    506
2    311.0    506
3    309.0    506
4    307.0    506
5    304.0    506
6    303.0    506
7    300.0    506
8    299.0    506
9    569.0    504
10   567.0    504
11   565.0    504
12   563.0    504
13   560.0    504
14   559.0    504
15   556.0    504
16   555.0    504
17   552.0    504
18  1309.0    504
19  1307.0    504

COMMON — train_rows_used_candidate:

     count  count
0    315.0    506
1    314.0    506
2    311.0    506
3    309.0    506
4    307.0    506
5    304.0    506
6    303.0    506
7    300.0    506
8    299.0    506
9    569.0    504
10   567.0    504
11   565.0    504
12   563.0    504
13   560.0    504
14   559.0    504
15   556.0    504
16   555.0    504
17   552.0    504
18  1309.0    504
19  1307.0    504

====================================================================================================
DIAGNOSTIC panel reconstruction and duplicate checks
====================================================================================================
Duplicate trade_date × tenor rows: 29,376
Rows where model_vrp_log matches candidate forecast variance <= 1e-10: 14,688 / 29,376
Rows where model_vrp_log differs candidate forecast variance >  1e-10: 14,688 / 29,376

           abs_diff
count  2.937600e+04
mean   8.724609e-02
std    1.733978e-01
min    0.000000e+00
50%    8.459571e-07
90%    2.508973e-01
99%    7.334173e-01
99.9%  1.960430e+00
max    2.596017e+00

Categorical diagnostics:

DIAGNOSTIC — model_spec:

                       count  count
0   existing_har_downside_v1  14688
1  unified_fds_no_min_return  14688

DIAGNOSTIC — model_source:

                                 count  count
0    existing_har_downside_v1_forecast  14688
1  unified_fds_no_min_return_oos_refit  14688

DIAGNOSTIC — fit_status_candidate:

               count  count
0  existing_forecast  14688
1      candidate_fit  14688

DIAGNOSTIC — fit_status:

    count  count
0  FIT_OK  29376

DIAGNOSTIC — forecast_repair_scope:

                      count  count
0            RESEARCH_FRONT   9792
1           RESEARCH_MIDDLE   9792
2  UNFROZEN_BACK_DIAGNOSTIC   9792

DIAGNOSTIC — is_back_frozen:

   count  count
0  False  19584
1   True   9792

DIAGNOSTIC — is_research_tenor:

   count  count
0   True  19584
1  False   9792

DIAGNOSTIC — tenor_bucket:

    count  count
0   Front   9792
1  Middle   9792
2    Back   9792

DIAGNOSTIC — test_year:

    count  count
0  2020.0   4554
1  2021.0   4536
2  2024.0   4536
3  2022.0   4518
4  2023.0   4500
5  2025.0   4500
6  2026.0   2232

DIAGNOSTIC — test_year_candidate:

   count  count
0   2020   4554
1   2021   4536
2   2024   4536
3   2022   4518
4   2023   4500
5   2025   4500
6   2026   2232

DIAGNOSTIC — selected_alpha:

   count  count
0  100.0  28364
1    1.0   1012

DIAGNOSTIC — selected_alpha_candidate:

   count  count
0  100.0  23850
1  300.0   3511
2   10.0   1509
3    1.0    506

DIAGNOSTIC — train_rows_used:

     count  count
0    315.0    506
1    311.0    506
2    314.0    506
3    307.0    506
4    309.0    506
5    303.0    506
6    304.0    506
7    300.0    506
8    299.0    506
9    560.0    504
10  1316.0    504
11   565.0    504
12  1317.0    504
13   567.0    504
14  1320.0    504
15  1313.0    504
16   559.0    504
17  1309.0    504
18  1312.0    504
19   552.0    504

DIAGNOSTIC — train_rows_used_candidate:

     count  count
0    315.0    506
1    311.0    506
2    314.0    506
3    307.0    506
4    309.0    506
5    303.0    506
6    304.0    506
7    300.0    506
8    299.0    506
9    560.0    504
10  1316.0    504
11   565.0    504
12  1317.0    504
13   567.0    504
14  1320.0    504
15  1313.0    504
16   559.0    504
17  1309.0    504
18  1312.0    504
19   552.0    504

====================================================================================================
Candidate dedupe methods
====================================================================================================

----------------------------------------------------------------------------------------------------
dedup_by_candidate_vrp
----------------------------------------------------------------------------------------------------
Rows: 16,452
Duplicate keys: 0
Date range: 2019-01-02 to 2026-07-01
Tenors: [9, 12, 15, 18, 21, 24, 27, 30, 33]
VRP candidate reconstruction rows <= 1e-10: 16,452 / 16,452
VRP candidate reconstruction rows >  1e-10: 0 / 16,452

       abs_diff
count   16452.0
mean        0.0
std         0.0
min         0.0
50%         0.0
90%         0.0
99%         0.0
99.9%       0.0
max         0.0

----------------------------------------------------------------------------------------------------
dedup_by_candidate_vol
----------------------------------------------------------------------------------------------------
Rows: 16,452
Duplicate keys: 0
Date range: 2019-01-02 to 2026-07-01
Tenors: [9, 12, 15, 18, 21, 24, 27, 30, 33]
VRP candidate reconstruction rows <= 1e-10: 16,452 / 16,452
VRP candidate reconstruction rows >  1e-10: 0 / 16,452

       abs_diff
count   16452.0
mean        0.0
std         0.0
min         0.0
50%         0.0
90%         0.0
99%         0.0
99.9%       0.0
max         0.0

====================================================================================================
Saved duplicate diagnostic preview
====================================================================================================
C:\Users\patri\vrp_project\data\audit\vrp_final_signal\07A_duplicate_block_diagnostic_preview.csv

In [5]:
from pathlib import Path
from datetime import datetime
import json
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", None)

# ======================================================================================
# Scope
# ======================================================================================

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

FORECAST_PANEL_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1"
    r"\07A_unified_fds_no_min_return_oos_forecast_panel_20200102_20260701_20260704_203242.parquet"
)

SIGNAL_RULES_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1"
    r"\09S_core_secondary_consistent_secondary_locked_rules_long_20260705_221829.parquet"
)

SIZING_RULES_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1"
    r"\15S_final_one_trade_per_day_naked_put_sizing_lock_rules_20260706_142800.parquet"
)

SELECTION_RULE_PATH = Path(
    r"C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1"
    r"\15S_final_one_trade_per_day_naked_put_selection_rule_20260706_142800.json"
)

RV21D_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\market_data\spy_realized_vol_history_v1.parquet"
)

LOCKED_16S_SELECTED_PATH = Path(
    r"C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1"
    r"\16S_locked_cumulative_pnl_timeseries_20260706_143802.parquet"
)

AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "vrp_final_signal"
AUDIT_DIR.mkdir(parents=True, exist_ok=True)

RUN_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

Z_3M_WINDOW = 63
Z_1Y_WINDOW = 252
Z_DDOF = 1

EXPECTED_TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

print("=" * 100)
print("VRP final signal logic dry run")
print("=" * 100)
print("No production files will be written.")
print(f"Run timestamp: {RUN_TIMESTAMP}")

# ======================================================================================
# Source existence
# ======================================================================================

paths = {
    "forecast_panel": FORECAST_PANEL_PATH,
    "signal_rules": SIGNAL_RULES_PATH,
    "sizing_rules": SIZING_RULES_PATH,
    "selection_rule": SELECTION_RULE_PATH,
    "rv21d": RV21D_PATH,
    "locked_16s_selected_optional": LOCKED_16S_SELECTED_PATH,
}

print("\n" + "=" * 100)
print("Source file existence")
print("=" * 100)

for name, path in paths.items():
    print(f"{name:32s} exists={path.exists()}  path={path}")

required_missing = [
    name for name, path in paths.items()
    if name != "locked_16s_selected_optional" and not path.exists()
]

if required_missing:
    raise FileNotFoundError(f"Missing required files: {required_missing}")

# ======================================================================================
# Load sources
# ======================================================================================

forecast_raw = pd.read_parquet(FORECAST_PANEL_PATH)
signal_rules_raw = pd.read_parquet(SIGNAL_RULES_PATH)
sizing_rules_raw = pd.read_parquet(SIZING_RULES_PATH)
rv21d_raw = pd.read_parquet(RV21D_PATH)

with open(SELECTION_RULE_PATH, "r", encoding="utf-8") as f:
    selection_rule_json = json.load(f)

locked_16s = None
if LOCKED_16S_SELECTED_PATH.exists():
    locked_16s = pd.read_parquet(LOCKED_16S_SELECTED_PATH)

# Normalize source dtypes
forecast_raw["trade_date"] = pd.to_datetime(forecast_raw["trade_date"], errors="coerce")
forecast_raw["tenor"] = pd.to_numeric(forecast_raw["tenor"], errors="coerce").astype("Int64")

rv21d_raw["trade_date"] = pd.to_datetime(rv21d_raw["trade_date"], errors="coerce")

signal_rules_raw["tenor"] = pd.to_numeric(signal_rules_raw["tenor"], errors="coerce").astype("Int64")
sizing_rules_raw["tenor"] = pd.to_numeric(sizing_rules_raw["tenor"], errors="coerce").astype("Int64")

# ======================================================================================
# Filter to unified FDS candidate rows
# ======================================================================================

base = forecast_raw[
    (forecast_raw["model_spec"].astype(str) == "unified_fds_no_min_return")
    & (forecast_raw["model_source"].astype(str) == "unified_fds_no_min_return_oos_refit")
    & (forecast_raw["fit_status_candidate"].astype(str) == "candidate_fit")
].copy()

base = base.sort_values(["trade_date", "tenor"]).reset_index(drop=True)

print("\n" + "=" * 100)
print("Unified FDS candidate base")
print("=" * 100)
print(f"Rows: {len(base):,}")
print(f"Date range: {base['trade_date'].min().date()} to {base['trade_date'].max().date()}")
print(f"Unique dates: {base['trade_date'].nunique():,}")
print(f"Tenors: {sorted(base['tenor'].dropna().astype(int).unique().tolist())}")
print(f"Duplicate trade_date × tenor rows: {base.duplicated(['trade_date', 'tenor'], keep=False).sum():,}")

# ======================================================================================
# Recompute final denominator fields
# ======================================================================================

base["implied_variance_final"] = base["implied_variance"].astype(float)
base["vix_style_vol_final"] = base["vix_style_vol"].astype(float)
base["forecast_variance_final"] = base["forecast_variance_candidate"].astype(float)
base["forecast_vol_final"] = np.sqrt(base["forecast_variance_final"]) * 100.0
base["model_vrp_log_final"] = np.log(base["implied_variance_final"] / base["forecast_variance_final"])
base["rsi14_final"] = base["RSI14"].astype(float)

base["source_model_vrp_log"] = base["model_vrp_log"].astype(float)
base["source_model_vrp_z_3m"] = base["model_vrp_z_3m"].astype(float)
base["source_model_vrp_z_1y"] = base["model_vrp_z_1y"].astype(float)

base["source_vs_final_model_vrp_log_diff"] = (
    base["source_model_vrp_log"] - base["model_vrp_log_final"]
)

# ======================================================================================
# Recompute prior-only z-scores from unified final VRP log
# ======================================================================================

base = base.sort_values(["tenor", "trade_date"]).copy()

def prior_only_z(series: pd.Series, window: int, ddof: int = 1) -> pd.Series:
    prior = series.shift(1)
    mean = prior.rolling(window=window, min_periods=window).mean()
    std = prior.rolling(window=window, min_periods=window).std(ddof=ddof)
    return (series - mean) / std

base["z_3m_final"] = (
    base.groupby("tenor", group_keys=False)["model_vrp_log_final"]
    .apply(lambda s: prior_only_z(s, Z_3M_WINDOW, Z_DDOF))
)

base["z_1y_final"] = (
    base.groupby("tenor", group_keys=False)["model_vrp_log_final"]
    .apply(lambda s: prior_only_z(s, Z_1Y_WINDOW, Z_DDOF))
)

base = base.sort_values(["trade_date", "tenor"]).reset_index(drop=True)

print("\n" + "=" * 100)
print("Final recomputed field checks")
print("=" * 100)

print("Source model_vrp_log vs recomputed model_vrp_log_final absolute diff:")
display(
    base["source_vs_final_model_vrp_log_diff"]
    .abs()
    .describe(percentiles=[0.5, 0.9, 0.99, 0.999])
    .to_frame("abs_diff")
)

print("\nZ-score non-null counts by tenor:")
z_summary = (
    base.groupby("tenor")
    .agg(
        rows=("trade_date", "size"),
        z_3m_non_null=("z_3m_final", lambda s: int(s.notna().sum())),
        z_1y_non_null=("z_1y_final", lambda s: int(s.notna().sum())),
        first_date=("trade_date", "min"),
        last_date=("trade_date", "max"),
    )
    .reset_index()
)
z_summary["first_date"] = z_summary["first_date"].dt.date.astype(str)
z_summary["last_date"] = z_summary["last_date"].dt.date.astype(str)
display(z_summary)

# ======================================================================================
# Join canonical RV21D
# ======================================================================================

rv21d = rv21d_raw[["trade_date", "spy_close", "rv21d_vol_pct"]].copy()
rv21d["rv21d_vol_pct_final"] = rv21d["rv21d_vol_pct"].astype(float)

base = base.merge(
    rv21d[["trade_date", "spy_close", "rv21d_vol_pct_final"]],
    on="trade_date",
    how="left",
    validate="many_to_one",
)

print("\n" + "=" * 100)
print("RV21D join")
print("=" * 100)
print(f"Rows after RV21D join: {len(base):,}")
print(f"Missing rv21d_vol_pct_final: {base['rv21d_vol_pct_final'].isna().sum():,}")
print(f"Latest date: {base['trade_date'].max().date()}")
display(
    base.sort_values(["trade_date", "tenor"])
    .tail(18)[["trade_date", "tenor", "spy_close", "rv21d_vol_pct_final"]]
)

# ======================================================================================
# Prepare active signal and sizing rules
# ======================================================================================

signal_rules = signal_rules_raw.copy()

if signal_rules["include_tenor"].dtype != bool:
    signal_rules["include_tenor"] = signal_rules["include_tenor"].astype(str).str.lower().map(
        {"true": True, "1": True, "yes": True, "false": False, "0": False, "no": False}
    ).fillna(False)

active_rules = signal_rules[
    (signal_rules["include_tenor"] == True)
    & (signal_rules["signal_layer"].isin(["Core", "Secondary"]))
].copy()

sizing_rules = sizing_rules_raw.copy()

if "is_locked" in sizing_rules.columns:
    if sizing_rules["is_locked"].dtype != bool:
        sizing_rules["is_locked"] = sizing_rules["is_locked"].astype(str).str.lower().map(
            {"true": True, "1": True, "yes": True, "false": False, "0": False, "no": False}
        ).fillna(False)

if "is_final_sizing_lock" in sizing_rules.columns:
    if sizing_rules["is_final_sizing_lock"].dtype != bool:
        sizing_rules["is_final_sizing_lock"] = sizing_rules["is_final_sizing_lock"].astype(str).str.lower().map(
            {"true": True, "1": True, "yes": True, "false": False, "0": False, "no": False}
        ).fillna(False)

active_sizing = sizing_rules[
    (sizing_rules["signal_layer"].isin(["Core", "Secondary"]))
    & (sizing_rules.get("is_locked", True) == True)
    & (sizing_rules.get("is_final_sizing_lock", True) == True)
].copy()

print("\n" + "=" * 100)
print("Active rules and sizing")
print("=" * 100)

print(f"Active signal rule rows: {len(active_rules):,}")
display(
    active_rules[
        [
            "signal_layer",
            "signal_priority",
            "tenor_bucket",
            "tenor",
            "model_vrp_log_min",
            "model_vrp_z_3m_min",
            "model_vrp_z_1y_min",
            "RSI14_max",
            "rv21d_vol_pct_min",
        ]
    ].sort_values(["signal_priority", "tenor"])
)

print(f"\nActive sizing rows: {len(active_sizing):,}")
display(
    active_sizing[
        [
            "sleeve_id",
            "signal_layer",
            "tenor_bucket",
            "tenor",
            "locked_size_pct",
            "sizing_quality_score",
            "win_rate",
            "pnl_per_day_expected_loss_1pct_positive",
            "signal_layer_order",
            "tenor_bucket_order",
            "display_order",
        ]
    ].sort_values(["signal_layer_order", "tenor"])
)

# ======================================================================================
# Apply signal thresholds
# ======================================================================================

candidate_base_cols = [
    "trade_date",
    "tenor",
    "tenor_bucket",
    "implied_variance_final",
    "vix_style_vol_final",
    "forecast_variance_final",
    "forecast_vol_final",
    "model_vrp_log_final",
    "z_3m_final",
    "z_1y_final",
    "rsi14_final",
    "rv21d_vol_pct_final",
    "spy_close",
    "model_spec",
    "model_source",
    "fit_status_candidate",
    "forecast_repair_scope",
]

candidate_base_cols = [c for c in candidate_base_cols if c in base.columns]

candidates = base[candidate_base_cols].merge(
    active_rules[
        [
            "signal_layer",
            "signal_priority",
            "tenor",
            "tenor_bucket",
            "model_vrp_log_min",
            "model_vrp_z_3m_min",
            "model_vrp_z_1y_min",
            "RSI14_max",
            "rv21d_vol_pct_min",
            "comparison_operator_model_vrp_log",
            "comparison_operator_model_vrp_z_3m",
            "comparison_operator_model_vrp_z_1y",
            "comparison_operator_RSI14",
            "comparison_operator_rv21d_vol_pct",
            "stack_lock_version",
            "stack_lock_decision_id",
            "lock_version",
            "lock_decision_id",
        ]
    ],
    on=["tenor", "tenor_bucket"],
    how="inner",
    validate="many_to_many",
)

supported_ops = {
    "comparison_operator_model_vrp_log": [">"],
    "comparison_operator_model_vrp_z_3m": [">"],
    "comparison_operator_model_vrp_z_1y": [">"],
    "comparison_operator_RSI14": ["<"],
    "comparison_operator_rv21d_vol_pct": [">"],
}

for op_col, allowed in supported_ops.items():
    actual = sorted(candidates[op_col].dropna().astype(str).unique().tolist())
    if actual != allowed:
        raise RuntimeError(f"Unexpected operators in {op_col}: {actual}. Expected {allowed}")

candidates["pass_model_vrp_log"] = candidates["model_vrp_log_final"] > candidates["model_vrp_log_min"]
candidates["pass_z_3m"] = candidates["z_3m_final"] > candidates["model_vrp_z_3m_min"]
candidates["pass_z_1y"] = candidates["z_1y_final"] > candidates["model_vrp_z_1y_min"]
candidates["pass_rsi14"] = candidates["rsi14_final"] < candidates["RSI14_max"]
candidates["pass_rv21d"] = candidates["rv21d_vol_pct_final"] > candidates["rv21d_vol_pct_min"]

pass_cols = [
    "pass_model_vrp_log",
    "pass_z_3m",
    "pass_z_1y",
    "pass_rsi14",
    "pass_rv21d",
]

candidates["qualified"] = candidates[pass_cols].all(axis=1)

# Join sizing to every candidate
sizing_join_cols = [
    "sleeve_id",
    "signal_layer",
    "tenor_bucket",
    "tenor",
    "locked_size_pct",
    "locked_size_label",
    "sizing_quality_score",
    "win_rate",
    "pnl_per_day_expected_loss_1pct_positive",
    "signal_layer_order",
    "tenor_bucket_order",
    "display_order",
    "sizing_lock_version",
    "sizing_lock_decision_id",
    "program_type",
    "pricing_basis_label",
    "not_defined_spread_sizing",
]

sizing_join_cols = [c for c in sizing_join_cols if c in active_sizing.columns]

candidates = candidates.merge(
    active_sizing[sizing_join_cols],
    on=["signal_layer", "tenor_bucket", "tenor"],
    how="left",
    validate="many_to_one",
)

missing_size_all = candidates["locked_size_pct"].isna().sum()
missing_size_qualified = candidates.loc[candidates["qualified"], "locked_size_pct"].isna().sum()

if missing_size_qualified > 0:
    raise RuntimeError(f"Qualified candidates missing sizing rows: {missing_size_qualified:,}")

print("\n" + "=" * 100)
print("Signal qualification counts")
print("=" * 100)

print(f"Candidate rows: {len(candidates):,}")
print(f"Qualified candidate rows: {candidates['qualified'].sum():,}")
print(f"Missing locked_size_pct among all candidates: {missing_size_all:,}")
print(f"Missing locked_size_pct among qualified candidates: {missing_size_qualified:,}")

pass_dist = (
    candidates[candidates["qualified"]]
    .groupby(["signal_layer", "tenor_bucket", "tenor"])
    .size()
    .reset_index(name="qualified_rows")
    .sort_values(["signal_layer", "tenor"])
)

display(pass_dist)

# ======================================================================================
# Apply 15S one-trade-per-day selection rule
# ======================================================================================

qualified = candidates[candidates["qualified"]].copy()

qualified = qualified.sort_values(
    [
        "trade_date",
        "locked_size_pct",
        "signal_layer_order",
        "sizing_quality_score",
        "win_rate",
        "pnl_per_day_expected_loss_1pct_positive",
        "tenor",
        "display_order",
    ],
    ascending=[
        True,
        False,  # highest locked size
        True,   # Core before Secondary if size tied
        False,  # higher sizing quality
        False,  # higher win rate
        True,   # lower positive 1% expected loss
        False,  # longer tenor
        True,
    ],
).reset_index(drop=True)

qualified["_selection_rank"] = qualified.groupby("trade_date").cumcount() + 1
selected = qualified[qualified["_selection_rank"] == 1].copy()

print("\n" + "=" * 100)
print("Selected trades — dry run")
print("=" * 100)

print(f"Selected rows: {len(selected):,}")
if len(selected) > 0:
    print(f"Selected date range: {selected['trade_date'].min().date()} to {selected['trade_date'].max().date()}")
    print(f"Max selected rows per date: {selected.groupby('trade_date').size().max()}")

selected_dist = (
    selected.groupby(["signal_layer", "tenor_bucket", "tenor", "sleeve_id", "locked_size_pct"])
    .size()
    .reset_index(name="selected_count")
    .sort_values(["signal_layer", "tenor"])
)

display(selected_dist)

selected_by_year = (
    selected.assign(year=selected["trade_date"].dt.year)
    .groupby(["year", "signal_layer", "tenor"])
    .size()
    .reset_index(name="selected_count")
    .sort_values(["year", "signal_layer", "tenor"])
)

print("\nSelected trades by year/layer/tenor:")
display(selected_by_year)

# ======================================================================================
# Build dry-run panel view
# ======================================================================================

panel = base.copy()

core_pass = (
    candidates[(candidates["signal_layer"] == "Core") & (candidates["qualified"])]
    [["trade_date", "tenor"]]
    .drop_duplicates()
    .assign(core_pass=True)
)

secondary_pass = (
    candidates[(candidates["signal_layer"] == "Secondary") & (candidates["qualified"])]
    [["trade_date", "tenor"]]
    .drop_duplicates()
    .assign(secondary_pass=True)
)

panel = panel.merge(core_pass, on=["trade_date", "tenor"], how="left")
panel = panel.merge(secondary_pass, on=["trade_date", "tenor"], how="left")

panel["core_pass"] = panel["core_pass"].fillna(False).astype(bool)
panel["secondary_pass"] = panel["secondary_pass"].fillna(False).astype(bool)

selected_marker = selected[
    [
        "trade_date",
        "tenor",
        "signal_layer",
        "tenor_bucket",
        "sleeve_id",
        "locked_size_pct",
        "locked_size_label",
        "sizing_quality_score",
        "win_rate",
        "pnl_per_day_expected_loss_1pct_positive",
    ]
].copy()

selected_marker = selected_marker.rename(
    columns={
        "signal_layer": "selected_layer",
        "tenor_bucket": "selected_tenor_bucket",
        "sleeve_id": "selected_sleeve_id",
        "locked_size_pct": "selected_size_pct",
        "locked_size_label": "selected_size_label",
        "sizing_quality_score": "selected_sizing_quality_score",
        "win_rate": "selected_win_rate",
        "pnl_per_day_expected_loss_1pct_positive": "selected_1pct_expected_loss_positive",
    }
)

panel = panel.merge(
    selected_marker,
    on=["trade_date", "tenor"],
    how="left",
    validate="one_to_one",
)

panel["selected"] = panel["selected_layer"].notna()
panel["selected_tenor"] = np.where(panel["selected"], panel["tenor"], np.nan)

final_panel_cols = [
    "trade_date",
    "tenor",
    "tenor_bucket",
    "model_spec",
    "model_source",
    "fit_status_candidate",
    "forecast_repair_scope",
    "implied_variance_final",
    "vix_style_vol_final",
    "forecast_variance_final",
    "forecast_vol_final",
    "model_vrp_log_final",
    "z_3m_final",
    "z_1y_final",
    "rsi14_final",
    "rv21d_vol_pct_final",
    "spy_close",
    "source_model_vrp_log",
    "source_model_vrp_z_3m",
    "source_model_vrp_z_1y",
    "source_vs_final_model_vrp_log_diff",
    "core_pass",
    "secondary_pass",
    "selected",
    "selected_layer",
    "selected_tenor_bucket",
    "selected_tenor",
    "selected_sleeve_id",
    "selected_size_pct",
    "selected_size_label",
    "selected_sizing_quality_score",
    "selected_win_rate",
    "selected_1pct_expected_loss_positive",
]

final_panel_cols = [c for c in final_panel_cols if c in panel.columns]
panel_out = panel[final_panel_cols].copy()

# ======================================================================================
# Compare to locked 16S selected artifact, if available
# ======================================================================================

comparison_summary = {}
comparison_detail = pd.DataFrame()

print("\n" + "=" * 100)
print("Comparison to locked 16S selected artifact")
print("=" * 100)

if locked_16s is None:
    print("16S artifact not found; skipping comparison.")
else:
    locked = locked_16s.copy()
    if "trade_date" in locked.columns:
        locked["trade_date"] = pd.to_datetime(locked["trade_date"], errors="coerce")
    
    print(f"16S rows: {len(locked):,}")
    print("16S columns:")
    for c in locked.columns:
        print(f"  {c}")

    # Column detection
    locked_layer_col = None
    for c in ["signal_layer", "selected_layer", "layer"]:
        if c in locked.columns:
            locked_layer_col = c
            break

    locked_tenor_col = None
    for c in ["tenor", "selected_tenor", "dte"]:
        if c in locked.columns:
            locked_tenor_col = c
            break

    if locked_layer_col is None or locked_tenor_col is None:
        print("Could not detect locked 16S layer/tenor columns. Skipping exact match comparison.")
    else:
        selected_compare = selected[
            ["trade_date", "signal_layer", "tenor", "sleeve_id", "locked_size_pct"]
        ].rename(
            columns={
                "signal_layer": "dry_signal_layer",
                "tenor": "dry_tenor",
                "sleeve_id": "dry_sleeve_id",
                "locked_size_pct": "dry_locked_size_pct",
            }
        )

        locked_compare_cols = ["trade_date", locked_layer_col, locked_tenor_col]
        if "sleeve_id" in locked.columns:
            locked_compare_cols.append("sleeve_id")
        if "locked_size_pct" in locked.columns:
            locked_compare_cols.append("locked_size_pct")

        locked_compare = locked[locked_compare_cols].copy()
        locked_compare = locked_compare.rename(
            columns={
                locked_layer_col: "locked_signal_layer",
                locked_tenor_col: "locked_tenor",
                "sleeve_id": "locked_sleeve_id",
                "locked_size_pct": "locked_size_pct",
            }
        )

        locked_compare["locked_tenor"] = pd.to_numeric(locked_compare["locked_tenor"], errors="coerce")
        selected_compare["dry_tenor"] = pd.to_numeric(selected_compare["dry_tenor"], errors="coerce")

        comparison_detail = locked_compare.merge(
            selected_compare,
            on="trade_date",
            how="outer",
            indicator=True,
        )

        comparison_detail["layer_match"] = (
            comparison_detail["locked_signal_layer"].astype("string")
            == comparison_detail["dry_signal_layer"].astype("string")
        )

        comparison_detail["tenor_match"] = (
            comparison_detail["locked_tenor"].astype("float")
            == comparison_detail["dry_tenor"].astype("float")
        )

        comparison_detail["exact_match"] = (
            (comparison_detail["_merge"] == "both")
            & comparison_detail["layer_match"]
            & comparison_detail["tenor_match"]
        )

        comparison_summary = {
            "locked_rows": int(len(locked_compare)),
            "dry_selected_rows": int(len(selected_compare)),
            "both_dates": int((comparison_detail["_merge"] == "both").sum()),
            "locked_only_dates": int((comparison_detail["_merge"] == "left_only").sum()),
            "dry_only_dates": int((comparison_detail["_merge"] == "right_only").sum()),
            "exact_layer_tenor_matches": int(comparison_detail["exact_match"].sum()),
            "common_date_mismatches": int(
                ((comparison_detail["_merge"] == "both") & (~comparison_detail["exact_match"])).sum()
            ),
        }

        print(json.dumps(comparison_summary, indent=2))

        print("\nLocked 16S distribution:")
        display(
            locked_compare
            .groupby(["locked_signal_layer", "locked_tenor"])
            .size()
            .reset_index(name="locked_count")
            .sort_values(["locked_signal_layer", "locked_tenor"])
        )

        print("\nDry-run selected distribution:")
        display(
            selected_compare
            .groupby(["dry_signal_layer", "dry_tenor"])
            .size()
            .reset_index(name="dry_count")
            .sort_values(["dry_signal_layer", "dry_tenor"])
        )

        print("\nSample comparison mismatches:")
        display(
            comparison_detail[
                (comparison_detail["_merge"] != "both") | (~comparison_detail["exact_match"])
            ]
            .sort_values("trade_date")
            .head(100)
        )

# ======================================================================================
# Validation
# ======================================================================================

validation_rows = []

def add_check(check, status, detail):
    validation_rows.append(
        {
            "check": check,
            "status": "PASS" if bool(status) else "FAIL",
            "detail": detail,
        }
    )

add_check(
    "filtered_to_unified_fds_candidate_rows",
    len(base) > 0
    and set(base["model_spec"].astype(str).unique()) == {"unified_fds_no_min_return"}
    and set(base["model_source"].astype(str).unique()) == {"unified_fds_no_min_return_oos_refit"}
    and set(base["fit_status_candidate"].astype(str).unique()) == {"candidate_fit"},
    f"rows={len(base):,}",
)

add_check(
    "one_row_per_trade_date_tenor",
    panel_out.duplicated(["trade_date", "tenor"], keep=False).sum() == 0,
    f"duplicate_rows={panel_out.duplicated(['trade_date', 'tenor'], keep=False).sum():,}",
)

actual_tenors = sorted(panel_out["tenor"].dropna().astype(int).unique().tolist())
add_check(
    "expected_tenor_grid",
    actual_tenors == EXPECTED_TENORS,
    f"actual_tenors={actual_tenors}",
)

add_check(
    "positive_implied_and_forecast_variance",
    (panel_out["implied_variance_final"] > 0).all()
    and (panel_out["forecast_variance_final"] > 0).all(),
    "implied_variance_final and forecast_variance_final must be positive",
)

forecast_vol_diff = (
    panel_out["forecast_vol_final"]
    - np.sqrt(panel_out["forecast_variance_final"]) * 100
).abs()

add_check(
    "forecast_vol_reconstruction",
    (forecast_vol_diff <= 1e-10).all(),
    f"max_abs_diff={forecast_vol_diff.max()}",
)

vrp_log_diff = (
    panel_out["model_vrp_log_final"]
    - np.log(panel_out["implied_variance_final"] / panel_out["forecast_variance_final"])
).abs()

add_check(
    "model_vrp_log_final_reconstruction",
    (vrp_log_diff <= 1e-10).all(),
    f"max_abs_diff={vrp_log_diff.max()}",
)

add_check(
    "rv21d_join_complete",
    panel_out["rv21d_vol_pct_final"].notna().all(),
    f"missing={panel_out['rv21d_vol_pct_final'].isna().sum():,}",
)

add_check(
    "active_signal_rule_count",
    len(active_rules) == 13,
    f"active_rules={len(active_rules):,}",
)

add_check(
    "active_sizing_rule_count",
    len(active_sizing) == 13,
    f"active_sizing={len(active_sizing):,}",
)

add_check(
    "qualified_candidates_have_sizing",
    missing_size_qualified == 0,
    f"missing_size_qualified={missing_size_qualified:,}",
)

max_selected_per_date = selected.groupby("trade_date").size().max() if len(selected) > 0 else 0

add_check(
    "max_one_selected_trade_per_day",
    max_selected_per_date <= 1,
    f"max_selected_per_date={max_selected_per_date}",
)

validation = pd.DataFrame(validation_rows)

print("\n" + "=" * 100)
print("Dry-run validation")
print("=" * 100)
display(validation)

if (validation["status"] == "FAIL").any():
    print("Validation failures found. Do not proceed to production script.")
else:
    print("All dry-run hard validations passed.")

# ======================================================================================
# Save audit outputs
# ======================================================================================

panel_audit_path = AUDIT_DIR / f"vrp_final_signal_logic_dry_run_panel_{RUN_TIMESTAMP}.csv"
selected_audit_path = AUDIT_DIR / f"vrp_final_signal_logic_dry_run_selected_{RUN_TIMESTAMP}.csv"
candidates_audit_path = AUDIT_DIR / f"vrp_final_signal_logic_dry_run_candidates_{RUN_TIMESTAMP}.csv"
validation_audit_path = AUDIT_DIR / f"vrp_final_signal_logic_dry_run_validation_{RUN_TIMESTAMP}.csv"
selected_dist_path = AUDIT_DIR / f"vrp_final_signal_logic_dry_run_selected_distribution_{RUN_TIMESTAMP}.csv"
comparison_path = AUDIT_DIR / f"vrp_final_signal_logic_dry_run_16S_comparison_{RUN_TIMESTAMP}.csv"
manifest_path = AUDIT_DIR / f"vrp_final_signal_logic_dry_run_manifest_{RUN_TIMESTAMP}.json"

panel_out.to_csv(panel_audit_path, index=False)
selected.to_csv(selected_audit_path, index=False)
candidates.to_csv(candidates_audit_path, index=False)
validation.to_csv(validation_audit_path, index=False)
selected_dist.to_csv(selected_dist_path, index=False)

if not comparison_detail.empty:
    comparison_detail.to_csv(comparison_path, index=False)

manifest = {
    "run_timestamp": RUN_TIMESTAMP,
    "run_type": "final_signal_logic_dry_run_only",
    "no_production_outputs_written": True,
    "forecast_panel_path": str(FORECAST_PANEL_PATH),
    "signal_rules_path": str(SIGNAL_RULES_PATH),
    "sizing_rules_path": str(SIZING_RULES_PATH),
    "selection_rule_path": str(SELECTION_RULE_PATH),
    "rv21d_path": str(RV21D_PATH),
    "locked_16s_selected_path": str(LOCKED_16S_SELECTED_PATH) if LOCKED_16S_SELECTED_PATH.exists() else None,
    "z_3m_window": Z_3M_WINDOW,
    "z_1y_window": Z_1Y_WINDOW,
    "z_ddof": Z_DDOF,
    "base_rows": int(len(base)),
    "panel_rows": int(len(panel_out)),
    "candidate_rows": int(len(candidates)),
    "qualified_candidate_rows": int(candidates["qualified"].sum()),
    "selected_rows": int(len(selected)),
    "selected_min_date": str(selected["trade_date"].min().date()) if len(selected) > 0 else None,
    "selected_max_date": str(selected["trade_date"].max().date()) if len(selected) > 0 else None,
    "comparison_summary": comparison_summary,
    "validation": validation.to_dict(orient="records"),
    "audit_outputs": {
        "panel": str(panel_audit_path),
        "selected": str(selected_audit_path),
        "candidates": str(candidates_audit_path),
        "validation": str(validation_audit_path),
        "selected_distribution": str(selected_dist_path),
        "comparison": str(comparison_path) if not comparison_detail.empty else None,
    },
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2)

print("\n" + "=" * 100)
print("Saved dry-run audit outputs")
print("=" * 100)
print(panel_audit_path)
print(selected_audit_path)
print(candidates_audit_path)
print(validation_audit_path)
print(selected_dist_path)
if not comparison_detail.empty:
    print(comparison_path)
print(manifest_path)

print("\nDONE — final signal logic dry run completed.")

====================================================================================================
VRP final signal logic dry run
====================================================================================================
No production files will be written.
Run timestamp: 20260706_222901

====================================================================================================
Source file existence
====================================================================================================
forecast_panel                   exists=True  path=C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_fds_no_min_return_oos_forecast_panel_20200102_20260701_20260704_203242.parquet
signal_rules                     exists=True  path=C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1\09S_core_secondary_consistent_secondary_locked_rules_long_20260705_221829.parquet
sizing_rules                     exists=True  path=C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_sizing_lock_rules_20260706_142800.parquet
selection_rule                   exists=True  path=C:\Users\patri\vrp_project\data\audit\vrp_core_secondary_tertiary_independent_sizing_research_v1\15S_final_one_trade_per_day_naked_put_selection_rule_20260706_142800.json
rv21d                            exists=True  path=C:\Users\patri\vrp_project\data\processed\market_data\spy_realized_vol_history_v1.parquet
locked_16s_selected_optional     exists=True  path=C:\Users\patri\vrp_project\data\processed\vrp_core_secondary_tertiary_independent_sizing_research_v1\16S_locked_cumulative_pnl_timeseries_20260706_143802.parquet

====================================================================================================
Unified FDS candidate base
====================================================================================================
Rows: 14,688
Date range: 2020-01-02 to 2026-07-01
Unique dates: 1,632
Tenors: [9, 12, 15, 18, 21, 24, 27, 30, 33]
Duplicate trade_date × tenor rows: 0

====================================================================================================
Final recomputed field checks
====================================================================================================
Source model_vrp_log vs recomputed model_vrp_log_final absolute diff:

           abs_diff
count  14688.000000
mean       0.174492
std        0.211922
min        0.000002
50%        0.124514
90%        0.338130
99%        1.199144
99.9%      2.193120
max        2.596017

Z-score non-null counts by tenor:

   tenor  rows  z_3m_non_null  z_1y_non_null  first_date   last_date
0      9  1632           1569           1380  2020-01-02  2026-07-01
1     12  1632           1569           1380  2020-01-02  2026-07-01
2     15  1632           1569           1380  2020-01-02  2026-07-01
3     18  1632           1569           1380  2020-01-02  2026-07-01
4     21  1632           1569           1380  2020-01-02  2026-07-01
5     24  1632           1569           1380  2020-01-02  2026-07-01
6     27  1632           1569           1380  2020-01-02  2026-07-01
7     30  1632           1569           1380  2020-01-02  2026-07-01
8     33  1632           1569           1380  2020-01-02  2026-07-01

====================================================================================================
RV21D join
====================================================================================================
Rows after RV21D join: 14,688
Missing rv21d_vol_pct_final: 0
Latest date: 2026-07-01

      trade_date  tenor  spy_close  rv21d_vol_pct_final
14670 2026-06-30      9     746.77            17.726787
14671 2026-06-30     12     746.77            17.726787
14672 2026-06-30     15     746.77            17.726787
14673 2026-06-30     18     746.77            17.726787
14674 2026-06-30     21     746.77            17.726787
14675 2026-06-30     24     746.77            17.726787
14676 2026-06-30     27     746.77            17.726787
14677 2026-06-30     30     746.77            17.726787
14678 2026-06-30     33     746.77            17.726787
14679 2026-07-01      9     745.76            17.686351
14680 2026-07-01     12     745.76            17.686351
14681 2026-07-01     15     745.76            17.686351
14682 2026-07-01     18     745.76            17.686351
14683 2026-07-01     21     745.76            17.686351
14684 2026-07-01     24     745.76            17.686351
14685 2026-07-01     27     745.76            17.686351
14686 2026-07-01     30     745.76            17.686351
14687 2026-07-01     33     745.76            17.686351

====================================================================================================
Active rules and sizing
====================================================================================================
Active signal rule rows: 13

,signal_layer,signal_priority,tenor_bucket,tenor,model_vrp_log_min,model_vrp_z_3m_min,model_vrp_z_1y_min,RSI14_max,rv21d_vol_pct_min
3,Core,1,Middle,21,0.65,0.7,0.7,70.0,8.5
4,Core,1,Middle,24,0.65,0.7,0.7,70.0,8.5
5,Core,1,Back,27,0.70,0.7,0.7,70.0,8.5
6,Core,1,Back,30,0.70,0.7,0.7,70.0,8.5
7,Core,1,Back,33,0.70,0.7,0.7,70.0,8.5
8,Secondary,2,Front,12,0.65,0.2,0.2,75.0,7.0
9,Secondary,2,Front,15,0.65,0.2,0.2,75.0,7.0
10,Secondary,2,Front,18,0.65,0.2,0.2,75.0,7.0
11,Secondary,2,Middle,21,0.65,0.2,0.2,76.0,7.0
12,Secondary,2,Middle,24,0.65,0.2,0.2,76.0,7.0
13,Secondary,2,Back,27,0.65,0.0,0.0,77.0,6.5
14,Secondary,2,Back,30,0.65,0.0,0.0,77.0,6.5
15,Secondary,2,Back,33,0.65,0.0,0.0,77.0,6.5

Active sizing rows: 13

,sleeve_id,signal_layer,tenor_bucket,tenor,locked_size_pct,sizing_quality_score,win_rate,pnl_per_day_expected_loss_1pct_positive,signal_layer_order,tenor_bucket_order,display_order
0,Core_Middle_21D,Core,Middle,21,0.0350,0.791050,0.849315,3935.354296,1,2,1
1,Core_Middle_24D,Core,Middle,24,0.0425,0.789258,0.851351,3122.894260,1,2,2
2,Core_Back_27D,Core,Back,27,0.0450,0.850288,0.875000,3429.035282,1,3,3
3,Core_Back_30D,Core,Back,30,0.0475,0.924325,0.902985,3270.987604,1,3,4
4,Core_Back_33D,Core,Back,33,0.0500,0.942536,0.926471,2478.940162,1,3,5
5,Secondary_Front_12D,Secondary,Front,12,0.0150,0.444253,0.779661,8265.349476,2,1,6
6,Secondary_Front_15D,Secondary,Front,15,0.0200,0.563784,0.795556,6625.789218,2,1,7
7,Secondary_Front_18D,Secondary,Front,18,0.0275,0.616805,0.805085,5205.437870,2,1,8
8,Secondary_Middle_21D,Secondary,Middle,21,0.0350,0.637433,0.800885,3746.893390,2,2,9
9,Secondary_Middle_24D,Secondary,Middle,24,0.0375,0.640723,0.801762,3057.750821,2,2,10
10,Secondary_Back_27D,Secondary,Back,27,0.0400,0.643219,0.809524,3232.669486,2,3,11
11,Secondary_Back_30D,Secondary,Back,30,0.0425,0.733903,0.846774,3300.432417,2,3,12
12,Secondary_Back_33D,Secondary,Back,33,0.0450,0.797547,0.874016,3228.046660,2,3,13

====================================================================================================
Signal qualification counts
====================================================================================================
Candidate rows: 19,584
Qualified candidate rows: 2,435
Missing locked_size_pct among all candidates: 0
Missing locked_size_pct among qualified candidates: 0

   signal_layer tenor_bucket  tenor  qualified_rows
3          Core       Middle     21             146
4          Core       Middle     24             148
0          Core         Back     27             136
1          Core         Back     30             134
2          Core         Back     33             136
8     Secondary        Front     12             295
9     Secondary        Front     15             225
10    Secondary       Middle     21             227
11    Secondary       Middle     24             227
5     Secondary         Back     27             255
6     Secondary         Back     30             250
7     Secondary         Back     33             256

====================================================================================================
Selected trades — dry run
====================================================================================================
Selected rows: 368
Selected date range: 2020-12-31 to 2026-06-02
Max selected rows per date: 1

,signal_layer,tenor_bucket,tenor,sleeve_id,locked_size_pct,selected_count
3,Core,Middle,21,Core_Middle_21D,0.0350,1
4,Core,Middle,24,Core_Middle_24D,0.0425,6
0,Core,Back,27,Core_Back_27D,0.0450,4
1,Core,Back,30,Core_Back_30D,0.0475,2
2,Core,Back,33,Core_Back_33D,0.0500,136
8,Secondary,Front,12,Secondary_Front_12D,0.0150,60
9,Secondary,Front,15,Secondary_Front_15D,0.0200,23
10,Secondary,Middle,21,Secondary_Middle_21D,0.0350,5
11,Secondary,Middle,24,Secondary_Middle_24D,0.0375,3
5,Secondary,Back,27,Secondary_Back_27D,0.0400,8
6,Secondary,Back,30,Secondary_Back_30D,0.0425,6
7,Secondary,Back,33,Secondary_Back_33D,0.0450,114

Selected trades by year/layer/tenor:

    year signal_layer  tenor  selected_count
0   2020    Secondary     33               1
1   2021         Core     33               3
2   2021    Secondary     12               6
3   2021    Secondary     15               7
4   2021    Secondary     27               2
5   2021    Secondary     30               1
6   2021    Secondary     33              10
7   2022         Core     27               1
8   2022         Core     33              66
9   2022    Secondary     12               5
10  2022    Secondary     15               2
11  2022    Secondary     21               1
12  2022    Secondary     27               1
13  2022    Secondary     30               3
14  2022    Secondary     33              44
15  2023         Core     24               1
16  2023         Core     30               1
17  2023    Secondary     12              26
18  2023    Secondary     15              10
19  2023    Secondary     21               1
20  2023    Secondary     33               7
21  2024         Core     21               1
22  2024         Core     24               4
23  2024         Core     27               1
24  2024         Core     33              16
25  2024    Secondary     12              13
26  2024    Secondary     15               3
27  2024    Secondary     21               3
28  2024    Secondary     24               2
29  2024    Secondary     33               3
30  2025         Core     24               1
31  2025         Core     27               1
32  2025         Core     30               1
33  2025         Core     33              23
34  2025    Secondary     12               8
35  2025    Secondary     15               1
36  2025    Secondary     24               1
37  2025    Secondary     27               3
38  2025    Secondary     30               1
39  2025    Secondary     33              28
40  2026         Core     27               1
41  2026         Core     33              28
42  2026    Secondary     12               2
43  2026    Secondary     27               2
44  2026    Secondary     30               1
45  2026    Secondary     33              21

====================================================================================================
Comparison to locked 16S selected artifact
====================================================================================================
16S rows: 365
16S columns:
  trade_date
  selected_trades
  sleeve_id
  signal_layer
  tenor_bucket
  tenor
  locked_size_pct
  daily_pnl
  daily_pnl_per_day
  daily_size_weighted_pnl
  daily_size_weighted_pnl_per_day
  cumulative_pnl
  cumulative_size_weighted_pnl
  static_account_value
  cumulative_size_weighted_return_on_static_account
  daily_size_weighted_return_on_static_account
  running_peak_cumulative_size_weighted_pnl
  drawdown_cumulative_size_weighted_pnl
{
  "locked_rows": 365,
  "dry_selected_rows": 368,
  "both_dates": 365,
  "locked_only_dates": 0,
  "dry_only_dates": 3,
  "exact_layer_tenor_matches": 351,
  "common_date_mismatches": 14
}

Locked 16S distribution:

C:\Users\patri\AppData\Local\Temp\ipykernel_17232\2268523961.py:531: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  panel["core_pass"] = panel["core_pass"].fillna(False).astype(bool)
C:\Users\patri\AppData\Local\Temp\ipykernel_17232\2268523961.py:532: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  panel["secondary_pass"] = panel["secondary_pass"].fillna(False).astype(bool)

   locked_signal_layer  locked_tenor  locked_count
0                 Core            21             1
1                 Core            24             6
2                 Core            27             4
3                 Core            30             2
4                 Core            33           136
5            Secondary            12            56
6            Secondary            15            13
7            Secondary            18            14
8            Secondary            21             5
9            Secondary            24             3
10           Secondary            27             7
11           Secondary            30             6
12           Secondary            33           112

Dry-run selected distribution:

   dry_signal_layer  dry_tenor  dry_count
0              Core         21          1
1              Core         24          6
2              Core         27          4
3              Core         30          2
4              Core         33        136
5         Secondary         12         60
6         Secondary         15         23
7         Secondary         21          5
8         Secondary         24          3
9         Secondary         27          8
10        Secondary         30          6
11        Secondary         33        114

Sample comparison mismatches:

,trade_date,locked_signal_layer,locked_tenor,locked_sleeve_id,locked_size_pct,dry_signal_layer,dry_tenor,dry_sleeve_id,dry_locked_size_pct,_merge,layer_match,tenor_match,exact_match
9,2021-09-10,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,15,Secondary_Front_15D,0.020,both,True,False,False
156,2023-01-17,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,15,Secondary_Front_15D,0.020,both,True,False,False
158,2023-01-26,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,15,Secondary_Front_15D,0.020,both,True,False,False
159,2023-01-27,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,15,Secondary_Front_15D,0.020,both,True,False,False
172,2023-03-16,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,15,Secondary_Front_15D,0.020,both,True,False,False
175,2023-03-21,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,15,Secondary_Front_15D,0.020,both,True,False,False
177,2023-03-23,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,12,Secondary_Front_12D,0.015,both,True,False,False
183,2023-04-18,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,12,Secondary_Front_12D,0.015,both,True,False,False
187,2023-05-24,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,12,Secondary_Front_12D,0.015,both,True,False,False
195,2023-10-17,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,15,Secondary_Front_15D,0.020,both,True,False,False
233,2024-10-23,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,15,Secondary_Front_15D,0.020,both,True,False,False
234,2024-10-24,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,15,Secondary_Front_15D,0.020,both,True,False,False
277,2025-07-29,NaN,NaN,NaN,NaN,Secondary,33,Secondary_Back_33D,0.045,right_only,<NA>,False,False
280,2025-08-11,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,12,Secondary_Front_12D,0.015,both,True,False,False
281,2025-08-15,Secondary,18.0,Secondary_Front_18D,0.0275,Secondary,15,Secondary_Front_15D,0.020,both,True,False,False
366,2026-06-01,NaN,NaN,NaN,NaN,Secondary,27,Secondary_Back_27D,0.040,right_only,<NA>,False,False
367,2026-06-02,NaN,NaN,NaN,NaN,Secondary,33,Secondary_Back_33D,0.045,right_only,<NA>,False,False

====================================================================================================
Dry-run validation
====================================================================================================

,check,status,detail
0,filtered_to_unified_fds_candidate_rows,PASS,"rows=14,688"
1,one_row_per_trade_date_tenor,PASS,duplicate_rows=0
2,expected_tenor_grid,PASS,"actual_tenors=[9, 12, 15, 18, 21, 24, 27, 30, 33]"
3,positive_implied_and_forecast_variance,PASS,implied_variance_final and forecast_variance_final must be positive
4,forecast_vol_reconstruction,PASS,max_abs_diff=0.0
5,model_vrp_log_final_reconstruction,PASS,max_abs_diff=0.0
6,rv21d_join_complete,PASS,missing=0
7,active_signal_rule_count,PASS,active_rules=13
8,active_sizing_rule_count,PASS,active_sizing=13
9,qualified_candidates_have_sizing,PASS,missing_size_qualified=0
10,max_one_selected_trade_per_day,PASS,max_selected_per_date=1

All dry-run hard validations passed.

====================================================================================================
Saved dry-run audit outputs
====================================================================================================
C:\Users\patri\vrp_project\data\audit\vrp_final_signal\vrp_final_signal_logic_dry_run_panel_20260706_222901.csv
C:\Users\patri\vrp_project\data\audit\vrp_final_signal\vrp_final_signal_logic_dry_run_selected_20260706_222901.csv
C:\Users\patri\vrp_project\data\audit\vrp_final_signal\vrp_final_signal_logic_dry_run_candidates_20260706_222901.csv
C:\Users\patri\vrp_project\data\audit\vrp_final_signal\vrp_final_signal_logic_dry_run_validation_20260706_222901.csv
C:\Users\patri\vrp_project\data\audit\vrp_final_signal\vrp_final_signal_logic_dry_run_selected_distribution_20260706_222901.csv
C:\Users\patri\vrp_project\data\audit\vrp_final_signal\vrp_final_signal_logic_dry_run_16S_comparison_20260706_222901.csv
C:\Users\patri\vrp_project\data\audit\vrp_final_signal\vrp_final_signal_logic_dry_run_manifest_20260706_222901.json

DONE — final signal logic dry run completed.