In [1]:
# ======================================================================================
# Cell 0 — Setup and locked model contract
# ======================================================================================
#
# New notebook:
#   07_unified_fds_core_signal_threshold_research_v1.ipynb
#
# Purpose:
#   Start clean threshold/signal research using the locked unified denominator:
#
#       unified_fds_no_min_return
#
# Locked model contract:
#   - One exact model spec across all tenors.
#   - Tenors: 9, 12, 15, 18, 21, 24, 27, 30, 33.
#   - No blending.
#   - No threshold grid inside the denominator.
#   - No separate Front/Middle/Back forecast model.
#   - No candidate_min_return_* features.
#
# First notebook stage:
#   Cells 0–3 only build and validate the clean signal base panel.
#
# Not in scope yet:
#   - No Core threshold sweep.
#   - No Secondary.
#   - No production lock.
#   - No sizing changes.
#
# Important evaluation convention:
#   Because tenors have different DTEs, threshold research should evaluate trade
#   quality using average P&L per day:
#
#       normalized_pnl_per_day = normalized_pnl_dollars / tenor
#
#   Total P&L is still retained for portfolio-level diagnostics, but per-day P&L
#   will be the primary cross-tenor quality metric.
# ======================================================================================

from pathlib import Path
from datetime import datetime
import json
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore", category=RuntimeWarning)

pd.set_option("display.max_columns", 180)
pd.set_option("display.width", 320)

# --------------------------------------------------------------------------------------
# Project paths
# --------------------------------------------------------------------------------------

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

SOURCE_BRANCH = "vrp_front_middle_corsi_forecast_repair_v1"
NEW_BRANCH = "vrp_unified_fds_core_signal_threshold_research_v1"

SOURCE_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / SOURCE_BRANCH

OUT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / NEW_BRANCH
OUT_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / NEW_BRANCH
OUT_CHART_DIR = OUT_AUDIT_DIR / "charts"

OUT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
OUT_AUDIT_DIR.mkdir(parents=True, exist_ok=True)
OUT_CHART_DIR.mkdir(parents=True, exist_ok=True)

TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

# --------------------------------------------------------------------------------------
# Locked model / tenor contract
# --------------------------------------------------------------------------------------

LOCKED_MODEL_SPEC = "unified_fds_no_min_return"
EXISTING_REFERENCE_SPEC = "existing_har_downside_v1"

ALL_TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]
FRONT_TENORS = [9, 12, 15]
MIDDLE_TENORS = [18, 21, 24]
BACK_TENORS = [27, 30, 33]

TENOR_BUCKET_MAP = {
    9: "Front",
    12: "Front",
    15: "Front",
    18: "Middle",
    21: "Middle",
    24: "Middle",
    27: "Back",
    30: "Back",
    33: "Back",
}

BUCKET_ORDER_MAP = {
    "Front": 1,
    "Middle": 2,
    "Back": 3,
}

# Locked Back Core anchor. Front/Middle research comes later.
LOCKED_BACK_CORE_THRESHOLDS = {
    "model_vrp_log": 0.70,
    "model_vrp_z_3m": 0.70,
    "model_vrp_z_1y": 0.70,
    "RSI14_max": 70.0,
    "forecast_vol_pct_min": 8.5,
}

# Legacy Core reference only. Not locked for Front/Middle.
LEGACY_CORE_REFERENCE_THRESHOLDS = {
    "Front": {
        "model_vrp_log": 0.60,
        "model_vrp_z_3m": 0.55,
        "model_vrp_z_1y": 0.65,
        "RSI14_max": 70.0,
        "forecast_vol_pct_min": 8.5,
    },
    "Middle": {
        "model_vrp_log": 0.65,
        "model_vrp_z_3m": 0.75,
        "model_vrp_z_1y": 0.65,
        "RSI14_max": 68.0,
        "forecast_vol_pct_min": 8.5,
    },
    "Back": LOCKED_BACK_CORE_THRESHOLDS,
}

TARGET_VAR_COL = "target_realized_variance"
TARGET_LOG_COL = "target_log_variance"

ZSCORE_WINDOWS = {
    "model_vrp_z_3m": {
        "window": 63,
        "min_periods": 63,
    },
    "model_vrp_z_1y": {
        "window": 252,
        "min_periods": 252,
    },
}

EPS = 1e-12

print("=" * 100)
print("Cell 0 — Setup and locked model contract")
print("=" * 100)
print(f"Source branch:      {SOURCE_BRANCH}")
print(f"New branch:         {NEW_BRANCH}")
print(f"Locked model spec:  {LOCKED_MODEL_SPEC}")
print(f"All tenors:         {ALL_TENORS}")
print(f"Output processed:   {OUT_PROCESSED_DIR}")
print(f"Output audit:       {OUT_AUDIT_DIR}")
print()
print("Primary cross-tenor evaluation metric:")
print("  normalized_pnl_per_day = normalized_pnl_dollars / tenor")
print()
print("CELL 0 COMPLETE")

====================================================================================================
Cell 0 — Setup and locked model contract
====================================================================================================
Source branch:      vrp_front_middle_corsi_forecast_repair_v1
New branch:         vrp_unified_fds_core_signal_threshold_research_v1
Locked model spec:  unified_fds_no_min_return
All tenors:         [9, 12, 15, 18, 21, 24, 27, 30, 33]
Output processed:   C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1
Output audit:       C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1

Primary cross-tenor evaluation metric:
  normalized_pnl_per_day = normalized_pnl_dollars / tenor

CELL 0 COMPLETE

In [2]:
# ======================================================================================
# Cell 1 — Load locked unified denominator panel
# ======================================================================================
#
# Input:
#   Latest Cell 7A unified denominator output:
#
#       data\processed\vrp_front_middle_corsi_forecast_repair_v1\
#       07A_unified_fds_no_min_return_oos_forecast_panel_*.parquet
#
# Scope:
#   - Load the locked model forecast panel.
#   - Keep the locked model rows for signal construction.
#   - Keep existing_har_downside_v1 only as optional reference, not for signal use.
# ======================================================================================

def latest_file(directory: Path, pattern: str, required: bool = True) -> Path | None:
    matches = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if matches:
        return matches[0]
    if required:
        raise FileNotFoundError(f"No file found in {directory} matching {pattern}")
    return None


source_panel_path = latest_file(
    SOURCE_PROCESSED_DIR,
    "07A_unified_fds_no_min_return_oos_forecast_panel_*.parquet",
    required=True,
)

raw_panel = pd.read_parquet(source_panel_path)

duplicate_cols = raw_panel.columns[raw_panel.columns.duplicated()].tolist()
if duplicate_cols:
    print("Dropping duplicate column labels:")
    print(sorted(set(duplicate_cols)))

raw_panel = raw_panel.loc[:, ~raw_panel.columns.duplicated(keep="last")].copy()

# Normalize core date / tenor fields.
raw_panel["trade_date"] = pd.to_datetime(raw_panel["trade_date"], errors="coerce").dt.normalize()
raw_panel["tenor"] = pd.to_numeric(raw_panel["tenor"], errors="coerce").astype("Int64")

if "last_forward_rv_date" in raw_panel.columns:
    raw_panel["last_forward_rv_date"] = pd.to_datetime(
        raw_panel["last_forward_rv_date"],
        errors="coerce",
    ).dt.normalize()
else:
    raise KeyError("Expected last_forward_rv_date in locked model panel.")

required_cols = [
    "trade_date",
    "tenor",
    "model_spec",
    "last_forward_rv_date",
    "implied_variance",
    "forecast_variance_candidate",
    "candidate_forecast_vol_pct",
    TARGET_VAR_COL,
    TARGET_LOG_COL,
    "normalized_pnl_dollars",
    "win",
    "RSI14",
]

missing_cols = [c for c in required_cols if c not in raw_panel.columns]
if missing_cols:
    raise KeyError(f"Missing required columns in locked model panel: {missing_cols}")

for c in [
    "implied_variance",
    "forecast_variance_candidate",
    "candidate_forecast_vol_pct",
    TARGET_VAR_COL,
    TARGET_LOG_COL,
    "normalized_pnl_dollars",
    "win",
    "RSI14",
]:
    raw_panel[c] = pd.to_numeric(raw_panel[c], errors="coerce")

raw_panel = raw_panel[
    raw_panel["trade_date"].notna()
    & raw_panel["tenor"].isin(ALL_TENORS)
    & raw_panel["model_spec"].isin([LOCKED_MODEL_SPEC, EXISTING_REFERENCE_SPEC])
].copy()

locked_rows = raw_panel[raw_panel["model_spec"] == LOCKED_MODEL_SPEC].copy()
reference_rows = raw_panel[raw_panel["model_spec"] == EXISTING_REFERENCE_SPEC].copy()

if locked_rows.empty:
    raise RuntimeError(f"No rows found for locked model spec: {LOCKED_MODEL_SPEC}")

date_min = locked_rows["trade_date"].min()
date_max = locked_rows["trade_date"].max()

print("=" * 100)
print("Cell 1 — Loaded locked unified denominator panel")
print("=" * 100)
print(f"Source panel:            {source_panel_path}")
print(f"Raw rows loaded:          {len(raw_panel):,}")
print(f"Locked model rows:        {len(locked_rows):,}")
print(f"Reference model rows:     {len(reference_rows):,}")
print(f"Locked date range:        {date_min.date()} to {date_max.date()}")
print(f"Tenors found:             {sorted(locked_rows['tenor'].dropna().astype(int).unique().tolist())}")
print(f"Models found:             {sorted(raw_panel['model_spec'].dropna().unique().tolist())}")
print()
print("Rows by model:")
display(raw_panel["model_spec"].value_counts(dropna=False).to_frame("rows"))
print()
print("Rows by tenor for locked model:")
display(
    locked_rows
    .groupby("tenor", as_index=False)
    .agg(
        rows=("trade_date", "size"),
        date_min=("trade_date", "min"),
        date_max=("trade_date", "max"),
    )
)

print("\nCELL 1 COMPLETE")

====================================================================================================
Cell 1 — Loaded locked unified denominator panel
====================================================================================================
Source panel:            C:\Users\patri\vrp_project\data\processed\vrp_front_middle_corsi_forecast_repair_v1\07A_unified_fds_no_min_return_oos_forecast_panel_20200102_20260701_20260704_203242.parquet
Raw rows loaded:          31,140
Locked model rows:        14,688
Reference model rows:     16,452
Locked date range:        2020-01-02 to 2026-07-01
Tenors found:             [9, 12, 15, 18, 21, 24, 27, 30, 33]
Models found:             ['existing_har_downside_v1', 'unified_fds_no_min_return']

Rows by model:

                            rows
model_spec
existing_har_downside_v1   16452
unified_fds_no_min_return  14688

Rows by tenor for locked model:

   tenor  rows   date_min   date_max
0      9  1632 2020-01-02 2026-07-01
1     12  1632 2020-01-02 2026-07-01
2     15  1632 2020-01-02 2026-07-01
3     18  1632 2020-01-02 2026-07-01
4     21  1632 2020-01-02 2026-07-01
5     24  1632 2020-01-02 2026-07-01
6     27  1632 2020-01-02 2026-07-01
7     30  1632 2020-01-02 2026-07-01
8     33  1632 2020-01-02 2026-07-01

CELL 1 COMPLETE

In [3]:
# ======================================================================================
# Cell 2 — Build clean unified signal base panel
# ======================================================================================
#
# Objective:
#   Build one clean signal row per trade_date × tenor using only:
#
#       unified_fds_no_min_return
#
# Key fields created:
#   - implied_vol_pct
#   - forecast_vol_pct
#   - forward_realized_vol_pct_raw
#   - forward_realized_complete
#   - forward_realized_vol_pct_completed
#   - model_vrp_log
#   - model_vrp_z_3m, prior-only by tenor
#   - model_vrp_z_1y, prior-only by tenor
#   - normalized_pnl_per_day = normalized_pnl_dollars / tenor
#
# Important:
#   - Forward realized target may be incomplete near the end of the sample.
#   - We keep raw target fields for historical research.
#   - We flag completed forward rows for visual / realized-vol diagnostics.
#   - Threshold research can still evaluate only historical completed outcomes.
# ======================================================================================

def annualized_vol_pct_from_variance(x: pd.Series) -> pd.Series:
    return np.sqrt(pd.to_numeric(x, errors="coerce").clip(lower=0)) * 100.0


def compute_prior_z_by_tenor(
    df: pd.DataFrame,
    value_col: str,
    window: int,
    min_periods: int,
) -> pd.Series:
    """
    Prior-only rolling z-score by tenor.

    For each row:
        z_t = (x_t - mean(x_{t-window} ... x_{t-1})) / std(x_{t-window} ... x_{t-1})

    This intentionally excludes the current row from the rolling mean/std.
    """
    out = pd.Series(np.nan, index=df.index, dtype="float64")

    for tenor, g in df.sort_values(["tenor", "trade_date"]).groupby("tenor"):
        shifted = g[value_col].shift(1)
        roll_mean = shifted.rolling(window=window, min_periods=min_periods).mean()
        roll_std = shifted.rolling(window=window, min_periods=min_periods).std(ddof=1)
        z = (g[value_col] - roll_mean) / roll_std.replace(0.0, np.nan)
        out.loc[g.index] = z

    return out


# Start with locked model only.
signal = locked_rows.copy()

signal = signal.sort_values(["trade_date", "tenor"]).reset_index(drop=True)

# Defensive uniqueness check before building one-row-per-date-tenor panel.
dup_keys = signal.duplicated(["trade_date", "tenor"], keep=False)
if dup_keys.any():
    duplicate_sample = signal.loc[dup_keys, ["trade_date", "tenor", "model_spec"]].head(20)
    display(duplicate_sample)
    raise RuntimeError("Locked model panel has duplicate trade_date × tenor rows.")

signal["tenor"] = signal["tenor"].astype(int)
signal["tenor_bucket"] = signal["tenor"].map(TENOR_BUCKET_MAP)
signal["tenor_bucket_order"] = signal["tenor_bucket"].map(BUCKET_ORDER_MAP)

# Core vol / variance fields.
signal["implied_variance"] = pd.to_numeric(signal["implied_variance"], errors="coerce")
signal["forecast_variance"] = pd.to_numeric(signal["forecast_variance_candidate"], errors="coerce")
signal["target_realized_variance"] = pd.to_numeric(signal[TARGET_VAR_COL], errors="coerce")

signal["implied_vol_pct"] = annualized_vol_pct_from_variance(signal["implied_variance"])
signal["forecast_vol_pct"] = annualized_vol_pct_from_variance(signal["forecast_variance"])
signal["forward_realized_vol_pct_raw"] = annualized_vol_pct_from_variance(signal["target_realized_variance"])

# Max available trade date from the locked panel.
max_available_trade_date = signal["trade_date"].max()

signal["forward_realized_complete"] = (
    signal["last_forward_rv_date"].notna()
    & (signal["last_forward_rv_date"] <= max_available_trade_date)
)

signal["target_realized_variance_completed"] = np.where(
    signal["forward_realized_complete"],
    signal["target_realized_variance"],
    np.nan,
)

signal["forward_realized_vol_pct_completed"] = np.where(
    signal["forward_realized_complete"],
    signal["forward_realized_vol_pct_raw"],
    np.nan,
)

# VRP fields.
signal["model_vrp_log"] = np.log(signal["implied_variance"] / signal["forecast_variance"].clip(lower=EPS))
signal["model_vrp_ratio"] = signal["implied_variance"] / signal["forecast_variance"].clip(lower=EPS)

signal["model_vrp_z_3m"] = compute_prior_z_by_tenor(
    signal,
    value_col="model_vrp_log",
    window=ZSCORE_WINDOWS["model_vrp_z_3m"]["window"],
    min_periods=ZSCORE_WINDOWS["model_vrp_z_3m"]["min_periods"],
)

signal["model_vrp_z_1y"] = compute_prior_z_by_tenor(
    signal,
    value_col="model_vrp_log",
    window=ZSCORE_WINDOWS["model_vrp_z_1y"]["window"],
    min_periods=ZSCORE_WINDOWS["model_vrp_z_1y"]["min_periods"],
)

# P&L normalization.
signal["normalized_pnl_dollars"] = pd.to_numeric(signal["normalized_pnl_dollars"], errors="coerce")
signal["normalized_pnl_per_day"] = signal["normalized_pnl_dollars"] / signal["tenor"].replace(0, np.nan)

# Retain useful trade outcome fields.
signal["win"] = pd.to_numeric(signal["win"], errors="coerce")
signal["RSI14"] = pd.to_numeric(signal["RSI14"], errors="coerce")

# Current diagnostic thresholds, used only as reference labels here.
signal["legacy_reference_model_vrp_log_threshold"] = signal["tenor_bucket"].map(
    {k: v["model_vrp_log"] for k, v in LEGACY_CORE_REFERENCE_THRESHOLDS.items()}
)
signal["legacy_reference_model_vrp_z_3m_threshold"] = signal["tenor_bucket"].map(
    {k: v["model_vrp_z_3m"] for k, v in LEGACY_CORE_REFERENCE_THRESHOLDS.items()}
)
signal["legacy_reference_model_vrp_z_1y_threshold"] = signal["tenor_bucket"].map(
    {k: v["model_vrp_z_1y"] for k, v in LEGACY_CORE_REFERENCE_THRESHOLDS.items()}
)
signal["legacy_reference_RSI14_max"] = signal["tenor_bucket"].map(
    {k: v["RSI14_max"] for k, v in LEGACY_CORE_REFERENCE_THRESHOLDS.items()}
)
signal["legacy_reference_forecast_vol_pct_min"] = signal["tenor_bucket"].map(
    {k: v["forecast_vol_pct_min"] for k, v in LEGACY_CORE_REFERENCE_THRESHOLDS.items()}
)

signal["legacy_reference_core_pass"] = (
    (signal["model_vrp_log"] > signal["legacy_reference_model_vrp_log_threshold"])
    & (signal["model_vrp_z_3m"] > signal["legacy_reference_model_vrp_z_3m_threshold"])
    & (signal["model_vrp_z_1y"] > signal["legacy_reference_model_vrp_z_1y_threshold"])
    & (signal["RSI14"] < signal["legacy_reference_RSI14_max"])
    & (signal["forecast_vol_pct"] > signal["legacy_reference_forecast_vol_pct_min"])
)

# Keep a clean, explicit column order where possible.
preferred_cols = [
    "trade_date",
    "tenor",
    "tenor_bucket",
    "tenor_bucket_order",
    "model_spec",
    "last_forward_rv_date",
    "forward_realized_complete",
    "implied_variance",
    "forecast_variance",
    "target_realized_variance",
    "target_realized_variance_completed",
    "implied_vol_pct",
    "forecast_vol_pct",
    "forward_realized_vol_pct_raw",
    "forward_realized_vol_pct_completed",
    "model_vrp_log",
    "model_vrp_ratio",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14",
    "normalized_pnl_dollars",
    "normalized_pnl_per_day",
    "win",
    "legacy_reference_model_vrp_log_threshold",
    "legacy_reference_model_vrp_z_3m_threshold",
    "legacy_reference_model_vrp_z_1y_threshold",
    "legacy_reference_RSI14_max",
    "legacy_reference_forecast_vol_pct_min",
    "legacy_reference_core_pass",
]

other_cols = [c for c in signal.columns if c not in preferred_cols]
signal = signal[preferred_cols + other_cols].copy()

# Save base panel.
base_panel_path = OUT_PROCESSED_DIR / (
    f"01_unified_fds_signal_base_panel_{signal['trade_date'].min():%Y%m%d}_"
    f"{signal['trade_date'].max():%Y%m%d}_{TIMESTAMP}.parquet"
)

signal.to_parquet(base_panel_path, index=False)

# Save summary audit.
summary_by_tenor = (
    signal.groupby(["tenor", "tenor_bucket"], as_index=False)
    .agg(
        rows=("trade_date", "size"),
        date_min=("trade_date", "min"),
        date_max=("trade_date", "max"),
        completed_forward_rows=("forward_realized_complete", "sum"),
        avg_implied_vol_pct=("implied_vol_pct", "mean"),
        avg_forecast_vol_pct=("forecast_vol_pct", "mean"),
        avg_model_vrp_log=("model_vrp_log", "mean"),
        z_3m_available_rows=("model_vrp_z_3m", lambda x: int(x.notna().sum())),
        z_1y_available_rows=("model_vrp_z_1y", lambda x: int(x.notna().sum())),
        avg_pnl_dollars=("normalized_pnl_dollars", "mean"),
        avg_pnl_per_day=("normalized_pnl_per_day", "mean"),
        median_pnl_per_day=("normalized_pnl_per_day", "median"),
    )
)

summary_by_bucket = (
    signal.groupby(["tenor_bucket", "tenor_bucket_order"], as_index=False)
    .agg(
        rows=("trade_date", "size"),
        completed_forward_rows=("forward_realized_complete", "sum"),
        avg_implied_vol_pct=("implied_vol_pct", "mean"),
        avg_forecast_vol_pct=("forecast_vol_pct", "mean"),
        avg_model_vrp_log=("model_vrp_log", "mean"),
        z_3m_available_rows=("model_vrp_z_3m", lambda x: int(x.notna().sum())),
        z_1y_available_rows=("model_vrp_z_1y", lambda x: int(x.notna().sum())),
        avg_pnl_dollars=("normalized_pnl_dollars", "mean"),
        avg_pnl_per_day=("normalized_pnl_per_day", "mean"),
        median_pnl_per_day=("normalized_pnl_per_day", "median"),
    )
    .sort_values("tenor_bucket_order")
)

summary_by_tenor_path = OUT_AUDIT_DIR / f"01_signal_base_summary_by_tenor_{TIMESTAMP}.csv"
summary_by_bucket_path = OUT_AUDIT_DIR / f"01_signal_base_summary_by_bucket_{TIMESTAMP}.csv"

summary_by_tenor.to_csv(summary_by_tenor_path, index=False)
summary_by_bucket.to_csv(summary_by_bucket_path, index=False)

print("=" * 100)
print("Cell 2 — Built clean unified signal base panel")
print("=" * 100)
print(f"Rows:                         {len(signal):,}")
print(f"Date range:                   {signal['trade_date'].min().date()} to {signal['trade_date'].max().date()}")
print(f"Max available trade date:      {max_available_trade_date.date()}")
print(f"Completed forward rows:        {int(signal['forward_realized_complete'].sum()):,} / {len(signal):,}")
print(f"Suppressed incomplete rows:    {int((~signal['forward_realized_complete']).sum()):,}")
print(f"Saved base panel:              {base_panel_path}")
print()
print("Summary by bucket:")
display(summary_by_bucket)
print()
print("Summary by tenor:")
display(summary_by_tenor)

print("\nCELL 2 COMPLETE")

====================================================================================================
Cell 2 — Built clean unified signal base panel
====================================================================================================
Rows:                         14,688
Date range:                   2020-01-02 to 2026-07-01
Max available trade date:      2026-07-01
Completed forward rows:        14,559 / 14,688
Suppressed incomplete rows:    129
Saved base panel:              C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\01_unified_fds_signal_base_panel_20200102_20260701_20260704_211636.parquet

Summary by bucket:

  tenor_bucket  tenor_bucket_order  rows  completed_forward_rows  avg_implied_vol_pct  avg_forecast_vol_pct  avg_model_vrp_log  z_3m_available_rows  z_1y_available_rows  avg_pnl_dollars  avg_pnl_per_day  median_pnl_per_day
1        Front                   1  4896                    4871            20.073584             14.867199           0.586669                 4707                 4140      1646.357888       133.312864          656.582042
2       Middle                   2  4896                    4853            20.489803             14.963731           0.592387                 4707                 4140      2988.726930       142.243849          512.556385
0         Back                   3  4896                    4835            20.862671             15.024010           0.606769                 4707                 4140      4731.834259       157.596048          454.394391

Summary by tenor:

   tenor tenor_bucket  rows   date_min   date_max  completed_forward_rows  avg_implied_vol_pct  avg_forecast_vol_pct  avg_model_vrp_log  z_3m_available_rows  z_1y_available_rows  avg_pnl_dollars  avg_pnl_per_day  median_pnl_per_day
0      9        Front  1632 2020-01-02 2026-07-01                    1625            19.913988             14.892609           0.574855                 1569                 1380       962.582306       106.953590          728.498588
1     12        Front  1632 2020-01-02 2026-07-01                    1624            20.084706             14.657151           0.619382                 1569                 1380      1669.246539       139.103878          639.436381
2     15        Front  1632 2020-01-02 2026-07-01                    1622            20.222058             15.051838           0.565772                 1569                 1380      2309.333426       153.955562          615.759612
3     18       Middle  1632 2020-01-02 2026-07-01                    1620            20.363649             14.867733           0.599534                 1569                 1380      2495.032221       138.612901          541.025351
4     21       Middle  1632 2020-01-02 2026-07-01                    1618            20.491143             15.045946           0.580522                 1569                 1380      3098.741526       147.559120          525.171067
5     24       Middle  1632 2020-01-02 2026-07-01                    1615            20.614617             14.977513           0.597104                 1569                 1380      3373.566002       140.565250          475.901402
6     27         Back  1632 2020-01-02 2026-07-01                    1614            20.742690             14.968975           0.606214                 1569                 1380      4227.971187       156.591525          475.015857
7     30         Back  1632 2020-01-02 2026-07-01                    1611            20.861959             15.085066           0.597346                 1569                 1380      4660.809980       155.360333          453.444428
8     33         Back  1632 2020-01-02 2026-07-01                    1610            20.983364             15.017990           0.616746                 1569                 1380      5307.797506       160.842349          436.928415

CELL 2 COMPLETE

In [4]:
# ======================================================================================
# Cell 3 — Validate locked signal base panel
# ======================================================================================
#
# Objective:
#   Validate that the clean signal base panel is suitable for Core threshold research.
#
# Checks:
#   - one locked model only
#   - one row per trade_date × tenor
#   - all exact tenors present
#   - bucket mapping correct
#   - prior-only z-scores exist after warmup
#   - no impossible variance values
#   - normalized_pnl_per_day created correctly
#   - incomplete forward realized targets are flagged
#   - Back locked threshold reference present
#
# No threshold sweep in this cell.
# ======================================================================================

validation_rows = []

def add_validation(check: str, status: str, detail: str):
    validation_rows.append({
        "check": check,
        "status": status,
        "detail": detail,
    })


# --------------------------------------------------------------------------------------
# Basic structure
# --------------------------------------------------------------------------------------

models_found = sorted(signal["model_spec"].dropna().unique().tolist())
tenors_found = sorted(signal["tenor"].dropna().astype(int).unique().tolist())
missing_tenors = sorted(set(ALL_TENORS) - set(tenors_found))
extra_tenors = sorted(set(tenors_found) - set(ALL_TENORS))

duplicate_key_count = int(signal.duplicated(["trade_date", "tenor"]).sum())

add_validation(
    "locked_model_only",
    "PASS" if models_found == [LOCKED_MODEL_SPEC] else "FAIL",
    f"models_found={models_found}",
)

add_validation(
    "one_row_per_trade_date_tenor",
    "PASS" if duplicate_key_count == 0 else "FAIL",
    f"duplicate_key_count={duplicate_key_count}",
)

add_validation(
    "all_exact_tenors_present",
    "PASS" if not missing_tenors and not extra_tenors else "FAIL",
    f"missing={missing_tenors}; extra={extra_tenors}",
)

bucket_bad = signal[
    signal["tenor_bucket"] != signal["tenor"].map(TENOR_BUCKET_MAP)
]

add_validation(
    "bucket_mapping",
    "PASS" if bucket_bad.empty else "FAIL",
    f"bad_rows={len(bucket_bad):,}",
)

# --------------------------------------------------------------------------------------
# Variance / vol sanity
# --------------------------------------------------------------------------------------

bad_variance_rows = signal[
    (~np.isfinite(signal["implied_variance"]))
    | (~np.isfinite(signal["forecast_variance"]))
    | (signal["implied_variance"] <= 0)
    | (signal["forecast_variance"] <= 0)
]

add_validation(
    "positive_implied_and_forecast_variance",
    "PASS" if bad_variance_rows.empty else "FAIL",
    f"bad_rows={len(bad_variance_rows):,}",
)

bad_vrp_rows = signal[
    ~np.isfinite(signal["model_vrp_log"])
]

add_validation(
    "model_vrp_log_finite",
    "PASS" if bad_vrp_rows.empty else "FAIL",
    f"bad_rows={len(bad_vrp_rows):,}",
)

# --------------------------------------------------------------------------------------
# Z-score availability and prior-only warmup
# --------------------------------------------------------------------------------------

z_summary = (
    signal.groupby("tenor", as_index=False)
    .agg(
        rows=("trade_date", "size"),
        z_3m_available_rows=("model_vrp_z_3m", lambda x: int(x.notna().sum())),
        z_1y_available_rows=("model_vrp_z_1y", lambda x: int(x.notna().sum())),
        first_date=("trade_date", "min"),
        first_z_3m_date=("trade_date", lambda x: signal.loc[x.index[signal.loc[x.index, "model_vrp_z_3m"].notna()], "trade_date"].min()),
        first_z_1y_date=("trade_date", lambda x: signal.loc[x.index[signal.loc[x.index, "model_vrp_z_1y"].notna()], "trade_date"].min()),
    )
)

z_3m_all_have_values = bool((z_summary["z_3m_available_rows"] > 0).all())
z_1y_all_have_values = bool((z_summary["z_1y_available_rows"] > 0).all())

add_validation(
    "z_3m_available_after_warmup",
    "PASS" if z_3m_all_have_values else "FAIL",
    z_summary[["tenor", "z_3m_available_rows", "first_z_3m_date"]].to_dict("records").__repr__(),
)

add_validation(
    "z_1y_available_after_warmup",
    "PASS" if z_1y_all_have_values else "FAIL",
    z_summary[["tenor", "z_1y_available_rows", "first_z_1y_date"]].to_dict("records").__repr__(),
)

# Spot-check prior-only behavior:
# For each tenor, first non-null 3m z should occur no earlier than row index 63 within that tenor.
prior_only_rows = []

for tenor, g in signal.sort_values(["tenor", "trade_date"]).groupby("tenor"):
    g = g.reset_index(drop=True).copy()
    first_z3_idx = g["model_vrp_z_3m"].first_valid_index()
    first_z1_idx = g["model_vrp_z_1y"].first_valid_index()

    prior_only_rows.append({
        "tenor": int(tenor),
        "first_z3_idx": first_z3_idx,
        "first_z1_idx": first_z1_idx,
        "z3_prior_only_ok": first_z3_idx is not None and first_z3_idx >= ZSCORE_WINDOWS["model_vrp_z_3m"]["min_periods"],
        "z1_prior_only_ok": first_z1_idx is not None and first_z1_idx >= ZSCORE_WINDOWS["model_vrp_z_1y"]["min_periods"],
    })

prior_only_check = pd.DataFrame(prior_only_rows)

add_validation(
    "zscore_prior_only_warmup_check",
    "PASS" if prior_only_check["z3_prior_only_ok"].all() and prior_only_check["z1_prior_only_ok"].all() else "FAIL",
    prior_only_check.to_dict("records").__repr__(),
)

# --------------------------------------------------------------------------------------
# P&L per day validation
# --------------------------------------------------------------------------------------

pnl_check = signal.copy()
pnl_check["expected_pnl_per_day"] = pnl_check["normalized_pnl_dollars"] / pnl_check["tenor"]
pnl_check["pnl_per_day_diff"] = pnl_check["normalized_pnl_per_day"] - pnl_check["expected_pnl_per_day"]

bad_pnl_per_day = pnl_check[
    pnl_check["normalized_pnl_dollars"].notna()
    & pnl_check["normalized_pnl_per_day"].notna()
    & (pnl_check["pnl_per_day_diff"].abs() > 1e-8)
]

add_validation(
    "normalized_pnl_per_day_created",
    "PASS" if bad_pnl_per_day.empty else "FAIL",
    f"bad_rows={len(bad_pnl_per_day):,}; formula=normalized_pnl_dollars / tenor",
)

pnl_per_day_available = int(signal["normalized_pnl_per_day"].notna().sum())

add_validation(
    "normalized_pnl_per_day_available",
    "PASS" if pnl_per_day_available > 0 else "FAIL",
    f"available_rows={pnl_per_day_available:,}",
)

# --------------------------------------------------------------------------------------
# Forward realized completion guard
# --------------------------------------------------------------------------------------

max_available_trade_date = signal["trade_date"].max()

completion_check_bad = signal[
    signal["last_forward_rv_date"].notna()
    & (
        signal["forward_realized_complete"]
        != (signal["last_forward_rv_date"] <= max_available_trade_date)
    )
]

add_validation(
    "forward_realized_completion_guard",
    "PASS" if completion_check_bad.empty else "FAIL",
    f"bad_rows={len(completion_check_bad):,}; max_available_trade_date={max_available_trade_date.date()}",
)

latest_rows = signal[signal["trade_date"] == max_available_trade_date].copy()
latest_completed_count = int(latest_rows["forward_realized_complete"].sum())

add_validation(
    "latest_forward_completion_count",
    "PASS",
    f"latest_date={max_available_trade_date.date()}; completed_forward_tenors={latest_completed_count}/9",
)

# --------------------------------------------------------------------------------------
# Back locked threshold reference
# --------------------------------------------------------------------------------------

back_ref = LEGACY_CORE_REFERENCE_THRESHOLDS["Back"]

back_reference_ok = (
    back_ref["model_vrp_log"] == LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"]
    and back_ref["model_vrp_z_3m"] == LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"]
    and back_ref["model_vrp_z_1y"] == LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_1y"]
    and back_ref["RSI14_max"] == LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"]
    and back_ref["forecast_vol_pct_min"] == LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"]
)

add_validation(
    "back_locked_threshold_reference",
    "PASS" if back_reference_ok else "FAIL",
    f"Back reference={back_ref}",
)

# --------------------------------------------------------------------------------------
# Save validation / manifest
# --------------------------------------------------------------------------------------

validation = pd.DataFrame(validation_rows)

validation_path = OUT_AUDIT_DIR / f"01_signal_base_validation_{TIMESTAMP}.csv"
z_summary_path = OUT_AUDIT_DIR / f"01_signal_base_zscore_summary_{TIMESTAMP}.csv"
prior_only_check_path = OUT_AUDIT_DIR / f"01_signal_base_prior_only_zscore_check_{TIMESTAMP}.csv"
manifest_path = OUT_AUDIT_DIR / f"01_signal_base_manifest_{TIMESTAMP}.json"

validation.to_csv(validation_path, index=False)
z_summary.to_csv(z_summary_path, index=False)
prior_only_check.to_csv(prior_only_check_path, index=False)

manifest = {
    "notebook": "07_unified_fds_core_signal_threshold_research_v1.ipynb",
    "cell_stage": "Cells 0-3 — clean locked signal base panel",
    "timestamp": TIMESTAMP,
    "source_panel": str(source_panel_path),
    "locked_model_spec": LOCKED_MODEL_SPEC,
    "all_tenors": ALL_TENORS,
    "new_branch": NEW_BRANCH,
    "base_panel_path": str(base_panel_path),
    "summary_by_tenor_path": str(summary_by_tenor_path),
    "summary_by_bucket_path": str(summary_by_bucket_path),
    "validation_path": str(validation_path),
    "z_summary_path": str(z_summary_path),
    "prior_only_check_path": str(prior_only_check_path),
    "primary_cross_tenor_trade_quality_metric": "normalized_pnl_per_day",
    "normalized_pnl_per_day_formula": "normalized_pnl_dollars / tenor",
    "zscore_method": {
        "model_vrp_z_3m": "prior-only rolling z-score of model_vrp_log by tenor, 63-row window, shifted one row",
        "model_vrp_z_1y": "prior-only rolling z-score of model_vrp_log by tenor, 252-row window, shifted one row",
    },
    "locked_back_core_thresholds": LOCKED_BACK_CORE_THRESHOLDS,
    "notes": [
        "No threshold sweep performed.",
        "No Secondary research performed.",
        "No sizing changes performed.",
        "This panel is the clean input for Core threshold research.",
        "Total P&L retained, but average P&L per day should be used for cross-tenor trade quality comparisons.",
    ],
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2)

failures = validation[validation["status"] == "FAIL"]

print("=" * 100)
print("Cell 3 — Validate locked signal base panel")
print("=" * 100)
print(f"Signal base panel:         {base_panel_path}")
print(f"Validation file:           {validation_path}")
print(f"Z-score summary:           {z_summary_path}")
print(f"Prior-only check:          {prior_only_check_path}")
print(f"Manifest:                  {manifest_path}")
print()
print("Validation:")
display(validation)

print()
print("Z-score summary:")
display(z_summary)

print()
print("Prior-only z-score warmup check:")
display(prior_only_check)

print()
print("Latest date rows:")
display(
    latest_rows[
        [
            "trade_date",
            "tenor",
            "tenor_bucket",
            "implied_vol_pct",
            "forecast_vol_pct",
            "model_vrp_log",
            "model_vrp_z_3m",
            "model_vrp_z_1y",
            "forward_realized_complete",
            "last_forward_rv_date",
            "normalized_pnl_dollars",
            "normalized_pnl_per_day",
        ]
    ].sort_values("tenor")
)

if not failures.empty:
    raise RuntimeError("Cell 3 validation failed. Review validation output above.")

print("\nCELL 3 PASSED")

====================================================================================================
Cell 3 — Validate locked signal base panel
====================================================================================================
Signal base panel:         C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\01_unified_fds_signal_base_panel_20200102_20260701_20260704_211636.parquet
Validation file:           C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\01_signal_base_validation_20260704_211636.csv
Z-score summary:           C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\01_signal_base_zscore_summary_20260704_211636.csv
Prior-only check:          C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\01_signal_base_prior_only_zscore_check_20260704_211636.csv
Manifest:                  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\01_signal_base_manifest_20260704_211636.json

Validation:

                                     check status                                             detail
0                        locked_model_only   PASS         models_found=['unified_fds_no_min_return']
1             one_row_per_trade_date_tenor   PASS                              duplicate_key_count=0
2                 all_exact_tenors_present   PASS                               missing=[]; extra=[]
3                           bucket_mapping   PASS                                         bad_rows=0
4   positive_implied_and_forecast_variance   PASS                                         bad_rows=0
5                     model_vrp_log_finite   PASS                                         bad_rows=0
6              z_3m_available_after_warmup   PASS  [{'tenor': 9, 'z_3m_available_rows': 1569, 'fi...
7              z_1y_available_after_warmup   PASS  [{'tenor': 9, 'z_1y_available_rows': 1380, 'fi...
8           zscore_prior_only_warmup_check   PASS  [{'tenor': 9, 'first_z3_idx': 63, 'first_z1_id...
9           normalized_pnl_per_day_created   PASS  bad_rows=0; formula=normalized_pnl_dollars / t...
10        normalized_pnl_per_day_available   PASS                              available_rows=14,499
11       forward_realized_completion_guard   PASS    bad_rows=0; max_available_trade_date=2026-07-01
12         latest_forward_completion_count   PASS  latest_date=2026-07-01; completed_forward_teno...
13         back_locked_threshold_reference   PASS  Back reference={'model_vrp_log': 0.7, 'model_v...

Z-score summary:

   tenor  rows  z_3m_available_rows  z_1y_available_rows first_date first_z_3m_date first_z_1y_date
0      9  1632                 1569                 1380 2020-01-02      2020-04-02      2020-12-31
1     12  1632                 1569                 1380 2020-01-02      2020-04-02      2020-12-31
2     15  1632                 1569                 1380 2020-01-02      2020-04-02      2020-12-31
3     18  1632                 1569                 1380 2020-01-02      2020-04-02      2020-12-31
4     21  1632                 1569                 1380 2020-01-02      2020-04-02      2020-12-31
5     24  1632                 1569                 1380 2020-01-02      2020-04-02      2020-12-31
6     27  1632                 1569                 1380 2020-01-02      2020-04-02      2020-12-31
7     30  1632                 1569                 1380 2020-01-02      2020-04-02      2020-12-31
8     33  1632                 1569                 1380 2020-01-02      2020-04-02      2020-12-31

Prior-only z-score warmup check:

   tenor  first_z3_idx  first_z1_idx  z3_prior_only_ok  z1_prior_only_ok
0      9            63           252              True              True
1     12            63           252              True              True
2     15            63           252              True              True
3     18            63           252              True              True
4     21            63           252              True              True
5     24            63           252              True              True
6     27            63           252              True              True
7     30            63           252              True              True
8     33            63           252              True              True

Latest date rows:

      trade_date  tenor tenor_bucket  implied_vol_pct  forecast_vol_pct  model_vrp_log  model_vrp_z_3m  model_vrp_z_1y  forward_realized_complete last_forward_rv_date  normalized_pnl_dollars  normalized_pnl_per_day
14679 2026-07-01      9        Front        12.841456         12.672383       0.026507       -1.727898       -1.529773                      False           2026-07-02                     NaN                     NaN
14680 2026-07-01     12        Front        13.738603         12.785639       0.143774       -1.514802       -1.442833                      False           2026-07-02                     NaN                     NaN
14681 2026-07-01     15        Front        14.249805         13.444656       0.116323       -1.437723       -1.415119                      False           2026-07-02                     NaN                     NaN
14682 2026-07-01     18       Middle        14.767299         13.468368       0.184143       -1.338608       -1.394870                      False           2026-07-02                     NaN                     NaN
14683 2026-07-01     21       Middle        15.175856         13.817420       0.187551       -1.272126       -1.375707                      False           2026-07-02                     NaN                     NaN
14684 2026-07-01     24       Middle        15.570145         13.927472       0.222984       -1.233577       -1.356383                      False           2026-07-02                     NaN                     NaN
14685 2026-07-01     27         Back        16.034296         13.951883       0.278231       -1.109388       -1.244294                      False           2026-07-02                     NaN                     NaN
14686 2026-07-01     30         Back        16.396160         14.129525       0.297561       -1.029999       -1.140252                      False           2026-07-02                     NaN                     NaN
14687 2026-07-01     33         Back        16.567266         14.150541       0.315352       -1.049221       -1.181808                      False           2026-07-02                     NaN                     NaN

CELL 3 PASSED

In [6]:
# ======================================================================================
# Cell 4 — Legacy Core baseline diagnostic using P&L/day
# ======================================================================================
#
# Objective:
#   Apply the current legacy/reference Core thresholds to the clean locked signal panel
#   and produce baseline diagnostics before any threshold sweep.
#
# Uses:
#   - locked unified_fds_no_min_return signal base panel from Cell 2 / Cell 3
#   - normalized_pnl_per_day = normalized_pnl_dollars / tenor
#
# Thresholds applied:
#   Front:
#       model_vrp_log > 0.60
#       model_vrp_z_3m > 0.55
#       model_vrp_z_1y > 0.65
#       RSI14 < 70
#       forecast_vol_pct > 8.5
#
#   Middle:
#       model_vrp_log > 0.65
#       model_vrp_z_3m > 0.75
#       model_vrp_z_1y > 0.65
#       RSI14 < 68
#       forecast_vol_pct > 8.5
#
#   Back:
#       model_vrp_log > 0.70
#       model_vrp_z_3m > 0.70
#       model_vrp_z_1y > 0.70
#       RSI14 < 70
#       forecast_vol_pct > 8.5
#
# Selection universes evaluated:
#   1. all_qualified_trades
#   2. one_trade_per_bucket_per_date_best_rank
#   3. one_trade_per_date_best_rank
#   4. thirty_day_anchor_only
#
# Important:
#   The best-rank selector is diagnostic only. It is not yet the final production
#   DTE-selection rule. We will discuss and test that separately.
#
# Not in scope:
#   - No threshold sweep.
#   - No Secondary.
#   - No production lock.
#   - No sizing changes.
# ======================================================================================

from pathlib import Path
from datetime import datetime
import json
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 180)
pd.set_option("display.width", 320)

# ======================================================================================
# 0. Fallback config if this cell is run independently
# ======================================================================================

if "PROJECT_ROOT" not in globals():
    PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

if "NEW_BRANCH" not in globals():
    NEW_BRANCH = "vrp_unified_fds_core_signal_threshold_research_v1"

if "OUT_PROCESSED_DIR" not in globals():
    OUT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / NEW_BRANCH
    OUT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

if "OUT_AUDIT_DIR" not in globals():
    OUT_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / NEW_BRANCH
    OUT_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

if "TIMESTAMP" not in globals():
    TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

if "ALL_TENORS" not in globals():
    ALL_TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

if "TENOR_BUCKET_MAP" not in globals():
    TENOR_BUCKET_MAP = {
        9: "Front",
        12: "Front",
        15: "Front",
        18: "Middle",
        21: "Middle",
        24: "Middle",
        27: "Back",
        30: "Back",
        33: "Back",
    }

if "BUCKET_ORDER_MAP" not in globals():
    BUCKET_ORDER_MAP = {"Front": 1, "Middle": 2, "Back": 3}

if "LOCKED_MODEL_SPEC" not in globals():
    LOCKED_MODEL_SPEC = "unified_fds_no_min_return"

if "LEGACY_CORE_REFERENCE_THRESHOLDS" not in globals():
    LEGACY_CORE_REFERENCE_THRESHOLDS = {
        "Front": {
            "model_vrp_log": 0.60,
            "model_vrp_z_3m": 0.55,
            "model_vrp_z_1y": 0.65,
            "RSI14_max": 70.0,
            "forecast_vol_pct_min": 8.5,
        },
        "Middle": {
            "model_vrp_log": 0.65,
            "model_vrp_z_3m": 0.75,
            "model_vrp_z_1y": 0.65,
            "RSI14_max": 68.0,
            "forecast_vol_pct_min": 8.5,
        },
        "Back": {
            "model_vrp_log": 0.70,
            "model_vrp_z_3m": 0.70,
            "model_vrp_z_1y": 0.70,
            "RSI14_max": 70.0,
            "forecast_vol_pct_min": 8.5,
        },
    }

BUCKET_CENTER_TENOR = {
    "Front": 12,
    "Middle": 21,
    "Back": 30,
}

BASELINE_LABEL = "legacy_core_reference_thresholds"

# ======================================================================================
# 1. Helpers
# ======================================================================================

def latest_file(directory: Path, pattern: str, required: bool = True) -> Path | None:
    matches = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if matches:
        return matches[0]
    if required:
        raise FileNotFoundError(f"No file found in {directory} matching {pattern}")
    return None


def max_drawdown_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)
    if len(pnl) == 0:
        return np.nan
    cumulative = pnl.cumsum()
    running_max = cumulative.cummax()
    drawdown = cumulative - running_max
    return float(drawdown.min())


def worst_rolling_sum(pnl: pd.Series, window: int) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)
    if len(pnl) == 0:
        return np.nan
    if len(pnl) < window:
        return float(pnl.sum())
    return float(pnl.rolling(window=window, min_periods=window).sum().min())


def profit_factor_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").dropna()
    gross_profit = float(pnl[pnl > 0].sum())
    gross_loss = float(pnl[pnl < 0].sum())
    if gross_loss < 0:
        return gross_profit / abs(gross_loss)
    if gross_profit > 0:
        return np.inf
    return np.nan


def summarize_trade_set(df: pd.DataFrame, selection_universe: str, group_cols: list[str]) -> pd.DataFrame:
    """
    Summarize selected trade rows.

    Includes both total P&L and P&L/day diagnostics.
    P&L/day is the primary cross-tenor quality metric.
    """
    rows = []

    if df.empty:
        return pd.DataFrame()

    d = df.copy()
    d["normalized_pnl_dollars"] = pd.to_numeric(d["normalized_pnl_dollars"], errors="coerce")
    d["normalized_pnl_per_day"] = pd.to_numeric(d["normalized_pnl_per_day"], errors="coerce")
    d["win"] = pd.to_numeric(d["win"], errors="coerce")

    d = d[
        d["normalized_pnl_dollars"].notna()
        & d["normalized_pnl_per_day"].notna()
    ].copy()

    if d.empty:
        return pd.DataFrame()

    d = d.sort_values(["trade_date", "tenor"]).copy()

    for keys, g in d.groupby(group_cols, dropna=False):
        if not isinstance(keys, tuple):
            keys = (keys,)

        row = dict(zip(group_cols, keys))

        pnl = g["normalized_pnl_dollars"]
        pnl_day = g["normalized_pnl_per_day"]
        wins = g["win"]

        y2025 = g[g["trade_date"].dt.year == 2025].copy()

        row.update({
            "baseline_label": BASELINE_LABEL,
            "selection_universe": selection_universe,
            "trades": int(len(g)),
            "date_min": g["trade_date"].min(),
            "date_max": g["trade_date"].max(),
            "tenor_min": int(g["tenor"].min()) if g["tenor"].notna().any() else np.nan,
            "tenor_max": int(g["tenor"].max()) if g["tenor"].notna().any() else np.nan,
            "avg_tenor": float(g["tenor"].mean()) if g["tenor"].notna().any() else np.nan,

            # Win / raw P&L.
            "win_rate": float(wins.mean()) if wins.notna().sum() else np.nan,
            "total_pnl": float(pnl.sum()),
            "avg_pnl": float(pnl.mean()),
            "median_pnl": float(pnl.median()),
            "worst_trade": float(pnl.min()),
            "best_trade": float(pnl.max()),
            "profit_factor": profit_factor_from_pnl(pnl),
            "selected_trade_drawdown": max_drawdown_from_pnl(pnl),
            "worst_5_trade_sum": worst_rolling_sum(pnl, 5),
            "worst_10_trade_sum": worst_rolling_sum(pnl, 10),
            "worst_20_trade_sum": worst_rolling_sum(pnl, 20),
            "trades_le_neg_50k": int((pnl <= -50_000).sum()),
            "trades_le_neg_100k": int((pnl <= -100_000).sum()),
            "trades_le_neg_150k": int((pnl <= -150_000).sum()),

            # P&L/day — primary cross-tenor trade-quality metrics.
            "total_pnl_per_day_sum": float(pnl_day.sum()),
            "avg_pnl_per_day": float(pnl_day.mean()),
            "median_pnl_per_day": float(pnl_day.median()),
            "worst_trade_pnl_per_day": float(pnl_day.min()),
            "best_trade_pnl_per_day": float(pnl_day.max()),
            "profit_factor_pnl_per_day": profit_factor_from_pnl(pnl_day),
            "pnl_per_day_drawdown": max_drawdown_from_pnl(pnl_day),
            "worst_5_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 5),
            "worst_10_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 10),
            "worst_20_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 20),

            # 2025 behavior.
            "trades_2025": int(len(y2025)),
            "pnl_2025": float(y2025["normalized_pnl_dollars"].sum()) if len(y2025) else 0.0,
            "avg_pnl_2025": float(y2025["normalized_pnl_dollars"].mean()) if len(y2025) else np.nan,
            "avg_pnl_per_day_2025": float(y2025["normalized_pnl_per_day"].mean()) if len(y2025) else np.nan,
            "worst_trade_2025": float(y2025["normalized_pnl_dollars"].min()) if len(y2025) else np.nan,
            "worst_trade_pnl_per_day_2025": float(y2025["normalized_pnl_per_day"].min()) if len(y2025) else np.nan,
        })

        rows.append(row)

    return pd.DataFrame(rows)


def add_selection_ranks(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add diagnostic ranking fields for selecting one tenor when multiple pass.

    Diagnostic only:
      - rank z_1y descending
      - rank z_3m descending
      - rank model_vrp_log descending
      - average rank
      - tie-break by distance to bucket center
    """
    d = df.copy()

    d["bucket_center_tenor"] = d["tenor_bucket"].map(BUCKET_CENTER_TENOR)
    d["distance_to_bucket_center"] = (d["tenor"] - d["bucket_center_tenor"]).abs()

    rank_group = ["trade_date", "tenor_bucket"]

    d["rank_z_1y_in_bucket_date"] = (
        d.groupby(rank_group)["model_vrp_z_1y"]
        .rank(method="min", ascending=False)
    )
    d["rank_z_3m_in_bucket_date"] = (
        d.groupby(rank_group)["model_vrp_z_3m"]
        .rank(method="min", ascending=False)
    )
    d["rank_vrp_log_in_bucket_date"] = (
        d.groupby(rank_group)["model_vrp_log"]
        .rank(method="min", ascending=False)
    )

    d["avg_signal_rank_in_bucket_date"] = d[
        [
            "rank_z_1y_in_bucket_date",
            "rank_z_3m_in_bucket_date",
            "rank_vrp_log_in_bucket_date",
        ]
    ].mean(axis=1)

    # Global date ranks across all passing tenors.
    d["rank_z_1y_in_date"] = (
        d.groupby("trade_date")["model_vrp_z_1y"]
        .rank(method="min", ascending=False)
    )
    d["rank_z_3m_in_date"] = (
        d.groupby("trade_date")["model_vrp_z_3m"]
        .rank(method="min", ascending=False)
    )
    d["rank_vrp_log_in_date"] = (
        d.groupby("trade_date")["model_vrp_log"]
        .rank(method="min", ascending=False)
    )

    d["avg_signal_rank_in_date"] = d[
        [
            "rank_z_1y_in_date",
            "rank_z_3m_in_date",
            "rank_vrp_log_in_date",
        ]
    ].mean(axis=1)

    return d


def apply_legacy_core_thresholds(df: pd.DataFrame) -> pd.DataFrame:
    d = df.copy()

    d["core_model_vrp_log_threshold"] = d["tenor_bucket"].map(
        {k: v["model_vrp_log"] for k, v in LEGACY_CORE_REFERENCE_THRESHOLDS.items()}
    )
    d["core_model_vrp_z_3m_threshold"] = d["tenor_bucket"].map(
        {k: v["model_vrp_z_3m"] for k, v in LEGACY_CORE_REFERENCE_THRESHOLDS.items()}
    )
    d["core_model_vrp_z_1y_threshold"] = d["tenor_bucket"].map(
        {k: v["model_vrp_z_1y"] for k, v in LEGACY_CORE_REFERENCE_THRESHOLDS.items()}
    )
    d["core_RSI14_max"] = d["tenor_bucket"].map(
        {k: v["RSI14_max"] for k, v in LEGACY_CORE_REFERENCE_THRESHOLDS.items()}
    )
    d["core_forecast_vol_pct_min"] = d["tenor_bucket"].map(
        {k: v["forecast_vol_pct_min"] for k, v in LEGACY_CORE_REFERENCE_THRESHOLDS.items()}
    )

    d["core_threshold_inputs_available"] = (
        d["model_vrp_log"].notna()
        & d["model_vrp_z_3m"].notna()
        & d["model_vrp_z_1y"].notna()
        & d["RSI14"].notna()
        & d["forecast_vol_pct"].notna()
    )

    d["legacy_core_pass"] = (
        d["core_threshold_inputs_available"]
        & (d["model_vrp_log"] > d["core_model_vrp_log_threshold"])
        & (d["model_vrp_z_3m"] > d["core_model_vrp_z_3m_threshold"])
        & (d["model_vrp_z_1y"] > d["core_model_vrp_z_1y_threshold"])
        & (d["RSI14"] < d["core_RSI14_max"])
        & (d["forecast_vol_pct"] > d["core_forecast_vol_pct_min"])
    )

    d["trade_outcome_available"] = (
        d["normalized_pnl_dollars"].notna()
        & d["normalized_pnl_per_day"].notna()
    )

    return d


# ======================================================================================
# 2. Load clean signal base panel if needed
# ======================================================================================

if "signal" not in globals() or not isinstance(signal, pd.DataFrame) or signal.empty:
    base_panel_path = latest_file(
        OUT_PROCESSED_DIR,
        "01_unified_fds_signal_base_panel_*.parquet",
        required=True,
    )
    signal = pd.read_parquet(base_panel_path)
else:
    base_panel_path = globals().get("base_panel_path", None)

signal = signal.copy()
signal["trade_date"] = pd.to_datetime(signal["trade_date"], errors="coerce").dt.normalize()
signal["tenor"] = pd.to_numeric(signal["tenor"], errors="coerce").astype(int)

if "last_forward_rv_date" in signal.columns:
    signal["last_forward_rv_date"] = pd.to_datetime(
        signal["last_forward_rv_date"],
        errors="coerce",
    ).dt.normalize()

required_signal_cols = [
    "trade_date",
    "tenor",
    "tenor_bucket",
    "model_spec",
    "implied_variance",
    "forecast_variance",
    "implied_vol_pct",
    "forecast_vol_pct",
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14",
    "normalized_pnl_dollars",
    "normalized_pnl_per_day",
    "win",
]

missing_signal_cols = [c for c in required_signal_cols if c not in signal.columns]
if missing_signal_cols:
    raise KeyError(f"Cell 4 missing required signal columns: {missing_signal_cols}")

# ======================================================================================
# 3. Apply baseline Core thresholds
# ======================================================================================

baseline = apply_legacy_core_thresholds(signal)

# Add fixed baseline label for grouping / audit summaries.
baseline["baseline_label"] = BASELINE_LABEL

# Trade evaluation should only use rows with completed / available outcomes.
qualified_all = baseline[
    baseline["legacy_core_pass"]
    & baseline["trade_outcome_available"]
].copy()

# Trade evaluation should only use rows with completed / available outcomes.
qualified_all = baseline[
    baseline["legacy_core_pass"]
    & baseline["trade_outcome_available"]
].copy()

qualified_all = add_selection_ranks(qualified_all)

one_trade_per_bucket_date = (
    qualified_all
    .sort_values(
        [
            "trade_date",
            "tenor_bucket_order",
            "avg_signal_rank_in_bucket_date",
            "distance_to_bucket_center",
            "rank_z_1y_in_bucket_date",
            "rank_z_3m_in_bucket_date",
            "rank_vrp_log_in_bucket_date",
            "tenor",
        ],
        ascending=[True, True, True, True, True, True, True, True],
    )
    .groupby(["trade_date", "tenor_bucket"], as_index=False)
    .head(1)
    .copy()
)

one_trade_per_date = (
    qualified_all
    .sort_values(
        [
            "trade_date",
            "avg_signal_rank_in_date",
            "rank_z_1y_in_date",
            "rank_z_3m_in_date",
            "rank_vrp_log_in_date",
            "distance_to_bucket_center",
            "tenor_bucket_order",
            "tenor",
        ],
        ascending=[True, True, True, True, True, True, True, True],
    )
    .groupby(["trade_date"], as_index=False)
    .head(1)
    .copy()
)

thirty_day_anchor = qualified_all[qualified_all["tenor"] == 30].copy()

# Add selection flags back to full baseline panel.
baseline["selected_all_qualified"] = baseline["legacy_core_pass"] & baseline["trade_outcome_available"]

selected_bucket_keys = set(
    zip(
        one_trade_per_bucket_date["trade_date"],
        one_trade_per_bucket_date["tenor"],
    )
)
selected_date_keys = set(
    zip(
        one_trade_per_date["trade_date"],
        one_trade_per_date["tenor"],
    )
)
selected_30d_keys = set(
    zip(
        thirty_day_anchor["trade_date"],
        thirty_day_anchor["tenor"],
    )
)

baseline["_key"] = list(zip(baseline["trade_date"], baseline["tenor"]))
baseline["selected_one_trade_per_bucket_date_best_rank"] = baseline["_key"].isin(selected_bucket_keys)
baseline["selected_one_trade_per_date_best_rank"] = baseline["_key"].isin(selected_date_keys)
baseline["selected_thirty_day_anchor"] = baseline["_key"].isin(selected_30d_keys)
baseline = baseline.drop(columns=["_key"])

# ======================================================================================
# 4. Summaries
# ======================================================================================

summary_frames = []

summary_frames.append(
    summarize_trade_set(
        qualified_all,
        selection_universe="all_qualified_trades",
        group_cols=["baseline_label"],
    )
)

summary_frames.append(
    summarize_trade_set(
        one_trade_per_bucket_date,
        selection_universe="one_trade_per_bucket_per_date_best_rank",
        group_cols=["baseline_label"],
    )
)

summary_frames.append(
    summarize_trade_set(
        one_trade_per_date,
        selection_universe="one_trade_per_date_best_rank",
        group_cols=["baseline_label"],
    )
)

summary_frames.append(
    summarize_trade_set(
        thirty_day_anchor,
        selection_universe="thirty_day_anchor_only",
        group_cols=["baseline_label"],
    )
)

summary_overall = pd.concat(
    [x for x in summary_frames if x is not None and not x.empty],
    ignore_index=True,
) if any(x is not None and not x.empty for x in summary_frames) else pd.DataFrame()

by_bucket_frames = []
for universe_name, d in [
    ("all_qualified_trades", qualified_all),
    ("one_trade_per_bucket_per_date_best_rank", one_trade_per_bucket_date),
    ("one_trade_per_date_best_rank", one_trade_per_date),
    ("thirty_day_anchor_only", thirty_day_anchor),
]:
    s = summarize_trade_set(
        d,
        selection_universe=universe_name,
        group_cols=["tenor_bucket", "tenor_bucket_order"],
    )
    if not s.empty:
        by_bucket_frames.append(s)

summary_by_bucket = pd.concat(by_bucket_frames, ignore_index=True) if by_bucket_frames else pd.DataFrame()
if not summary_by_bucket.empty:
    summary_by_bucket = summary_by_bucket.sort_values(
        ["selection_universe", "tenor_bucket_order"]
    )

by_tenor_frames = []
for universe_name, d in [
    ("all_qualified_trades", qualified_all),
    ("one_trade_per_bucket_per_date_best_rank", one_trade_per_bucket_date),
    ("one_trade_per_date_best_rank", one_trade_per_date),
    ("thirty_day_anchor_only", thirty_day_anchor),
]:
    s = summarize_trade_set(
        d,
        selection_universe=universe_name,
        group_cols=["tenor", "tenor_bucket", "tenor_bucket_order"],
    )
    if not s.empty:
        by_tenor_frames.append(s)

summary_by_tenor = pd.concat(by_tenor_frames, ignore_index=True) if by_tenor_frames else pd.DataFrame()
if not summary_by_tenor.empty:
    summary_by_tenor = summary_by_tenor.sort_values(
        ["selection_universe", "tenor"]
    )

by_year_frames = []
for universe_name, d in [
    ("all_qualified_trades", qualified_all),
    ("one_trade_per_bucket_per_date_best_rank", one_trade_per_bucket_date),
    ("one_trade_per_date_best_rank", one_trade_per_date),
    ("thirty_day_anchor_only", thirty_day_anchor),
]:
    if not d.empty:
        dy = d.copy()
        dy["year"] = dy["trade_date"].dt.year.astype(int)
        s = summarize_trade_set(
            dy,
            selection_universe=universe_name,
            group_cols=["year"],
        )
        if not s.empty:
            by_year_frames.append(s)

summary_by_year = pd.concat(by_year_frames, ignore_index=True) if by_year_frames else pd.DataFrame()
if not summary_by_year.empty:
    summary_by_year = summary_by_year.sort_values(
        ["selection_universe", "year"]
    )

# Pass-rate diagnostics, including rows without trade outcomes.
pass_diagnostics_by_tenor = (
    baseline.groupby(["tenor", "tenor_bucket", "tenor_bucket_order"], as_index=False)
    .agg(
        rows=("trade_date", "size"),
        threshold_inputs_available_rows=("core_threshold_inputs_available", "sum"),
        pass_rows_all_dates=("legacy_core_pass", "sum"),
        trade_outcome_available_rows=("trade_outcome_available", "sum"),
        pass_rows_with_outcomes=("selected_all_qualified", "sum"),
        avg_model_vrp_log=("model_vrp_log", "mean"),
        avg_z_3m=("model_vrp_z_3m", "mean"),
        avg_z_1y=("model_vrp_z_1y", "mean"),
        avg_RSI14=("RSI14", "mean"),
        avg_forecast_vol_pct=("forecast_vol_pct", "mean"),
        avg_implied_vol_pct=("implied_vol_pct", "mean"),
    )
    .sort_values("tenor")
)

pass_diagnostics_by_tenor["pass_rate_all_dates"] = (
    pass_diagnostics_by_tenor["pass_rows_all_dates"]
    / pass_diagnostics_by_tenor["threshold_inputs_available_rows"].replace(0, np.nan)
)

pass_diagnostics_by_tenor["pass_rate_with_outcomes"] = (
    pass_diagnostics_by_tenor["pass_rows_with_outcomes"]
    / pass_diagnostics_by_tenor["trade_outcome_available_rows"].replace(0, np.nan)
)

pass_diagnostics_by_bucket = (
    baseline.groupby(["tenor_bucket", "tenor_bucket_order"], as_index=False)
    .agg(
        rows=("trade_date", "size"),
        threshold_inputs_available_rows=("core_threshold_inputs_available", "sum"),
        pass_rows_all_dates=("legacy_core_pass", "sum"),
        trade_outcome_available_rows=("trade_outcome_available", "sum"),
        pass_rows_with_outcomes=("selected_all_qualified", "sum"),
        avg_model_vrp_log=("model_vrp_log", "mean"),
        avg_z_3m=("model_vrp_z_3m", "mean"),
        avg_z_1y=("model_vrp_z_1y", "mean"),
        avg_RSI14=("RSI14", "mean"),
        avg_forecast_vol_pct=("forecast_vol_pct", "mean"),
        avg_implied_vol_pct=("implied_vol_pct", "mean"),
    )
    .sort_values("tenor_bucket_order")
)

pass_diagnostics_by_bucket["pass_rate_all_dates"] = (
    pass_diagnostics_by_bucket["pass_rows_all_dates"]
    / pass_diagnostics_by_bucket["threshold_inputs_available_rows"].replace(0, np.nan)
)

pass_diagnostics_by_bucket["pass_rate_with_outcomes"] = (
    pass_diagnostics_by_bucket["pass_rows_with_outcomes"]
    / pass_diagnostics_by_bucket["trade_outcome_available_rows"].replace(0, np.nan)
)

# ======================================================================================
# 5. Save outputs
# ======================================================================================

date_min = baseline["trade_date"].min()
date_max = baseline["trade_date"].max()

baseline_panel_path = OUT_PROCESSED_DIR / (
    f"02_legacy_core_baseline_trade_panel_{date_min:%Y%m%d}_{date_max:%Y%m%d}_{TIMESTAMP}.parquet"
)
qualified_panel_path = OUT_PROCESSED_DIR / (
    f"02_legacy_core_baseline_qualified_trade_panel_{date_min:%Y%m%d}_{date_max:%Y%m%d}_{TIMESTAMP}.parquet"
)

summary_overall_path = OUT_AUDIT_DIR / f"02_legacy_core_baseline_summary_{TIMESTAMP}.csv"
summary_by_year_path = OUT_AUDIT_DIR / f"02_legacy_core_baseline_by_year_{TIMESTAMP}.csv"
summary_by_bucket_path = OUT_AUDIT_DIR / f"02_legacy_core_baseline_by_bucket_{TIMESTAMP}.csv"
summary_by_tenor_path = OUT_AUDIT_DIR / f"02_legacy_core_baseline_by_tenor_{TIMESTAMP}.csv"
pass_diag_by_bucket_path = OUT_AUDIT_DIR / f"02_legacy_core_baseline_pass_diagnostics_by_bucket_{TIMESTAMP}.csv"
pass_diag_by_tenor_path = OUT_AUDIT_DIR / f"02_legacy_core_baseline_pass_diagnostics_by_tenor_{TIMESTAMP}.csv"
thresholds_used_path = OUT_AUDIT_DIR / f"02_legacy_core_baseline_thresholds_used_{TIMESTAMP}.csv"
validation_path = OUT_AUDIT_DIR / f"02_legacy_core_baseline_validation_{TIMESTAMP}.csv"
manifest_path = OUT_AUDIT_DIR / f"02_legacy_core_baseline_manifest_{TIMESTAMP}.json"

baseline.to_parquet(baseline_panel_path, index=False)
qualified_all.to_parquet(qualified_panel_path, index=False)

summary_overall.to_csv(summary_overall_path, index=False)
summary_by_year.to_csv(summary_by_year_path, index=False)
summary_by_bucket.to_csv(summary_by_bucket_path, index=False)
summary_by_tenor.to_csv(summary_by_tenor_path, index=False)
pass_diagnostics_by_bucket.to_csv(pass_diag_by_bucket_path, index=False)
pass_diagnostics_by_tenor.to_csv(pass_diag_by_tenor_path, index=False)

threshold_rows = []
for bucket, params in LEGACY_CORE_REFERENCE_THRESHOLDS.items():
    row = {"tenor_bucket": bucket, "tenor_bucket_order": BUCKET_ORDER_MAP[bucket]}
    row.update(params)
    threshold_rows.append(row)

thresholds_used = pd.DataFrame(threshold_rows).sort_values("tenor_bucket_order")
thresholds_used.to_csv(thresholds_used_path, index=False)

# ======================================================================================
# 6. Validation
# ======================================================================================

validation_rows = []

def add_validation(check: str, status: str, detail: str):
    validation_rows.append({"check": check, "status": status, "detail": detail})

models_found = sorted(baseline["model_spec"].dropna().unique().tolist())
tenors_found = sorted(baseline["tenor"].dropna().astype(int).unique().tolist())
missing_tenors = sorted(set(ALL_TENORS) - set(tenors_found))
extra_tenors = sorted(set(tenors_found) - set(ALL_TENORS))
duplicate_key_count = int(baseline.duplicated(["trade_date", "tenor"]).sum())

bad_pnl_day = baseline[
    baseline["normalized_pnl_dollars"].notna()
    & baseline["normalized_pnl_per_day"].notna()
    & (
        (
            baseline["normalized_pnl_dollars"] / baseline["tenor"].replace(0, np.nan)
        )
        - baseline["normalized_pnl_per_day"]
    ).abs().gt(1e-8)
]

add_validation(
    "locked_model_only",
    "PASS" if models_found == [LOCKED_MODEL_SPEC] else "FAIL",
    f"models_found={models_found}",
)

add_validation(
    "one_row_per_trade_date_tenor",
    "PASS" if duplicate_key_count == 0 else "FAIL",
    f"duplicate_key_count={duplicate_key_count}",
)

add_validation(
    "all_exact_tenors_present",
    "PASS" if not missing_tenors and not extra_tenors else "FAIL",
    f"missing={missing_tenors}; extra={extra_tenors}",
)

add_validation(
    "legacy_core_thresholds_applied",
    "PASS" if "legacy_core_pass" in baseline.columns else "FAIL",
    f"qualified_rows_with_outcomes={len(qualified_all):,}",
)

add_validation(
    "normalized_pnl_per_day_formula",
    "PASS" if bad_pnl_day.empty else "FAIL",
    f"bad_rows={len(bad_pnl_day):,}; formula=normalized_pnl_dollars / tenor",
)

add_validation(
    "selection_all_qualified_created",
    "PASS" if len(qualified_all) > 0 else "WARN",
    f"rows={len(qualified_all):,}",
)

add_validation(
    "selection_one_trade_per_bucket_date_created",
    "PASS" if len(one_trade_per_bucket_date) > 0 else "WARN",
    f"rows={len(one_trade_per_bucket_date):,}",
)

add_validation(
    "selection_one_trade_per_date_created",
    "PASS" if len(one_trade_per_date) > 0 else "WARN",
    f"rows={len(one_trade_per_date):,}",
)

add_validation(
    "selection_thirty_day_anchor_created",
    "PASS" if len(thirty_day_anchor) > 0 else "WARN",
    f"rows={len(thirty_day_anchor):,}",
)

add_validation(
    "no_threshold_sweep",
    "PASS",
    "Only one fixed legacy/reference Core threshold set was evaluated.",
)

add_validation(
    "no_secondary",
    "PASS",
    "No Secondary threshold logic evaluated.",
)

add_validation(
    "diagnostic_selection_only",
    "PASS",
    "Best-rank DTE selection is diagnostic only, not a production lock.",
)

validation = pd.DataFrame(validation_rows)
validation.to_csv(validation_path, index=False)

failures = validation[validation["status"] == "FAIL"]

manifest = {
    "notebook": "07_unified_fds_core_signal_threshold_research_v1.ipynb",
    "cell": "Cell 4 — Legacy Core baseline diagnostic using P&L/day",
    "timestamp": TIMESTAMP,
    "base_panel_path": str(base_panel_path),
    "baseline_panel_path": str(baseline_panel_path),
    "qualified_panel_path": str(qualified_panel_path),
    "summary_overall_path": str(summary_overall_path),
    "summary_by_year_path": str(summary_by_year_path),
    "summary_by_bucket_path": str(summary_by_bucket_path),
    "summary_by_tenor_path": str(summary_by_tenor_path),
    "pass_diag_by_bucket_path": str(pass_diag_by_bucket_path),
    "pass_diag_by_tenor_path": str(pass_diag_by_tenor_path),
    "thresholds_used_path": str(thresholds_used_path),
    "validation_path": str(validation_path),
    "locked_model_spec": LOCKED_MODEL_SPEC,
    "baseline_label": BASELINE_LABEL,
    "thresholds_used": LEGACY_CORE_REFERENCE_THRESHOLDS,
    "primary_cross_tenor_trade_quality_metric": "avg_pnl_per_day",
    "pnl_per_day_formula": "normalized_pnl_dollars / tenor",
    "selection_universes": [
        "all_qualified_trades",
        "one_trade_per_bucket_per_date_best_rank",
        "one_trade_per_date_best_rank",
        "thirty_day_anchor_only",
    ],
    "notes": [
        "No threshold sweep performed.",
        "No Secondary research performed.",
        "No sizing changes performed.",
        "Best-rank DTE selection is diagnostic only.",
        "Total P&L retained, but P&L/day is the primary cross-tenor quality metric.",
    ],
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2)

if not failures.empty:
    display(validation)
    raise RuntimeError("Cell 4 validation failed. Review validation output above.")

# ======================================================================================
# 7. Display concise review
# ======================================================================================

print("=" * 100)
print("Cell 4 — Legacy Core baseline diagnostic using P&L/day")
print("=" * 100)
print(f"Signal base panel:             {base_panel_path}")
print(f"Baseline trade panel:          {baseline_panel_path}")
print(f"Qualified trade panel:         {qualified_panel_path}")
print(f"Date range:                    {date_min.date()} to {date_max.date()}")
print(f"Rows:                          {len(baseline):,}")
print(f"All qualified rows:            {len(qualified_all):,}")
print(f"One per bucket/date rows:      {len(one_trade_per_bucket_date):,}")
print(f"One per date rows:             {len(one_trade_per_date):,}")
print(f"30D anchor rows:               {len(thirty_day_anchor):,}")
print("Primary quality metric:        avg_pnl_per_day")
print("No threshold sweep:            True")
print("No Secondary:                  True")
print("Diagnostic DTE selector only:  True")

print()
print("Validation:")
display(validation)

print()
print("Thresholds used:")
display(thresholds_used)

print()
print("Pass diagnostics by bucket:")
display(pass_diagnostics_by_bucket)

print()
print("Pass diagnostics by tenor:")
display(pass_diagnostics_by_tenor)

print()
print("Overall baseline summary:")
overall_display_cols = [
    "selection_universe",
    "trades",
    "date_min",
    "date_max",
    "avg_tenor",
    "win_rate",
    "total_pnl",
    "profit_factor",
    "avg_pnl",
    "avg_pnl_per_day",
    "median_pnl_per_day",
    "worst_trade",
    "worst_trade_pnl_per_day",
    "selected_trade_drawdown",
    "pnl_per_day_drawdown",
    "worst_20_trade_sum",
    "worst_20_trade_pnl_per_day_sum",
    "trades_le_neg_100k",
    "pnl_2025",
    "avg_pnl_per_day_2025",
    "worst_trade_2025",
]
display(
    summary_overall[
        [c for c in overall_display_cols if c in summary_overall.columns]
    ]
)

print()
print("Baseline summary by bucket:")
bucket_display_cols = [
    "selection_universe",
    "tenor_bucket",
    "trades",
    "avg_tenor",
    "win_rate",
    "total_pnl",
    "profit_factor",
    "avg_pnl",
    "avg_pnl_per_day",
    "median_pnl_per_day",
    "worst_trade",
    "worst_trade_pnl_per_day",
    "selected_trade_drawdown",
    "pnl_per_day_drawdown",
    "trades_le_neg_100k",
    "pnl_2025",
    "avg_pnl_per_day_2025",
]
display(
    summary_by_bucket[
        [c for c in bucket_display_cols if c in summary_by_bucket.columns]
    ]
)

print()
print("Baseline summary by tenor:")
tenor_display_cols = [
    "selection_universe",
    "tenor",
    "tenor_bucket",
    "trades",
    "win_rate",
    "total_pnl",
    "profit_factor",
    "avg_pnl",
    "avg_pnl_per_day",
    "median_pnl_per_day",
    "worst_trade",
    "worst_trade_pnl_per_day",
    "trades_le_neg_100k",
    "pnl_2025",
    "avg_pnl_per_day_2025",
]
display(
    summary_by_tenor[
        [c for c in tenor_display_cols if c in summary_by_tenor.columns]
    ]
)

print()
print("Baseline summary by year:")
year_display_cols = [
    "selection_universe",
    "year",
    "trades",
    "avg_tenor",
    "win_rate",
    "total_pnl",
    "profit_factor",
    "avg_pnl",
    "avg_pnl_per_day",
    "median_pnl_per_day",
    "worst_trade",
    "worst_trade_pnl_per_day",
    "trades_le_neg_100k",
]
display(
    summary_by_year[
        [c for c in year_display_cols if c in summary_by_year.columns]
    ]
)

print()
print("Saved outputs:")
saved_paths = [
    baseline_panel_path,
    qualified_panel_path,
    summary_overall_path,
    summary_by_year_path,
    summary_by_bucket_path,
    summary_by_tenor_path,
    pass_diag_by_bucket_path,
    pass_diag_by_tenor_path,
    thresholds_used_path,
    validation_path,
    manifest_path,
]
for p in saved_paths:
    print(f"  {p}")

print("\nCELL 4 PASSED")

====================================================================================================
Cell 4 — Legacy Core baseline diagnostic using P&L/day
====================================================================================================
Signal base panel:             C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\01_unified_fds_signal_base_panel_20200102_20260701_20260704_211636.parquet
Baseline trade panel:          C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_trade_panel_20200102_20260701_20260704_211636.parquet
Qualified trade panel:         C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_qualified_trade_panel_20200102_20260701_20260704_211636.parquet
Date range:                    2020-01-02 to 2026-07-01
Rows:                          14,688
All qualified rows:            1,516
One per bucket/date rows:      572
One per date rows:             271
30D anchor rows:               149
Primary quality metric:        avg_pnl_per_day
No threshold sweep:            True
No Secondary:                  True
Diagnostic DTE selector only:  True

Validation:

                                          check status                                             detail
0                             locked_model_only   PASS         models_found=['unified_fds_no_min_return']
1                  one_row_per_trade_date_tenor   PASS                              duplicate_key_count=0
2                      all_exact_tenors_present   PASS                               missing=[]; extra=[]
3                legacy_core_thresholds_applied   PASS                 qualified_rows_with_outcomes=1,516
4                normalized_pnl_per_day_formula   PASS  bad_rows=0; formula=normalized_pnl_dollars / t...
5               selection_all_qualified_created   PASS                                         rows=1,516
6   selection_one_trade_per_bucket_date_created   PASS                                           rows=572
7          selection_one_trade_per_date_created   PASS                                           rows=271
8           selection_thirty_day_anchor_created   PASS                                           rows=149
9                            no_threshold_sweep   PASS  Only one fixed legacy/reference Core threshold...
10                                 no_secondary   PASS            No Secondary threshold logic evaluated.
11                    diagnostic_selection_only   PASS  Best-rank DTE selection is diagnostic only, no...

Thresholds used:

  tenor_bucket  tenor_bucket_order  model_vrp_log  model_vrp_z_3m  model_vrp_z_1y  RSI14_max  forecast_vol_pct_min
0        Front                   1           0.60            0.55            0.65       70.0                   8.5
1       Middle                   2           0.65            0.75            0.65       68.0                   8.5
2         Back                   3           0.70            0.70            0.70       70.0                   8.5

Pass diagnostics by bucket:

  tenor_bucket  tenor_bucket_order  rows  threshold_inputs_available_rows  pass_rows_all_dates  trade_outcome_available_rows  pass_rows_with_outcomes  avg_model_vrp_log  avg_z_3m  avg_z_1y  avg_RSI14  avg_forecast_vol_pct  avg_implied_vol_pct  pass_rate_all_dates  pass_rate_with_outcomes
1        Front                   1  4896                             4140                  626                          4852                      626           0.586669 -0.028588 -0.132722  55.649311             14.867199            20.073584             0.151208                 0.129019
2       Middle                   2  4896                             4140                  441                          4832                      441           0.592387 -0.052434 -0.148519  55.649311             14.963731            20.489803             0.106522                 0.091267
0         Back                   3  4896                             4140                  449                          4815                      449           0.606769 -0.085194 -0.144797  55.649311             15.024010            20.862671             0.108454                 0.093250

Pass diagnostics by tenor:

   tenor tenor_bucket  tenor_bucket_order  rows  threshold_inputs_available_rows  pass_rows_all_dates  trade_outcome_available_rows  pass_rows_with_outcomes  avg_model_vrp_log  avg_z_3m  avg_z_1y  avg_RSI14  avg_forecast_vol_pct  avg_implied_vol_pct  pass_rate_all_dates  pass_rate_with_outcomes
0      9        Front                   1  1632                             1380                  215                          1620                      215           0.574855 -0.019909 -0.123148  55.649311             14.892609            19.913988             0.155797                 0.132716
1     12        Front                   1  1632                             1380                  219                          1617                      219           0.619382 -0.027503 -0.131594  55.649311             14.657151            20.084706             0.158696                 0.135436
2     15        Front                   1  1632                             1380                  192                          1615                      192           0.565772 -0.038352 -0.143425  55.649311             15.051838            20.222058             0.139130                 0.118885
3     18       Middle                   2  1632                             1380                  150                          1613                      150           0.599534 -0.043465 -0.145949  55.649311             14.867733            20.363649             0.108696                 0.092994
4     21       Middle                   2  1632                             1380                  145                          1610                      145           0.580522 -0.050834 -0.147411  55.649311             15.045946            20.491143             0.105072                 0.090062
5     24       Middle                   2  1632                             1380                  146                          1609                      146           0.597104 -0.063003 -0.152197  55.649311             14.977513            20.614617             0.105797                 0.090740
6     27         Back                   3  1632                             1380                  150                          1606                      150           0.606214 -0.072916 -0.145998  55.649311             14.968975            20.742690             0.108696                 0.093400
7     30         Back                   3  1632                             1380                  149                          1606                      149           0.597346 -0.087323 -0.147475  55.649311             15.085066            20.861959             0.107971                 0.092777
8     33         Back                   3  1632                             1380                  150                          1603                      150           0.616746 -0.095345 -0.140919  55.649311             15.017990            20.983364             0.108696                 0.093575

Overall baseline summary:

,selection_universe,trades,date_min,date_max,avg_tenor,win_rate,total_pnl,profit_factor,avg_pnl,avg_pnl_per_day,median_pnl_per_day,worst_trade,worst_trade_pnl_per_day,selected_trade_drawdown,pnl_per_day_drawdown,worst_20_trade_sum,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025
0,all_qualified_trades,1516,2020-12-31,2026-04-29,19.895778,0.831794,1.618933e+07,3.356787,10678.975291,497.719778,828.459104,-108475.796818,-10843.526096,-2.374676e+06,-142968.943249,-1.381033e+06,-81685.473081,5,3.613112e+06,561.800760,-97591.734861
1,one_trade_per_bucket_per_date_best_rank,572,2020-12-31,2026-04-29,19.468531,0.835664,5.890958e+06,3.302506,10298.877931,444.366425,813.313734,-108475.796818,-10843.526096,-7.917038e+05,-54837.874446,-4.903769e+05,-31567.776933,1,1.353028e+06,509.416529,-97591.734861
2,one_trade_per_date_best_rank,271,2020-12-31,2026-04-29,18.675277,0.826568,2.564921e+06,2.965809,9464.653426,317.598665,815.608298,-97591.734861,-10843.526096,-2.172410e+05,-25896.932035,-1.466307e+05,-18376.039701,0,5.071451e+05,331.359125,-97591.734861
3,thirty_day_anchor_only,149,2021-11-24,2026-04-29,30.000000,0.912752,2.609075e+06,6.144710,17510.567838,583.685595,760.748549,-103670.923339,-3455.697445,-2.264450e+05,-7548.166806,-4.090111e+04,-1363.370357,1,5.220439e+05,470.309858,-92588.332880

Baseline summary by bucket:

                        selection_universe tenor_bucket  trades  avg_tenor  win_rate     total_pnl  profit_factor       avg_pnl  avg_pnl_per_day  median_pnl_per_day    worst_trade  worst_trade_pnl_per_day  selected_trade_drawdown  pnl_per_day_drawdown  trades_le_neg_100k      pnl_2025  avg_pnl_per_day_2025
1                     all_qualified_trades        Front     626  11.889776  0.758786  2.990948e+06       1.833926   4777.871610       378.057737          929.785668 -108475.796818            -10843.526096            -1.043128e+06         -89407.280791                   1  9.393989e+05            557.425000
2                     all_qualified_trades       Middle     441  20.972789  0.854875  5.395172e+06       4.037928  12233.950381       585.672602          890.138242 -108475.796818             -6026.433157            -1.100582e+06         -53372.354016                   2  1.078530e+06            694.609610
0                     all_qualified_trades         Back     449  30.000000  0.910913  7.803207e+06       6.178966  17379.079724       578.167980          749.380192 -103670.923339             -3455.697445            -6.618667e+05         -22592.617567                   2  1.595182e+06            478.622817
4  one_trade_per_bucket_per_date_best_rank        Front     254  11.645669  0.775591  1.111919e+06       1.761633   4377.634070       291.824914          883.253425  -97591.734861            -10843.526096            -3.651900e+05         -32616.889530                   0  3.694666e+05            418.435971
5  one_trade_per_bucket_per_date_best_rank       Middle     161  21.279503  0.857143  2.020946e+06       4.278450  12552.458906       561.018598          816.603529 -108475.796818             -6026.433157            -3.885260e+05         -20774.019539                   1  4.096800e+05            696.485135
3  one_trade_per_bucket_per_date_best_rank         Back     157  30.267516  0.910828  2.758093e+06       6.720384  17567.472859       571.529126          725.641743  -92579.572354             -3428.873050            -2.390255e+05          -8575.316243                   0  5.738815e+05            515.211913
7             one_trade_per_date_best_rank        Front     149  10.550336  0.724832  1.214388e+05       1.105633    815.025328         8.022641          811.253139  -97591.734861            -10843.526096            -3.284433e+05         -37700.273110                   0  5.936995e+04             93.790767
8             one_trade_per_date_best_rank       Middle      39  21.538462  0.923077  5.864401e+05      12.991430  15036.924744       685.905668          738.125423  -43456.123262             -2414.229070            -4.345612e+04          -2414.229070                   0  1.978255e+05            645.693581
6             one_trade_per_date_best_rank         Back      83  31.915663  0.963855  1.857042e+06      18.481184  22374.002886       700.283660          838.377164  -41205.775564             -1248.659866            -4.120578e+04          -1248.659866                   0  2.499496e+05            491.733734
9                   thirty_day_anchor_only         Back     149  30.000000  0.912752  2.609075e+06       6.144710  17510.567838       583.685595          760.748549 -103670.923339             -3455.697445            -2.264450e+05          -7548.166806                   1  5.220439e+05            470.309858

Baseline summary by tenor:

                         selection_universe  tenor tenor_bucket  trades  win_rate     total_pnl  profit_factor       avg_pnl  avg_pnl_per_day  median_pnl_per_day    worst_trade  worst_trade_pnl_per_day  trades_le_neg_100k       pnl_2025  avg_pnl_per_day_2025
0                      all_qualified_trades      9        Front     215  0.716279  4.718107e+05       1.332341   2194.468466       243.829830          974.669129  -97591.734861            -10843.526096                   0  183708.799766            537.160233
1                      all_qualified_trades     12        Front     219  0.757991  9.778962e+05       1.778103   4465.279246       372.106604          927.671694  -93387.142625             -7782.261885                   0  301102.221792            512.078608
2                      all_qualified_trades     15        Front     192  0.807292  1.541241e+06       2.693380   8027.295586       535.153039          856.814928 -108475.796818             -7231.719788                   1  454587.889537            618.486925
3                      all_qualified_trades     18       Middle     150  0.840000  1.596866e+06       3.667159  10645.775517       591.431973          948.175200 -108475.796818             -6026.433157                   1  306184.345567            680.409657
4                      all_qualified_trades     21       Middle     145  0.868966  1.899085e+06       4.373309  13097.141061       623.673384          924.055271 -108475.796818             -5165.514134                   1  371243.158060            736.593568
5                      all_qualified_trades     24       Middle     146  0.856164  1.899220e+06       4.091935  13008.358471       542.014936          813.997671  -92579.572354             -3857.482181                   0  401102.977593            668.504963
6                      all_qualified_trades     27         Back     150  0.886667  2.261703e+06       4.622321  15078.020966       558.445221          799.790089  -92588.332880             -3429.197514                   0  476139.167658            476.615783
7                      all_qualified_trades     30         Back     149  0.912752  2.609075e+06       6.144710  17510.567838       583.685595          760.748549 -103670.923339             -3455.697445                   1  522043.942659            470.309858
8                      all_qualified_trades     33         Back     150  0.933333  2.932429e+06       8.815754  19549.526954       592.409908          707.910764 -103670.923339             -3141.543131                   1  596999.171873            488.942811
9   one_trade_per_bucket_per_date_best_rank      9        Front      99  0.717172 -1.252547e+05       0.867058  -1265.199033      -140.577670          963.929498  -97591.734861            -10843.526096                   0  -36177.604344           -334.977818
10  one_trade_per_bucket_per_date_best_rank     12        Front      86  0.720930  3.337480e+05       1.743913   3880.790950       323.399246          722.590964  -39182.024065             -3265.168672                   0   74764.337178            311.518072
11  one_trade_per_bucket_per_date_best_rank     15        Front      69  0.927536  9.034257e+05      14.074811  13093.126616       872.875108          992.901604  -22485.261081             -1499.017405                   0  330879.880118            848.409949
12  one_trade_per_bucket_per_date_best_rank     18       Middle      60  0.750000  2.624900e+05       1.588480   4374.832571       243.046254          689.874138 -108475.796818             -6026.433157                   1   74960.341955            462.718160
13  one_trade_per_bucket_per_date_best_rank     21       Middle      26  0.961538  4.153333e+05      13.516676  15974.357195       760.683676          853.526186  -33182.394118             -1580.114006                   0  116589.422117            925.312874
14  one_trade_per_bucket_per_date_best_rank     24       Middle      75  0.906667  1.343123e+06      10.789285  17908.301900       746.179246          999.240182  -44692.201363             -1862.175057                   0  218130.191078            757.396497
15  one_trade_per_bucket_per_date_best_rank     27         Back      64  0.890625  7.946444e+05       3.772550  12416.319396       459.863681          551.599082  -92579.572354             -3428.873050                   0  362079.851866            515.783265
16  one_trade_per_bucket_per_date_best_rank     30         Back      15  0.866667  2.641151e+05       7.929464  17607.671904       586.922397          667.955404  -24704.938663              -823.497955                   0   87340.106049            970.445623
17  one_trade_per_bucket_per_date_best_rank     33         Back      78  0.935897  1.699334e+06      11.794523  21786.329730       660.191810          827.964633  -48751.416767             -1477.315660                   0  124461.574059            377.156285
18             one_trade_per_date_best_rank      9        Front      95  0.705263 -1.832756e+05       0.805477  -1929.217112      -214.357457          889.105063  -97591.734861            -10843.526096                   0  -36177.604344           -334.977818
19             one_trade_per_date_best_rank     12        Front      31  0.677419  7.470232e+04       1.497147   2409.752121       200.812677          635.126605  -39182.024065             -3265.168672                   0   27817.193774            257.566609
20             one_trade_per_date_best_rank     15        Front      23  0.869565  2.300121e+05       5.021921  10000.525379       666.701692          834.214020  -25919.354017             -1727.956934                   0   67730.360341            501.706373
21             one_trade_per_date_best_rank     18       Middle      10  0.800000  6.501047e+04       2.435188   6501.047409       361.169301          679.662269  -43456.123262             -2414.229070                   0   16093.677664            298.031068
22             one_trade_per_date_best_rank     21       Middle      12  1.000000  2.372824e+05            inf  19773.531145       941.596721          948.772253   12396.264410               590.298305                   0   96340.934637            917.532711
23             one_trade_per_date_best_rank     24       Middle      17  0.941176  2.841472e+05      79.768088  16714.542186       696.439258          586.101625   -3607.390045              -150.307919                   0   85390.881085            592.992230
24             one_trade_per_date_best_rank     27         Back      11  1.000000  1.936114e+05            inf  17601.040087       651.890374          490.611603    9846.425377               364.682421                   0   87298.162926            461.895042
25             one_trade_per_date_best_rank     30         Back       8  1.000000  1.800994e+05            inf  22512.425547       750.414185          609.067883     339.761603                11.325387                   0   65134.060866           1085.567681
26             one_trade_per_date_best_rank     33         Back      64  0.953125  1.483331e+06      14.963274  23177.053034       702.334940          848.184256  -41205.775564             -1248.659866                   0   97517.403201            369.384103
27                   thirty_day_anchor_only     30         Back     149  0.912752  2.609075e+06       6.144710  17510.567838       583.685595          760.748549 -103670.923339             -3455.697445                   1  522043.942659            470.309858

Baseline summary by year:

                         selection_universe  year  trades  avg_tenor  win_rate     total_pnl  profit_factor       avg_pnl  avg_pnl_per_day  median_pnl_per_day    worst_trade  worst_trade_pnl_per_day  trades_le_neg_100k
0                      all_qualified_trades  2020       3  14.000000  1.000000  3.205478e+04            inf  10684.926887       786.205350          809.800314    7640.965158               699.819606                   0
1                      all_qualified_trades  2021      44  18.409091  0.795455  5.320991e+05       5.649787  12093.161408       556.328944          919.725315  -27346.824178             -3038.536020                   0
2                      all_qualified_trades  2022     610  20.621311  0.863934  9.310524e+06       4.388050  15263.154751       688.171248         1070.124798 -108475.796818            -10376.349181                   5
3                      all_qualified_trades  2023      55  13.636364  0.854545  4.514193e+05       2.708876   8207.624361       528.665736         1067.983722  -49261.410409             -5473.490045                   0
4                      all_qualified_trades  2024     217  18.165899  0.898618  2.215444e+06      11.301579  10209.420327       578.955983          635.126605  -17160.183108             -1713.991609                   0
5                      all_qualified_trades  2025     321  20.401869  0.919003  3.613112e+06       6.499567  11255.799609       561.800760          647.312944  -97591.734861            -10843.526096                   0
6                      all_qualified_trades  2026     266  20.639098  0.597744  3.467304e+04       1.012079    130.349759      -101.979228          663.056652  -59939.127377             -4353.558229                   0
7   one_trade_per_bucket_per_date_best_rank  2020       2  15.000000  1.000000  2.233718e+04            inf  11168.588445       774.407867          774.407867    7640.965158               699.819606                   0
8   one_trade_per_bucket_per_date_best_rank  2021      19  16.894737  0.789474  1.911491e+05       4.405221  10060.477904       488.436003          899.315728  -21201.476345             -2355.719594                   0
9   one_trade_per_bucket_per_date_best_rank  2022     217  21.110599  0.852535  3.190454e+06       3.906377  14702.552075       553.455733         1052.045145 -108475.796818            -10376.349181                   1
10  one_trade_per_bucket_per_date_best_rank  2023      29  11.793103  0.862069  2.174992e+05       2.606499   7499.973333       596.524477         1206.495202  -49261.410409             -5473.490045                   0
11  one_trade_per_bucket_per_date_best_rank  2024      89  17.426966  0.921348  9.131207e+05      14.024484  10259.782641       627.594890          668.949699  -17160.183108             -1713.991609                   0
12  one_trade_per_bucket_per_date_best_rank  2025     124  19.645161  0.927419  1.353028e+06       6.677848  10911.516936       509.416529          659.432646  -97591.734861            -10843.526096                   0
13  one_trade_per_bucket_per_date_best_rank  2026      92  20.380435  0.586957  3.370137e+03       1.003508     36.631928      -142.110905          614.743532  -48751.416767             -3265.168672                   0
14             one_trade_per_date_best_rank  2020       1   9.000000  1.000000  7.640965e+03            inf   7640.965158       848.996129          848.996129    7640.965158               848.996129                   0
15             one_trade_per_date_best_rank  2021      11  12.818182  0.636364  2.858359e+04       1.509202   2598.508348       162.162344          326.212481  -21201.476345             -2355.719594                   0
16             one_trade_per_date_best_rank  2022      90  22.200000  0.822222  1.229057e+06       2.989005  13656.185200       199.006769          956.842391  -93387.142625            -10376.349181                   0
17             one_trade_per_date_best_rank  2023      22   9.954545  0.863636  1.459588e+05       2.490877   6634.492282       658.727376         1364.863605  -49261.410409             -5473.490045                   0
18             one_trade_per_date_best_rank  2024      53  15.735849  0.924528  5.202529e+05      11.636631   9816.092027       662.710131          712.345615  -17160.183108             -1713.991609                   0
19             one_trade_per_date_best_rank  2025      61  19.131148  0.868852  5.071451e+05       3.298826   8313.853609       331.359125          659.930132  -97591.734861            -10843.526096                   0
20             one_trade_per_date_best_rank  2026      33  21.000000  0.636364  1.262831e+05       1.479647   3826.759867      -130.384808          667.382994  -43456.123262             -3265.168672                   0
21                   thirty_day_anchor_only  2021       4  30.000000  1.000000  9.180456e+04            inf  22951.139899       765.037997          800.699050   15378.201665               512.606722                   0
22                   thirty_day_anchor_only  2022      66  30.000000  0.924242  1.528384e+06       9.125206  23157.329977       771.910999          967.586332 -103670.923339             -3455.697445                   1
23                   thirty_day_anchor_only  2023       1  30.000000  1.000000  2.343846e+04            inf  23438.457453       781.281915          781.281915   23438.457453               781.281915                   0
24                   thirty_day_anchor_only  2024      14  30.000000  1.000000  2.366811e+05            inf  16905.793407       563.526447          524.851181   14568.250800               485.608360                   0
25                   thirty_day_anchor_only  2025      37  30.000000  0.972973  5.220439e+05       6.638334  14109.295748       470.309858          472.031973  -92588.332880             -3086.277763                   0
26                   thirty_day_anchor_only  2026      27  30.000000  0.740741  2.067228e+05       1.912905   7656.398595       255.213286          721.008180  -57036.901356             -1901.230045                   0

Saved outputs:
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_trade_panel_20200102_20260701_20260704_211636.parquet
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_qualified_trade_panel_20200102_20260701_20260704_211636.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_summary_20260704_211636.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_by_year_20260704_211636.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_by_bucket_20260704_211636.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_by_tenor_20260704_211636.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_pass_diagnostics_by_bucket_20260704_211636.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_pass_diagnostics_by_tenor_20260704_211636.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_thresholds_used_20260704_211636.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_validation_20260704_211636.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\02_legacy_core_baseline_manifest_20260704_211636.json

CELL 4 PASSED

In [7]:
# ======================================================================================
# Cell 5 — Core threshold candidate grid design
# ======================================================================================
#
# Objective:
#   Define the Core threshold candidate grid for the next sweep.
#
# Important:
#   This cell only DESIGNS and SAVES the candidate grid.
#   It does not evaluate trades.
#   It does not run a threshold sweep.
#
# Locked constraints:
#   - Back Core thresholds remain fixed.
#   - No Secondary.
#   - No sizing changes.
#   - No production lock.
#
# New z-score constraint:
#   Within each bucket:
#
#       model_vrp_z_3m threshold == model_vrp_z_1y threshold
#
#   Therefore the grid uses one bucket-level z threshold:
#
#       Front z
#       Middle z
#       Back z
#
#   and applies that same value to both 3m and 1y z-score filters.
#
# Design direction from Cell 4:
#   - Front is the weak bucket, especially 9D.
#   - Middle and Back are already strong on P&L/day.
#   - Back remains the anchor.
#   - First sweep should mostly test whether Front needs tighter log / RSI / vol-floor
#     filters while leaving Middle close to current levels.
# ======================================================================================

from pathlib import Path
from datetime import datetime
import itertools
import json

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 180)
pd.set_option("display.width", 320)

# ======================================================================================
# 0. Fallback config if this cell is run independently
# ======================================================================================

if "PROJECT_ROOT" not in globals():
    PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

if "NEW_BRANCH" not in globals():
    NEW_BRANCH = "vrp_unified_fds_core_signal_threshold_research_v1"

if "OUT_PROCESSED_DIR" not in globals():
    OUT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / NEW_BRANCH
    OUT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

if "OUT_AUDIT_DIR" not in globals():
    OUT_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / NEW_BRANCH
    OUT_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

CELL5_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

if "LOCKED_MODEL_SPEC" not in globals():
    LOCKED_MODEL_SPEC = "unified_fds_no_min_return"

if "ALL_TENORS" not in globals():
    ALL_TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

if "BUCKET_ORDER_MAP" not in globals():
    BUCKET_ORDER_MAP = {"Front": 1, "Middle": 2, "Back": 3}

if "LOCKED_BACK_CORE_THRESHOLDS" not in globals():
    LOCKED_BACK_CORE_THRESHOLDS = {
        "model_vrp_log": 0.70,
        "model_vrp_z_3m": 0.70,
        "model_vrp_z_1y": 0.70,
        "RSI14_max": 70.0,
        "forecast_vol_pct_min": 8.5,
    }

# ======================================================================================
# 1. Candidate grid ranges
# ======================================================================================
#
# Notes:
#   - Back remains fixed.
#   - Front z and Middle z are single bucket-level z thresholds.
#   - That single z value is copied into both model_vrp_z_3m and model_vrp_z_1y.
#   - Because Back z is locked at 0.70 and z thresholds are directionally monotonic,
#     Front/Middle z candidates are constrained to <= 0.70.
#   - Front weakness should be addressed mainly by VRP log, RSI, and forecast-vol floor.
# ======================================================================================

GRID_RANGES = {
    "Front": {
        "model_vrp_log": [0.60, 0.65, 0.70],
        "model_vrp_z": [0.65, 0.70],
        "RSI14_max": [70.0, 68.0, 66.0],
        "forecast_vol_pct_min": [8.5, 10.0, 11.5],
    },
    "Middle": {
        "model_vrp_log": [0.65, 0.70],
        "model_vrp_z": [0.65, 0.70],
        "RSI14_max": [68.0, 66.0],
        "forecast_vol_pct_min": [8.5, 10.0],
    },
    "Back": {
        "model_vrp_log": [LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"]],
        "model_vrp_z": [LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"]],
        "RSI14_max": [LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"]],
        "forecast_vol_pct_min": [LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"]],
    },
}

# ======================================================================================
# 2. Constraint helpers
# ======================================================================================

def is_between(x, a, b):
    lo = min(a, b)
    hi = max(a, b)
    return (x >= lo) and (x <= hi)


def candidate_passes_design_constraints(row):
    """
    Enforce grid-design constraints only.

    This does NOT evaluate trade performance.
    """

    # Back fixed.
    back_fixed_ok = (
        row["Back_model_vrp_log"] == LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"]
        and row["Back_model_vrp_z"] == LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"]
        and row["Back_RSI14_max"] == LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"]
        and row["Back_forecast_vol_pct_min"] == LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"]
    )

    if not back_fixed_ok:
        return False

    # VRP log threshold:
    # Higher is stricter. Keep the standard Front <= Middle <= Back structure.
    log_ok = (
        row["Front_model_vrp_log"]
        <= row["Middle_model_vrp_log"]
        <= row["Back_model_vrp_log"]
    )

    # Z threshold:
    # One z threshold per bucket, applied equally to 3m and 1y.
    # Higher is stricter. Back is locked at 0.70, so Front/Middle cannot exceed Back.
    z_ok = (
        row["Front_model_vrp_z"]
        <= row["Middle_model_vrp_z"]
        <= row["Back_model_vrp_z"]
    )

    # Forecast-vol floor:
    # Higher is stricter. Since Back is locked at 8.5, Front may be tighter than Back.
    # Middle must sit between Front and Back.
    forecast_floor_ok = is_between(
        row["Middle_forecast_vol_pct_min"],
        row["Front_forecast_vol_pct_min"],
        row["Back_forecast_vol_pct_min"],
    )

    # RSI cap:
    # Lower is stricter. We allow Back's locked 70 as an anchor exception.
    # For Front/Middle, require Middle not looser than Front.
    # Example allowed: Front 70, Middle 68.
    rsi_ok = row["Front_RSI14_max"] >= row["Middle_RSI14_max"]

    return bool(log_ok and z_ok and forecast_floor_ok and rsi_ok)


def build_wide_candidate_grid():
    rows = []

    product_iter = itertools.product(
        GRID_RANGES["Front"]["model_vrp_log"],
        GRID_RANGES["Front"]["model_vrp_z"],
        GRID_RANGES["Front"]["RSI14_max"],
        GRID_RANGES["Front"]["forecast_vol_pct_min"],

        GRID_RANGES["Middle"]["model_vrp_log"],
        GRID_RANGES["Middle"]["model_vrp_z"],
        GRID_RANGES["Middle"]["RSI14_max"],
        GRID_RANGES["Middle"]["forecast_vol_pct_min"],

        GRID_RANGES["Back"]["model_vrp_log"],
        GRID_RANGES["Back"]["model_vrp_z"],
        GRID_RANGES["Back"]["RSI14_max"],
        GRID_RANGES["Back"]["forecast_vol_pct_min"],
    )

    for vals in product_iter:
        (
            front_log,
            front_z,
            front_rsi,
            front_fv_floor,

            middle_log,
            middle_z,
            middle_rsi,
            middle_fv_floor,

            back_log,
            back_z,
            back_rsi,
            back_fv_floor,
        ) = vals

        row = {
            "Front_model_vrp_log": float(front_log),
            "Front_model_vrp_z": float(front_z),
            "Front_RSI14_max": float(front_rsi),
            "Front_forecast_vol_pct_min": float(front_fv_floor),

            "Middle_model_vrp_log": float(middle_log),
            "Middle_model_vrp_z": float(middle_z),
            "Middle_RSI14_max": float(middle_rsi),
            "Middle_forecast_vol_pct_min": float(middle_fv_floor),

            "Back_model_vrp_log": float(back_log),
            "Back_model_vrp_z": float(back_z),
            "Back_RSI14_max": float(back_rsi),
            "Back_forecast_vol_pct_min": float(back_fv_floor),
        }

        row["passes_design_constraints"] = candidate_passes_design_constraints(row)

        if row["passes_design_constraints"]:
            rows.append(row)

    grid = pd.DataFrame(rows).reset_index(drop=True)

    if grid.empty:
        raise RuntimeError("Candidate grid is empty after applying design constraints.")

    grid.insert(0, "candidate_id", [f"core_grid_{i:05d}" for i in range(1, len(grid) + 1)])
    grid.insert(1, "candidate_family", "core_front_middle_back_locked")
    grid.insert(2, "locked_model_spec", LOCKED_MODEL_SPEC)

    # Expand the single bucket z threshold into explicit 3m and 1y threshold columns.
    for bucket in ["Front", "Middle", "Back"]:
        grid[f"{bucket}_model_vrp_z_3m"] = grid[f"{bucket}_model_vrp_z"]
        grid[f"{bucket}_model_vrp_z_1y"] = grid[f"{bucket}_model_vrp_z"]

    # Convenience diagnostics.
    grid["front_middle_log_gap"] = grid["Middle_model_vrp_log"] - grid["Front_model_vrp_log"]
    grid["middle_back_log_gap"] = grid["Back_model_vrp_log"] - grid["Middle_model_vrp_log"]

    grid["front_middle_z_gap"] = grid["Middle_model_vrp_z"] - grid["Front_model_vrp_z"]
    grid["middle_back_z_gap"] = grid["Back_model_vrp_z"] - grid["Middle_model_vrp_z"]

    grid["front_middle_RSI_gap"] = grid["Front_RSI14_max"] - grid["Middle_RSI14_max"]

    grid["front_middle_forecast_floor_gap"] = (
        grid["Front_forecast_vol_pct_min"] - grid["Middle_forecast_vol_pct_min"]
    )
    grid["middle_back_forecast_floor_gap"] = (
        grid["Middle_forecast_vol_pct_min"] - grid["Back_forecast_vol_pct_min"]
    )

    return grid


def build_long_candidate_grid(grid_wide):
    rows = []

    for _, row in grid_wide.iterrows():
        for bucket in ["Front", "Middle", "Back"]:
            rows.append({
                "candidate_id": row["candidate_id"],
                "candidate_family": row["candidate_family"],
                "locked_model_spec": row["locked_model_spec"],
                "tenor_bucket": bucket,
                "tenor_bucket_order": BUCKET_ORDER_MAP[bucket],
                "model_vrp_log": row[f"{bucket}_model_vrp_log"],
                "model_vrp_z": row[f"{bucket}_model_vrp_z"],
                "model_vrp_z_3m": row[f"{bucket}_model_vrp_z_3m"],
                "model_vrp_z_1y": row[f"{bucket}_model_vrp_z_1y"],
                "RSI14_max": row[f"{bucket}_RSI14_max"],
                "forecast_vol_pct_min": row[f"{bucket}_forecast_vol_pct_min"],
                "is_back_locked": bucket == "Back",
            })

    long_grid = pd.DataFrame(rows).sort_values(
        ["candidate_id", "tenor_bucket_order"]
    ).reset_index(drop=True)

    return long_grid


# ======================================================================================
# 3. Build candidate grid
# ======================================================================================

grid_wide = build_wide_candidate_grid()
grid_long = build_long_candidate_grid(grid_wide)

# ======================================================================================
# 4. Save outputs
# ======================================================================================

grid_wide_csv_path = OUT_AUDIT_DIR / f"03_core_threshold_candidate_grid_wide_{CELL5_TIMESTAMP}.csv"
grid_wide_parquet_path = OUT_PROCESSED_DIR / f"03_core_threshold_candidate_grid_wide_{CELL5_TIMESTAMP}.parquet"

grid_long_csv_path = OUT_AUDIT_DIR / f"03_core_threshold_candidate_grid_long_{CELL5_TIMESTAMP}.csv"
grid_long_parquet_path = OUT_PROCESSED_DIR / f"03_core_threshold_candidate_grid_long_{CELL5_TIMESTAMP}.parquet"

grid_ranges_path = OUT_AUDIT_DIR / f"03_core_threshold_candidate_grid_ranges_{CELL5_TIMESTAMP}.json"
validation_path = OUT_AUDIT_DIR / f"03_core_threshold_candidate_grid_validation_{CELL5_TIMESTAMP}.csv"
manifest_path = OUT_AUDIT_DIR / f"03_core_threshold_candidate_grid_manifest_{CELL5_TIMESTAMP}.json"

grid_wide.to_csv(grid_wide_csv_path, index=False)
grid_wide.to_parquet(grid_wide_parquet_path, index=False)

grid_long.to_csv(grid_long_csv_path, index=False)
grid_long.to_parquet(grid_long_parquet_path, index=False)

with open(grid_ranges_path, "w", encoding="utf-8") as f:
    json.dump(GRID_RANGES, f, indent=2)

# ======================================================================================
# 5. Validation
# ======================================================================================

validation_rows = []

def add_validation(check, status, detail):
    validation_rows.append({
        "check": check,
        "status": status,
        "detail": detail,
    })

# Candidate count.
add_validation(
    "candidate_grid_non_empty",
    "PASS" if len(grid_wide) > 0 else "FAIL",
    f"candidate_count={len(grid_wide):,}",
)

# Back fixed.
back_fixed_bad = grid_wide[
    (grid_wide["Back_model_vrp_log"] != LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"])
    | (grid_wide["Back_model_vrp_z"] != LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"])
    | (grid_wide["Back_RSI14_max"] != LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"])
    | (grid_wide["Back_forecast_vol_pct_min"] != LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"])
]

add_validation(
    "back_thresholds_locked",
    "PASS" if back_fixed_bad.empty else "FAIL",
    f"bad_rows={len(back_fixed_bad):,}; locked_back={LOCKED_BACK_CORE_THRESHOLDS}",
)

# Z equality within bucket.
z_equality_bad_rows = []

for bucket in ["Front", "Middle", "Back"]:
    bad = grid_wide[
        grid_wide[f"{bucket}_model_vrp_z_3m"] != grid_wide[f"{bucket}_model_vrp_z_1y"]
    ]
    if not bad.empty:
        z_equality_bad_rows.append((bucket, len(bad)))

add_validation(
    "z_3m_equals_z_1y_within_each_bucket",
    "PASS" if not z_equality_bad_rows else "FAIL",
    f"bad_bucket_counts={z_equality_bad_rows}",
)

# Log monotonicity.
log_bad = grid_wide[
    ~(
        (grid_wide["Front_model_vrp_log"] <= grid_wide["Middle_model_vrp_log"])
        & (grid_wide["Middle_model_vrp_log"] <= grid_wide["Back_model_vrp_log"])
    )
]

add_validation(
    "vrp_log_front_middle_back_monotonic",
    "PASS" if log_bad.empty else "FAIL",
    f"bad_rows={len(log_bad):,}; rule=Front <= Middle <= Back",
)

# Z monotonicity.
z_bad = grid_wide[
    ~(
        (grid_wide["Front_model_vrp_z"] <= grid_wide["Middle_model_vrp_z"])
        & (grid_wide["Middle_model_vrp_z"] <= grid_wide["Back_model_vrp_z"])
    )
]

add_validation(
    "z_threshold_front_middle_back_monotonic",
    "PASS" if z_bad.empty else "FAIL",
    f"bad_rows={len(z_bad):,}; rule=Front <= Middle <= Back",
)

# Forecast floor middle-between-front-and-back.
forecast_floor_bad = grid_wide[
    ~grid_wide.apply(
        lambda r: is_between(
            r["Middle_forecast_vol_pct_min"],
            r["Front_forecast_vol_pct_min"],
            r["Back_forecast_vol_pct_min"],
        ),
        axis=1,
    )
]

add_validation(
    "forecast_vol_floor_middle_between_front_and_back",
    "PASS" if forecast_floor_bad.empty else "FAIL",
    f"bad_rows={len(forecast_floor_bad):,}; Back fixed at 8.5, Front may be tighter",
)

# RSI Front/Middle only, Back exception.
rsi_bad = grid_wide[
    ~(grid_wide["Front_RSI14_max"] >= grid_wide["Middle_RSI14_max"])
]

add_validation(
    "rsi_front_middle_constraint",
    "PASS" if rsi_bad.empty else "FAIL",
    f"bad_rows={len(rsi_bad):,}; rule=Front RSI cap >= Middle RSI cap; Back locked exception",
)

# Long grid row count should be 3 per candidate.
long_count_ok = len(grid_long) == 3 * len(grid_wide)

add_validation(
    "long_grid_has_three_rows_per_candidate",
    "PASS" if long_count_ok else "FAIL",
    f"long_rows={len(grid_long):,}; expected={3 * len(grid_wide):,}",
)

# Explicit no-evaluation checks.
trade_metric_cols = [
    "trades",
    "win_rate",
    "total_pnl",
    "avg_pnl",
    "avg_pnl_per_day",
    "profit_factor",
    "worst_trade",
]

unexpected_trade_cols = [c for c in trade_metric_cols if c in grid_wide.columns]

add_validation(
    "no_trade_evaluation_performed",
    "PASS" if not unexpected_trade_cols else "FAIL",
    f"unexpected_trade_metric_cols={unexpected_trade_cols}",
)

add_validation(
    "no_secondary",
    "PASS",
    "Candidate grid is Core only.",
)

add_validation(
    "no_sizing_changes",
    "PASS",
    "Candidate grid contains thresholds only, no sizing fields.",
)

validation = pd.DataFrame(validation_rows)
validation.to_csv(validation_path, index=False)

failures = validation[validation["status"] == "FAIL"]

manifest = {
    "notebook": "07_unified_fds_core_signal_threshold_research_v1.ipynb",
    "cell": "Cell 5 — Core threshold candidate grid design",
    "timestamp": CELL5_TIMESTAMP,
    "locked_model_spec": LOCKED_MODEL_SPEC,
    "candidate_count": int(len(grid_wide)),
    "long_grid_rows": int(len(grid_long)),
    "grid_wide_csv_path": str(grid_wide_csv_path),
    "grid_wide_parquet_path": str(grid_wide_parquet_path),
    "grid_long_csv_path": str(grid_long_csv_path),
    "grid_long_parquet_path": str(grid_long_parquet_path),
    "grid_ranges_path": str(grid_ranges_path),
    "validation_path": str(validation_path),
    "grid_ranges": GRID_RANGES,
    "locked_back_core_thresholds": LOCKED_BACK_CORE_THRESHOLDS,
    "hard_constraints": [
        "Back Core thresholds fixed.",
        "Within each bucket, model_vrp_z_3m threshold equals model_vrp_z_1y threshold.",
        "VRP log threshold: Front <= Middle <= Back.",
        "Z threshold: Front <= Middle <= Back.",
        "Forecast-vol floor: Middle must sit between Front and Back; Back fixed at 8.5; Front may be tighter.",
        "RSI cap: Front >= Middle; Back RSI fixed exception.",
        "No trade evaluation performed.",
        "No threshold sweep performed.",
        "No Secondary.",
        "No sizing changes.",
    ],
    "notes": [
        "This cell defines threshold candidates only.",
        "Cell 6 should evaluate this candidate grid against the clean signal base panel.",
        "P&L/day remains the primary cross-tenor quality metric for Cell 6.",
    ],
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2)

if not failures.empty:
    display(validation)
    raise RuntimeError("Cell 5 validation failed. Review validation output above.")

# ======================================================================================
# 6. Display concise review
# ======================================================================================

print("=" * 100)
print("Cell 5 — Core threshold candidate grid design")
print("=" * 100)
print(f"Locked model spec:              {LOCKED_MODEL_SPEC}")
print(f"Candidate count:                {len(grid_wide):,}")
print(f"Long grid rows:                 {len(grid_long):,}")
print(f"Back thresholds locked:         True")
print(f"Z 3m == Z 1y within bucket:     True")
print(f"No trade evaluation:            True")
print(f"No threshold sweep:             True")
print(f"No Secondary:                   True")
print(f"No sizing changes:              True")
print()
print("Saved outputs:")
for p in [
    grid_wide_csv_path,
    grid_wide_parquet_path,
    grid_long_csv_path,
    grid_long_parquet_path,
    grid_ranges_path,
    validation_path,
    manifest_path,
]:
    print(f"  {p}")

print()
print("Validation:")
display(validation)

print()
print("Grid ranges:")
display(
    pd.DataFrame(
        [
            {
                "bucket": bucket,
                "model_vrp_log": GRID_RANGES[bucket]["model_vrp_log"],
                "model_vrp_z_applied_to_3m_and_1y": GRID_RANGES[bucket]["model_vrp_z"],
                "RSI14_max": GRID_RANGES[bucket]["RSI14_max"],
                "forecast_vol_pct_min": GRID_RANGES[bucket]["forecast_vol_pct_min"],
            }
            for bucket in ["Front", "Middle", "Back"]
        ]
    )
)

print()
print("Candidate grid sample:")
display(grid_wide.head(20))

print()
print("Long-format sample:")
display(grid_long.head(30))

print("\nCELL 5 PASSED")

====================================================================================================
Cell 5 — Core threshold candidate grid design
====================================================================================================
Locked model spec:              unified_fds_no_min_return
Candidate count:                375
Long grid rows:                 1,125
Back thresholds locked:         True
Z 3m == Z 1y within bucket:     True
No trade evaluation:            True
No threshold sweep:             True
No Secondary:                   True
No sizing changes:              True

Saved outputs:
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\03_core_threshold_candidate_grid_wide_20260704_213318.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\03_core_threshold_candidate_grid_wide_20260704_213318.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\03_core_threshold_candidate_grid_long_20260704_213318.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\03_core_threshold_candidate_grid_long_20260704_213318.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\03_core_threshold_candidate_grid_ranges_20260704_213318.json
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\03_core_threshold_candidate_grid_validation_20260704_213318.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\03_core_threshold_candidate_grid_manifest_20260704_213318.json

Validation:

                                               check status                                             detail
0                           candidate_grid_non_empty   PASS                                candidate_count=375
1                             back_thresholds_locked   PASS  bad_rows=0; locked_back={'model_vrp_log': 0.7,...
2                z_3m_equals_z_1y_within_each_bucket   PASS                               bad_bucket_counts=[]
3                vrp_log_front_middle_back_monotonic   PASS           bad_rows=0; rule=Front <= Middle <= Back
4            z_threshold_front_middle_back_monotonic   PASS           bad_rows=0; rule=Front <= Middle <= Back
5   forecast_vol_floor_middle_between_front_and_back   PASS  bad_rows=0; Back fixed at 8.5, Front may be ti...
6                        rsi_front_middle_constraint   PASS  bad_rows=0; rule=Front RSI cap >= Middle RSI c...
7             long_grid_has_three_rows_per_candidate   PASS                    long_rows=1,125; expected=1,125
8                      no_trade_evaluation_performed   PASS                    unexpected_trade_metric_cols=[]
9                                       no_secondary   PASS                       Candidate grid is Core only.
10                                 no_sizing_changes   PASS  Candidate grid contains thresholds only, no si...

Grid ranges:

   bucket     model_vrp_log model_vrp_z_applied_to_3m_and_1y           RSI14_max forecast_vol_pct_min
0   Front  [0.6, 0.65, 0.7]                      [0.65, 0.7]  [70.0, 68.0, 66.0]    [8.5, 10.0, 11.5]
1  Middle       [0.65, 0.7]                      [0.65, 0.7]        [68.0, 66.0]          [8.5, 10.0]
2    Back             [0.7]                            [0.7]              [70.0]                [8.5]

Candidate grid sample:

,candidate_id,candidate_family,locked_model_spec,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Back_RSI14_max,Back_forecast_vol_pct_min,passes_design_constraints,Front_model_vrp_z_3m,Front_model_vrp_z_1y,Middle_model_vrp_z_3m,Middle_model_vrp_z_1y,Back_model_vrp_z_3m,Back_model_vrp_z_1y,front_middle_log_gap,middle_back_log_gap,front_middle_z_gap,middle_back_z_gap,front_middle_RSI_gap,front_middle_forecast_floor_gap,middle_back_forecast_floor_gap
0,core_grid_00001,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,8.5,0.65,0.65,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.05,0.05,0.00,0.05,2.0,0.0,0.0
1,core_grid_00002,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,8.5,0.65,0.65,66.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.05,0.05,0.00,0.05,4.0,0.0,0.0
2,core_grid_00003,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,8.5,0.65,0.70,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.70,0.70,0.7,0.7,0.05,0.05,0.05,0.00,2.0,0.0,0.0
3,core_grid_00004,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,8.5,0.65,0.70,66.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.70,0.70,0.7,0.7,0.05,0.05,0.05,0.00,4.0,0.0,0.0
4,core_grid_00005,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,8.5,0.70,0.65,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.10,0.00,0.00,0.05,2.0,0.0,0.0
5,core_grid_00006,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,8.5,0.70,0.65,66.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.10,0.00,0.00,0.05,4.0,0.0,0.0
6,core_grid_00007,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,8.5,0.70,0.70,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.70,0.70,0.7,0.7,0.10,0.00,0.05,0.00,2.0,0.0,0.0
7,core_grid_00008,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,8.5,0.70,0.70,66.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.70,0.70,0.7,0.7,0.10,0.00,0.05,0.00,4.0,0.0,0.0
8,core_grid_00009,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.65,0.65,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.05,0.05,0.00,0.05,2.0,1.5,0.0
9,core_grid_00010,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.65,0.65,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.05,0.05,0.00,0.05,2.0,0.0,1.5
10,core_grid_00011,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.65,0.65,66.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.05,0.05,0.00,0.05,4.0,1.5,0.0
11,core_grid_00012,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.65,0.65,66.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.05,0.05,0.00,0.05,4.0,0.0,1.5
12,core_grid_00013,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.65,0.70,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.70,0.70,0.7,0.7,0.05,0.05,0.05,0.00,2.0,1.5,0.0
13,core_grid_00014,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.65,0.70,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.70,0.70,0.7,0.7,0.05,0.05,0.05,0.00,2.0,0.0,1.5
14,core_grid_00015,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.65,0.70,66.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.70,0.70,0.7,0.7,0.05,0.05,0.05,0.00,4.0,1.5,0.0
15,core_grid_00016,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.65,0.70,66.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.70,0.70,0.7,0.7,0.05,0.05,0.05,0.00,4.0,0.0,1.5
16,core_grid_00017,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.70,0.65,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.10,0.00,0.00,0.05,2.0,1.5,0.0
17,core_grid_00018,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.70,0.65,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.10,0.00,0.00,0.05,2.0,0.0,1.5
18,core_grid_00019,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.70,0.65,66.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.10,0.00,0.00,0.05,4.0,1.5,0.0
19,core_grid_00020,core_front_middle_back_locked,unified_fds_no_min_return,0.6,0.65,70.0,10.0,0.70,0.65,66.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.65,0.65,0.7,0.7,0.10,0.00,0.00,0.05,4.0,0.0,1.5

Long-format sample:

       candidate_id               candidate_family          locked_model_spec tenor_bucket  tenor_bucket_order  model_vrp_log  model_vrp_z  model_vrp_z_3m  model_vrp_z_1y  RSI14_max  forecast_vol_pct_min  is_back_locked
0   core_grid_00001  core_front_middle_back_locked  unified_fds_no_min_return        Front                   1           0.60         0.65            0.65            0.65       70.0                   8.5           False
1   core_grid_00001  core_front_middle_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.65            0.65            0.65       68.0                   8.5           False
2   core_grid_00001  core_front_middle_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
3   core_grid_00002  core_front_middle_back_locked  unified_fds_no_min_return        Front                   1           0.60         0.65            0.65            0.65       70.0                   8.5           False
4   core_grid_00002  core_front_middle_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.65            0.65            0.65       66.0                   8.5           False
5   core_grid_00002  core_front_middle_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
6   core_grid_00003  core_front_middle_back_locked  unified_fds_no_min_return        Front                   1           0.60         0.65            0.65            0.65       70.0                   8.5           False
7   core_grid_00003  core_front_middle_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.70            0.70            0.70       68.0                   8.5           False
8   core_grid_00003  core_front_middle_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
9   core_grid_00004  core_front_middle_back_locked  unified_fds_no_min_return        Front                   1           0.60         0.65            0.65            0.65       70.0                   8.5           False
10  core_grid_00004  core_front_middle_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.70            0.70            0.70       66.0                   8.5           False
11  core_grid_00004  core_front_middle_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
12  core_grid_00005  core_front_middle_back_locked  unified_fds_no_min_return        Front                   1           0.60         0.65            0.65            0.65       70.0                   8.5           False
13  core_grid_00005  core_front_middle_back_locked  unified_fds_no_min_return       Middle                   2           0.70         0.65            0.65            0.65       68.0                   8.5           False
14  core_grid_00005  core_front_middle_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
15  core_grid_00006  core_front_middle_back_locked  unified_fds_no_min_return        Front                   1           0.60         0.65            0.65            0.65       70.0                   8.5           False
16  core_grid_00006  core_front_middle_back_locked  unified_fds_no_min_return       Middle                   2           0.70         0.65            0.65            0.65       66.0                   8.5           False
17  core_grid_00006  core_front_middle_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
18  core_grid_00007  core_front_middle_back_locked  unified_fds_no_min_return        Front                   1           0.60         0.65            0.65            0.65       70.0                   8.5           False
19  core_grid_00007  core_front_middle_back_locked  unified_fds_no_min_return       Middle                   2           0.70         0.70            0.70            0.70       68.0                   8.5           False
20  core_grid_00007  core_front_middle_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
21  core_grid_00008  core_front_middle_back_locked  unified_fds_no_min_return        Front                   1           0.60         0.65            0.65            0.65       70.0                   8.5           False
22  core_grid_00008  core_front_middle_back_locked  unified_fds_no_min_return       Middle                   2           0.70         0.70            0.70            0.70       66.0                   8.5           False
23  core_grid_00008  core_front_middle_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
24  core_grid_00009  core_front_middle_back_locked  unified_fds_no_min_return        Front                   1           0.60         0.65            0.65            0.65       70.0                  10.0           False
25  core_grid_00009  core_front_middle_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.65            0.65            0.65       68.0                   8.5           False
26  core_grid_00009  core_front_middle_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
27  core_grid_00010  core_front_middle_back_locked  unified_fds_no_min_return        Front                   1           0.60         0.65            0.65            0.65       70.0                  10.0           False
28  core_grid_00010  core_front_middle_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.65            0.65            0.65       68.0                  10.0           False
29  core_grid_00010  core_front_middle_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True

CELL 5 PASSED

In [8]:
# ======================================================================================
# Cell 6 — Core threshold candidate sweep using P&L/day
# ======================================================================================
#
# Objective:
#   Evaluate the Cell 5 Core threshold candidate grid against the clean locked signal panel.
#
# Inputs:
#   01_unified_fds_signal_base_panel_*.parquet
#   03_core_threshold_candidate_grid_wide_*.parquet
#   03_core_threshold_candidate_grid_long_*.parquet
#
# Outputs:
#   04_core_threshold_sweep_candidate_summary_*.csv
#   04_core_threshold_sweep_by_bucket_*.csv
#   04_core_threshold_sweep_by_tenor_*.csv
#   04_core_threshold_sweep_by_year_*.csv
#   04_core_threshold_sweep_candidate_pass_diagnostics_*.csv
#   04_core_threshold_sweep_selected_trade_panel_*.parquet
#   04_core_threshold_sweep_validation_*.csv
#   04_core_threshold_sweep_manifest_*.json
#
# Selection universes evaluated:
#   1. all_qualified_trades
#   2. one_trade_per_bucket_per_date_best_rank
#   3. one_trade_per_date_best_rank
#   4. thirty_day_anchor_only
#
# Primary cross-tenor quality metric:
#   avg_pnl_per_day
#
# Important:
#   This is the first-pass sweep only.
#   It does not choose a final threshold set.
#   If best candidates cluster at grid boundaries, we will expand the grid later.
#
# Not in scope:
#   - No final candidate selection.
#   - No Secondary.
#   - No sizing changes.
#   - No production lock.
# ======================================================================================

from pathlib import Path
from datetime import datetime
import json
import time
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore", category=RuntimeWarning)

pd.set_option("display.max_columns", 220)
pd.set_option("display.width", 360)

# ======================================================================================
# 0. Fallback config if this cell is run independently
# ======================================================================================

if "PROJECT_ROOT" not in globals():
    PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

if "NEW_BRANCH" not in globals():
    NEW_BRANCH = "vrp_unified_fds_core_signal_threshold_research_v1"

if "OUT_PROCESSED_DIR" not in globals():
    OUT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / NEW_BRANCH
    OUT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

if "OUT_AUDIT_DIR" not in globals():
    OUT_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / NEW_BRANCH
    OUT_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

CELL6_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

if "LOCKED_MODEL_SPEC" not in globals():
    LOCKED_MODEL_SPEC = "unified_fds_no_min_return"

if "ALL_TENORS" not in globals():
    ALL_TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

if "BUCKET_ORDER_MAP" not in globals():
    BUCKET_ORDER_MAP = {"Front": 1, "Middle": 2, "Back": 3}

if "BUCKET_CENTER_TENOR" not in globals():
    BUCKET_CENTER_TENOR = {
        "Front": 12,
        "Middle": 21,
        "Back": 30,
    }

if "LOCKED_BACK_CORE_THRESHOLDS" not in globals():
    LOCKED_BACK_CORE_THRESHOLDS = {
        "model_vrp_log": 0.70,
        "model_vrp_z_3m": 0.70,
        "model_vrp_z_1y": 0.70,
        "RSI14_max": 70.0,
        "forecast_vol_pct_min": 8.5,
    }

SELECTION_UNIVERSES = [
    "all_qualified_trades",
    "one_trade_per_bucket_per_date_best_rank",
    "one_trade_per_date_best_rank",
    "thirty_day_anchor_only",
]

PRIMARY_RANKING_METRIC = "avg_pnl_per_day"

# ======================================================================================
# 1. Helpers
# ======================================================================================

def latest_file(directory: Path, pattern: str, required: bool = True) -> Path | None:
    matches = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if matches:
        return matches[0]
    if required:
        raise FileNotFoundError(f"No file found in {directory} matching {pattern}")
    return None


def profit_factor_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").dropna()
    gross_profit = float(pnl[pnl > 0].sum())
    gross_loss = float(pnl[pnl < 0].sum())

    if gross_loss < 0:
        return gross_profit / abs(gross_loss)
    if gross_profit > 0:
        return np.inf
    return np.nan


def max_drawdown_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)

    if len(pnl) == 0:
        return np.nan

    cumulative = pnl.cumsum()
    running_max = cumulative.cummax()
    drawdown = cumulative - running_max

    return float(drawdown.min())


def worst_rolling_sum(pnl: pd.Series, window: int) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)

    if len(pnl) == 0:
        return np.nan

    if len(pnl) < window:
        return float(pnl.sum())

    return float(pnl.rolling(window=window, min_periods=window).sum().min())


def add_selection_ranks(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add diagnostic best-rank fields for selected-tenor views.

    This is still not a final production DTE selector.
    It is a diagnostic selector to make threshold comparisons less noisy.
    """
    d = df.copy()

    if d.empty:
        return d

    d["bucket_center_tenor"] = d["tenor_bucket"].map(BUCKET_CENTER_TENOR)
    d["distance_to_bucket_center"] = (d["tenor"] - d["bucket_center_tenor"]).abs()

    # Within bucket/date.
    rank_group = ["trade_date", "tenor_bucket"]

    d["rank_z_1y_in_bucket_date"] = (
        d.groupby(rank_group)["model_vrp_z_1y"]
        .rank(method="min", ascending=False)
    )
    d["rank_z_3m_in_bucket_date"] = (
        d.groupby(rank_group)["model_vrp_z_3m"]
        .rank(method="min", ascending=False)
    )
    d["rank_vrp_log_in_bucket_date"] = (
        d.groupby(rank_group)["model_vrp_log"]
        .rank(method="min", ascending=False)
    )

    d["avg_signal_rank_in_bucket_date"] = d[
        [
            "rank_z_1y_in_bucket_date",
            "rank_z_3m_in_bucket_date",
            "rank_vrp_log_in_bucket_date",
        ]
    ].mean(axis=1)

    # Across full date.
    d["rank_z_1y_in_date"] = (
        d.groupby("trade_date")["model_vrp_z_1y"]
        .rank(method="min", ascending=False)
    )
    d["rank_z_3m_in_date"] = (
        d.groupby("trade_date")["model_vrp_z_3m"]
        .rank(method="min", ascending=False)
    )
    d["rank_vrp_log_in_date"] = (
        d.groupby("trade_date")["model_vrp_log"]
        .rank(method="min", ascending=False)
    )

    d["avg_signal_rank_in_date"] = d[
        [
            "rank_z_1y_in_date",
            "rank_z_3m_in_date",
            "rank_vrp_log_in_date",
        ]
    ].mean(axis=1)

    return d


def select_trade_universes(qualified: pd.DataFrame) -> dict[str, pd.DataFrame]:
    """
    Given qualified trades for one candidate, return all selection universes.
    """
    if qualified.empty:
        return {
            "all_qualified_trades": qualified.copy(),
            "one_trade_per_bucket_per_date_best_rank": qualified.copy(),
            "one_trade_per_date_best_rank": qualified.copy(),
            "thirty_day_anchor_only": qualified.copy(),
        }

    q = add_selection_ranks(qualified)

    one_trade_per_bucket_date = (
        q.sort_values(
            [
                "trade_date",
                "tenor_bucket_order",
                "avg_signal_rank_in_bucket_date",
                "distance_to_bucket_center",
                "rank_z_1y_in_bucket_date",
                "rank_z_3m_in_bucket_date",
                "rank_vrp_log_in_bucket_date",
                "tenor",
            ],
            ascending=[True, True, True, True, True, True, True, True],
        )
        .groupby(["trade_date", "tenor_bucket"], as_index=False)
        .head(1)
        .copy()
    )

    one_trade_per_date = (
        q.sort_values(
            [
                "trade_date",
                "avg_signal_rank_in_date",
                "rank_z_1y_in_date",
                "rank_z_3m_in_date",
                "rank_vrp_log_in_date",
                "distance_to_bucket_center",
                "tenor_bucket_order",
                "tenor",
            ],
            ascending=[True, True, True, True, True, True, True, True],
        )
        .groupby(["trade_date"], as_index=False)
        .head(1)
        .copy()
    )

    thirty_day_anchor = q[q["tenor"] == 30].copy()

    return {
        "all_qualified_trades": q.copy(),
        "one_trade_per_bucket_per_date_best_rank": one_trade_per_bucket_date,
        "one_trade_per_date_best_rank": one_trade_per_date,
        "thirty_day_anchor_only": thirty_day_anchor,
    }


def summarize_trade_set(
    df: pd.DataFrame,
    candidate_id: str,
    selection_universe: str,
    group_cols: list[str] | None = None,
    include_empty_overall: bool = False,
) -> pd.DataFrame:
    """
    Summarize one selected trade set.

    For overall candidate-level summaries, use group_cols=[] and include_empty_overall=True.
    """
    if group_cols is None:
        group_cols = []

    rows = []

    d = df.copy()

    if not d.empty:
        d["normalized_pnl_dollars"] = pd.to_numeric(d["normalized_pnl_dollars"], errors="coerce")
        d["normalized_pnl_per_day"] = pd.to_numeric(d["normalized_pnl_per_day"], errors="coerce")
        d["win"] = pd.to_numeric(d["win"], errors="coerce")
        d = d[
            d["normalized_pnl_dollars"].notna()
            & d["normalized_pnl_per_day"].notna()
        ].copy()
        d = d.sort_values(["trade_date", "tenor"]).copy()

    if d.empty:
        if include_empty_overall and len(group_cols) == 0:
            return pd.DataFrame([{
                "candidate_id": candidate_id,
                "selection_universe": selection_universe,
                "trades": 0,
                "unique_trade_dates": 0,
                "date_min": pd.NaT,
                "date_max": pd.NaT,
                "avg_tenor": np.nan,
                "win_rate": np.nan,
                "total_pnl": 0.0,
                "avg_pnl": np.nan,
                "median_pnl": np.nan,
                "worst_trade": np.nan,
                "best_trade": np.nan,
                "profit_factor": np.nan,
                "selected_trade_drawdown": np.nan,
                "worst_5_trade_sum": np.nan,
                "worst_10_trade_sum": np.nan,
                "worst_20_trade_sum": np.nan,
                "trades_le_neg_50k": 0,
                "trades_le_neg_100k": 0,
                "trades_le_neg_150k": 0,
                "total_pnl_per_day_sum": 0.0,
                "avg_pnl_per_day": np.nan,
                "median_pnl_per_day": np.nan,
                "worst_trade_pnl_per_day": np.nan,
                "best_trade_pnl_per_day": np.nan,
                "profit_factor_pnl_per_day": np.nan,
                "pnl_per_day_drawdown": np.nan,
                "worst_5_trade_pnl_per_day_sum": np.nan,
                "worst_10_trade_pnl_per_day_sum": np.nan,
                "worst_20_trade_pnl_per_day_sum": np.nan,
                "trades_2025": 0,
                "pnl_2025": 0.0,
                "avg_pnl_per_day_2025": np.nan,
                "worst_trade_2025": np.nan,
                "trades_2026": 0,
                "pnl_2026": 0.0,
                "avg_pnl_per_day_2026": np.nan,
                "worst_trade_2026": np.nan,
            }])
        return pd.DataFrame()

    if len(group_cols) == 0:
        grouped = [((), d)]
    else:
        grouped = d.groupby(group_cols, dropna=False)

    for keys, g in grouped:
        if len(group_cols) == 0:
            keys = ()
        elif not isinstance(keys, tuple):
            keys = (keys,)

        row = {
            "candidate_id": candidate_id,
            "selection_universe": selection_universe,
        }

        for col, key in zip(group_cols, keys):
            row[col] = key

        pnl = g["normalized_pnl_dollars"]
        pnl_day = g["normalized_pnl_per_day"]
        wins = g["win"]

        y2025 = g[g["trade_date"].dt.year == 2025].copy()
        y2026 = g[g["trade_date"].dt.year == 2026].copy()

        row.update({
            "trades": int(len(g)),
            "unique_trade_dates": int(g["trade_date"].nunique()),
            "date_min": g["trade_date"].min(),
            "date_max": g["trade_date"].max(),
            "tenor_min": int(g["tenor"].min()) if g["tenor"].notna().any() else np.nan,
            "tenor_max": int(g["tenor"].max()) if g["tenor"].notna().any() else np.nan,
            "avg_tenor": float(g["tenor"].mean()) if g["tenor"].notna().any() else np.nan,

            # Total-dollar P&L.
            "win_rate": float(wins.mean()) if wins.notna().sum() else np.nan,
            "total_pnl": float(pnl.sum()),
            "avg_pnl": float(pnl.mean()),
            "median_pnl": float(pnl.median()),
            "worst_trade": float(pnl.min()),
            "best_trade": float(pnl.max()),
            "profit_factor": profit_factor_from_pnl(pnl),
            "selected_trade_drawdown": max_drawdown_from_pnl(pnl),
            "worst_5_trade_sum": worst_rolling_sum(pnl, 5),
            "worst_10_trade_sum": worst_rolling_sum(pnl, 10),
            "worst_20_trade_sum": worst_rolling_sum(pnl, 20),
            "trades_le_neg_50k": int((pnl <= -50_000).sum()),
            "trades_le_neg_100k": int((pnl <= -100_000).sum()),
            "trades_le_neg_150k": int((pnl <= -150_000).sum()),

            # P&L/day — primary cross-tenor quality.
            "total_pnl_per_day_sum": float(pnl_day.sum()),
            "avg_pnl_per_day": float(pnl_day.mean()),
            "median_pnl_per_day": float(pnl_day.median()),
            "worst_trade_pnl_per_day": float(pnl_day.min()),
            "best_trade_pnl_per_day": float(pnl_day.max()),
            "profit_factor_pnl_per_day": profit_factor_from_pnl(pnl_day),
            "pnl_per_day_drawdown": max_drawdown_from_pnl(pnl_day),
            "worst_5_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 5),
            "worst_10_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 10),
            "worst_20_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 20),

            # Recent year diagnostics.
            "trades_2025": int(len(y2025)),
            "pnl_2025": float(y2025["normalized_pnl_dollars"].sum()) if len(y2025) else 0.0,
            "avg_pnl_per_day_2025": float(y2025["normalized_pnl_per_day"].mean()) if len(y2025) else np.nan,
            "worst_trade_2025": float(y2025["normalized_pnl_dollars"].min()) if len(y2025) else np.nan,

            "trades_2026": int(len(y2026)),
            "pnl_2026": float(y2026["normalized_pnl_dollars"].sum()) if len(y2026) else 0.0,
            "avg_pnl_per_day_2026": float(y2026["normalized_pnl_per_day"].mean()) if len(y2026) else np.nan,
            "worst_trade_2026": float(y2026["normalized_pnl_dollars"].min()) if len(y2026) else np.nan,
        })

        rows.append(row)

    return pd.DataFrame(rows)


def apply_candidate_thresholds(signal_df: pd.DataFrame, candidate: pd.Series) -> tuple[pd.DataFrame, dict]:
    """
    Apply one candidate's bucket thresholds to the signal panel.
    """
    d = signal_df.copy()

    required_inputs = (
        d["model_vrp_log"].notna()
        & d["model_vrp_z_3m"].notna()
        & d["model_vrp_z_1y"].notna()
        & d["RSI14"].notna()
        & d["forecast_vol_pct"].notna()
    )

    pass_mask = pd.Series(False, index=d.index)

    bucket_pass_counts = {}

    for bucket in ["Front", "Middle", "Back"]:
        bucket_mask = d["tenor_bucket"].eq(bucket)

        log_threshold = candidate[f"{bucket}_model_vrp_log"]
        z_threshold = candidate[f"{bucket}_model_vrp_z"]
        rsi_max = candidate[f"{bucket}_RSI14_max"]
        fv_floor = candidate[f"{bucket}_forecast_vol_pct_min"]

        bucket_pass = (
            required_inputs
            & bucket_mask
            & (d["model_vrp_log"] > log_threshold)
            & (d["model_vrp_z_3m"] > z_threshold)
            & (d["model_vrp_z_1y"] > z_threshold)
            & (d["RSI14"] < rsi_max)
            & (d["forecast_vol_pct"] > fv_floor)
        )

        pass_mask = pass_mask | bucket_pass
        bucket_pass_counts[f"{bucket}_pass_rows_all_dates"] = int(bucket_pass.sum())

    d["candidate_core_pass"] = pass_mask

    outcome_available = (
        d["normalized_pnl_dollars"].notna()
        & d["normalized_pnl_per_day"].notna()
    )

    qualified = d[
        d["candidate_core_pass"]
        & outcome_available
    ].copy()

    diagnostics = {
        "candidate_id": candidate["candidate_id"],
        "pass_rows_all_dates": int(pass_mask.sum()),
        "pass_rows_with_outcomes": int(len(qualified)),
        "threshold_input_available_rows": int(required_inputs.sum()),
        "trade_outcome_available_rows": int(outcome_available.sum()),
    }

    diagnostics.update(bucket_pass_counts)

    return qualified, diagnostics


def attach_candidate_parameters(summary: pd.DataFrame, grid_wide: pd.DataFrame) -> pd.DataFrame:
    if summary.empty:
        return summary

    param_cols = [
        c for c in grid_wide.columns
        if c == "candidate_id"
        or c.endswith("_model_vrp_log")
        or c.endswith("_model_vrp_z")
        or c.endswith("_RSI14_max")
        or c.endswith("_forecast_vol_pct_min")
        or c in [
            "front_middle_log_gap",
            "middle_back_log_gap",
            "front_middle_z_gap",
            "middle_back_z_gap",
            "front_middle_RSI_gap",
            "front_middle_forecast_floor_gap",
            "middle_back_forecast_floor_gap",
        ]
    ]

    params = grid_wide[param_cols].copy()

    out = summary.merge(params, on="candidate_id", how="left", validate="many_to_one")

    return out


# ======================================================================================
# 2. Load signal panel and candidate grid
# ======================================================================================

base_panel_path = latest_file(
    OUT_PROCESSED_DIR,
    "01_unified_fds_signal_base_panel_*.parquet",
    required=True,
)

grid_wide_path = latest_file(
    OUT_PROCESSED_DIR,
    "03_core_threshold_candidate_grid_wide_*.parquet",
    required=True,
)

grid_long_path = latest_file(
    OUT_PROCESSED_DIR,
    "03_core_threshold_candidate_grid_long_*.parquet",
    required=True,
)

signal = pd.read_parquet(base_panel_path)
grid_wide = pd.read_parquet(grid_wide_path)
grid_long = pd.read_parquet(grid_long_path)

# Normalize dates / numeric fields.
signal["trade_date"] = pd.to_datetime(signal["trade_date"], errors="coerce").dt.normalize()
signal["tenor"] = pd.to_numeric(signal["tenor"], errors="coerce").astype(int)

if "last_forward_rv_date" in signal.columns:
    signal["last_forward_rv_date"] = pd.to_datetime(
        signal["last_forward_rv_date"],
        errors="coerce",
    ).dt.normalize()

required_signal_cols = [
    "trade_date",
    "tenor",
    "tenor_bucket",
    "tenor_bucket_order",
    "model_spec",
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14",
    "forecast_vol_pct",
    "normalized_pnl_dollars",
    "normalized_pnl_per_day",
    "win",
]

missing_signal_cols = [c for c in required_signal_cols if c not in signal.columns]
if missing_signal_cols:
    raise KeyError(f"Cell 6 missing required signal columns: {missing_signal_cols}")

required_grid_cols = [
    "candidate_id",
    "Front_model_vrp_log",
    "Front_model_vrp_z",
    "Front_RSI14_max",
    "Front_forecast_vol_pct_min",
    "Middle_model_vrp_log",
    "Middle_model_vrp_z",
    "Middle_RSI14_max",
    "Middle_forecast_vol_pct_min",
    "Back_model_vrp_log",
    "Back_model_vrp_z",
    "Back_RSI14_max",
    "Back_forecast_vol_pct_min",
]

missing_grid_cols = [c for c in required_grid_cols if c not in grid_wide.columns]
if missing_grid_cols:
    raise KeyError(f"Cell 6 missing required grid columns: {missing_grid_cols}")

# Ensure numeric fields.
for c in [
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14",
    "forecast_vol_pct",
    "normalized_pnl_dollars",
    "normalized_pnl_per_day",
    "win",
]:
    signal[c] = pd.to_numeric(signal[c], errors="coerce")

for c in [c for c in grid_wide.columns if c.endswith("_model_vrp_log") or c.endswith("_model_vrp_z") or c.endswith("_RSI14_max") or c.endswith("_forecast_vol_pct_min")]:
    grid_wide[c] = pd.to_numeric(grid_wide[c], errors="coerce")

grid_wide = grid_wide.sort_values("candidate_id").reset_index(drop=True)

# ======================================================================================
# 3. Sweep candidates
# ======================================================================================

start_time = time.time()

overall_summary_rows = []
bucket_summary_rows = []
tenor_summary_rows = []
year_summary_rows = []
pass_diagnostic_rows = []
selected_trade_frames = []

candidate_count = len(grid_wide)

print("=" * 100)
print("Cell 6 — Core threshold candidate sweep using P&L/day")
print("=" * 100)
print(f"Signal panel:             {base_panel_path}")
print(f"Wide candidate grid:      {grid_wide_path}")
print(f"Long candidate grid:      {grid_long_path}")
print(f"Candidates to evaluate:   {candidate_count:,}")
print(f"Selection universes:      {SELECTION_UNIVERSES}")
print(f"Primary metric:           {PRIMARY_RANKING_METRIC}")
print()

for i, candidate in grid_wide.iterrows():
    candidate_id = candidate["candidate_id"]

    qualified, pass_diag = apply_candidate_thresholds(signal, candidate)
    pass_diagnostic_rows.append(pass_diag)

    universes = select_trade_universes(qualified)

    for universe_name, selected in universes.items():
        if not selected.empty:
            selected = selected.copy()
            selected.insert(0, "selection_universe", universe_name)
            selected.insert(0, "candidate_id", candidate_id)

            # Attach the candidate's exact thresholds to selected rows for audit traceability.
            for bucket in ["Front", "Middle", "Back"]:
                selected[f"{bucket}_model_vrp_log_threshold"] = candidate[f"{bucket}_model_vrp_log"]
                selected[f"{bucket}_model_vrp_z_threshold"] = candidate[f"{bucket}_model_vrp_z"]
                selected[f"{bucket}_RSI14_max"] = candidate[f"{bucket}_RSI14_max"]
                selected[f"{bucket}_forecast_vol_pct_min"] = candidate[f"{bucket}_forecast_vol_pct_min"]

            selected_trade_frames.append(selected)

        overall_summary_rows.append(
            summarize_trade_set(
                selected,
                candidate_id=candidate_id,
                selection_universe=universe_name,
                group_cols=[],
                include_empty_overall=True,
            )
        )

        bucket_summary_rows.append(
            summarize_trade_set(
                selected,
                candidate_id=candidate_id,
                selection_universe=universe_name,
                group_cols=["tenor_bucket", "tenor_bucket_order"],
                include_empty_overall=False,
            )
        )

        tenor_summary_rows.append(
            summarize_trade_set(
                selected,
                candidate_id=candidate_id,
                selection_universe=universe_name,
                group_cols=["tenor", "tenor_bucket", "tenor_bucket_order"],
                include_empty_overall=False,
            )
        )

        if not selected.empty:
            selected_year = selected.copy()
            selected_year["year"] = selected_year["trade_date"].dt.year.astype(int)

            year_summary_rows.append(
                summarize_trade_set(
                    selected_year,
                    candidate_id=candidate_id,
                    selection_universe=universe_name,
                    group_cols=["year"],
                    include_empty_overall=False,
                )
            )

    if (i + 1) % 50 == 0 or (i + 1) == candidate_count:
        elapsed = time.time() - start_time
        print(f"  Evaluated {i + 1:,} / {candidate_count:,} candidates | elapsed {elapsed:,.1f}s")

# Combine.
summary_overall = pd.concat(overall_summary_rows, ignore_index=True) if overall_summary_rows else pd.DataFrame()
summary_by_bucket = pd.concat(bucket_summary_rows, ignore_index=True) if bucket_summary_rows else pd.DataFrame()
summary_by_tenor = pd.concat(tenor_summary_rows, ignore_index=True) if tenor_summary_rows else pd.DataFrame()
summary_by_year = pd.concat(year_summary_rows, ignore_index=True) if year_summary_rows else pd.DataFrame()
pass_diagnostics = pd.DataFrame(pass_diagnostic_rows)

selected_trade_panel = (
    pd.concat(selected_trade_frames, ignore_index=True)
    if selected_trade_frames
    else pd.DataFrame()
)

# Attach candidate thresholds to summary tables.
summary_overall = attach_candidate_parameters(summary_overall, grid_wide)
summary_by_bucket = attach_candidate_parameters(summary_by_bucket, grid_wide)
summary_by_tenor = attach_candidate_parameters(summary_by_tenor, grid_wide)
summary_by_year = attach_candidate_parameters(summary_by_year, grid_wide)
pass_diagnostics = attach_candidate_parameters(pass_diagnostics, grid_wide)

# Sort useful outputs.
if not summary_overall.empty:
    summary_overall = summary_overall.sort_values(
        ["selection_universe", PRIMARY_RANKING_METRIC, "profit_factor_pnl_per_day", "trades"],
        ascending=[True, False, False, False],
    )

if not summary_by_bucket.empty:
    summary_by_bucket = summary_by_bucket.sort_values(
        ["selection_universe", "candidate_id", "tenor_bucket_order"]
    )

if not summary_by_tenor.empty:
    summary_by_tenor = summary_by_tenor.sort_values(
        ["selection_universe", "candidate_id", "tenor"]
    )

if not summary_by_year.empty:
    summary_by_year = summary_by_year.sort_values(
        ["selection_universe", "candidate_id", "year"]
    )

elapsed_seconds = time.time() - start_time

# ======================================================================================
# 4. Save outputs
# ======================================================================================

candidate_summary_path = OUT_AUDIT_DIR / f"04_core_threshold_sweep_candidate_summary_{CELL6_TIMESTAMP}.csv"
by_bucket_path = OUT_AUDIT_DIR / f"04_core_threshold_sweep_by_bucket_{CELL6_TIMESTAMP}.csv"
by_tenor_path = OUT_AUDIT_DIR / f"04_core_threshold_sweep_by_tenor_{CELL6_TIMESTAMP}.csv"
by_year_path = OUT_AUDIT_DIR / f"04_core_threshold_sweep_by_year_{CELL6_TIMESTAMP}.csv"
pass_diagnostics_path = OUT_AUDIT_DIR / f"04_core_threshold_sweep_candidate_pass_diagnostics_{CELL6_TIMESTAMP}.csv"
selected_trade_panel_path = OUT_PROCESSED_DIR / f"04_core_threshold_sweep_selected_trade_panel_{CELL6_TIMESTAMP}.parquet"
validation_path = OUT_AUDIT_DIR / f"04_core_threshold_sweep_validation_{CELL6_TIMESTAMP}.csv"
manifest_path = OUT_AUDIT_DIR / f"04_core_threshold_sweep_manifest_{CELL6_TIMESTAMP}.json"

summary_overall.to_csv(candidate_summary_path, index=False)
summary_by_bucket.to_csv(by_bucket_path, index=False)
summary_by_tenor.to_csv(by_tenor_path, index=False)
summary_by_year.to_csv(by_year_path, index=False)
pass_diagnostics.to_csv(pass_diagnostics_path, index=False)

selected_trade_panel.to_parquet(selected_trade_panel_path, index=False)

# ======================================================================================
# 5. Validation
# ======================================================================================

validation_rows = []

def add_validation(check, status, detail):
    validation_rows.append({
        "check": check,
        "status": status,
        "detail": detail,
    })

models_found = sorted(signal["model_spec"].dropna().unique().tolist())
candidate_ids = grid_wide["candidate_id"].dropna().tolist()
candidate_id_unique = len(candidate_ids) == len(set(candidate_ids))

expected_overall_rows = len(grid_wide) * len(SELECTION_UNIVERSES)
actual_overall_rows = len(summary_overall)

back_bad = grid_wide[
    (grid_wide["Back_model_vrp_log"] != LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"])
    | (grid_wide["Back_model_vrp_z"] != LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"])
    | (grid_wide["Back_RSI14_max"] != LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"])
    | (grid_wide["Back_forecast_vol_pct_min"] != LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"])
]

z_equality_bad = grid_wide[
    ("Front_model_vrp_z_3m" in grid_wide.columns)
    & ("Front_model_vrp_z_1y" in grid_wide.columns)
] if False else pd.DataFrame()

if {"Front_model_vrp_z_3m", "Front_model_vrp_z_1y", "Middle_model_vrp_z_3m", "Middle_model_vrp_z_1y", "Back_model_vrp_z_3m", "Back_model_vrp_z_1y"}.issubset(set(grid_wide.columns)):
    z_equality_bad = grid_wide[
        (grid_wide["Front_model_vrp_z_3m"] != grid_wide["Front_model_vrp_z_1y"])
        | (grid_wide["Middle_model_vrp_z_3m"] != grid_wide["Middle_model_vrp_z_1y"])
        | (grid_wide["Back_model_vrp_z_3m"] != grid_wide["Back_model_vrp_z_1y"])
    ]

bad_pnl_day = signal[
    signal["normalized_pnl_dollars"].notna()
    & signal["normalized_pnl_per_day"].notna()
    & (
        (
            signal["normalized_pnl_dollars"] / signal["tenor"].replace(0, np.nan)
        )
        - signal["normalized_pnl_per_day"]
    ).abs().gt(1e-8)
]

selection_universes_found = sorted(summary_overall["selection_universe"].dropna().unique().tolist())

selected_trade_universes_found = (
    sorted(selected_trade_panel["selection_universe"].dropna().unique().tolist())
    if not selected_trade_panel.empty and "selection_universe" in selected_trade_panel.columns
    else []
)

add_validation(
    "signal_panel_loaded",
    "PASS" if len(signal) > 0 else "FAIL",
    f"rows={len(signal):,}; path={base_panel_path}",
)

add_validation(
    "locked_model_only",
    "PASS" if models_found == [LOCKED_MODEL_SPEC] else "FAIL",
    f"models_found={models_found}",
)

add_validation(
    "candidate_grid_loaded",
    "PASS" if len(grid_wide) > 0 else "FAIL",
    f"candidate_count={len(grid_wide):,}; path={grid_wide_path}",
)

add_validation(
    "candidate_id_unique",
    "PASS" if candidate_id_unique else "FAIL",
    f"candidate_ids={len(candidate_ids):,}; unique={len(set(candidate_ids)):,}",
)

add_validation(
    "back_thresholds_locked",
    "PASS" if back_bad.empty else "FAIL",
    f"bad_rows={len(back_bad):,}; locked_back={LOCKED_BACK_CORE_THRESHOLDS}",
)

add_validation(
    "z_3m_equals_z_1y_within_bucket",
    "PASS" if z_equality_bad.empty else "FAIL",
    f"bad_rows={len(z_equality_bad):,}",
)

add_validation(
    "normalized_pnl_per_day_formula",
    "PASS" if bad_pnl_day.empty else "FAIL",
    f"bad_rows={len(bad_pnl_day):,}; formula=normalized_pnl_dollars / tenor",
)

add_validation(
    "overall_summary_rows_complete",
    "PASS" if actual_overall_rows == expected_overall_rows else "FAIL",
    f"actual={actual_overall_rows:,}; expected={expected_overall_rows:,}",
)

add_validation(
    "all_selection_universes_evaluated",
    "PASS" if selection_universes_found == sorted(SELECTION_UNIVERSES) else "FAIL",
    f"found={selection_universes_found}",
)

add_validation(
    "selected_trade_panel_saved",
    "PASS" if len(selected_trade_panel) > 0 else "WARN",
    f"rows={len(selected_trade_panel):,}; universes={selected_trade_universes_found}",
)

add_validation(
    "candidate_pass_diagnostics_created",
    "PASS" if len(pass_diagnostics) == len(grid_wide) else "FAIL",
    f"rows={len(pass_diagnostics):,}; expected={len(grid_wide):,}",
)

add_validation(
    "no_final_candidate_selection",
    "PASS",
    "Cell 6 is raw sweep only. Final ranking/selection deferred to Cell 7.",
)

add_validation(
    "no_secondary",
    "PASS",
    "Core only.",
)

add_validation(
    "no_sizing_changes",
    "PASS",
    "Threshold sweep only. No sizing fields changed.",
)

add_validation(
    "no_production_lock",
    "PASS",
    "No production threshold lock performed.",
)

validation = pd.DataFrame(validation_rows)
validation.to_csv(validation_path, index=False)

failures = validation[validation["status"] == "FAIL"]

manifest = {
    "notebook": "07_unified_fds_core_signal_threshold_research_v1.ipynb",
    "cell": "Cell 6 — Core threshold candidate sweep using P&L/day",
    "timestamp": CELL6_TIMESTAMP,
    "elapsed_seconds": elapsed_seconds,
    "locked_model_spec": LOCKED_MODEL_SPEC,
    "base_panel_path": str(base_panel_path),
    "grid_wide_path": str(grid_wide_path),
    "grid_long_path": str(grid_long_path),
    "candidate_count": int(len(grid_wide)),
    "selection_universes": SELECTION_UNIVERSES,
    "primary_ranking_metric": PRIMARY_RANKING_METRIC,
    "candidate_summary_path": str(candidate_summary_path),
    "by_bucket_path": str(by_bucket_path),
    "by_tenor_path": str(by_tenor_path),
    "by_year_path": str(by_year_path),
    "pass_diagnostics_path": str(pass_diagnostics_path),
    "selected_trade_panel_path": str(selected_trade_panel_path),
    "validation_path": str(validation_path),
    "notes": [
        "Raw sweep only.",
        "No final candidate selected.",
        "No Secondary.",
        "No sizing changes.",
        "No production lock.",
        "If top candidates cluster at parameter boundaries, expand the grid in a later cell.",
        "P&L/day is the primary cross-tenor quality metric.",
        "Best-rank DTE selection remains diagnostic only.",
    ],
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2)

if not failures.empty:
    display(validation)
    raise RuntimeError("Cell 6 validation failed. Review validation output above.")

# ======================================================================================
# 6. Display concise review
# ======================================================================================

print("=" * 100)
print("Cell 6 — Core threshold candidate sweep using P&L/day")
print("=" * 100)
print(f"Signal panel:                  {base_panel_path}")
print(f"Candidate grid:                {grid_wide_path}")
print(f"Candidates evaluated:          {len(grid_wide):,}")
print(f"Overall summary rows:          {len(summary_overall):,}")
print(f"By-bucket rows:                {len(summary_by_bucket):,}")
print(f"By-tenor rows:                 {len(summary_by_tenor):,}")
print(f"By-year rows:                  {len(summary_by_year):,}")
print(f"Selected trade panel rows:     {len(selected_trade_panel):,}")
print(f"Elapsed seconds:               {elapsed_seconds:,.1f}")
print(f"Primary ranking metric:        {PRIMARY_RANKING_METRIC}")
print("No final candidate selection:  True")
print("No Secondary:                  True")
print("No sizing changes:             True")
print("No production lock:            True")

print()
print("Validation:")
display(validation)

print()
print("Top 20 by avg P&L/day — one trade per bucket/date:")
top_bucket = summary_overall[
    summary_overall["selection_universe"].eq("one_trade_per_bucket_per_date_best_rank")
].sort_values(
    ["avg_pnl_per_day", "profit_factor_pnl_per_day", "trades"],
    ascending=[False, False, False],
).head(20)

top_display_cols = [
    "candidate_id",
    "selection_universe",
    "trades",
    "unique_trade_dates",
    "avg_tenor",
    "win_rate",
    "total_pnl",
    "profit_factor",
    "avg_pnl_per_day",
    "median_pnl_per_day",
    "worst_trade_pnl_per_day",
    "pnl_per_day_drawdown",
    "worst_20_trade_pnl_per_day_sum",
    "trades_le_neg_100k",
    "pnl_2025",
    "avg_pnl_per_day_2025",
    "pnl_2026",
    "avg_pnl_per_day_2026",
    "Front_model_vrp_log",
    "Front_model_vrp_z",
    "Front_RSI14_max",
    "Front_forecast_vol_pct_min",
    "Middle_model_vrp_log",
    "Middle_model_vrp_z",
    "Middle_RSI14_max",
    "Middle_forecast_vol_pct_min",
    "Back_model_vrp_log",
    "Back_model_vrp_z",
]
display(top_bucket[[c for c in top_display_cols if c in top_bucket.columns]])

print()
print("Top 20 by avg P&L/day — one trade per date:")
top_date = summary_overall[
    summary_overall["selection_universe"].eq("one_trade_per_date_best_rank")
].sort_values(
    ["avg_pnl_per_day", "profit_factor_pnl_per_day", "trades"],
    ascending=[False, False, False],
).head(20)

display(top_date[[c for c in top_display_cols if c in top_date.columns]])

print()
print("Top 20 by avg P&L/day — all qualified trades:")
top_all = summary_overall[
    summary_overall["selection_universe"].eq("all_qualified_trades")
].sort_values(
    ["avg_pnl_per_day", "profit_factor_pnl_per_day", "trades"],
    ascending=[False, False, False],
).head(20)

display(top_all[[c for c in top_display_cols if c in top_all.columns]])

print()
print("30D anchor reference rows:")
anchor = summary_overall[
    summary_overall["selection_universe"].eq("thirty_day_anchor_only")
].sort_values("candidate_id").head(10)

display(anchor[[c for c in top_display_cols if c in anchor.columns]])

print()
print("Pass diagnostics sample:")
pass_diag_display_cols = [
    "candidate_id",
    "pass_rows_all_dates",
    "pass_rows_with_outcomes",
    "Front_pass_rows_all_dates",
    "Middle_pass_rows_all_dates",
    "Back_pass_rows_all_dates",
    "Front_model_vrp_log",
    "Front_model_vrp_z",
    "Front_RSI14_max",
    "Front_forecast_vol_pct_min",
    "Middle_model_vrp_log",
    "Middle_model_vrp_z",
    "Middle_RSI14_max",
    "Middle_forecast_vol_pct_min",
]
display(pass_diagnostics[[c for c in pass_diag_display_cols if c in pass_diagnostics.columns]].head(20))

print()
print("Saved outputs:")
for p in [
    candidate_summary_path,
    by_bucket_path,
    by_tenor_path,
    by_year_path,
    pass_diagnostics_path,
    selected_trade_panel_path,
    validation_path,
    manifest_path,
]:
    print(f"  {p}")

print("\nCELL 6 PASSED")

====================================================================================================
Cell 6 — Core threshold candidate sweep using P&L/day
====================================================================================================
Signal panel:             C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\01_unified_fds_signal_base_panel_20200102_20260701_20260704_211636.parquet
Wide candidate grid:      C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\03_core_threshold_candidate_grid_wide_20260704_213318.parquet
Long candidate grid:      C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\03_core_threshold_candidate_grid_long_20260704_213318.parquet
Candidates to evaluate:   375
Selection universes:      ['all_qualified_trades', 'one_trade_per_bucket_per_date_best_rank', 'one_trade_per_date_best_rank', 'thirty_day_anchor_only']
Primary metric:           avg_pnl_per_day

  Evaluated 50 / 375 candidates | elapsed 23.2s
  Evaluated 100 / 375 candidates | elapsed 45.6s
  Evaluated 150 / 375 candidates | elapsed 67.2s
  Evaluated 200 / 375 candidates | elapsed 89.0s
  Evaluated 250 / 375 candidates | elapsed 112.1s
  Evaluated 300 / 375 candidates | elapsed 133.6s
  Evaluated 350 / 375 candidates | elapsed 155.4s
  Evaluated 375 / 375 candidates | elapsed 166.2s
====================================================================================================
Cell 6 — Core threshold candidate sweep using P&L/day
====================================================================================================
Signal panel:                  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\01_unified_fds_signal_base_panel_20200102_20260701_20260704_211636.parquet
Candidate grid:                C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\03_core_threshold_candidate_grid_wide_20260704_213318.parquet
Candidates evaluated:          375
Overall summary rows:          1,500
By-bucket rows:                3,750
By-tenor rows:                 10,500
By-year rows:                  9,240
Selected trade panel rows:     834,098
Elapsed seconds:               168.8
Primary ranking metric:        avg_pnl_per_day
No final candidate selection:  True
No Secondary:                  True
No sizing changes:             True
No production lock:            True

Validation:

                                 check status                                             detail
0                  signal_panel_loaded   PASS  rows=14,688; path=C:\Users\patri\vrp_project\d...
1                    locked_model_only   PASS         models_found=['unified_fds_no_min_return']
2                candidate_grid_loaded   PASS  candidate_count=375; path=C:\Users\patri\vrp_p...
3                  candidate_id_unique   PASS                      candidate_ids=375; unique=375
4               back_thresholds_locked   PASS  bad_rows=0; locked_back={'model_vrp_log': 0.7,...
5       z_3m_equals_z_1y_within_bucket   PASS                                         bad_rows=0
6       normalized_pnl_per_day_formula   PASS  bad_rows=0; formula=normalized_pnl_dollars / t...
7        overall_summary_rows_complete   PASS                       actual=1,500; expected=1,500
8    all_selection_universes_evaluated   PASS  found=['all_qualified_trades', 'one_trade_per_...
9           selected_trade_panel_saved   PASS  rows=834,098; universes=['all_qualified_trades...
10  candidate_pass_diagnostics_created   PASS                             rows=375; expected=375
11        no_final_candidate_selection   PASS  Cell 6 is raw sweep only. Final ranking/select...
12                        no_secondary   PASS                                         Core only.
13                   no_sizing_changes   PASS    Threshold sweep only. No sizing fields changed.
14                  no_production_lock   PASS            No production threshold lock performed.

Top 20 by avg P&L/day — one trade per bucket/date:

,candidate_id,selection_universe,trades,unique_trade_dates,avg_tenor,win_rate,total_pnl,profit_factor,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,pnl_2025,avg_pnl_per_day_2025,pnl_2026,avg_pnl_per_day_2026,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z
1313,core_grid_00329,one_trade_per_bucket_per_date_best_rank,492,224,20.579268,0.839431,5.556302e+06,3.408855,478.215063,867.741336,-10376.349181,-54837.874446,-30554.551981,1,1.250250e+06,663.667312,-9141.293529,-154.274083,0.70,0.65,68.0,10.0,0.70,0.70,68.0,8.5,0.7,0.7
1317,core_grid_00330,one_trade_per_bucket_per_date_best_rank,488,224,20.581967,0.838115,5.515712e+06,3.391258,478.046934,873.480210,-10376.349181,-54837.874446,-30554.551981,1,1.209660e+06,671.521620,-9141.293529,-154.274083,0.70,0.65,68.0,10.0,0.70,0.70,68.0,10.0,0.7,0.7
1297,core_grid_00325,one_trade_per_bucket_per_date_best_rank,501,227,20.598802,0.840319,5.629937e+06,3.389343,477.255445,865.753788,-10376.349181,-54837.874446,-30554.551981,1,1.275860e+06,662.989656,-9141.293529,-154.274083,0.70,0.65,68.0,10.0,0.70,0.65,68.0,8.5,0.7,0.7
1321,core_grid_00331,one_trade_per_bucket_per_date_best_rank,484,224,20.559917,0.836777,5.461740e+06,3.367859,477.160908,879.606050,-10376.349181,-54837.874446,-30554.551981,1,1.198626e+06,675.033211,-38017.482311,-173.190990,0.70,0.65,68.0,10.0,0.70,0.70,66.0,8.5,0.7,0.7
1325,core_grid_00332,one_trade_per_bucket_per_date_best_rank,484,224,20.578512,0.836777,5.465876e+06,3.369652,477.154319,879.606050,-10376.349181,-54837.874446,-30554.551981,1,1.202761e+06,674.994787,-38017.482311,-173.190990,0.70,0.65,68.0,10.0,0.70,0.70,66.0,10.0,0.7,0.7
809,core_grid_00203,one_trade_per_bucket_per_date_best_rank,509,232,20.416503,0.838900,5.678573e+06,3.424063,476.858038,845.092627,-10376.349181,-54837.874446,-30554.551981,1,1.260338e+06,636.992355,8259.859683,-144.716233,0.65,0.65,68.0,10.0,0.65,0.70,68.0,8.5,0.7,0.7
813,core_grid_00204,one_trade_per_bucket_per_date_best_rank,505,232,20.417822,0.837624,5.637983e+06,3.406736,476.684820,851.275886,-10376.349181,-54837.874446,-30554.551981,1,1.219748e+06,643.277152,8259.859683,-144.716233,0.65,0.65,68.0,10.0,0.65,0.70,68.0,10.0,0.7,0.7
1301,core_grid_00326,one_trade_per_bucket_per_date_best_rank,496,226,20.600806,0.838710,5.574651e+06,3.365880,476.633571,870.479355,-10376.349181,-54837.874446,-30554.551981,1,1.235270e+06,670.629787,-9141.293529,-154.274083,0.70,0.65,68.0,10.0,0.70,0.65,68.0,10.0,0.7,0.7
793,core_grid_00199,one_trade_per_bucket_per_date_best_rank,518,235,20.438224,0.839768,5.752208e+06,3.404529,475.953491,843.286845,-10376.349181,-54837.874446,-30554.551981,1,1.285949e+06,636.911088,8259.859683,-144.716233,0.65,0.65,68.0,10.0,0.65,0.65,68.0,8.5,0.7,0.7
841,core_grid_00211,one_trade_per_bucket_per_date_best_rank,502,232,20.408367,0.838645,5.595748e+06,3.390586,475.946264,857.744702,-10376.349181,-54837.874446,-30554.551981,1,1.245589e+06,644.603693,-9141.293529,-154.274083,0.65,0.65,68.0,10.0,0.70,0.70,68.0,8.5,0.7,0.7
817,core_grid_00205,one_trade_per_bucket_per_date_best_rank,501,232,20.395210,0.836327,5.584011e+06,3.383696,475.817983,856.311368,-10376.349181,-54837.874446,-30554.551981,1,1.208714e+06,646.302641,-20616.329098,-163.210556,0.65,0.65,68.0,10.0,0.65,0.70,66.0,8.5,0.7,0.7
821,core_grid_00206,one_trade_per_bucket_per_date_best_rank,501,232,20.413174,0.836327,5.588146e+06,3.385462,475.811618,856.311368,-10376.349181,-54837.874446,-30554.551981,1,1.212850e+06,646.265983,-20616.329098,-163.210556,0.65,0.65,68.0,10.0,0.65,0.70,66.0,10.0,0.7,0.7
845,core_grid_00212,one_trade_per_bucket_per_date_best_rank,498,232,20.409639,0.837349,5.555158e+06,3.373245,475.763288,864.716371,-10376.349181,-54837.874446,-30554.551981,1,1.204999e+06,651.388663,-9141.293529,-154.274083,0.65,0.65,68.0,10.0,0.70,0.70,68.0,10.0,0.7,0.7
1305,core_grid_00327,one_trade_per_bucket_per_date_best_rank,492,226,20.579268,0.837398,5.520679e+06,3.342974,475.750461,875.924899,-10376.349181,-54837.874446,-30554.551981,1,1.224236e+06,674.048260,-38017.482311,-173.190990,0.70,0.65,68.0,10.0,0.70,0.65,66.0,8.5,0.7,0.7
1309,core_grid_00328,one_trade_per_bucket_per_date_best_rank,492,226,20.597561,0.837398,5.524815e+06,3.344729,475.743979,875.924899,-10376.349181,-54837.874446,-30554.551981,1,1.228372e+06,674.010740,-38017.482311,-173.190990,0.70,0.65,68.0,10.0,0.70,0.65,66.0,10.0,0.7,0.7
797,core_grid_00200,one_trade_per_bucket_per_date_best_rank,513,234,20.438596,0.838207,5.696921e+06,3.381418,475.339535,847.938830,-10376.349181,-54837.874446,-30554.551981,1,1.245359e+06,643.052610,8259.859683,-144.716233,0.65,0.65,68.0,10.0,0.65,0.65,68.0,10.0,0.7,0.7
825,core_grid_00207,one_trade_per_bucket_per_date_best_rank,511,235,20.430528,0.839530,5.669383e+06,3.371733,475.045385,854.101666,-10376.349181,-54837.874446,-30554.551981,1,1.271200e+06,644.355195,-9141.293529,-154.274083,0.65,0.65,68.0,10.0,0.70,0.65,68.0,8.5,0.7,0.7
849,core_grid_00213,one_trade_per_bucket_per_date_best_rank,494,232,20.386640,0.836032,5.501186e+06,3.350188,474.876707,867.741336,-10376.349181,-54837.874446,-30554.551981,1,1.193965e+06,654.580770,-38017.482311,-173.190990,0.65,0.65,68.0,10.0,0.70,0.70,66.0,8.5,0.7,0.7
853,core_grid_00214,one_trade_per_bucket_per_date_best_rank,494,232,20.404858,0.836032,5.505322e+06,3.351954,474.870251,867.741336,-10376.349181,-54837.874446,-30554.551981,1,1.198101e+06,654.543250,-38017.482311,-173.190990,0.65,0.65,68.0,10.0,0.70,0.70,66.0,10.0,0.7,0.7
945,core_grid_00237,one_trade_per_bucket_per_date_best_rank,495,229,20.484848,0.836364,5.546702e+06,3.380011,474.849411,859.178035,-10376.349181,-54837.874446,-30554.551981,1,1.201816e+06,648.470130,-55282.641615,-201.159250,0.65,0.65,66.0,10.0,0.65,0.70,66.0,8.5,0.7,0.7

Top 20 by avg P&L/day — one trade per date:

,candidate_id,selection_universe,trades,unique_trade_dates,avg_tenor,win_rate,total_pnl,profit_factor,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,pnl_2025,avg_pnl_per_day_2025,pnl_2026,avg_pnl_per_day_2026,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z
842,core_grid_00211,one_trade_per_date_best_rank,232,232,20.262931,0.849138,2.595524e+06,3.461773,383.253113,843.769983,-10376.349181,-21551.836736,-16562.587161,0,557133.039924,508.031635,131395.979748,-140.821713,0.65,0.65,68.0,10.0,0.70,0.7,68.0,8.5,0.7,0.7
850,core_grid_00213,one_trade_per_date_best_rank,232,232,20.327586,0.849138,2.599076e+06,3.465142,382.893138,843.769983,-10376.349181,-21551.836736,-16562.587161,0,561637.032317,506.120205,130444.093271,-140.572187,0.65,0.65,68.0,10.0,0.70,0.7,66.0,8.5,0.7,0.7
854,core_grid_00214,one_trade_per_date_best_rank,232,232,20.366379,0.849138,2.603212e+06,3.469065,382.879391,843.769983,-10376.349181,-21551.836736,-16562.587161,0,565772.539033,506.053763,130444.093271,-140.572187,0.65,0.65,68.0,10.0,0.70,0.7,66.0,10.0,0.7,0.7
846,core_grid_00212,one_trade_per_date_best_rank,232,232,20.379310,0.849138,2.604164e+06,3.469968,382.513512,843.769983,-10376.349181,-21551.836736,-16562.587161,0,565772.539033,504.456893,131395.979748,-140.821713,0.65,0.65,68.0,10.0,0.70,0.7,68.0,10.0,0.7,0.7
810,core_grid_00203,one_trade_per_date_best_rank,232,232,20.314655,0.849138,2.595524e+06,3.461773,381.696531,842.027987,-10376.349181,-21551.836736,-16562.587161,0,557133.039924,508.457890,131395.979748,-140.821713,0.65,0.65,68.0,10.0,0.65,0.7,68.0,8.5,0.7,0.7
818,core_grid_00205,one_trade_per_date_best_rank,232,232,20.379310,0.849138,2.599076e+06,3.465142,381.336555,842.027987,-10376.349181,-21551.836736,-16562.587161,0,561637.032317,506.546460,130444.093271,-140.572187,0.65,0.65,68.0,10.0,0.65,0.7,66.0,8.5,0.7,0.7
822,core_grid_00206,one_trade_per_date_best_rank,232,232,20.418103,0.849138,2.603212e+06,3.469065,381.322808,842.027987,-10376.349181,-21551.836736,-16562.587161,0,565772.539033,506.480018,130444.093271,-140.572187,0.65,0.65,68.0,10.0,0.65,0.7,66.0,10.0,0.7,0.7
814,core_grid_00204,one_trade_per_date_best_rank,232,232,20.431034,0.849138,2.604164e+06,3.469968,380.956929,842.027987,-10376.349181,-21551.836736,-16562.587161,0,565772.539033,504.883148,131395.979748,-140.821713,0.65,0.65,68.0,10.0,0.65,0.7,68.0,10.0,0.7,0.7
1114,core_grid_00279,one_trade_per_date_best_rank,224,224,20.665179,0.852679,2.561098e+06,3.507437,379.864054,843.203840,-10376.349181,-21551.836736,-14343.591500,0,557133.039924,508.031635,142771.771286,-105.723115,0.65,0.70,68.0,10.0,0.70,0.7,68.0,8.5,0.7,0.7
1118,core_grid_00280,one_trade_per_date_best_rank,224,224,20.785714,0.852679,2.569737e+06,3.515895,379.098038,843.203840,-10376.349181,-21551.836736,-14343.591500,0,565772.539033,504.456893,142771.771286,-105.723115,0.65,0.70,68.0,10.0,0.70,0.7,68.0,10.0,0.7,0.7
1098,core_grid_00275,one_trade_per_date_best_rank,224,224,20.718750,0.852679,2.561098e+06,3.507437,378.251879,839.856218,-10376.349181,-21551.836736,-14343.591500,0,557133.039924,508.457890,142771.771286,-105.723115,0.65,0.70,68.0,10.0,0.65,0.7,68.0,8.5,0.7,0.7
1122,core_grid_00281,one_trade_per_date_best_rank,223,223,20.757848,0.852018,2.552869e+06,3.499380,377.671096,843.686978,-10376.349181,-21551.836736,-14343.591500,0,561637.032317,506.120205,130039.193376,-134.202735,0.65,0.70,68.0,10.0,0.70,0.7,66.0,8.5,0.7,0.7
1126,core_grid_00282,one_trade_per_date_best_rank,223,223,20.798206,0.852018,2.557005e+06,3.503429,377.656794,843.686978,-10376.349181,-21551.836736,-14343.591500,0,565772.539033,506.053763,130039.193376,-134.202735,0.65,0.70,68.0,10.0,0.70,0.7,66.0,10.0,0.7,0.7
1102,core_grid_00276,one_trade_per_date_best_rank,224,224,20.839286,0.852679,2.569737e+06,3.515895,377.485863,839.856218,-10376.349181,-21551.836736,-14343.591500,0,565772.539033,504.883148,142771.771286,-105.723115,0.65,0.70,68.0,10.0,0.65,0.7,68.0,10.0,0.7,0.7
1314,core_grid_00329,one_trade_per_date_best_rank,224,224,20.558036,0.848214,2.542834e+06,3.444728,376.508549,852.688776,-10376.349181,-21551.836736,-16562.587161,0,553915.778868,523.624414,131395.979748,-140.821713,0.70,0.65,68.0,10.0,0.70,0.7,68.0,8.5,0.7,0.7
1322,core_grid_00331,one_trade_per_date_best_rank,224,224,20.625000,0.848214,2.546386e+06,3.448143,376.135717,852.688776,-10376.349181,-21551.836736,-16562.587161,0,558419.771261,521.629879,130444.093271,-140.572187,0.70,0.65,68.0,10.0,0.70,0.7,66.0,8.5,0.7,0.7
1326,core_grid_00332,one_trade_per_date_best_rank,224,224,20.665179,0.848214,2.550522e+06,3.452119,376.121479,852.688776,-10376.349181,-21551.836736,-16562.587161,0,562555.277977,521.560548,130444.093271,-140.572187,0.70,0.65,68.0,10.0,0.70,0.7,66.0,10.0,0.7,0.7
1106,core_grid_00277,one_trade_per_date_best_rank,223,223,20.811659,0.852018,2.552869e+06,3.499380,376.051691,841.335272,-10376.349181,-21551.836736,-14343.591500,0,561637.032317,506.546460,130039.193376,-134.202735,0.65,0.70,68.0,10.0,0.65,0.7,66.0,8.5,0.7,0.7
1110,core_grid_00278,one_trade_per_date_best_rank,223,223,20.852018,0.852018,2.557005e+06,3.503429,376.037390,841.335272,-10376.349181,-21551.836736,-14343.591500,0,565772.539033,506.480018,130039.193376,-134.202735,0.65,0.70,68.0,10.0,0.65,0.7,66.0,10.0,0.7,0.7
790,core_grid_00198,one_trade_per_date_best_rank,241,241,19.668050,0.846473,2.588586e+06,3.362638,376.015906,841.335272,-10376.349181,-21551.836736,-16562.587161,0,573737.025457,535.557083,121027.993954,-127.958219,0.65,0.65,68.0,8.5,0.70,0.7,66.0,8.5,0.7,0.7

Top 20 by avg P&L/day — all qualified trades:

,candidate_id,selection_universe,trades,unique_trade_dates,avg_tenor,win_rate,total_pnl,profit_factor,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,pnl_2025,avg_pnl_per_day_2025,pnl_2026,avg_pnl_per_day_2026,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z
972,core_grid_00244,all_qualified_trades,1328,224,21.002259,0.837349,1.559619e+07,3.498046,536.088751,892.533112,-10376.349181,-137635.647031,-70754.378759,5,3.184015e+06,659.231168,-73987.229744,-134.167381,0.65,0.65,66.0,11.5,0.65,0.65,66.0,10.0,0.7,0.7
868,core_grid_00218,all_qualified_trades,1331,225,20.981968,0.836965,1.560668e+07,3.494912,535.923163,892.830365,-10376.349181,-137635.647031,-70754.378759,5,3.184015e+06,659.231168,-51450.455305,-124.329741,0.65,0.65,68.0,11.5,0.65,0.65,66.0,10.0,0.7,0.7
1188,core_grid_00298,all_qualified_trades,1281,214,21.222482,0.839188,1.522858e+07,3.526129,535.634041,891.932931,-10376.349181,-136371.670193,-69549.218613,5,3.118471e+06,659.601932,-94368.910553,-138.916408,0.65,0.70,66.0,11.5,0.65,0.70,66.0,10.0,0.7,0.7
980,core_grid_00246,all_qualified_trades,1310,222,21.000000,0.836641,1.538406e+07,3.487757,535.502701,893.639528,-10376.349181,-137635.647031,-70754.378759,5,3.118471e+06,659.601932,-91388.382956,-138.065332,0.65,0.65,66.0,11.5,0.65,0.70,66.0,10.0,0.7,0.7
968,core_grid_00243,all_qualified_trades,1332,224,20.995495,0.837087,1.562189e+07,3.500962,535.481723,891.961043,-10376.349181,-137635.647031,-70754.378759,5,3.209714e+06,653.574076,-73987.229744,-134.167381,0.65,0.65,66.0,11.5,0.65,0.65,66.0,8.5,0.7,0.7
1140,core_grid_00286,all_qualified_trades,1284,215,21.200935,0.838785,1.523907e+07,3.522827,535.463455,891.961043,-10376.349181,-136371.670193,-69549.218613,5,3.118471e+06,659.601932,-71832.136114,-128.920829,0.65,0.70,68.0,11.5,0.65,0.70,66.0,10.0,0.7,0.7
884,core_grid_00222,all_qualified_trades,1313,223,20.979436,0.836253,1.539455e+07,3.484612,535.336183,893.646418,-10376.349181,-137635.647031,-70754.378759,5,3.118471e+06,659.601932,-68851.608518,-128.156874,0.65,0.65,68.0,11.5,0.65,0.70,66.0,10.0,0.7,0.7
864,core_grid_00217,all_qualified_trades,1335,225,20.975281,0.836704,1.563238e+07,3.497824,535.317995,891.989155,-10376.349181,-137635.647031,-70754.378759,5,3.209714e+06,653.574076,-51450.455305,-124.329741,0.65,0.65,68.0,11.5,0.65,0.65,66.0,8.5,0.7,0.7
1340,core_grid_00336,all_qualified_trades,1281,221,21.140515,0.835285,1.511450e+07,3.450037,535.238847,900.815238,-10376.349181,-137635.647031,-70754.378759,5,3.050818e+06,670.332684,-86252.761730,-131.597216,0.70,0.65,68.0,11.5,0.70,0.65,66.0,10.0,0.7,0.7
1184,core_grid_00297,all_qualified_trades,1285,214,21.214786,0.838911,1.525428e+07,3.529135,535.006225,891.398055,-10376.349181,-136371.670193,-69549.218613,5,3.144170e+06,653.812535,-94368.910553,-138.916408,0.65,0.70,66.0,11.5,0.65,0.70,66.0,8.5,0.7,0.7
976,core_grid_00245,all_qualified_trades,1314,222,20.993151,0.836377,1.540976e+07,3.490706,534.889142,892.533112,-10376.349181,-137635.647031,-70754.378759,5,3.144170e+06,653.812535,-91388.382956,-138.065332,0.65,0.65,66.0,11.5,0.65,0.70,66.0,8.5,0.7,0.7
1356,core_grid_00340,all_qualified_trades,1266,219,21.142180,0.834913,1.494458e+07,3.446064,534.881160,901.294096,-10376.349181,-137635.647031,-70754.378759,5,3.010077e+06,669.869218,-86252.761730,-131.597216,0.70,0.65,68.0,11.5,0.70,0.70,66.0,10.0,0.7,0.7
1136,core_grid_00285,all_qualified_trades,1288,215,21.193323,0.838509,1.526477e+07,3.525829,534.837631,891.421065,-10376.349181,-136371.670193,-69549.218613,5,3.144170e+06,653.812535,-71832.136114,-128.920829,0.65,0.70,68.0,11.5,0.65,0.70,66.0,8.5,0.7,0.7
880,core_grid_00221,all_qualified_trades,1317,223,20.972665,0.835991,1.542025e+07,3.487557,534.724527,892.830365,-10376.349181,-137635.647031,-70754.378759,5,3.144170e+06,653.812535,-68851.608518,-128.156874,0.65,0.65,68.0,11.5,0.65,0.70,66.0,8.5,0.7,0.7
860,core_grid_00216,all_qualified_trades,1343,226,20.982130,0.836932,1.570979e+07,3.501759,534.652530,890.138242,-10376.349181,-137635.647031,-70754.378759,5,3.216010e+06,657.161110,29699.847555,-106.266873,0.65,0.65,68.0,11.5,0.65,0.65,68.0,10.0,0.7,0.7
1336,core_grid_00335,all_qualified_trades,1285,221,21.133074,0.835019,1.514020e+07,3.453012,534.612261,899.841736,-10376.349181,-137635.647031,-70754.378759,5,3.076517e+06,664.045126,-86252.761730,-131.597216,0.70,0.65,68.0,11.5,0.70,0.65,66.0,8.5,0.7,0.7
988,core_grid_00248,all_qualified_trades,1302,224,21.002304,0.834869,1.526140e+07,3.445144,534.533052,900.011346,-10376.349181,-137635.647031,-70754.378759,5,3.094030e+06,660.993317,-108789.536169,-141.573923,0.65,0.65,66.0,11.5,0.70,0.65,66.0,10.0,0.7,0.7
900,core_grid_00226,all_qualified_trades,1305,225,20.981609,0.834483,1.527189e+07,3.442110,534.367742,900.180955,-10376.349181,-137635.647031,-70754.378759,5,3.094030e+06,660.993317,-86252.761730,-131.597216,0.65,0.65,68.0,11.5,0.70,0.65,66.0,10.0,0.7,0.7
1388,core_grid_00348,all_qualified_trades,1279,220,21.157154,0.835027,1.509197e+07,3.446384,534.362695,900.180955,-10376.349181,-137635.647031,-70754.378759,5,3.050818e+06,670.332684,-108789.536169,-141.573923,0.70,0.65,66.0,11.5,0.70,0.65,66.0,10.0,0.7,0.7
1196,core_grid_00300,all_qualified_trades,1258,214,21.228935,0.837043,1.493599e+07,3.478351,534.276063,899.396978,-10376.349181,-136371.670193,-69549.218613,5,3.053289e+06,660.419449,-111770.063765,-142.457246,0.65,0.70,66.0,11.5,0.70,0.70,66.0,10.0,0.7,0.7

30D anchor reference rows:

,candidate_id,selection_universe,trades,unique_trade_dates,avg_tenor,win_rate,total_pnl,profit_factor,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,pnl_2025,avg_pnl_per_day_2025,pnl_2026,avg_pnl_per_day_2026,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z
3,core_grid_00001,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.6,0.65,70.0,8.5,0.65,0.65,68.0,8.5,0.7,0.7
7,core_grid_00002,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.6,0.65,70.0,8.5,0.65,0.65,66.0,8.5,0.7,0.7
11,core_grid_00003,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.6,0.65,70.0,8.5,0.65,0.70,68.0,8.5,0.7,0.7
15,core_grid_00004,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.6,0.65,70.0,8.5,0.65,0.70,66.0,8.5,0.7,0.7
19,core_grid_00005,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.6,0.65,70.0,8.5,0.70,0.65,68.0,8.5,0.7,0.7
23,core_grid_00006,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.6,0.65,70.0,8.5,0.70,0.65,66.0,8.5,0.7,0.7
27,core_grid_00007,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.6,0.65,70.0,8.5,0.70,0.70,68.0,8.5,0.7,0.7
31,core_grid_00008,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.6,0.65,70.0,8.5,0.70,0.70,66.0,8.5,0.7,0.7
35,core_grid_00009,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.6,0.65,70.0,10.0,0.65,0.65,68.0,8.5,0.7,0.7
39,core_grid_00010,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.6,0.65,70.0,10.0,0.65,0.65,68.0,10.0,0.7,0.7

Pass diagnostics sample:

       candidate_id  pass_rows_all_dates  pass_rows_with_outcomes  Front_pass_rows_all_dates  Middle_pass_rows_all_dates  Back_pass_rows_all_dates  Front_model_vrp_log  Front_model_vrp_z  Front_RSI14_max  Front_forecast_vol_pct_min  Middle_model_vrp_log  Middle_model_vrp_z  Middle_RSI14_max  Middle_forecast_vol_pct_min
0   core_grid_00001                 1505                     1505                        592                         464                       449                  0.6               0.65             70.0                         8.5                  0.65                0.65              68.0                          8.5
1   core_grid_00002                 1480                     1480                        592                         439                       449                  0.6               0.65             70.0                         8.5                  0.65                0.65              66.0                          8.5
2   core_grid_00003                 1486                     1486                        592                         445                       449                  0.6               0.65             70.0                         8.5                  0.65                0.70              68.0                          8.5
3   core_grid_00004                 1462                     1462                        592                         421                       449                  0.6               0.65             70.0                         8.5                  0.65                0.70              66.0                          8.5
4   core_grid_00005                 1479                     1479                        592                         438                       449                  0.6               0.65             70.0                         8.5                  0.70                0.65              68.0                          8.5
5   core_grid_00006                 1454                     1454                        592                         413                       449                  0.6               0.65             70.0                         8.5                  0.70                0.65              66.0                          8.5
6   core_grid_00007                 1463                     1463                        592                         422                       449                  0.6               0.65             70.0                         8.5                  0.70                0.70              68.0                          8.5
7   core_grid_00008                 1439                     1439                        592                         398                       449                  0.6               0.65             70.0                         8.5                  0.70                0.70              66.0                          8.5
8   core_grid_00009                 1446                     1446                        533                         464                       449                  0.6               0.65             70.0                        10.0                  0.65                0.65              68.0                          8.5
9   core_grid_00010                 1429                     1429                        533                         447                       449                  0.6               0.65             70.0                        10.0                  0.65                0.65              68.0                         10.0
10  core_grid_00011                 1421                     1421                        533                         439                       449                  0.6               0.65             70.0                        10.0                  0.65                0.65              66.0                          8.5
11  core_grid_00012                 1417                     1417                        533                         435                       449                  0.6               0.65             70.0                        10.0                  0.65                0.65              66.0                         10.0
12  core_grid_00013                 1427                     1427                        533                         445                       449                  0.6               0.65             70.0                        10.0                  0.65                0.70              68.0                          8.5
13  core_grid_00014                 1411                     1411                        533                         429                       449                  0.6               0.65             70.0                        10.0                  0.65                0.70              68.0                         10.0
14  core_grid_00015                 1403                     1403                        533                         421                       449                  0.6               0.65             70.0                        10.0                  0.65                0.70              66.0                          8.5
15  core_grid_00016                 1399                     1399                        533                         417                       449                  0.6               0.65             70.0                        10.0                  0.65                0.70              66.0                         10.0
16  core_grid_00017                 1420                     1420                        533                         438                       449                  0.6               0.65             70.0                        10.0                  0.70                0.65              68.0                          8.5
17  core_grid_00018                 1403                     1403                        533                         421                       449                  0.6               0.65             70.0                        10.0                  0.70                0.65              68.0                         10.0
18  core_grid_00019                 1395                     1395                        533                         413                       449                  0.6               0.65             70.0                        10.0                  0.70                0.65              66.0                          8.5
19  core_grid_00020                 1391                     1391                        533                         409                       449                  0.6               0.65             70.0                        10.0                  0.70                0.65              66.0                         10.0

Saved outputs:
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\04_core_threshold_sweep_candidate_summary_20260704_214008.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\04_core_threshold_sweep_by_bucket_20260704_214008.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\04_core_threshold_sweep_by_tenor_20260704_214008.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\04_core_threshold_sweep_by_year_20260704_214008.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\04_core_threshold_sweep_candidate_pass_diagnostics_20260704_214008.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\04_core_threshold_sweep_selected_trade_panel_20260704_214008.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\04_core_threshold_sweep_validation_20260704_214008.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\04_core_threshold_sweep_manifest_20260704_214008.json

CELL 6 PASSED

In [9]:
# ======================================================================================
# Cell 7 — Front-focused expanded Core threshold grid design
# ======================================================================================
#
# Objective:
#   Create a second-pass expanded Core threshold grid focused on the Front bucket.
#
# Why:
#   Cell 6 showed that the first-pass grid improved P&L/day, but:
#     - 2026 remained weak.
#     - Top all-qualified candidates clustered near the Front forecast-vol-floor boundary.
#     - Front remains the weak bucket.
#
# This cell only designs and saves the expanded grid.
#
# Important:
#   This cell does NOT evaluate trades.
#   This cell does NOT run a threshold sweep.
#   This cell does NOT select final thresholds.
#
# Design choices:
#   - Back remains locked.
#   - Middle remains narrow.
#   - Front is expanded tighter.
#   - Within each bucket:
#         model_vrp_z_3m threshold == model_vrp_z_1y threshold
#   - Middle must sit between Front and Back for each parameter.
#   - Front is allowed to be tighter than Back for this expanded research grid.
#
# Not in scope:
#   - No trade evaluation.
#   - No final candidate ranking.
#   - No Secondary.
#   - No sizing changes.
#   - No production lock.
# ======================================================================================

from pathlib import Path
from datetime import datetime
import itertools
import json

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 220)
pd.set_option("display.width", 360)

# ======================================================================================
# 0. Fallback config if this cell is run independently
# ======================================================================================

if "PROJECT_ROOT" not in globals():
    PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

if "NEW_BRANCH" not in globals():
    NEW_BRANCH = "vrp_unified_fds_core_signal_threshold_research_v1"

if "OUT_PROCESSED_DIR" not in globals():
    OUT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / NEW_BRANCH
    OUT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

if "OUT_AUDIT_DIR" not in globals():
    OUT_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / NEW_BRANCH
    OUT_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

CELL7_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

if "LOCKED_MODEL_SPEC" not in globals():
    LOCKED_MODEL_SPEC = "unified_fds_no_min_return"

if "BUCKET_ORDER_MAP" not in globals():
    BUCKET_ORDER_MAP = {"Front": 1, "Middle": 2, "Back": 3}

if "LOCKED_BACK_CORE_THRESHOLDS" not in globals():
    LOCKED_BACK_CORE_THRESHOLDS = {
        "model_vrp_log": 0.70,
        "model_vrp_z_3m": 0.70,
        "model_vrp_z_1y": 0.70,
        "RSI14_max": 70.0,
        "forecast_vol_pct_min": 8.5,
    }

EXPANDED_GRID_FAMILY = "core_front_expanded_back_locked"

# ======================================================================================
# 1. Helper functions
# ======================================================================================

def latest_file(directory: Path, pattern: str, required: bool = True) -> Path | None:
    matches = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if matches:
        return matches[0]
    if required:
        raise FileNotFoundError(f"No file found in {directory} matching {pattern}")
    return None


def is_between_inclusive(x, a, b, tol=1e-12):
    lo = min(float(a), float(b)) - tol
    hi = max(float(a), float(b)) + tol
    return lo <= float(x) <= hi


def candidate_passes_design_constraints(row):
    """
    Design constraints only. No trade evaluation.

    Key difference versus Cell 5:
      - Front may be tighter than Back.
      - Middle must sit between Front and Back.
    """

    # Back fixed.
    back_fixed_ok = (
        row["Back_model_vrp_log"] == LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"]
        and row["Back_model_vrp_z"] == LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"]
        and row["Back_RSI14_max"] == LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"]
        and row["Back_forecast_vol_pct_min"] == LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"]
    )

    if not back_fixed_ok:
        return False

    # Within-bucket z equality is handled by construction, but require the bucket-level z
    # value to be a valid scalar.
    z_scalar_ok = (
        np.isfinite(row["Front_model_vrp_z"])
        and np.isfinite(row["Middle_model_vrp_z"])
        and np.isfinite(row["Back_model_vrp_z"])
    )

    if not z_scalar_ok:
        return False

    # Middle must sit between Front and Back.
    #
    # For log, z, and forecast-vol floor:
    #   Higher number is stricter.
    #
    # For RSI cap:
    #   Lower number is stricter.
    #
    # Numeric "between Front and Back" handles both cases.
    middle_between_log_ok = is_between_inclusive(
        row["Middle_model_vrp_log"],
        row["Front_model_vrp_log"],
        row["Back_model_vrp_log"],
    )

    middle_between_z_ok = is_between_inclusive(
        row["Middle_model_vrp_z"],
        row["Front_model_vrp_z"],
        row["Back_model_vrp_z"],
    )

    middle_between_rsi_ok = is_between_inclusive(
        row["Middle_RSI14_max"],
        row["Front_RSI14_max"],
        row["Back_RSI14_max"],
    )

    middle_between_fv_floor_ok = is_between_inclusive(
        row["Middle_forecast_vol_pct_min"],
        row["Front_forecast_vol_pct_min"],
        row["Back_forecast_vol_pct_min"],
    )

    return bool(
        middle_between_log_ok
        and middle_between_z_ok
        and middle_between_rsi_ok
        and middle_between_fv_floor_ok
    )


# ======================================================================================
# 2. Expanded candidate grid ranges
# ======================================================================================
#
# Front is expanded tighter.
# Middle stays narrow.
# Back stays locked.
#
# Note:
#   Front_model_vrp_log includes 0.75, which is tighter than locked Back 0.70.
#   This is intentional for Front-focused expansion.
# ======================================================================================

EXPANDED_GRID_RANGES = {
    "Front": {
        "model_vrp_log": [0.65, 0.70, 0.75],
        "model_vrp_z": [0.65, 0.70],
        "RSI14_max": [68.0, 66.0, 64.0],
        "forecast_vol_pct_min": [10.0, 11.5, 13.0, 14.5],
    },
    "Middle": {
        "model_vrp_log": [0.65, 0.70],
        "model_vrp_z": [0.70],
        "RSI14_max": [68.0, 66.0],
        "forecast_vol_pct_min": [8.5, 10.0],
    },
    "Back": {
        "model_vrp_log": [LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"]],
        "model_vrp_z": [LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"]],
        "RSI14_max": [LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"]],
        "forecast_vol_pct_min": [LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"]],
    },
}

# ======================================================================================
# 3. Optional: read first-pass sweep output for boundary-review context
# ======================================================================================

first_pass_summary_path = latest_file(
    OUT_AUDIT_DIR,
    "04_core_threshold_sweep_candidate_summary_*.csv",
    required=False,
)

first_pass_boundary_review = pd.DataFrame()

if first_pass_summary_path is not None:
    first_pass = pd.read_csv(first_pass_summary_path)

    first_pass_required_cols = [
        "candidate_id",
        "selection_universe",
        "trades",
        "avg_pnl_per_day",
        "profit_factor",
        "pnl_per_day_drawdown",
        "avg_pnl_per_day_2026",
        "Front_model_vrp_log",
        "Front_model_vrp_z",
        "Front_RSI14_max",
        "Front_forecast_vol_pct_min",
        "Middle_model_vrp_log",
        "Middle_model_vrp_z",
        "Middle_RSI14_max",
        "Middle_forecast_vol_pct_min",
    ]

    usable_cols = [c for c in first_pass_required_cols if c in first_pass.columns]

    review_frames = []

    for universe in [
        "all_qualified_trades",
        "one_trade_per_bucket_per_date_best_rank",
        "one_trade_per_date_best_rank",
    ]:
        u = first_pass[first_pass["selection_universe"].eq(universe)].copy()

        if not u.empty and "avg_pnl_per_day" in u.columns:
            review_frames.append(
                u.sort_values(
                    ["avg_pnl_per_day", "profit_factor", "trades"],
                    ascending=[False, False, False],
                )
                .head(25)
                .loc[:, usable_cols]
            )

    if review_frames:
        first_pass_boundary_review = pd.concat(review_frames, ignore_index=True)

# ======================================================================================
# 4. Build expanded wide candidate grid
# ======================================================================================

rows = []

product_iter = itertools.product(
    EXPANDED_GRID_RANGES["Front"]["model_vrp_log"],
    EXPANDED_GRID_RANGES["Front"]["model_vrp_z"],
    EXPANDED_GRID_RANGES["Front"]["RSI14_max"],
    EXPANDED_GRID_RANGES["Front"]["forecast_vol_pct_min"],

    EXPANDED_GRID_RANGES["Middle"]["model_vrp_log"],
    EXPANDED_GRID_RANGES["Middle"]["model_vrp_z"],
    EXPANDED_GRID_RANGES["Middle"]["RSI14_max"],
    EXPANDED_GRID_RANGES["Middle"]["forecast_vol_pct_min"],

    EXPANDED_GRID_RANGES["Back"]["model_vrp_log"],
    EXPANDED_GRID_RANGES["Back"]["model_vrp_z"],
    EXPANDED_GRID_RANGES["Back"]["RSI14_max"],
    EXPANDED_GRID_RANGES["Back"]["forecast_vol_pct_min"],
)

for vals in product_iter:
    (
        front_log,
        front_z,
        front_rsi,
        front_fv_floor,

        middle_log,
        middle_z,
        middle_rsi,
        middle_fv_floor,

        back_log,
        back_z,
        back_rsi,
        back_fv_floor,
    ) = vals

    row = {
        "Front_model_vrp_log": float(front_log),
        "Front_model_vrp_z": float(front_z),
        "Front_RSI14_max": float(front_rsi),
        "Front_forecast_vol_pct_min": float(front_fv_floor),

        "Middle_model_vrp_log": float(middle_log),
        "Middle_model_vrp_z": float(middle_z),
        "Middle_RSI14_max": float(middle_rsi),
        "Middle_forecast_vol_pct_min": float(middle_fv_floor),

        "Back_model_vrp_log": float(back_log),
        "Back_model_vrp_z": float(back_z),
        "Back_RSI14_max": float(back_rsi),
        "Back_forecast_vol_pct_min": float(back_fv_floor),
    }

    row["passes_design_constraints"] = candidate_passes_design_constraints(row)

    if row["passes_design_constraints"]:
        rows.append(row)

expanded_grid_wide = pd.DataFrame(rows).reset_index(drop=True)

if expanded_grid_wide.empty:
    raise RuntimeError("Expanded candidate grid is empty after applying design constraints.")

expanded_grid_wide.insert(
    0,
    "candidate_id",
    [f"core_front_expanded_{i:05d}" for i in range(1, len(expanded_grid_wide) + 1)],
)
expanded_grid_wide.insert(1, "candidate_family", EXPANDED_GRID_FAMILY)
expanded_grid_wide.insert(2, "locked_model_spec", LOCKED_MODEL_SPEC)

# Expand bucket-level z into explicit 3m and 1y thresholds.
for bucket in ["Front", "Middle", "Back"]:
    expanded_grid_wide[f"{bucket}_model_vrp_z_3m"] = expanded_grid_wide[f"{bucket}_model_vrp_z"]
    expanded_grid_wide[f"{bucket}_model_vrp_z_1y"] = expanded_grid_wide[f"{bucket}_model_vrp_z"]

# Diagnostics showing how Front compares to locked Back and Middle.
expanded_grid_wide["front_minus_back_log"] = (
    expanded_grid_wide["Front_model_vrp_log"] - expanded_grid_wide["Back_model_vrp_log"]
)
expanded_grid_wide["front_minus_back_z"] = (
    expanded_grid_wide["Front_model_vrp_z"] - expanded_grid_wide["Back_model_vrp_z"]
)
expanded_grid_wide["front_minus_back_RSI_cap"] = (
    expanded_grid_wide["Front_RSI14_max"] - expanded_grid_wide["Back_RSI14_max"]
)
expanded_grid_wide["front_minus_back_forecast_floor"] = (
    expanded_grid_wide["Front_forecast_vol_pct_min"] - expanded_grid_wide["Back_forecast_vol_pct_min"]
)

expanded_grid_wide["middle_between_front_back_log"] = expanded_grid_wide.apply(
    lambda r: is_between_inclusive(r["Middle_model_vrp_log"], r["Front_model_vrp_log"], r["Back_model_vrp_log"]),
    axis=1,
)
expanded_grid_wide["middle_between_front_back_z"] = expanded_grid_wide.apply(
    lambda r: is_between_inclusive(r["Middle_model_vrp_z"], r["Front_model_vrp_z"], r["Back_model_vrp_z"]),
    axis=1,
)
expanded_grid_wide["middle_between_front_back_RSI"] = expanded_grid_wide.apply(
    lambda r: is_between_inclusive(r["Middle_RSI14_max"], r["Front_RSI14_max"], r["Back_RSI14_max"]),
    axis=1,
)
expanded_grid_wide["middle_between_front_back_forecast_floor"] = expanded_grid_wide.apply(
    lambda r: is_between_inclusive(
        r["Middle_forecast_vol_pct_min"],
        r["Front_forecast_vol_pct_min"],
        r["Back_forecast_vol_pct_min"],
    ),
    axis=1,
)

expanded_grid_wide["front_log_tighter_than_back"] = (
    expanded_grid_wide["Front_model_vrp_log"] > expanded_grid_wide["Back_model_vrp_log"]
)
expanded_grid_wide["front_RSI_tighter_than_back"] = (
    expanded_grid_wide["Front_RSI14_max"] < expanded_grid_wide["Back_RSI14_max"]
)
expanded_grid_wide["front_forecast_floor_tighter_than_back"] = (
    expanded_grid_wide["Front_forecast_vol_pct_min"] > expanded_grid_wide["Back_forecast_vol_pct_min"]
)

# ======================================================================================
# 5. Build expanded long candidate grid
# ======================================================================================

long_rows = []

for _, row in expanded_grid_wide.iterrows():
    for bucket in ["Front", "Middle", "Back"]:
        long_rows.append({
            "candidate_id": row["candidate_id"],
            "candidate_family": row["candidate_family"],
            "locked_model_spec": row["locked_model_spec"],
            "tenor_bucket": bucket,
            "tenor_bucket_order": BUCKET_ORDER_MAP[bucket],
            "model_vrp_log": row[f"{bucket}_model_vrp_log"],
            "model_vrp_z": row[f"{bucket}_model_vrp_z"],
            "model_vrp_z_3m": row[f"{bucket}_model_vrp_z_3m"],
            "model_vrp_z_1y": row[f"{bucket}_model_vrp_z_1y"],
            "RSI14_max": row[f"{bucket}_RSI14_max"],
            "forecast_vol_pct_min": row[f"{bucket}_forecast_vol_pct_min"],
            "is_back_locked": bucket == "Back",
        })

expanded_grid_long = (
    pd.DataFrame(long_rows)
    .sort_values(["candidate_id", "tenor_bucket_order"])
    .reset_index(drop=True)
)

# ======================================================================================
# 6. Save outputs
# ======================================================================================

grid_wide_csv_path = OUT_AUDIT_DIR / f"05_core_front_expanded_candidate_grid_wide_{CELL7_TIMESTAMP}.csv"
grid_wide_parquet_path = OUT_PROCESSED_DIR / f"05_core_front_expanded_candidate_grid_wide_{CELL7_TIMESTAMP}.parquet"

grid_long_csv_path = OUT_AUDIT_DIR / f"05_core_front_expanded_candidate_grid_long_{CELL7_TIMESTAMP}.csv"
grid_long_parquet_path = OUT_PROCESSED_DIR / f"05_core_front_expanded_candidate_grid_long_{CELL7_TIMESTAMP}.parquet"

grid_ranges_path = OUT_AUDIT_DIR / f"05_core_front_expanded_candidate_grid_ranges_{CELL7_TIMESTAMP}.json"
first_pass_review_path = OUT_AUDIT_DIR / f"05_core_front_expanded_first_pass_boundary_review_{CELL7_TIMESTAMP}.csv"
validation_path = OUT_AUDIT_DIR / f"05_core_front_expanded_candidate_grid_validation_{CELL7_TIMESTAMP}.csv"
manifest_path = OUT_AUDIT_DIR / f"05_core_front_expanded_candidate_grid_manifest_{CELL7_TIMESTAMP}.json"

expanded_grid_wide.to_csv(grid_wide_csv_path, index=False)
expanded_grid_wide.to_parquet(grid_wide_parquet_path, index=False)

expanded_grid_long.to_csv(grid_long_csv_path, index=False)
expanded_grid_long.to_parquet(grid_long_parquet_path, index=False)

with open(grid_ranges_path, "w", encoding="utf-8") as f:
    json.dump(EXPANDED_GRID_RANGES, f, indent=2, default=str)

if not first_pass_boundary_review.empty:
    first_pass_boundary_review.to_csv(first_pass_review_path, index=False)
else:
    pd.DataFrame().to_csv(first_pass_review_path, index=False)

# ======================================================================================
# 7. Validation
# ======================================================================================

validation_rows = []

def add_validation(check, status, detail):
    validation_rows.append({
        "check": check,
        "status": status,
        "detail": detail,
    })

# Candidate count.
add_validation(
    "expanded_candidate_grid_non_empty",
    "PASS" if len(expanded_grid_wide) > 0 else "FAIL",
    f"candidate_count={len(expanded_grid_wide):,}",
)

# Long grid row count.
add_validation(
    "long_grid_has_three_rows_per_candidate",
    "PASS" if len(expanded_grid_long) == 3 * len(expanded_grid_wide) else "FAIL",
    f"long_rows={len(expanded_grid_long):,}; expected={3 * len(expanded_grid_wide):,}",
)

# Back fixed.
back_bad = expanded_grid_wide[
    (expanded_grid_wide["Back_model_vrp_log"] != LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"])
    | (expanded_grid_wide["Back_model_vrp_z"] != LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"])
    | (expanded_grid_wide["Back_RSI14_max"] != LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"])
    | (expanded_grid_wide["Back_forecast_vol_pct_min"] != LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"])
]

add_validation(
    "back_thresholds_locked",
    "PASS" if back_bad.empty else "FAIL",
    f"bad_rows={len(back_bad):,}; locked_back={LOCKED_BACK_CORE_THRESHOLDS}",
)

# Z equality within bucket.
z_equality_bad = expanded_grid_wide[
    (expanded_grid_wide["Front_model_vrp_z_3m"] != expanded_grid_wide["Front_model_vrp_z_1y"])
    | (expanded_grid_wide["Middle_model_vrp_z_3m"] != expanded_grid_wide["Middle_model_vrp_z_1y"])
    | (expanded_grid_wide["Back_model_vrp_z_3m"] != expanded_grid_wide["Back_model_vrp_z_1y"])
]

add_validation(
    "z_3m_equals_z_1y_within_each_bucket",
    "PASS" if z_equality_bad.empty else "FAIL",
    f"bad_rows={len(z_equality_bad):,}",
)

# Middle between Front and Back.
middle_between_bad = expanded_grid_wide[
    ~(
        expanded_grid_wide["middle_between_front_back_log"]
        & expanded_grid_wide["middle_between_front_back_z"]
        & expanded_grid_wide["middle_between_front_back_RSI"]
        & expanded_grid_wide["middle_between_front_back_forecast_floor"]
    )
]

add_validation(
    "middle_between_front_and_back_all_parameters",
    "PASS" if middle_between_bad.empty else "FAIL",
    f"bad_rows={len(middle_between_bad):,}",
)

# Front-focused expansion should include some candidates tighter than Back.
front_log_tighter_count = int(expanded_grid_wide["front_log_tighter_than_back"].sum())
front_RSI_tighter_count = int(expanded_grid_wide["front_RSI_tighter_than_back"].sum())
front_fv_tighter_count = int(expanded_grid_wide["front_forecast_floor_tighter_than_back"].sum())

add_validation(
    "front_log_can_be_tighter_than_back",
    "PASS" if front_log_tighter_count > 0 else "WARN",
    f"front_log_tighter_candidates={front_log_tighter_count:,}",
)

add_validation(
    "front_RSI_can_be_tighter_than_back",
    "PASS" if front_RSI_tighter_count > 0 else "WARN",
    f"front_RSI_tighter_candidates={front_RSI_tighter_count:,}",
)

add_validation(
    "front_forecast_floor_can_be_tighter_than_back",
    "PASS" if front_fv_tighter_count > 0 else "WARN",
    f"front_forecast_floor_tighter_candidates={front_fv_tighter_count:,}",
)

# First-pass review loaded if available.
add_validation(
    "first_pass_sweep_summary_loaded_for_context",
    "PASS" if first_pass_summary_path is not None else "WARN",
    f"path={first_pass_summary_path}",
)

# No trade-evaluation metric columns in grid itself.
trade_metric_cols = [
    "trades",
    "win_rate",
    "total_pnl",
    "avg_pnl",
    "avg_pnl_per_day",
    "profit_factor",
    "worst_trade",
    "pnl_per_day_drawdown",
]

unexpected_trade_cols = [c for c in trade_metric_cols if c in expanded_grid_wide.columns]

add_validation(
    "no_trade_evaluation_performed",
    "PASS" if not unexpected_trade_cols else "FAIL",
    f"unexpected_trade_metric_cols={unexpected_trade_cols}",
)

add_validation(
    "no_secondary",
    "PASS",
    "Expanded grid is Core only.",
)

add_validation(
    "no_sizing_changes",
    "PASS",
    "Expanded grid contains thresholds only, no sizing fields.",
)

add_validation(
    "no_production_lock",
    "PASS",
    "No production threshold lock performed.",
)

validation = pd.DataFrame(validation_rows)
validation.to_csv(validation_path, index=False)

failures = validation[validation["status"] == "FAIL"]

manifest = {
    "notebook": "07_unified_fds_core_signal_threshold_research_v1.ipynb",
    "cell": "Cell 7 — Front-focused expanded Core threshold grid design",
    "timestamp": CELL7_TIMESTAMP,
    "locked_model_spec": LOCKED_MODEL_SPEC,
    "candidate_family": EXPANDED_GRID_FAMILY,
    "candidate_count": int(len(expanded_grid_wide)),
    "long_grid_rows": int(len(expanded_grid_long)),
    "grid_wide_csv_path": str(grid_wide_csv_path),
    "grid_wide_parquet_path": str(grid_wide_parquet_path),
    "grid_long_csv_path": str(grid_long_csv_path),
    "grid_long_parquet_path": str(grid_long_parquet_path),
    "grid_ranges_path": str(grid_ranges_path),
    "first_pass_summary_path": str(first_pass_summary_path) if first_pass_summary_path is not None else None,
    "first_pass_review_path": str(first_pass_review_path),
    "validation_path": str(validation_path),
    "expanded_grid_ranges": EXPANDED_GRID_RANGES,
    "locked_back_core_thresholds": LOCKED_BACK_CORE_THRESHOLDS,
    "hard_constraints": [
        "Back Core thresholds fixed.",
        "Within each bucket, model_vrp_z_3m threshold equals model_vrp_z_1y threshold.",
        "Middle must sit between Front and Back for model_vrp_log.",
        "Middle must sit between Front and Back for model_vrp_z.",
        "Middle must sit between Front and Back for RSI14_max.",
        "Middle must sit between Front and Back for forecast_vol_pct_min.",
        "Front may be tighter than Back in the expanded Front-focused grid.",
        "No trade evaluation performed.",
        "No threshold sweep performed.",
        "No Secondary.",
        "No sizing changes.",
        "No production lock.",
    ],
    "notes": [
        "This cell defines the expanded threshold candidates only.",
        "Cell 8 should sweep this expanded grid.",
        "P&L/day remains the primary cross-tenor trade-quality metric for Cell 8.",
        "If expanded winners still cluster at boundaries, do not lock; expand again or reconsider selection rules.",
    ],
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2, default=str)

if not failures.empty:
    display(validation)
    raise RuntimeError("Cell 7 validation failed. Review validation output above.")

# ======================================================================================
# 8. Display concise review
# ======================================================================================

print("=" * 100)
print("Cell 7 — Front-focused expanded Core threshold grid design")
print("=" * 100)
print(f"Locked model spec:                  {LOCKED_MODEL_SPEC}")
print(f"Candidate family:                   {EXPANDED_GRID_FAMILY}")
print(f"Expanded candidate count:           {len(expanded_grid_wide):,}")
print(f"Long grid rows:                     {len(expanded_grid_long):,}")
print(f"Back thresholds locked:             True")
print(f"Z 3m == Z 1y within bucket:         True")
print(f"Middle between Front and Back:      True")
print(f"Front can be tighter than Back:     True")
print(f"No trade evaluation:                True")
print(f"No threshold sweep:                 True")
print(f"No Secondary:                       True")
print(f"No sizing changes:                  True")
print(f"No production lock:                 True")

print()
print("Saved outputs:")
for p in [
    grid_wide_csv_path,
    grid_wide_parquet_path,
    grid_long_csv_path,
    grid_long_parquet_path,
    grid_ranges_path,
    first_pass_review_path,
    validation_path,
    manifest_path,
]:
    print(f"  {p}")

print()
print("Validation:")
display(validation)

print()
print("Expanded grid ranges:")
display(
    pd.DataFrame(
        [
            {
                "bucket": bucket,
                "model_vrp_log": EXPANDED_GRID_RANGES[bucket]["model_vrp_log"],
                "model_vrp_z_applied_to_3m_and_1y": EXPANDED_GRID_RANGES[bucket]["model_vrp_z"],
                "RSI14_max": EXPANDED_GRID_RANGES[bucket]["RSI14_max"],
                "forecast_vol_pct_min": EXPANDED_GRID_RANGES[bucket]["forecast_vol_pct_min"],
            }
            for bucket in ["Front", "Middle", "Back"]
        ]
    )
)

print()
print("Candidate counts by Front parameters:")
display(
    expanded_grid_wide
    .groupby(
        [
            "Front_model_vrp_log",
            "Front_model_vrp_z",
            "Front_RSI14_max",
            "Front_forecast_vol_pct_min",
        ],
        as_index=False,
    )
    .agg(candidates=("candidate_id", "nunique"))
    .sort_values(
        [
            "Front_model_vrp_log",
            "Front_model_vrp_z",
            "Front_RSI14_max",
            "Front_forecast_vol_pct_min",
        ]
    )
)

print()
print("Candidate counts by Middle parameters:")
display(
    expanded_grid_wide
    .groupby(
        [
            "Middle_model_vrp_log",
            "Middle_model_vrp_z",
            "Middle_RSI14_max",
            "Middle_forecast_vol_pct_min",
        ],
        as_index=False,
    )
    .agg(candidates=("candidate_id", "nunique"))
    .sort_values(
        [
            "Middle_model_vrp_log",
            "Middle_model_vrp_z",
            "Middle_RSI14_max",
            "Middle_forecast_vol_pct_min",
        ]
    )
)

if not first_pass_boundary_review.empty:
    print()
    print("First-pass top-candidate review used as context:")
    display(first_pass_boundary_review.head(50))

print()
print("Expanded wide grid sample:")
display(expanded_grid_wide.head(25))

print()
print("Expanded long grid sample:")
display(expanded_grid_long.head(30))

print("\nCELL 7 PASSED")

====================================================================================================
Cell 7 — Front-focused expanded Core threshold grid design
====================================================================================================
Locked model spec:                  unified_fds_no_min_return
Candidate family:                   core_front_expanded_back_locked
Expanded candidate count:           320
Long grid rows:                     960
Back thresholds locked:             True
Z 3m == Z 1y within bucket:         True
Middle between Front and Back:      True
Front can be tighter than Back:     True
No trade evaluation:                True
No threshold sweep:                 True
No Secondary:                       True
No sizing changes:                  True
No production lock:                 True

Saved outputs:
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\05_core_front_expanded_candidate_grid_wide_20260704_215243.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\05_core_front_expanded_candidate_grid_wide_20260704_215243.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\05_core_front_expanded_candidate_grid_long_20260704_215243.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\05_core_front_expanded_candidate_grid_long_20260704_215243.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\05_core_front_expanded_candidate_grid_ranges_20260704_215243.json
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\05_core_front_expanded_first_pass_boundary_review_20260704_215243.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\05_core_front_expanded_candidate_grid_validation_20260704_215243.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\05_core_front_expanded_candidate_grid_manifest_20260704_215243.json

Validation:

                                            check status                                             detail
0               expanded_candidate_grid_non_empty   PASS                                candidate_count=320
1          long_grid_has_three_rows_per_candidate   PASS                        long_rows=960; expected=960
2                          back_thresholds_locked   PASS  bad_rows=0; locked_back={'model_vrp_log': 0.7,...
3             z_3m_equals_z_1y_within_each_bucket   PASS                                         bad_rows=0
4    middle_between_front_and_back_all_parameters   PASS                                         bad_rows=0
5              front_log_can_be_tighter_than_back   PASS                    front_log_tighter_candidates=80
6              front_RSI_can_be_tighter_than_back   PASS                   front_RSI_tighter_candidates=320
7   front_forecast_floor_can_be_tighter_than_back   PASS        front_forecast_floor_tighter_candidates=320
8     first_pass_sweep_summary_loaded_for_context   PASS  path=C:\Users\patri\vrp_project\data\audit\vrp...
9                   no_trade_evaluation_performed   PASS                    unexpected_trade_metric_cols=[]
10                                   no_secondary   PASS                        Expanded grid is Core only.
11                              no_sizing_changes   PASS  Expanded grid contains thresholds only, no siz...
12                             no_production_lock   PASS            No production threshold lock performed.

Expanded grid ranges:

   bucket      model_vrp_log model_vrp_z_applied_to_3m_and_1y           RSI14_max      forecast_vol_pct_min
0   Front  [0.65, 0.7, 0.75]                      [0.65, 0.7]  [68.0, 66.0, 64.0]  [10.0, 11.5, 13.0, 14.5]
1  Middle        [0.65, 0.7]                            [0.7]        [68.0, 66.0]               [8.5, 10.0]
2    Back              [0.7]                            [0.7]              [70.0]                     [8.5]

Candidate counts by Front parameters:

    Front_model_vrp_log  Front_model_vrp_z  Front_RSI14_max  Front_forecast_vol_pct_min  candidates
0                  0.65               0.65             64.0                        10.0           8
1                  0.65               0.65             64.0                        11.5           8
2                  0.65               0.65             64.0                        13.0           8
3                  0.65               0.65             64.0                        14.5           8
4                  0.65               0.65             66.0                        10.0           8
..                  ...                ...              ...                         ...         ...
67                 0.75               0.70             66.0                        14.5           4
68                 0.75               0.70             68.0                        10.0           2
69                 0.75               0.70             68.0                        11.5           2
70                 0.75               0.70             68.0                        13.0           2
71                 0.75               0.70             68.0                        14.5           2

[72 rows x 5 columns]

Candidate counts by Middle parameters:

   Middle_model_vrp_log  Middle_model_vrp_z  Middle_RSI14_max  Middle_forecast_vol_pct_min  candidates
0                  0.65                 0.7              66.0                          8.5          16
1                  0.65                 0.7              66.0                         10.0          16
2                  0.65                 0.7              68.0                          8.5          24
3                  0.65                 0.7              68.0                         10.0          24
4                  0.70                 0.7              66.0                          8.5          48
5                  0.70                 0.7              66.0                         10.0          48
6                  0.70                 0.7              68.0                          8.5          72
7                  0.70                 0.7              68.0                         10.0          72

First-pass top-candidate review used as context:

       candidate_id                       selection_universe  trades  avg_pnl_per_day  profit_factor  pnl_per_day_drawdown  avg_pnl_per_day_2026  Front_model_vrp_log  Front_model_vrp_z  Front_RSI14_max  Front_forecast_vol_pct_min  Middle_model_vrp_log  Middle_model_vrp_z  Middle_RSI14_max  Middle_forecast_vol_pct_min
0   core_grid_00244                     all_qualified_trades    1328       536.088751       3.498046        -137635.647031           -134.167381                 0.65               0.65             66.0                        11.5                  0.65                0.65              66.0                         10.0
1   core_grid_00218                     all_qualified_trades    1331       535.923163       3.494912        -137635.647031           -124.329741                 0.65               0.65             68.0                        11.5                  0.65                0.65              66.0                         10.0
2   core_grid_00298                     all_qualified_trades    1281       535.634041       3.526129        -136371.670193           -138.916408                 0.65               0.70             66.0                        11.5                  0.65                0.70              66.0                         10.0
3   core_grid_00246                     all_qualified_trades    1310       535.502701       3.487757        -137635.647031           -138.065332                 0.65               0.65             66.0                        11.5                  0.65                0.70              66.0                         10.0
4   core_grid_00243                     all_qualified_trades    1332       535.481723       3.500962        -137635.647031           -134.167381                 0.65               0.65             66.0                        11.5                  0.65                0.65              66.0                          8.5
5   core_grid_00286                     all_qualified_trades    1284       535.463455       3.522827        -136371.670193           -128.920829                 0.65               0.70             68.0                        11.5                  0.65                0.70              66.0                         10.0
6   core_grid_00222                     all_qualified_trades    1313       535.336183       3.484612        -137635.647031           -128.156874                 0.65               0.65             68.0                        11.5                  0.65                0.70              66.0                         10.0
7   core_grid_00217                     all_qualified_trades    1335       535.317995       3.497824        -137635.647031           -124.329741                 0.65               0.65             68.0                        11.5                  0.65                0.65              66.0                          8.5
8   core_grid_00336                     all_qualified_trades    1281       535.238847       3.450037        -137635.647031           -131.597216                 0.70               0.65             68.0                        11.5                  0.70                0.65              66.0                         10.0
9   core_grid_00297                     all_qualified_trades    1285       535.006225       3.529135        -136371.670193           -138.916408                 0.65               0.70             66.0                        11.5                  0.65                0.70              66.0                          8.5
10  core_grid_00245                     all_qualified_trades    1314       534.889142       3.490706        -137635.647031           -138.065332                 0.65               0.65             66.0                        11.5                  0.65                0.70              66.0                          8.5
11  core_grid_00340                     all_qualified_trades    1266       534.881160       3.446064        -137635.647031           -131.597216                 0.70               0.65             68.0                        11.5                  0.70                0.70              66.0                         10.0
12  core_grid_00285                     all_qualified_trades    1288       534.837631       3.525829        -136371.670193           -128.920829                 0.65               0.70             68.0                        11.5                  0.65                0.70              66.0                          8.5
13  core_grid_00221                     all_qualified_trades    1317       534.724527       3.487557        -137635.647031           -128.156874                 0.65               0.65             68.0                        11.5                  0.65                0.70              66.0                          8.5
14  core_grid_00216                     all_qualified_trades    1343       534.652530       3.501759        -137635.647031           -106.266873                 0.65               0.65             68.0                        11.5                  0.65                0.65              68.0                         10.0
15  core_grid_00335                     all_qualified_trades    1285       534.612261       3.453012        -137635.647031           -131.597216                 0.70               0.65             68.0                        11.5                  0.70                0.65              66.0                          8.5
16  core_grid_00248                     all_qualified_trades    1302       534.533052       3.445144        -137635.647031           -141.573923                 0.65               0.65             66.0                        11.5                  0.70                0.65              66.0                         10.0
17  core_grid_00226                     all_qualified_trades    1305       534.367742       3.442110        -137635.647031           -131.597216                 0.65               0.65             68.0                        11.5                  0.70                0.65              66.0                         10.0
18  core_grid_00348                     all_qualified_trades    1279       534.362695       3.446384        -137635.647031           -141.573923                 0.70               0.65             66.0                        11.5                  0.70                0.65              66.0                         10.0
19  core_grid_00300                     all_qualified_trades    1258       534.276063       3.478351        -136371.670193           -142.457246                 0.65               0.70             66.0                        11.5                  0.70                0.70              66.0                         10.0
20  core_grid_00339                     all_qualified_trades    1270       534.248300       3.449069        -137635.647031           -131.597216                 0.70               0.65             68.0                        11.5                  0.70                0.70              66.0                          8.5
21  core_grid_00250                     all_qualified_trades    1287       534.172976       3.441170        -137635.647031           -141.573923                 0.65               0.65             66.0                        11.5                  0.70                0.70              66.0                         10.0
22  core_grid_00284                     all_qualified_trades    1296       534.150997       3.529805        -136371.670193           -110.534896                 0.65               0.70             68.0                        11.5                  0.65                0.70              68.0                         10.0
23  core_grid_00290                     all_qualified_trades    1261       534.105596       3.475144        -136371.670193           -132.392247                 0.65               0.70             68.0                        11.5                  0.70                0.70              66.0                         10.0
24  core_grid_00220                     all_qualified_trades    1325       534.053604       3.491564        -137635.647031           -109.933120                 0.65               0.65             68.0                        11.5                  0.65                0.70              68.0                         10.0
25  core_grid_00329  one_trade_per_bucket_per_date_best_rank     492       478.215063       3.408855         -54837.874446           -154.274083                 0.70               0.65             68.0                        10.0                  0.70                0.70              68.0                          8.5
26  core_grid_00330  one_trade_per_bucket_per_date_best_rank     488       478.046934       3.391258         -54837.874446           -154.274083                 0.70               0.65             68.0                        10.0                  0.70                0.70              68.0                         10.0
27  core_grid_00325  one_trade_per_bucket_per_date_best_rank     501       477.255445       3.389343         -54837.874446           -154.274083                 0.70               0.65             68.0                        10.0                  0.70                0.65              68.0                          8.5
28  core_grid_00331  one_trade_per_bucket_per_date_best_rank     484       477.160908       3.367859         -54837.874446           -173.190990                 0.70               0.65             68.0                        10.0                  0.70                0.70              66.0                          8.5
29  core_grid_00332  one_trade_per_bucket_per_date_best_rank     484       477.154319       3.369652         -54837.874446           -173.190990                 0.70               0.65             68.0                        10.0                  0.70                0.70              66.0                         10.0
30  core_grid_00203  one_trade_per_bucket_per_date_best_rank     509       476.858038       3.424063         -54837.874446           -144.716233                 0.65               0.65             68.0                        10.0                  0.65                0.70              68.0                          8.5
31  core_grid_00204  one_trade_per_bucket_per_date_best_rank     505       476.684820       3.406736         -54837.874446           -144.716233                 0.65               0.65             68.0                        10.0                  0.65                0.70              68.0                         10.0
32  core_grid_00326  one_trade_per_bucket_per_date_best_rank     496       476.633571       3.365880         -54837.874446           -154.274083                 0.70               0.65             68.0                        10.0                  0.70                0.65              68.0                         10.0
33  core_grid_00199  one_trade_per_bucket_per_date_best_rank     518       475.953491       3.404529         -54837.874446           -144.716233                 0.65               0.65             68.0                        10.0                  0.65                0.65              68.0                          8.5
34  core_grid_00211  one_trade_per_bucket_per_date_best_rank     502       475.946264       3.390586         -54837.874446           -154.274083                 0.65               0.65             68.0                        10.0                  0.70                0.70              68.0                          8.5
35  core_grid_00205  one_trade_per_bucket_per_date_best_rank     501       475.817983       3.383696         -54837.874446           -163.210556                 0.65               0.65             68.0                        10.0                  0.65                0.70              66.0                          8.5
36  core_grid_00206  one_trade_per_bucket_per_date_best_rank     501       475.811618       3.385462         -54837.874446           -163.210556                 0.65               0.65             68.0                        10.0                  0.65                0.70              66.0                         10.0
37  core_grid_00212  one_trade_per_bucket_per_date_best_rank     498       475.763288       3.373245         -54837.874446           -154.274083                 0.65               0.65             68.0                        10.0                  0.70                0.70              68.0                         10.0
38  core_grid_00327  one_trade_per_bucket_per_date_best_rank     492       475.750461       3.342974         -54837.874446           -173.190990                 0.70               0.65             68.0                        10.0                  0.70                0.65              66.0                          8.5
39  core_grid_00328  one_trade_per_bucket_per_date_best_rank     492       475.743979       3.344729         -54837.874446           -173.190990                 0.70               0.65             68.0                        10.0                  0.70                0.65              66.0                         10.0
40  core_grid_00200  one_trade_per_bucket_per_date_best_rank     513       475.339535       3.381418         -54837.874446           -144.716233                 0.65               0.65             68.0                        10.0                  0.65                0.65              68.0                         10.0
41  core_grid_00207  one_trade_per_bucket_per_date_best_rank     511       475.045385       3.371733         -54837.874446           -154.274083                 0.65               0.65             68.0                        10.0                  0.70                0.65              68.0                          8.5
42  core_grid_00213  one_trade_per_bucket_per_date_best_rank     494       474.876707       3.350188         -54837.874446           -173.190990                 0.65               0.65             68.0                        10.0                  0.70                0.70              66.0                          8.5
43  core_grid_00214  one_trade_per_bucket_per_date_best_rank     494       474.870251       3.351954         -54837.874446           -173.190990                 0.65               0.65             68.0                        10.0                  0.70                0.70              66.0                         10.0
44  core_grid_00237  one_trade_per_bucket_per_date_best_rank     495       474.849411       3.380011         -54837.874446           -201.159250                 0.65               0.65             66.0                        10.0                  0.65                0.70              66.0                          8.5
45  core_grid_00238  one_trade_per_bucket_per_date_best_rank     495       474.842968       3.381785         -54837.874446           -201.159250                 0.65               0.65             66.0                        10.0                  0.65                0.70              66.0                         10.0
46  core_grid_00201  one_trade_per_bucket_per_date_best_rank     509       474.475751       3.358857         -54837.874446           -163.210556                 0.65               0.65             68.0                        10.0                  0.65                0.65              66.0                          8.5
47  core_grid_00202  one_trade_per_bucket_per_date_best_rank     509       474.469485       3.360586         -54837.874446           -163.210556                 0.65               0.65             68.0                        10.0                  0.65                0.65              66.0                         10.0
48  core_grid_00208  one_trade_per_bucket_per_date_best_rank     506       474.413962       3.348604         -54837.874446           -154.274083                 0.65               0.65             68.0                        10.0                  0.70                0.65              68.0                         10.0
49  core_grid_00241  one_trade_per_bucket_per_date_best_rank     488       473.882668       3.346326         -54837.874446           -211.929103                 0.65               0.65             66.0                        10.0                  0.70                0.70              66.0                          8.5

Expanded wide grid sample:

,candidate_id,candidate_family,locked_model_spec,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Back_RSI14_max,Back_forecast_vol_pct_min,passes_design_constraints,Front_model_vrp_z_3m,Front_model_vrp_z_1y,Middle_model_vrp_z_3m,Middle_model_vrp_z_1y,Back_model_vrp_z_3m,Back_model_vrp_z_1y,front_minus_back_log,front_minus_back_z,front_minus_back_RSI_cap,front_minus_back_forecast_floor,middle_between_front_back_log,middle_between_front_back_z,middle_between_front_back_RSI,middle_between_front_back_forecast_floor,front_log_tighter_than_back,front_RSI_tighter_than_back,front_forecast_floor_tighter_than_back
0,core_front_expanded_00001,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,10.0,0.65,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,1.5,True,True,True,True,False,True,True
1,core_front_expanded_00002,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,10.0,0.65,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,1.5,True,True,True,True,False,True,True
2,core_front_expanded_00003,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,10.0,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,1.5,True,True,True,True,False,True,True
3,core_front_expanded_00004,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,10.0,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,1.5,True,True,True,True,False,True,True
4,core_front_expanded_00005,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,11.5,0.65,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,3.0,True,True,True,True,False,True,True
5,core_front_expanded_00006,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,11.5,0.65,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,3.0,True,True,True,True,False,True,True
6,core_front_expanded_00007,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,11.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,3.0,True,True,True,True,False,True,True
7,core_front_expanded_00008,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,11.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,3.0,True,True,True,True,False,True,True
8,core_front_expanded_00009,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,13.0,0.65,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,4.5,True,True,True,True,False,True,True
9,core_front_expanded_00010,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,13.0,0.65,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,4.5,True,True,True,True,False,True,True
10,core_front_expanded_00011,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,13.0,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,4.5,True,True,True,True,False,True,True
11,core_front_expanded_00012,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,13.0,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,4.5,True,True,True,True,False,True,True
12,core_front_expanded_00013,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,14.5,0.65,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,6.0,True,True,True,True,False,True,True
13,core_front_expanded_00014,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,6.0,True,True,True,True,False,True,True
14,core_front_expanded_00015,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,6.0,True,True,True,True,False,True,True
15,core_front_expanded_00016,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-2.0,6.0,True,True,True,True,False,True,True
16,core_front_expanded_00017,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,66.0,10.0,0.65,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-4.0,1.5,True,True,True,True,False,True,True
17,core_front_expanded_00018,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,66.0,10.0,0.65,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-4.0,1.5,True,True,True,True,False,True,True
18,core_front_expanded_00019,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,66.0,10.0,0.65,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-4.0,1.5,True,True,True,True,False,True,True
19,core_front_expanded_00020,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,66.0,10.0,0.65,0.7,66.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-4.0,1.5,True,True,True,True,False,True,True
20,core_front_expanded_00021,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,66.0,10.0,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-4.0,1.5,True,True,True,True,False,True,True
21,core_front_expanded_00022,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,66.0,10.0,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-4.0,1.5,True,True,True,True,False,True,True
22,core_front_expanded_00023,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,66.0,10.0,0.70,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-4.0,1.5,True,True,True,True,False,True,True
23,core_front_expanded_00024,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,66.0,10.0,0.70,0.7,66.0,10.0,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-4.0,1.5,True,True,True,True,False,True,True
24,core_front_expanded_00025,core_front_expanded_back_locked,unified_fds_no_min_return,0.65,0.65,66.0,11.5,0.65,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,0.65,0.65,0.7,0.7,0.7,0.7,-0.05,-0.05,-4.0,3.0,True,True,True,True,False,True,True

Expanded long grid sample:

                 candidate_id                 candidate_family          locked_model_spec tenor_bucket  tenor_bucket_order  model_vrp_log  model_vrp_z  model_vrp_z_3m  model_vrp_z_1y  RSI14_max  forecast_vol_pct_min  is_back_locked
0   core_front_expanded_00001  core_front_expanded_back_locked  unified_fds_no_min_return        Front                   1           0.65         0.65            0.65            0.65       68.0                  10.0           False
1   core_front_expanded_00001  core_front_expanded_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.70            0.70            0.70       68.0                   8.5           False
2   core_front_expanded_00001  core_front_expanded_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
3   core_front_expanded_00002  core_front_expanded_back_locked  unified_fds_no_min_return        Front                   1           0.65         0.65            0.65            0.65       68.0                  10.0           False
4   core_front_expanded_00002  core_front_expanded_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.70            0.70            0.70       68.0                  10.0           False
5   core_front_expanded_00002  core_front_expanded_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
6   core_front_expanded_00003  core_front_expanded_back_locked  unified_fds_no_min_return        Front                   1           0.65         0.65            0.65            0.65       68.0                  10.0           False
7   core_front_expanded_00003  core_front_expanded_back_locked  unified_fds_no_min_return       Middle                   2           0.70         0.70            0.70            0.70       68.0                   8.5           False
8   core_front_expanded_00003  core_front_expanded_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
9   core_front_expanded_00004  core_front_expanded_back_locked  unified_fds_no_min_return        Front                   1           0.65         0.65            0.65            0.65       68.0                  10.0           False
10  core_front_expanded_00004  core_front_expanded_back_locked  unified_fds_no_min_return       Middle                   2           0.70         0.70            0.70            0.70       68.0                  10.0           False
11  core_front_expanded_00004  core_front_expanded_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
12  core_front_expanded_00005  core_front_expanded_back_locked  unified_fds_no_min_return        Front                   1           0.65         0.65            0.65            0.65       68.0                  11.5           False
13  core_front_expanded_00005  core_front_expanded_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.70            0.70            0.70       68.0                   8.5           False
14  core_front_expanded_00005  core_front_expanded_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
15  core_front_expanded_00006  core_front_expanded_back_locked  unified_fds_no_min_return        Front                   1           0.65         0.65            0.65            0.65       68.0                  11.5           False
16  core_front_expanded_00006  core_front_expanded_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.70            0.70            0.70       68.0                  10.0           False
17  core_front_expanded_00006  core_front_expanded_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
18  core_front_expanded_00007  core_front_expanded_back_locked  unified_fds_no_min_return        Front                   1           0.65         0.65            0.65            0.65       68.0                  11.5           False
19  core_front_expanded_00007  core_front_expanded_back_locked  unified_fds_no_min_return       Middle                   2           0.70         0.70            0.70            0.70       68.0                   8.5           False
20  core_front_expanded_00007  core_front_expanded_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
21  core_front_expanded_00008  core_front_expanded_back_locked  unified_fds_no_min_return        Front                   1           0.65         0.65            0.65            0.65       68.0                  11.5           False
22  core_front_expanded_00008  core_front_expanded_back_locked  unified_fds_no_min_return       Middle                   2           0.70         0.70            0.70            0.70       68.0                  10.0           False
23  core_front_expanded_00008  core_front_expanded_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
24  core_front_expanded_00009  core_front_expanded_back_locked  unified_fds_no_min_return        Front                   1           0.65         0.65            0.65            0.65       68.0                  13.0           False
25  core_front_expanded_00009  core_front_expanded_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.70            0.70            0.70       68.0                   8.5           False
26  core_front_expanded_00009  core_front_expanded_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True
27  core_front_expanded_00010  core_front_expanded_back_locked  unified_fds_no_min_return        Front                   1           0.65         0.65            0.65            0.65       68.0                  13.0           False
28  core_front_expanded_00010  core_front_expanded_back_locked  unified_fds_no_min_return       Middle                   2           0.65         0.70            0.70            0.70       68.0                  10.0           False
29  core_front_expanded_00010  core_front_expanded_back_locked  unified_fds_no_min_return         Back                   3           0.70         0.70            0.70            0.70       70.0                   8.5            True

CELL 7 PASSED

In [10]:
# ======================================================================================
# Cell 8 — Front-focused expanded Core threshold sweep using P&L/day
# ======================================================================================
#
# Objective:
#   Evaluate the Cell 7 Front-focused expanded Core threshold grid against the clean
#   locked signal panel.
#
# Inputs:
#   01_unified_fds_signal_base_panel_*.parquet
#   05_core_front_expanded_candidate_grid_wide_*.parquet
#   05_core_front_expanded_candidate_grid_long_*.parquet
#
# Outputs:
#   06_core_front_expanded_sweep_candidate_summary_*.csv
#   06_core_front_expanded_sweep_by_bucket_*.csv
#   06_core_front_expanded_sweep_by_tenor_*.csv
#   06_core_front_expanded_sweep_by_year_*.csv
#   06_core_front_expanded_sweep_candidate_pass_diagnostics_*.csv
#   06_core_front_expanded_sweep_boundary_diagnostics_*.csv
#   06_core_front_expanded_sweep_selected_trade_panel_*.parquet
#   06_core_front_expanded_sweep_validation_*.csv
#   06_core_front_expanded_sweep_manifest_*.json
#
# Selection universes evaluated:
#   1. all_qualified_trades
#   2. one_trade_per_bucket_per_date_best_rank
#   3. one_trade_per_date_best_rank
#   4. thirty_day_anchor_only
#
# Primary cross-tenor quality metric:
#   avg_pnl_per_day
#
# Important:
#   This is an expanded sweep only.
#   It does not choose a final threshold set.
#   It explicitly checks whether top candidates are still sitting at parameter boundaries.
#
# Not in scope:
#   - No final candidate selection.
#   - No Secondary.
#   - No sizing changes.
#   - No production lock.
# ======================================================================================

from pathlib import Path
from datetime import datetime
import json
import time
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore", category=RuntimeWarning)

pd.set_option("display.max_columns", 240)
pd.set_option("display.width", 380)

# ======================================================================================
# 0. Fallback config if this cell is run independently
# ======================================================================================

if "PROJECT_ROOT" not in globals():
    PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

if "NEW_BRANCH" not in globals():
    NEW_BRANCH = "vrp_unified_fds_core_signal_threshold_research_v1"

if "OUT_PROCESSED_DIR" not in globals():
    OUT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / NEW_BRANCH
    OUT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

if "OUT_AUDIT_DIR" not in globals():
    OUT_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / NEW_BRANCH
    OUT_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

CELL8_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

if "LOCKED_MODEL_SPEC" not in globals():
    LOCKED_MODEL_SPEC = "unified_fds_no_min_return"

if "ALL_TENORS" not in globals():
    ALL_TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

if "BUCKET_ORDER_MAP" not in globals():
    BUCKET_ORDER_MAP = {"Front": 1, "Middle": 2, "Back": 3}

if "BUCKET_CENTER_TENOR" not in globals():
    BUCKET_CENTER_TENOR = {
        "Front": 12,
        "Middle": 21,
        "Back": 30,
    }

if "LOCKED_BACK_CORE_THRESHOLDS" not in globals():
    LOCKED_BACK_CORE_THRESHOLDS = {
        "model_vrp_log": 0.70,
        "model_vrp_z_3m": 0.70,
        "model_vrp_z_1y": 0.70,
        "RSI14_max": 70.0,
        "forecast_vol_pct_min": 8.5,
    }

SELECTION_UNIVERSES = [
    "all_qualified_trades",
    "one_trade_per_bucket_per_date_best_rank",
    "one_trade_per_date_best_rank",
    "thirty_day_anchor_only",
]

PRIMARY_RANKING_METRIC = "avg_pnl_per_day"
TOP_N_BOUNDARY_REVIEW = 50

# ======================================================================================
# 1. Helpers
# ======================================================================================

def latest_file(directory: Path, pattern: str, required: bool = True) -> Path | None:
    matches = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if matches:
        return matches[0]
    if required:
        raise FileNotFoundError(f"No file found in {directory} matching {pattern}")
    return None


def profit_factor_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").dropna()
    gross_profit = float(pnl[pnl > 0].sum())
    gross_loss = float(pnl[pnl < 0].sum())

    if gross_loss < 0:
        return gross_profit / abs(gross_loss)
    if gross_profit > 0:
        return np.inf
    return np.nan


def max_drawdown_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)

    if len(pnl) == 0:
        return np.nan

    cumulative = pnl.cumsum()
    running_max = cumulative.cummax()
    drawdown = cumulative - running_max

    return float(drawdown.min())


def worst_rolling_sum(pnl: pd.Series, window: int) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)

    if len(pnl) == 0:
        return np.nan

    if len(pnl) < window:
        return float(pnl.sum())

    return float(pnl.rolling(window=window, min_periods=window).sum().min())


def add_selection_ranks(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add diagnostic best-rank fields for selected-tenor views.

    This remains a diagnostic DTE selector only.
    """
    d = df.copy()

    if d.empty:
        return d

    d["bucket_center_tenor"] = d["tenor_bucket"].map(BUCKET_CENTER_TENOR)
    d["distance_to_bucket_center"] = (d["tenor"] - d["bucket_center_tenor"]).abs()

    # Within bucket/date.
    rank_group = ["trade_date", "tenor_bucket"]

    d["rank_z_1y_in_bucket_date"] = (
        d.groupby(rank_group)["model_vrp_z_1y"]
        .rank(method="min", ascending=False)
    )
    d["rank_z_3m_in_bucket_date"] = (
        d.groupby(rank_group)["model_vrp_z_3m"]
        .rank(method="min", ascending=False)
    )
    d["rank_vrp_log_in_bucket_date"] = (
        d.groupby(rank_group)["model_vrp_log"]
        .rank(method="min", ascending=False)
    )

    d["avg_signal_rank_in_bucket_date"] = d[
        [
            "rank_z_1y_in_bucket_date",
            "rank_z_3m_in_bucket_date",
            "rank_vrp_log_in_bucket_date",
        ]
    ].mean(axis=1)

    # Across full date.
    d["rank_z_1y_in_date"] = (
        d.groupby("trade_date")["model_vrp_z_1y"]
        .rank(method="min", ascending=False)
    )
    d["rank_z_3m_in_date"] = (
        d.groupby("trade_date")["model_vrp_z_3m"]
        .rank(method="min", ascending=False)
    )
    d["rank_vrp_log_in_date"] = (
        d.groupby("trade_date")["model_vrp_log"]
        .rank(method="min", ascending=False)
    )

    d["avg_signal_rank_in_date"] = d[
        [
            "rank_z_1y_in_date",
            "rank_z_3m_in_date",
            "rank_vrp_log_in_date",
        ]
    ].mean(axis=1)

    return d


def select_trade_universes(qualified: pd.DataFrame) -> dict[str, pd.DataFrame]:
    """
    Given qualified trades for one candidate, return all selection universes.
    """
    if qualified.empty:
        return {
            "all_qualified_trades": qualified.copy(),
            "one_trade_per_bucket_per_date_best_rank": qualified.copy(),
            "one_trade_per_date_best_rank": qualified.copy(),
            "thirty_day_anchor_only": qualified.copy(),
        }

    q = add_selection_ranks(qualified)

    one_trade_per_bucket_date = (
        q.sort_values(
            [
                "trade_date",
                "tenor_bucket_order",
                "avg_signal_rank_in_bucket_date",
                "distance_to_bucket_center",
                "rank_z_1y_in_bucket_date",
                "rank_z_3m_in_bucket_date",
                "rank_vrp_log_in_bucket_date",
                "tenor",
            ],
            ascending=[True, True, True, True, True, True, True, True],
        )
        .groupby(["trade_date", "tenor_bucket"], as_index=False)
        .head(1)
        .copy()
    )

    one_trade_per_date = (
        q.sort_values(
            [
                "trade_date",
                "avg_signal_rank_in_date",
                "rank_z_1y_in_date",
                "rank_z_3m_in_date",
                "rank_vrp_log_in_date",
                "distance_to_bucket_center",
                "tenor_bucket_order",
                "tenor",
            ],
            ascending=[True, True, True, True, True, True, True, True],
        )
        .groupby(["trade_date"], as_index=False)
        .head(1)
        .copy()
    )

    thirty_day_anchor = q[q["tenor"] == 30].copy()

    return {
        "all_qualified_trades": q.copy(),
        "one_trade_per_bucket_per_date_best_rank": one_trade_per_bucket_date,
        "one_trade_per_date_best_rank": one_trade_per_date,
        "thirty_day_anchor_only": thirty_day_anchor,
    }


def summarize_trade_set(
    df: pd.DataFrame,
    candidate_id: str,
    selection_universe: str,
    group_cols: list[str] | None = None,
    include_empty_overall: bool = False,
) -> pd.DataFrame:
    """
    Summarize one selected trade set.

    For overall candidate-level summaries, use group_cols=[] and include_empty_overall=True.
    """
    if group_cols is None:
        group_cols = []

    rows = []
    d = df.copy()

    if not d.empty:
        d["normalized_pnl_dollars"] = pd.to_numeric(d["normalized_pnl_dollars"], errors="coerce")
        d["normalized_pnl_per_day"] = pd.to_numeric(d["normalized_pnl_per_day"], errors="coerce")
        d["win"] = pd.to_numeric(d["win"], errors="coerce")
        d = d[
            d["normalized_pnl_dollars"].notna()
            & d["normalized_pnl_per_day"].notna()
        ].copy()
        d = d.sort_values(["trade_date", "tenor"]).copy()

    if d.empty:
        if include_empty_overall and len(group_cols) == 0:
            return pd.DataFrame([{
                "candidate_id": candidate_id,
                "selection_universe": selection_universe,
                "trades": 0,
                "unique_trade_dates": 0,
                "date_min": pd.NaT,
                "date_max": pd.NaT,
                "avg_tenor": np.nan,
                "win_rate": np.nan,
                "total_pnl": 0.0,
                "avg_pnl": np.nan,
                "median_pnl": np.nan,
                "worst_trade": np.nan,
                "best_trade": np.nan,
                "profit_factor": np.nan,
                "selected_trade_drawdown": np.nan,
                "worst_5_trade_sum": np.nan,
                "worst_10_trade_sum": np.nan,
                "worst_20_trade_sum": np.nan,
                "trades_le_neg_50k": 0,
                "trades_le_neg_100k": 0,
                "trades_le_neg_150k": 0,
                "total_pnl_per_day_sum": 0.0,
                "avg_pnl_per_day": np.nan,
                "median_pnl_per_day": np.nan,
                "worst_trade_pnl_per_day": np.nan,
                "best_trade_pnl_per_day": np.nan,
                "profit_factor_pnl_per_day": np.nan,
                "pnl_per_day_drawdown": np.nan,
                "worst_5_trade_pnl_per_day_sum": np.nan,
                "worst_10_trade_pnl_per_day_sum": np.nan,
                "worst_20_trade_pnl_per_day_sum": np.nan,
                "trades_2025": 0,
                "pnl_2025": 0.0,
                "avg_pnl_per_day_2025": np.nan,
                "worst_trade_2025": np.nan,
                "trades_2026": 0,
                "pnl_2026": 0.0,
                "avg_pnl_per_day_2026": np.nan,
                "worst_trade_2026": np.nan,
            }])
        return pd.DataFrame()

    if len(group_cols) == 0:
        grouped = [((), d)]
    else:
        grouped = d.groupby(group_cols, dropna=False)

    for keys, g in grouped:
        if len(group_cols) == 0:
            keys = ()
        elif not isinstance(keys, tuple):
            keys = (keys,)

        row = {
            "candidate_id": candidate_id,
            "selection_universe": selection_universe,
        }

        for col, key in zip(group_cols, keys):
            row[col] = key

        pnl = g["normalized_pnl_dollars"]
        pnl_day = g["normalized_pnl_per_day"]
        wins = g["win"]

        y2025 = g[g["trade_date"].dt.year == 2025].copy()
        y2026 = g[g["trade_date"].dt.year == 2026].copy()

        row.update({
            "trades": int(len(g)),
            "unique_trade_dates": int(g["trade_date"].nunique()),
            "date_min": g["trade_date"].min(),
            "date_max": g["trade_date"].max(),
            "tenor_min": int(g["tenor"].min()) if g["tenor"].notna().any() else np.nan,
            "tenor_max": int(g["tenor"].max()) if g["tenor"].notna().any() else np.nan,
            "avg_tenor": float(g["tenor"].mean()) if g["tenor"].notna().any() else np.nan,

            # Total-dollar P&L.
            "win_rate": float(wins.mean()) if wins.notna().sum() else np.nan,
            "total_pnl": float(pnl.sum()),
            "avg_pnl": float(pnl.mean()),
            "median_pnl": float(pnl.median()),
            "worst_trade": float(pnl.min()),
            "best_trade": float(pnl.max()),
            "profit_factor": profit_factor_from_pnl(pnl),
            "selected_trade_drawdown": max_drawdown_from_pnl(pnl),
            "worst_5_trade_sum": worst_rolling_sum(pnl, 5),
            "worst_10_trade_sum": worst_rolling_sum(pnl, 10),
            "worst_20_trade_sum": worst_rolling_sum(pnl, 20),
            "trades_le_neg_50k": int((pnl <= -50_000).sum()),
            "trades_le_neg_100k": int((pnl <= -100_000).sum()),
            "trades_le_neg_150k": int((pnl <= -150_000).sum()),

            # P&L/day — primary cross-tenor quality.
            "total_pnl_per_day_sum": float(pnl_day.sum()),
            "avg_pnl_per_day": float(pnl_day.mean()),
            "median_pnl_per_day": float(pnl_day.median()),
            "worst_trade_pnl_per_day": float(pnl_day.min()),
            "best_trade_pnl_per_day": float(pnl_day.max()),
            "profit_factor_pnl_per_day": profit_factor_from_pnl(pnl_day),
            "pnl_per_day_drawdown": max_drawdown_from_pnl(pnl_day),
            "worst_5_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 5),
            "worst_10_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 10),
            "worst_20_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 20),

            # Recent year diagnostics.
            "trades_2025": int(len(y2025)),
            "pnl_2025": float(y2025["normalized_pnl_dollars"].sum()) if len(y2025) else 0.0,
            "avg_pnl_per_day_2025": float(y2025["normalized_pnl_per_day"].mean()) if len(y2025) else np.nan,
            "worst_trade_2025": float(y2025["normalized_pnl_dollars"].min()) if len(y2025) else np.nan,

            "trades_2026": int(len(y2026)),
            "pnl_2026": float(y2026["normalized_pnl_dollars"].sum()) if len(y2026) else 0.0,
            "avg_pnl_per_day_2026": float(y2026["normalized_pnl_per_day"].mean()) if len(y2026) else np.nan,
            "worst_trade_2026": float(y2026["normalized_pnl_dollars"].min()) if len(y2026) else np.nan,
        })

        rows.append(row)

    return pd.DataFrame(rows)


def apply_candidate_thresholds(signal_df: pd.DataFrame, candidate: pd.Series) -> tuple[pd.DataFrame, dict]:
    """
    Apply one expanded-grid candidate's bucket thresholds to the signal panel.
    """
    d = signal_df.copy()

    required_inputs = (
        d["model_vrp_log"].notna()
        & d["model_vrp_z_3m"].notna()
        & d["model_vrp_z_1y"].notna()
        & d["RSI14"].notna()
        & d["forecast_vol_pct"].notna()
    )

    pass_mask = pd.Series(False, index=d.index)

    diagnostics = {
        "candidate_id": candidate["candidate_id"],
        "threshold_input_available_rows": int(required_inputs.sum()),
    }

    for bucket in ["Front", "Middle", "Back"]:
        bucket_mask = d["tenor_bucket"].eq(bucket)

        log_threshold = candidate[f"{bucket}_model_vrp_log"]
        z_threshold = candidate[f"{bucket}_model_vrp_z"]
        rsi_max = candidate[f"{bucket}_RSI14_max"]
        fv_floor = candidate[f"{bucket}_forecast_vol_pct_min"]

        bucket_pass = (
            required_inputs
            & bucket_mask
            & (d["model_vrp_log"] > log_threshold)
            & (d["model_vrp_z_3m"] > z_threshold)
            & (d["model_vrp_z_1y"] > z_threshold)
            & (d["RSI14"] < rsi_max)
            & (d["forecast_vol_pct"] > fv_floor)
        )

        pass_mask = pass_mask | bucket_pass

        diagnostics[f"{bucket}_pass_rows_all_dates"] = int(bucket_pass.sum())

    d["candidate_core_pass"] = pass_mask

    outcome_available = (
        d["normalized_pnl_dollars"].notna()
        & d["normalized_pnl_per_day"].notna()
    )

    qualified = d[
        d["candidate_core_pass"]
        & outcome_available
    ].copy()

    diagnostics["pass_rows_all_dates"] = int(pass_mask.sum())
    diagnostics["pass_rows_with_outcomes"] = int(len(qualified))
    diagnostics["trade_outcome_available_rows"] = int(outcome_available.sum())

    return qualified, diagnostics


def attach_candidate_parameters(summary: pd.DataFrame, grid_wide: pd.DataFrame) -> pd.DataFrame:
    if summary.empty:
        return summary

    param_cols = [
        c for c in grid_wide.columns
        if c == "candidate_id"
        or c.endswith("_model_vrp_log")
        or c.endswith("_model_vrp_z")
        or c.endswith("_RSI14_max")
        or c.endswith("_forecast_vol_pct_min")
        or c.startswith("front_minus_back_")
        or c.startswith("middle_between_front_back_")
        or c in [
            "front_log_tighter_than_back",
            "front_RSI_tighter_than_back",
            "front_forecast_floor_tighter_than_back",
            "candidate_family",
            "locked_model_spec",
        ]
    ]

    params = grid_wide[param_cols].copy()

    return summary.merge(params, on="candidate_id", how="left", validate="many_to_one")


def build_boundary_diagnostics(summary_overall: pd.DataFrame, grid_wide: pd.DataFrame, top_n: int = 50) -> pd.DataFrame:
    """
    Identify whether top candidates are sitting at parameter boundaries.

    This is diagnostic only; it does not select final thresholds.
    """
    if summary_overall.empty:
        return pd.DataFrame()

    boundary_specs = []

    for bucket in ["Front", "Middle", "Back"]:
        for metric in [
            "model_vrp_log",
            "model_vrp_z",
            "RSI14_max",
            "forecast_vol_pct_min",
        ]:
            col = f"{bucket}_{metric}"
            if col in grid_wide.columns:
                vals = sorted(pd.to_numeric(grid_wide[col], errors="coerce").dropna().unique().tolist())
                if vals:
                    boundary_specs.append({
                        "parameter": col,
                        "grid_min": min(vals),
                        "grid_max": max(vals),
                    })

    boundary_spec_df = pd.DataFrame(boundary_specs)

    rows = []

    for universe in sorted(summary_overall["selection_universe"].dropna().unique().tolist()):
        u = summary_overall[summary_overall["selection_universe"].eq(universe)].copy()

        if u.empty or PRIMARY_RANKING_METRIC not in u.columns:
            continue

        top = (
            u.sort_values(
                [PRIMARY_RANKING_METRIC, "profit_factor_pnl_per_day", "trades"],
                ascending=[False, False, False],
            )
            .head(top_n)
            .copy()
        )

        for _, spec in boundary_spec_df.iterrows():
            param = spec["parameter"]
            grid_min = spec["grid_min"]
            grid_max = spec["grid_max"]

            if param not in top.columns:
                continue

            vals = pd.to_numeric(top[param], errors="coerce")

            rows.append({
                "selection_universe": universe,
                "top_n": int(len(top)),
                "parameter": param,
                "grid_min": grid_min,
                "grid_max": grid_max,
                "top_min": float(vals.min()) if vals.notna().any() else np.nan,
                "top_max": float(vals.max()) if vals.notna().any() else np.nan,
                "top_mode": float(vals.mode().iloc[0]) if vals.notna().any() and not vals.mode().empty else np.nan,
                "share_top_at_grid_min": float((vals == grid_min).mean()) if len(vals) else np.nan,
                "share_top_at_grid_max": float((vals == grid_max).mean()) if len(vals) else np.nan,
                "count_top_at_grid_min": int((vals == grid_min).sum()) if len(vals) else 0,
                "count_top_at_grid_max": int((vals == grid_max).sum()) if len(vals) else 0,
                "boundary_warning": bool(
                    ((vals == grid_min).mean() >= 0.50)
                    or ((vals == grid_max).mean() >= 0.50)
                ) if len(vals) else False,
            })

    return pd.DataFrame(rows)


# ======================================================================================
# 2. Load signal panel and expanded candidate grid
# ======================================================================================

base_panel_path = latest_file(
    OUT_PROCESSED_DIR,
    "01_unified_fds_signal_base_panel_*.parquet",
    required=True,
)

grid_wide_path = latest_file(
    OUT_PROCESSED_DIR,
    "05_core_front_expanded_candidate_grid_wide_*.parquet",
    required=True,
)

grid_long_path = latest_file(
    OUT_PROCESSED_DIR,
    "05_core_front_expanded_candidate_grid_long_*.parquet",
    required=True,
)

signal = pd.read_parquet(base_panel_path)
grid_wide = pd.read_parquet(grid_wide_path)
grid_long = pd.read_parquet(grid_long_path)

# Normalize dates / numeric fields.
signal["trade_date"] = pd.to_datetime(signal["trade_date"], errors="coerce").dt.normalize()
signal["tenor"] = pd.to_numeric(signal["tenor"], errors="coerce").astype(int)

if "last_forward_rv_date" in signal.columns:
    signal["last_forward_rv_date"] = pd.to_datetime(
        signal["last_forward_rv_date"],
        errors="coerce",
    ).dt.normalize()

required_signal_cols = [
    "trade_date",
    "tenor",
    "tenor_bucket",
    "tenor_bucket_order",
    "model_spec",
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14",
    "forecast_vol_pct",
    "normalized_pnl_dollars",
    "normalized_pnl_per_day",
    "win",
]

missing_signal_cols = [c for c in required_signal_cols if c not in signal.columns]
if missing_signal_cols:
    raise KeyError(f"Cell 8 missing required signal columns: {missing_signal_cols}")

required_grid_cols = [
    "candidate_id",
    "Front_model_vrp_log",
    "Front_model_vrp_z",
    "Front_RSI14_max",
    "Front_forecast_vol_pct_min",
    "Middle_model_vrp_log",
    "Middle_model_vrp_z",
    "Middle_RSI14_max",
    "Middle_forecast_vol_pct_min",
    "Back_model_vrp_log",
    "Back_model_vrp_z",
    "Back_RSI14_max",
    "Back_forecast_vol_pct_min",
]

missing_grid_cols = [c for c in required_grid_cols if c not in grid_wide.columns]
if missing_grid_cols:
    raise KeyError(f"Cell 8 missing required grid columns: {missing_grid_cols}")

# Ensure numeric fields.
for c in [
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14",
    "forecast_vol_pct",
    "normalized_pnl_dollars",
    "normalized_pnl_per_day",
    "win",
]:
    signal[c] = pd.to_numeric(signal[c], errors="coerce")

for c in [
    c for c in grid_wide.columns
    if c.endswith("_model_vrp_log")
    or c.endswith("_model_vrp_z")
    or c.endswith("_RSI14_max")
    or c.endswith("_forecast_vol_pct_min")
]:
    grid_wide[c] = pd.to_numeric(grid_wide[c], errors="coerce")

grid_wide = grid_wide.sort_values("candidate_id").reset_index(drop=True)

# ======================================================================================
# 3. Sweep expanded candidates
# ======================================================================================

start_time = time.time()

overall_summary_rows = []
bucket_summary_rows = []
tenor_summary_rows = []
year_summary_rows = []
pass_diagnostic_rows = []
selected_trade_frames = []

candidate_count = len(grid_wide)

print("=" * 100)
print("Cell 8 — Front-focused expanded Core threshold sweep using P&L/day")
print("=" * 100)
print(f"Signal panel:             {base_panel_path}")
print(f"Expanded wide grid:       {grid_wide_path}")
print(f"Expanded long grid:       {grid_long_path}")
print(f"Candidates to evaluate:   {candidate_count:,}")
print(f"Selection universes:      {SELECTION_UNIVERSES}")
print(f"Primary metric:           {PRIMARY_RANKING_METRIC}")
print()

for i, candidate in grid_wide.iterrows():
    candidate_id = candidate["candidate_id"]

    qualified, pass_diag = apply_candidate_thresholds(signal, candidate)
    pass_diagnostic_rows.append(pass_diag)

    universes = select_trade_universes(qualified)

    for universe_name, selected in universes.items():
        if not selected.empty:
            selected = selected.copy()
            selected.insert(0, "selection_universe", universe_name)
            selected.insert(0, "candidate_id", candidate_id)

            # Attach exact candidate thresholds for audit traceability.
            for bucket in ["Front", "Middle", "Back"]:
                selected[f"{bucket}_model_vrp_log_threshold"] = candidate[f"{bucket}_model_vrp_log"]
                selected[f"{bucket}_model_vrp_z_threshold"] = candidate[f"{bucket}_model_vrp_z"]
                selected[f"{bucket}_RSI14_max"] = candidate[f"{bucket}_RSI14_max"]
                selected[f"{bucket}_forecast_vol_pct_min"] = candidate[f"{bucket}_forecast_vol_pct_min"]

            selected_trade_frames.append(selected)

        overall_summary_rows.append(
            summarize_trade_set(
                selected,
                candidate_id=candidate_id,
                selection_universe=universe_name,
                group_cols=[],
                include_empty_overall=True,
            )
        )

        bucket_summary_rows.append(
            summarize_trade_set(
                selected,
                candidate_id=candidate_id,
                selection_universe=universe_name,
                group_cols=["tenor_bucket", "tenor_bucket_order"],
                include_empty_overall=False,
            )
        )

        tenor_summary_rows.append(
            summarize_trade_set(
                selected,
                candidate_id=candidate_id,
                selection_universe=universe_name,
                group_cols=["tenor", "tenor_bucket", "tenor_bucket_order"],
                include_empty_overall=False,
            )
        )

        if not selected.empty:
            selected_year = selected.copy()
            selected_year["year"] = selected_year["trade_date"].dt.year.astype(int)

            year_summary_rows.append(
                summarize_trade_set(
                    selected_year,
                    candidate_id=candidate_id,
                    selection_universe=universe_name,
                    group_cols=["year"],
                    include_empty_overall=False,
                )
            )

    if (i + 1) % 50 == 0 or (i + 1) == candidate_count:
        elapsed = time.time() - start_time
        print(f"  Evaluated {i + 1:,} / {candidate_count:,} candidates | elapsed {elapsed:,.1f}s")

# Combine.
summary_overall = pd.concat(overall_summary_rows, ignore_index=True) if overall_summary_rows else pd.DataFrame()
summary_by_bucket = pd.concat(bucket_summary_rows, ignore_index=True) if bucket_summary_rows else pd.DataFrame()
summary_by_tenor = pd.concat(tenor_summary_rows, ignore_index=True) if tenor_summary_rows else pd.DataFrame()
summary_by_year = pd.concat(year_summary_rows, ignore_index=True) if year_summary_rows else pd.DataFrame()
pass_diagnostics = pd.DataFrame(pass_diagnostic_rows)

selected_trade_panel = (
    pd.concat(selected_trade_frames, ignore_index=True)
    if selected_trade_frames
    else pd.DataFrame()
)

# Attach candidate thresholds and grid diagnostics.
summary_overall = attach_candidate_parameters(summary_overall, grid_wide)
summary_by_bucket = attach_candidate_parameters(summary_by_bucket, grid_wide)
summary_by_tenor = attach_candidate_parameters(summary_by_tenor, grid_wide)
summary_by_year = attach_candidate_parameters(summary_by_year, grid_wide)
pass_diagnostics = attach_candidate_parameters(pass_diagnostics, grid_wide)

# Boundary diagnostics after parameters are attached.
boundary_diagnostics = build_boundary_diagnostics(
    summary_overall=summary_overall,
    grid_wide=grid_wide,
    top_n=TOP_N_BOUNDARY_REVIEW,
)

# Sort useful outputs.
if not summary_overall.empty:
    summary_overall = summary_overall.sort_values(
        ["selection_universe", PRIMARY_RANKING_METRIC, "profit_factor_pnl_per_day", "trades"],
        ascending=[True, False, False, False],
    )

if not summary_by_bucket.empty:
    summary_by_bucket = summary_by_bucket.sort_values(
        ["selection_universe", "candidate_id", "tenor_bucket_order"]
    )

if not summary_by_tenor.empty:
    summary_by_tenor = summary_by_tenor.sort_values(
        ["selection_universe", "candidate_id", "tenor"]
    )

if not summary_by_year.empty:
    summary_by_year = summary_by_year.sort_values(
        ["selection_universe", "candidate_id", "year"]
    )

elapsed_seconds = time.time() - start_time

# ======================================================================================
# 4. Save outputs
# ======================================================================================

candidate_summary_path = OUT_AUDIT_DIR / f"06_core_front_expanded_sweep_candidate_summary_{CELL8_TIMESTAMP}.csv"
by_bucket_path = OUT_AUDIT_DIR / f"06_core_front_expanded_sweep_by_bucket_{CELL8_TIMESTAMP}.csv"
by_tenor_path = OUT_AUDIT_DIR / f"06_core_front_expanded_sweep_by_tenor_{CELL8_TIMESTAMP}.csv"
by_year_path = OUT_AUDIT_DIR / f"06_core_front_expanded_sweep_by_year_{CELL8_TIMESTAMP}.csv"
pass_diagnostics_path = OUT_AUDIT_DIR / f"06_core_front_expanded_sweep_candidate_pass_diagnostics_{CELL8_TIMESTAMP}.csv"
boundary_diagnostics_path = OUT_AUDIT_DIR / f"06_core_front_expanded_sweep_boundary_diagnostics_{CELL8_TIMESTAMP}.csv"
selected_trade_panel_path = OUT_PROCESSED_DIR / f"06_core_front_expanded_sweep_selected_trade_panel_{CELL8_TIMESTAMP}.parquet"
validation_path = OUT_AUDIT_DIR / f"06_core_front_expanded_sweep_validation_{CELL8_TIMESTAMP}.csv"
manifest_path = OUT_AUDIT_DIR / f"06_core_front_expanded_sweep_manifest_{CELL8_TIMESTAMP}.json"

summary_overall.to_csv(candidate_summary_path, index=False)
summary_by_bucket.to_csv(by_bucket_path, index=False)
summary_by_tenor.to_csv(by_tenor_path, index=False)
summary_by_year.to_csv(by_year_path, index=False)
pass_diagnostics.to_csv(pass_diagnostics_path, index=False)
boundary_diagnostics.to_csv(boundary_diagnostics_path, index=False)

selected_trade_panel.to_parquet(selected_trade_panel_path, index=False)

# ======================================================================================
# 5. Validation
# ======================================================================================

validation_rows = []

def add_validation(check, status, detail):
    validation_rows.append({
        "check": check,
        "status": status,
        "detail": detail,
    })

models_found = sorted(signal["model_spec"].dropna().unique().tolist())
candidate_ids = grid_wide["candidate_id"].dropna().tolist()
candidate_id_unique = len(candidate_ids) == len(set(candidate_ids))

expected_overall_rows = len(grid_wide) * len(SELECTION_UNIVERSES)
actual_overall_rows = len(summary_overall)

back_bad = grid_wide[
    (grid_wide["Back_model_vrp_log"] != LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"])
    | (grid_wide["Back_model_vrp_z"] != LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"])
    | (grid_wide["Back_RSI14_max"] != LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"])
    | (grid_wide["Back_forecast_vol_pct_min"] != LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"])
]

z_equality_required_cols = {
    "Front_model_vrp_z_3m",
    "Front_model_vrp_z_1y",
    "Middle_model_vrp_z_3m",
    "Middle_model_vrp_z_1y",
    "Back_model_vrp_z_3m",
    "Back_model_vrp_z_1y",
}

if z_equality_required_cols.issubset(set(grid_wide.columns)):
    z_equality_bad = grid_wide[
        (grid_wide["Front_model_vrp_z_3m"] != grid_wide["Front_model_vrp_z_1y"])
        | (grid_wide["Middle_model_vrp_z_3m"] != grid_wide["Middle_model_vrp_z_1y"])
        | (grid_wide["Back_model_vrp_z_3m"] != grid_wide["Back_model_vrp_z_1y"])
    ]
else:
    z_equality_bad = pd.DataFrame({"missing_z_equality_cols": list(z_equality_required_cols - set(grid_wide.columns))})

bad_pnl_day = signal[
    signal["normalized_pnl_dollars"].notna()
    & signal["normalized_pnl_per_day"].notna()
    & (
        (
            signal["normalized_pnl_dollars"] / signal["tenor"].replace(0, np.nan)
        )
        - signal["normalized_pnl_per_day"]
    ).abs().gt(1e-8)
]

selection_universes_found = sorted(summary_overall["selection_universe"].dropna().unique().tolist())

selected_trade_universes_found = (
    sorted(selected_trade_panel["selection_universe"].dropna().unique().tolist())
    if not selected_trade_panel.empty and "selection_universe" in selected_trade_panel.columns
    else []
)

boundary_warning_count = (
    int(boundary_diagnostics["boundary_warning"].sum())
    if not boundary_diagnostics.empty and "boundary_warning" in boundary_diagnostics.columns
    else 0
)

add_validation(
    "signal_panel_loaded",
    "PASS" if len(signal) > 0 else "FAIL",
    f"rows={len(signal):,}; path={base_panel_path}",
)

add_validation(
    "locked_model_only",
    "PASS" if models_found == [LOCKED_MODEL_SPEC] else "FAIL",
    f"models_found={models_found}",
)

add_validation(
    "expanded_candidate_grid_loaded",
    "PASS" if len(grid_wide) > 0 else "FAIL",
    f"candidate_count={len(grid_wide):,}; path={grid_wide_path}",
)

add_validation(
    "candidate_id_unique",
    "PASS" if candidate_id_unique else "FAIL",
    f"candidate_ids={len(candidate_ids):,}; unique={len(set(candidate_ids)):,}",
)

add_validation(
    "back_thresholds_locked",
    "PASS" if back_bad.empty else "FAIL",
    f"bad_rows={len(back_bad):,}; locked_back={LOCKED_BACK_CORE_THRESHOLDS}",
)

add_validation(
    "z_3m_equals_z_1y_within_bucket",
    "PASS" if z_equality_bad.empty else "FAIL",
    f"bad_rows={len(z_equality_bad):,}",
)

add_validation(
    "normalized_pnl_per_day_formula",
    "PASS" if bad_pnl_day.empty else "FAIL",
    f"bad_rows={len(bad_pnl_day):,}; formula=normalized_pnl_dollars / tenor",
)

add_validation(
    "overall_summary_rows_complete",
    "PASS" if actual_overall_rows == expected_overall_rows else "FAIL",
    f"actual={actual_overall_rows:,}; expected={expected_overall_rows:,}",
)

add_validation(
    "all_selection_universes_evaluated",
    "PASS" if selection_universes_found == sorted(SELECTION_UNIVERSES) else "FAIL",
    f"found={selection_universes_found}",
)

add_validation(
    "selected_trade_panel_saved",
    "PASS" if len(selected_trade_panel) > 0 else "WARN",
    f"rows={len(selected_trade_panel):,}; universes={selected_trade_universes_found}",
)

add_validation(
    "candidate_pass_diagnostics_created",
    "PASS" if len(pass_diagnostics) == len(grid_wide) else "FAIL",
    f"rows={len(pass_diagnostics):,}; expected={len(grid_wide):,}",
)

add_validation(
    "boundary_diagnostics_created",
    "PASS" if len(boundary_diagnostics) > 0 else "WARN",
    f"rows={len(boundary_diagnostics):,}; warnings={boundary_warning_count:,}",
)

add_validation(
    "no_final_candidate_selection",
    "PASS",
    "Cell 8 is expanded sweep only. Final ranking/selection deferred.",
)

add_validation(
    "no_secondary",
    "PASS",
    "Core only.",
)

add_validation(
    "no_sizing_changes",
    "PASS",
    "Threshold sweep only. No sizing fields changed.",
)

add_validation(
    "no_production_lock",
    "PASS",
    "No production threshold lock performed.",
)

validation = pd.DataFrame(validation_rows)
validation.to_csv(validation_path, index=False)

failures = validation[validation["status"] == "FAIL"]

manifest = {
    "notebook": "07_unified_fds_core_signal_threshold_research_v1.ipynb",
    "cell": "Cell 8 — Front-focused expanded Core threshold sweep using P&L/day",
    "timestamp": CELL8_TIMESTAMP,
    "elapsed_seconds": elapsed_seconds,
    "locked_model_spec": LOCKED_MODEL_SPEC,
    "base_panel_path": str(base_panel_path),
    "grid_wide_path": str(grid_wide_path),
    "grid_long_path": str(grid_long_path),
    "candidate_count": int(len(grid_wide)),
    "selection_universes": SELECTION_UNIVERSES,
    "primary_ranking_metric": PRIMARY_RANKING_METRIC,
    "top_n_boundary_review": TOP_N_BOUNDARY_REVIEW,
    "candidate_summary_path": str(candidate_summary_path),
    "by_bucket_path": str(by_bucket_path),
    "by_tenor_path": str(by_tenor_path),
    "by_year_path": str(by_year_path),
    "pass_diagnostics_path": str(pass_diagnostics_path),
    "boundary_diagnostics_path": str(boundary_diagnostics_path),
    "selected_trade_panel_path": str(selected_trade_panel_path),
    "validation_path": str(validation_path),
    "boundary_warning_count": boundary_warning_count,
    "notes": [
        "Expanded sweep only.",
        "No final candidate selected.",
        "No Secondary.",
        "No sizing changes.",
        "No production lock.",
        "If top candidates cluster at parameter boundaries, do not lock; expand again or reconsider selection rules.",
        "P&L/day is the primary cross-tenor quality metric.",
        "Best-rank DTE selection remains diagnostic only.",
    ],
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2, default=str)

if not failures.empty:
    display(validation)
    raise RuntimeError("Cell 8 validation failed. Review validation output above.")

# ======================================================================================
# 6. Display concise review
# ======================================================================================

print("=" * 100)
print("Cell 8 — Front-focused expanded Core threshold sweep using P&L/day")
print("=" * 100)
print(f"Signal panel:                  {base_panel_path}")
print(f"Expanded candidate grid:       {grid_wide_path}")
print(f"Candidates evaluated:          {len(grid_wide):,}")
print(f"Overall summary rows:          {len(summary_overall):,}")
print(f"By-bucket rows:                {len(summary_by_bucket):,}")
print(f"By-tenor rows:                 {len(summary_by_tenor):,}")
print(f"By-year rows:                  {len(summary_by_year):,}")
print(f"Pass diagnostic rows:          {len(pass_diagnostics):,}")
print(f"Boundary diagnostic rows:      {len(boundary_diagnostics):,}")
print(f"Boundary warnings:             {boundary_warning_count:,}")
print(f"Selected trade panel rows:     {len(selected_trade_panel):,}")
print(f"Elapsed seconds:               {elapsed_seconds:,.1f}")
print(f"Primary ranking metric:        {PRIMARY_RANKING_METRIC}")
print("No final candidate selection:  True")
print("No Secondary:                  True")
print("No sizing changes:             True")
print("No production lock:            True")

print()
print("Validation:")
display(validation)

top_display_cols = [
    "candidate_id",
    "selection_universe",
    "trades",
    "unique_trade_dates",
    "avg_tenor",
    "win_rate",
    "total_pnl",
    "profit_factor",
    "avg_pnl_per_day",
    "median_pnl_per_day",
    "worst_trade_pnl_per_day",
    "pnl_per_day_drawdown",
    "worst_20_trade_pnl_per_day_sum",
    "trades_le_neg_100k",
    "pnl_2025",
    "avg_pnl_per_day_2025",
    "pnl_2026",
    "avg_pnl_per_day_2026",
    "Front_model_vrp_log",
    "Front_model_vrp_z",
    "Front_RSI14_max",
    "Front_forecast_vol_pct_min",
    "Middle_model_vrp_log",
    "Middle_model_vrp_z",
    "Middle_RSI14_max",
    "Middle_forecast_vol_pct_min",
    "Back_model_vrp_log",
    "Back_model_vrp_z",
    "front_log_tighter_than_back",
    "front_RSI_tighter_than_back",
    "front_forecast_floor_tighter_than_back",
]

print()
print("Top 25 by avg P&L/day — one trade per bucket/date:")
top_bucket = summary_overall[
    summary_overall["selection_universe"].eq("one_trade_per_bucket_per_date_best_rank")
].sort_values(
    ["avg_pnl_per_day", "profit_factor_pnl_per_day", "trades"],
    ascending=[False, False, False],
).head(25)

display(top_bucket[[c for c in top_display_cols if c in top_bucket.columns]])

print()
print("Top 25 by avg P&L/day — one trade per date:")
top_date = summary_overall[
    summary_overall["selection_universe"].eq("one_trade_per_date_best_rank")
].sort_values(
    ["avg_pnl_per_day", "profit_factor_pnl_per_day", "trades"],
    ascending=[False, False, False],
).head(25)

display(top_date[[c for c in top_display_cols if c in top_date.columns]])

print()
print("Top 25 by avg P&L/day — all qualified trades:")
top_all = summary_overall[
    summary_overall["selection_universe"].eq("all_qualified_trades")
].sort_values(
    ["avg_pnl_per_day", "profit_factor_pnl_per_day", "trades"],
    ascending=[False, False, False],
).head(25)

display(top_all[[c for c in top_display_cols if c in top_all.columns]])

print()
print("30D anchor reference rows:")
anchor = summary_overall[
    summary_overall["selection_universe"].eq("thirty_day_anchor_only")
].sort_values("candidate_id").head(10)

display(anchor[[c for c in top_display_cols if c in anchor.columns]])

print()
print("Boundary diagnostics — parameters where >=50% of top candidates sit at min or max:")
if not boundary_diagnostics.empty:
    display(
        boundary_diagnostics[
            boundary_diagnostics["boundary_warning"].eq(True)
        ].sort_values(
            ["selection_universe", "parameter"]
        )
    )
else:
    print("No boundary diagnostics available.")

print()
print("Pass diagnostics sample:")
pass_diag_display_cols = [
    "candidate_id",
    "pass_rows_all_dates",
    "pass_rows_with_outcomes",
    "Front_pass_rows_all_dates",
    "Middle_pass_rows_all_dates",
    "Back_pass_rows_all_dates",
    "Front_model_vrp_log",
    "Front_model_vrp_z",
    "Front_RSI14_max",
    "Front_forecast_vol_pct_min",
    "Middle_model_vrp_log",
    "Middle_model_vrp_z",
    "Middle_RSI14_max",
    "Middle_forecast_vol_pct_min",
]
display(pass_diagnostics[[c for c in pass_diag_display_cols if c in pass_diagnostics.columns]].head(25))

print()
print("Saved outputs:")
for p in [
    candidate_summary_path,
    by_bucket_path,
    by_tenor_path,
    by_year_path,
    pass_diagnostics_path,
    boundary_diagnostics_path,
    selected_trade_panel_path,
    validation_path,
    manifest_path,
]:
    print(f"  {p}")

print("\nCELL 8 PASSED")

====================================================================================================
Cell 8 — Front-focused expanded Core threshold sweep using P&L/day
====================================================================================================
Signal panel:             C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\01_unified_fds_signal_base_panel_20200102_20260701_20260704_211636.parquet
Expanded wide grid:       C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\05_core_front_expanded_candidate_grid_wide_20260704_215243.parquet
Expanded long grid:       C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\05_core_front_expanded_candidate_grid_long_20260704_215243.parquet
Candidates to evaluate:   320
Selection universes:      ['all_qualified_trades', 'one_trade_per_bucket_per_date_best_rank', 'one_trade_per_date_best_rank', 'thirty_day_anchor_only']
Primary metric:           avg_pnl_per_day

  Evaluated 50 / 320 candidates | elapsed 21.8s
  Evaluated 100 / 320 candidates | elapsed 43.4s
  Evaluated 150 / 320 candidates | elapsed 65.1s
  Evaluated 200 / 320 candidates | elapsed 86.3s
  Evaluated 250 / 320 candidates | elapsed 107.9s
  Evaluated 300 / 320 candidates | elapsed 129.2s
  Evaluated 320 / 320 candidates | elapsed 138.0s
====================================================================================================
Cell 8 — Front-focused expanded Core threshold sweep using P&L/day
====================================================================================================
Signal panel:                  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\01_unified_fds_signal_base_panel_20200102_20260701_20260704_211636.parquet
Expanded candidate grid:       C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\05_core_front_expanded_candidate_grid_wide_20260704_215243.parquet
Candidates evaluated:          320
Overall summary rows:          1,280
By-bucket rows:                3,200
By-tenor rows:                 8,960
By-year rows:                  7,680
Pass diagnostic rows:          320
Boundary diagnostic rows:      48
Boundary warnings:             41
Selected trade panel rows:     659,356
Elapsed seconds:               140.4
Primary ranking metric:        avg_pnl_per_day
No final candidate selection:  True
No Secondary:                  True
No sizing changes:             True
No production lock:            True

Validation:

                                 check status                                             detail
0                  signal_panel_loaded   PASS  rows=14,688; path=C:\Users\patri\vrp_project\d...
1                    locked_model_only   PASS         models_found=['unified_fds_no_min_return']
2       expanded_candidate_grid_loaded   PASS  candidate_count=320; path=C:\Users\patri\vrp_p...
3                  candidate_id_unique   PASS                      candidate_ids=320; unique=320
4               back_thresholds_locked   PASS  bad_rows=0; locked_back={'model_vrp_log': 0.7,...
5       z_3m_equals_z_1y_within_bucket   PASS                                         bad_rows=0
6       normalized_pnl_per_day_formula   PASS  bad_rows=0; formula=normalized_pnl_dollars / t...
7        overall_summary_rows_complete   PASS                       actual=1,280; expected=1,280
8    all_selection_universes_evaluated   PASS  found=['all_qualified_trades', 'one_trade_per_...
9           selected_trade_panel_saved   PASS  rows=659,356; universes=['all_qualified_trades...
10  candidate_pass_diagnostics_created   PASS                             rows=320; expected=320
11        boundary_diagnostics_created   PASS                               rows=48; warnings=41
12        no_final_candidate_selection   PASS  Cell 8 is expanded sweep only. Final ranking/s...
13                        no_secondary   PASS                                         Core only.
14                   no_sizing_changes   PASS    Threshold sweep only. No sizing fields changed.
15                  no_production_lock   PASS            No production threshold lock performed.

Top 25 by avg P&L/day — one trade per bucket/date:

,candidate_id,selection_universe,trades,unique_trade_dates,avg_tenor,win_rate,total_pnl,profit_factor,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,pnl_2025,avg_pnl_per_day_2025,pnl_2026,avg_pnl_per_day_2026,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,front_log_tighter_than_back,front_RSI_tighter_than_back,front_forecast_floor_tighter_than_back
669,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,428,197,21.995327,0.855140,5.479290e+06,3.881266,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,1.139874e+06,661.947436,204439.021480,77.113098,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
725,core_front_expanded_00182,one_trade_per_bucket_per_date_best_rank,428,197,21.995327,0.855140,5.479290e+06,3.881266,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,1.139874e+06,661.947436,204439.021480,77.113098,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
789,core_front_expanded_00198,one_trade_per_bucket_per_date_best_rank,428,197,21.995327,0.855140,5.479290e+06,3.881266,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,1.139874e+06,661.947436,204439.021480,77.113098,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
729,core_front_expanded_00183,one_trade_per_bucket_per_date_best_rank,424,196,21.983491,0.853774,5.425318e+06,3.852885,547.507072,890.768149,-10376.349181,-30723.516018,-24889.323006,2,1.128840e+06,665.656487,175562.832699,60.157120,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,False,True,True
793,core_front_expanded_00199,one_trade_per_bucket_per_date_best_rank,424,196,21.983491,0.853774,5.425318e+06,3.852885,547.507072,890.768149,-10376.349181,-30723.516018,-24889.323006,2,1.128840e+06,665.656487,175562.832699,60.157120,0.70,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,False,True,True
733,core_front_expanded_00184,one_trade_per_bucket_per_date_best_rank,424,196,22.004717,0.853774,5.429453e+06,3.855060,547.499550,890.768149,-10376.349181,-30723.516018,-24889.323006,2,1.132976e+06,665.614524,175562.832699,60.157120,0.70,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,False,True,True
797,core_front_expanded_00200,one_trade_per_bucket_per_date_best_rank,424,196,22.004717,0.853774,5.429453e+06,3.855060,547.499550,890.768149,-10376.349181,-30723.516018,-24889.323006,2,1.132976e+06,665.614524,175562.832699,60.157120,0.70,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,False,True,True
665,core_front_expanded_00167,one_trade_per_bucket_per_date_best_rank,432,197,21.979167,0.856481,5.519880e+06,3.902610,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,1.180464e+06,653.887160,204439.021480,77.113098,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
721,core_front_expanded_00181,one_trade_per_bucket_per_date_best_rank,432,197,21.979167,0.856481,5.519880e+06,3.902610,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,1.180464e+06,653.887160,204439.021480,77.113098,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
785,core_front_expanded_00197,one_trade_per_bucket_per_date_best_rank,432,197,21.979167,0.856481,5.519880e+06,3.902610,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,1.180464e+06,653.887160,204439.021480,77.113098,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
989,core_front_expanded_00248,one_trade_per_bucket_per_date_best_rank,423,194,22.113475,0.855792,5.434757e+06,3.872530,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,1.121242e+06,670.977756,204439.021480,77.113098,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,True
1045,core_front_expanded_00262,one_trade_per_bucket_per_date_best_rank,423,194,22.113475,0.855792,5.434757e+06,3.872530,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,1.121242e+06,670.977756,204439.021480,77.113098,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,True
1109,core_front_expanded_00278,one_trade_per_bucket_per_date_best_rank,423,194,22.113475,0.855792,5.434757e+06,3.872530,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,1.121242e+06,670.977756,204439.021480,77.113098,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,True
61,core_front_expanded_00016,one_trade_per_bucket_per_date_best_rank,431,199,21.925754,0.853828,5.484875e+06,3.851100,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,1.135214e+06,640.272931,204439.021480,77.113098,0.65,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
181,core_front_expanded_00046,one_trade_per_bucket_per_date_best_rank,431,199,21.925754,0.853828,5.484875e+06,3.851100,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,1.135214e+06,640.272931,204439.021480,77.113098,0.65,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
309,core_front_expanded_00078,one_trade_per_bucket_per_date_best_rank,431,199,21.925754,0.853828,5.484875e+06,3.851100,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,1.135214e+06,640.272931,204439.021480,77.113098,0.65,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
53,core_front_expanded_00014,one_trade_per_bucket_per_date_best_rank,438,203,21.910959,0.853881,5.567699e+06,3.891386,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,1.149963e+06,631.734887,221840.174693,85.752231,0.65,0.65,68.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,False,True,True
165,core_front_expanded_00042,one_trade_per_bucket_per_date_best_rank,438,203,21.910959,0.853881,5.567699e+06,3.891386,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,1.149963e+06,631.734887,221840.174693,85.752231,0.65,0.65,66.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,False,True,True
293,core_front_expanded_00074,one_trade_per_bucket_per_date_best_rank,438,203,21.910959,0.853881,5.567699e+06,3.891386,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,1.149963e+06,631.734887,221840.174693,85.752231,0.65,0.65,64.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,False,True,True
1049,core_front_expanded_00263,one_trade_per_bucket_per_date_best_rank,419,193,22.102625,0.854415,5.380785e+06,3.844003,544.954259,889.707640,-10376.349181,-30723.516018,-24889.323006,2,1.110208e+06,674.962936,175562.832699,60.157120,0.75,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,True
1113,core_front_expanded_00279,one_trade_per_bucket_per_date_best_rank,419,193,22.102625,0.854415,5.380785e+06,3.844003,544.954259,889.707640,-10376.349181,-30723.516018,-24889.323006,2,1.110208e+06,674.962936,175562.832699,60.157120,0.75,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,True
1053,core_front_expanded_00264,one_trade_per_bucket_per_date_best_rank,419,193,22.124105,0.854415,5.384921e+06,3.846189,544.946647,889.707640,-10376.349181,-30723.516018,-24889.323006,2,1.114344e+06,674.919248,175562.832699,60.157120,0.75,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,True
1117,core_front_expanded_00280,one_trade_per_bucket_per_date_best_rank,419,193,22.124105,0.854415,5.384921e+06,3.846189,544.946647,889.707640,-10376.349181,-30723.516018,-24889.323006,2,1.114344e+06,674.919248,175562.832699,60.157120,0.75,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,True
985,core_front_expanded_00247,one_trade_per_bucket_per_date_best_rank,427,194,22.096019,0.857143,5.475347e+06,3.893984,544.898750,874.092727,-10376.349181,-30723.516018,-24889.323006,2,1.161833e+06,662.144375,204439.021480,77.113098,0.75,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,True,True
1041,core_front_expanded_00261,one_trade_per_bucket_per_date_best_rank,427,194,22.096019,0.857143,5.475347e+06,3.893984,544.898750,874.092727,-10376.349181,-30723.516018,-24889.323006,2,1.161833e+06,662.144375,204439.021480,77.113098,0.75,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,True,True

Top 25 by avg P&L/day — one trade per date:

,candidate_id,selection_universe,trades,unique_trade_dates,avg_tenor,win_rate,total_pnl,profit_factor,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,pnl_2025,avg_pnl_per_day_2025,pnl_2026,avg_pnl_per_day_2026,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,front_log_tighter_than_back,front_RSI_tighter_than_back,front_forecast_floor_tighter_than_back
50,core_front_expanded_00013,one_trade_per_date_best_rank,203,203,22.714286,0.847291,2.450608e+06,3.495839,389.863487,794.545894,-10376.349181,-22715.558180,-12883.355347,1,530159.385099,467.160456,88071.198750,-67.026082,0.65,0.65,68.0,14.5,0.65,0.7,68.0,8.5,0.7,0.7,False,True,True
162,core_front_expanded_00041,one_trade_per_date_best_rank,203,203,22.714286,0.847291,2.450608e+06,3.495839,389.863487,794.545894,-10376.349181,-22715.558180,-12883.355347,1,530159.385099,467.160456,88071.198750,-67.026082,0.65,0.65,66.0,14.5,0.65,0.7,68.0,8.5,0.7,0.7,False,True,True
290,core_front_expanded_00073,one_trade_per_date_best_rank,203,203,22.714286,0.847291,2.450608e+06,3.495839,389.863487,794.545894,-10376.349181,-22715.558180,-12883.355347,1,530159.385099,467.160456,88071.198750,-67.026082,0.65,0.65,64.0,14.5,0.65,0.7,68.0,8.5,0.7,0.7,False,True,True
54,core_front_expanded_00014,one_trade_per_date_best_rank,203,203,22.847291,0.847291,2.459247e+06,3.504638,389.018228,794.545894,-10376.349181,-22715.558180,-12883.355347,1,538798.884208,463.347398,88071.198750,-67.026082,0.65,0.65,68.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,False,True,True
166,core_front_expanded_00042,one_trade_per_date_best_rank,203,203,22.847291,0.847291,2.459247e+06,3.504638,389.018228,794.545894,-10376.349181,-22715.558180,-12883.355347,1,538798.884208,463.347398,88071.198750,-67.026082,0.65,0.65,66.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,False,True,True
294,core_front_expanded_00074,one_trade_per_date_best_rank,203,203,22.847291,0.847291,2.459247e+06,3.504638,389.018228,794.545894,-10376.349181,-22715.558180,-12883.355347,1,538798.884208,463.347398,88071.198750,-67.026082,0.65,0.65,64.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,False,True,True
658,core_front_expanded_00165,one_trade_per_date_best_rank,214,214,21.406542,0.850467,2.521855e+06,3.547787,388.543784,842.027987,-10376.349181,-21813.518224,-15190.125635,0,550371.935978,505.453047,103010.822372,-145.681905,0.70,0.65,68.0,13.0,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
706,core_front_expanded_00177,one_trade_per_date_best_rank,214,214,21.406542,0.850467,2.521855e+06,3.547787,388.543784,842.027987,-10376.349181,-21813.518224,-15190.125635,0,550371.935978,505.453047,103010.822372,-145.681905,0.70,0.65,66.0,13.0,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
662,core_front_expanded_00166,one_trade_per_date_best_rank,214,214,21.532710,0.850467,2.530494e+06,3.556516,387.741972,842.027987,-10376.349181,-21813.518224,-15190.125635,0,559011.435087,501.639989,103010.822372,-145.681905,0.70,0.65,68.0,13.0,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
710,core_front_expanded_00178,one_trade_per_date_best_rank,214,214,21.532710,0.850467,2.530494e+06,3.556516,387.741972,842.027987,-10376.349181,-21813.518224,-15190.125635,0,559011.435087,501.639989,103010.822372,-145.681905,0.70,0.65,66.0,13.0,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
42,core_front_expanded_00011,one_trade_per_date_best_rank,217,217,21.317972,0.847926,2.538233e+06,3.528062,387.643012,841.335272,-10376.349181,-21813.518224,-15190.125635,0,553589.197034,490.301756,103010.822372,-145.681905,0.65,0.65,68.0,13.0,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
146,core_front_expanded_00037,one_trade_per_date_best_rank,217,217,21.317972,0.847926,2.538233e+06,3.528062,387.643012,841.335272,-10376.349181,-21813.518224,-15190.125635,0,553589.197034,490.301756,103010.822372,-145.681905,0.65,0.65,66.0,13.0,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
666,core_front_expanded_00167,one_trade_per_date_best_rank,197,197,22.842640,0.847716,2.396716e+06,3.476776,387.519431,815.608298,-10376.349181,-22715.558180,-12883.355347,1,526942.124043,481.464299,88071.198750,-67.026082,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
722,core_front_expanded_00181,one_trade_per_date_best_rank,197,197,22.842640,0.847716,2.396716e+06,3.476776,387.519431,815.608298,-10376.349181,-22715.558180,-12883.355347,1,526942.124043,481.464299,88071.198750,-67.026082,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
786,core_front_expanded_00197,one_trade_per_date_best_rank,197,197,22.842640,0.847716,2.396716e+06,3.476776,387.519431,815.608298,-10376.349181,-22715.558180,-12883.355347,1,526942.124043,481.464299,88071.198750,-67.026082,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
170,core_front_expanded_00043,one_trade_per_date_best_rank,202,202,22.915842,0.846535,2.449642e+06,3.494855,387.339681,803.111169,-10376.349181,-22715.558180,-12883.355347,1,541925.858135,464.437629,75338.620840,-96.135432,0.65,0.65,66.0,14.5,0.65,0.7,66.0,8.5,0.7,0.7,False,True,True
298,core_front_expanded_00075,one_trade_per_date_best_rank,202,202,22.915842,0.846535,2.449642e+06,3.494855,387.339681,803.111169,-10376.349181,-22715.558180,-12883.355347,1,541925.858135,464.437629,75338.620840,-96.135432,0.65,0.65,64.0,14.5,0.65,0.7,66.0,8.5,0.7,0.7,False,True,True
174,core_front_expanded_00044,one_trade_per_date_best_rank,202,202,22.960396,0.846535,2.453777e+06,3.499067,387.323893,803.111169,-10376.349181,-22715.558180,-12883.355347,1,546061.364850,464.366757,75338.620840,-96.135432,0.65,0.65,66.0,14.5,0.65,0.7,66.0,10.0,0.7,0.7,False,True,True
302,core_front_expanded_00076,one_trade_per_date_best_rank,202,202,22.960396,0.846535,2.453777e+06,3.499067,387.323893,803.111169,-10376.349181,-22715.558180,-12883.355347,1,546061.364850,464.366757,75338.620840,-96.135432,0.65,0.65,64.0,14.5,0.65,0.7,66.0,10.0,0.7,0.7,False,True,True
46,core_front_expanded_00012,one_trade_per_date_best_rank,217,217,21.442396,0.847926,2.546873e+06,3.536667,386.852285,841.335272,-10376.349181,-21813.518224,-15190.125635,0,562228.696143,486.650956,103010.822372,-145.681905,0.65,0.65,68.0,13.0,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
150,core_front_expanded_00038,one_trade_per_date_best_rank,217,217,21.442396,0.847926,2.546873e+06,3.536667,386.852285,841.335272,-10376.349181,-21813.518224,-15190.125635,0,562228.696143,486.650956,103010.822372,-145.681905,0.65,0.65,66.0,13.0,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
670,core_front_expanded_00168,one_trade_per_date_best_rank,197,197,22.979695,0.847716,2.405356e+06,3.485704,386.648428,815.608298,-10376.349181,-22715.558180,-12883.355347,1,535581.623152,477.473890,88071.198750,-67.026082,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
726,core_front_expanded_00182,one_trade_per_date_best_rank,197,197,22.979695,0.847716,2.405356e+06,3.485704,386.648428,815.608298,-10376.349181,-22715.558180,-12883.355347,1,535581.623152,477.473890,88071.198750,-67.026082,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
790,core_front_expanded_00198,one_trade_per_date_best_rank,197,197,22.979695,0.847716,2.405356e+06,3.485704,386.648428,815.608298,-10376.349181,-22715.558180,-12883.355347,1,535581.623152,477.473890,88071.198750,-67.026082,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
34,core_front_expanded_00009,one_trade_per_date_best_rank,218,218,21.371560,0.848624,2.548564e+06,3.538351,386.390673,831.252943,-10376.349181,-21813.518224,-15190.125635,0,553589.197034,490.737080,103010.822372,-145.681905,0.65,0.65,68.0,13.0,0.65,0.7,68.0,8.5,0.7,0.7,False,True,True

Top 25 by avg P&L/day — all qualified trades:

,candidate_id,selection_universe,trades,unique_trade_dates,avg_tenor,win_rate,total_pnl,profit_factor,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,pnl_2025,avg_pnl_per_day_2025,pnl_2026,avg_pnl_per_day_2026,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,front_log_tighter_than_back,front_RSI_tighter_than_back,front_forecast_floor_tighter_than_back
1052,core_front_expanded_00264,all_qualified_trades,1144,193,22.172203,0.856643,1.527791e+07,4.149722,615.883641,903.447547,-10376.349181,-78789.306291,-56329.963714,5,2.941152e+06,685.144473,533142.416334,86.469117,0.75,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,True
1116,core_front_expanded_00280,all_qualified_trades,1144,193,22.172203,0.856643,1.527791e+07,4.149722,615.883641,903.447547,-10376.349181,-78789.306291,-56329.963714,5,2.941152e+06,685.144473,533142.416334,86.469117,0.75,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,True
1048,core_front_expanded_00263,all_qualified_trades,1148,193,22.160279,0.856272,1.530361e+07,4.153072,614.901288,902.006748,-10376.349181,-78789.306291,-56329.963714,5,2.966852e+06,678.085254,533142.416334,86.469117,0.75,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,True
1112,core_front_expanded_00279,all_qualified_trades,1148,193,22.160279,0.856272,1.530361e+07,4.153072,614.901288,902.006748,-10376.349181,-78789.306291,-56329.963714,5,2.966852e+06,678.085254,533142.416334,86.469117,0.75,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,True
732,core_front_expanded_00184,all_qualified_trades,1154,196,22.078856,0.855286,1.531900e+07,4.111617,613.628522,905.270243,-10376.349181,-78789.306291,-56329.963714,5,2.930955e+06,657.952148,547498.735468,91.805130,0.70,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,False,True,True
796,core_front_expanded_00200,all_qualified_trades,1154,196,22.078856,0.855286,1.531900e+07,4.111617,613.628522,905.270243,-10376.349181,-78789.306291,-56329.963714,5,2.930955e+06,657.952148,547498.735468,91.805130,0.70,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,False,True,True
988,core_front_expanded_00248,all_qualified_trades,1156,194,22.160035,0.856401,1.538103e+07,4.155305,613.577424,899.763851,-10376.349181,-78789.306291,-56329.963714,5,2.973148e+06,682.357688,614292.719195,102.240484,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,True
1044,core_front_expanded_00262,all_qualified_trades,1156,194,22.160035,0.856401,1.538103e+07,4.155305,613.577424,899.763851,-10376.349181,-78789.306291,-56329.963714,5,2.973148e+06,682.357688,614292.719195,102.240484,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,True
1108,core_front_expanded_00278,all_qualified_trades,1156,194,22.160035,0.856401,1.538103e+07,4.155305,613.577424,899.763851,-10376.349181,-78789.306291,-56329.963714,5,2.973148e+06,682.357688,614292.719195,102.240484,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,True
1212,core_front_expanded_00304,all_qualified_trades,1123,189,22.370436,0.858415,1.513046e+07,4.182393,613.453369,901.772954,-10376.349181,-78789.306291,-55420.870999,5,2.941152e+06,685.144473,533142.416334,86.469117,0.75,0.70,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,True
1276,core_front_expanded_00320,all_qualified_trades,1123,189,22.370436,0.858415,1.513046e+07,4.182393,613.453369,901.772954,-10376.349181,-78789.306291,-55420.870999,5,2.941152e+06,685.144473,533142.416334,86.469117,0.75,0.70,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,True
728,core_front_expanded_00183,all_qualified_trades,1158,196,22.067358,0.854922,1.534470e+07,4.114942,612.662442,903.447547,-10376.349181,-78789.306291,-56329.963714,5,2.956655e+06,651.630122,547498.735468,91.805130,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,False,True,True
792,core_front_expanded_00199,all_qualified_trades,1158,196,22.067358,0.854922,1.534470e+07,4.114942,612.662442,903.447547,-10376.349181,-78789.306291,-56329.963714,5,2.956655e+06,651.630122,547498.735468,91.805130,0.70,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,False,True,True
1208,core_front_expanded_00303,all_qualified_trades,1127,189,22.357587,0.858030,1.515616e+07,4.185791,612.461336,899.841736,-10376.349181,-78789.306291,-55420.870999,5,2.966852e+06,678.085254,533142.416334,86.469117,0.75,0.70,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,True
1272,core_front_expanded_00319,all_qualified_trades,1127,189,22.357587,0.858030,1.515616e+07,4.185791,612.461336,899.841736,-10376.349181,-78789.306291,-55420.870999,5,2.966852e+06,678.085254,533142.416334,86.469117,0.75,0.70,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,True
668,core_front_expanded_00168,all_qualified_trades,1166,197,22.067753,0.855060,1.542211e+07,4.117304,611.365293,900.976954,-10376.349181,-78789.306291,-56329.963714,5,2.962951e+06,655.647214,628649.038329,107.353191,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
724,core_front_expanded_00182,all_qualified_trades,1166,197,22.067753,0.855060,1.542211e+07,4.117304,611.365293,900.976954,-10376.349181,-78789.306291,-56329.963714,5,2.962951e+06,655.647214,628649.038329,107.353191,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
788,core_front_expanded_00198,all_qualified_trades,1166,197,22.067753,0.855060,1.542211e+07,4.117304,611.365293,900.976954,-10376.349181,-78789.306291,-56329.963714,5,2.962951e+06,655.647214,628649.038329,107.353191,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
188,core_front_expanded_00048,all_qualified_trades,1169,198,21.946963,0.853721,1.540608e+07,4.083939,611.227822,908.046066,-10376.349181,-78789.306291,-56329.963714,5,2.974168e+06,648.743117,547498.735468,91.805130,0.65,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,False,True,True
316,core_front_expanded_00080,all_qualified_trades,1169,198,21.946963,0.853721,1.540608e+07,4.083939,611.227822,908.046066,-10376.349181,-78789.306291,-56329.963714,5,2.974168e+06,648.743117,547498.735468,91.805130,0.65,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,False,True,True
172,core_front_expanded_00044,all_qualified_trades,1192,202,21.926174,0.855705,1.569867e+07,4.141350,611.202385,899.763851,-10376.349181,-78789.306291,-56329.963714,5,3.039349e+06,648.174329,564899.888681,94.835001,0.65,0.65,66.0,14.5,0.65,0.7,66.0,10.0,0.7,0.7,False,True,True
300,core_front_expanded_00076,all_qualified_trades,1192,202,21.926174,0.855705,1.569867e+07,4.141350,611.202385,899.763851,-10376.349181,-78789.306291,-56329.963714,5,3.039349e+06,648.174329,564899.888681,94.835001,0.65,0.65,64.0,14.5,0.65,0.7,66.0,10.0,0.7,0.7,False,True,True
1148,core_front_expanded_00288,all_qualified_trades,1135,190,22.355947,0.858150,1.523357e+07,4.187924,611.130176,899.315728,-10376.349181,-78789.306291,-55420.870999,5,2.973148e+06,682.357688,614292.719195,102.240484,0.75,0.70,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,True
1204,core_front_expanded_00302,all_qualified_trades,1135,190,22.355947,0.858150,1.523357e+07,4.187924,611.130176,899.315728,-10376.349181,-78789.306291,-55420.870999,5,2.973148e+06,682.357688,614292.719195,102.240484,0.75,0.70,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,True
1268,core_front_expanded_00318,all_qualified_trades,1135,190,22.355947,0.858150,1.523357e+07,4.187924,611.130176,899.315728,-10376.349181,-78789.306291,-55420.870999,5,2.973148e+06,682.357688,614292.719195,102.240484,0.75,0.70,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,True

30D anchor reference rows:

,candidate_id,selection_universe,trades,unique_trade_dates,avg_tenor,win_rate,total_pnl,profit_factor,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,pnl_2025,avg_pnl_per_day_2025,pnl_2026,avg_pnl_per_day_2026,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,front_log_tighter_than_back,front_RSI_tighter_than_back,front_forecast_floor_tighter_than_back
3,core_front_expanded_00001,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.65,0.65,68.0,10.0,0.65,0.7,68.0,8.5,0.7,0.7,False,True,True
7,core_front_expanded_00002,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.65,0.65,68.0,10.0,0.65,0.7,68.0,10.0,0.7,0.7,False,True,True
11,core_front_expanded_00003,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.65,0.65,68.0,10.0,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
15,core_front_expanded_00004,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.65,0.65,68.0,10.0,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
19,core_front_expanded_00005,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.65,0.65,68.0,11.5,0.65,0.7,68.0,8.5,0.7,0.7,False,True,True
23,core_front_expanded_00006,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.65,0.65,68.0,11.5,0.65,0.7,68.0,10.0,0.7,0.7,False,True,True
27,core_front_expanded_00007,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.65,0.65,68.0,11.5,0.70,0.7,68.0,8.5,0.7,0.7,False,True,True
31,core_front_expanded_00008,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.65,0.65,68.0,11.5,0.70,0.7,68.0,10.0,0.7,0.7,False,True,True
35,core_front_expanded_00009,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.65,0.65,68.0,13.0,0.65,0.7,68.0,8.5,0.7,0.7,False,True,True
39,core_front_expanded_00010,thirty_day_anchor_only,149,149,30.0,0.912752,2.609075e+06,6.14471,583.685595,760.748549,-3455.697445,-7548.166806,-1363.370357,1,522043.942659,470.309858,206722.762055,255.213286,0.65,0.65,68.0,13.0,0.65,0.7,68.0,10.0,0.7,0.7,False,True,True

Boundary diagnostics — parameters where >=50% of top candidates sit at min or max:

                         selection_universe  top_n                    parameter  grid_min  grid_max  top_min  top_max  top_mode  share_top_at_grid_min  share_top_at_grid_max  count_top_at_grid_min  count_top_at_grid_max  boundary_warning
10                     all_qualified_trades     50               Back_RSI14_max     70.00     70.00    70.00    70.00     70.00                   1.00                   1.00                     50                     50              True
11                     all_qualified_trades     50    Back_forecast_vol_pct_min      8.50      8.50     8.50     8.50      8.50                   1.00                   1.00                     50                     50              True
8                      all_qualified_trades     50           Back_model_vrp_log      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
9                      all_qualified_trades     50             Back_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
3                      all_qualified_trades     50   Front_forecast_vol_pct_min     10.00     14.50    14.50    14.50     14.50                   0.00                   1.00                      0                     50              True
1                      all_qualified_trades     50            Front_model_vrp_z      0.65      0.70     0.65     0.70      0.65                   0.62                   0.38                     31                     19              True
6                      all_qualified_trades     50             Middle_RSI14_max     66.00     68.00    66.00    68.00     66.00                   0.64                   0.36                     32                     18              True
7                      all_qualified_trades     50  Middle_forecast_vol_pct_min      8.50     10.00     8.50    10.00     10.00                   0.38                   0.62                     19                     31              True
4                      all_qualified_trades     50         Middle_model_vrp_log      0.65      0.70     0.65     0.70      0.70                   0.22                   0.78                     11                     39              True
5                      all_qualified_trades     50           Middle_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
22  one_trade_per_bucket_per_date_best_rank     50               Back_RSI14_max     70.00     70.00    70.00    70.00     70.00                   1.00                   1.00                     50                     50              True
23  one_trade_per_bucket_per_date_best_rank     50    Back_forecast_vol_pct_min      8.50      8.50     8.50     8.50      8.50                   1.00                   1.00                     50                     50              True
20  one_trade_per_bucket_per_date_best_rank     50           Back_model_vrp_log      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
21  one_trade_per_bucket_per_date_best_rank     50             Back_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
15  one_trade_per_bucket_per_date_best_rank     50   Front_forecast_vol_pct_min     10.00     14.50    14.50    14.50     14.50                   0.00                   1.00                      0                     50              True
13  one_trade_per_bucket_per_date_best_rank     50            Front_model_vrp_z      0.65      0.70     0.65     0.70      0.65                   0.80                   0.20                     40                     10              True
18  one_trade_per_bucket_per_date_best_rank     50             Middle_RSI14_max     66.00     68.00    66.00    68.00     68.00                   0.40                   0.60                     20                     30              True
19  one_trade_per_bucket_per_date_best_rank     50  Middle_forecast_vol_pct_min      8.50     10.00     8.50    10.00      8.50                   0.50                   0.50                     25                     25              True
16  one_trade_per_bucket_per_date_best_rank     50         Middle_model_vrp_log      0.65      0.70     0.65     0.70      0.70                   0.20                   0.80                     10                     40              True
17  one_trade_per_bucket_per_date_best_rank     50           Middle_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
34             one_trade_per_date_best_rank     50               Back_RSI14_max     70.00     70.00    70.00    70.00     70.00                   1.00                   1.00                     50                     50              True
35             one_trade_per_date_best_rank     50    Back_forecast_vol_pct_min      8.50      8.50     8.50     8.50      8.50                   1.00                   1.00                     50                     50              True
32             one_trade_per_date_best_rank     50           Back_model_vrp_log      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
33             one_trade_per_date_best_rank     50             Back_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
27             one_trade_per_date_best_rank     50   Front_forecast_vol_pct_min     10.00     14.50    13.00    14.50     14.50                   0.00                   0.64                      0                     32              True
24             one_trade_per_date_best_rank     50          Front_model_vrp_log      0.65      0.75     0.65     0.75      0.65                   0.56                   0.12                     28                      6              True
25             one_trade_per_date_best_rank     50            Front_model_vrp_z      0.65      0.70     0.65     0.65      0.65                   1.00                   0.00                     50                      0              True
30             one_trade_per_date_best_rank     50             Middle_RSI14_max     66.00     68.00    66.00    68.00     68.00                   0.28                   0.72                     14                     36              True
31             one_trade_per_date_best_rank     50  Middle_forecast_vol_pct_min      8.50     10.00     8.50    10.00      8.50                   0.50                   0.50                     25                     25              True
28             one_trade_per_date_best_rank     50         Middle_model_vrp_log      0.65      0.70     0.65     0.70      0.70                   0.32                   0.68                     16                     34              True
29             one_trade_per_date_best_rank     50           Middle_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
46                   thirty_day_anchor_only     50               Back_RSI14_max     70.00     70.00    70.00    70.00     70.00                   1.00                   1.00                     50                     50              True
47                   thirty_day_anchor_only     50    Back_forecast_vol_pct_min      8.50      8.50     8.50     8.50      8.50                   1.00                   1.00                     50                     50              True
44                   thirty_day_anchor_only     50           Back_model_vrp_log      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
45                   thirty_day_anchor_only     50             Back_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
36                   thirty_day_anchor_only     50          Front_model_vrp_log      0.65      0.75     0.65     0.65      0.65                   1.00                   0.00                     50                      0              True
37                   thirty_day_anchor_only     50            Front_model_vrp_z      0.65      0.70     0.65     0.65      0.65                   1.00                   0.00                     50                      0              True
42                   thirty_day_anchor_only     50             Middle_RSI14_max     66.00     68.00    66.00    68.00     68.00                   0.32                   0.68                     16                     34              True
43                   thirty_day_anchor_only     50  Middle_forecast_vol_pct_min      8.50     10.00     8.50    10.00      8.50                   0.50                   0.50                     25                     25              True
40                   thirty_day_anchor_only     50         Middle_model_vrp_log      0.65      0.70     0.65     0.70      0.65                   0.52                   0.48                     26                     24              True
41                   thirty_day_anchor_only     50           Middle_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True

Pass diagnostics sample:

                 candidate_id  pass_rows_all_dates  pass_rows_with_outcomes  Front_pass_rows_all_dates  Middle_pass_rows_all_dates  Back_pass_rows_all_dates  Front_model_vrp_log  Front_model_vrp_z  Front_RSI14_max  Front_forecast_vol_pct_min  Middle_model_vrp_log  Middle_model_vrp_z  Middle_RSI14_max  Middle_forecast_vol_pct_min
0   core_front_expanded_00001                 1376                     1376                        482                         445                       449                 0.65               0.65             68.0                        10.0                  0.65                 0.7              68.0                          8.5
1   core_front_expanded_00002                 1360                     1360                        482                         429                       449                 0.65               0.65             68.0                        10.0                  0.65                 0.7              68.0                         10.0
2   core_front_expanded_00003                 1353                     1353                        482                         422                       449                 0.65               0.65             68.0                        10.0                  0.70                 0.7              68.0                          8.5
3   core_front_expanded_00004                 1337                     1337                        482                         406                       449                 0.65               0.65             68.0                        10.0                  0.70                 0.7              68.0                         10.0
4   core_front_expanded_00005                 1341                     1341                        447                         445                       449                 0.65               0.65             68.0                        11.5                  0.65                 0.7              68.0                          8.5
5   core_front_expanded_00006                 1325                     1325                        447                         429                       449                 0.65               0.65             68.0                        11.5                  0.65                 0.7              68.0                         10.0
6   core_front_expanded_00007                 1318                     1318                        447                         422                       449                 0.65               0.65             68.0                        11.5                  0.70                 0.7              68.0                          8.5
7   core_front_expanded_00008                 1302                     1302                        447                         406                       449                 0.65               0.65             68.0                        11.5                  0.70                 0.7              68.0                         10.0
8   core_front_expanded_00009                 1301                     1301                        407                         445                       449                 0.65               0.65             68.0                        13.0                  0.65                 0.7              68.0                          8.5
9   core_front_expanded_00010                 1285                     1285                        407                         429                       449                 0.65               0.65             68.0                        13.0                  0.65                 0.7              68.0                         10.0
10  core_front_expanded_00011                 1278                     1278                        407                         422                       449                 0.65               0.65             68.0                        13.0                  0.70                 0.7              68.0                          8.5
11  core_front_expanded_00012                 1262                     1262                        407                         406                       449                 0.65               0.65             68.0                        13.0                  0.70                 0.7              68.0                         10.0
12  core_front_expanded_00013                 1220                     1220                        326                         445                       449                 0.65               0.65             68.0                        14.5                  0.65                 0.7              68.0                          8.5
13  core_front_expanded_00014                 1204                     1204                        326                         429                       449                 0.65               0.65             68.0                        14.5                  0.65                 0.7              68.0                         10.0
14  core_front_expanded_00015                 1197                     1197                        326                         422                       449                 0.65               0.65             68.0                        14.5                  0.70                 0.7              68.0                          8.5
15  core_front_expanded_00016                 1181                     1181                        326                         406                       449                 0.65               0.65             68.0                        14.5                  0.70                 0.7              68.0                         10.0
16  core_front_expanded_00017                 1366                     1366                        472                         445                       449                 0.65               0.65             66.0                        10.0                  0.65                 0.7              68.0                          8.5
17  core_front_expanded_00018                 1350                     1350                        472                         429                       449                 0.65               0.65             66.0                        10.0                  0.65                 0.7              68.0                         10.0
18  core_front_expanded_00019                 1342                     1342                        472                         421                       449                 0.65               0.65             66.0                        10.0                  0.65                 0.7              66.0                          8.5
19  core_front_expanded_00020                 1338                     1338                        472                         417                       449                 0.65               0.65             66.0                        10.0                  0.65                 0.7              66.0                         10.0
20  core_front_expanded_00021                 1343                     1343                        472                         422                       449                 0.65               0.65             66.0                        10.0                  0.70                 0.7              68.0                          8.5
21  core_front_expanded_00022                 1327                     1327                        472                         406                       449                 0.65               0.65             66.0                        10.0                  0.70                 0.7              68.0                         10.0
22  core_front_expanded_00023                 1319                     1319                        472                         398                       449                 0.65               0.65             66.0                        10.0                  0.70                 0.7              66.0                          8.5
23  core_front_expanded_00024                 1315                     1315                        472                         394                       449                 0.65               0.65             66.0                        10.0                  0.70                 0.7              66.0                         10.0
24  core_front_expanded_00025                 1338                     1338                        444                         445                       449                 0.65               0.65             66.0                        11.5                  0.65                 0.7              68.0                          8.5

Saved outputs:
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\06_core_front_expanded_sweep_candidate_summary_20260704_215631.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\06_core_front_expanded_sweep_by_bucket_20260704_215631.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\06_core_front_expanded_sweep_by_tenor_20260704_215631.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\06_core_front_expanded_sweep_by_year_20260704_215631.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\06_core_front_expanded_sweep_candidate_pass_diagnostics_20260704_215631.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\06_core_front_expanded_sweep_boundary_diagnostics_20260704_215631.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\06_core_front_expanded_sweep_selected_trade_panel_20260704_215631.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\06_core_front_expanded_sweep_validation_20260704_215631.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\06_core_front_expanded_sweep_manifest_20260704_215631.json

CELL 8 PASSED

In [11]:
# ======================================================================================
# Cell 9 — Candidate ranking and robustness diagnostics
# ======================================================================================
#
# Objective:
#   Rank the expanded Cell 8 Core candidates using robustness diagnostics, not pure
#   avg P&L/day alone.
#
# Inputs:
#   06_core_front_expanded_sweep_candidate_summary_*.csv
#   06_core_front_expanded_sweep_by_bucket_*.csv
#   06_core_front_expanded_sweep_by_tenor_*.csv
#   06_core_front_expanded_sweep_by_year_*.csv
#   06_core_front_expanded_sweep_boundary_diagnostics_*.csv
#
# Outputs:
#   07_core_candidate_ranked_summary_*.csv
#   07_core_candidate_ranked_by_bucket_*.csv
#   07_core_candidate_ranked_by_tenor_*.csv
#   07_core_candidate_ranked_by_year_*.csv
#   07_core_candidate_boundary_review_*.csv
#   07_core_candidate_ranking_validation_*.csv
#   07_core_candidate_ranking_manifest_*.json
#
# Primary selection universe for candidate ranking:
#   one_trade_per_bucket_per_date_best_rank
#
# Primary metric remains:
#   avg_pnl_per_day
#
# Robustness screens:
#   - enough trades
#   - positive 2025 avg P&L/day
#   - positive 2026 avg P&L/day
#   - acceptable P&L/day drawdown
#   - acceptable worst 20-trade P&L/day sum
#   - no increase in large-loss count beyond tolerance
#   - positive bucket-level P&L/day across Front/Middle/Back
#   - year/bucket/tenor diagnostics retained for review
#
# Important:
#   This cell does NOT select final thresholds.
#   This cell does NOT run another sweep.
#   This cell does NOT expand the grid.
#   This cell does NOT change sizing.
#   This cell does NOT lock production.
# ======================================================================================

from pathlib import Path
from datetime import datetime
import json

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 260)
pd.set_option("display.width", 420)

# ======================================================================================
# 0. Fallback config
# ======================================================================================

if "PROJECT_ROOT" not in globals():
    PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

if "NEW_BRANCH" not in globals():
    NEW_BRANCH = "vrp_unified_fds_core_signal_threshold_research_v1"

if "OUT_PROCESSED_DIR" not in globals():
    OUT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / NEW_BRANCH
    OUT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

if "OUT_AUDIT_DIR" not in globals():
    OUT_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / NEW_BRANCH
    OUT_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

CELL9_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

PRIMARY_SELECTION_UNIVERSE = "one_trade_per_bucket_per_date_best_rank"
PRIMARY_RANKING_METRIC = "avg_pnl_per_day"

# These are ranking/review screens, not production locks.
ROBUSTNESS_SCREEN_CONFIG = {
    "min_trades": 375,
    "min_unique_trade_dates": 175,
    "min_avg_pnl_per_day": 450.0,
    "min_avg_pnl_per_day_2025": 0.0,
    "min_avg_pnl_per_day_2026": 0.0,
    "min_pnl_per_day_drawdown": -40_000.0,
    "min_worst_20_trade_pnl_per_day_sum": -35_000.0,
    "max_trades_le_neg_100k": 2,
    "min_bucket_avg_pnl_per_day": 0.0,
    "min_positive_bucket_count": 3,
}

TOP_N_REVIEW = 50

# ======================================================================================
# 1. Helpers
# ======================================================================================

def latest_file(directory: Path, pattern: str, required: bool = True) -> Path | None:
    matches = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if matches:
        return matches[0]
    if required:
        raise FileNotFoundError(f"No file found in {directory} matching {pattern}")
    return None


def coerce_numeric(df: pd.DataFrame, exclude_cols=None) -> pd.DataFrame:
    if exclude_cols is None:
        exclude_cols = set()
    else:
        exclude_cols = set(exclude_cols)

    out = df.copy()

    for c in out.columns:
        if c in exclude_cols:
            continue
        if out[c].dtype == "object":
            continue
        out[c] = pd.to_numeric(out[c], errors="ignore")

    return out


def safe_numeric(s: pd.Series) -> pd.Series:
    x = pd.to_numeric(s, errors="coerce").replace([np.inf, -np.inf], np.nan)

    if x.notna().any():
        return x

    return pd.Series(np.nan, index=s.index)


def percentile_score(series: pd.Series, higher_is_better: bool = True) -> pd.Series:
    """
    Return 0-1 percentile scores.

    higher_is_better=True:
        highest value gets highest score.

    higher_is_better=False:
        lowest value gets highest score.
    """
    x = safe_numeric(series)

    if x.notna().sum() <= 1:
        return pd.Series(0.5, index=series.index)

    fill_value = x.median()
    x = x.fillna(fill_value)

    if higher_is_better:
        return x.rank(pct=True, method="average", ascending=True)

    return x.rank(pct=True, method="average", ascending=False)


def add_param_boundary_flags(df: pd.DataFrame, param_cols: list[str]) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Add per-candidate min/max boundary flags based on values present in the candidate universe.
    """
    out = df.copy()
    rows = []

    for col in param_cols:
        if col not in out.columns:
            continue

        vals = pd.to_numeric(out[col], errors="coerce").dropna().unique().tolist()

        if not vals:
            continue

        grid_min = min(vals)
        grid_max = max(vals)

        min_flag = f"{col}_at_grid_min"
        max_flag = f"{col}_at_grid_max"

        out[min_flag] = pd.to_numeric(out[col], errors="coerce").eq(grid_min)
        out[max_flag] = pd.to_numeric(out[col], errors="coerce").eq(grid_max)

        rows.append({
            "parameter": col,
            "grid_min": grid_min,
            "grid_max": grid_max,
            "candidate_count_at_min": int(out[min_flag].sum()),
            "candidate_count_at_max": int(out[max_flag].sum()),
            "candidate_share_at_min": float(out[min_flag].mean()),
            "candidate_share_at_max": float(out[max_flag].mean()),
        })

    return out, pd.DataFrame(rows)


def flatten_pivot_columns(pivot_df: pd.DataFrame) -> pd.DataFrame:
    pivot_df = pivot_df.copy()
    pivot_df.columns = [
        "_".join([str(x) for x in col if str(x) != ""])
        if isinstance(col, tuple)
        else str(col)
        for col in pivot_df.columns
    ]
    return pivot_df.reset_index()


def build_bucket_diagnostics(by_bucket: pd.DataFrame, universe: str) -> pd.DataFrame:
    d = by_bucket[by_bucket["selection_universe"].eq(universe)].copy()

    if d.empty:
        return pd.DataFrame()

    metrics = [
        "trades",
        "unique_trade_dates",
        "avg_pnl_per_day",
        "median_pnl_per_day",
        "profit_factor_pnl_per_day",
        "pnl_per_day_drawdown",
        "worst_20_trade_pnl_per_day_sum",
        "avg_pnl_per_day_2025",
        "avg_pnl_per_day_2026",
        "trades_le_neg_100k",
    ]

    available_metrics = [m for m in metrics if m in d.columns]

    pivot = d.pivot_table(
        index="candidate_id",
        columns="tenor_bucket",
        values=available_metrics,
        aggfunc="first",
    )

    out = flatten_pivot_columns(pivot)

    # Rename from metric_bucket to Bucket_metric for easier reading.
    rename_map = {}
    for c in out.columns:
        if "_" not in c or c == "candidate_id":
            continue
        parts = c.split("_")
        bucket = parts[-1]
        metric = "_".join(parts[:-1])
        if bucket in ["Front", "Middle", "Back"]:
            rename_map[c] = f"{bucket}_{metric}"

    out = out.rename(columns=rename_map)

    bucket_avg_cols = [
        c for c in [
            "Front_avg_pnl_per_day",
            "Middle_avg_pnl_per_day",
            "Back_avg_pnl_per_day",
        ]
        if c in out.columns
    ]

    if bucket_avg_cols:
        out["min_bucket_avg_pnl_per_day"] = out[bucket_avg_cols].min(axis=1)
        out["max_bucket_avg_pnl_per_day"] = out[bucket_avg_cols].max(axis=1)
        out["positive_bucket_count"] = out[bucket_avg_cols].gt(0).sum(axis=1)
        out["all_buckets_positive_avg_pnl_per_day"] = out["positive_bucket_count"].eq(len(bucket_avg_cols))

    return out


def build_tenor_diagnostics(by_tenor: pd.DataFrame, universe: str) -> pd.DataFrame:
    d = by_tenor[by_tenor["selection_universe"].eq(universe)].copy()

    if d.empty:
        return pd.DataFrame()

    # Candidate-level tenor stability diagnostics.
    g = d.groupby("candidate_id", as_index=False).agg(
        tenors_active=("tenor", "nunique"),
        min_tenor_avg_pnl_per_day=("avg_pnl_per_day", "min"),
        max_tenor_avg_pnl_per_day=("avg_pnl_per_day", "max"),
        positive_tenor_count=("avg_pnl_per_day", lambda x: int((pd.to_numeric(x, errors="coerce") > 0).sum())),
        negative_tenor_count=("avg_pnl_per_day", lambda x: int((pd.to_numeric(x, errors="coerce") <= 0).sum())),
    )

    front = d[d["tenor_bucket"].eq("Front")].copy()

    if not front.empty:
        front_g = front.groupby("candidate_id", as_index=False).agg(
            front_tenors_active=("tenor", "nunique"),
            front_min_tenor_avg_pnl_per_day=("avg_pnl_per_day", "min"),
            front_positive_tenor_count=("avg_pnl_per_day", lambda x: int((pd.to_numeric(x, errors="coerce") > 0).sum())),
            front_negative_tenor_count=("avg_pnl_per_day", lambda x: int((pd.to_numeric(x, errors="coerce") <= 0).sum())),
        )

        g = g.merge(front_g, on="candidate_id", how="left", validate="one_to_one")

    # Add explicit 9/12/15 avg P&L/day where present.
    front_tenor_values = d[d["tenor"].isin([9, 12, 15])].pivot_table(
        index="candidate_id",
        columns="tenor",
        values="avg_pnl_per_day",
        aggfunc="first",
    )

    if not front_tenor_values.empty:
        front_tenor_values = front_tenor_values.rename(
            columns={
                9: "tenor_9_avg_pnl_per_day",
                12: "tenor_12_avg_pnl_per_day",
                15: "tenor_15_avg_pnl_per_day",
            }
        ).reset_index()

        g = g.merge(front_tenor_values, on="candidate_id", how="left", validate="one_to_one")

    return g


def build_year_diagnostics(by_year: pd.DataFrame, universe: str) -> pd.DataFrame:
    d = by_year[by_year["selection_universe"].eq(universe)].copy()

    if d.empty:
        return pd.DataFrame()

    d["year"] = pd.to_numeric(d["year"], errors="coerce").astype("Int64")

    g = d.groupby("candidate_id", as_index=False).agg(
        years_active=("year", "nunique"),
        min_year_avg_pnl_per_day=("avg_pnl_per_day", "min"),
        max_year_avg_pnl_per_day=("avg_pnl_per_day", "max"),
        positive_year_count=("avg_pnl_per_day", lambda x: int((pd.to_numeric(x, errors="coerce") > 0).sum())),
        negative_year_count=("avg_pnl_per_day", lambda x: int((pd.to_numeric(x, errors="coerce") <= 0).sum())),
        min_year_trade_count=("trades", "min"),
    )

    year_pivot = d.pivot_table(
        index="candidate_id",
        columns="year",
        values="avg_pnl_per_day",
        aggfunc="first",
    )

    if not year_pivot.empty:
        year_pivot = year_pivot.rename(
            columns={year: f"year_{int(year)}_avg_pnl_per_day" for year in year_pivot.columns if pd.notna(year)}
        ).reset_index()

        g = g.merge(year_pivot, on="candidate_id", how="left", validate="one_to_one")

    return g


def add_robustness_screens(df: pd.DataFrame) -> pd.DataFrame:
    d = df.copy()
    cfg = ROBUSTNESS_SCREEN_CONFIG

    d["screen_min_trades"] = pd.to_numeric(d["trades"], errors="coerce") >= cfg["min_trades"]
    d["screen_min_unique_trade_dates"] = pd.to_numeric(d["unique_trade_dates"], errors="coerce") >= cfg["min_unique_trade_dates"]
    d["screen_avg_pnl_per_day"] = pd.to_numeric(d["avg_pnl_per_day"], errors="coerce") >= cfg["min_avg_pnl_per_day"]
    d["screen_2025_positive"] = pd.to_numeric(d["avg_pnl_per_day_2025"], errors="coerce") >= cfg["min_avg_pnl_per_day_2025"]
    d["screen_2026_positive"] = pd.to_numeric(d["avg_pnl_per_day_2026"], errors="coerce") >= cfg["min_avg_pnl_per_day_2026"]
    d["screen_drawdown"] = pd.to_numeric(d["pnl_per_day_drawdown"], errors="coerce") >= cfg["min_pnl_per_day_drawdown"]
    d["screen_worst20"] = pd.to_numeric(d["worst_20_trade_pnl_per_day_sum"], errors="coerce") >= cfg["min_worst_20_trade_pnl_per_day_sum"]
    d["screen_large_loss_count"] = pd.to_numeric(d["trades_le_neg_100k"], errors="coerce") <= cfg["max_trades_le_neg_100k"]

    if "min_bucket_avg_pnl_per_day" in d.columns:
        d["screen_bucket_min_positive"] = pd.to_numeric(d["min_bucket_avg_pnl_per_day"], errors="coerce") >= cfg["min_bucket_avg_pnl_per_day"]
    else:
        d["screen_bucket_min_positive"] = False

    if "positive_bucket_count" in d.columns:
        d["screen_all_buckets_positive"] = pd.to_numeric(d["positive_bucket_count"], errors="coerce") >= cfg["min_positive_bucket_count"]
    else:
        d["screen_all_buckets_positive"] = False

    screen_cols = [
        "screen_min_trades",
        "screen_min_unique_trade_dates",
        "screen_avg_pnl_per_day",
        "screen_2025_positive",
        "screen_2026_positive",
        "screen_drawdown",
        "screen_worst20",
        "screen_large_loss_count",
        "screen_bucket_min_positive",
        "screen_all_buckets_positive",
    ]

    d["robustness_screen_pass"] = d[screen_cols].all(axis=1)
    d["robustness_screen_pass_count"] = d[screen_cols].sum(axis=1)
    d["robustness_screen_fail_count"] = len(screen_cols) - d["robustness_screen_pass_count"]

    failed_items = []
    for _, row in d.iterrows():
        failed = [c.replace("screen_", "") for c in screen_cols if not bool(row[c])]
        failed_items.append(", ".join(failed))

    d["robustness_failed_screens"] = failed_items

    return d


def add_composite_score(df: pd.DataFrame) -> pd.DataFrame:
    d = df.copy()

    score_specs = {
        "avg_pnl_per_day": {"weight": 0.25, "higher_is_better": True},
        "profit_factor_pnl_per_day": {"weight": 0.12, "higher_is_better": True},
        "pnl_per_day_drawdown": {"weight": 0.14, "higher_is_better": True},
        "worst_20_trade_pnl_per_day_sum": {"weight": 0.12, "higher_is_better": True},
        "avg_pnl_per_day_2026": {"weight": 0.16, "higher_is_better": True},
        "avg_pnl_per_day_2025": {"weight": 0.06, "higher_is_better": True},
        "min_bucket_avg_pnl_per_day": {"weight": 0.08, "higher_is_better": True},
        "trades": {"weight": 0.04, "higher_is_better": True},
        "trades_le_neg_100k": {"weight": 0.03, "higher_is_better": False},
    }

    # If profit_factor_pnl_per_day is missing, fall back to profit_factor.
    if "profit_factor_pnl_per_day" not in d.columns and "profit_factor" in d.columns:
        d["profit_factor_pnl_per_day"] = d["profit_factor"]

    raw_score_cols = []

    for metric, spec in score_specs.items():
        if metric not in d.columns:
            continue

        score_col = f"score_component_{metric}"
        d[score_col] = percentile_score(d[metric], higher_is_better=spec["higher_is_better"])
        d[score_col] = d[score_col] * spec["weight"]
        raw_score_cols.append(score_col)

    d["robustness_score"] = d[raw_score_cols].sum(axis=1) if raw_score_cols else np.nan

    # Small penalty for sitting at expanded-grid max on Front forecast vol floor.
    # This is not a disqualifier; it is a warning that more expansion may be needed.
    if "Front_forecast_vol_pct_min_at_grid_max" in d.columns:
        d["front_forecast_floor_boundary_penalty"] = np.where(
            d["Front_forecast_vol_pct_min_at_grid_max"].astype(bool),
            0.015,
            0.0,
        )
    else:
        d["front_forecast_floor_boundary_penalty"] = 0.0

    d["robustness_score_after_boundary_penalty"] = (
        d["robustness_score"] - d["front_forecast_floor_boundary_penalty"]
    )

    d["robustness_rank"] = (
        d["robustness_score_after_boundary_penalty"]
        .rank(method="min", ascending=False)
        .astype(int)
    )

    d["avg_pnl_per_day_rank"] = (
        pd.to_numeric(d["avg_pnl_per_day"], errors="coerce")
        .rank(method="min", ascending=False)
        .astype(int)
    )

    return d


# ======================================================================================
# 2. Load Cell 8 outputs
# ======================================================================================

candidate_summary_path = latest_file(
    OUT_AUDIT_DIR,
    "06_core_front_expanded_sweep_candidate_summary_*.csv",
    required=True,
)

by_bucket_path = latest_file(
    OUT_AUDIT_DIR,
    "06_core_front_expanded_sweep_by_bucket_*.csv",
    required=True,
)

by_tenor_path = latest_file(
    OUT_AUDIT_DIR,
    "06_core_front_expanded_sweep_by_tenor_*.csv",
    required=True,
)

by_year_path = latest_file(
    OUT_AUDIT_DIR,
    "06_core_front_expanded_sweep_by_year_*.csv",
    required=True,
)

boundary_diagnostics_path = latest_file(
    OUT_AUDIT_DIR,
    "06_core_front_expanded_sweep_boundary_diagnostics_*.csv",
    required=True,
)

summary = pd.read_csv(candidate_summary_path)
by_bucket = pd.read_csv(by_bucket_path)
by_tenor = pd.read_csv(by_tenor_path)
by_year = pd.read_csv(by_year_path)
boundary_diagnostics = pd.read_csv(boundary_diagnostics_path)

# Parse dates where available.
for df in [summary, by_bucket, by_tenor, by_year]:
    for c in ["date_min", "date_max"]:
        if c in df.columns:
            df[c] = pd.to_datetime(df[c], errors="coerce")

# ======================================================================================
# 3. Build ranking table
# ======================================================================================

primary = summary[summary["selection_universe"].eq(PRIMARY_SELECTION_UNIVERSE)].copy()

if primary.empty:
    raise RuntimeError(f"No rows found for primary selection universe: {PRIMARY_SELECTION_UNIVERSE}")

param_cols = [
    c for c in primary.columns
    if c.startswith("Front_")
    or c.startswith("Middle_")
    or c.startswith("Back_")
]

primary, param_boundary_summary = add_param_boundary_flags(primary, param_cols)

bucket_diag = build_bucket_diagnostics(by_bucket, PRIMARY_SELECTION_UNIVERSE)
tenor_diag = build_tenor_diagnostics(by_tenor, PRIMARY_SELECTION_UNIVERSE)
year_diag = build_year_diagnostics(by_year, PRIMARY_SELECTION_UNIVERSE)

ranked = primary.copy()

for diag_name, diag in [
    ("bucket", bucket_diag),
    ("tenor", tenor_diag),
    ("year", year_diag),
]:
    if not diag.empty:
        ranked = ranked.merge(
            diag,
            on="candidate_id",
            how="left",
            validate="one_to_one",
            suffixes=("", f"_{diag_name}"),
        )

ranked = add_robustness_screens(ranked)
ranked = add_composite_score(ranked)

ranked = ranked.sort_values(
    [
        "robustness_screen_pass",
        "robustness_score_after_boundary_penalty",
        "avg_pnl_per_day",
        "avg_pnl_per_day_2026",
        "pnl_per_day_drawdown",
        "trades",
    ],
    ascending=[False, False, False, False, False, False],
).reset_index(drop=True)

# Re-number display rank after sorting.
ranked.insert(0, "review_rank", np.arange(1, len(ranked) + 1))

# ======================================================================================
# 4. Build review subsets
# ======================================================================================

top_candidate_ids = ranked.head(TOP_N_REVIEW)["candidate_id"].tolist()
screen_pass_candidate_ids = ranked[ranked["robustness_screen_pass"]]["candidate_id"].tolist()

ranked_by_bucket = by_bucket[
    by_bucket["candidate_id"].isin(top_candidate_ids)
    & by_bucket["selection_universe"].eq(PRIMARY_SELECTION_UNIVERSE)
].copy()

ranked_by_tenor = by_tenor[
    by_tenor["candidate_id"].isin(top_candidate_ids)
    & by_tenor["selection_universe"].eq(PRIMARY_SELECTION_UNIVERSE)
].copy()

ranked_by_year = by_year[
    by_year["candidate_id"].isin(top_candidate_ids)
    & by_year["selection_universe"].eq(PRIMARY_SELECTION_UNIVERSE)
].copy()

# Add review rank to detail tables.
rank_map = ranked.set_index("candidate_id")["review_rank"].to_dict()

for df in [ranked_by_bucket, ranked_by_tenor, ranked_by_year]:
    df.insert(0, "review_rank", df["candidate_id"].map(rank_map))
    df.sort_values(
        [c for c in ["review_rank", "tenor_bucket_order", "tenor", "year"] if c in df.columns],
        inplace=True,
    )

# Boundary review specific to expanded sweep top candidates.
boundary_review = boundary_diagnostics.copy()

if "boundary_warning" in boundary_review.columns:
    boundary_review["boundary_warning"] = boundary_review["boundary_warning"].astype(bool)

boundary_review = boundary_review.sort_values(
    [c for c in ["selection_universe", "boundary_warning", "parameter"] if c in boundary_review.columns],
    ascending=[True, False, True][:len([c for c in ["selection_universe", "boundary_warning", "parameter"] if c in boundary_review.columns])],
).reset_index(drop=True)

# ======================================================================================
# 5. Save outputs
# ======================================================================================

ranked_summary_path = OUT_AUDIT_DIR / f"07_core_candidate_ranked_summary_{CELL9_TIMESTAMP}.csv"
ranked_by_bucket_path = OUT_AUDIT_DIR / f"07_core_candidate_ranked_by_bucket_{CELL9_TIMESTAMP}.csv"
ranked_by_tenor_path = OUT_AUDIT_DIR / f"07_core_candidate_ranked_by_tenor_{CELL9_TIMESTAMP}.csv"
ranked_by_year_path = OUT_AUDIT_DIR / f"07_core_candidate_ranked_by_year_{CELL9_TIMESTAMP}.csv"
boundary_review_path = OUT_AUDIT_DIR / f"07_core_candidate_boundary_review_{CELL9_TIMESTAMP}.csv"
param_boundary_summary_path = OUT_AUDIT_DIR / f"07_core_candidate_parameter_boundary_summary_{CELL9_TIMESTAMP}.csv"
validation_path = OUT_AUDIT_DIR / f"07_core_candidate_ranking_validation_{CELL9_TIMESTAMP}.csv"
manifest_path = OUT_AUDIT_DIR / f"07_core_candidate_ranking_manifest_{CELL9_TIMESTAMP}.json"

ranked.to_csv(ranked_summary_path, index=False)
ranked_by_bucket.to_csv(ranked_by_bucket_path, index=False)
ranked_by_tenor.to_csv(ranked_by_tenor_path, index=False)
ranked_by_year.to_csv(ranked_by_year_path, index=False)
boundary_review.to_csv(boundary_review_path, index=False)
param_boundary_summary.to_csv(param_boundary_summary_path, index=False)

# ======================================================================================
# 6. Validation
# ======================================================================================

validation_rows = []

def add_validation(check, status, detail):
    validation_rows.append({
        "check": check,
        "status": status,
        "detail": detail,
    })

required_summary_cols = [
    "candidate_id",
    "selection_universe",
    "trades",
    "unique_trade_dates",
    "avg_pnl_per_day",
    "avg_pnl_per_day_2025",
    "avg_pnl_per_day_2026",
    "pnl_per_day_drawdown",
    "worst_20_trade_pnl_per_day_sum",
    "trades_le_neg_100k",
]

missing_required_summary_cols = [c for c in required_summary_cols if c not in summary.columns]

add_validation(
    "cell8_candidate_summary_loaded",
    "PASS" if not summary.empty else "FAIL",
    f"rows={len(summary):,}; path={candidate_summary_path}",
)

add_validation(
    "required_summary_columns_available",
    "PASS" if not missing_required_summary_cols else "FAIL",
    f"missing={missing_required_summary_cols}",
)

add_validation(
    "primary_selection_universe_available",
    "PASS" if not primary.empty else "FAIL",
    f"primary_selection_universe={PRIMARY_SELECTION_UNIVERSE}; rows={len(primary):,}",
)

add_validation(
    "ranked_candidates_created",
    "PASS" if not ranked.empty else "FAIL",
    f"rows={len(ranked):,}",
)

add_validation(
    "candidate_ids_unique_in_ranked_summary",
    "PASS" if ranked["candidate_id"].is_unique else "FAIL",
    f"candidate_rows={len(ranked):,}; unique_candidates={ranked['candidate_id'].nunique():,}",
)

add_validation(
    "robustness_screen_created",
    "PASS" if "robustness_screen_pass" in ranked.columns else "FAIL",
    f"screen_pass_count={int(ranked['robustness_screen_pass'].sum()) if 'robustness_screen_pass' in ranked.columns else 'NA'}",
)

add_validation(
    "robustness_score_created",
    "PASS" if "robustness_score_after_boundary_penalty" in ranked.columns else "FAIL",
    f"non_null_scores={int(ranked['robustness_score_after_boundary_penalty'].notna().sum()) if 'robustness_score_after_boundary_penalty' in ranked.columns else 'NA'}",
)

add_validation(
    "bucket_diagnostics_created",
    "PASS" if not bucket_diag.empty else "WARN",
    f"rows={len(bucket_diag):,}",
)

add_validation(
    "tenor_diagnostics_created",
    "PASS" if not tenor_diag.empty else "WARN",
    f"rows={len(tenor_diag):,}",
)

add_validation(
    "year_diagnostics_created",
    "PASS" if not year_diag.empty else "WARN",
    f"rows={len(year_diag):,}",
)

boundary_warning_count = (
    int(boundary_review["boundary_warning"].sum())
    if "boundary_warning" in boundary_review.columns
    else 0
)

add_validation(
    "boundary_review_loaded",
    "PASS" if not boundary_review.empty else "WARN",
    f"rows={len(boundary_review):,}; boundary_warnings={boundary_warning_count:,}; path={boundary_diagnostics_path}",
)

front_fv_max_count = (
    int(ranked.get("Front_forecast_vol_pct_min_at_grid_max", pd.Series(False, index=ranked.index)).sum())
)

top25_front_fv_max_count = (
    int(
        ranked.head(25)
        .get("Front_forecast_vol_pct_min_at_grid_max", pd.Series(False, index=ranked.head(25).index))
        .sum()
    )
)

add_validation(
    "front_forecast_vol_floor_boundary_flag_created",
    "PASS" if "Front_forecast_vol_pct_min_at_grid_max" in ranked.columns else "WARN",
    f"all_ranked_at_max={front_fv_max_count:,}; top25_at_max={top25_front_fv_max_count:,}",
)

add_validation(
    "no_new_sweep",
    "PASS",
    "Cell 9 only ranks existing Cell 8 outputs.",
)

add_validation(
    "no_final_candidate_selection",
    "PASS",
    "Cell 9 creates ranked diagnostics only; no final lock.",
)

add_validation(
    "no_secondary",
    "PASS",
    "Core only.",
)

add_validation(
    "no_sizing_changes",
    "PASS",
    "No sizing fields changed.",
)

add_validation(
    "no_production_lock",
    "PASS",
    "No production threshold lock performed.",
)

validation = pd.DataFrame(validation_rows)
validation.to_csv(validation_path, index=False)

failures = validation[validation["status"] == "FAIL"]

manifest = {
    "notebook": "07_unified_fds_core_signal_threshold_research_v1.ipynb",
    "cell": "Cell 9 — Candidate ranking and robustness diagnostics",
    "timestamp": CELL9_TIMESTAMP,
    "primary_selection_universe": PRIMARY_SELECTION_UNIVERSE,
    "primary_ranking_metric": PRIMARY_RANKING_METRIC,
    "robustness_screen_config": ROBUSTNESS_SCREEN_CONFIG,
    "top_n_review": TOP_N_REVIEW,
    "candidate_summary_path": str(candidate_summary_path),
    "by_bucket_path": str(by_bucket_path),
    "by_tenor_path": str(by_tenor_path),
    "by_year_path": str(by_year_path),
    "boundary_diagnostics_path": str(boundary_diagnostics_path),
    "ranked_summary_path": str(ranked_summary_path),
    "ranked_by_bucket_path": str(ranked_by_bucket_path),
    "ranked_by_tenor_path": str(ranked_by_tenor_path),
    "ranked_by_year_path": str(ranked_by_year_path),
    "boundary_review_path": str(boundary_review_path),
    "param_boundary_summary_path": str(param_boundary_summary_path),
    "validation_path": str(validation_path),
    "ranked_candidate_count": int(len(ranked)),
    "robustness_screen_pass_count": int(ranked["robustness_screen_pass"].sum()),
    "boundary_warning_count": int(boundary_warning_count),
    "top25_front_forecast_floor_at_grid_max_count": int(top25_front_fv_max_count),
    "notes": [
        "Ranking diagnostics only.",
        "No new sweep.",
        "No final threshold selected.",
        "No Secondary.",
        "No sizing changes.",
        "No production lock.",
        "If top-ranked candidates remain at Front forecast-vol-floor max, consider another Front forecast-vol-floor expansion before locking.",
    ],
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2, default=str)

if not failures.empty:
    display(validation)
    raise RuntimeError("Cell 9 validation failed. Review validation output above.")

# ======================================================================================
# 7. Display review
# ======================================================================================

print("=" * 100)
print("Cell 9 — Candidate ranking and robustness diagnostics")
print("=" * 100)
print(f"Candidate summary:             {candidate_summary_path}")
print(f"Primary selection universe:    {PRIMARY_SELECTION_UNIVERSE}")
print(f"Ranked candidates:             {len(ranked):,}")
print(f"Robustness screen pass count:  {int(ranked['robustness_screen_pass'].sum()):,}")
print(f"Boundary warnings loaded:      {boundary_warning_count:,}")
print(f"Top 25 Front FV floor at max:  {top25_front_fv_max_count:,} / 25")
print("No new sweep:                  True")
print("No final candidate selection:  True")
print("No Secondary:                  True")
print("No sizing changes:             True")
print("No production lock:            True")

print()
print("Validation:")
display(validation)

main_display_cols = [
    "review_rank",
    "candidate_id",
    "robustness_screen_pass",
    "robustness_score_after_boundary_penalty",
    "avg_pnl_per_day_rank",
    "trades",
    "unique_trade_dates",
    "avg_tenor",
    "win_rate",
    "total_pnl",
    "profit_factor",
    "profit_factor_pnl_per_day",
    "avg_pnl_per_day",
    "median_pnl_per_day",
    "worst_trade_pnl_per_day",
    "pnl_per_day_drawdown",
    "worst_20_trade_pnl_per_day_sum",
    "trades_le_neg_100k",
    "avg_pnl_per_day_2025",
    "avg_pnl_per_day_2026",
    "min_bucket_avg_pnl_per_day",
    "positive_bucket_count",
    "min_tenor_avg_pnl_per_day",
    "front_min_tenor_avg_pnl_per_day",
    "positive_year_count",
    "negative_year_count",
    "Front_model_vrp_log",
    "Front_model_vrp_z",
    "Front_RSI14_max",
    "Front_forecast_vol_pct_min",
    "Middle_model_vrp_log",
    "Middle_model_vrp_z",
    "Middle_RSI14_max",
    "Middle_forecast_vol_pct_min",
    "Back_model_vrp_log",
    "Back_model_vrp_z",
    "Front_forecast_vol_pct_min_at_grid_max",
    "Front_model_vrp_log_at_grid_max",
    "robustness_failed_screens",
]

print()
print("Top 30 ranked candidates — robustness score:")
display(ranked[[c for c in main_display_cols if c in ranked.columns]].head(30))

print()
print("Candidates passing all robustness screens:")
screen_pass = ranked[ranked["robustness_screen_pass"]].copy()
display(screen_pass[[c for c in main_display_cols if c in screen_pass.columns]].head(50))

print()
print("Top 30 by raw avg P&L/day:")
raw_top = ranked.sort_values(
    ["avg_pnl_per_day", "profit_factor_pnl_per_day", "avg_pnl_per_day_2026", "trades"],
    ascending=[False, False, False, False],
).head(30)
display(raw_top[[c for c in main_display_cols if c in raw_top.columns]])

print()
print("Bucket detail for top 20 ranked candidates:")
display(ranked_by_bucket[ranked_by_bucket["review_rank"].le(20)])

print()
print("Tenor detail for top 20 ranked candidates:")
display(ranked_by_tenor[ranked_by_tenor["review_rank"].le(20)])

print()
print("Year detail for top 20 ranked candidates:")
display(ranked_by_year[ranked_by_year["review_rank"].le(20)])

print()
print("Boundary warnings from Cell 8:")
if "boundary_warning" in boundary_review.columns:
    display(
        boundary_review[boundary_review["boundary_warning"]]
        .sort_values(["selection_universe", "parameter"])
    )
else:
    display(boundary_review)

print()
print("Parameter boundary summary across ranked candidates:")
display(param_boundary_summary)

print()
print("Saved outputs:")
for p in [
    ranked_summary_path,
    ranked_by_bucket_path,
    ranked_by_tenor_path,
    ranked_by_year_path,
    boundary_review_path,
    param_boundary_summary_path,
    validation_path,
    manifest_path,
]:
    print(f"  {p}")

print("\nCELL 9 PASSED")

====================================================================================================
Cell 9 — Candidate ranking and robustness diagnostics
====================================================================================================
Candidate summary:             C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\06_core_front_expanded_sweep_candidate_summary_20260704_215631.csv
Primary selection universe:    one_trade_per_bucket_per_date_best_rank
Ranked candidates:             320
Robustness screen pass count:  80
Boundary warnings loaded:      41
Top 25 Front FV floor at max:  25 / 25
No new sweep:                  True
No final candidate selection:  True
No Secondary:                  True
No sizing changes:             True
No production lock:            True

Validation:

                                             check status                                             detail
0                   cell8_candidate_summary_loaded   PASS  rows=1,280; path=C:\Users\patri\vrp_project\da...
1               required_summary_columns_available   PASS                                         missing=[]
2             primary_selection_universe_available   PASS  primary_selection_universe=one_trade_per_bucke...
3                        ranked_candidates_created   PASS                                           rows=320
4           candidate_ids_unique_in_ranked_summary   PASS          candidate_rows=320; unique_candidates=320
5                        robustness_screen_created   PASS                               screen_pass_count=80
6                         robustness_score_created   PASS                                non_null_scores=320
7                       bucket_diagnostics_created   PASS                                           rows=320
8                        tenor_diagnostics_created   PASS                                           rows=320
9                         year_diagnostics_created   PASS                                           rows=320
10                          boundary_review_loaded   PASS  rows=48; boundary_warnings=41; path=C:\Users\p...
11  front_forecast_vol_floor_boundary_flag_created   PASS              all_ranked_at_max=80; top25_at_max=25
12                                    no_new_sweep   PASS         Cell 9 only ranks existing Cell 8 outputs.
13                    no_final_candidate_selection   PASS  Cell 9 creates ranked diagnostics only; no fin...
14                                    no_secondary   PASS                                         Core only.
15                               no_sizing_changes   PASS                          No sizing fields changed.
16                              no_production_lock   PASS            No production threshold lock performed.

Top 30 ranked candidates — robustness score:

,review_rank,candidate_id,robustness_screen_pass,robustness_score_after_boundary_penalty,avg_pnl_per_day_rank,trades,unique_trade_dates,avg_tenor,win_rate,total_pnl,profit_factor,profit_factor_pnl_per_day,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,avg_pnl_per_day_2025,avg_pnl_per_day_2026,min_bucket_avg_pnl_per_day,positive_bucket_count,min_tenor_avg_pnl_per_day,front_min_tenor_avg_pnl_per_day,positive_year_count,negative_year_count,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Front_forecast_vol_pct_min_at_grid_max,Front_model_vrp_log_at_grid_max,robustness_failed_screens
0,1,core_front_expanded_00168,True,0.846453,1,428,197,21.995327,0.855140,5.479290e+06,3.881266,2.897659,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
1,2,core_front_expanded_00182,True,0.846453,1,428,197,21.995327,0.855140,5.479290e+06,3.881266,2.897659,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
2,3,core_front_expanded_00198,True,0.846453,1,428,197,21.995327,0.855140,5.479290e+06,3.881266,2.897659,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
3,4,core_front_expanded_00167,True,0.839922,8,432,197,21.979167,0.856481,5.519880e+06,3.902610,2.913804,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
4,5,core_front_expanded_00181,True,0.839922,8,432,197,21.979167,0.856481,5.519880e+06,3.902610,2.913804,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
5,6,core_front_expanded_00197,True,0.839922,8,432,197,21.979167,0.856481,5.519880e+06,3.902610,2.913804,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
6,7,core_front_expanded_00248,True,0.835891,11,423,194,22.113475,0.855792,5.434757e+06,3.872530,2.879166,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
7,8,core_front_expanded_00262,True,0.835891,11,423,194,22.113475,0.855792,5.434757e+06,3.872530,2.879166,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
8,9,core_front_expanded_00278,True,0.835891,11,423,194,22.113475,0.855792,5.434757e+06,3.872530,2.879166,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
9,10,core_front_expanded_00183,True,0.820937,4,424,196,21.983491,0.853774,5.425318e+06,3.852885,2.878714,547.507072,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.656487,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,False,
10,11,core_front_expanded_00199,True,0.820937,4,424,196,21.983491,0.853774,5.425318e+06,3.852885,2.878714,547.507072,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.656487,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,False,
11,12,core_front_expanded_00247,True,0.820109,24,427,194,22.096019,0.857143,5.475347e+06,3.893984,2.895417,544.898750,874.092727,-10376.349181,-30723.516018,-24889.323006,2,662.144375,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,True,
12,13,core_front_expanded_00261,True,0.820109,24,427,194,22.096019,0.857143,5.475347e+06,3.893984,2.895417,544.898750,874.092727,-10376.349181,-30723.516018,-24889.323006,2,662.144375,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,True,
13,14,core_front_expanded_00277,True,0.820109,24,427,194,22.096019,0.857143,5.475347e+06,3.893984,2.895417,544.898750,874.092727,-10376.349181,-30723.516018,-24889.323006,2,662.144375,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,True,
14,15,core_front_expanded_00184,True,0.817875,6,424,196,22.004717,0.853774,5.429453e+06,3.855060,2.878688,547.499550,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.614524,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,False,
15,16,core_front_expanded_00200,True,0.817875,6,424,196,22.004717,0.853774,5.429453e+06,3.855060,2.878688,547.499550,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.614524,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,False,
16,17,core_front_expanded_00014,True,0.816828,17,438,203,21.910959,0.853881,5.567699e+06,3.891386,2.902244,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,631.734887,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,68.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,True,False,
17,18,core_front_expanded_00042,True,0.816828,17,438,203,21.910959,0.853881,5.567699e+06,3.891386,2.902244,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,631.734887,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,True,False,
18,19,core_front_expanded_00074,True,0.816828,17,438,203,21.910959,0.853881,5.567699e+06,3.891386,2.902244,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,631.734887,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,True,False,
19,20,core_front_expanded_00263,True,0.808937,20,419,193,22.102625,0.854415,5.380785e+06,3.844003,2.860095,544.954259,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.962936,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,
20,21,core_front_expanded_00279,True,0.808937,20,419,193,22.102625,0.854415,5.380785e+06,3.844003,2.860095,544.954259,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.962936,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,
21,22,core_front_expanded_00016,True,0.806922,14,431,199,21.925754,0.853828,5.484875e+06,3.851100,2.873528,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,640.272931,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
22,23,core_front_expanded_00046,True,0.806922,14,431,199,21.925754,0.853828,5.484875e+06,3.851100,2.873528,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,640.272931,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
23,24,core_front_expanded_00078,True,0.806922,14,431,199,21.925754,0.853828,5.484875e+06,3.851100,2.873528,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,640.272931,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
24,25,core_front_expanded_00264,True,0.805875,22,419,193,22.124105,0.854415,5.384921e+06,3.846189,2.860069,544.946647,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.919248,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,
25,26,core_front_expanded_00280,True,0.805875,22,419,193,22.124105,0.854415,5.384921e+06,3.846189,2.860069,544.946647,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.919248,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,
26,27,core_front_expanded_00013,True,0.800109,38,442,203,21.895928,0.855204,5.608289e+06,3.912465,2.918139,544.660782,865.535305,-10376.349181,-30723.516018,-24889.323006,2,625.475684,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,68.0,14.5,0.65,0.7,68.0,8.5,0.7,0.7,True,False,
27,28,core_front_expanded_00041,True,0.800109,38,442,203,21.895928,0.855204,5.608289e+06,3.912465,2.918139,544.660782,865.535305,-10376.349181,-30723.516018,-24889.323006,2,625.475684,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.65,0.7,68.0,8.5,0.7,0.7,True,False,
28,29,core_front_expanded_00073,True,0.800109,38,442,203,21.895928,0.855204,5.608289e+06,3.912465,2.918139,544.660782,865.535305,-10376.349181,-30723.516018,-24889.323006,2,625.475684,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.65,0.7,68.0,8.5,0.7,0.7,True,False,
29,30,core_front_expanded_00015,True,0.787641,35,435,199,21.910345,0.855172,5.525465e+06,3.872199,2.889436,544.699653,877.757072,-10376.349181,-30723.516018,-24889.323006,2,633.451432,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,

Candidates passing all robustness screens:

,review_rank,candidate_id,robustness_screen_pass,robustness_score_after_boundary_penalty,avg_pnl_per_day_rank,trades,unique_trade_dates,avg_tenor,win_rate,total_pnl,profit_factor,profit_factor_pnl_per_day,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,avg_pnl_per_day_2025,avg_pnl_per_day_2026,min_bucket_avg_pnl_per_day,positive_bucket_count,min_tenor_avg_pnl_per_day,front_min_tenor_avg_pnl_per_day,positive_year_count,negative_year_count,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Front_forecast_vol_pct_min_at_grid_max,Front_model_vrp_log_at_grid_max,robustness_failed_screens
0,1,core_front_expanded_00168,True,0.846453,1,428,197,21.995327,0.855140,5.479290e+06,3.881266,2.897659,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
1,2,core_front_expanded_00182,True,0.846453,1,428,197,21.995327,0.855140,5.479290e+06,3.881266,2.897659,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
2,3,core_front_expanded_00198,True,0.846453,1,428,197,21.995327,0.855140,5.479290e+06,3.881266,2.897659,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
3,4,core_front_expanded_00167,True,0.839922,8,432,197,21.979167,0.856481,5.519880e+06,3.902610,2.913804,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
4,5,core_front_expanded_00181,True,0.839922,8,432,197,21.979167,0.856481,5.519880e+06,3.902610,2.913804,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
5,6,core_front_expanded_00197,True,0.839922,8,432,197,21.979167,0.856481,5.519880e+06,3.902610,2.913804,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
6,7,core_front_expanded_00248,True,0.835891,11,423,194,22.113475,0.855792,5.434757e+06,3.872530,2.879166,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
7,8,core_front_expanded_00262,True,0.835891,11,423,194,22.113475,0.855792,5.434757e+06,3.872530,2.879166,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
8,9,core_front_expanded_00278,True,0.835891,11,423,194,22.113475,0.855792,5.434757e+06,3.872530,2.879166,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
9,10,core_front_expanded_00183,True,0.820937,4,424,196,21.983491,0.853774,5.425318e+06,3.852885,2.878714,547.507072,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.656487,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,False,
10,11,core_front_expanded_00199,True,0.820937,4,424,196,21.983491,0.853774,5.425318e+06,3.852885,2.878714,547.507072,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.656487,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,False,
11,12,core_front_expanded_00247,True,0.820109,24,427,194,22.096019,0.857143,5.475347e+06,3.893984,2.895417,544.898750,874.092727,-10376.349181,-30723.516018,-24889.323006,2,662.144375,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,True,
12,13,core_front_expanded_00261,True,0.820109,24,427,194,22.096019,0.857143,5.475347e+06,3.893984,2.895417,544.898750,874.092727,-10376.349181,-30723.516018,-24889.323006,2,662.144375,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,True,
13,14,core_front_expanded_00277,True,0.820109,24,427,194,22.096019,0.857143,5.475347e+06,3.893984,2.895417,544.898750,874.092727,-10376.349181,-30723.516018,-24889.323006,2,662.144375,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,True,
14,15,core_front_expanded_00184,True,0.817875,6,424,196,22.004717,0.853774,5.429453e+06,3.855060,2.878688,547.499550,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.614524,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,False,
15,16,core_front_expanded_00200,True,0.817875,6,424,196,22.004717,0.853774,5.429453e+06,3.855060,2.878688,547.499550,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.614524,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,False,
16,17,core_front_expanded_00014,True,0.816828,17,438,203,21.910959,0.853881,5.567699e+06,3.891386,2.902244,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,631.734887,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,68.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,True,False,
17,18,core_front_expanded_00042,True,0.816828,17,438,203,21.910959,0.853881,5.567699e+06,3.891386,2.902244,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,631.734887,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,True,False,
18,19,core_front_expanded_00074,True,0.816828,17,438,203,21.910959,0.853881,5.567699e+06,3.891386,2.902244,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,631.734887,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,True,False,
19,20,core_front_expanded_00263,True,0.808937,20,419,193,22.102625,0.854415,5.380785e+06,3.844003,2.860095,544.954259,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.962936,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,
20,21,core_front_expanded_00279,True,0.808937,20,419,193,22.102625,0.854415,5.380785e+06,3.844003,2.860095,544.954259,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.962936,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,
21,22,core_front_expanded_00016,True,0.806922,14,431,199,21.925754,0.853828,5.484875e+06,3.851100,2.873528,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,640.272931,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
22,23,core_front_expanded_00046,True,0.806922,14,431,199,21.925754,0.853828,5.484875e+06,3.851100,2.873528,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,640.272931,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
23,24,core_front_expanded_00078,True,0.806922,14,431,199,21.925754,0.853828,5.484875e+06,3.851100,2.873528,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,640.272931,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
24,25,core_front_expanded_00264,True,0.805875,22,419,193,22.124105,0.854415,5.384921e+06,3.846189,2.860069,544.946647,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.919248,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,
25,26,core_front_expanded_00280,True,0.805875,22,419,193,22.124105,0.854415,5.384921e+06,3.846189,2.860069,544.946647,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.919248,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,
26,27,core_front_expanded_00013,True,0.800109,38,442,203,21.895928,0.855204,5.608289e+06,3.912465,2.918139,544.660782,865.535305,-10376.349181,-30723.516018,-24889.323006,2,625.475684,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,68.0,14.5,0.65,0.7,68.0,8.5,0.7,0.7,True,False,
27,28,core_front_expanded_00041,True,0.800109,38,442,203,21.895928,0.855204,5.608289e+06,3.912465,2.918139,544.660782,865.535305,-10376.349181,-30723.516018,-24889.323006,2,625.475684,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.65,0.7,68.0,8.5,0.7,0.7,True,False,
28,29,core_front_expanded_00073,True,0.800109,38,442,203,21.895928,0.855204,5.608289e+06,3.912465,2.918139,544.660782,865.535305,-10376.349181,-30723.516018,-24889.323006,2,625.475684,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.65,0.7,68.0,8.5,0.7,0.7,True,False,
29,30,core_front_expanded_00015,True,0.787641,35,435,199,21.910345,0.855172,5.525465e+06,3.872199,2.889436,544.699653,877.757072,-10376.349181,-30723.516018,-24889.323006,2,633.451432,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
30,31,core_front_expanded_00045,True,0.787641,35,435,199,21.910345,0.855172,5.525465e+06,3.872199,2.889436,544.699653,877.757072,-10376.349181,-30723.516018,-24889.323006,2,633.451432,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
31,32,core_front_expanded_00077,True,0.787641,35,435,199,21.910345,0.855172,5.525465e+06,3.872199,2.889436,544.699653,877.757072,-10376.349181,-30723.516018,-24889.323006,2,633.451432,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
32,33,core_front_expanded_00208,True,0.787078,41,422,193,22.172986,0.853081,5.400606e+06,3.839890,2.832004,536.425019,879.606050,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,477.363084,3,-289.677288,-289.677288,6,0,0.70,0.70,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
33,34,core_front_expanded_00222,True,0.787078,41,422,193,22.172986,0.853081,5.400606e+06,3.839890,2.832004,536.425019,879.606050,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,477.363084,3,-289.677288,-289.677288,6,0,0.70,0.70,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
34,35,core_front_expanded_00238,True,0.787078,41,422,193,22.172986,0.853081,5.400606e+06,3.839890,2.832004,536.425019,879.606050,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,477.363084,3,-289.677288,-289.677288,6,0,0.70,0.70,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
35,36,core_front_expanded_00207,True,0.783734,44,426,193,22.154930,0.854460,5.441196e+06,3.861235,2.848149,536.071045,873.480210,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,477.363084,3,-289.677288,-289.677288,6,0,0.70,0.70,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
36,37,core_front_expanded_00221,True,0.783734,44,426,193,22.154930,0.854460,5.441196e+06,3.861235,2.848149,536.071045,873.480210,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,477.363084,3,-289.677288,-289.677288,6,0,0.70,0.70,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
37,38,core_front_expanded_00237,True,0.783734,44,426,193,22.154930,0.854460,5.441196e+06,3.861235,2.848149,536.071045,873.480210,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,477.363084,3,-289.677288,-289.677288,6,0,0.70,0.70,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
38,39,core_front_expanded_00043,True,0.780469,31,434,202,21.898618,0.852535,5.513727e+06,3.863357,2.883591,544.709987,875.924899,-10376.349181,-30723.516018,-24889.323006,2,634.880828,69.265215,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.65,0.7,66.0,8.5,0.7,0.7,True,False,
39,40,core_front_expanded_00075,True,0.780469,31,434,202,21.898618,0.852535,5.513727e+06,3.863357,2.883591,544.709987,875.924899,-10376.349181,-30723.516018,-24889.323006,2,634.880828,69.265215,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.65,0.7,66.0,8.5,0.7,0.7,True,False,
40,41,core_front_expanded_00044,True,0.777406,33,434,202,21.919355,0.852535,5.517863e+06,3.865505,2.883566,544.702638,875.924899,-10376.349181,-30723.516018,-24889.323006,2,634.840963,69.265215,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.65,0.7,66.0,10.0,0.7,0.7,True,False,
41,42,core_front_expanded_00076,True,0.777406,33,434,202,21.919355,0.852535,5.517863e+06,3.865505,2.883566,544.702638,875.924899,-10376.349181,-30723.516018,-24889.323006,2,634.840963,69.265215,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.65,0.7,66.0,10.0,0.7,0.7,True,False,
42,43,core_front_expanded_00047,True,0.777406,27,427,198,21.913349,0.852459,5.430903e+06,3.823045,2.854860,544.750393,890.138242,-10376.349181,-30723.516018,-24889.323006,2,643.608999,60.157120,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,False,
43,44,core_front_expanded_00079,True,0.777406,27,427,198,21.913349,0.852459,5.430903e+06,3.823045,2.854860,544.750393,890.138242,-10376.349181,-30723.516018,-24889.323006,2,643.608999,60.157120,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,False,
44,45,core_front_expanded_00048,True,0.774344,29,427,198,21.934426,0.852459,5.435038e+06,3.825195,2.854835,544.742924,890.138242,-10376.349181,-30723.516018,-24889.323006,2,643.568112,60.157120,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,False,
45,46,core_front_expanded_00080,True,0.774344,29,427,198,21.934426,0.852459,5.435038e+06,3.825195,2.854835,544.742924,890.138242,-10376.349181,-30723.516018,-24889.323006,2,643.568112,60.157120,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,False,
46,47,core_front_expanded_00288,True,0.772328,57,417,190,22.294964,0.853717,5.356073e+06,3.830942,2.813078,533.727083,874.092727,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,464.567150,3,-340.126292,-340.126292,6,0,0.75,0.70,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
47,48,core_front_expanded_00302,True,0.772328,57,417,190,22.294964,0.853717,5.356073e+06,3.830942,2.813078,533.727083,874.092727,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,464.567150,3,-340.126292,-340.126292,6,0,0.75,0.70,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
48,49,core_front_expanded_00318,True,0.772328,57,417,190,22.294964,0.853717,5.356073e+06,3.830942,2.813078,533.727083,874.092727,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,464.567150,3,-340.126292,-340.126292,6,0,0.75,0.70,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
49,50,core_front_expanded_00094,True,0.763328,51,432,199,22.083333,0.851852,5.489015e+06,3.850524,2.837605,533.871513,865.535305,-10376.349181,-30723.516018,-24889.323006,2,631.734887,85.752231,469.239805,3,-289.677288,-289.677288,6,0,0.65,0.70,68.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,True,False,

Top 30 by raw avg P&L/day:

,review_rank,candidate_id,robustness_screen_pass,robustness_score_after_boundary_penalty,avg_pnl_per_day_rank,trades,unique_trade_dates,avg_tenor,win_rate,total_pnl,profit_factor,profit_factor_pnl_per_day,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,avg_pnl_per_day_2025,avg_pnl_per_day_2026,min_bucket_avg_pnl_per_day,positive_bucket_count,min_tenor_avg_pnl_per_day,front_min_tenor_avg_pnl_per_day,positive_year_count,negative_year_count,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Front_forecast_vol_pct_min_at_grid_max,Front_model_vrp_log_at_grid_max,robustness_failed_screens
0,1,core_front_expanded_00168,True,0.846453,1,428,197,21.995327,0.855140,5.479290e+06,3.881266,2.897659,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
1,2,core_front_expanded_00182,True,0.846453,1,428,197,21.995327,0.855140,5.479290e+06,3.881266,2.897659,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
2,3,core_front_expanded_00198,True,0.846453,1,428,197,21.995327,0.855140,5.479290e+06,3.881266,2.897659,547.859866,885.630340,-10376.349181,-30723.516018,-24889.323006,2,661.947436,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
9,10,core_front_expanded_00183,True,0.820937,4,424,196,21.983491,0.853774,5.425318e+06,3.852885,2.878714,547.507072,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.656487,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,False,
10,11,core_front_expanded_00199,True,0.820937,4,424,196,21.983491,0.853774,5.425318e+06,3.852885,2.878714,547.507072,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.656487,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,False,
14,15,core_front_expanded_00184,True,0.817875,6,424,196,22.004717,0.853774,5.429453e+06,3.855060,2.878688,547.499550,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.614524,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,False,
15,16,core_front_expanded_00200,True,0.817875,6,424,196,22.004717,0.853774,5.429453e+06,3.855060,2.878688,547.499550,890.768149,-10376.349181,-30723.516018,-24889.323006,2,665.614524,60.157120,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,False,
3,4,core_front_expanded_00167,True,0.839922,8,432,197,21.979167,0.856481,5.519880e+06,3.902610,2.913804,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
4,5,core_front_expanded_00181,True,0.839922,8,432,197,21.979167,0.856481,5.519880e+06,3.902610,2.913804,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
5,6,core_front_expanded_00197,True,0.839922,8,432,197,21.979167,0.856481,5.519880e+06,3.902610,2.913804,547.404931,879.606050,-10376.349181,-30723.516018,-24889.323006,2,653.887160,77.113098,520.383465,3,-129.435164,-129.435164,6,0,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,False,
6,7,core_front_expanded_00248,True,0.835891,11,423,194,22.113475,0.855792,5.434757e+06,3.872530,2.879166,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
7,8,core_front_expanded_00262,True,0.835891,11,423,194,22.113475,0.855792,5.434757e+06,3.872530,2.879166,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
8,9,core_front_expanded_00278,True,0.835891,11,423,194,22.113475,0.855792,5.434757e+06,3.872530,2.879166,545.335363,881.455029,-10376.349181,-30723.516018,-24889.323006,2,670.977756,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,True,
21,22,core_front_expanded_00016,True,0.806922,14,431,199,21.925754,0.853828,5.484875e+06,3.851100,2.873528,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,640.272931,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
22,23,core_front_expanded_00046,True,0.806922,14,431,199,21.925754,0.853828,5.484875e+06,3.851100,2.873528,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,640.272931,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
23,24,core_front_expanded_00078,True,0.806922,14,431,199,21.925754,0.853828,5.484875e+06,3.851100,2.873528,545.126315,881.553041,-10376.349181,-30723.516018,-24889.323006,2,640.272931,77.113098,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,True,False,
16,17,core_front_expanded_00014,True,0.816828,17,438,203,21.910959,0.853881,5.567699e+06,3.891386,2.902244,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,631.734887,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,68.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,True,False,
17,18,core_front_expanded_00042,True,0.816828,17,438,203,21.910959,0.853881,5.567699e+06,3.891386,2.902244,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,631.734887,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,True,False,
18,19,core_front_expanded_00074,True,0.816828,17,438,203,21.910959,0.853881,5.567699e+06,3.891386,2.902244,545.080270,870.479355,-10376.349181,-30723.516018,-24889.323006,2,631.734887,85.752231,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.65,0.7,68.0,10.0,0.7,0.7,True,False,
19,20,core_front_expanded_00263,True,0.808937,20,419,193,22.102625,0.854415,5.380785e+06,3.844003,2.860095,544.954259,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.962936,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,
20,21,core_front_expanded_00279,True,0.808937,20,419,193,22.102625,0.854415,5.380785e+06,3.844003,2.860095,544.954259,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.962936,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,True,
24,25,core_front_expanded_00264,True,0.805875,22,419,193,22.124105,0.854415,5.384921e+06,3.846189,2.860069,544.946647,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.919248,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,
25,26,core_front_expanded_00280,True,0.805875,22,419,193,22.124105,0.854415,5.384921e+06,3.846189,2.860069,544.946647,889.707640,-10376.349181,-30723.516018,-24889.323006,2,674.919248,60.157120,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,True,
11,12,core_front_expanded_00247,True,0.820109,24,427,194,22.096019,0.857143,5.475347e+06,3.893984,2.895417,544.898750,874.092727,-10376.349181,-30723.516018,-24889.323006,2,662.144375,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,True,
12,13,core_front_expanded_00261,True,0.820109,24,427,194,22.096019,0.857143,5.475347e+06,3.893984,2.895417,544.898750,874.092727,-10376.349181,-30723.516018,-24889.323006,2,662.144375,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,True,
13,14,core_front_expanded_00277,True,0.820109,24,427,194,22.096019,0.857143,5.475347e+06,3.893984,2.895417,544.898750,874.092727,-10376.349181,-30723.516018,-24889.323006,2,662.144375,77.113098,510.082211,3,-169.827553,-169.827553,6,0,0.75,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,True,True,
42,43,core_front_expanded_00047,True,0.777406,27,427,198,21.913349,0.852459,5.430903e+06,3.823045,2.854860,544.750393,890.138242,-10376.349181,-30723.516018,-24889.323006,2,643.608999,60.157120,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,False,
43,44,core_front_expanded_00079,True,0.777406,27,427,198,21.913349,0.852459,5.430903e+06,3.823045,2.854860,544.750393,890.138242,-10376.349181,-30723.516018,-24889.323006,2,643.608999,60.157120,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,True,False,
44,45,core_front_expanded_00048,True,0.774344,29,427,198,21.934426,0.852459,5.435038e+06,3.825195,2.854835,544.742924,890.138242,-10376.349181,-30723.516018,-24889.323006,2,643.568112,60.157120,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,66.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,False,
45,46,core_front_expanded_00080,True,0.774344,29,427,198,21.934426,0.852459,5.435038e+06,3.825195,2.854835,544.742924,890.138242,-10376.349181,-30723.516018,-24889.323006,2,643.568112,60.157120,511.617614,3,-129.435164,-129.435164,6,0,0.65,0.65,64.0,14.5,0.70,0.7,66.0,10.0,0.7,0.7,True,False,

Bucket detail for top 20 ranked candidates:

,review_rank,candidate_id,selection_universe,tenor_bucket,tenor_bucket_order,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,candidate_family,locked_model_spec,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Back_RSI14_max,Back_forecast_vol_pct_min,front_minus_back_log,front_minus_back_z,front_minus_back_RSI_cap,front_minus_back_forecast_floor,middle_between_front_back_log,middle_between_front_back_z,middle_between_front_back_RSI,middle_between_front_back_forecast_floor,front_log_tighter_than_back,front_RSI_tighter_than_back,front_forecast_floor_tighter_than_back
1461,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,Front,1,122,122,2021-09-20,2026-04-06,9,15,12.172131,0.795082,8.959548e+05,7343.892140,15537.629243,-108475.796818,38031.055016,2.183679,-237211.539967,-155233.786408,-237211.539967,-107763.939183,4,1,0,63486.782722,520.383465,1326.845332,-10376.349181,3784.000307,1.870487,-25542.234359,-16578.116553,-22503.256665,-14292.437002,16,201165.483862,879.555283,-40441.053294,16,78676.859406,400.032400,-34533.046342,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
1462,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
1463,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
1503,2,core_front_expanded_00182,one_trade_per_bucket_per_date_best_rank,Front,1,122,122,2021-09-20,2026-04-06,9,15,12.172131,0.795082,8.959548e+05,7343.892140,15537.629243,-108475.796818,38031.055016,2.183679,-237211.539967,-155233.786408,-237211.539967,-107763.939183,4,1,0,63486.782722,520.383465,1326.845332,-10376.349181,3784.000307,1.870487,-25542.234359,-16578.116553,-22503.256665,-14292.437002,16,201165.483862,879.555283,-40441.053294,16,78676.859406,400.032400,-34533.046342,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-4.0,6.0,True,True,True,True,False,True,True
1504,2,core_front_expanded_00182,one_trade_per_bucket_per_date_best_rank,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-4.0,6.0,True,True,True,True,False,True,True
1505,2,core_front_expanded_00182,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-4.0,6.0,True,True,True,True,False,True,True
1551,3,core_front_expanded_00198,one_trade_per_bucket_per_date_best_rank,Front,1,122,122,2021-09-20,2026-04-06,9,15,12.172131,0.795082,8.959548e+05,7343.892140,15537.629243,-108475.796818,38031.055016,2.183679,-237211.539967,-155233.786408,-237211.539967,-107763.939183,4,1,0,63486.782722,520.383465,1326.845332,-10376.349181,3784.000307,1.870487,-25542.234359,-16578.116553,-22503.256665,-14292.437002,16,201165.483862,879.555283,-40441.053294,16,78676.859406,400.032400,-34533.046342,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-6.0,6.0,True,True,True,True,False,True,True
1552,3,core_front_expanded_00198,one_trade_per_bucket_per_date_best_rank,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-6.0,6.0,True,True,True,True,False,True,True
1553,3,core_front_expanded_00198,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-6.0,6.0,True,True,True,True,False,True,True
1458,4,core_front_expanded_00167,one_trade_per_bucket_per_date_best_rank,Front,1,122,122,2021-09-20,2026-04-06,9,15,12.172131,0.795082,8.959548e+05,7343.892140,15537.629243,-108475.796818,38031.055016,2.183679,-237211.539967,-155233.786408,-237211.539967,-107763.939183,4,1,0,63486.782722,520.383465,1326.845332,-10376.349181,3784.000307,1.870487,-25542.234359,-16578.116553,-22503.256665,-14292.437002,16,201165.483862,879.555283,-40441.053294,16,78676.859406,400.032400,-34533.046342,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
1459,4,core_front_expanded_00167,one_trade_per_bucket_per_date_best_rank,Middle,2,153,153,2021-11-24,2026-04-29,18,24,21.294118,0.849673,1.865832e+06,12194.980045,18720.325571,-108475.796818,42988.137121,3.815843,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,83262.074671,544.196566,925.336320,-6026.433157,1791.172380,3.450601,-20774.019539,-10696.956646,-19097.652002,-16788.785812,26,405417.381515,723.027339,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
1460,4,core_front_expanded_00167,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
1500,5,core_front_expanded_00181,one_trade_per_bucket_per_date_best_rank,Front,1,122,122,2021-09-20,2026-04-06,9,15,12.172131,0.795082,8.959548e+05,7343.892140,15537.629243,-108475.796818,38031.055016,2.183679,-237211.539967,-155233.786408,-237211.539967,-107763.939183,4,1,0,63486.782722,520.383465,1326.845332,-10376.349181,3784.000307,1.870487,-25542.234359,-16578.116553,-22503.256665,-14292.437002,16,201165.483862,879.555283,-40441.053294,16,78676.859406,400.032400,-34533.046342,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,0.00,-0.05,-4.0,6.0,True,True,True,True,False,True,True
1501,5,core_front_expanded_00181,one_trade_per_bucket_per_date_best_rank,Middle,2,153,153,2021-11-24,2026-04-29,18,24,21.294118,0.849673,1.865832e+06,12194.980045,18720.325571,-108475.796818,42988.137121,3.815843,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,83262.074671,544.196566,925.336320,-6026.433157,1791.172380,3.450601,-20774.019539,-10696.956646,-19097.652002,-16788.785812,26,405417.381515,723.027339,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,0.00,-0.05,-4.0,6.0,True,True,True,True,False,True,True
1502,5,core_front_expanded_00181,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,0.00,-0.05,-4.0,6.0,True,True,True,True,False,True,True
1548,6,core_front_expanded_00197,one_trade_per_bucket_per_date_best_rank,Front,1,122,122,2021-09-20,2026-04-06,9,15,12.172131,0.795082,8.959548e+05,7343.892140,15537.629243,-108475.796818,38031.055016,2.183679,-237211.539967,-155233.786408,-237211.539967,-107763.939183,4,1,0,63486.782722,520.383465,1326.845332,-10376.349181,3784.000307,1.870487,-25542.234359,-16578.116553,-22503.256665,-14292.437002,16,201165.483862,879.555283,-40441.053294,16,78676.859406,400.032400,-34533.046342,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,0.00,-0.05,-6.0,6.0,True,True,True,True,False,True,True
1549,6,core_front_expanded_00197,one_trade_per_bucket_per_date_best_rank,Middle,2,153,153,2021-11-24,2026-04-29,18,24,21.294118,0.849673,1.865832e+06,12194.980045,18720.325571,-108475.796818,42988.137121,3.815843,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,83262.074671,544.196566,925.336320,-6026.433157,1791.172380,3.450601,-20774.019539,-10696.956646,-19097.652002,-16788.785812,26,405417.381515,723.027339,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,0.00,-0.05,-6.0,6.0,True,True,True,True,False,True,True
1550,6,core_front_expanded_00197,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,0.00,-0.05,-6.0,6.0,True,True,True,True,False,True,True
1701,7,core_front_expanded_00248,one_trade_per_bucket_per_date_best_rank,Front,1,117,117,2021-09-20,2026-04-06,9,15,12.179487,0.794872,8.514223e+05,7277.113790,16033.176342,-108475.796818,38031.055016,2.139477,-237211.539967,-155233.786408,-237211.539967,-107763.939183,4,1,0,59679.618657,510.082211,1348.228749,-10376.349181,3784.000307,1.827475,-25542.234359,-16578.116553,-22503.256665,-14292.437002,13,182533.668390,981.175835,-40441.053294,16,78676.859406,400.032400,-34533.046342,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.05,-0.05,-2.0,6.0,True,True,True,True,True,True,True
1702,7,core_front_expanded_00248,one_trade_per_bucket_per_date_best_rank,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.05,-0.05,-2.0,6.0,True,True,True,True,True,True,True
1703,7,core_front_expanded_00248,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.05,-0.05,-2.0,6.0,True,True,True,True,True,True,True
1743,8,core_front_expanded_00262,one_trade_per_bucket_per_date_best_rank,Front,1,117,117,2021-09-20,2026-04-06,9,15,12.179487,0.794872,8.514223e+05,7277.113790,16033.176342,-108475.796818,38031.055016,2.139477,-237211.539967,-155233.786408,-237211.539967,-107763.939183,4,1,0,59679.618657,510.082211,1348.228749,-10376.349181,3784.000307,1.827475,-25542.234359,-16578.116553,-22503.256665,-14292.437002,13,182533.668390,981.175835,-40441.053294,16,78676.859406,400.032400,-34533.046342,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True
1744,8,core_front_expanded_00262,one_trade_per_bucket_per_date_best_rank,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True
1745,8,core_front_expanded_00262,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True
1791,9,core_front_expanded_00278,one_trade_per_bucket_per_date_best_rank,Front,1,117,117,2021-09-20,2026-04-06,9,15,12.179487,0.794872,8.514223e+05,7277.113790,16033.176342,-108475.796818,38031.055016,2.139477,-237211.539967,-155233.786408,-237211.539967,-107763.939183,4,1,0,59679.618657,510.082211,1348.228749,-10376.349181,3784.000307,1.827475,-25542.234359,-16578.116553,-22503.256665,-14292.437002,13,182533.668390,981.175835,-40441.053294,16,78676.859406,400.032400,-34533.046342,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.05,-0.05,-6.0,6.0,True,True,True,True,True,True,True
1792,9,core_front_expanded_00278,one_trade_per_bucket_per_date_best_rank,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.05,-0.05,-6.0,6.0,True,True,True,True,True,True,True
1793,9,core_front_expanded_00278,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.05,-0.05,-6.0,6.0,True,True,True,True,True,True,True
1506,10,core_front_expanded_00183,one_trade_per_bucket_per_date_best_rank,Front,1,122,122,2021-09-20,2026-04-06,9,15,12.172131,0.795082,8.959548e+05,7343.892140,15537.629243,-108475.796818,38031.055016,2.183679,-237211.539967,-155233.786408,-237211.539967,-107763.939183,4,1,0,63486.782722,520.383465,1326.845332,-10376.349181,3784.000307,1.870487,-25542.234359,-16578.116553,-22503.256665,-14292.437002,16,201165.483862,879.555283,-40441.053294,16,78676.859406,400.032400,-34533.046342,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,70.0,8.5,0.00,-0.05,-4.0,6.0,True,True,True,True,False,True,True

Tenor detail for top 20 ranked candidates:

,review_rank,candidate_id,selection_universe,tenor,tenor_bucket,tenor_bucket_order,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,candidate_family,locked_model_spec,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Back_RSI14_max,Back_forecast_vol_pct_min,front_minus_back_log,front_minus_back_z,front_minus_back_RSI_cap,front_minus_back_forecast_floor,middle_between_front_back_log,middle_between_front_back_z,middle_between_front_back_RSI,middle_between_front_back_forecast_floor,front_log_tighter_than_back,front_RSI_tighter_than_back,front_forecast_floor_tighter_than_back
4383,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,9,Front,1,37,37,2021-09-20,2026-03-23,9,9,9.0,0.702703,-4.310191e+04,-1164.916472,12815.804660,-93387.142625,34056.002766,0.902752,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-4789.101052,-129.435164,1423.978296,-10376.349181,3784.000307,0.902752,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
4384,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,12,Front,1,41,41,2021-12-03,2026-03-26,12,12,12.0,0.756098,3.403260e+05,8300.634740,14831.966723,-34533.046342,23041.639194,3.046018,-97297.099252,-85992.436400,-50247.933007,88198.337843,0,0,0,28360.502028,691.719562,1235.997227,-2877.753862,1920.136599,3.046018,-8108.091604,-7166.036367,-4187.327751,7349.861487,4,23000.973924,479.186957,-9719.373848,10,-3332.596641,-27.771639,-34533.046342,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
4385,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,15,Front,1,44,44,2022-01-21,2026-04-06,15,15,15.0,0.909091,5.987307e+05,13607.516504,19174.236934,-108475.796818,38031.055016,5.062776,-111137.668230,-86408.441669,17201.570824,128127.175790,1,1,0,39915.381746,907.167767,1278.282462,-7231.719788,2535.403668,5.062776,-7409.177882,-5760.562778,1146.771388,8541.811719,9,171898.199151,1273.319994,14103.157032,4,54763.357418,912.722624,-4542.821791,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
4386,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,18,Middle,2,54,54,2021-12-03,2026-03-25,18,18,18.0,0.740741,2.046359e+05,3789.554584,12641.588528,-108475.796818,25912.875855,1.460678,-315930.254948,-202522.266450,-315930.254948,-239409.369941,1,1,0,11368.663752,210.530810,702.310474,-6026.433157,1439.604214,1.460678,-17551.680830,-11251.237025,-17551.680830,-13300.520552,6,60950.563003,564.357065,6005.032657,18,-225068.948261,-694.657248,-45195.769858,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
4387,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,21,Middle,2,25,25,2021-12-01,2026-04-29,21,21,21.0,0.960000,3.987075e+05,15948.301588,18720.325571,-33182.394118,28179.541598,13.015635,-33182.394118,28166.045377,114624.158683,307501.033557,0,0,0,18986.073319,759.442933,891.444075,-1580.114006,1341.882933,13.015635,-1580.114006,1341.240256,5458.293271,14642.906360,7,127030.264488,864.151459,10440.842371,6,47374.991856,375.991999,-33182.394118,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5242,20,core_front_expanded_00263,one_trade_per_bucket_per_date_best_rank,21,Middle,2,22,22,2021-12-01,2026-04-07,21,21,21.0,0.954545,3.593905e+05,16335.932207,19840.275103,-33182.394118,28179.541598,11.830759,-33182.394118,34852.977257,122608.919369,314105.396523,0,0,0,17113.833741,777.901534,944.775005,-1580.114006,1341.882933,11.830759,-1580.114006,1659.665584,5838.519970,14957.399834,6,116589.422117,925.312874,17127.774251,4,18498.803074,220.223846,-33182.394118,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True
5243,20,core_front_expanded_00263,one_trade_per_bucket_per_date_best_rank,24,Middle,2,68,68,2021-11-24,2026-03-30,24,24,24.0,0.882353,1.197031e+06,17603.398194,24518.387746,-48027.465092,42988.137121,7.462376,-48027.465092,-17563.867069,84062.019309,251744.287040,0,0,0,49876.294883,733.474925,1021.599489,-2001.144379,1791.172380,7.462376,-2001.144379,-731.827795,3502.584138,10489.345293,8,166040.965000,864.796693,11584.867060,5,53985.195231,449.876627,-39413.392878,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True
5244,20,core_front_expanded_00263,one_trade_per_bucket_per_date_best_rank,27,Back,3,64,64,2021-11-24,2026-04-29,27,27,27.0,0.890625,7.946444e+05,12416.319396,14893.175204,-92579.572354,32071.631184,3.772550,-197819.722192,-184263.764146,-42456.069649,115794.844473,1,0,0,29431.275605,459.863681,551.599082,-3428.873050,1187.838192,3.772550,-7326.656377,-6824.583857,-1572.447024,4288.697943,26,362079.851866,515.783265,1573.629536,6,-31782.783676,-196.190023,-42147.706567,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True
5245,20,core_front_expanded_00263,one_trade_per_bucket_per_date_best_rank,30,Back,3,15,15,2022-03-09,2026-03-12,30,30,30.0,0.866667,2.641151e+05,17607.671904,20038.662122,-24704.938663,45095.398744,7.929464,-38114.790745,4469.678163,113186.089954,264115.078564,0,0,0,8803.835952,586.922397,667.955404,-823.497955,1503.179958,7.929464,-1270.493025,148.989272,3772.869665,8803.835952,3,87340.106049,970.445623,20038.662122,4,-13646.575851,-113.721465,-24704.938663,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True
5246,20,core_front_expanded_00263,one_trade_per_bucket_per_date_best_rank,33,Back,3,78,78,2021-12-06,2026-03-30,33,33,33.0,0.935897,1.699334e+06,21786.329730,27322.832885,-48751.416767,35371.772564,11.794523,-75662.284598,-49881.038125,33880.957771,174718.883975,0,0,0,51494.961181,660.191810,827.964633,-1477.315660,1071.871896,11.794523,-2292.796503,-1511.546610,1026.695690,5294.511636,10,124461.574059,377.156285,-40557.495661,19,294900.282775,470.335379,-48751.416767,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True

Year detail for top 20 ranked candidates:

,review_rank,candidate_id,selection_universe,year,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,candidate_family,locked_model_spec,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Back_RSI14_max,Back_forecast_vol_pct_min,front_minus_back_log,front_minus_back_z,front_minus_back_RSI_cap,front_minus_back_forecast_floor,middle_between_front_back_log,middle_between_front_back_z,middle_between_front_back_RSI,middle_between_front_back_forecast_floor,front_log_tighter_than_back,front_RSI_tighter_than_back,front_forecast_floor_tighter_than_back
2922,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,2021,13,6,2021-09-20,2021-12-06,9,33,18.923077,0.846154,2.062837e+05,15867.977728,18191.728857,-11223.996761,28384.414940,14.908592,-11223.996761,33218.559687,150054.178521,206283.710464,0,0,0,11560.124404,889.240339,1051.274627,-1247.110751,2021.303206,9.272485,-1247.110751,2348.829679,8231.826751,11560.124404,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
2923,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,2022,205,82,2022-01-20,2022-12-12,9,33,21.834146,0.853659,3.071482e+06,14982.836643,23981.764361,-108475.796818,35371.772564,3.804860,-554230.966487,-405645.462671,-550839.711287,-418288.570453,6,2,0,116417.332430,567.889426,1052.375232,-10376.349181,2233.055309,2.470002,-29528.075858,-24262.767198,-29339.672792,-24889.323006,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
2924,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,2023,14,10,2023-02-09,2023-10-19,9,27,13.071429,1.000000,2.269504e+05,16210.745571,15462.096439,11953.938503,23438.457453,inf,0.000000,73206.630843,163660.892461,226950.437993,0,0,0,19205.908886,1371.850635,1376.096842,738.125423,2204.494056,inf,0.000000,5729.543771,12173.737160,19205.908886,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
2925,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,2024,45,26,2024-08-02,2024-12-18,9,33,22.866667,0.977778,6.302609e+05,14005.798839,14568.250800,-3611.331326,28845.059994,175.523158,-3611.331326,33479.020904,104254.907925,241251.060430,0,0,0,30624.335204,680.540782,585.908058,-150.472139,1548.210115,204.521632,-150.472139,1121.746314,3675.720283,9267.224902,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
2926,1,core_front_expanded_00168,one_trade_per_bucket_per_date_best_rank,2025,77,43,2025-03-04,2025-11-20,9,33,23.415584,0.961039,1.139874e+06,14803.561875,14958.999019,-40557.495661,45095.398744,13.565039,-80998.548955,-78707.857490,97654.517973,217859.816866,0,0,0,50969.952607,661.947436,664.223685,-4493.450366,3784.000307,8.802622,-5722.465386,-5698.380893,3796.477361,8675.786622,77,1.139874e+06,661.947436,-40557.495661,0,0.000000,NaN,NaN,core_front_expanded_back_locked,unified_fds_no_min_return,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,0.00,-0.05,-2.0,6.0,True,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3493,20,core_front_expanded_00263,one_trade_per_bucket_per_date_best_rank,2022,205,82,2022-01-20,2022-12-12,9,33,21.834146,0.853659,3.071482e+06,14982.836643,23981.764361,-108475.796818,35371.772564,3.804860,-554230.966487,-405645.462671,-550839.711287,-418288.570453,6,2,0,116417.332430,567.889426,1052.375232,-10376.349181,2233.055309,2.470002,-29528.075858,-24262.767198,-29339.672792,-24889.323006,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True
3494,20,core_front_expanded_00263,one_trade_per_bucket_per_date_best_rank,2023,13,9,2023-02-09,2023-10-13,9,27,13.153846,1.000000,2.129719e+05,16382.457182,15462.208692,11953.938503,23438.457453,inf,0.000000,78289.550419,165715.574180,212971.943369,0,0,0,18041.034334,1387.771872,1423.978296,738.125423,2204.494056,inf,0.000000,5729.543771,12790.326646,18041.034334,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True
3495,20,core_front_expanded_00263,one_trade_per_bucket_per_date_best_rank,2024,43,25,2024-08-02,2024-12-18,9,33,23.162791,0.976744,6.042769e+05,14052.952018,14698.863518,-3611.331326,28845.059994,168.328025,-3611.331326,33479.020904,104259.553525,240947.128675,0,0,0,28713.736305,667.761309,585.511493,-150.472139,1548.210115,191.824272,-150.472139,1121.746314,3654.275951,9271.615149,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True
3496,20,core_front_expanded_00263,one_trade_per_bucket_per_date_best_rank,2025,73,42,2025-03-06,2025-11-20,9,33,23.794521,0.972603,1.110208e+06,15208.335118,15613.049794,-40557.495661,45095.398744,14.706523,-80998.548955,-34932.480877,93519.011258,219731.506922,0,0,0,49272.294361,674.962936,664.223685,-4493.450366,3784.000307,9.610326,-5722.465386,-1104.432765,3796.477361,8680.915375,73,1.110208e+06,674.962936,-40557.495661,0,0.000000,NaN,NaN,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True
3497,20,core_front_expanded_00263,one_trade_per_bucket_per_date_best_rank,2026,72,29,2026-02-05,2026-04-29,9,33,22.708333,0.638889,1.755628e+05,2438.372676,15330.338792,-48751.416767,30382.251113,1.251711,-557346.062507,-176953.066095,-322613.763893,-490347.831814,0,0,0,4331.312668,60.157120,643.030332,-2877.753862,1701.869017,1.119355,-30723.516018,-7228.586685,-13568.238215,-23979.307248,0,0.000000e+00,NaN,NaN,72,175562.832699,60.15712,-48751.416767,core_front_expanded_back_locked,unified_fds_no_min_return,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,0.05,-0.05,-4.0,6.0,True,True,True,True,True,True,True

Boundary warnings from Cell 8:

                         selection_universe  top_n                    parameter  grid_min  grid_max  top_min  top_max  top_mode  share_top_at_grid_min  share_top_at_grid_max  count_top_at_grid_min  count_top_at_grid_max  boundary_warning
0                      all_qualified_trades     50               Back_RSI14_max     70.00     70.00    70.00    70.00     70.00                   1.00                   1.00                     50                     50              True
1                      all_qualified_trades     50    Back_forecast_vol_pct_min      8.50      8.50     8.50     8.50      8.50                   1.00                   1.00                     50                     50              True
2                      all_qualified_trades     50           Back_model_vrp_log      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
3                      all_qualified_trades     50             Back_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
4                      all_qualified_trades     50   Front_forecast_vol_pct_min     10.00     14.50    14.50    14.50     14.50                   0.00                   1.00                      0                     50              True
5                      all_qualified_trades     50            Front_model_vrp_z      0.65      0.70     0.65     0.70      0.65                   0.62                   0.38                     31                     19              True
6                      all_qualified_trades     50             Middle_RSI14_max     66.00     68.00    66.00    68.00     66.00                   0.64                   0.36                     32                     18              True
7                      all_qualified_trades     50  Middle_forecast_vol_pct_min      8.50     10.00     8.50    10.00     10.00                   0.38                   0.62                     19                     31              True
8                      all_qualified_trades     50         Middle_model_vrp_log      0.65      0.70     0.65     0.70      0.70                   0.22                   0.78                     11                     39              True
9                      all_qualified_trades     50           Middle_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
12  one_trade_per_bucket_per_date_best_rank     50               Back_RSI14_max     70.00     70.00    70.00    70.00     70.00                   1.00                   1.00                     50                     50              True
13  one_trade_per_bucket_per_date_best_rank     50    Back_forecast_vol_pct_min      8.50      8.50     8.50     8.50      8.50                   1.00                   1.00                     50                     50              True
14  one_trade_per_bucket_per_date_best_rank     50           Back_model_vrp_log      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
15  one_trade_per_bucket_per_date_best_rank     50             Back_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
16  one_trade_per_bucket_per_date_best_rank     50   Front_forecast_vol_pct_min     10.00     14.50    14.50    14.50     14.50                   0.00                   1.00                      0                     50              True
17  one_trade_per_bucket_per_date_best_rank     50            Front_model_vrp_z      0.65      0.70     0.65     0.70      0.65                   0.80                   0.20                     40                     10              True
18  one_trade_per_bucket_per_date_best_rank     50             Middle_RSI14_max     66.00     68.00    66.00    68.00     68.00                   0.40                   0.60                     20                     30              True
19  one_trade_per_bucket_per_date_best_rank     50  Middle_forecast_vol_pct_min      8.50     10.00     8.50    10.00      8.50                   0.50                   0.50                     25                     25              True
20  one_trade_per_bucket_per_date_best_rank     50         Middle_model_vrp_log      0.65      0.70     0.65     0.70      0.70                   0.20                   0.80                     10                     40              True
21  one_trade_per_bucket_per_date_best_rank     50           Middle_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
24             one_trade_per_date_best_rank     50               Back_RSI14_max     70.00     70.00    70.00    70.00     70.00                   1.00                   1.00                     50                     50              True
25             one_trade_per_date_best_rank     50    Back_forecast_vol_pct_min      8.50      8.50     8.50     8.50      8.50                   1.00                   1.00                     50                     50              True
26             one_trade_per_date_best_rank     50           Back_model_vrp_log      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
27             one_trade_per_date_best_rank     50             Back_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
28             one_trade_per_date_best_rank     50   Front_forecast_vol_pct_min     10.00     14.50    13.00    14.50     14.50                   0.00                   0.64                      0                     32              True
29             one_trade_per_date_best_rank     50          Front_model_vrp_log      0.65      0.75     0.65     0.75      0.65                   0.56                   0.12                     28                      6              True
30             one_trade_per_date_best_rank     50            Front_model_vrp_z      0.65      0.70     0.65     0.65      0.65                   1.00                   0.00                     50                      0              True
31             one_trade_per_date_best_rank     50             Middle_RSI14_max     66.00     68.00    66.00    68.00     68.00                   0.28                   0.72                     14                     36              True
32             one_trade_per_date_best_rank     50  Middle_forecast_vol_pct_min      8.50     10.00     8.50    10.00      8.50                   0.50                   0.50                     25                     25              True
33             one_trade_per_date_best_rank     50         Middle_model_vrp_log      0.65      0.70     0.65     0.70      0.70                   0.32                   0.68                     16                     34              True
34             one_trade_per_date_best_rank     50           Middle_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
36                   thirty_day_anchor_only     50               Back_RSI14_max     70.00     70.00    70.00    70.00     70.00                   1.00                   1.00                     50                     50              True
37                   thirty_day_anchor_only     50    Back_forecast_vol_pct_min      8.50      8.50     8.50     8.50      8.50                   1.00                   1.00                     50                     50              True
38                   thirty_day_anchor_only     50           Back_model_vrp_log      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
39                   thirty_day_anchor_only     50             Back_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True
40                   thirty_day_anchor_only     50          Front_model_vrp_log      0.65      0.75     0.65     0.65      0.65                   1.00                   0.00                     50                      0              True
41                   thirty_day_anchor_only     50            Front_model_vrp_z      0.65      0.70     0.65     0.65      0.65                   1.00                   0.00                     50                      0              True
42                   thirty_day_anchor_only     50             Middle_RSI14_max     66.00     68.00    66.00    68.00     68.00                   0.32                   0.68                     16                     34              True
43                   thirty_day_anchor_only     50  Middle_forecast_vol_pct_min      8.50     10.00     8.50    10.00      8.50                   0.50                   0.50                     25                     25              True
44                   thirty_day_anchor_only     50         Middle_model_vrp_log      0.65      0.70     0.65     0.70      0.65                   0.52                   0.48                     26                     24              True
45                   thirty_day_anchor_only     50           Middle_model_vrp_z      0.70      0.70     0.70     0.70      0.70                   1.00                   1.00                     50                     50              True

Parameter boundary summary across ranked candidates:

                      parameter  grid_min  grid_max  candidate_count_at_min  candidate_count_at_max  candidate_share_at_min  candidate_share_at_max
0           Front_model_vrp_log      0.65      0.75                     160                      80                    0.50                    0.25
1             Front_model_vrp_z      0.65      0.70                     160                     160                    0.50                    0.50
2               Front_RSI14_max     64.00     68.00                     128                      64                    0.40                    0.20
3    Front_forecast_vol_pct_min     10.00     14.50                      80                      80                    0.25                    0.25
4          Middle_model_vrp_log      0.65      0.70                      80                     240                    0.25                    0.75
5            Middle_model_vrp_z      0.70      0.70                     320                     320                    1.00                    1.00
6              Middle_RSI14_max     66.00     68.00                     128                     192                    0.40                    0.60
7   Middle_forecast_vol_pct_min      8.50     10.00                     160                     160                    0.50                    0.50
8            Back_model_vrp_log      0.70      0.70                     320                     320                    1.00                    1.00
9              Back_model_vrp_z      0.70      0.70                     320                     320                    1.00                    1.00
10               Back_RSI14_max     70.00     70.00                     320                     320                    1.00                    1.00
11    Back_forecast_vol_pct_min      8.50      8.50                     320                     320                    1.00                    1.00

Saved outputs:
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\07_core_candidate_ranked_summary_20260704_220821.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\07_core_candidate_ranked_by_bucket_20260704_220821.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\07_core_candidate_ranked_by_tenor_20260704_220821.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\07_core_candidate_ranked_by_year_20260704_220821.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\07_core_candidate_boundary_review_20260704_220821.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\07_core_candidate_parameter_boundary_summary_20260704_220821.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\07_core_candidate_ranking_validation_20260704_220821.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\07_core_candidate_ranking_manifest_20260704_220821.json

CELL 9 PASSED

In [12]:
# ======================================================================================
# Cell 10 — Front tenor and boundary diagnostics
# ======================================================================================
#
# Objective:
#   Diagnose the remaining Front-bucket issues after Cell 9 ranking.
#
# Cell 9 showed:
#   - 80 candidates passed robustness screens.
#   - Top 25 candidates all used Front forecast_vol_pct_min = 14.5.
#   - Top candidate family remained strong overall.
#   - But 9D remained negative while 12D and 15D were strong.
#
# This cell tests whether the remaining issue is:
#   A. Front forecast-vol floor boundary,
#   B. 9D-specific weakness,
#   C. the current DTE-selection rule,
#   D. or Middle / 2026 instability.
#
# Tests:
#   1. Compare actual Front selected trades by 9D / 12D / 15D.
#   2. Compare Front all-tenor selected vs Front excluding 9D.
#   3. Recompute a diagnostic one-trade-per-bucket/date selector that excludes 9D
#      from Front, while keeping Middle and Back logic unchanged.
#   4. Show Front all-qualified P&L/day by forecast-vol state.
#   5. Check whether Front RSI is non-binding among top candidates.
#
# Important:
#   - No new threshold grid.
#   - No sweep expansion.
#   - No final threshold selection.
#   - No production lock.
#   - No Secondary.
#   - No sizing changes.
#
# This is diagnostic only.
# ======================================================================================

from pathlib import Path
from datetime import datetime
import hashlib
import json

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 280)
pd.set_option("display.width", 460)

# ======================================================================================
# 0. Fallback config
# ======================================================================================

if "PROJECT_ROOT" not in globals():
    PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

if "NEW_BRANCH" not in globals():
    NEW_BRANCH = "vrp_unified_fds_core_signal_threshold_research_v1"

if "OUT_PROCESSED_DIR" not in globals():
    OUT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / NEW_BRANCH
    OUT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

if "OUT_AUDIT_DIR" not in globals():
    OUT_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / NEW_BRANCH
    OUT_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

CELL10_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

PRIMARY_SELECTION_UNIVERSE = "one_trade_per_bucket_per_date_best_rank"
ALL_QUALIFIED_UNIVERSE = "all_qualified_trades"

TOP_N_CANDIDATES = 50

BUCKET_CENTER_TENOR = {
    "Front": 12,
    "Middle": 21,
    "Back": 30,
}

FORECAST_VOL_BINS = [-np.inf, 14.5, 16.0, 18.0, 20.0, np.inf]
FORECAST_VOL_BIN_LABELS = [
    "<=14.5",
    "14.5-16.0",
    "16.0-18.0",
    "18.0-20.0",
    ">20.0",
]

# ======================================================================================
# 1. Helpers
# ======================================================================================

def latest_file(directory: Path, pattern: str, required: bool = True) -> Path | None:
    matches = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if matches:
        return matches[0]
    if required:
        raise FileNotFoundError(f"No file found in {directory} matching {pattern}")
    return None


def profit_factor_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").dropna()
    gross_profit = float(pnl[pnl > 0].sum())
    gross_loss = float(pnl[pnl < 0].sum())

    if gross_loss < 0:
        return gross_profit / abs(gross_loss)
    if gross_profit > 0:
        return np.inf
    return np.nan


def max_drawdown_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)

    if len(pnl) == 0:
        return np.nan

    cumulative = pnl.cumsum()
    running_max = cumulative.cummax()
    drawdown = cumulative - running_max

    return float(drawdown.min())


def worst_rolling_sum(pnl: pd.Series, window: int) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)

    if len(pnl) == 0:
        return np.nan

    if len(pnl) < window:
        return float(pnl.sum())

    return float(pnl.rolling(window=window, min_periods=window).sum().min())


def summarize_trades(
    df: pd.DataFrame,
    group_cols: list[str],
    diagnostic_label: str,
) -> pd.DataFrame:
    d = df.copy()

    if d.empty:
        return pd.DataFrame()

    d["trade_date"] = pd.to_datetime(d["trade_date"], errors="coerce").dt.normalize()

    for c in [
        "tenor",
        "normalized_pnl_dollars",
        "normalized_pnl_per_day",
        "win",
        "forecast_vol_pct",
        "model_vrp_log",
        "model_vrp_z_3m",
        "model_vrp_z_1y",
        "RSI14",
    ]:
        if c in d.columns:
            d[c] = pd.to_numeric(d[c], errors="coerce")

    d = d[
        d["normalized_pnl_dollars"].notna()
        & d["normalized_pnl_per_day"].notna()
    ].copy()

    if d.empty:
        return pd.DataFrame()

    d = d.sort_values(["candidate_id", "trade_date", "tenor"]).copy()

    rows = []

    for keys, g in d.groupby(group_cols, dropna=False):
        if not isinstance(keys, tuple):
            keys = (keys,)

        row = {
            "diagnostic_label": diagnostic_label,
        }

        for col, key in zip(group_cols, keys):
            row[col] = key

        pnl = pd.to_numeric(g["normalized_pnl_dollars"], errors="coerce")
        pnl_day = pd.to_numeric(g["normalized_pnl_per_day"], errors="coerce")
        wins = pd.to_numeric(g["win"], errors="coerce") if "win" in g.columns else pd.Series(np.nan, index=g.index)

        y2025 = g[g["trade_date"].dt.year == 2025].copy()
        y2026 = g[g["trade_date"].dt.year == 2026].copy()

        row.update({
            "trades": int(len(g)),
            "unique_trade_dates": int(g["trade_date"].nunique()),
            "date_min": g["trade_date"].min(),
            "date_max": g["trade_date"].max(),
            "tenor_min": int(g["tenor"].min()) if "tenor" in g.columns and g["tenor"].notna().any() else np.nan,
            "tenor_max": int(g["tenor"].max()) if "tenor" in g.columns and g["tenor"].notna().any() else np.nan,
            "avg_tenor": float(g["tenor"].mean()) if "tenor" in g.columns and g["tenor"].notna().any() else np.nan,
            "win_rate": float(wins.mean()) if wins.notna().sum() else np.nan,

            "total_pnl": float(pnl.sum()),
            "avg_pnl": float(pnl.mean()),
            "median_pnl": float(pnl.median()),
            "worst_trade": float(pnl.min()),
            "best_trade": float(pnl.max()),
            "profit_factor": profit_factor_from_pnl(pnl),
            "selected_trade_drawdown": max_drawdown_from_pnl(pnl),
            "worst_5_trade_sum": worst_rolling_sum(pnl, 5),
            "worst_10_trade_sum": worst_rolling_sum(pnl, 10),
            "worst_20_trade_sum": worst_rolling_sum(pnl, 20),
            "trades_le_neg_50k": int((pnl <= -50_000).sum()),
            "trades_le_neg_100k": int((pnl <= -100_000).sum()),
            "trades_le_neg_150k": int((pnl <= -150_000).sum()),

            "total_pnl_per_day_sum": float(pnl_day.sum()),
            "avg_pnl_per_day": float(pnl_day.mean()),
            "median_pnl_per_day": float(pnl_day.median()),
            "worst_trade_pnl_per_day": float(pnl_day.min()),
            "best_trade_pnl_per_day": float(pnl_day.max()),
            "profit_factor_pnl_per_day": profit_factor_from_pnl(pnl_day),
            "pnl_per_day_drawdown": max_drawdown_from_pnl(pnl_day),
            "worst_5_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 5),
            "worst_10_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 10),
            "worst_20_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 20),

            "trades_2025": int(len(y2025)),
            "pnl_2025": float(y2025["normalized_pnl_dollars"].sum()) if len(y2025) else 0.0,
            "avg_pnl_per_day_2025": float(y2025["normalized_pnl_per_day"].mean()) if len(y2025) else np.nan,
            "worst_trade_2025": float(y2025["normalized_pnl_dollars"].min()) if len(y2025) else np.nan,

            "trades_2026": int(len(y2026)),
            "pnl_2026": float(y2026["normalized_pnl_dollars"].sum()) if len(y2026) else 0.0,
            "avg_pnl_per_day_2026": float(y2026["normalized_pnl_per_day"].mean()) if len(y2026) else np.nan,
            "worst_trade_2026": float(y2026["normalized_pnl_dollars"].min()) if len(y2026) else np.nan,
        })

        if "forecast_vol_pct" in g.columns:
            row.update({
                "avg_forecast_vol_pct": float(g["forecast_vol_pct"].mean()),
                "min_forecast_vol_pct": float(g["forecast_vol_pct"].min()),
                "max_forecast_vol_pct": float(g["forecast_vol_pct"].max()),
            })

        if "model_vrp_log" in g.columns:
            row["avg_model_vrp_log"] = float(g["model_vrp_log"].mean())

        if "model_vrp_z_3m" in g.columns:
            row["avg_model_vrp_z_3m"] = float(g["model_vrp_z_3m"].mean())

        if "model_vrp_z_1y" in g.columns:
            row["avg_model_vrp_z_1y"] = float(g["model_vrp_z_1y"].mean())

        rows.append(row)

    return pd.DataFrame(rows)


def add_diagnostic_selection_ranks(df: pd.DataFrame) -> pd.DataFrame:
    d = df.copy()

    if d.empty:
        return d

    d["bucket_center_tenor"] = d["tenor_bucket"].map(BUCKET_CENTER_TENOR)
    d["distance_to_bucket_center"] = (d["tenor"] - d["bucket_center_tenor"]).abs()

    group_cols = ["candidate_id", "trade_date", "tenor_bucket"]

    d["rank_z_1y_in_bucket_date_diag"] = (
        d.groupby(group_cols)["model_vrp_z_1y"]
        .rank(method="min", ascending=False)
    )

    d["rank_z_3m_in_bucket_date_diag"] = (
        d.groupby(group_cols)["model_vrp_z_3m"]
        .rank(method="min", ascending=False)
    )

    d["rank_vrp_log_in_bucket_date_diag"] = (
        d.groupby(group_cols)["model_vrp_log"]
        .rank(method="min", ascending=False)
    )

    d["avg_signal_rank_in_bucket_date_diag"] = d[
        [
            "rank_z_1y_in_bucket_date_diag",
            "rank_z_3m_in_bucket_date_diag",
            "rank_vrp_log_in_bucket_date_diag",
        ]
    ].mean(axis=1)

    return d


def diagnostic_one_trade_per_bucket_excluding_9d(all_qualified: pd.DataFrame) -> pd.DataFrame:
    """
    Recompute a diagnostic one-trade-per-bucket/date selector, excluding 9D from Front.

    This is not a new threshold sweep. It uses the exact trades that already passed
    the existing Cell 8 candidate thresholds.
    """
    d = all_qualified.copy()

    if d.empty:
        return d

    # Exclude 9D only from Front.
    d = d[
        ~(
            d["tenor_bucket"].eq("Front")
            & d["tenor"].eq(9)
        )
    ].copy()

    if d.empty:
        return d

    d = add_diagnostic_selection_ranks(d)

    selected = (
        d.sort_values(
            [
                "candidate_id",
                "trade_date",
                "tenor_bucket_order",
                "avg_signal_rank_in_bucket_date_diag",
                "distance_to_bucket_center",
                "rank_z_1y_in_bucket_date_diag",
                "rank_z_3m_in_bucket_date_diag",
                "rank_vrp_log_in_bucket_date_diag",
                "tenor",
            ],
            ascending=[True, True, True, True, True, True, True, True, True],
        )
        .groupby(["candidate_id", "trade_date", "tenor_bucket"], as_index=False)
        .head(1)
        .copy()
    )

    selected["diagnostic_selection_universe"] = "one_trade_per_bucket_per_date_excluding_front_9d"

    return selected


def make_trade_set_hash(df: pd.DataFrame) -> str:
    if df.empty:
        return "EMPTY"

    d = df.copy()
    d["trade_date"] = pd.to_datetime(d["trade_date"], errors="coerce").dt.strftime("%Y-%m-%d")
    d["tenor"] = pd.to_numeric(d["tenor"], errors="coerce").astype("Int64").astype(str)

    if "tenor_bucket" not in d.columns:
        d["tenor_bucket"] = ""

    keys = (
        d[["trade_date", "tenor_bucket", "tenor"]]
        .astype(str)
        .sort_values(["trade_date", "tenor_bucket", "tenor"])
        .agg("|".join, axis=1)
        .tolist()
    )

    joined = "\n".join(keys).encode("utf-8")

    return hashlib.md5(joined).hexdigest()


def attach_ranked_params(df: pd.DataFrame, ranked: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df

    param_cols = [
        "candidate_id",
        "review_rank",
        "robustness_screen_pass",
        "robustness_score_after_boundary_penalty",
        "Front_model_vrp_log",
        "Front_model_vrp_z",
        "Front_RSI14_max",
        "Front_forecast_vol_pct_min",
        "Middle_model_vrp_log",
        "Middle_model_vrp_z",
        "Middle_RSI14_max",
        "Middle_forecast_vol_pct_min",
        "Back_model_vrp_log",
        "Back_model_vrp_z",
        "Back_RSI14_max",
        "Back_forecast_vol_pct_min",
        "Front_forecast_vol_pct_min_at_grid_max",
        "Front_model_vrp_log_at_grid_max",
    ]

    available = [c for c in param_cols if c in ranked.columns]

    return df.merge(
        ranked[available].drop_duplicates("candidate_id"),
        on="candidate_id",
        how="left",
        validate="many_to_one",
    )


# ======================================================================================
# 2. Load inputs
# ======================================================================================

selected_trade_panel_path = latest_file(
    OUT_PROCESSED_DIR,
    "06_core_front_expanded_sweep_selected_trade_panel_*.parquet",
    required=True,
)

ranked_summary_path = latest_file(
    OUT_AUDIT_DIR,
    "07_core_candidate_ranked_summary_*.csv",
    required=True,
)

ranked_by_tenor_path = latest_file(
    OUT_AUDIT_DIR,
    "07_core_candidate_ranked_by_tenor_*.csv",
    required=True,
)

ranked_by_bucket_path = latest_file(
    OUT_AUDIT_DIR,
    "07_core_candidate_ranked_by_bucket_*.csv",
    required=True,
)

ranked_by_year_path = latest_file(
    OUT_AUDIT_DIR,
    "07_core_candidate_ranked_by_year_*.csv",
    required=True,
)

selected_panel = pd.read_parquet(selected_trade_panel_path)
ranked = pd.read_csv(ranked_summary_path)
ranked_by_tenor = pd.read_csv(ranked_by_tenor_path)
ranked_by_bucket = pd.read_csv(ranked_by_bucket_path)
ranked_by_year = pd.read_csv(ranked_by_year_path)

selected_panel["trade_date"] = pd.to_datetime(selected_panel["trade_date"], errors="coerce").dt.normalize()

for c in [
    "tenor",
    "tenor_bucket_order",
    "normalized_pnl_dollars",
    "normalized_pnl_per_day",
    "win",
    "forecast_vol_pct",
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14",
]:
    if c in selected_panel.columns:
        selected_panel[c] = pd.to_numeric(selected_panel[c], errors="coerce")

ranked = ranked.sort_values("review_rank").reset_index(drop=True)

top_candidate_ids = ranked.head(TOP_N_CANDIDATES)["candidate_id"].tolist()

top_panel = selected_panel[
    selected_panel["candidate_id"].isin(top_candidate_ids)
].copy()

actual_primary = top_panel[
    top_panel["selection_universe"].eq(PRIMARY_SELECTION_UNIVERSE)
].copy()

all_qualified = top_panel[
    top_panel["selection_universe"].eq(ALL_QUALIFIED_UNIVERSE)
].copy()

# ======================================================================================
# 3. Actual Front tenor diagnostics
# ======================================================================================

actual_front = actual_primary[
    actual_primary["tenor_bucket"].eq("Front")
].copy()

actual_front_ex_9d_drop_only = actual_front[
    actual_front["tenor"].ne(9)
].copy()

actual_front_all_summary = summarize_trades(
    actual_front,
    group_cols=["candidate_id"],
    diagnostic_label="actual_selected_front_all_tenors",
)

actual_front_ex_9d_drop_summary = summarize_trades(
    actual_front_ex_9d_drop_only,
    group_cols=["candidate_id"],
    diagnostic_label="actual_selected_front_drop_9d_no_reselection",
)

actual_front_by_tenor = summarize_trades(
    actual_front,
    group_cols=["candidate_id", "tenor"],
    diagnostic_label="actual_selected_front_by_tenor",
)

actual_front_by_tenor = attach_ranked_params(actual_front_by_tenor, ranked)

# ======================================================================================
# 4. Diagnostic re-selection excluding Front 9D
# ======================================================================================

diagnostic_reselected = diagnostic_one_trade_per_bucket_excluding_9d(all_qualified)

diagnostic_reselected_summary = summarize_trades(
    diagnostic_reselected,
    group_cols=["candidate_id"],
    diagnostic_label="diagnostic_one_trade_per_bucket_excluding_front_9d",
)

diagnostic_reselected_by_bucket = summarize_trades(
    diagnostic_reselected,
    group_cols=["candidate_id", "tenor_bucket", "tenor_bucket_order"],
    diagnostic_label="diagnostic_one_trade_per_bucket_excluding_front_9d_by_bucket",
)

diagnostic_reselected_by_tenor = summarize_trades(
    diagnostic_reselected,
    group_cols=["candidate_id", "tenor", "tenor_bucket", "tenor_bucket_order"],
    diagnostic_label="diagnostic_one_trade_per_bucket_excluding_front_9d_by_tenor",
)

diagnostic_reselected_summary = attach_ranked_params(diagnostic_reselected_summary, ranked)
diagnostic_reselected_by_bucket = attach_ranked_params(diagnostic_reselected_by_bucket, ranked)
diagnostic_reselected_by_tenor = attach_ranked_params(diagnostic_reselected_by_tenor, ranked)

# Actual primary summary for comparison.
actual_primary_summary = summarize_trades(
    actual_primary,
    group_cols=["candidate_id"],
    diagnostic_label="actual_one_trade_per_bucket_per_date",
)

actual_primary_summary = attach_ranked_params(actual_primary_summary, ranked)

# Compare actual vs diagnostic excluding 9D.
comparison_cols = [
    "candidate_id",
    "trades",
    "unique_trade_dates",
    "avg_tenor",
    "win_rate",
    "total_pnl",
    "profit_factor",
    "avg_pnl_per_day",
    "median_pnl_per_day",
    "pnl_per_day_drawdown",
    "worst_20_trade_pnl_per_day_sum",
    "trades_le_neg_100k",
    "avg_pnl_per_day_2025",
    "avg_pnl_per_day_2026",
]

actual_compare = actual_primary_summary[[c for c in comparison_cols if c in actual_primary_summary.columns]].copy()
diagnostic_compare = diagnostic_reselected_summary[[c for c in comparison_cols if c in diagnostic_reselected_summary.columns]].copy()

actual_compare = actual_compare.add_prefix("actual_").rename(columns={"actual_candidate_id": "candidate_id"})
diagnostic_compare = diagnostic_compare.add_prefix("ex9d_").rename(columns={"ex9d_candidate_id": "candidate_id"})

front_ex9d_comparison = actual_compare.merge(
    diagnostic_compare,
    on="candidate_id",
    how="inner",
    validate="one_to_one",
)

front_ex9d_comparison = attach_ranked_params(front_ex9d_comparison, ranked)

for metric in [
    "avg_pnl_per_day",
    "total_pnl",
    "profit_factor",
    "pnl_per_day_drawdown",
    "worst_20_trade_pnl_per_day_sum",
    "avg_pnl_per_day_2025",
    "avg_pnl_per_day_2026",
    "trades",
]:
    actual_col = f"actual_{metric}"
    ex9d_col = f"ex9d_{metric}"
    delta_col = f"delta_ex9d_minus_actual_{metric}"

    if actual_col in front_ex9d_comparison.columns and ex9d_col in front_ex9d_comparison.columns:
        front_ex9d_comparison[delta_col] = (
            front_ex9d_comparison[ex9d_col] - front_ex9d_comparison[actual_col]
        )

front_ex9d_comparison = front_ex9d_comparison.sort_values(
    [
        "review_rank",
        "delta_ex9d_minus_actual_avg_pnl_per_day",
    ],
    ascending=[True, False],
).reset_index(drop=True)

# ======================================================================================
# 5. Forecast-vol state diagnostics for Front all-qualified trades
# ======================================================================================

front_all_qualified = all_qualified[
    all_qualified["tenor_bucket"].eq("Front")
].copy()

front_all_qualified["front_forecast_vol_bin"] = pd.cut(
    front_all_qualified["forecast_vol_pct"],
    bins=FORECAST_VOL_BINS,
    labels=FORECAST_VOL_BIN_LABELS,
    include_lowest=True,
)

front_forecast_vol_state = summarize_trades(
    front_all_qualified,
    group_cols=["candidate_id", "tenor", "front_forecast_vol_bin"],
    diagnostic_label="front_all_qualified_by_tenor_and_forecast_vol_state",
)

front_forecast_vol_state = attach_ranked_params(front_forecast_vol_state, ranked)

front_forecast_vol_state_summary = summarize_trades(
    front_all_qualified,
    group_cols=["candidate_id", "front_forecast_vol_bin"],
    diagnostic_label="front_all_qualified_by_forecast_vol_state",
)

front_forecast_vol_state_summary = attach_ranked_params(front_forecast_vol_state_summary, ranked)

# ======================================================================================
# 6. Front RSI binding diagnostics
# ======================================================================================

primary_actual_hash_rows = []

for candidate_id, g in actual_primary.groupby("candidate_id"):
    primary_actual_hash_rows.append({
        "candidate_id": candidate_id,
        "actual_primary_trade_set_hash": make_trade_set_hash(g),
        "actual_primary_selected_rows": int(len(g)),
    })

actual_hash = pd.DataFrame(primary_actual_hash_rows)

front_hash_rows = []

for candidate_id, g in actual_front.groupby("candidate_id"):
    front_hash_rows.append({
        "candidate_id": candidate_id,
        "actual_front_trade_set_hash": make_trade_set_hash(g),
        "actual_front_selected_rows": int(len(g)),
    })

front_hash = pd.DataFrame(front_hash_rows)

rsi_diag_base = ranked[
    ranked["candidate_id"].isin(top_candidate_ids)
].copy()

rsi_diag_base = rsi_diag_base.merge(actual_hash, on="candidate_id", how="left")
rsi_diag_base = rsi_diag_base.merge(front_hash, on="candidate_id", how="left")

signature_cols_without_front_rsi = [
    "Front_model_vrp_log",
    "Front_model_vrp_z",
    "Front_forecast_vol_pct_min",
    "Middle_model_vrp_log",
    "Middle_model_vrp_z",
    "Middle_RSI14_max",
    "Middle_forecast_vol_pct_min",
    "Back_model_vrp_log",
    "Back_model_vrp_z",
    "Back_RSI14_max",
    "Back_forecast_vol_pct_min",
]

signature_cols_without_front_rsi = [
    c for c in signature_cols_without_front_rsi
    if c in rsi_diag_base.columns
]

rsi_binding_diagnostics = (
    rsi_diag_base
    .groupby(signature_cols_without_front_rsi, dropna=False)
    .agg(
        candidate_count=("candidate_id", "nunique"),
        candidate_ids=("candidate_id", lambda x: ", ".join(map(str, x))),
        review_ranks=("review_rank", lambda x: ", ".join(map(str, x))),
        front_rsi_values=("Front_RSI14_max", lambda x: ", ".join(map(lambda y: str(float(y)), sorted(pd.to_numeric(x, errors="coerce").dropna().unique())))),
        unique_front_rsi_values=("Front_RSI14_max", lambda x: int(pd.to_numeric(x, errors="coerce").nunique())),
        unique_actual_primary_trade_sets=("actual_primary_trade_set_hash", "nunique"),
        unique_actual_front_trade_sets=("actual_front_trade_set_hash", "nunique"),
        min_avg_pnl_per_day=("avg_pnl_per_day", "min"),
        max_avg_pnl_per_day=("avg_pnl_per_day", "max"),
        min_2026_avg_pnl_per_day=("avg_pnl_per_day_2026", "min"),
        max_2026_avg_pnl_per_day=("avg_pnl_per_day_2026", "max"),
        min_trades=("trades", "min"),
        max_trades=("trades", "max"),
    )
    .reset_index()
)

rsi_binding_diagnostics["front_rsi_nonbinding_trade_set_test"] = (
    (rsi_binding_diagnostics["unique_front_rsi_values"] > 1)
    & (rsi_binding_diagnostics["unique_actual_primary_trade_sets"] == 1)
    & (rsi_binding_diagnostics["unique_actual_front_trade_sets"] == 1)
)

rsi_binding_diagnostics["front_rsi_nonbinding_metric_test"] = (
    (rsi_binding_diagnostics["unique_front_rsi_values"] > 1)
    & np.isclose(
        rsi_binding_diagnostics["min_avg_pnl_per_day"],
        rsi_binding_diagnostics["max_avg_pnl_per_day"],
        rtol=0,
        atol=1e-9,
    )
    & np.isclose(
        rsi_binding_diagnostics["min_2026_avg_pnl_per_day"],
        rsi_binding_diagnostics["max_2026_avg_pnl_per_day"],
        rtol=0,
        atol=1e-9,
    )
)

rsi_binding_diagnostics = rsi_binding_diagnostics.sort_values(
    [
        "front_rsi_nonbinding_trade_set_test",
        "candidate_count",
        "max_avg_pnl_per_day",
    ],
    ascending=[False, False, False],
).reset_index(drop=True)

# ======================================================================================
# 7. Diagnostic conclusion flags
# ======================================================================================

top25 = ranked.head(25).copy()

top25_front_fv_all_at_max = bool(
    "Front_forecast_vol_pct_min_at_grid_max" in top25.columns
    and top25["Front_forecast_vol_pct_min_at_grid_max"].astype(bool).all()
)

top_candidate_id = ranked.iloc[0]["candidate_id"]

top_front_tenor = actual_front_by_tenor[
    actual_front_by_tenor["candidate_id"].eq(top_candidate_id)
].copy()

top_9d_avg = np.nan
top_12d_avg = np.nan
top_15d_avg = np.nan

if not top_front_tenor.empty:
    if (top_front_tenor["tenor"] == 9).any():
        top_9d_avg = float(top_front_tenor.loc[top_front_tenor["tenor"].eq(9), "avg_pnl_per_day"].iloc[0])
    if (top_front_tenor["tenor"] == 12).any():
        top_12d_avg = float(top_front_tenor.loc[top_front_tenor["tenor"].eq(12), "avg_pnl_per_day"].iloc[0])
    if (top_front_tenor["tenor"] == 15).any():
        top_15d_avg = float(top_front_tenor.loc[top_front_tenor["tenor"].eq(15), "avg_pnl_per_day"].iloc[0])

top_9d_negative = bool(pd.notna(top_9d_avg) and top_9d_avg < 0)
top_12d_positive = bool(pd.notna(top_12d_avg) and top_12d_avg > 0)
top_15d_positive = bool(pd.notna(top_15d_avg) and top_15d_avg > 0)

top_ex9d_delta = np.nan

if not front_ex9d_comparison.empty:
    row = front_ex9d_comparison[front_ex9d_comparison["candidate_id"].eq(top_candidate_id)]
    if not row.empty and "delta_ex9d_minus_actual_avg_pnl_per_day" in row.columns:
        top_ex9d_delta = float(row["delta_ex9d_minus_actual_avg_pnl_per_day"].iloc[0])

diagnostic_conclusion = pd.DataFrame([
    {
        "diagnostic": "top25_front_forecast_vol_floor_all_at_grid_max",
        "status": "WARN" if top25_front_fv_all_at_max else "PASS",
        "detail": f"top25_all_at_front_fv_floor_max={top25_front_fv_all_at_max}",
    },
    {
        "diagnostic": "top_candidate_9d_avg_pnl_per_day_negative",
        "status": "WARN" if top_9d_negative else "PASS",
        "detail": f"top_candidate={top_candidate_id}; 9D_avg_pnl_per_day={top_9d_avg}",
    },
    {
        "diagnostic": "top_candidate_12d_and_15d_positive",
        "status": "PASS" if top_12d_positive and top_15d_positive else "WARN",
        "detail": f"top_candidate={top_candidate_id}; 12D={top_12d_avg}; 15D={top_15d_avg}",
    },
    {
        "diagnostic": "diagnostic_excluding_9d_improves_top_candidate_avg_pnl_per_day",
        "status": "INFO",
        "detail": f"top_candidate={top_candidate_id}; ex9d_minus_actual_avg_pnl_per_day={top_ex9d_delta}",
    },
    {
        "diagnostic": "front_rsi_nonbinding_groups_found",
        "status": "INFO",
        "detail": f"nonbinding_trade_set_groups={int(rsi_binding_diagnostics['front_rsi_nonbinding_trade_set_test'].sum()) if not rsi_binding_diagnostics.empty else 0}",
    },
    {
        "diagnostic": "no_new_grid_or_sweep",
        "status": "PASS",
        "detail": "Cell 10 uses existing Cell 8/9 outputs only.",
    },
    {
        "diagnostic": "no_final_lock",
        "status": "PASS",
        "detail": "Cell 10 is diagnostic only.",
    },
])

# ======================================================================================
# 8. Save outputs
# ======================================================================================

front_tenor_summary_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_actual_front_by_tenor_{CELL10_TIMESTAMP}.csv"
front_summary_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_front_summary_{CELL10_TIMESTAMP}.csv"
front_ex9d_comparison_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_ex9d_comparison_{CELL10_TIMESTAMP}.csv"
reselected_summary_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_ex9d_reselected_summary_{CELL10_TIMESTAMP}.csv"
reselected_by_bucket_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_ex9d_reselected_by_bucket_{CELL10_TIMESTAMP}.csv"
reselected_by_tenor_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_ex9d_reselected_by_tenor_{CELL10_TIMESTAMP}.csv"
front_forecast_state_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_forecast_vol_state_by_tenor_{CELL10_TIMESTAMP}.csv"
front_forecast_state_summary_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_forecast_vol_state_summary_{CELL10_TIMESTAMP}.csv"
rsi_binding_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_front_rsi_binding_diagnostics_{CELL10_TIMESTAMP}.csv"
diagnostic_conclusion_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_diagnostic_conclusion_{CELL10_TIMESTAMP}.csv"
reselected_trade_panel_path = OUT_PROCESSED_DIR / f"08_front_tenor_boundary_ex9d_reselected_trade_panel_{CELL10_TIMESTAMP}.parquet"
validation_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_validation_{CELL10_TIMESTAMP}.csv"
manifest_path = OUT_AUDIT_DIR / f"08_front_tenor_boundary_manifest_{CELL10_TIMESTAMP}.json"

front_summary_combined = pd.concat(
    [
        actual_front_all_summary,
        actual_front_ex_9d_drop_summary,
    ],
    ignore_index=True,
)

front_summary_combined = attach_ranked_params(front_summary_combined, ranked)

actual_front_by_tenor.to_csv(front_tenor_summary_path, index=False)
front_summary_combined.to_csv(front_summary_path, index=False)
front_ex9d_comparison.to_csv(front_ex9d_comparison_path, index=False)
diagnostic_reselected_summary.to_csv(reselected_summary_path, index=False)
diagnostic_reselected_by_bucket.to_csv(reselected_by_bucket_path, index=False)
diagnostic_reselected_by_tenor.to_csv(reselected_by_tenor_path, index=False)
front_forecast_vol_state.to_csv(front_forecast_state_path, index=False)
front_forecast_vol_state_summary.to_csv(front_forecast_state_summary_path, index=False)
rsi_binding_diagnostics.to_csv(rsi_binding_path, index=False)
diagnostic_conclusion.to_csv(diagnostic_conclusion_path, index=False)
diagnostic_reselected.to_parquet(reselected_trade_panel_path, index=False)

# ======================================================================================
# 9. Validation
# ======================================================================================

validation_rows = []

def add_validation(check, status, detail):
    validation_rows.append({
        "check": check,
        "status": status,
        "detail": detail,
    })

required_selected_cols = [
    "candidate_id",
    "selection_universe",
    "trade_date",
    "tenor",
    "tenor_bucket",
    "tenor_bucket_order",
    "normalized_pnl_dollars",
    "normalized_pnl_per_day",
    "win",
    "forecast_vol_pct",
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
]

missing_selected_cols = [c for c in required_selected_cols if c not in selected_panel.columns]

add_validation(
    "selected_trade_panel_loaded",
    "PASS" if not selected_panel.empty else "FAIL",
    f"rows={len(selected_panel):,}; path={selected_trade_panel_path}",
)

add_validation(
    "required_selected_columns_available",
    "PASS" if not missing_selected_cols else "FAIL",
    f"missing={missing_selected_cols}",
)

add_validation(
    "ranked_summary_loaded",
    "PASS" if not ranked.empty else "FAIL",
    f"rows={len(ranked):,}; path={ranked_summary_path}",
)

add_validation(
    "top_candidate_set_created",
    "PASS" if len(top_candidate_ids) > 0 else "FAIL",
    f"top_n={TOP_N_CANDIDATES}; actual={len(top_candidate_ids)}",
)

add_validation(
    "actual_primary_universe_available",
    "PASS" if not actual_primary.empty else "FAIL",
    f"rows={len(actual_primary):,}; universe={PRIMARY_SELECTION_UNIVERSE}",
)

add_validation(
    "all_qualified_universe_available",
    "PASS" if not all_qualified.empty else "FAIL",
    f"rows={len(all_qualified):,}; universe={ALL_QUALIFIED_UNIVERSE}",
)

add_validation(
    "front_actual_by_tenor_created",
    "PASS" if not actual_front_by_tenor.empty else "FAIL",
    f"rows={len(actual_front_by_tenor):,}",
)

add_validation(
    "diagnostic_ex9d_reselection_created",
    "PASS" if not diagnostic_reselected.empty else "FAIL",
    f"rows={len(diagnostic_reselected):,}",
)

add_validation(
    "front_ex9d_comparison_created",
    "PASS" if not front_ex9d_comparison.empty else "FAIL",
    f"rows={len(front_ex9d_comparison):,}",
)

add_validation(
    "forecast_vol_state_diagnostics_created",
    "PASS" if not front_forecast_vol_state.empty else "WARN",
    f"rows={len(front_forecast_vol_state):,}",
)

add_validation(
    "front_rsi_binding_diagnostics_created",
    "PASS" if not rsi_binding_diagnostics.empty else "WARN",
    f"rows={len(rsi_binding_diagnostics):,}",
)

add_validation(
    "top25_front_forecast_vol_floor_boundary_confirmed",
    "WARN" if top25_front_fv_all_at_max else "PASS",
    f"top25_all_at_front_fv_floor_max={top25_front_fv_all_at_max}",
)

add_validation(
    "top_candidate_9d_negative_check",
    "WARN" if top_9d_negative else "PASS",
    f"top_candidate={top_candidate_id}; 9D_avg_pnl_per_day={top_9d_avg}",
)

add_validation(
    "no_new_grid",
    "PASS",
    "No candidate grid created.",
)

add_validation(
    "no_new_sweep",
    "PASS",
    "Only existing selected trades were recombined diagnostically.",
)

add_validation(
    "no_final_candidate_selection",
    "PASS",
    "Diagnostic only.",
)

add_validation(
    "no_secondary",
    "PASS",
    "Core only.",
)

add_validation(
    "no_sizing_changes",
    "PASS",
    "No sizing fields changed.",
)

add_validation(
    "no_production_lock",
    "PASS",
    "No production threshold lock performed.",
)

validation = pd.DataFrame(validation_rows)
validation.to_csv(validation_path, index=False)

failures = validation[validation["status"] == "FAIL"]

manifest = {
    "notebook": "07_unified_fds_core_signal_threshold_research_v1.ipynb",
    "cell": "Cell 10 — Front tenor and boundary diagnostics",
    "timestamp": CELL10_TIMESTAMP,
    "top_n_candidates": TOP_N_CANDIDATES,
    "primary_selection_universe": PRIMARY_SELECTION_UNIVERSE,
    "all_qualified_universe": ALL_QUALIFIED_UNIVERSE,
    "selected_trade_panel_path": str(selected_trade_panel_path),
    "ranked_summary_path": str(ranked_summary_path),
    "ranked_by_tenor_path": str(ranked_by_tenor_path),
    "ranked_by_bucket_path": str(ranked_by_bucket_path),
    "ranked_by_year_path": str(ranked_by_year_path),
    "front_tenor_summary_path": str(front_tenor_summary_path),
    "front_summary_path": str(front_summary_path),
    "front_ex9d_comparison_path": str(front_ex9d_comparison_path),
    "reselected_summary_path": str(reselected_summary_path),
    "reselected_by_bucket_path": str(reselected_by_bucket_path),
    "reselected_by_tenor_path": str(reselected_by_tenor_path),
    "front_forecast_state_path": str(front_forecast_state_path),
    "front_forecast_state_summary_path": str(front_forecast_state_summary_path),
    "rsi_binding_path": str(rsi_binding_path),
    "diagnostic_conclusion_path": str(diagnostic_conclusion_path),
    "reselected_trade_panel_path": str(reselected_trade_panel_path),
    "validation_path": str(validation_path),
    "top_candidate_id": str(top_candidate_id),
    "top_candidate_9d_avg_pnl_per_day": top_9d_avg,
    "top_candidate_12d_avg_pnl_per_day": top_12d_avg,
    "top_candidate_15d_avg_pnl_per_day": top_15d_avg,
    "top25_front_forecast_vol_floor_all_at_grid_max": top25_front_fv_all_at_max,
    "notes": [
        "Diagnostic only.",
        "No new threshold grid.",
        "No new sweep expansion.",
        "No final candidate selection.",
        "No Secondary.",
        "No sizing changes.",
        "No production lock.",
        "Diagnostic ex-9D selection recombines already-qualified trades only.",
    ],
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2, default=str)

if not failures.empty:
    display(validation)
    raise RuntimeError("Cell 10 validation failed. Review validation output above.")

# ======================================================================================
# 10. Display review
# ======================================================================================

print("=" * 100)
print("Cell 10 — Front tenor and boundary diagnostics")
print("=" * 100)
print(f"Selected trade panel:                   {selected_trade_panel_path}")
print(f"Ranked summary:                         {ranked_summary_path}")
print(f"Top candidates reviewed:                {len(top_candidate_ids):,}")
print(f"Actual primary rows reviewed:           {len(actual_primary):,}")
print(f"All-qualified rows reviewed:            {len(all_qualified):,}")
print(f"Diagnostic ex-9D reselected rows:        {len(diagnostic_reselected):,}")
print(f"Top candidate:                          {top_candidate_id}")
print(f"Top candidate 9D avg P&L/day:            {top_9d_avg:,.2f}")
print(f"Top candidate 12D avg P&L/day:           {top_12d_avg:,.2f}")
print(f"Top candidate 15D avg P&L/day:           {top_15d_avg:,.2f}")
print(f"Top 25 Front FV floor all at grid max:   {top25_front_fv_all_at_max}")
print("No new grid:                            True")
print("No new sweep:                           True")
print("No final candidate selection:           True")
print("No Secondary:                           True")
print("No sizing changes:                      True")
print("No production lock:                     True")

print()
print("Validation:")
display(validation)

print()
print("Diagnostic conclusions:")
display(diagnostic_conclusion)

print()
print("Top 20 — actual Front selected by tenor:")
display(
    actual_front_by_tenor[
        actual_front_by_tenor["review_rank"].le(20)
    ].sort_values(["review_rank", "tenor"])
)

print()
print("Top 20 — actual vs diagnostic one-trade-per-bucket/date excluding Front 9D:")
compare_display_cols = [
    "review_rank",
    "candidate_id",
    "actual_trades",
    "ex9d_trades",
    "delta_ex9d_minus_actual_trades",
    "actual_avg_pnl_per_day",
    "ex9d_avg_pnl_per_day",
    "delta_ex9d_minus_actual_avg_pnl_per_day",
    "actual_total_pnl",
    "ex9d_total_pnl",
    "delta_ex9d_minus_actual_total_pnl",
    "actual_profit_factor",
    "ex9d_profit_factor",
    "delta_ex9d_minus_actual_profit_factor",
    "actual_pnl_per_day_drawdown",
    "ex9d_pnl_per_day_drawdown",
    "delta_ex9d_minus_actual_pnl_per_day_drawdown",
    "actual_avg_pnl_per_day_2026",
    "ex9d_avg_pnl_per_day_2026",
    "delta_ex9d_minus_actual_avg_pnl_per_day_2026",
    "Front_model_vrp_log",
    "Front_model_vrp_z",
    "Front_RSI14_max",
    "Front_forecast_vol_pct_min",
    "Middle_model_vrp_log",
    "Middle_model_vrp_z",
    "Middle_RSI14_max",
    "Middle_forecast_vol_pct_min",
]
display(front_ex9d_comparison[[c for c in compare_display_cols if c in front_ex9d_comparison.columns]].head(20))

print()
print("Top 20 — diagnostic ex-9D reselected by bucket:")
display(
    diagnostic_reselected_by_bucket[
        diagnostic_reselected_by_bucket["review_rank"].le(20)
    ].sort_values(["review_rank", "tenor_bucket_order"])
)

print()
print("Top 20 — diagnostic ex-9D reselected by tenor:")
display(
    diagnostic_reselected_by_tenor[
        diagnostic_reselected_by_tenor["review_rank"].le(20)
    ].sort_values(["review_rank", "tenor_bucket_order", "tenor"])
)

print()
print("Top 20 — Front all-qualified by forecast-vol state and tenor:")
display(
    front_forecast_vol_state[
        front_forecast_vol_state["review_rank"].le(20)
    ].sort_values(["review_rank", "tenor", "front_forecast_vol_bin"])
)

print()
print("Front RSI binding diagnostics:")
display(rsi_binding_diagnostics.head(30))

print()
print("Saved outputs:")
for p in [
    front_tenor_summary_path,
    front_summary_path,
    front_ex9d_comparison_path,
    reselected_summary_path,
    reselected_by_bucket_path,
    reselected_by_tenor_path,
    front_forecast_state_path,
    front_forecast_state_summary_path,
    rsi_binding_path,
    diagnostic_conclusion_path,
    reselected_trade_panel_path,
    validation_path,
    manifest_path,
]:
    print(f"  {p}")

print("\nCELL 10 PASSED")

C:\Users\patri\AppData\Local\Temp\ipykernel_21560\1391526047.py:178: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for keys, g in d.groupby(group_cols, dropna=False):
C:\Users\patri\AppData\Local\Temp\ipykernel_21560\1391526047.py:178: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for keys, g in d.groupby(group_cols, dropna=False):

====================================================================================================
Cell 10 — Front tenor and boundary diagnostics
====================================================================================================
Selected trade panel:                   C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\06_core_front_expanded_sweep_selected_trade_panel_20260704_215631.parquet
Ranked summary:                         C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\07_core_candidate_ranked_summary_20260704_220821.csv
Top candidates reviewed:                50
Actual primary rows reviewed:           21,411
All-qualified rows reviewed:            58,599
Diagnostic ex-9D reselected rows:        21,049
Top candidate:                          core_front_expanded_00168
Top candidate 9D avg P&L/day:            -129.44
Top candidate 12D avg P&L/day:           691.72
Top candidate 15D avg P&L/day:           907.17
Top 25 Front FV floor all at grid max:   True
No new grid:                            True
No new sweep:                           True
No final candidate selection:           True
No Secondary:                           True
No sizing changes:                      True
No production lock:                     True

Validation:

                                                check status                                             detail
0                         selected_trade_panel_loaded   PASS  rows=659,356; path=C:\Users\patri\vrp_project\...
1                 required_selected_columns_available   PASS                                         missing=[]
2                               ranked_summary_loaded   PASS  rows=320; path=C:\Users\patri\vrp_project\data...
3                           top_candidate_set_created   PASS                                top_n=50; actual=50
4                   actual_primary_universe_available   PASS  rows=21,411; universe=one_trade_per_bucket_per...
5                    all_qualified_universe_available   PASS         rows=58,599; universe=all_qualified_trades
6                       front_actual_by_tenor_created   PASS                                           rows=150
7                 diagnostic_ex9d_reselection_created   PASS                                        rows=21,049
8                       front_ex9d_comparison_created   PASS                                            rows=50
9              forecast_vol_state_diagnostics_created   PASS                                           rows=600
10              front_rsi_binding_diagnostics_created   PASS                                            rows=20
11  top25_front_forecast_vol_floor_boundary_confirmed   WARN               top25_all_at_front_fv_floor_max=True
12                    top_candidate_9d_negative_check   WARN  top_candidate=core_front_expanded_00168; 9D_av...
13                                        no_new_grid   PASS                         No candidate grid created.
14                                       no_new_sweep   PASS  Only existing selected trades were recombined ...
15                       no_final_candidate_selection   PASS                                   Diagnostic only.
16                                       no_secondary   PASS                                         Core only.
17                                  no_sizing_changes   PASS                          No sizing fields changed.
18                                 no_production_lock   PASS            No production threshold lock performed.

Diagnostic conclusions:

                                          diagnostic status                                             detail
0     top25_front_forecast_vol_floor_all_at_grid_max   WARN               top25_all_at_front_fv_floor_max=True
1          top_candidate_9d_avg_pnl_per_day_negative   WARN  top_candidate=core_front_expanded_00168; 9D_av...
2                 top_candidate_12d_and_15d_positive   PASS  top_candidate=core_front_expanded_00168; 12D=6...
3  diagnostic_excluding_9d_improves_top_candidate...   INFO  top_candidate=core_front_expanded_00168; ex9d_...
4                  front_rsi_nonbinding_groups_found   INFO                     nonbinding_trade_set_groups=19
5                               no_new_grid_or_sweep   PASS       Cell 10 uses existing Cell 8/9 outputs only.
6                                      no_final_lock   PASS                        Cell 10 is diagnostic only.

Top 20 — actual Front selected by tenor:

,diagnostic_label,candidate_id,tenor,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,avg_forecast_vol_pct,min_forecast_vol_pct,max_forecast_vol_pct,avg_model_vrp_log,avg_model_vrp_z_3m,avg_model_vrp_z_1y,review_rank,robustness_screen_pass,robustness_score_after_boundary_penalty,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Back_RSI14_max,Back_forecast_vol_pct_min,Front_forecast_vol_pct_min_at_grid_max,Front_model_vrp_log_at_grid_max
66,actual_selected_front_by_tenor,core_front_expanded_00168,9,37,37,2021-09-20,2026-03-23,9,9,9.0,0.702703,-43101.909470,-1164.916472,12815.804660,-93387.142625,34056.002766,0.902752,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-4789.101052,-129.435164,1423.978296,-10376.349181,3784.000307,0.902752,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,17.789539,14.849697,44.221370,0.947306,1.363329,1.236607,1,True,0.846453,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
67,actual_selected_front_by_tenor,core_front_expanded_00168,12,41,41,2021-12-03,2026-03-26,12,12,12.0,0.756098,340326.024340,8300.634740,14831.966723,-34533.046342,23041.639194,3.046018,-97297.099252,-85992.436400,-50247.933007,88198.337843,0,0,0,28360.502028,691.719562,1235.997227,-2877.753862,1920.136599,3.046018,-8108.091604,-7166.036367,-4187.327751,7349.861487,4,23000.973924,479.186957,-9719.373848,10,-3332.596641,-27.771639,-34533.046342,16.789384,14.724990,21.622469,1.079547,1.606122,1.679719,1,True,0.846453,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
68,actual_selected_front_by_tenor,core_front_expanded_00168,15,44,44,2022-01-21,2026-04-06,15,15,15.0,0.909091,598730.726190,13607.516504,19174.236934,-108475.796818,38031.055016,5.062776,-111137.668230,-86408.441669,17201.570824,128127.175790,1,1,0,39915.381746,907.167767,1278.282462,-7231.719788,2535.403668,5.062776,-7409.177882,-5760.562778,1146.771388,8541.811719,9,171898.199151,1273.319994,14103.157032,4,54763.357418,912.722624,-4542.821791,18.246005,14.560532,41.974813,0.951312,1.459961,1.563556,1,True,0.846453,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
72,actual_selected_front_by_tenor,core_front_expanded_00182,9,37,37,2021-09-20,2026-03-23,9,9,9.0,0.702703,-43101.909470,-1164.916472,12815.804660,-93387.142625,34056.002766,0.902752,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-4789.101052,-129.435164,1423.978296,-10376.349181,3784.000307,0.902752,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,17.789539,14.849697,44.221370,0.947306,1.363329,1.236607,2,True,0.846453,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
73,actual_selected_front_by_tenor,core_front_expanded_00182,12,41,41,2021-12-03,2026-03-26,12,12,12.0,0.756098,340326.024340,8300.634740,14831.966723,-34533.046342,23041.639194,3.046018,-97297.099252,-85992.436400,-50247.933007,88198.337843,0,0,0,28360.502028,691.719562,1235.997227,-2877.753862,1920.136599,3.046018,-8108.091604,-7166.036367,-4187.327751,7349.861487,4,23000.973924,479.186957,-9719.373848,10,-3332.596641,-27.771639,-34533.046342,16.789384,14.724990,21.622469,1.079547,1.606122,1.679719,2,True,0.846453,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
74,actual_selected_front_by_tenor,core_front_expanded_00182,15,44,44,2022-01-21,2026-04-06,15,15,15.0,0.909091,598730.726190,13607.516504,19174.236934,-108475.796818,38031.055016,5.062776,-111137.668230,-86408.441669,17201.570824,128127.175790,1,1,0,39915.381746,907.167767,1278.282462,-7231.719788,2535.403668,5.062776,-7409.177882,-5760.562778,1146.771388,8541.811719,9,171898.199151,1273.319994,14103.157032,4,54763.357418,912.722624,-4542.821791,18.246005,14.560532,41.974813,0.951312,1.459961,1.563556,2,True,0.846453,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
84,actual_selected_front_by_tenor,core_front_expanded_00198,9,37,37,2021-09-20,2026-03-23,9,9,9.0,0.702703,-43101.909470,-1164.916472,12815.804660,-93387.142625,34056.002766,0.902752,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-4789.101052,-129.435164,1423.978296,-10376.349181,3784.000307,0.902752,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,17.789539,14.849697,44.221370,0.947306,1.363329,1.236607,3,True,0.846453,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
85,actual_selected_front_by_tenor,core_front_expanded_00198,12,41,41,2021-12-03,2026-03-26,12,12,12.0,0.756098,340326.024340,8300.634740,14831.966723,-34533.046342,23041.639194,3.046018,-97297.099252,-85992.436400,-50247.933007,88198.337843,0,0,0,28360.502028,691.719562,1235.997227,-2877.753862,1920.136599,3.046018,-8108.091604,-7166.036367,-4187.327751,7349.861487,4,23000.973924,479.186957,-9719.373848,10,-3332.596641,-27.771639,-34533.046342,16.789384,14.724990,21.622469,1.079547,1.606122,1.679719,3,True,0.846453,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
86,actual_selected_front_by_tenor,core_front_expanded_00198,15,44,44,2022-01-21,2026-04-06,15,15,15.0,0.909091,598730.726190,13607.516504,19174.236934,-108475.796818,38031.055016,5.062776,-111137.668230,-86408.441669,17201.570824,128127.175790,1,1,0,39915.381746,907.167767,1278.282462,-7231.719788,2535.403668,5.062776,-7409.177882,-5760.562778,1146.771388,8541.811719,9,171898.199151,1273.319994,14103.157032,4,54763.357418,912.722624,-4542.821791,18.246005,14.560532,41.974813,0.951312,1.459961,1.563556,3,True,0.846453,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
63,actual_selected_front_by_tenor,core_front_expanded_00167,9,37,37,2021-09-20,2026-03-23,9,9,9.0,0.702703,-43101.909470,-1164.916472,12815.804660,-93387.142625,34056.002766,0.902752,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-4789.101052,-129.435164,1423.978296,-10376.349181,3784.000307,0.902752,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,17.789539,14.849697,44.221370,0.947306,1.363329,1.236607,4,True,0.839922,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
64,actual_selected_front_by_tenor,core_front_expanded_00167,12,41,41,2021-12-03,2026-03-26,12,12,12.0,0.756098,340326.024340,8300.634740,14831.966723,-34533.046342,23041.639194,3.046018,-97297.099252,-85992.436400,-50247.933007,88198.337843,0,0,0,28360.502028,691.719562,1235.997227,-2877.753862,1920.136599,3.046018,-8108.091604,-7166.036367,-4187.327751,7349.861487,4,23000.973924,479.186957,-9719.373848,10,-3332.596641,-27.771639,-34533.046342,16.789384,14.724990,21.622469,1.079547,1.606122,1.679719,4,True,0.839922,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
65,actual_selected_front_by_tenor,core_front_expanded_00167,15,44,44,2022-01-21,2026-04-06,15,15,15.0,0.909091,598730.726190,13607.516504,19174.236934,-108475.796818,38031.055016,5.062776,-111137.668230,-86408.441669,17201.570824,128127.175790,1,1,0,39915.381746,907.167767,1278.282462,-7231.719788,2535.403668,5.062776,-7409.177882,-5760.562778,1146.771388,8541.811719,9,171898.199151,1273.319994,14103.157032,4,54763.357418,912.722624,-4542.821791,18.246005,14.560532,41.974813,0.951312,1.459961,1.563556,4,True,0.839922,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
69,actual_selected_front_by_tenor,core_front_expanded_00181,9,37,37,2021-09-20,2026-03-23,9,9,9.0,0.702703,-43101.909470,-1164.916472,12815.804660,-93387.142625,34056.002766,0.902752,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-4789.101052,-129.435164,1423.978296,-10376.349181,3784.000307,0.902752,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,17.789539,14.849697,44.221370,0.947306,1.363329,1.236607,5,True,0.839922,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
70,actual_selected_front_by_tenor,core_front_expanded_00181,12,41,41,2021-12-03,2026-03-26,12,12,12.0,0.756098,340326.024340,8300.634740,14831.966723,-34533.046342,23041.639194,3.046018,-97297.099252,-85992.436400,-50247.933007,88198.337843,0,0,0,28360.502028,691.719562,1235.997227,-2877.753862,1920.136599,3.046018,-8108.091604,-7166.036367,-4187.327751,7349.861487,4,23000.973924,479.186957,-9719.373848,10,-3332.596641,-27.771639,-34533.046342,16.789384,14.724990,21.622469,1.079547,1.606122,1.679719,5,True,0.839922,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
71,actual_selected_front_by_tenor,core_front_expanded_00181,15,44,44,2022-01-21,2026-04-06,15,15,15.0,0.909091,598730.726190,13607.516504,19174.236934,-108475.796818,38031.055016,5.062776,-111137.668230,-86408.441669,17201.570824,128127.175790,1,1,0,39915.381746,907.167767,1278.282462,-7231.719788,2535.403668,5.062776,-7409.177882,-5760.562778,1146.771388,8541.811719,9,171898.199151,1273.319994,14103.157032,4,54763.357418,912.722624,-4542.821791,18.246005,14.560532,41.974813,0.951312,1.459961,1.563556,5,True,0.839922,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
81,actual_selected_front_by_tenor,core_front_expanded_00197,9,37,37,2021-09-20,2026-03-23,9,9,9.0,0.702703,-43101.909470,-1164.916472,12815.804660,-93387.142625,34056.002766,0.902752,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-4789.101052,-129.435164,1423.978296,-10376.349181,3784.000307,0.902752,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,17.789539,14.849697,44.221370,0.947306,1.363329,1.236607,6,True,0.839922,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
82,actual_selected_front_by_tenor,core_front_expanded_00197,12,41,41,2021-12-03,2026-03-26,12,12,12.0,0.756098,340326.024340,8300.634740,14831.966723,-34533.046342,23041.639194,3.046018,-97297.099252,-85992.436400,-50247.933007,88198.337843,0,0,0,28360.502028,691.719562,1235.997227,-2877.753862,1920.136599,3.046018,-8108.091604,-7166.036367,-4187.327751,7349.861487,4,23000.973924,479.186957,-9719.373848,10,-3332.596641,-27.771639,-34533.046342,16.789384,14.724990,21.622469,1.079547,1.606122,1.679719,6,True,0.839922,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
83,actual_selected_front_by_tenor,core_front_expanded_00197,15,44,44,2022-01-21,2026-04-06,15,15,15.0,0.909091,598730.726190,13607.516504,19174.236934,-108475.796818,38031.055016,5.062776,-111137.668230,-86408.441669,17201.570824,128127.175790,1,1,0,39915.381746,907.167767,1278.282462,-7231.719788,2535.403668,5.062776,-7409.177882,-5760.562778,1146.771388,8541.811719,9,171898.199151,1273.319994,14103.157032,4,54763.357418,912.722624,-4542.821791,18.246005,14.560532,41.974813,0.951312,1.459961,1.563556,6,True,0.839922,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
114,actual_selected_front_by_tenor,core_front_expanded_00248,9,36,36,2021-09-20,2026-03-23,9,9,9.0,0.694444,-55024.127038,-1528.447973,13137.224499,-93387.142625,34056.002766,0.875853,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-6113.791893,-169.827553,1459.691611,-10376.349181,3784.000307,0.875853,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,17.825036,14.849697,44.221370,0.953087,1.375038,1.235345,7,True,0.835891,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
115,actual_selected_front_by_tenor,core_front_expanded_00248,12,38,38,2021-12-03,2026-03-26,12,12,12.0,0.763158,321818.871276,8468.917665,15292.055756,-34533.046342,23041.639194,3.054822,-97297.099252,-85992.436400,-22456.343030,120123.647210,0,0,0,26818.239273,705.743139,1274.337980,-2877.753862,1920.136599,3.054822,-8108.091604,-7166.036367,-1871.361919,10010.303934,2,18472.315484,769.679812,6005.032657,10,-3332.596641,-27.771639,-34533.046342,16.876643,14.724990,21.622469,1.107731,1.608783,1.727838,7,True,0.835891,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
116,actual_selected_front_by_tenor,core_front_expanded_00248,15,43,43,2022-01-21,2026-04-06,15,15,15.0,0.906977,584627.569158,13595.989980,19628.148297,-108475.796818,38031.055016,4.967077,-111137.668230,-86408.441669,17201.570824,128127.175790,1,1,0,38975.171277,906.399332,1308.543220,-7231.719788,2535.403668,4.967077,-7409.177882,-5760.562778,1146.771388,8541.811719,8,157795.042119,1314.958684,15613.049794,4,54763.357418,912.722624,-4542.821791,18.310888,14.560532,41.974813,0.956807,1.464912,1.566433,7,True,0.835891,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
120,actual_selected_front_by_tenor,core_front_expanded_00262,9,36,36,2021-09-20,2026-03-23,9,9,9.0,0.694444,-55024.127038,-1528.447973,13137.224499,-93387.142625,34056.002766,0.875853,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-6113.791893,-169.827553,1459.691611,-10376.349181,3784.000307,0.875853,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,17.825036,14.849697,44.221370,0.953087,1.375038,1.235345,8,True,0.835891,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
121,actual_selected_front_by_tenor,core_front_expanded_00262,12,38,38,2021-12-03,2026-03-26,12,12,12.0,0.763158,321818.871276,8468.917665,15292.055756,-34533.046342,23041.639194,3.054822,-97297.099252,-85992.436400,-22456.343030,120123.647210,0,0,0,26818.239273,705.743139,1274.337980,-2877.753862,1920.136599,3.054822,-8108.091604,-7166.036367,-1871.361919,10010.303934,2,18472.315484,769.679812,6005.032657,10,-3332.596641,-27.771639,-34533.046342,16.876643,14.724990,21.622469,1.107731,1.608783,1.727838,8,True,0.835891,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
122,actual_selected_front_by_tenor,core_front_expanded_00262,15,43,43,2022-01-21,2026-04-06,15,15,15.0,0.906977,584627.569158,13595.989980,19628.148297,-108475.796818,38031.055016,4.967077,-111137.668230,-86408.441669,17201.570824,128127.175790,1,1,0,38975.171277,906.399332,1308.543220,-7231.719788,2535.403668,4.967077,-7409.177882,-5760.562778,1146.771388,8541.811719,8,157795.042119,1314.958684,15613.049794,4,54763.357418,912.722624,-4542.821791,18.310888,14.560532,41.974813,0.956807,1.464912,1.566433,8,True,0.835891,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
132,actual_selected_front_by_tenor,core_front_expanded_00278,9,36,36,2021-09-20,2026-03-23,9,9,9.0,0.694444,-55024.127038,-1528.447973,13137.224499,-93387.142625,34056.002766,0.875853,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-6113.791893,-169.827553,1459.691611,-10376.349181,3784.000307,0.875853,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,17.825036,14.849697,44.221370,0.953087,1.375038,1.235345,9,True,0.835891,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
133,actual_selected_front_by_tenor,core_front_expanded_00278,12,38,38,2021-12-03,2026-03-26,12,12,12.0,0.763158,321818.871276,8468.917665,15292.055756,-34533.046342,23041.639194,3.054822,-97297.099252,-85992.436400,-22456.343030,120123.647210,0,0,0,26818.239273,705.743139,1274.337980,-2877.753862,1920.136599,3.054822,-8108.091604,-7166.036367,-1871.361919,10010.303934,2,18472.315484,769.679812,6005.032657,10,-3332.596641,-27.771639,-34533.046342,16.876643,14.724990,21.622469,1.107731,1.608783,1.727838,9,True,0.835891,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
134,actual_selected_front_by_tenor,core_front_expanded_00278,15,43,43,2022-01-21,2026-04-06,15,15,15.0,0.906977,584627.569158,13595.989980,19628.148297,-108475.796818,38031.055016,4.967077,-111137.668230,-86408.441669,17201.570824,128127.175790,1,1,0,38975.171277,906.399332,1308.543220,-7231.719788,2535.403668,4.967077,-7409.177882,-5760.562778,1146.771388,8541.811719,8,157795.042119,1314.958684,15613.049794,4,54763.357418,912.722624,-4542.821791,18.310888,14.560532,41.974813,0.956807,1.464912,1.566433,9,True,0.835891,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
75,actual_selected_front_by_tenor,core_front_expanded_00183,9,37,37,2021-09-20,2026-03-23,9,9,9.0,0.702703,-43101.909470,-1164.916472,12815.804660,-93387.142625,34056.002766,0.902752,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-4789.101052,-129.435164,1423.978296,-10376.349181,3784.000307,0.902752,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,17.789539,14.849697,44.221370,0.947306,1.363329,1.236607,10,True,0.820937,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,False
76,actual_selected_front_by_tenor,core_front_expanded_00183,12,41,41,2021-12-03,2026-03-26,12,12,12.0,0.756098,340326.024340,8300.634740,14831.966723,-34533.046342,23041.639194,3.046018,-97297.099252,-85992.436400,-50247.933007,88198.337843,0,0,0,28360.502028,691.719562,1235.997227,-2877.753862,1920.136599,3.046018,-8108.091604,-7166.036367,-4187.327751,7349.861487,4,23000.973924,479.186957,-9719.373848,10,-3332.596641,-27.771639,-34533.046342,16.789384,14.724990,21.622469,1.079547,1.606122,1.679719,10,True,0.820937,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,False
77,actual_selected_front_by_tenor,core_front_expanded_00183,15,44,44,2022-01-21,2026-04-06,15,15,15.0,0.909091,598730.726190,13607.516504,19174.236934,-108475.796818,38031.055016,5.062776,-111137.668230,-86408.441669,17201.570824,128127.175790,1,1,0,39915.381746,907.167767,1278.282462,-7231.719788,2535.403668,5.062776,-7409.177882,-5760.562778,1146.771388,8541.811719,9,171898.199151,1273.319994,14103.157032,4,54763.357418,912.722624,-4542.821791,18.246005,14.560532,41.974813,0.951312,1.459961,1.563556,10,True,0.820937,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,False
87,actual_selected_front_by_tenor,core_front_expanded_00199,9,37,37,2021-09-20,2026-03-23,9,9,9.0,0.702703,-43101.909470,-1164.916472,12815.804660,-93387.142625,34056.002766,0.902752,-308609.812578,-188630.697140,-308609.812578,-247038.070135,3,0,0,-4789.101052,-129.435164,1423.978296,-10376.349181,3784.000307,0.902752,-34289.979175,-20958.966349,-34289.979175,-27448.674459,3,6266.310786,232.085585,-40441.053294,2,27246.098629,1513.672146,11929.277477,17.789539,14.849697,44.221370,0.947306,1.363329,1.236607,11,True,0.820937,0.70,0.65,64.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,False

Top 20 — actual vs diagnostic one-trade-per-bucket/date excluding Front 9D:

,review_rank,candidate_id,actual_trades,ex9d_trades,delta_ex9d_minus_actual_trades,actual_avg_pnl_per_day,ex9d_avg_pnl_per_day,delta_ex9d_minus_actual_avg_pnl_per_day,actual_total_pnl,ex9d_total_pnl,delta_ex9d_minus_actual_total_pnl,actual_profit_factor,ex9d_profit_factor,delta_ex9d_minus_actual_profit_factor,actual_pnl_per_day_drawdown,ex9d_pnl_per_day_drawdown,delta_ex9d_minus_actual_pnl_per_day_drawdown,actual_avg_pnl_per_day_2026,ex9d_avg_pnl_per_day_2026,delta_ex9d_minus_actual_avg_pnl_per_day_2026,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min
0,1,core_front_expanded_00168,428,420,-8,547.859866,599.350614,51.490748,5.479290e+06,5.765970e+06,286680.526729,3.881266,4.278241,0.396974,-30723.516018,-29677.448469,1046.067549,77.113098,66.164231,-10.948867,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0
1,2,core_front_expanded_00182,428,420,-8,547.859866,599.350614,51.490748,5.479290e+06,5.765970e+06,286680.526729,3.881266,4.278241,0.396974,-30723.516018,-29677.448469,1046.067549,77.113098,66.164231,-10.948867,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0
2,3,core_front_expanded_00198,428,420,-8,547.859866,599.350614,51.490748,5.479290e+06,5.765970e+06,286680.526729,3.881266,4.278241,0.396974,-30723.516018,-29677.448469,1046.067549,77.113098,66.164231,-10.948867,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0
3,4,core_front_expanded_00167,432,424,-8,547.404931,598.401333,50.996402,5.519880e+06,5.806561e+06,286680.526729,3.902610,4.301318,0.398708,-30723.516018,-29677.448469,1046.067549,77.113098,66.164231,-10.948867,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5
4,5,core_front_expanded_00181,432,424,-8,547.404931,598.401333,50.996402,5.519880e+06,5.806561e+06,286680.526729,3.902610,4.301318,0.398708,-30723.516018,-29677.448469,1046.067549,77.113098,66.164231,-10.948867,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5
5,6,core_front_expanded_00197,432,424,-8,547.404931,598.401333,50.996402,5.519880e+06,5.806561e+06,286680.526729,3.902610,4.301318,0.398708,-30723.516018,-29677.448469,1046.067549,77.113098,66.164231,-10.948867,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5
6,7,core_front_expanded_00248,423,413,-10,545.335363,604.457345,59.121982,5.434757e+06,5.738113e+06,303355.930238,3.872530,4.383369,0.510839,-30723.516018,-29677.448469,1046.067549,77.113098,50.682098,-26.431000,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0
7,8,core_front_expanded_00262,423,413,-10,545.335363,604.457345,59.121982,5.434757e+06,5.738113e+06,303355.930238,3.872530,4.383369,0.510839,-30723.516018,-29677.448469,1046.067549,77.113098,50.682098,-26.431000,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0
8,9,core_front_expanded_00278,423,413,-10,545.335363,604.457345,59.121982,5.434757e+06,5.738113e+06,303355.930238,3.872530,4.383369,0.510839,-30723.516018,-29677.448469,1046.067549,77.113098,50.682098,-26.431000,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0
9,10,core_front_expanded_00183,424,416,-8,547.507072,599.486139,51.979067,5.425318e+06,5.711998e+06,286680.526729,3.852885,4.247555,0.394670,-30723.516018,-29677.448469,1046.067549,60.157120,48.904118,-11.253002,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5
10,11,core_front_expanded_00199,424,416,-8,547.507072,599.486139,51.979067,5.425318e+06,5.711998e+06,286680.526729,3.852885,4.247555,0.394670,-30723.516018,-29677.448469,1046.067549,60.157120,48.904118,-11.253002,0.70,0.65,64.0,14.5,0.70,0.7,66.0,8.5
11,12,core_front_expanded_00247,427,417,-10,544.898750,603.443144,58.544394,5.475347e+06,5.778703e+06,303355.930238,3.893984,4.407302,0.513318,-30723.516018,-29677.448469,1046.067549,77.113098,50.682098,-26.431000,0.75,0.65,68.0,14.5,0.70,0.7,68.0,8.5
12,13,core_front_expanded_00261,427,417,-10,544.898750,603.443144,58.544394,5.475347e+06,5.778703e+06,303355.930238,3.893984,4.407302,0.513318,-30723.516018,-29677.448469,1046.067549,77.113098,50.682098,-26.431000,0.75,0.65,66.0,14.5,0.70,0.7,68.0,8.5
13,14,core_front_expanded_00277,427,417,-10,544.898750,603.443144,58.544394,5.475347e+06,5.778703e+06,303355.930238,3.893984,4.407302,0.513318,-30723.516018,-29677.448469,1046.067549,77.113098,50.682098,-26.431000,0.75,0.65,64.0,14.5,0.70,0.7,68.0,8.5
14,15,core_front_expanded_00184,424,416,-8,547.499550,599.478472,51.978922,5.429453e+06,5.716134e+06,286680.526729,3.855060,4.249906,0.394846,-30723.516018,-29677.448469,1046.067549,60.157120,48.904118,-11.253002,0.70,0.65,66.0,14.5,0.70,0.7,66.0,10.0
15,16,core_front_expanded_00200,424,416,-8,547.499550,599.478472,51.978922,5.429453e+06,5.716134e+06,286680.526729,3.855060,4.249906,0.394846,-30723.516018,-29677.448469,1046.067549,60.157120,48.904118,-11.253002,0.70,0.65,64.0,14.5,0.70,0.7,66.0,10.0
16,17,core_front_expanded_00014,438,432,-6,545.080270,599.249240,54.168970,5.567699e+06,5.891625e+06,323925.975247,3.891386,4.319404,0.428019,-30723.516018,-29677.448469,1046.067549,85.752231,74.949349,-10.802882,0.65,0.65,68.0,14.5,0.65,0.7,68.0,10.0
17,18,core_front_expanded_00042,438,432,-6,545.080270,599.249240,54.168970,5.567699e+06,5.891625e+06,323925.975247,3.891386,4.319404,0.428019,-30723.516018,-29677.448469,1046.067549,85.752231,74.949349,-10.802882,0.65,0.65,66.0,14.5,0.65,0.7,68.0,10.0
18,19,core_front_expanded_00074,438,432,-6,545.080270,599.249240,54.168970,5.567699e+06,5.891625e+06,323925.975247,3.891386,4.319404,0.428019,-30723.516018,-29677.448469,1046.067549,85.752231,74.949349,-10.802882,0.65,0.65,64.0,14.5,0.65,0.7,68.0,10.0
19,20,core_front_expanded_00263,419,409,-10,544.954259,604.645133,59.690874,5.380785e+06,5.684141e+06,303355.930238,3.844003,4.351545,0.507542,-30723.516018,-29677.448469,1046.067549,60.157120,32.742769,-27.414352,0.75,0.65,66.0,14.5,0.70,0.7,66.0,8.5

Top 20 — diagnostic ex-9D reselected by bucket:

,diagnostic_label,candidate_id,tenor_bucket,tenor_bucket_order,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,avg_forecast_vol_pct,min_forecast_vol_pct,max_forecast_vol_pct,avg_model_vrp_log,avg_model_vrp_z_3m,avg_model_vrp_z_1y,review_rank,robustness_screen_pass,robustness_score_after_boundary_penalty,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Back_RSI14_max,Back_forecast_vol_pct_min,Front_forecast_vol_pct_min_at_grid_max,Front_model_vrp_log_at_grid_max
67,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00168,Front,1,114,114,2021-11-26,2026-04-06,12,15,13.921053,0.842105,1.182635e+06,10373.994454,17482.133127,-108475.796818,38031.055016,2.925833,-184899.069310,-155233.786408,-115031.525880,-107763.939183,5,1,0,80730.017868,708.158051,1303.733205,-7782.261885,2838.000230,2.693449,-15408.255776,-11442.031294,-8873.903973,-9007.476734,15,179053.829323,779.593856,-53165.507841,16,85069.510082,349.393890,-34533.046342,17.736131,14.560532,42.687401,0.977923,1.486919,1.513787,1,True,0.846453,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
68,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00168,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,16.138256,10.107217,37.957610,0.958411,1.638650,1.765631,1,True,0.846453,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
66,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00168,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,15.591142,8.962500,35.104648,0.954808,1.664904,1.892251,1,True,0.846453,0.70,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
73,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00182,Front,1,114,114,2021-11-26,2026-04-06,12,15,13.921053,0.842105,1.182635e+06,10373.994454,17482.133127,-108475.796818,38031.055016,2.925833,-184899.069310,-155233.786408,-115031.525880,-107763.939183,5,1,0,80730.017868,708.158051,1303.733205,-7782.261885,2838.000230,2.693449,-15408.255776,-11442.031294,-8873.903973,-9007.476734,15,179053.829323,779.593856,-53165.507841,16,85069.510082,349.393890,-34533.046342,17.736131,14.560532,42.687401,0.977923,1.486919,1.513787,2,True,0.846453,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
74,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00182,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,16.138256,10.107217,37.957610,0.958411,1.638650,1.765631,2,True,0.846453,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
72,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00182,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,15.591142,8.962500,35.104648,0.954808,1.664904,1.892251,2,True,0.846453,0.70,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
85,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00198,Front,1,114,114,2021-11-26,2026-04-06,12,15,13.921053,0.842105,1.182635e+06,10373.994454,17482.133127,-108475.796818,38031.055016,2.925833,-184899.069310,-155233.786408,-115031.525880,-107763.939183,5,1,0,80730.017868,708.158051,1303.733205,-7782.261885,2838.000230,2.693449,-15408.255776,-11442.031294,-8873.903973,-9007.476734,15,179053.829323,779.593856,-53165.507841,16,85069.510082,349.393890,-34533.046342,17.736131,14.560532,42.687401,0.977923,1.486919,1.513787,3,True,0.846453,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
86,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00198,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,16.138256,10.107217,37.957610,0.958411,1.638650,1.765631,3,True,0.846453,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
84,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00198,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,15.591142,8.962500,35.104648,0.954808,1.664904,1.892251,3,True,0.846453,0.70,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
64,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00167,Front,1,114,114,2021-11-26,2026-04-06,12,15,13.921053,0.842105,1.182635e+06,10373.994454,17482.133127,-108475.796818,38031.055016,2.925833,-184899.069310,-155233.786408,-115031.525880,-107763.939183,5,1,0,80730.017868,708.158051,1303.733205,-7782.261885,2838.000230,2.693449,-15408.255776,-11442.031294,-8873.903973,-9007.476734,15,179053.829323,779.593856,-53165.507841,16,85069.510082,349.393890,-34533.046342,17.736131,14.560532,42.687401,0.977923,1.486919,1.513787,4,True,0.839922,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
65,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00167,Middle,2,153,153,2021-11-24,2026-04-29,18,24,21.294118,0.849673,1.865832e+06,12194.980045,18720.325571,-108475.796818,42988.137121,3.815843,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,83262.074671,544.196566,925.336320,-6026.433157,1791.172380,3.450601,-20774.019539,-10696.956646,-19097.652002,-16788.785812,26,405417.381515,723.027339,6005.032657,29,-123708.761175,-275.810184,-45195.769858,15.962170,8.930589,37.957610,0.961129,1.636003,1.772448,4,True,0.839922,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
63,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00167,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,15.591142,8.962500,35.104648,0.954808,1.664904,1.892251,4,True,0.839922,0.70,0.65,68.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
70,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00181,Front,1,114,114,2021-11-26,2026-04-06,12,15,13.921053,0.842105,1.182635e+06,10373.994454,17482.133127,-108475.796818,38031.055016,2.925833,-184899.069310,-155233.786408,-115031.525880,-107763.939183,5,1,0,80730.017868,708.158051,1303.733205,-7782.261885,2838.000230,2.693449,-15408.255776,-11442.031294,-8873.903973,-9007.476734,15,179053.829323,779.593856,-53165.507841,16,85069.510082,349.393890,-34533.046342,17.736131,14.560532,42.687401,0.977923,1.486919,1.513787,5,True,0.839922,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
71,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00181,Middle,2,153,153,2021-11-24,2026-04-29,18,24,21.294118,0.849673,1.865832e+06,12194.980045,18720.325571,-108475.796818,42988.137121,3.815843,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,83262.074671,544.196566,925.336320,-6026.433157,1791.172380,3.450601,-20774.019539,-10696.956646,-19097.652002,-16788.785812,26,405417.381515,723.027339,6005.032657,29,-123708.761175,-275.810184,-45195.769858,15.962170,8.930589,37.957610,0.961129,1.636003,1.772448,5,True,0.839922,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
69,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00181,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,15.591142,8.962500,35.104648,0.954808,1.664904,1.892251,5,True,0.839922,0.70,0.65,66.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
82,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00197,Front,1,114,114,2021-11-26,2026-04-06,12,15,13.921053,0.842105,1.182635e+06,10373.994454,17482.133127,-108475.796818,38031.055016,2.925833,-184899.069310,-155233.786408,-115031.525880,-107763.939183,5,1,0,80730.017868,708.158051,1303.733205,-7782.261885,2838.000230,2.693449,-15408.255776,-11442.031294,-8873.903973,-9007.476734,15,179053.829323,779.593856,-53165.507841,16,85069.510082,349.393890,-34533.046342,17.736131,14.560532,42.687401,0.977923,1.486919,1.513787,6,True,0.839922,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
83,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00197,Middle,2,153,153,2021-11-24,2026-04-29,18,24,21.294118,0.849673,1.865832e+06,12194.980045,18720.325571,-108475.796818,42988.137121,3.815843,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,83262.074671,544.196566,925.336320,-6026.433157,1791.172380,3.450601,-20774.019539,-10696.956646,-19097.652002,-16788.785812,26,405417.381515,723.027339,6005.032657,29,-123708.761175,-275.810184,-45195.769858,15.962170,8.930589,37.957610,0.961129,1.636003,1.772448,6,True,0.839922,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
81,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00197,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,15.591142,8.962500,35.104648,0.954808,1.664904,1.892251,6,True,0.839922,0.70,0.65,64.0,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,True,False
115,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00248,Front,1,107,107,2021-11-26,2026-04-06,12,15,14.018692,0.850467,1.154778e+06,10792.320034,17641.251396,-108475.796818,38031.055016,3.095006,-184899.069310,-155233.786408,-115031.525880,-107763.939183,4,1,0,78643.643472,734.987322,1336.098028,-7782.261885,2535.403668,2.853424,-15408.255776,-11442.031294,-8873.903973,-9007.476734,10,179531.518925,1196.876793,6005.032657,15,70713.190948,292.929487,-34533.046342,17.624317,14.560532,41.974813,0.994598,1.482820,1.539446,7,True,0.835891,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
116,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00248,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,16.138256,10.107217,37.957610,0.958411,1.638650,1.765631,7,True,0.835891,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
114,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00248,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,15.591142,8.962500,35.104648,0.954808,1.664904,1.892251,7,True,0.835891,0.75,0.65,68.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
121,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00262,Front,1,107,107,2021-11-26,2026-04-06,12,15,14.018692,0.850467,1.154778e+06,10792.320034,17641.251396,-108475.796818,38031.055016,3.095006,-184899.069310,-155233.786408,-115031.525880,-107763.939183,4,1,0,78643.643472,734.987322,1336.098028,-7782.261885,2535.403668,2.853424,-15408.255776,-11442.031294,-8873.903973,-9007.476734,10,179531.518925,1196.876793,6005.032657,15,70713.190948,292.929487,-34533.046342,17.624317,14.560532,41.974813,0.994598,1.482820,1.539446,8,True,0.835891,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
122,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00262,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,16.138256,10.107217,37.957610,0.958411,1.638650,1.765631,8,True,0.835891,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
120,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00262,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,15.591142,8.962500,35.104648,0.954808,1.664904,1.892251,8,True,0.835891,0.75,0.65,66.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
133,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00278,Front,1,107,107,2021-11-26,2026-04-06,12,15,14.018692,0.850467,1.154778e+06,10792.320034,17641.251396,-108475.796818,38031.055016,3.095006,-184899.069310,-155233.786408,-115031.525880,-107763.939183,4,1,0,78643.643472,734.987322,1336.098028,-7782.261885,2535.403668,2.853424,-15408.255776,-11442.031294,-8873.903973,-9007.476734,10,179531.518925,1196.876793,6005.032657,15,70713.190948,292.929487,-34533.046342,17.624317,14.560532,41.974813,0.994598,1.482820,1.539446,9,True,0.835891,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
134,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00278,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,364827.248536,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,16.138256,10.107217,37.957610,0.958411,1.638650,1.765631,9,True,0.835891,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
132,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00278,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-239025.497756,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,573881.531973,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,15.591142,8.962500,35.104648,0.954808,1.664904,1.892251,9,True,0.835891,0.75,0.65,64.0,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,True
76,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00183,Front,1,114,114,2021-11-26,2026-04-06,12,15,13.921053,0.842105,1.182635e+06,10373.994454,17482.133127,-108475.796818,38031.055016,2.925833,-184899.069310,-155233.786408,-115031.525880,-107763.939183,5,1,0,80730.017868,708.158051,1303.733205,-7782.261885,2838.000230,2.693449,-15408.255776,-11442.031294,-8873.903973,-9007.476734,15,179053.829323,779.593856,-53165.507841,16,85069.510082,349.393890,-34533.046342,17.736131,14.560532,42.687401,0.977923,1.486919,1.513787,10,True,0.820937,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,False
77,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00183,Middle,2,145,145,2021-11-24,2026-04-07,18,24,21.268966,0.841379,1.771270e+06,12215.654113,19202.248344,-108475.796818,42988.137121,3.673134,-388526.041944,-197285.561652,-358351.426266,-302908.024370,1,1,0,78926.143107,544.318228,964.213690,-6026.433157,1791.172380,3.322985,-20774.019539,-10696.956646,-19097.652002,-16788.785812,21,353793.263286,782.083043,6005.032657,27,-152584.949956,-347.168590,-45195.769858,16.265817,9.857271,37.957610,0.959724,1.645989,1.763567,10,True,0.820937,0.70,0.65,66.0,14.5,0.70,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,False

Top 20 — diagnostic ex-9D reselected by tenor:

,diagnostic_label,candidate_id,tenor,tenor_bucket,tenor_bucket_order,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,avg_forecast_vol_pct,min_forecast_vol_pct,max_forecast_vol_pct,avg_model_vrp_log,avg_model_vrp_z_3m,avg_model_vrp_z_1y,review_rank,robustness_screen_pass,robustness_score_after_boundary_penalty,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Back_RSI14_max,Back_forecast_vol_pct_min,Front_forecast_vol_pct_min_at_grid_max,Front_model_vrp_log_at_grid_max
176,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00168,12,Front,1,41,41,2021-11-26,2026-03-23,12,12,12.0,0.731707,1.132596e+05,2762.429291,15316.821152,-93387.142625,34056.002766,1.280376,-184899.069310,-156487.963652,-122614.706599,-59638.895291,4,0,0,9438.300076,230.202441,1276.401763,-7782.261885,2838.000230,1.280376,-15408.255776,-13040.663638,-10217.892217,-4969.907941,4,-14580.846635,-303.767638,-53165.507841,3,-4859.906056,-134.997390,-34533.046342,17.196380,14.602465,42.687401,0.948543,1.423900,1.222544,1,True,0.846453,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
177,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00168,15,Front,1,73,73,2021-12-06,2026-04-06,15,15,15.0,0.904110,1.069376e+06,14648.983108,20206.136079,-108475.796818,38031.055016,6.089021,-111137.668230,-86408.441669,18156.232241,191946.278936,1,1,0,71291.717792,976.598874,1347.075739,-7231.719788,2535.403668,6.089021,-7409.177882,-5760.562778,1210.415483,12796.418596,11,193634.675957,1173.543491,6005.032657,13,89929.416138,461.176493,-25919.354017,18.039279,14.560532,41.974813,0.994425,1.522314,1.677363,1,True,0.846453,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
178,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00168,18,Middle,2,54,54,2021-12-03,2026-03-25,18,18,18.0,0.740741,2.046359e+05,3789.554584,12641.588528,-108475.796818,25912.875855,1.460678,-315930.254948,-202522.266450,-315930.254948,-239409.369941,1,1,0,11368.663752,210.530810,702.310474,-6026.433157,1439.604214,1.460678,-17551.680830,-11251.237025,-17551.680830,-13300.520552,6,60950.563003,564.357065,6005.032657,18,-225068.948261,-694.657248,-45195.769858,15.162066,10.968784,20.662663,0.958589,1.661407,1.564000,1,True,0.846453,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
179,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00168,21,Middle,2,25,25,2021-12-01,2026-04-29,21,21,21.0,0.960000,3.987075e+05,15948.301588,18720.325571,-33182.394118,28179.541598,13.015635,-33182.394118,28166.045377,114624.158683,307501.033557,0,0,0,18986.073319,759.442933,891.444075,-1580.114006,1341.882933,13.015635,-1580.114006,1341.240256,5458.293271,14642.906360,7,127030.264488,864.151459,10440.842371,6,47374.991856,375.991999,-33182.394118,15.294476,10.277772,19.229675,0.991714,1.775799,1.989921,1,True,0.846453,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
180,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00168,24,Middle,2,70,70,2021-11-24,2026-03-30,24,24,24.0,0.885714,1.221898e+06,17455.690380,24257.585415,-48027.465092,42988.137121,7.596626,-48027.465092,-17563.867069,84062.019309,232583.964589,0,0,0,50912.430276,727.320433,1010.732726,-2001.144379,1791.172380,7.596626,-2001.144379,-731.827795,3502.584138,9690.998525,9,176846.421045,818.733431,10805.456045,5,53985.195231,449.876627,-39413.392878,17.192668,10.107217,37.957610,0.946381,1.572113,1.841072,1,True,0.846453,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00263,21,Middle,2,22,22,2021-12-01,2026-04-07,21,21,21.0,0.954545,3.593905e+05,16335.932207,19840.275103,-33182.394118,28179.541598,11.830759,-33182.394118,34852.977257,122608.919369,314105.396523,0,0,0,17113.833741,777.901534,944.775005,-1580.114006,1341.882933,11.830759,-1580.114006,1659.665584,5838.519970,14957.399834,6,116589.422117,925.312874,17127.774251,4,18498.803074,220.223846,-33182.394118,15.922866,12.133041,19.229675,1.002903,1.897822,2.085096,20,True,0.808937,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,True
332,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00263,24,Middle,2,68,68,2021-11-24,2026-03-30,24,24,24.0,0.882353,1.197031e+06,17603.398194,24518.387746,-48027.465092,42988.137121,7.462376,-48027.465092,-17563.867069,84062.019309,251744.287040,0,0,0,49876.294883,733.474925,1021.599489,-2001.144379,1791.172380,7.462376,-2001.144379,-731.827795,3502.584138,10489.345293,8,166040.965000,864.796693,11584.867060,5,53985.195231,449.876627,-39413.392878,17.366431,10.107217,37.957610,0.946631,1.562921,1.819786,20,True,0.808937,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,True
333,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00263,27,Back,3,64,64,2021-11-24,2026-04-29,27,27,27.0,0.890625,7.946444e+05,12416.319396,14893.175204,-92579.572354,32071.631184,3.772550,-197819.722192,-184263.764146,-42456.069649,115794.844473,1,0,0,29431.275605,459.863681,551.599082,-3428.873050,1187.838192,3.772550,-7326.656377,-6824.583857,-1572.447024,4288.697943,26,362079.851866,515.783265,1573.629536,6,-31782.783676,-196.190023,-42147.706567,14.039033,8.962500,19.627067,0.958344,1.569641,1.807425,20,True,0.808937,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,True
334,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00263,30,Back,3,15,15,2022-03-09,2026-03-12,30,30,30.0,0.866667,2.641151e+05,17607.671904,20038.662122,-24704.938663,45095.398744,7.929464,-38114.790745,4469.678163,113186.089954,264115.078564,0,0,0,8803.835952,586.922397,667.955404,-823.497955,1503.179958,7.929464,-1270.493025,148.989272,3772.869665,8803.835952,3,87340.106049,970.445623,20038.662122,4,-13646.575851,-113.721465,-24704.938663,17.110889,12.871940,35.104648,0.960610,1.989407,2.181125,20,True,0.808937,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,True
335,diagnostic_one_trade_per_bucket_excluding_fron...,core_front_expanded_00263,33,Back,3,78,78,2021-12-06,2026-03-30,33,33,33.0,0.935897,1.699334e+06,21786.329730,27322.832885,-48751.416767,35371.772564,11.794523,-75662.284598,-49881.038125,33880.957771,174718.883975,0,0,0,51494.961181,660.191810,827.964633,-1477.315660,1071.871896,11.794523,-2292.796503,-1511.546610,1026.695690,5294.511636,10,124461.574059,377.156285,-40557.495661,19,294900.282775,470.335379,-48751.416767,16.572409,10.902616,20.811922,0.950792,1.680665,1.906300,20,True,0.808937,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,True

Top 20 — Front all-qualified by forecast-vol state and tenor:

,diagnostic_label,candidate_id,tenor,front_forecast_vol_bin,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,avg_forecast_vol_pct,min_forecast_vol_pct,max_forecast_vol_pct,avg_model_vrp_log,avg_model_vrp_z_3m,avg_model_vrp_z_1y,review_rank,robustness_screen_pass,robustness_score_after_boundary_penalty,Front_model_vrp_log,Front_model_vrp_z,Front_RSI14_max,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Back_RSI14_max,Back_forecast_vol_pct_min,Front_forecast_vol_pct_min_at_grid_max,Front_model_vrp_log_at_grid_max
264,front_all_qualified_by_tenor_and_forecast_vol_...,core_front_expanded_00168,9,14.5-16.0,27,27,2021-09-20,2026-03-25,9,9,9.0,0.592593,-48888.317355,-1810.678421,11929.277477,-93387.142625,19447.414501,0.807317,-114818.822346,-97275.376201,-96978.617527,-37285.054805,1,0,0,-5432.035262,-201.186491,1325.475275,-10376.349181,2160.823833,0.807317,-12757.646927,-10808.375133,-10775.401947,-4142.783867,3,37442.662838,1386.765290,12324.018696,10,-44064.330492,-489.603672,-34533.046342,15.415351,14.849697,15.922100,1.056021,1.444606,1.449487,1,True,0.846453,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
265,front_all_qualified_by_tenor_and_forecast_vol_...,core_front_expanded_00168,9,16.0-18.0,38,38,2021-12-03,2026-03-27,9,9,9.0,0.710526,145677.702150,3833.623741,13744.511376,-91511.926686,20272.650373,1.611993,-139236.750214,-86725.249685,-139236.750214,14560.733750,1,0,0,16186.411350,425.958193,1527.167931,-10167.991854,2252.516708,1.611993,-15470.750024,-9636.138854,-15470.750024,1617.859306,7,1703.884091,27.045779,-40441.053294,3,20420.243016,756.305297,-7630.854164,16.791175,16.010776,17.679317,0.991156,1.442374,1.512091,1,True,0.846453,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
266,front_all_qualified_by_tenor_and_forecast_vol_...,core_front_expanded_00168,9,18.0-20.0,26,26,2021-11-26,2026-03-30,9,9,9.0,0.692308,147582.539325,5676.251513,16309.807045,-51422.095318,20796.749647,1.874678,-156274.990752,-131403.979248,-90995.981143,45315.327066,1,0,0,16398.059925,630.694613,1812.200783,-5713.566146,2310.749961,1.874678,-17363.887861,-14600.442139,-10110.664571,5035.036341,0,0.000000,NaN,NaN,1,17607.965043,1956.440560,17607.965043,19.103491,18.156373,19.982162,0.983056,1.249816,1.257193,1,True,0.846453,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
267,front_all_qualified_by_tenor_and_forecast_vol_...,core_front_expanded_00168,9,>20.0,11,11,2022-03-07,2025-04-08,9,9,9.0,1.000000,217909.736059,19809.976005,19811.415388,1145.711413,34077.430827,inf,0.000000,68402.991829,183832.305233,217909.736059,0,0,0,24212.192895,2201.108445,2201.268376,127.301268,3786.381203,inf,0.000000,7600.332425,20425.811693,24212.192895,2,68133.433592,3785.190755,34056.002766,0,0.000000,NaN,NaN,25.431652,20.093698,44.221370,0.953874,1.554130,1.574822,1,True,0.846453,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
268,front_all_qualified_by_tenor_and_forecast_vol_...,core_front_expanded_00168,12,14.5-16.0,37,37,2022-01-31,2026-03-25,12,12,12.0,0.729730,154992.434469,4188.984715,13970.305530,-93387.142625,22246.736532,1.615540,-105596.559441,-111434.165049,-69242.240846,62727.148829,1,0,0,12916.036206,349.082060,1164.192127,-7782.261885,1853.894711,1.615540,-8799.713287,-9286.180421,-5770.186737,5227.262402,7,99776.948534,1187.820816,12324.018696,11,6856.695786,51.944665,-34533.046342,15.373201,14.602465,15.997554,1.050434,1.440896,1.533876,1,True,0.846453,0.70,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,front_all_qualified_by_tenor_and_forecast_vol_...,core_front_expanded_00263,12,>20.0,9,9,2022-03-07,2025-04-08,12,12,12.0,1.000000,185343.858746,20593.762083,19811.415388,9860.085556,34077.430827,inf,0.000000,86466.062828,185343.858746,185343.858746,0,0,0,15445.321562,1716.146840,1650.951282,821.673796,2839.785902,inf,0.000000,7205.505236,15445.321562,15445.321562,1,34077.430827,2839.785902,34077.430827,0,0.000000,NaN,NaN,23.333687,20.077205,42.674335,0.973598,1.630899,1.616625,20,True,0.808937,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,True
500,front_all_qualified_by_tenor_and_forecast_vol_...,core_front_expanded_00263,15,14.5-16.0,18,18,2022-07-25,2026-04-06,15,15,15.0,0.777778,78148.961130,4341.608952,15901.195360,-108475.796818,23364.485981,1.531861,-108475.796818,-66233.350416,16169.177237,78148.961130,1,1,0,5209.930742,289.440597,1060.079691,-7231.719788,1557.632399,1.531861,-7231.719788,-4415.556694,1077.945149,5209.930742,5,82402.527652,1098.700369,15613.049794,6,27081.500641,300.905563,-15848.617660,15.295436,14.560532,15.942005,0.991619,1.536740,1.660089,20,True,0.808937,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,True
501,front_all_qualified_by_tenor_and_forecast_vol_...,core_front_expanded_00263,15,16.0-18.0,42,42,2021-12-03,2026-03-27,15,15,15.0,0.857143,563967.538611,13427.798538,19396.656655,-30944.391936,26240.867946,4.723543,-61700.707099,-1737.119259,76896.978618,230782.395499,0,0,0,37597.835907,895.186569,1293.110444,-2062.959462,1749.391196,4.723543,-4113.380473,-115.807951,5126.465241,15385.493033,4,59097.936258,984.965604,6005.032657,8,60027.929364,500.232745,-25919.354017,16.852573,16.001975,17.875847,1.008764,1.528847,1.614830,20,True,0.808937,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,True
502,front_all_qualified_by_tenor_and_forecast_vol_...,core_front_expanded_00263,15,18.0-20.0,30,30,2021-11-26,2026-03-30,15,15,15.0,0.900000,460815.440940,15360.514698,21476.872495,-33620.942289,24859.690803,11.130727,-45486.907699,-4387.074893,51342.941061,236233.206012,0,0,0,30721.029396,1024.034313,1431.791500,-2241.396153,1657.312720,11.130727,-3032.460513,-292.471660,3422.862737,15748.880401,0,0.000000,NaN,NaN,1,22037.542641,1469.169509,22037.542641,19.060079,18.168579,19.964467,0.938147,1.312977,1.320945,20,True,0.808937,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,True
503,front_all_qualified_by_tenor_and_forecast_vol_...,core_front_expanded_00263,15,>20.0,11,11,2022-03-07,2025-04-08,15,15,15.0,1.000000,252565.623618,22960.511238,24256.073177,9204.093999,38031.055016,inf,0.000000,97800.783964,214534.568603,252565.623618,0,0,0,16837.708241,1530.700749,1617.071545,613.606267,2535.403668,inf,0.000000,6520.052264,14302.304574,16837.708241,1,38031.055016,2535.403668,38031.055016,0,0.000000,NaN,NaN,22.862523,20.016216,41.974813,0.932277,1.655562,1.685473,20,True,0.808937,0.75,0.65,66.0,14.5,0.7,0.7,66.0,8.5,0.7,0.7,70.0,8.5,True,True

Front RSI binding diagnostics:

,Front_model_vrp_log,Front_model_vrp_z,Front_forecast_vol_pct_min,Middle_model_vrp_log,Middle_model_vrp_z,Middle_RSI14_max,Middle_forecast_vol_pct_min,Back_model_vrp_log,Back_model_vrp_z,Back_RSI14_max,Back_forecast_vol_pct_min,candidate_count,candidate_ids,review_ranks,front_rsi_values,unique_front_rsi_values,unique_actual_primary_trade_sets,unique_actual_front_trade_sets,min_avg_pnl_per_day,max_avg_pnl_per_day,min_2026_avg_pnl_per_day,max_2026_avg_pnl_per_day,min_trades,max_trades,front_rsi_nonbinding_trade_set_test,front_rsi_nonbinding_metric_test
0,0.70,0.65,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,3,"core_front_expanded_00168, core_front_expanded...","1, 2, 3","64.0, 66.0, 68.0",3,1,1,547.859866,547.859866,77.113098,77.113098,428,428,True,True
1,0.70,0.65,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,3,"core_front_expanded_00167, core_front_expanded...","4, 5, 6","64.0, 66.0, 68.0",3,1,1,547.404931,547.404931,77.113098,77.113098,432,432,True,True
2,0.75,0.65,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,3,"core_front_expanded_00248, core_front_expanded...","7, 8, 9","64.0, 66.0, 68.0",3,1,1,545.335363,545.335363,77.113098,77.113098,423,423,True,True
3,0.65,0.65,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,3,"core_front_expanded_00016, core_front_expanded...","22, 23, 24","64.0, 66.0, 68.0",3,1,1,545.126315,545.126315,77.113098,77.113098,431,431,True,True
4,0.65,0.65,14.5,0.65,0.7,68.0,10.0,0.7,0.7,70.0,8.5,3,"core_front_expanded_00014, core_front_expanded...","17, 18, 19","64.0, 66.0, 68.0",3,1,1,545.080270,545.080270,85.752231,85.752231,438,438,True,True
5,0.75,0.65,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,3,"core_front_expanded_00247, core_front_expanded...","12, 13, 14","64.0, 66.0, 68.0",3,1,1,544.898750,544.898750,77.113098,77.113098,427,427,True,True
6,0.65,0.65,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,3,"core_front_expanded_00015, core_front_expanded...","30, 31, 32","64.0, 66.0, 68.0",3,1,1,544.699653,544.699653,77.113098,77.113098,435,435,True,True
7,0.65,0.65,14.5,0.65,0.7,68.0,8.5,0.7,0.7,70.0,8.5,3,"core_front_expanded_00013, core_front_expanded...","27, 28, 29","64.0, 66.0, 68.0",3,1,1,544.660782,544.660782,85.752231,85.752231,442,442,True,True
8,0.70,0.70,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,3,"core_front_expanded_00208, core_front_expanded...","33, 34, 35","64.0, 66.0, 68.0",3,1,1,536.425019,536.425019,77.113098,77.113098,422,422,True,True
9,0.70,0.70,14.5,0.70,0.7,68.0,8.5,0.7,0.7,70.0,8.5,3,"core_front_expanded_00207, core_front_expanded...","36, 37, 38","64.0, 66.0, 68.0",3,1,1,536.071045,536.071045,77.113098,77.113098,426,426,True,True
10,0.75,0.70,14.5,0.70,0.7,68.0,10.0,0.7,0.7,70.0,8.5,3,"core_front_expanded_00288, core_front_expanded...","47, 48, 49","64.0, 66.0, 68.0",3,1,1,533.727083,533.727083,77.113098,77.113098,417,417,True,True
11,0.70,0.65,14.5,0.70,0.7,66.0,8.5,0.7,0.7,70.0,8.5,2,"core_front_expanded_00183, core_front_expanded...","10, 11","64.0, 66.0",2,1,1,547.507072,547.507072,60.157120,60.157120,424,424,True,True
12,0.70,0.65,14.5,0.70,0.7,66.0,10.0,0.7,0.7,70.0,8.5,2,"core_front_expanded_00184, core_front_expanded...","15, 16","64.0, 66.0",2,1,1,547.499550,547.499550,60.157120,60.157120,424,424,True,True
13,0.75,0.65,14.5,0.70,0.7,66.0,8.5,0.7,0.7,70.0,8.5,2,"core_front_expanded_00263, core_front_expanded...","20, 21","64.0, 66.0",2,1,1,544.954259,544.954259,60.157120,60.157120,419,419,True,True
14,0.75,0.65,14.5,0.70,0.7,66.0,10.0,0.7,0.7,70.0,8.5,2,"core_front_expanded_00264, core_front_expanded...","25, 26","64.0, 66.0",2,1,1,544.946647,544.946647,60.157120,60.157120,419,419,True,True
15,0.65,0.65,14.5,0.70,0.7,66.0,8.5,0.7,0.7,70.0,8.5,2,"core_front_expanded_00047, core_front_expanded...","43, 44","64.0, 66.0",2,1,1,544.750393,544.750393,60.157120,60.157120,427,427,True,True
16,0.65,0.65,14.5,0.70,0.7,66.0,10.0,0.7,0.7,70.0,8.5,2,"core_front_expanded_00048, core_front_expanded...","45, 46","64.0, 66.0",2,1,1,544.742924,544.742924,60.157120,60.157120,427,427,True,True
17,0.65,0.65,14.5,0.65,0.7,66.0,8.5,0.7,0.7,70.0,8.5,2,"core_front_expanded_00043, core_front_expanded...","39, 40","64.0, 66.0",2,1,1,544.709987,544.709987,69.265215,69.265215,434,434,True,True
18,0.65,0.65,14.5,0.65,0.7,66.0,10.0,0.7,0.7,70.0,8.5,2,"core_front_expanded_00044, core_front_expanded...","41, 42","64.0, 66.0",2,1,1,544.702638,544.702638,69.265215,69.265215,434,434,True,True
19,0.65,0.70,14.5,0.65,0.7,68.0,10.0,0.7,0.7,70.0,8.5,1,core_front_expanded_00094,50,68.0,1,1,1,533.871513,533.871513,85.752231,85.752231,432,432,False,False

Saved outputs:
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_actual_front_by_tenor_20260704_221323.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_front_summary_20260704_221323.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_ex9d_comparison_20260704_221323.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_ex9d_reselected_summary_20260704_221323.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_ex9d_reselected_by_bucket_20260704_221323.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_ex9d_reselected_by_tenor_20260704_221323.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_forecast_vol_state_by_tenor_20260704_221323.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_forecast_vol_state_summary_20260704_221323.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_front_rsi_binding_diagnostics_20260704_221323.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_diagnostic_conclusion_20260704_221323.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_ex9d_reselected_trade_panel_20260704_221323.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_validation_20260704_221323.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\08_front_tenor_boundary_manifest_20260704_221323.json

CELL 10 PASSED

In [13]:
# ======================================================================================
# Cell 11 — 9D-specific Front rule candidate design
# ======================================================================================
#
# Objective:
#   Create a small diagnostic candidate grid to compare:
#       1. Core Front excluding 9D entirely.
#       2. Core Front allowing 9D only with a higher 9D-specific forecast-vol floor.
#
# Why:
#   Cell 10 showed:
#       - Top-ranked expanded candidate still had Front forecast-vol floor at grid max 14.5.
#       - 9D remained negative under the shared Front rule.
#       - 12D and 15D were strong.
#       - 9D improved materially as forecast-vol state increased.
#
# This cell only designs and saves candidate rules.
#
# Important:
#   This cell does NOT evaluate trades.
#   This cell does NOT run a sweep.
#   This cell does NOT select final thresholds.
#   This cell does NOT lock production.
#
# Candidate families:
#   A. front_ex_9d:
#        - 9D excluded from Core Front.
#        - 12D and 15D use the selected Front rule.
#
#   B. front_conditional_9d:
#        - 12D and 15D use the selected Front rule.
#        - 9D is allowed only with a higher 9D-specific forecast-vol floor:
#              16.0, 18.0, 20.0
#
# Fixed reference rule used for this diagnostic design:
#   Front 12D/15D:
#       model_vrp_log > 0.70
#       model_vrp_z   > 0.65
#       RSI14         < 68
#       forecast vol  > 14.5
#
#   Middle:
#       model_vrp_log > 0.70
#       model_vrp_z   > 0.70
#       RSI14         < 68
#       forecast vol  > 10.0
#
#   Back:
#       locked unchanged
#
# Not in scope:
#   - No trade evaluation.
#   - No parameter expansion beyond the 9D forecast-vol floor test.
#   - No Secondary.
#   - No sizing changes.
#   - No production lock.
# ======================================================================================

from pathlib import Path
from datetime import datetime
import json

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 260)
pd.set_option("display.width", 420)

# ======================================================================================
# 0. Fallback config
# ======================================================================================

if "PROJECT_ROOT" not in globals():
    PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

if "NEW_BRANCH" not in globals():
    NEW_BRANCH = "vrp_unified_fds_core_signal_threshold_research_v1"

if "OUT_PROCESSED_DIR" not in globals():
    OUT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / NEW_BRANCH
    OUT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

if "OUT_AUDIT_DIR" not in globals():
    OUT_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / NEW_BRANCH
    OUT_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

CELL11_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

if "LOCKED_MODEL_SPEC" not in globals():
    LOCKED_MODEL_SPEC = "unified_fds_no_min_return"

if "ALL_TENORS" not in globals():
    ALL_TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

if "TENOR_BUCKET_MAP" not in globals():
    TENOR_BUCKET_MAP = {
        9: "Front",
        12: "Front",
        15: "Front",
        18: "Middle",
        21: "Middle",
        24: "Middle",
        27: "Back",
        30: "Back",
        33: "Back",
    }

if "BUCKET_ORDER_MAP" not in globals():
    BUCKET_ORDER_MAP = {
        "Front": 1,
        "Middle": 2,
        "Back": 3,
    }

if "LOCKED_BACK_CORE_THRESHOLDS" not in globals():
    LOCKED_BACK_CORE_THRESHOLDS = {
        "model_vrp_log": 0.70,
        "model_vrp_z_3m": 0.70,
        "model_vrp_z_1y": 0.70,
        "RSI14_max": 70.0,
        "forecast_vol_pct_min": 8.5,
    }

CANDIDATE_FAMILY = "core_front_9d_rule_test"

# ======================================================================================
# 1. Helpers
# ======================================================================================

def latest_file(directory: Path, pattern: str, required: bool = True) -> Path | None:
    matches = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if matches:
        return matches[0]
    if required:
        raise FileNotFoundError(f"No file found in {directory} matching {pattern}")
    return None


def tenor_bucket(tenor: int) -> str:
    return TENOR_BUCKET_MAP[int(tenor)]


def threshold_dict(
    model_vrp_log: float,
    model_vrp_z: float,
    rsi_max: float,
    forecast_vol_pct_min: float,
) -> dict:
    return {
        "model_vrp_log": float(model_vrp_log),
        "model_vrp_z": float(model_vrp_z),
        "model_vrp_z_3m": float(model_vrp_z),
        "model_vrp_z_1y": float(model_vrp_z),
        "RSI14_max": float(rsi_max),
        "forecast_vol_pct_min": float(forecast_vol_pct_min),
    }


# ======================================================================================
# 2. Load context inputs
# ======================================================================================

signal_panel_path = latest_file(
    OUT_PROCESSED_DIR,
    "01_unified_fds_signal_base_panel_*.parquet",
    required=True,
)

ranked_summary_path = latest_file(
    OUT_AUDIT_DIR,
    "07_core_candidate_ranked_summary_*.csv",
    required=True,
)

front_tenor_diag_path = latest_file(
    OUT_AUDIT_DIR,
    "08_front_tenor_boundary_actual_front_by_tenor_*.csv",
    required=False,
)

front_ex9d_comparison_path = latest_file(
    OUT_AUDIT_DIR,
    "08_front_tenor_boundary_ex9d_comparison_*.csv",
    required=False,
)

front_forecast_state_path = latest_file(
    OUT_AUDIT_DIR,
    "08_front_tenor_boundary_forecast_vol_state_by_tenor_*.csv",
    required=False,
)

signal = pd.read_parquet(signal_panel_path)
ranked_summary = pd.read_csv(ranked_summary_path)

signal["trade_date"] = pd.to_datetime(signal["trade_date"], errors="coerce").dt.normalize()
signal["tenor"] = pd.to_numeric(signal["tenor"], errors="coerce").astype(int)

# Context review only. Not used to evaluate or select trades.
context_rows = []

context_rows.append({
    "context_item": "signal_panel_path",
    "value": str(signal_panel_path),
})

context_rows.append({
    "context_item": "ranked_summary_path",
    "value": str(ranked_summary_path),
})

context_rows.append({
    "context_item": "front_tenor_diag_path",
    "value": str(front_tenor_diag_path) if front_tenor_diag_path is not None else None,
})

context_rows.append({
    "context_item": "front_ex9d_comparison_path",
    "value": str(front_ex9d_comparison_path) if front_ex9d_comparison_path is not None else None,
})

context_rows.append({
    "context_item": "front_forecast_state_path",
    "value": str(front_forecast_state_path) if front_forecast_state_path is not None else None,
})

context_rows.append({
    "context_item": "signal_rows",
    "value": int(len(signal)),
})

context_rows.append({
    "context_item": "signal_date_min",
    "value": str(signal["trade_date"].min().date()),
})

context_rows.append({
    "context_item": "signal_date_max",
    "value": str(signal["trade_date"].max().date()),
})

context_rows.append({
    "context_item": "signal_tenors",
    "value": str(sorted(signal["tenor"].dropna().unique().tolist())),
})

if not ranked_summary.empty and "review_rank" in ranked_summary.columns:
    top_ranked = ranked_summary.sort_values("review_rank").head(10).copy()

    for _, row in top_ranked.iterrows():
        context_rows.append({
            "context_item": f"top_ranked_candidate_{int(row['review_rank'])}",
            "value": str(row.get("candidate_id")),
        })

context_review = pd.DataFrame(context_rows)

# ======================================================================================
# 3. Fixed reference rules for the 9D-specific candidate design
# ======================================================================================

FRONT_12_15_RULE = threshold_dict(
    model_vrp_log=0.70,
    model_vrp_z=0.65,
    rsi_max=68.0,
    forecast_vol_pct_min=14.5,
)

# For conditional 9D candidates, keep log/z/RSI same as Front rule, but raise FV floor.
NINE_D_BASE_RULE = threshold_dict(
    model_vrp_log=0.70,
    model_vrp_z=0.65,
    rsi_max=68.0,
    forecast_vol_pct_min=14.5,
)

MIDDLE_RULE = threshold_dict(
    model_vrp_log=0.70,
    model_vrp_z=0.70,
    rsi_max=68.0,
    forecast_vol_pct_min=10.0,
)

BACK_RULE = threshold_dict(
    model_vrp_log=LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"],
    model_vrp_z=LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"],
    rsi_max=LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"],
    forecast_vol_pct_min=LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"],
)

NINE_D_CONDITIONAL_FORECAST_VOL_FLOORS = [16.0, 18.0, 20.0]

# ======================================================================================
# 4. Build wide candidate design
# ======================================================================================

wide_rows = []

# Candidate A: exclude 9D.
wide_rows.append({
    "candidate_id": "core_front_9d_rule_0001",
    "candidate_family": CANDIDATE_FAMILY,
    "candidate_subfamily": "front_ex_9d",
    "candidate_description": "Exclude 9D from Core Front; use Front rule for 12D/15D only.",
    "locked_model_spec": LOCKED_MODEL_SPEC,

    "front_9d_include": False,
    "front_9d_rule_type": "excluded",
    "front_9d_model_vrp_log": NINE_D_BASE_RULE["model_vrp_log"],
    "front_9d_model_vrp_z": NINE_D_BASE_RULE["model_vrp_z"],
    "front_9d_RSI14_max": NINE_D_BASE_RULE["RSI14_max"],
    "front_9d_forecast_vol_pct_min": np.nan,

    "front_12_15_include": True,
    "front_12_15_model_vrp_log": FRONT_12_15_RULE["model_vrp_log"],
    "front_12_15_model_vrp_z": FRONT_12_15_RULE["model_vrp_z"],
    "front_12_15_RSI14_max": FRONT_12_15_RULE["RSI14_max"],
    "front_12_15_forecast_vol_pct_min": FRONT_12_15_RULE["forecast_vol_pct_min"],

    "middle_include": True,
    "middle_model_vrp_log": MIDDLE_RULE["model_vrp_log"],
    "middle_model_vrp_z": MIDDLE_RULE["model_vrp_z"],
    "middle_RSI14_max": MIDDLE_RULE["RSI14_max"],
    "middle_forecast_vol_pct_min": MIDDLE_RULE["forecast_vol_pct_min"],

    "back_include": True,
    "back_model_vrp_log": BACK_RULE["model_vrp_log"],
    "back_model_vrp_z": BACK_RULE["model_vrp_z"],
    "back_RSI14_max": BACK_RULE["RSI14_max"],
    "back_forecast_vol_pct_min": BACK_RULE["forecast_vol_pct_min"],
})

# Candidate B family: conditional 9D with higher FV floor.
for i, nine_d_fv_floor in enumerate(NINE_D_CONDITIONAL_FORECAST_VOL_FLOORS, start=2):
    wide_rows.append({
        "candidate_id": f"core_front_9d_rule_{i:04d}",
        "candidate_family": CANDIDATE_FAMILY,
        "candidate_subfamily": "front_conditional_9d",
        "candidate_description": f"Allow 9D only if 9D forecast vol > {nine_d_fv_floor}; use Front rule for 12D/15D.",
        "locked_model_spec": LOCKED_MODEL_SPEC,

        "front_9d_include": True,
        "front_9d_rule_type": "conditional_higher_forecast_vol_floor",
        "front_9d_model_vrp_log": NINE_D_BASE_RULE["model_vrp_log"],
        "front_9d_model_vrp_z": NINE_D_BASE_RULE["model_vrp_z"],
        "front_9d_RSI14_max": NINE_D_BASE_RULE["RSI14_max"],
        "front_9d_forecast_vol_pct_min": float(nine_d_fv_floor),

        "front_12_15_include": True,
        "front_12_15_model_vrp_log": FRONT_12_15_RULE["model_vrp_log"],
        "front_12_15_model_vrp_z": FRONT_12_15_RULE["model_vrp_z"],
        "front_12_15_RSI14_max": FRONT_12_15_RULE["RSI14_max"],
        "front_12_15_forecast_vol_pct_min": FRONT_12_15_RULE["forecast_vol_pct_min"],

        "middle_include": True,
        "middle_model_vrp_log": MIDDLE_RULE["model_vrp_log"],
        "middle_model_vrp_z": MIDDLE_RULE["model_vrp_z"],
        "middle_RSI14_max": MIDDLE_RULE["RSI14_max"],
        "middle_forecast_vol_pct_min": MIDDLE_RULE["forecast_vol_pct_min"],

        "back_include": True,
        "back_model_vrp_log": BACK_RULE["model_vrp_log"],
        "back_model_vrp_z": BACK_RULE["model_vrp_z"],
        "back_RSI14_max": BACK_RULE["RSI14_max"],
        "back_forecast_vol_pct_min": BACK_RULE["forecast_vol_pct_min"],
    })

candidate_grid_wide = pd.DataFrame(wide_rows)

# Convenience diagnostics.
candidate_grid_wide["z_3m_equals_z_1y_within_rule"] = True
candidate_grid_wide["back_locked"] = (
    (candidate_grid_wide["back_model_vrp_log"] == LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"])
    & (candidate_grid_wide["back_model_vrp_z"] == LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"])
    & (candidate_grid_wide["back_RSI14_max"] == LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"])
    & (candidate_grid_wide["back_forecast_vol_pct_min"] == LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"])
)
candidate_grid_wide["front_12_15_same_as_top_reference"] = (
    (candidate_grid_wide["front_12_15_model_vrp_log"] == 0.70)
    & (candidate_grid_wide["front_12_15_model_vrp_z"] == 0.65)
    & (candidate_grid_wide["front_12_15_RSI14_max"] == 68.0)
    & (candidate_grid_wide["front_12_15_forecast_vol_pct_min"] == 14.5)
)
candidate_grid_wide["middle_same_as_top_reference"] = (
    (candidate_grid_wide["middle_model_vrp_log"] == 0.70)
    & (candidate_grid_wide["middle_model_vrp_z"] == 0.70)
    & (candidate_grid_wide["middle_RSI14_max"] == 68.0)
    & (candidate_grid_wide["middle_forecast_vol_pct_min"] == 10.0)
)

# ======================================================================================
# 5. Build tenor-level long candidate design
# ======================================================================================
#
# This is the practical input for Cell 12.
# Each row is candidate_id × tenor.
#
# include_tenor=False means the tenor is excluded from that candidate's Core rules.
# ======================================================================================

long_rows = []

for _, row in candidate_grid_wide.iterrows():
    candidate_id = row["candidate_id"]

    for tenor in ALL_TENORS:
        bucket = tenor_bucket(tenor)

        if bucket == "Front" and tenor == 9:
            include_tenor = bool(row["front_9d_include"])
            rule_scope = "front_9d"
            rule_type = row["front_9d_rule_type"]
            model_vrp_log = row["front_9d_model_vrp_log"]
            model_vrp_z = row["front_9d_model_vrp_z"]
            rsi_max = row["front_9d_RSI14_max"]
            fv_floor = row["front_9d_forecast_vol_pct_min"]

        elif bucket == "Front" and tenor in [12, 15]:
            include_tenor = bool(row["front_12_15_include"])
            rule_scope = "front_12_15"
            rule_type = "shared_front_12_15_rule"
            model_vrp_log = row["front_12_15_model_vrp_log"]
            model_vrp_z = row["front_12_15_model_vrp_z"]
            rsi_max = row["front_12_15_RSI14_max"]
            fv_floor = row["front_12_15_forecast_vol_pct_min"]

        elif bucket == "Middle":
            include_tenor = bool(row["middle_include"])
            rule_scope = "middle"
            rule_type = "shared_middle_rule"
            model_vrp_log = row["middle_model_vrp_log"]
            model_vrp_z = row["middle_model_vrp_z"]
            rsi_max = row["middle_RSI14_max"]
            fv_floor = row["middle_forecast_vol_pct_min"]

        elif bucket == "Back":
            include_tenor = bool(row["back_include"])
            rule_scope = "back"
            rule_type = "locked_back_rule"
            model_vrp_log = row["back_model_vrp_log"]
            model_vrp_z = row["back_model_vrp_z"]
            rsi_max = row["back_RSI14_max"]
            fv_floor = row["back_forecast_vol_pct_min"]

        else:
            raise ValueError(f"Unexpected tenor/bucket combination: tenor={tenor}, bucket={bucket}")

        long_rows.append({
            "candidate_id": candidate_id,
            "candidate_family": row["candidate_family"],
            "candidate_subfamily": row["candidate_subfamily"],
            "locked_model_spec": row["locked_model_spec"],
            "tenor": int(tenor),
            "tenor_bucket": bucket,
            "tenor_bucket_order": BUCKET_ORDER_MAP[bucket],
            "rule_scope": rule_scope,
            "rule_type": rule_type,
            "include_tenor": include_tenor,

            "model_vrp_log": float(model_vrp_log) if pd.notna(model_vrp_log) else np.nan,
            "model_vrp_z": float(model_vrp_z) if pd.notna(model_vrp_z) else np.nan,
            "model_vrp_z_3m": float(model_vrp_z) if pd.notna(model_vrp_z) else np.nan,
            "model_vrp_z_1y": float(model_vrp_z) if pd.notna(model_vrp_z) else np.nan,
            "RSI14_max": float(rsi_max) if pd.notna(rsi_max) else np.nan,
            "forecast_vol_pct_min": float(fv_floor) if pd.notna(fv_floor) else np.nan,

            "is_front_9d": bucket == "Front" and tenor == 9,
            "is_front_12_15": bucket == "Front" and tenor in [12, 15],
            "is_back_locked": bucket == "Back",
        })

candidate_grid_long = (
    pd.DataFrame(long_rows)
    .sort_values(["candidate_id", "tenor"])
    .reset_index(drop=True)
)

# ======================================================================================
# 6. Save outputs
# ======================================================================================

wide_csv_path = OUT_AUDIT_DIR / f"09_core_front_9d_rule_candidate_grid_wide_{CELL11_TIMESTAMP}.csv"
wide_parquet_path = OUT_PROCESSED_DIR / f"09_core_front_9d_rule_candidate_grid_wide_{CELL11_TIMESTAMP}.parquet"

long_csv_path = OUT_AUDIT_DIR / f"09_core_front_9d_rule_candidate_grid_long_{CELL11_TIMESTAMP}.csv"
long_parquet_path = OUT_PROCESSED_DIR / f"09_core_front_9d_rule_candidate_grid_long_{CELL11_TIMESTAMP}.parquet"

context_path = OUT_AUDIT_DIR / f"09_core_front_9d_rule_candidate_grid_context_{CELL11_TIMESTAMP}.csv"
ranges_path = OUT_AUDIT_DIR / f"09_core_front_9d_rule_candidate_grid_ranges_{CELL11_TIMESTAMP}.json"
validation_path = OUT_AUDIT_DIR / f"09_core_front_9d_rule_candidate_grid_validation_{CELL11_TIMESTAMP}.csv"
manifest_path = OUT_AUDIT_DIR / f"09_core_front_9d_rule_candidate_grid_manifest_{CELL11_TIMESTAMP}.json"

candidate_grid_wide.to_csv(wide_csv_path, index=False)
candidate_grid_wide.to_parquet(wide_parquet_path, index=False)

candidate_grid_long.to_csv(long_csv_path, index=False)
candidate_grid_long.to_parquet(long_parquet_path, index=False)

context_review.to_csv(context_path, index=False)

grid_ranges = {
    "candidate_family": CANDIDATE_FAMILY,
    "front_12_15_rule": FRONT_12_15_RULE,
    "nine_d_base_rule": NINE_D_BASE_RULE,
    "nine_d_candidate_forecast_vol_pct_min": NINE_D_CONDITIONAL_FORECAST_VOL_FLOORS,
    "middle_rule": MIDDLE_RULE,
    "back_rule": BACK_RULE,
    "candidate_subfamilies": {
        "front_ex_9d": {
            "description": "9D excluded from Core Front. 12D/15D use Front rule.",
            "candidate_count": int(candidate_grid_wide["candidate_subfamily"].eq("front_ex_9d").sum()),
        },
        "front_conditional_9d": {
            "description": "9D included only with higher 9D-specific forecast-vol floor.",
            "candidate_count": int(candidate_grid_wide["candidate_subfamily"].eq("front_conditional_9d").sum()),
        },
    },
}

with open(ranges_path, "w", encoding="utf-8") as f:
    json.dump(grid_ranges, f, indent=2, default=str)

# ======================================================================================
# 7. Validation
# ======================================================================================

validation_rows = []

def add_validation(check, status, detail):
    validation_rows.append({
        "check": check,
        "status": status,
        "detail": detail,
    })

candidate_count = len(candidate_grid_wide)
expected_candidate_count = 1 + len(NINE_D_CONDITIONAL_FORECAST_VOL_FLOORS)

long_row_count = len(candidate_grid_long)
expected_long_row_count = candidate_count * len(ALL_TENORS)

missing_tenors_by_candidate = (
    candidate_grid_long
    .groupby("candidate_id")["tenor"]
    .apply(lambda x: sorted(set(ALL_TENORS) - set(x.tolist())))
    .reset_index(name="missing_tenors")
)

bad_missing = missing_tenors_by_candidate[
    missing_tenors_by_candidate["missing_tenors"].apply(len).gt(0)
]

bad_z_equality = candidate_grid_long[
    candidate_grid_long["include_tenor"]
    & (
        candidate_grid_long["model_vrp_z_3m"].ne(candidate_grid_long["model_vrp_z_1y"])
    )
]

bad_ex9d = candidate_grid_long[
    candidate_grid_long["candidate_subfamily"].eq("front_ex_9d")
    & candidate_grid_long["is_front_9d"]
    & candidate_grid_long["include_tenor"]
]

bad_conditional_9d = candidate_grid_long[
    candidate_grid_long["candidate_subfamily"].eq("front_conditional_9d")
    & candidate_grid_long["is_front_9d"]
    & (
        ~candidate_grid_long["include_tenor"]
        | ~candidate_grid_long["forecast_vol_pct_min"].isin(NINE_D_CONDITIONAL_FORECAST_VOL_FLOORS)
    )
]

bad_12_15 = candidate_grid_long[
    candidate_grid_long["is_front_12_15"]
    & (
        ~candidate_grid_long["include_tenor"]
        | candidate_grid_long["model_vrp_log"].ne(FRONT_12_15_RULE["model_vrp_log"])
        | candidate_grid_long["model_vrp_z"].ne(FRONT_12_15_RULE["model_vrp_z"])
        | candidate_grid_long["RSI14_max"].ne(FRONT_12_15_RULE["RSI14_max"])
        | candidate_grid_long["forecast_vol_pct_min"].ne(FRONT_12_15_RULE["forecast_vol_pct_min"])
    )
]

bad_middle = candidate_grid_long[
    candidate_grid_long["tenor_bucket"].eq("Middle")
    & (
        ~candidate_grid_long["include_tenor"]
        | candidate_grid_long["model_vrp_log"].ne(MIDDLE_RULE["model_vrp_log"])
        | candidate_grid_long["model_vrp_z"].ne(MIDDLE_RULE["model_vrp_z"])
        | candidate_grid_long["RSI14_max"].ne(MIDDLE_RULE["RSI14_max"])
        | candidate_grid_long["forecast_vol_pct_min"].ne(MIDDLE_RULE["forecast_vol_pct_min"])
    )
]

bad_back = candidate_grid_long[
    candidate_grid_long["tenor_bucket"].eq("Back")
    & (
        ~candidate_grid_long["include_tenor"]
        | candidate_grid_long["model_vrp_log"].ne(BACK_RULE["model_vrp_log"])
        | candidate_grid_long["model_vrp_z"].ne(BACK_RULE["model_vrp_z"])
        | candidate_grid_long["RSI14_max"].ne(BACK_RULE["RSI14_max"])
        | candidate_grid_long["forecast_vol_pct_min"].ne(BACK_RULE["forecast_vol_pct_min"])
    )
]

trade_metric_cols = [
    "trades",
    "win_rate",
    "total_pnl",
    "avg_pnl",
    "avg_pnl_per_day",
    "profit_factor",
    "worst_trade",
    "pnl_per_day_drawdown",
]

unexpected_trade_cols = [
    c for c in trade_metric_cols
    if c in candidate_grid_wide.columns or c in candidate_grid_long.columns
]

add_validation(
    "signal_panel_loaded_for_context",
    "PASS" if len(signal) > 0 else "FAIL",
    f"rows={len(signal):,}; path={signal_panel_path}",
)

add_validation(
    "ranked_summary_loaded_for_context",
    "PASS" if len(ranked_summary) > 0 else "FAIL",
    f"rows={len(ranked_summary):,}; path={ranked_summary_path}",
)

add_validation(
    "candidate_grid_count",
    "PASS" if candidate_count == expected_candidate_count else "FAIL",
    f"candidate_count={candidate_count:,}; expected={expected_candidate_count:,}",
)

add_validation(
    "long_grid_has_all_tenors_per_candidate",
    "PASS" if long_row_count == expected_long_row_count and bad_missing.empty else "FAIL",
    f"long_rows={long_row_count:,}; expected={expected_long_row_count:,}; candidates_missing_tenors={len(bad_missing):,}",
)

add_validation(
    "front_ex_9d_candidate_exists",
    "PASS" if candidate_grid_wide["candidate_subfamily"].eq("front_ex_9d").sum() == 1 else "FAIL",
    f"count={int(candidate_grid_wide['candidate_subfamily'].eq('front_ex_9d').sum())}",
)

add_validation(
    "conditional_9d_candidates_exist",
    "PASS" if candidate_grid_wide["candidate_subfamily"].eq("front_conditional_9d").sum() == len(NINE_D_CONDITIONAL_FORECAST_VOL_FLOORS) else "FAIL",
    f"count={int(candidate_grid_wide['candidate_subfamily'].eq('front_conditional_9d').sum())}; expected={len(NINE_D_CONDITIONAL_FORECAST_VOL_FLOORS)}",
)

add_validation(
    "front_ex_9d_excludes_9d",
    "PASS" if bad_ex9d.empty else "FAIL",
    f"bad_rows={len(bad_ex9d):,}",
)

add_validation(
    "conditional_9d_uses_higher_9d_forecast_vol_floors",
    "PASS" if bad_conditional_9d.empty else "FAIL",
    f"bad_rows={len(bad_conditional_9d):,}; allowed_floors={NINE_D_CONDITIONAL_FORECAST_VOL_FLOORS}",
)

add_validation(
    "front_12_15_rule_fixed",
    "PASS" if bad_12_15.empty else "FAIL",
    f"bad_rows={len(bad_12_15):,}; rule={FRONT_12_15_RULE}",
)

add_validation(
    "middle_rule_fixed",
    "PASS" if bad_middle.empty else "FAIL",
    f"bad_rows={len(bad_middle):,}; rule={MIDDLE_RULE}",
)

add_validation(
    "back_rule_locked",
    "PASS" if bad_back.empty else "FAIL",
    f"bad_rows={len(bad_back):,}; rule={BACK_RULE}",
)

add_validation(
    "z_3m_equals_z_1y_within_included_rules",
    "PASS" if bad_z_equality.empty else "FAIL",
    f"bad_rows={len(bad_z_equality):,}",
)

add_validation(
    "no_trade_evaluation_performed",
    "PASS" if not unexpected_trade_cols else "FAIL",
    f"unexpected_trade_metric_cols={unexpected_trade_cols}",
)

add_validation(
    "no_new_sweep",
    "PASS",
    "Cell 11 creates candidate design only.",
)

add_validation(
    "no_final_candidate_selection",
    "PASS",
    "No final thresholds selected.",
)

add_validation(
    "no_secondary",
    "PASS",
    "Core only.",
)

add_validation(
    "no_sizing_changes",
    "PASS",
    "No sizing fields included.",
)

add_validation(
    "no_production_lock",
    "PASS",
    "No production threshold lock performed.",
)

validation = pd.DataFrame(validation_rows)
validation.to_csv(validation_path, index=False)

failures = validation[validation["status"] == "FAIL"]

manifest = {
    "notebook": "07_unified_fds_core_signal_threshold_research_v1.ipynb",
    "cell": "Cell 11 — 9D-specific Front rule candidate design",
    "timestamp": CELL11_TIMESTAMP,
    "locked_model_spec": LOCKED_MODEL_SPEC,
    "candidate_family": CANDIDATE_FAMILY,
    "candidate_count": int(candidate_count),
    "long_grid_rows": int(long_row_count),
    "signal_panel_path": str(signal_panel_path),
    "ranked_summary_path": str(ranked_summary_path),
    "front_tenor_diag_path": str(front_tenor_diag_path) if front_tenor_diag_path is not None else None,
    "front_ex9d_comparison_path": str(front_ex9d_comparison_path) if front_ex9d_comparison_path is not None else None,
    "front_forecast_state_path": str(front_forecast_state_path) if front_forecast_state_path is not None else None,
    "wide_csv_path": str(wide_csv_path),
    "wide_parquet_path": str(wide_parquet_path),
    "long_csv_path": str(long_csv_path),
    "long_parquet_path": str(long_parquet_path),
    "context_path": str(context_path),
    "ranges_path": str(ranges_path),
    "validation_path": str(validation_path),
    "candidate_subfamilies": sorted(candidate_grid_wide["candidate_subfamily"].unique().tolist()),
    "front_12_15_rule": FRONT_12_15_RULE,
    "nine_d_conditional_forecast_vol_floors": NINE_D_CONDITIONAL_FORECAST_VOL_FLOORS,
    "middle_rule": MIDDLE_RULE,
    "back_rule": BACK_RULE,
    "hard_constraints": [
        "No trade evaluation.",
        "No sweep.",
        "No final threshold selection.",
        "9D exclusion candidate included.",
        "Conditional 9D candidates use forecast-vol floors 16.0, 18.0, 20.0.",
        "12D/15D use fixed Front rule.",
        "Middle uses fixed rule.",
        "Back remains locked.",
        "Within each included rule, model_vrp_z_3m equals model_vrp_z_1y.",
        "No Secondary.",
        "No sizing changes.",
        "No production lock.",
    ],
    "notes": [
        "Cell 12 should sweep these four candidate rules.",
        "Cell 12 should compare front_ex_9d versus front_conditional_9d directly.",
        "This design intentionally does not broaden the full parameter grid.",
    ],
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2, default=str)

if not failures.empty:
    display(validation)
    raise RuntimeError("Cell 11 validation failed. Review validation output above.")

# ======================================================================================
# 8. Display concise review
# ======================================================================================

print("=" * 100)
print("Cell 11 — 9D-specific Front rule candidate design")
print("=" * 100)
print(f"Signal panel:                       {signal_panel_path}")
print(f"Ranked summary:                     {ranked_summary_path}")
print(f"Candidate family:                   {CANDIDATE_FAMILY}")
print(f"Candidate count:                    {candidate_count:,}")
print(f"Long grid rows:                     {long_row_count:,}")
print(f"9D exclusion candidates:            {int(candidate_grid_wide['candidate_subfamily'].eq('front_ex_9d').sum()):,}")
print(f"Conditional 9D candidates:          {int(candidate_grid_wide['candidate_subfamily'].eq('front_conditional_9d').sum()):,}")
print(f"9D conditional FV floors:           {NINE_D_CONDITIONAL_FORECAST_VOL_FLOORS}")
print("No trade evaluation:                True")
print("No sweep:                           True")
print("No final candidate selection:       True")
print("No Secondary:                       True")
print("No sizing changes:                  True")
print("No production lock:                 True")

print()
print("Validation:")
display(validation)

print()
print("Wide candidate design:")
display(candidate_grid_wide)

print()
print("Long tenor-level candidate design:")
display(candidate_grid_long)

print()
print("Context review:")
display(context_review)

print()
print("Saved outputs:")
for p in [
    wide_csv_path,
    wide_parquet_path,
    long_csv_path,
    long_parquet_path,
    context_path,
    ranges_path,
    validation_path,
    manifest_path,
]:
    print(f"  {p}")

print("\nCELL 11 PASSED")

====================================================================================================
Cell 11 — 9D-specific Front rule candidate design
====================================================================================================
Signal panel:                       C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\01_unified_fds_signal_base_panel_20200102_20260701_20260704_211636.parquet
Ranked summary:                     C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\07_core_candidate_ranked_summary_20260704_220821.csv
Candidate family:                   core_front_9d_rule_test
Candidate count:                    4
Long grid rows:                     36
9D exclusion candidates:            1
Conditional 9D candidates:          3
9D conditional FV floors:           [16.0, 18.0, 20.0]
No trade evaluation:                True
No sweep:                           True
No final candidate selection:       True
No Secondary:                       True
No sizing changes:                  True
No production lock:                 True

Validation:

                                                check status                                             detail
0                     signal_panel_loaded_for_context   PASS  rows=14,688; path=C:\Users\patri\vrp_project\d...
1                   ranked_summary_loaded_for_context   PASS  rows=320; path=C:\Users\patri\vrp_project\data...
2                                candidate_grid_count   PASS                      candidate_count=4; expected=4
3              long_grid_has_all_tenors_per_candidate   PASS  long_rows=36; expected=36; candidates_missing_...
4                        front_ex_9d_candidate_exists   PASS                                            count=1
5                     conditional_9d_candidates_exist   PASS                                count=3; expected=3
6                             front_ex_9d_excludes_9d   PASS                                         bad_rows=0
7   conditional_9d_uses_higher_9d_forecast_vol_floors   PASS      bad_rows=0; allowed_floors=[16.0, 18.0, 20.0]
8                              front_12_15_rule_fixed   PASS  bad_rows=0; rule={'model_vrp_log': 0.7, 'model...
9                                   middle_rule_fixed   PASS  bad_rows=0; rule={'model_vrp_log': 0.7, 'model...
10                                   back_rule_locked   PASS  bad_rows=0; rule={'model_vrp_log': 0.7, 'model...
11             z_3m_equals_z_1y_within_included_rules   PASS                                         bad_rows=0
12                      no_trade_evaluation_performed   PASS                    unexpected_trade_metric_cols=[]
13                                       no_new_sweep   PASS             Cell 11 creates candidate design only.
14                       no_final_candidate_selection   PASS                      No final thresholds selected.
15                                       no_secondary   PASS                                         Core only.
16                                  no_sizing_changes   PASS                         No sizing fields included.
17                                 no_production_lock   PASS            No production threshold lock performed.

Wide candidate design:

,candidate_id,candidate_family,candidate_subfamily,candidate_description,locked_model_spec,front_9d_include,front_9d_rule_type,front_9d_model_vrp_log,front_9d_model_vrp_z,front_9d_RSI14_max,front_9d_forecast_vol_pct_min,front_12_15_include,front_12_15_model_vrp_log,front_12_15_model_vrp_z,front_12_15_RSI14_max,front_12_15_forecast_vol_pct_min,middle_include,middle_model_vrp_log,middle_model_vrp_z,middle_RSI14_max,middle_forecast_vol_pct_min,back_include,back_model_vrp_log,back_model_vrp_z,back_RSI14_max,back_forecast_vol_pct_min,z_3m_equals_z_1y_within_rule,back_locked,front_12_15_same_as_top_reference,middle_same_as_top_reference
0,core_front_9d_rule_0001,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,unified_fds_no_min_return,False,excluded,0.7,0.65,68.0,NaN,True,0.7,0.65,68.0,14.5,True,0.7,0.7,68.0,10.0,True,0.7,0.7,70.0,8.5,True,True,True,True
1,core_front_9d_rule_0002,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 16.0; use F...,unified_fds_no_min_return,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,16.0,True,0.7,0.65,68.0,14.5,True,0.7,0.7,68.0,10.0,True,0.7,0.7,70.0,8.5,True,True,True,True
2,core_front_9d_rule_0003,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 18.0; use F...,unified_fds_no_min_return,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,18.0,True,0.7,0.65,68.0,14.5,True,0.7,0.7,68.0,10.0,True,0.7,0.7,70.0,8.5,True,True,True,True
3,core_front_9d_rule_0004,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,unified_fds_no_min_return,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,True,0.7,0.65,68.0,14.5,True,0.7,0.7,68.0,10.0,True,0.7,0.7,70.0,8.5,True,True,True,True

Long tenor-level candidate design:

               candidate_id         candidate_family   candidate_subfamily          locked_model_spec  tenor tenor_bucket  tenor_bucket_order   rule_scope                              rule_type  include_tenor  model_vrp_log  model_vrp_z  model_vrp_z_3m  model_vrp_z_1y  RSI14_max  forecast_vol_pct_min  is_front_9d  is_front_12_15  is_back_locked
0   core_front_9d_rule_0001  core_front_9d_rule_test           front_ex_9d  unified_fds_no_min_return      9        Front                   1     front_9d                               excluded          False            0.7         0.65            0.65            0.65       68.0                   NaN         True           False           False
1   core_front_9d_rule_0001  core_front_9d_rule_test           front_ex_9d  unified_fds_no_min_return     12        Front                   1  front_12_15                shared_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True           False
2   core_front_9d_rule_0001  core_front_9d_rule_test           front_ex_9d  unified_fds_no_min_return     15        Front                   1  front_12_15                shared_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True           False
3   core_front_9d_rule_0001  core_front_9d_rule_test           front_ex_9d  unified_fds_no_min_return     18       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
4   core_front_9d_rule_0001  core_front_9d_rule_test           front_ex_9d  unified_fds_no_min_return     21       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
5   core_front_9d_rule_0001  core_front_9d_rule_test           front_ex_9d  unified_fds_no_min_return     24       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
6   core_front_9d_rule_0001  core_front_9d_rule_test           front_ex_9d  unified_fds_no_min_return     27         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True
7   core_front_9d_rule_0001  core_front_9d_rule_test           front_ex_9d  unified_fds_no_min_return     30         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True
8   core_front_9d_rule_0001  core_front_9d_rule_test           front_ex_9d  unified_fds_no_min_return     33         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True
9   core_front_9d_rule_0002  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return      9        Front                   1     front_9d  conditional_higher_forecast_vol_floor           True            0.7         0.65            0.65            0.65       68.0                  16.0         True           False           False
10  core_front_9d_rule_0002  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     12        Front                   1  front_12_15                shared_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True           False
11  core_front_9d_rule_0002  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     15        Front                   1  front_12_15                shared_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True           False
12  core_front_9d_rule_0002  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     18       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
13  core_front_9d_rule_0002  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     21       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
14  core_front_9d_rule_0002  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     24       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
15  core_front_9d_rule_0002  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     27         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True
16  core_front_9d_rule_0002  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     30         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True
17  core_front_9d_rule_0002  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     33         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True
18  core_front_9d_rule_0003  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return      9        Front                   1     front_9d  conditional_higher_forecast_vol_floor           True            0.7         0.65            0.65            0.65       68.0                  18.0         True           False           False
19  core_front_9d_rule_0003  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     12        Front                   1  front_12_15                shared_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True           False
20  core_front_9d_rule_0003  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     15        Front                   1  front_12_15                shared_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True           False
21  core_front_9d_rule_0003  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     18       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
22  core_front_9d_rule_0003  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     21       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
23  core_front_9d_rule_0003  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     24       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
24  core_front_9d_rule_0003  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     27         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True
25  core_front_9d_rule_0003  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     30         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True
26  core_front_9d_rule_0003  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     33         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True
27  core_front_9d_rule_0004  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return      9        Front                   1     front_9d  conditional_higher_forecast_vol_floor           True            0.7         0.65            0.65            0.65       68.0                  20.0         True           False           False
28  core_front_9d_rule_0004  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     12        Front                   1  front_12_15                shared_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True           False
29  core_front_9d_rule_0004  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     15        Front                   1  front_12_15                shared_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True           False
30  core_front_9d_rule_0004  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     18       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
31  core_front_9d_rule_0004  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     21       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
32  core_front_9d_rule_0004  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     24       Middle                   2       middle                     shared_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False           False
33  core_front_9d_rule_0004  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     27         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True
34  core_front_9d_rule_0004  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     30         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True
35  core_front_9d_rule_0004  core_front_9d_rule_test  front_conditional_9d  unified_fds_no_min_return     33         Back                   3         back                       locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False            True

Context review:

                  context_item                                              value
0            signal_panel_path  C:\Users\patri\vrp_project\data\processed\vrp_...
1          ranked_summary_path  C:\Users\patri\vrp_project\data\audit\vrp_unif...
2        front_tenor_diag_path  C:\Users\patri\vrp_project\data\audit\vrp_unif...
3   front_ex9d_comparison_path  C:\Users\patri\vrp_project\data\audit\vrp_unif...
4    front_forecast_state_path  C:\Users\patri\vrp_project\data\audit\vrp_unif...
5                  signal_rows                                              14688
6              signal_date_min                                         2020-01-02
7              signal_date_max                                         2026-07-01
8                signal_tenors                [9, 12, 15, 18, 21, 24, 27, 30, 33]
9       top_ranked_candidate_1                          core_front_expanded_00168
10      top_ranked_candidate_2                          core_front_expanded_00182
11      top_ranked_candidate_3                          core_front_expanded_00198
12      top_ranked_candidate_4                          core_front_expanded_00167
13      top_ranked_candidate_5                          core_front_expanded_00181
14      top_ranked_candidate_6                          core_front_expanded_00197
15      top_ranked_candidate_7                          core_front_expanded_00248
16      top_ranked_candidate_8                          core_front_expanded_00262
17      top_ranked_candidate_9                          core_front_expanded_00278
18     top_ranked_candidate_10                          core_front_expanded_00183

Saved outputs:
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_wide_20260704_221815.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_wide_20260704_221815.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_long_20260704_221815.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_long_20260704_221815.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_context_20260704_221815.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_ranges_20260704_221815.json
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_validation_20260704_221815.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_manifest_20260704_221815.json

CELL 11 PASSED

In [14]:
# ======================================================================================
# Cell 12 — 9D-specific Front rule sweep
# ======================================================================================
#
# Objective:
#   Evaluate the four Cell 11 9D-specific Front rule candidates:
#
#       1. Exclude 9D from Core Front.
#       2. Allow 9D only if 9D forecast vol > 16.0.
#       3. Allow 9D only if 9D forecast vol > 18.0.
#       4. Allow 9D only if 9D forecast vol > 20.0.
#
# Inputs:
#   01_unified_fds_signal_base_panel_*.parquet
#   09_core_front_9d_rule_candidate_grid_wide_*.parquet
#   09_core_front_9d_rule_candidate_grid_long_*.parquet
#
# Outputs:
#   10_core_front_9d_rule_sweep_candidate_summary_*.csv
#   10_core_front_9d_rule_sweep_by_bucket_*.csv
#   10_core_front_9d_rule_sweep_by_tenor_*.csv
#   10_core_front_9d_rule_sweep_by_year_*.csv
#   10_core_front_9d_rule_sweep_candidate_pass_diagnostics_*.csv
#   10_core_front_9d_rule_sweep_selected_trade_panel_*.parquet
#   10_core_front_9d_rule_sweep_validation_*.csv
#   10_core_front_9d_rule_sweep_manifest_*.json
#
# Selection universes:
#   1. all_qualified_trades
#   2. one_trade_per_bucket_per_date_best_rank
#   3. one_trade_per_date_best_rank
#
# Primary metric:
#   avg_pnl_per_day
#
# Important:
#   This is a focused 9D-rule sweep only.
#   This cell does NOT select final thresholds.
#   This cell does NOT run a broad optimization.
#   This cell does NOT change sizing.
#   This cell does NOT lock production.
# ======================================================================================

from pathlib import Path
from datetime import datetime
import json
import time
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore", category=RuntimeWarning)

pd.set_option("display.max_columns", 280)
pd.set_option("display.width", 460)

# ======================================================================================
# 0. Fallback config
# ======================================================================================

if "PROJECT_ROOT" not in globals():
    PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

if "NEW_BRANCH" not in globals():
    NEW_BRANCH = "vrp_unified_fds_core_signal_threshold_research_v1"

if "OUT_PROCESSED_DIR" not in globals():
    OUT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / NEW_BRANCH
    OUT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

if "OUT_AUDIT_DIR" not in globals():
    OUT_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / NEW_BRANCH
    OUT_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

CELL12_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

if "LOCKED_MODEL_SPEC" not in globals():
    LOCKED_MODEL_SPEC = "unified_fds_no_min_return"

if "ALL_TENORS" not in globals():
    ALL_TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

if "BUCKET_CENTER_TENOR" not in globals():
    BUCKET_CENTER_TENOR = {
        "Front": 12,
        "Middle": 21,
        "Back": 30,
    }

SELECTION_UNIVERSES = [
    "all_qualified_trades",
    "one_trade_per_bucket_per_date_best_rank",
    "one_trade_per_date_best_rank",
]

PRIMARY_RANKING_METRIC = "avg_pnl_per_day"
CANDIDATE_FAMILY = "core_front_9d_rule_test"

# ======================================================================================
# 1. Helpers
# ======================================================================================

def latest_file(directory: Path, pattern: str, required: bool = True) -> Path | None:
    matches = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if matches:
        return matches[0]
    if required:
        raise FileNotFoundError(f"No file found in {directory} matching {pattern}")
    return None


def profit_factor_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").dropna()
    gross_profit = float(pnl[pnl > 0].sum())
    gross_loss = float(pnl[pnl < 0].sum())

    if gross_loss < 0:
        return gross_profit / abs(gross_loss)
    if gross_profit > 0:
        return np.inf
    return np.nan


def max_drawdown_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)

    if len(pnl) == 0:
        return np.nan

    cumulative = pnl.cumsum()
    running_max = cumulative.cummax()
    drawdown = cumulative - running_max

    return float(drawdown.min())


def worst_rolling_sum(pnl: pd.Series, window: int) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)

    if len(pnl) == 0:
        return np.nan

    if len(pnl) < window:
        return float(pnl.sum())

    return float(pnl.rolling(window=window, min_periods=window).sum().min())


def add_selection_ranks(df: pd.DataFrame) -> pd.DataFrame:
    """
    Diagnostic DTE selector:
      - Within bucket/date: rank by z_1y, z_3m, model_vrp_log.
      - Tie-break closest to bucket center.
      - Does not use realized P&L.
    """
    d = df.copy()

    if d.empty:
        return d

    d["bucket_center_tenor"] = d["tenor_bucket"].map(BUCKET_CENTER_TENOR)
    d["distance_to_bucket_center"] = (d["tenor"] - d["bucket_center_tenor"]).abs()

    bucket_group = ["trade_date", "tenor_bucket"]

    d["rank_z_1y_in_bucket_date"] = (
        d.groupby(bucket_group)["model_vrp_z_1y"]
        .rank(method="min", ascending=False)
    )
    d["rank_z_3m_in_bucket_date"] = (
        d.groupby(bucket_group)["model_vrp_z_3m"]
        .rank(method="min", ascending=False)
    )
    d["rank_vrp_log_in_bucket_date"] = (
        d.groupby(bucket_group)["model_vrp_log"]
        .rank(method="min", ascending=False)
    )

    d["avg_signal_rank_in_bucket_date"] = d[
        [
            "rank_z_1y_in_bucket_date",
            "rank_z_3m_in_bucket_date",
            "rank_vrp_log_in_bucket_date",
        ]
    ].mean(axis=1)

    d["rank_z_1y_in_date"] = (
        d.groupby("trade_date")["model_vrp_z_1y"]
        .rank(method="min", ascending=False)
    )
    d["rank_z_3m_in_date"] = (
        d.groupby("trade_date")["model_vrp_z_3m"]
        .rank(method="min", ascending=False)
    )
    d["rank_vrp_log_in_date"] = (
        d.groupby("trade_date")["model_vrp_log"]
        .rank(method="min", ascending=False)
    )

    d["avg_signal_rank_in_date"] = d[
        [
            "rank_z_1y_in_date",
            "rank_z_3m_in_date",
            "rank_vrp_log_in_date",
        ]
    ].mean(axis=1)

    return d


def select_trade_universes(qualified: pd.DataFrame) -> dict[str, pd.DataFrame]:
    if qualified.empty:
        return {
            "all_qualified_trades": qualified.copy(),
            "one_trade_per_bucket_per_date_best_rank": qualified.copy(),
            "one_trade_per_date_best_rank": qualified.copy(),
        }

    q = add_selection_ranks(qualified)

    one_trade_per_bucket_date = (
        q.sort_values(
            [
                "trade_date",
                "tenor_bucket_order",
                "avg_signal_rank_in_bucket_date",
                "distance_to_bucket_center",
                "rank_z_1y_in_bucket_date",
                "rank_z_3m_in_bucket_date",
                "rank_vrp_log_in_bucket_date",
                "tenor",
            ],
            ascending=[True, True, True, True, True, True, True, True],
        )
        .groupby(["trade_date", "tenor_bucket"], as_index=False)
        .head(1)
        .copy()
    )

    one_trade_per_date = (
        q.sort_values(
            [
                "trade_date",
                "avg_signal_rank_in_date",
                "rank_z_1y_in_date",
                "rank_z_3m_in_date",
                "rank_vrp_log_in_date",
                "distance_to_bucket_center",
                "tenor_bucket_order",
                "tenor",
            ],
            ascending=[True, True, True, True, True, True, True, True],
        )
        .groupby(["trade_date"], as_index=False)
        .head(1)
        .copy()
    )

    return {
        "all_qualified_trades": q.copy(),
        "one_trade_per_bucket_per_date_best_rank": one_trade_per_bucket_date,
        "one_trade_per_date_best_rank": one_trade_per_date,
    }


def summarize_trade_set(
    df: pd.DataFrame,
    candidate_id: str,
    selection_universe: str,
    group_cols: list[str] | None = None,
    include_empty_overall: bool = False,
) -> pd.DataFrame:
    if group_cols is None:
        group_cols = []

    d = df.copy()

    if not d.empty:
        d["trade_date"] = pd.to_datetime(d["trade_date"], errors="coerce").dt.normalize()

        for c in [
            "normalized_pnl_dollars",
            "normalized_pnl_per_day",
            "win",
            "tenor",
        ]:
            if c in d.columns:
                d[c] = pd.to_numeric(d[c], errors="coerce")

        d = d[
            d["normalized_pnl_dollars"].notna()
            & d["normalized_pnl_per_day"].notna()
        ].copy()

        d = d.sort_values(["trade_date", "tenor"]).copy()

    if d.empty:
        if include_empty_overall and len(group_cols) == 0:
            return pd.DataFrame([{
                "candidate_id": candidate_id,
                "selection_universe": selection_universe,
                "trades": 0,
                "unique_trade_dates": 0,
                "date_min": pd.NaT,
                "date_max": pd.NaT,
                "tenor_min": np.nan,
                "tenor_max": np.nan,
                "avg_tenor": np.nan,
                "win_rate": np.nan,
                "total_pnl": 0.0,
                "avg_pnl": np.nan,
                "median_pnl": np.nan,
                "worst_trade": np.nan,
                "best_trade": np.nan,
                "profit_factor": np.nan,
                "selected_trade_drawdown": np.nan,
                "worst_5_trade_sum": np.nan,
                "worst_10_trade_sum": np.nan,
                "worst_20_trade_sum": np.nan,
                "trades_le_neg_50k": 0,
                "trades_le_neg_100k": 0,
                "trades_le_neg_150k": 0,
                "total_pnl_per_day_sum": 0.0,
                "avg_pnl_per_day": np.nan,
                "median_pnl_per_day": np.nan,
                "worst_trade_pnl_per_day": np.nan,
                "best_trade_pnl_per_day": np.nan,
                "profit_factor_pnl_per_day": np.nan,
                "pnl_per_day_drawdown": np.nan,
                "worst_5_trade_pnl_per_day_sum": np.nan,
                "worst_10_trade_pnl_per_day_sum": np.nan,
                "worst_20_trade_pnl_per_day_sum": np.nan,
                "trades_2025": 0,
                "pnl_2025": 0.0,
                "avg_pnl_per_day_2025": np.nan,
                "worst_trade_2025": np.nan,
                "trades_2026": 0,
                "pnl_2026": 0.0,
                "avg_pnl_per_day_2026": np.nan,
                "worst_trade_2026": np.nan,
            }])
        return pd.DataFrame()

    rows = []

    if len(group_cols) == 0:
        grouped = [((), d)]
    else:
        grouped = d.groupby(group_cols, dropna=False)

    for keys, g in grouped:
        if len(group_cols) == 0:
            keys = ()
        elif not isinstance(keys, tuple):
            keys = (keys,)

        row = {
            "candidate_id": candidate_id,
            "selection_universe": selection_universe,
        }

        for col, key in zip(group_cols, keys):
            row[col] = key

        pnl = pd.to_numeric(g["normalized_pnl_dollars"], errors="coerce")
        pnl_day = pd.to_numeric(g["normalized_pnl_per_day"], errors="coerce")
        wins = pd.to_numeric(g["win"], errors="coerce") if "win" in g.columns else pd.Series(np.nan, index=g.index)

        y2025 = g[g["trade_date"].dt.year == 2025].copy()
        y2026 = g[g["trade_date"].dt.year == 2026].copy()

        row.update({
            "trades": int(len(g)),
            "unique_trade_dates": int(g["trade_date"].nunique()),
            "date_min": g["trade_date"].min(),
            "date_max": g["trade_date"].max(),
            "tenor_min": int(g["tenor"].min()) if "tenor" in g.columns and g["tenor"].notna().any() else np.nan,
            "tenor_max": int(g["tenor"].max()) if "tenor" in g.columns and g["tenor"].notna().any() else np.nan,
            "avg_tenor": float(g["tenor"].mean()) if "tenor" in g.columns and g["tenor"].notna().any() else np.nan,

            "win_rate": float(wins.mean()) if wins.notna().sum() else np.nan,
            "total_pnl": float(pnl.sum()),
            "avg_pnl": float(pnl.mean()),
            "median_pnl": float(pnl.median()),
            "worst_trade": float(pnl.min()),
            "best_trade": float(pnl.max()),
            "profit_factor": profit_factor_from_pnl(pnl),
            "selected_trade_drawdown": max_drawdown_from_pnl(pnl),
            "worst_5_trade_sum": worst_rolling_sum(pnl, 5),
            "worst_10_trade_sum": worst_rolling_sum(pnl, 10),
            "worst_20_trade_sum": worst_rolling_sum(pnl, 20),
            "trades_le_neg_50k": int((pnl <= -50_000).sum()),
            "trades_le_neg_100k": int((pnl <= -100_000).sum()),
            "trades_le_neg_150k": int((pnl <= -150_000).sum()),

            "total_pnl_per_day_sum": float(pnl_day.sum()),
            "avg_pnl_per_day": float(pnl_day.mean()),
            "median_pnl_per_day": float(pnl_day.median()),
            "worst_trade_pnl_per_day": float(pnl_day.min()),
            "best_trade_pnl_per_day": float(pnl_day.max()),
            "profit_factor_pnl_per_day": profit_factor_from_pnl(pnl_day),
            "pnl_per_day_drawdown": max_drawdown_from_pnl(pnl_day),
            "worst_5_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 5),
            "worst_10_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 10),
            "worst_20_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 20),

            "trades_2025": int(len(y2025)),
            "pnl_2025": float(y2025["normalized_pnl_dollars"].sum()) if len(y2025) else 0.0,
            "avg_pnl_per_day_2025": float(y2025["normalized_pnl_per_day"].mean()) if len(y2025) else np.nan,
            "worst_trade_2025": float(y2025["normalized_pnl_dollars"].min()) if len(y2025) else np.nan,

            "trades_2026": int(len(y2026)),
            "pnl_2026": float(y2026["normalized_pnl_dollars"].sum()) if len(y2026) else 0.0,
            "avg_pnl_per_day_2026": float(y2026["normalized_pnl_per_day"].mean()) if len(y2026) else np.nan,
            "worst_trade_2026": float(y2026["normalized_pnl_dollars"].min()) if len(y2026) else np.nan,
        })

        rows.append(row)

    return pd.DataFrame(rows)


def apply_tenor_level_candidate_thresholds(signal_df: pd.DataFrame, candidate_rules: pd.DataFrame) -> tuple[pd.DataFrame, dict]:
    """
    Apply one Cell 11 tenor-level candidate rule set.

    candidate_rules contains one row per tenor.
    include_tenor=False means the tenor is excluded from the candidate's Core rules.
    """
    candidate_id = candidate_rules["candidate_id"].iloc[0]

    threshold_cols = [
        "candidate_id",
        "candidate_family",
        "candidate_subfamily",
        "tenor",
        "rule_scope",
        "rule_type",
        "include_tenor",
        "model_vrp_log",
        "model_vrp_z_3m",
        "model_vrp_z_1y",
        "RSI14_max",
        "forecast_vol_pct_min",
    ]

    rules = candidate_rules[threshold_cols].copy()

    rules = rules.rename(columns={
        "model_vrp_log": "threshold_model_vrp_log",
        "model_vrp_z_3m": "threshold_model_vrp_z_3m",
        "model_vrp_z_1y": "threshold_model_vrp_z_1y",
        "RSI14_max": "threshold_RSI14_max",
        "forecast_vol_pct_min": "threshold_forecast_vol_pct_min",
    })

    d = signal_df.merge(
        rules,
        on="tenor",
        how="left",
        validate="many_to_one",
    )

    required_inputs = (
        d["include_tenor"].fillna(False).astype(bool)
        & d["model_vrp_log"].notna()
        & d["model_vrp_z_3m"].notna()
        & d["model_vrp_z_1y"].notna()
        & d["RSI14"].notna()
        & d["forecast_vol_pct"].notna()
        & d["threshold_model_vrp_log"].notna()
        & d["threshold_model_vrp_z_3m"].notna()
        & d["threshold_model_vrp_z_1y"].notna()
        & d["threshold_RSI14_max"].notna()
        & d["threshold_forecast_vol_pct_min"].notna()
    )

    pass_mask = (
        required_inputs
        & (d["model_vrp_log"] > d["threshold_model_vrp_log"])
        & (d["model_vrp_z_3m"] > d["threshold_model_vrp_z_3m"])
        & (d["model_vrp_z_1y"] > d["threshold_model_vrp_z_1y"])
        & (d["RSI14"] < d["threshold_RSI14_max"])
        & (d["forecast_vol_pct"] > d["threshold_forecast_vol_pct_min"])
    )

    d["candidate_core_pass"] = pass_mask

    outcome_available = (
        d["normalized_pnl_dollars"].notna()
        & d["normalized_pnl_per_day"].notna()
    )

    qualified = d[
        d["candidate_core_pass"]
        & outcome_available
    ].copy()

    diagnostics = {
        "candidate_id": candidate_id,
        "candidate_subfamily": candidate_rules["candidate_subfamily"].iloc[0],
        "threshold_input_available_rows": int(required_inputs.sum()),
        "pass_rows_all_dates": int(pass_mask.sum()),
        "pass_rows_with_outcomes": int(len(qualified)),
        "trade_outcome_available_rows": int(outcome_available.sum()),
    }

    for tenor in ALL_TENORS:
        tenor_mask = d["tenor"].eq(tenor)
        diagnostics[f"tenor_{tenor}_included"] = bool(
            candidate_rules.loc[candidate_rules["tenor"].eq(tenor), "include_tenor"].iloc[0]
        )
        diagnostics[f"tenor_{tenor}_pass_rows_all_dates"] = int((pass_mask & tenor_mask).sum())
        diagnostics[f"tenor_{tenor}_pass_rows_with_outcomes"] = int(
            (pass_mask & tenor_mask & outcome_available).sum()
        )

    for bucket in ["Front", "Middle", "Back"]:
        bucket_mask = d["tenor_bucket"].eq(bucket)
        diagnostics[f"{bucket}_pass_rows_all_dates"] = int((pass_mask & bucket_mask).sum())
        diagnostics[f"{bucket}_pass_rows_with_outcomes"] = int(
            (pass_mask & bucket_mask & outcome_available).sum()
        )

    return qualified, diagnostics


def attach_candidate_parameters(summary_df: pd.DataFrame, wide_grid: pd.DataFrame) -> pd.DataFrame:
    if summary_df.empty:
        return summary_df

    param_cols = [
        "candidate_id",
        "candidate_family",
        "candidate_subfamily",
        "candidate_description",
        "front_9d_include",
        "front_9d_rule_type",
        "front_9d_model_vrp_log",
        "front_9d_model_vrp_z",
        "front_9d_RSI14_max",
        "front_9d_forecast_vol_pct_min",
        "front_12_15_model_vrp_log",
        "front_12_15_model_vrp_z",
        "front_12_15_RSI14_max",
        "front_12_15_forecast_vol_pct_min",
        "middle_model_vrp_log",
        "middle_model_vrp_z",
        "middle_RSI14_max",
        "middle_forecast_vol_pct_min",
        "back_model_vrp_log",
        "back_model_vrp_z",
        "back_RSI14_max",
        "back_forecast_vol_pct_min",
    ]

    available = [c for c in param_cols if c in wide_grid.columns]

    return summary_df.merge(
        wide_grid[available].drop_duplicates("candidate_id"),
        on="candidate_id",
        how="left",
        validate="many_to_one",
    )


# ======================================================================================
# 2. Load inputs
# ======================================================================================

signal_panel_path = latest_file(
    OUT_PROCESSED_DIR,
    "01_unified_fds_signal_base_panel_*.parquet",
    required=True,
)

candidate_grid_wide_path = latest_file(
    OUT_PROCESSED_DIR,
    "09_core_front_9d_rule_candidate_grid_wide_*.parquet",
    required=True,
)

candidate_grid_long_path = latest_file(
    OUT_PROCESSED_DIR,
    "09_core_front_9d_rule_candidate_grid_long_*.parquet",
    required=True,
)

signal = pd.read_parquet(signal_panel_path)
grid_wide = pd.read_parquet(candidate_grid_wide_path)
grid_long = pd.read_parquet(candidate_grid_long_path)

signal["trade_date"] = pd.to_datetime(signal["trade_date"], errors="coerce").dt.normalize()
signal["tenor"] = pd.to_numeric(signal["tenor"], errors="coerce").astype(int)

required_signal_cols = [
    "trade_date",
    "tenor",
    "tenor_bucket",
    "tenor_bucket_order",
    "model_spec",
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14",
    "forecast_vol_pct",
    "normalized_pnl_dollars",
    "normalized_pnl_per_day",
    "win",
]

required_long_cols = [
    "candidate_id",
    "candidate_family",
    "candidate_subfamily",
    "tenor",
    "tenor_bucket",
    "tenor_bucket_order",
    "rule_scope",
    "rule_type",
    "include_tenor",
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14_max",
    "forecast_vol_pct_min",
]

missing_signal_cols = [c for c in required_signal_cols if c not in signal.columns]
missing_long_cols = [c for c in required_long_cols if c not in grid_long.columns]

if missing_signal_cols:
    raise KeyError(f"Cell 12 missing signal columns: {missing_signal_cols}")

if missing_long_cols:
    raise KeyError(f"Cell 12 missing long-grid columns: {missing_long_cols}")

for c in [
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14",
    "forecast_vol_pct",
    "normalized_pnl_dollars",
    "normalized_pnl_per_day",
    "win",
]:
    signal[c] = pd.to_numeric(signal[c], errors="coerce")

for c in [
    "tenor",
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
    "RSI14_max",
    "forecast_vol_pct_min",
]:
    grid_long[c] = pd.to_numeric(grid_long[c], errors="coerce")

grid_long["include_tenor"] = grid_long["include_tenor"].astype(bool)
grid_long["tenor"] = grid_long["tenor"].astype(int)

grid_wide = grid_wide.sort_values("candidate_id").reset_index(drop=True)
grid_long = grid_long.sort_values(["candidate_id", "tenor"]).reset_index(drop=True)

candidate_ids = grid_wide["candidate_id"].dropna().tolist()

# ======================================================================================
# 3. Sweep candidates
# ======================================================================================

start_time = time.time()

overall_summary_rows = []
bucket_summary_rows = []
tenor_summary_rows = []
year_summary_rows = []
pass_diagnostic_rows = []
selected_trade_frames = []

print("=" * 100)
print("Cell 12 — 9D-specific Front rule sweep")
print("=" * 100)
print(f"Signal panel:             {signal_panel_path}")
print(f"Wide candidate grid:      {candidate_grid_wide_path}")
print(f"Long candidate grid:      {candidate_grid_long_path}")
print(f"Candidates to evaluate:   {len(candidate_ids):,}")
print(f"Selection universes:      {SELECTION_UNIVERSES}")
print(f"Primary metric:           {PRIMARY_RANKING_METRIC}")
print()

for i, candidate_id in enumerate(candidate_ids, start=1):
    rules = grid_long[grid_long["candidate_id"].eq(candidate_id)].copy()

    if rules.empty:
        raise RuntimeError(f"No long-grid rules found for candidate_id={candidate_id}")

    qualified, pass_diag = apply_tenor_level_candidate_thresholds(signal, rules)
    pass_diagnostic_rows.append(pass_diag)

    universes = select_trade_universes(qualified)

    for universe_name, selected in universes.items():
        if not selected.empty:
            selected = selected.copy()
            selected.insert(0, "selection_universe", universe_name)

            selected_trade_frames.append(selected)

        overall_summary_rows.append(
            summarize_trade_set(
                selected,
                candidate_id=candidate_id,
                selection_universe=universe_name,
                group_cols=[],
                include_empty_overall=True,
            )
        )

        bucket_summary_rows.append(
            summarize_trade_set(
                selected,
                candidate_id=candidate_id,
                selection_universe=universe_name,
                group_cols=["tenor_bucket", "tenor_bucket_order"],
                include_empty_overall=False,
            )
        )

        tenor_summary_rows.append(
            summarize_trade_set(
                selected,
                candidate_id=candidate_id,
                selection_universe=universe_name,
                group_cols=["tenor", "tenor_bucket", "tenor_bucket_order"],
                include_empty_overall=False,
            )
        )

        if not selected.empty:
            y = selected.copy()
            y["year"] = y["trade_date"].dt.year.astype(int)

            year_summary_rows.append(
                summarize_trade_set(
                    y,
                    candidate_id=candidate_id,
                    selection_universe=universe_name,
                    group_cols=["year"],
                    include_empty_overall=False,
                )
            )

    print(f"  Evaluated {i:,} / {len(candidate_ids):,}: {candidate_id}")

summary_overall = pd.concat(overall_summary_rows, ignore_index=True) if overall_summary_rows else pd.DataFrame()
summary_by_bucket = pd.concat(bucket_summary_rows, ignore_index=True) if bucket_summary_rows else pd.DataFrame()
summary_by_tenor = pd.concat(tenor_summary_rows, ignore_index=True) if tenor_summary_rows else pd.DataFrame()
summary_by_year = pd.concat(year_summary_rows, ignore_index=True) if year_summary_rows else pd.DataFrame()
pass_diagnostics = pd.DataFrame(pass_diagnostic_rows)

selected_trade_panel = (
    pd.concat(selected_trade_frames, ignore_index=True)
    if selected_trade_frames
    else pd.DataFrame()
)

# Attach candidate parameters.
summary_overall = attach_candidate_parameters(summary_overall, grid_wide)
summary_by_bucket = attach_candidate_parameters(summary_by_bucket, grid_wide)
summary_by_tenor = attach_candidate_parameters(summary_by_tenor, grid_wide)
summary_by_year = attach_candidate_parameters(summary_by_year, grid_wide)
pass_diagnostics = attach_candidate_parameters(pass_diagnostics, grid_wide)

# Sort outputs.
if not summary_overall.empty:
    summary_overall = summary_overall.sort_values(
        ["selection_universe", PRIMARY_RANKING_METRIC, "profit_factor_pnl_per_day", "trades"],
        ascending=[True, False, False, False],
    ).reset_index(drop=True)

if not summary_by_bucket.empty:
    summary_by_bucket = summary_by_bucket.sort_values(
        ["selection_universe", "candidate_id", "tenor_bucket_order"],
    ).reset_index(drop=True)

if not summary_by_tenor.empty:
    summary_by_tenor = summary_by_tenor.sort_values(
        ["selection_universe", "candidate_id", "tenor"],
    ).reset_index(drop=True)

if not summary_by_year.empty:
    summary_by_year = summary_by_year.sort_values(
        ["selection_universe", "candidate_id", "year"],
    ).reset_index(drop=True)

elapsed_seconds = time.time() - start_time

# ======================================================================================
# 4. Direct comparison table
# ======================================================================================

primary = summary_overall[
    summary_overall["selection_universe"].eq("one_trade_per_bucket_per_date_best_rank")
].copy()

primary = primary.sort_values(
    ["avg_pnl_per_day", "profit_factor_pnl_per_day", "trades"],
    ascending=[False, False, False],
).reset_index(drop=True)

primary.insert(0, "comparison_rank", np.arange(1, len(primary) + 1))

baseline_ex9d = primary[primary["candidate_subfamily"].eq("front_ex_9d")].copy()

comparison_rows = []

if not baseline_ex9d.empty:
    base = baseline_ex9d.iloc[0]

    for _, row in primary.iterrows():
        comparison_rows.append({
            "candidate_id": row["candidate_id"],
            "candidate_subfamily": row["candidate_subfamily"],
            "front_9d_include": row["front_9d_include"],
            "front_9d_forecast_vol_pct_min": row["front_9d_forecast_vol_pct_min"],
            "trades": row["trades"],
            "avg_pnl_per_day": row["avg_pnl_per_day"],
            "total_pnl": row["total_pnl"],
            "profit_factor": row["profit_factor"],
            "profit_factor_pnl_per_day": row["profit_factor_pnl_per_day"],
            "pnl_per_day_drawdown": row["pnl_per_day_drawdown"],
            "worst_20_trade_pnl_per_day_sum": row["worst_20_trade_pnl_per_day_sum"],
            "avg_pnl_per_day_2025": row["avg_pnl_per_day_2025"],
            "avg_pnl_per_day_2026": row["avg_pnl_per_day_2026"],
            "trades_le_neg_100k": row["trades_le_neg_100k"],

            "delta_vs_ex9d_trades": row["trades"] - base["trades"],
            "delta_vs_ex9d_avg_pnl_per_day": row["avg_pnl_per_day"] - base["avg_pnl_per_day"],
            "delta_vs_ex9d_total_pnl": row["total_pnl"] - base["total_pnl"],
            "delta_vs_ex9d_profit_factor": row["profit_factor"] - base["profit_factor"],
            "delta_vs_ex9d_pnl_per_day_drawdown": row["pnl_per_day_drawdown"] - base["pnl_per_day_drawdown"],
            "delta_vs_ex9d_worst_20_trade_pnl_per_day_sum": row["worst_20_trade_pnl_per_day_sum"] - base["worst_20_trade_pnl_per_day_sum"],
            "delta_vs_ex9d_avg_pnl_per_day_2025": row["avg_pnl_per_day_2025"] - base["avg_pnl_per_day_2025"],
            "delta_vs_ex9d_avg_pnl_per_day_2026": row["avg_pnl_per_day_2026"] - base["avg_pnl_per_day_2026"],
        })

comparison_table = pd.DataFrame(comparison_rows)

if not comparison_table.empty:
    comparison_table = comparison_table.sort_values(
        ["avg_pnl_per_day", "profit_factor_pnl_per_day", "trades"],
        ascending=[False, False, False],
    ).reset_index(drop=True)

# ======================================================================================
# 5. Save outputs
# ======================================================================================

candidate_summary_path = OUT_AUDIT_DIR / f"10_core_front_9d_rule_sweep_candidate_summary_{CELL12_TIMESTAMP}.csv"
by_bucket_path = OUT_AUDIT_DIR / f"10_core_front_9d_rule_sweep_by_bucket_{CELL12_TIMESTAMP}.csv"
by_tenor_path = OUT_AUDIT_DIR / f"10_core_front_9d_rule_sweep_by_tenor_{CELL12_TIMESTAMP}.csv"
by_year_path = OUT_AUDIT_DIR / f"10_core_front_9d_rule_sweep_by_year_{CELL12_TIMESTAMP}.csv"
pass_diagnostics_path = OUT_AUDIT_DIR / f"10_core_front_9d_rule_sweep_candidate_pass_diagnostics_{CELL12_TIMESTAMP}.csv"
comparison_path = OUT_AUDIT_DIR / f"10_core_front_9d_rule_sweep_ex9d_vs_conditional_comparison_{CELL12_TIMESTAMP}.csv"
selected_trade_panel_path = OUT_PROCESSED_DIR / f"10_core_front_9d_rule_sweep_selected_trade_panel_{CELL12_TIMESTAMP}.parquet"
validation_path = OUT_AUDIT_DIR / f"10_core_front_9d_rule_sweep_validation_{CELL12_TIMESTAMP}.csv"
manifest_path = OUT_AUDIT_DIR / f"10_core_front_9d_rule_sweep_manifest_{CELL12_TIMESTAMP}.json"

summary_overall.to_csv(candidate_summary_path, index=False)
summary_by_bucket.to_csv(by_bucket_path, index=False)
summary_by_tenor.to_csv(by_tenor_path, index=False)
summary_by_year.to_csv(by_year_path, index=False)
pass_diagnostics.to_csv(pass_diagnostics_path, index=False)
comparison_table.to_csv(comparison_path, index=False)
selected_trade_panel.to_parquet(selected_trade_panel_path, index=False)

# ======================================================================================
# 6. Validation
# ======================================================================================

validation_rows = []

def add_validation(check, status, detail):
    validation_rows.append({
        "check": check,
        "status": status,
        "detail": detail,
    })

models_found = sorted(signal["model_spec"].dropna().unique().tolist())

expected_candidate_count = 4
actual_candidate_count = len(candidate_ids)

expected_overall_rows = actual_candidate_count * len(SELECTION_UNIVERSES)
actual_overall_rows = len(summary_overall)

selection_universes_found = sorted(summary_overall["selection_universe"].dropna().unique().tolist())

bad_long_grid_candidate_tenors = (
    grid_long
    .groupby("candidate_id")["tenor"]
    .apply(lambda x: sorted(set(ALL_TENORS) - set(x.tolist())))
    .reset_index(name="missing_tenors")
)
bad_long_grid_candidate_tenors = bad_long_grid_candidate_tenors[
    bad_long_grid_candidate_tenors["missing_tenors"].apply(len).gt(0)
]

bad_ex9d_inclusion = grid_long[
    grid_long["candidate_subfamily"].eq("front_ex_9d")
    & grid_long["tenor"].eq(9)
    & grid_long["include_tenor"].astype(bool)
]

conditional_9d_floors_found = sorted(
    grid_long[
        grid_long["candidate_subfamily"].eq("front_conditional_9d")
        & grid_long["tenor"].eq(9)
    ]["forecast_vol_pct_min"].dropna().unique().tolist()
)

bad_pnl_day = signal[
    signal["normalized_pnl_dollars"].notna()
    & signal["normalized_pnl_per_day"].notna()
    & (
        (
            signal["normalized_pnl_dollars"] / signal["tenor"].replace(0, np.nan)
        )
        - signal["normalized_pnl_per_day"]
    ).abs().gt(1e-8)
]

add_validation(
    "signal_panel_loaded",
    "PASS" if len(signal) > 0 else "FAIL",
    f"rows={len(signal):,}; path={signal_panel_path}",
)

add_validation(
    "locked_model_only",
    "PASS" if models_found == [LOCKED_MODEL_SPEC] else "FAIL",
    f"models_found={models_found}",
)

add_validation(
    "candidate_grid_loaded",
    "PASS" if actual_candidate_count == expected_candidate_count else "FAIL",
    f"candidate_count={actual_candidate_count:,}; expected={expected_candidate_count:,}",
)

add_validation(
    "long_grid_has_all_tenors_per_candidate",
    "PASS" if bad_long_grid_candidate_tenors.empty else "FAIL",
    f"bad_candidates={len(bad_long_grid_candidate_tenors):,}",
)

add_validation(
    "front_ex_9d_candidate_excludes_9d",
    "PASS" if bad_ex9d_inclusion.empty else "FAIL",
    f"bad_rows={len(bad_ex9d_inclusion):,}",
)

add_validation(
    "conditional_9d_floors_present",
    "PASS" if conditional_9d_floors_found == [16.0, 18.0, 20.0] else "FAIL",
    f"found={conditional_9d_floors_found}",
)

add_validation(
    "normalized_pnl_per_day_formula",
    "PASS" if bad_pnl_day.empty else "FAIL",
    f"bad_rows={len(bad_pnl_day):,}",
)

add_validation(
    "overall_summary_rows_complete",
    "PASS" if actual_overall_rows == expected_overall_rows else "FAIL",
    f"actual={actual_overall_rows:,}; expected={expected_overall_rows:,}",
)

add_validation(
    "all_selection_universes_evaluated",
    "PASS" if selection_universes_found == sorted(SELECTION_UNIVERSES) else "FAIL",
    f"found={selection_universes_found}",
)

add_validation(
    "selected_trade_panel_saved",
    "PASS" if len(selected_trade_panel) > 0 else "WARN",
    f"rows={len(selected_trade_panel):,}; path={selected_trade_panel_path}",
)

add_validation(
    "pass_diagnostics_created",
    "PASS" if len(pass_diagnostics) == actual_candidate_count else "FAIL",
    f"rows={len(pass_diagnostics):,}; expected={actual_candidate_count:,}",
)

add_validation(
    "comparison_table_created",
    "PASS" if not comparison_table.empty else "WARN",
    f"rows={len(comparison_table):,}; path={comparison_path}",
)

add_validation(
    "no_broad_optimization",
    "PASS",
    "Only four Cell 11 9D-rule candidates evaluated.",
)

add_validation(
    "no_final_candidate_selection",
    "PASS",
    "Cell 12 is a focused comparison sweep only.",
)

add_validation(
    "no_secondary",
    "PASS",
    "Core only.",
)

add_validation(
    "no_sizing_changes",
    "PASS",
    "No sizing fields changed.",
)

add_validation(
    "no_production_lock",
    "PASS",
    "No production threshold lock performed.",
)

validation = pd.DataFrame(validation_rows)
validation.to_csv(validation_path, index=False)

failures = validation[validation["status"] == "FAIL"]

manifest = {
    "notebook": "07_unified_fds_core_signal_threshold_research_v1.ipynb",
    "cell": "Cell 12 — 9D-specific Front rule sweep",
    "timestamp": CELL12_TIMESTAMP,
    "elapsed_seconds": elapsed_seconds,
    "locked_model_spec": LOCKED_MODEL_SPEC,
    "candidate_family": CANDIDATE_FAMILY,
    "signal_panel_path": str(signal_panel_path),
    "candidate_grid_wide_path": str(candidate_grid_wide_path),
    "candidate_grid_long_path": str(candidate_grid_long_path),
    "candidate_count": int(actual_candidate_count),
    "selection_universes": SELECTION_UNIVERSES,
    "primary_ranking_metric": PRIMARY_RANKING_METRIC,
    "candidate_summary_path": str(candidate_summary_path),
    "by_bucket_path": str(by_bucket_path),
    "by_tenor_path": str(by_tenor_path),
    "by_year_path": str(by_year_path),
    "pass_diagnostics_path": str(pass_diagnostics_path),
    "comparison_path": str(comparison_path),
    "selected_trade_panel_path": str(selected_trade_panel_path),
    "validation_path": str(validation_path),
    "notes": [
        "Focused 9D-rule sweep only.",
        "No broad threshold optimization.",
        "No final threshold selected.",
        "No Secondary.",
        "No sizing changes.",
        "No production lock.",
        "The key comparison is front_ex_9d versus front_conditional_9d with 9D forecast-vol floors 16.0, 18.0, and 20.0.",
    ],
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2, default=str)

if not failures.empty:
    display(validation)
    raise RuntimeError("Cell 12 validation failed. Review validation output above.")

# ======================================================================================
# 7. Display concise review
# ======================================================================================

print("=" * 100)
print("Cell 12 — 9D-specific Front rule sweep")
print("=" * 100)
print(f"Signal panel:                  {signal_panel_path}")
print(f"Wide candidate grid:           {candidate_grid_wide_path}")
print(f"Long candidate grid:           {candidate_grid_long_path}")
print(f"Candidates evaluated:          {actual_candidate_count:,}")
print(f"Overall summary rows:          {len(summary_overall):,}")
print(f"By-bucket rows:                {len(summary_by_bucket):,}")
print(f"By-tenor rows:                 {len(summary_by_tenor):,}")
print(f"By-year rows:                  {len(summary_by_year):,}")
print(f"Pass diagnostic rows:          {len(pass_diagnostics):,}")
print(f"Selected trade panel rows:     {len(selected_trade_panel):,}")
print(f"Elapsed seconds:               {elapsed_seconds:,.1f}")
print(f"Primary ranking metric:        {PRIMARY_RANKING_METRIC}")
print("No broad optimization:         True")
print("No final candidate selection:  True")
print("No Secondary:                  True")
print("No sizing changes:             True")
print("No production lock:            True")

print()
print("Validation:")
display(validation)

main_display_cols = [
    "comparison_rank",
    "candidate_id",
    "candidate_subfamily",
    "front_9d_include",
    "front_9d_forecast_vol_pct_min",
    "trades",
    "unique_trade_dates",
    "avg_tenor",
    "win_rate",
    "total_pnl",
    "profit_factor",
    "profit_factor_pnl_per_day",
    "avg_pnl_per_day",
    "median_pnl_per_day",
    "worst_trade_pnl_per_day",
    "pnl_per_day_drawdown",
    "worst_20_trade_pnl_per_day_sum",
    "trades_le_neg_100k",
    "avg_pnl_per_day_2025",
    "avg_pnl_per_day_2026",
    "delta_vs_ex9d_trades",
    "delta_vs_ex9d_avg_pnl_per_day",
    "delta_vs_ex9d_total_pnl",
    "delta_vs_ex9d_profit_factor",
    "delta_vs_ex9d_pnl_per_day_drawdown",
    "delta_vs_ex9d_avg_pnl_per_day_2026",
]

print()
print("Direct comparison — one trade per bucket/date:")
display(comparison_table[[c for c in main_display_cols if c in comparison_table.columns]])

top_display_cols = [
    "candidate_id",
    "candidate_subfamily",
    "selection_universe",
    "front_9d_include",
    "front_9d_forecast_vol_pct_min",
    "trades",
    "unique_trade_dates",
    "avg_tenor",
    "win_rate",
    "total_pnl",
    "profit_factor",
    "avg_pnl_per_day",
    "median_pnl_per_day",
    "pnl_per_day_drawdown",
    "worst_20_trade_pnl_per_day_sum",
    "trades_le_neg_100k",
    "avg_pnl_per_day_2025",
    "avg_pnl_per_day_2026",
]

print()
print("Candidate summary — all selection universes:")
display(summary_overall[[c for c in top_display_cols if c in summary_overall.columns]])

print()
print("By-bucket detail:")
display(summary_by_bucket)

print()
print("By-tenor detail:")
display(summary_by_tenor)

print()
print("By-year detail:")
display(summary_by_year)

print()
print("Pass diagnostics:")
pass_diag_cols = [
    "candidate_id",
    "candidate_subfamily",
    "pass_rows_all_dates",
    "pass_rows_with_outcomes",
    "Front_pass_rows_with_outcomes",
    "Middle_pass_rows_with_outcomes",
    "Back_pass_rows_with_outcomes",
    "tenor_9_included",
    "tenor_9_pass_rows_with_outcomes",
    "tenor_12_pass_rows_with_outcomes",
    "tenor_15_pass_rows_with_outcomes",
    "front_9d_forecast_vol_pct_min",
]
display(pass_diagnostics[[c for c in pass_diag_cols if c in pass_diagnostics.columns]])

print()
print("Saved outputs:")
for p in [
    candidate_summary_path,
    by_bucket_path,
    by_tenor_path,
    by_year_path,
    pass_diagnostics_path,
    comparison_path,
    selected_trade_panel_path,
    validation_path,
    manifest_path,
]:
    print(f"  {p}")

print("\nCELL 12 PASSED")

====================================================================================================
Cell 12 — 9D-specific Front rule sweep
====================================================================================================
Signal panel:             C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\01_unified_fds_signal_base_panel_20200102_20260701_20260704_211636.parquet
Wide candidate grid:      C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_wide_20260704_221815.parquet
Long candidate grid:      C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_long_20260704_221815.parquet
Candidates to evaluate:   4
Selection universes:      ['all_qualified_trades', 'one_trade_per_bucket_per_date_best_rank', 'one_trade_per_date_best_rank']
Primary metric:           avg_pnl_per_day

  Evaluated 1 / 4: core_front_9d_rule_0001
  Evaluated 2 / 4: core_front_9d_rule_0002
  Evaluated 3 / 4: core_front_9d_rule_0003
  Evaluated 4 / 4: core_front_9d_rule_0004
====================================================================================================
Cell 12 — 9D-specific Front rule sweep
====================================================================================================
Signal panel:                  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\01_unified_fds_signal_base_panel_20200102_20260701_20260704_211636.parquet
Wide candidate grid:           C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_wide_20260704_221815.parquet
Long candidate grid:           C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\09_core_front_9d_rule_candidate_grid_long_20260704_221815.parquet
Candidates evaluated:          4
Overall summary rows:          12
By-bucket rows:                36
By-tenor rows:                 105
By-year rows:                  72
Pass diagnostic rows:          4
Selected trade panel rows:     6,831
Elapsed seconds:               2.3
Primary ranking metric:        avg_pnl_per_day
No broad optimization:         True
No final candidate selection:  True
No Secondary:                  True
No sizing changes:             True
No production lock:            True

Validation:

                                     check status                                             detail
0                      signal_panel_loaded   PASS  rows=14,688; path=C:\Users\patri\vrp_project\d...
1                        locked_model_only   PASS         models_found=['unified_fds_no_min_return']
2                    candidate_grid_loaded   PASS                      candidate_count=4; expected=4
3   long_grid_has_all_tenors_per_candidate   PASS                                   bad_candidates=0
4        front_ex_9d_candidate_excludes_9d   PASS                                         bad_rows=0
5            conditional_9d_floors_present   PASS                           found=[16.0, 18.0, 20.0]
6           normalized_pnl_per_day_formula   PASS                                         bad_rows=0
7            overall_summary_rows_complete   PASS                             actual=12; expected=12
8        all_selection_universes_evaluated   PASS  found=['all_qualified_trades', 'one_trade_per_...
9               selected_trade_panel_saved   PASS  rows=6,831; path=C:\Users\patri\vrp_project\da...
10                pass_diagnostics_created   PASS                                 rows=4; expected=4
11                comparison_table_created   PASS  rows=4; path=C:\Users\patri\vrp_project\data\a...
12                   no_broad_optimization   PASS    Only four Cell 11 9D-rule candidates evaluated.
13            no_final_candidate_selection   PASS        Cell 12 is a focused comparison sweep only.
14                            no_secondary   PASS                                         Core only.
15                       no_sizing_changes   PASS                          No sizing fields changed.
16                      no_production_lock   PASS            No production threshold lock performed.

Direct comparison — one trade per bucket/date:

,candidate_id,candidate_subfamily,front_9d_include,front_9d_forecast_vol_pct_min,trades,total_pnl,profit_factor,profit_factor_pnl_per_day,avg_pnl_per_day,pnl_per_day_drawdown,worst_20_trade_pnl_per_day_sum,trades_le_neg_100k,avg_pnl_per_day_2025,avg_pnl_per_day_2026,delta_vs_ex9d_trades,delta_vs_ex9d_avg_pnl_per_day,delta_vs_ex9d_total_pnl,delta_vs_ex9d_profit_factor,delta_vs_ex9d_pnl_per_day_drawdown,delta_vs_ex9d_avg_pnl_per_day_2026
0,core_front_9d_rule_0004,front_conditional_9d,True,20.0,420,5.745171e+06,4.266415,3.583912,604.785125,-29677.448469,-23715.163620,2,651.802316,66.164231,0,5.434511,-20799.372769,-0.011825,0.0,0.000000
1,core_front_9d_rule_0001,front_ex_9d,False,NaN,420,5.765970e+06,4.278241,3.560693,599.350614,-29677.448469,-23715.163620,2,639.354946,66.164231,0,0.000000,0.000000,0.000000,0.0,0.000000
2,core_front_9d_rule_0003,front_conditional_9d,True,18.0,421,5.609588e+06,4.055074,3.215378,574.513452,-29677.448469,-24889.323006,2,651.802316,66.164231,1,-24.837163,-156382.139908,-0.223167,0.0,0.000000
3,core_front_9d_rule_0002,front_conditional_9d,True,16.0,425,5.522829e+06,3.951584,3.050389,558.471372,-29677.448469,-24889.323006,2,652.290375,74.509040,5,-40.879242,-243141.315638,-0.326656,0.0,8.344809

Candidate summary — all selection universes:

               candidate_id   candidate_subfamily                       selection_universe  front_9d_include  front_9d_forecast_vol_pct_min  trades  unique_trade_dates  avg_tenor  win_rate     total_pnl  profit_factor  avg_pnl_per_day  median_pnl_per_day  pnl_per_day_drawdown  worst_20_trade_pnl_per_day_sum  trades_le_neg_100k  avg_pnl_per_day_2025  avg_pnl_per_day_2026
0   core_front_9d_rule_0004  front_conditional_9d                     all_qualified_trades              True                           20.0    1075                 190  23.173953  0.870698  1.517774e+07       4.540601       637.859996          892.830365         -75606.722483                   -51948.701006                   5            667.022760            118.221316
1   core_front_9d_rule_0003  front_conditional_9d                     all_qualified_trades              True                           18.0    1101                 191  22.839237  0.866485  1.532532e+07       4.439643       637.690786          897.199587         -75606.722483                   -56329.963714                   5            667.022760            127.366685
2   core_front_9d_rule_0002  front_conditional_9d                     all_qualified_trades              True                           16.0    1139                 195  22.377524  0.861282  1.547100e+07       4.296236       630.626837          900.180955         -75606.722483                   -56329.963714                   5            644.735004            136.615783
3   core_front_9d_rule_0001           front_ex_9d                     all_qualified_trades             False                            NaN    1064                 190  23.320489  0.869361  1.495983e+07       4.489767       621.698593          890.768149         -75606.722483                   -51948.701006                   5            634.541843            118.221316
4   core_front_9d_rule_0004  front_conditional_9d  one_trade_per_bucket_per_date_best_rank              True                           20.0     420                 190  22.600000  0.869048  5.745171e+06       4.266415       604.785125          890.768149         -29677.448469                   -23715.163620                   2            651.802316             66.164231
5   core_front_9d_rule_0001           front_ex_9d  one_trade_per_bucket_per_date_best_rank             False                            NaN     420                 190  22.657143  0.869048  5.765970e+06       4.278241       599.350614          889.922941         -29677.448469                   -23715.163620                   2            639.354946             66.164231
6   core_front_9d_rule_0003  front_conditional_9d  one_trade_per_bucket_per_date_best_rank              True                           18.0     421                 191  22.475059  0.862233  5.609588e+06       4.055074       574.513452          889.707640         -29677.448469                   -24889.323006                   2            651.802316             66.164231
7   core_front_9d_rule_0002  front_conditional_9d  one_trade_per_bucket_per_date_best_rank              True                           16.0     425                 195  22.235294  0.856471  5.522829e+06       3.951584       558.471372          881.455029         -29677.448469                   -24889.323006                   2            652.290375             74.509040
8   core_front_9d_rule_0004  front_conditional_9d             one_trade_per_date_best_rank              True                           20.0     190                 190  24.284211  0.857895  2.536242e+06       3.946970       454.641629          813.642371         -15408.255776                   -12325.363096                   1            478.938805           -127.858733
9   core_front_9d_rule_0001           front_ex_9d             one_trade_per_date_best_rank             False                            NaN     190                 190  24.315789  0.857895  2.536242e+06       3.946970       448.221148          813.642371         -15408.255776                   -12325.363096                   1            456.938804           -127.858733
10  core_front_9d_rule_0002  front_conditional_9d             one_trade_per_date_best_rank              True                           16.0     195                 195  23.507692  0.846154  2.426784e+06       3.582883       396.241191          799.105682         -21450.298331                   -13263.377040                   1            477.473890           -127.858733
11  core_front_9d_rule_0003  front_conditional_9d             one_trade_per_date_best_rank              True                           18.0     191                 191  24.109948  0.848168  2.444237e+06       3.622153       394.444393          799.105682         -19401.612529                   -13263.377040                   1            478.938805           -127.858733

By-bucket detail:

,candidate_id,selection_universe,tenor_bucket,tenor_bucket_order,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,candidate_family,candidate_subfamily,candidate_description,front_9d_include,front_9d_rule_type,front_9d_model_vrp_log,front_9d_model_vrp_z,front_9d_RSI14_max,front_9d_forecast_vol_pct_min,front_12_15_model_vrp_log,front_12_15_model_vrp_z,front_12_15_RSI14_max,front_12_15_forecast_vol_pct_min,middle_model_vrp_log,middle_model_vrp_z,middle_RSI14_max,middle_forecast_vol_pct_min,back_model_vrp_log,back_model_vrp_z,back_RSI14_max,back_forecast_vol_pct_min
0,core_front_9d_rule_0001,all_qualified_trades,Front,1,209,114,2021-11-26,2026-04-06,12,15,13.464115,0.837321,2.310634e+06,11055.663803,17567.102335,-108475.796818,38031.055016,3.590672,-2.465998e+05,-226971.628112,-153136.609478,-47612.232253,5,1,0,169726.132544,812.086759,1311.298419,-7782.261885,2839.785902,3.474356,-19521.636249,-18029.536635,-11642.314572,-3496.317907,25,3.335604e+05,982.778347,-53165.507841,29,173318.912565,435.314707,-34533.046342,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
1,core_front_9d_rule_0001,all_qualified_trades,Middle,2,406,149,2021-11-24,2026-04-29,18,24,21.007389,0.839901,4.845991e+06,11935.937517,19418.611704,-108475.796818,42988.137121,3.566524,-1.100582e+06,-387844.309642,-519811.154884,-804340.738820,8,2,0,232163.747591,571.831891,937.303166,-6026.433157,2112.836390,3.561390,-53372.354016,-19045.459664,-24693.231746,-38674.703212,56,9.269282e+05,788.132901,-6858.911357,87,-197855.418348,-119.515967,-57319.352129,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
2,core_front_9d_rule_0001,all_qualified_trades,Back,3,449,157,2021-11-24,2026-04-29,27,33,30.000000,0.910913,7.803207e+06,17379.079724,22206.045183,-103670.923339,45095.398744,6.178966,-6.618667e+05,-385819.395957,-468035.087509,-642205.608403,9,2,0,259597.422898,578.167980,749.380192,-3455.697445,1592.153227,6.050604,-22592.617567,-12930.040209,-15890.033520,-21944.652890,111,1.595182e+06,478.622817,-92588.332880,84,659221.666545,254.976498,-59939.127377,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
3,core_front_9d_rule_0002,all_qualified_trades,Front,1,284,119,2021-11-26,2026-04-06,9,15,12.285211,0.813380,2.821804e+06,9935.928565,17058.567271,-108475.796818,38031.055016,3.172839,-3.381117e+05,-338111.703095,-244384.313764,-202252.531937,7,1,0,226522.796715,797.615481,1393.571853,-10167.991854,3786.381203,2.990704,-29689.628103,-29689.628103,-22096.382339,-16952.361123,34,4.033978e+05,950.857666,-53165.507841,33,211347.120624,510.590393,-34533.046342,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 16.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,16.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
4,core_front_9d_rule_0002,all_qualified_trades,Middle,2,406,149,2021-11-24,2026-04-29,18,24,21.007389,0.839901,4.845991e+06,11935.937517,19418.611704,-108475.796818,42988.137121,3.566524,-1.100582e+06,-387844.309642,-519811.154884,-804340.738820,8,2,0,232163.747591,571.831891,937.303166,-6026.433157,2112.836390,3.561390,-53372.354016,-19045.459664,-24693.231746,-38674.703212,56,9.269282e+05,788.132901,-6858.911357,87,-197855.418348,-119.515967,-57319.352129,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 16.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,16.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
5,core_front_9d_rule_0002,all_qualified_trades,Back,3,449,157,2021-11-24,2026-04-29,27,33,30.000000,0.910913,7.803207e+06,17379.079724,22206.045183,-103670.923339,45095.398744,6.178966,-6.618667e+05,-385819.395957,-468035.087509,-642205.608403,9,2,0,259597.422898,578.167980,749.380192,-3455.697445,1592.153227,6.050604,-22592.617567,-12930.040209,-15890.033520,-21944.652890,111,1.595182e+06,478.622817,-92588.332880,84,659221.666545,254.976498,-59939.127377,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 16.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,16.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
6,core_front_9d_rule_0003,all_qualified_trades,Front,1,246,115,2021-11-26,2026-04-06,9,15,12.792683,0.829268,2.676126e+06,10878.561017,17555.424650,-108475.796818,38031.055016,3.523140,-2.517484e+05,-227537.680322,-213508.932771,-202252.531937,6,1,0,210336.385365,855.025957,1373.461654,-7782.261885,3786.381203,3.408204,-22931.992614,-18311.640069,-16334.633142,-16952.361123,27,4.016939e+05,1190.364451,-53165.507841,30,190926.877608,486.018902,-34533.046342,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 18.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,18.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
7,core_front_9d_rule_0003,all_qualified_trades,Middle,2,406,149,2021-11-24,2026-04-29,18,24,21.007389,0.839901,4.845991e+06,11935.937517,19418.611704,-108475.796818,42988.137121,3.566524,-1.100582e+06,-387844.309642,-519811.154884,-804340.738820,8,2,0,232163.747591,571.831891,937.303166,-6026.433157,2112.836390,3.561390,-53372.354016,-19045.459664,-24693.231746,-38674.703212,56,9.269282e+05,788.132901,-6858.911357,87,-197855.418348,-119.515967,-57319.352129,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 18.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,18.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
8,core_front_9d_rule_0003,all_qualified_trades,Back,3,449,157,2021-11-24,2026-04-29,27,33,30.000000,0.910913,7.803207e+06,17379.079724,22206.045183,-103670.923339,45095.398744,6.178966,-6.618667e+05,-385819.395957,-468035.087509,-642205.608403,9,2,0,259597.422898,578.167980,749.380192,-3455.697445,1592.153227,6.050604,-22592.617567,-12930.040209,-15890.033520,-21944.652890,111,1.595182e+06,478.622817,-92588.332880,84,659221.666545,254.976498,-59939.127377,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 18.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,18.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
9,core_front_9d_rule_0004,all_qualified_trades,Front,1,220,114,2021-11-26,2026-04-06,9,15,13.240909,0.845455,2.528543e+06,11493.379413,17587.533689,-108475.796818,38031.055016,3.834991,-2.465998e+05,-226971.628112,-153136.609478,-53361.141286,5,1,0,193938.325440,881.537843,1347.652244,-7782.261885,3786.381203,3.827334,-19521.636249,-18029.536635,-11642.314572,-2368.313553,27,4.016939e+05,1190.364451,-53165.507841,29,173318.912565,435.314707,-34533.046342,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
10,core_front_9d_rule_0004,all_qualified_trades,Middle,2,406,149,2021-11-24,2026-04-29,18,24,21.007389,0.839901,4.845991e+06,11935.937517,19418.611704,-108475.796818,42988.137121,3.566524,-1.100582e+06,-387844.309642,-519811.154884,-804340.738820,8,2,0,232163.747591,571.831891,937.303166,-6026.433157,2112.836390,3.561390,-53372.354016,-19045.459664,-24693.231746,-38674.703212,56,9.269282e+05,788.132901,-6858.911357,87,-197855.418348,-119.515967,-57319.352129,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
11,core_front_9d_rule_0004,all_qualified_trades,Back,3,449,157,2021-11-24,2026-04-29,27,33,30.000000,0.910913,7.803207e+06,17379.079724,22206.045183,-103670.923339,45095.398744,6.178966,-6.618667e+05,-385819.395957,-468035.087509,-642205.608403,9,2,0,259597.422898,578.167980,749.380192,-3455.697445,1592.153227,6.050604,-22592.617567,-12930.040209,-15890.033520,-21944.652890,111,1.595182e+06,478.622817,-92588.332880,84,659221.666545,254.976498,-59939.127377,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
12,core_front_9d_rule_0001,one_trade_per_bucket_per_date_best_rank,Front,1,114,114,2021-11-26,2026-04-06,12,15,13.921053,0.842105,1.182635e+06,10373.994454,17482.133127,-108475.796818,38031.055016,2.925833,-1.848991e+05,-155233.786408,-115031.525880,-107763.939183,5,1,0,80730.017868,708.158051,1303.733205,-7782.261885,2838.000230,2.693449,-15408.255776,-11442.031294,-8873.903973,-9007.476734,15,1.790538e+05,779.593856,-53165.507841,16,85069.510082,349.393890,-34533.046342,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
13,core_front_9d_rule_0001,one_trade_per_bucket_per_date_best_rank,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-3.885260e+05,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,3.648272e+05,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
14,core_front_9d_rule_0001,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-2.390255e+05,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,5.738815e+05,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
15,core_front_9d_rule_0002,one_trade_per_bucket_per_date_best_rank,Front,1,119,119,2021-11-26,2026-04-06,9,15,12.781513,0.798319,9.394941e+05,7894.908001,16458.138249,-108475.796818,38031.055016,2.293411,-2.372115e+05,-155233.786408,-237211.539967,-107763.939183,4,1,0,66353.092967,557.589017,1276.401763,-10167.991854,3784.000307,2.018837,-23764.781773,-13984.029258,-22503.256665,-12514.984416,15,1.917783e+05,845.133361,-40441.053294,16,85069.510082,387.988630,-34533.046342,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 16.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,16.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
16,core_front_9d_rule_0002,one_trade_per_bucket_per_date_best_rank,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-3.885260e+05,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,3.648272e+05,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 16.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,16.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
17,core_front_9d_rule_0002,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-2.390255e+05,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,5.738815e+05,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 16.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,16.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
18,core_front_9d_rule_0003,one_trade_per_bucket_per_date_best_rank,Front,1,115,115,2021-11-26,2026-04-06,9,15,13.330435,0.817391,1.026253e+06,8923.941112,17403.249421,-108475.796818,38031.055016,2.484347,-2.372115e+05,-155233.786408,-237211.539967,-107763.939183,5,1,0,70872.923031,616.286287,1287.297697,-7782.261885,3784.000307,2.210562,-22503.256665,-12634.345552,-22503.256665,-10435.868270,15,1.790538e+05,842.660528,-53165.507841,16,85069.510082,349.393890,-34533.046342,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 18.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,18.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
19,core_front_9d_rule_0003,one_trade_per_bucket_per_date_best_rank,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-3.885260e+05,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,3.648272e+05,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 18.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,18.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
20,core_front_9d_rule_0003,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-2.390255e+05,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,5.738815e+05,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 18.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,18.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
21,core_front_9d_rule_0004,one_trade_per_bucket_per_date_best_rank,Front,1,114,114,2021-11-26,2026-04-06,9,15,13.710526,0.842105,1.161836e+06,10191.543816,17465.522143,-108475.796818,38031.055016,2.891963,-1.848991e+05,-155233.786408,-115031.525880,-107763.939183,5,1,0,83012.512514,728.179934,1303.733205,-7782.261885,3784.000307,2.741328,-15408.255776,-11442.031294,-8873.903973,-9007.476734,15,1.790538e+05,842.660528,-53165.507841,16,85069.510082,349.393890,-34533.046342,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
22,core_front_9d_rule_0004,one_trade_per_bucket_per_date_best_rank,Middle,2,149,149,2021-11-24,2026-04-29,18,24,21.322148,0.845638,1.825242e+06,12249.945060,19054.854885,-108475.796818,42988.137121,3.754586,-3.885260e+05,-197285.561652,-358351.426266,-302908.024370,1,1,0,81267.167347,545.417231,941.415290,-6026.433157,1791.172380,3.391886,-20774.019539,-10696.956646,-19097.652002,-16788.785812,22,3.648272e+05,763.809249,6005.032657,29,-123708.761175,-275.810184,-45195.769858,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
23,core_front_9d_rule_0004,one_trade_per_bucket_per_date_best_rank,Back,3,157,157,2021-11-24,2026-04-29,27,33,30.267516,0.910828,2.758093e+06,17567.472859,22023.638806,-92579.572354,45095.398744,6.720384,-2.390255e+05,-239025.497756,-167625.769039,-28832.859354,1,0,0,89730.072738,571.529126,725.641743,-3428.873050,1503.179958,6.387187,-8575.316243,-8575.316243,-5791.962467,-791.493536,39,5.738815e+05,515.211913,-40557.495661,29,249470.923248,251.874007,-48751.416767,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
24,core_front_9d_rule_0001,one_trade_per_date_best_rank,Front,1,42,42,2021-11-26,2026-03-23,12,15,12.928571,0.666667,-2.023082e+04,-481.686136,15389.514922,-108475.796818,34056.002766,0.962735,-3.140602e+05,-165452.994772,-293576.904141,-149542.733283,5,1,0,-2841.814136,-67.662241,1163.016069,-7782.261885,2838.000230,0.933797,-24980.940878,-13179.666935,-23488.841264,-13620.311474,4,-1.321583e+04,-340.384148,-53165.507841,4,-49678.400997,-908.040955,-34533.046342,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
25,core_front_9d_rule_0001,one_trade_per_date_best_rank,Middle,2,55,55,2021-11-24,2026-04-29,18,24,20.727273,0.836364,5.961916e+05,10839.847759,14504.025393,-45195.769858,29527.318207,3.851793,-2.020599e+05,-171885.265941,-152167.856800,-24645.596165,0,0,0,26303.834188,478.251531,684.569927,-2510.876103,1341.882933,3.274580,-11225.548979,-9549.181441,-9146.714611,-2826.381656,14,2.068117e+05,699.931860,6898.478535,11,-135116.399952,-730.705831,-45195.769858,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
26,core_front_9d_rule_0001,one_trade_per_date_best_rank,Back,3,93,93,2022-01-20,2026-03-30,27,33,31.580645,0.956989,1.960281e+06,21078.291800,26220.014509,-41205.775564,45095.398744,19.038157,-4.120578e+04,5588.919045,73366.201823,182063.473532,0,0,0,61699.998060,663.440839,794.545894,-1248.659866,1503.179958,19.735828,-1248.659866,170.390764,2606.443229,6445.451874,25,3.292613e+05,448.434364,-40557.495661,15,258493.500287,522.277730,-24467.645896,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
27,core_front_9d_rule_0002,one_trade_per_date_best_rank,Front,1,50,50,2021-11-26,2026-03-23,9,15,11.460000,0.660000,-5.265506e+04,-1053.101102,13956.192831,-108475.796818,34056.002766,0.915323,-3.743581e+05,-256817.455322,-349487.101483,-312959.098926,4,1,0,-7227.173448,-144.543469,1220.638157,-10167.991854,3784.000307,0.874531,-36205.487202,-23714.126288,-33442.041479,-31205.316831,4,-4.913746e+02,-119.631973,-40441.053294,4,-49678.400997,-908.040955,-34533.046342,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 16.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,16.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5

By-tenor detail:

,candidate_id,selection_universe,tenor,tenor_bucket,tenor_bucket_order,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,candidate_family,candidate_subfamily,candidate_description,front_9d_include,front_9d_rule_type,front_9d_model_vrp_log,front_9d_model_vrp_z,front_9d_RSI14_max,front_9d_forecast_vol_pct_min,front_12_15_model_vrp_log,front_12_15_model_vrp_z,front_12_15_RSI14_max,front_12_15_forecast_vol_pct_min,middle_model_vrp_log,middle_model_vrp_z,middle_RSI14_max,middle_forecast_vol_pct_min,back_model_vrp_log,back_model_vrp_z,back_RSI14_max,back_forecast_vol_pct_min
0,core_front_9d_rule_0001,all_qualified_trades,12,Front,1,107,107,2021-11-26,2026-03-30,12,12,12.0,0.803738,9.410330e+05,8794.701060,16261.476461,-93387.142625,34077.430827,2.717140,-184899.069310,-133378.745874,-44891.999753,-46814.316307,4,0,0,78419.417789,732.891755,1355.123038,-7782.261885,2839.785902,2.717140,-15408.255776,-11114.895489,-3740.999979,-3901.193026,14,139925.763364,832.891449,-53165.507841,14,64171.939919,381.975833,-34533.046342,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
1,core_front_9d_rule_0001,all_qualified_trades,15,Front,1,102,102,2021-11-26,2026-04-06,15,15,15.0,0.872549,1.369601e+06,13427.458052,19533.657782,-108475.796818,38031.055016,4.982767,-144758.610519,-137432.633379,-45777.120699,62607.070637,1,1,0,91306.714755,895.163870,1302.243852,-7231.719788,2535.403668,4.982767,-9650.574035,-9162.175559,-3051.808047,4173.804709,11,193634.675957,1173.543491,6005.032657,15,109146.972646,485.097656,-25919.354017,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
2,core_front_9d_rule_0001,all_qualified_trades,18,Middle,2,136,136,2021-11-24,2026-04-29,18,18,18.0,0.845588,1.475143e+06,10846.640334,17482.133127,-108475.796818,38031.055016,3.507062,-388526.041944,-197285.561652,-358351.426266,-311461.162391,1,1,0,81952.393636,602.591130,971.229618,-6026.433157,2112.836390,3.507062,-21584.780108,-10960.308981,-19908.412570,-17303.397911,17,266370.737792,870.492607,6005.032657,29,-138442.807121,-265.216106,-45195.769858,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
3,core_front_9d_rule_0001,all_qualified_trades,21,Middle,2,133,133,2021-11-24,2026-04-29,21,21,21.0,0.834586,1.639575e+06,12327.628876,20221.414273,-108475.796818,42988.137121,3.571958,-355922.057117,-232923.170187,-336696.705037,-238955.001712,3,1,0,78074.982884,587.029946,962.924489,-5165.514134,2047.054149,3.571958,-16948.669387,-11091.579533,-16033.176430,-11378.809605,18,304725.379601,806.151798,-6858.911357,29,-38824.225026,-63.750780,-56809.083631,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
4,core_front_9d_rule_0001,all_qualified_trades,24,Middle,2,137,137,2021-11-24,2026-04-29,24,24,24.0,0.839416,1.731273e+06,12637.028509,20248.487481,-92579.572354,42988.137121,3.614121,-356133.708504,-250626.850425,-336908.356424,-238387.242084,4,0,0,72136.371071,526.542855,843.686978,-3857.482181,1791.172380,3.614121,-14838.904521,-10442.785434,-14037.848184,-9932.801754,21,355832.058718,706.015990,-6858.911357,29,-20588.386201,-29.581015,-57319.352129,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,core_front_9d_rule_0004,one_trade_per_date_best_rank,21,Middle,2,16,16,2022-07-08,2026-04-29,21,21,21.0,1.000000,2.889010e+05,18056.312904,17924.049911,10440.842371,28179.541598,inf,0.000000,77384.324038,163028.873713,288901.006462,0,0,0,13757.190784,859.824424,853.526186,497.182970,1341.882933,inf,0.000000,3684.967811,7763.279701,13757.190784,6,106781.777007,847.474421,10440.842371,4,66943.481667,796.946210,14372.163389,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
101,core_front_9d_rule_0004,one_trade_per_date_best_rank,24,Middle,2,17,17,2021-11-24,2025-11-20,24,24,24.0,0.941176,3.258042e+05,19164.950348,18058.670277,-3607.390045,29527.318207,91.315755,0.000000,65187.097259,160163.830969,325804.155909,0,0,0,13575.173163,798.539598,752.444595,-150.307919,1230.304925,91.315755,0.000000,2716.129052,6673.492957,13575.173163,4,60697.480864,632.265426,10805.456045,0,0.000000,NaN,NaN,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
102,core_front_9d_rule_0004,one_trade_per_date_best_rank,27,Back,3,18,18,2022-03-11,2025-10-09,27,27,27.0,1.000000,2.601399e+05,14452.214533,12605.164972,1573.629536,32071.631184,inf,0.000000,41606.154816,103595.613503,260139.861596,0,0,0,9634.809689,535.267205,466.857962,58.282575,1187.838192,inf,0.000000,1540.968697,3836.874574,9634.809689,14,153826.583563,406.948634,1573.629536,0,0.000000,NaN,NaN,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
103,core_front_9d_rule_0004,one_trade_per_date_best_rank,30,Back,3,8,8,2022-10-11,2026-03-06,30,30,30.0,1.000000,1.800994e+05,22512.425547,18272.036498,339.761603,45095.398744,inf,0.000000,97420.257682,180099.404378,180099.404378,0,0,0,6003.313479,750.414185,609.067883,11.325387,1503.179958,inf,0.000000,3247.341923,6003.313479,6003.313479,2,65134.060866,1085.567681,20038.662122,1,339.761603,11.325387,339.761603,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
104,core_front_9d_rule_0004,one_trade_per_date_best_rank,33,Back,3,67,67,2022-01-20,2026-03-30,33,33,33.0,0.940299,1.520042e+06,22687.192111,27847.148575,-41205.775564,35371.772564,14.987154,-41205.775564,13829.377661,107857.392947,257342.488542,0,0,0,46061.874892,687.490670,843.852987,-1248.659866,1071.871896,14.987154,-1248.659866,419.072050,3268.405847,7798.257229,9,110300.614882,371.382542,-40557.495661,14,258153.738684,558.774326,-24467.645896,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5

By-year detail:

,candidate_id,selection_universe,year,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,candidate_family,candidate_subfamily,candidate_description,front_9d_include,front_9d_rule_type,front_9d_model_vrp_log,front_9d_model_vrp_z,front_9d_RSI14_max,front_9d_forecast_vol_pct_min,front_12_15_model_vrp_log,front_12_15_model_vrp_z,front_12_15_RSI14_max,front_12_15_forecast_vol_pct_min,middle_model_vrp_log,middle_model_vrp_z,middle_RSI14_max,middle_forecast_vol_pct_min,back_model_vrp_log,back_model_vrp_z,back_RSI14_max,back_forecast_vol_pct_min
0,core_front_9d_rule_0001,all_qualified_trades,2021,29,5,2021-11-24,2021-12-06,12,33,21.931034,0.862069,5.285488e+05,18225.821619,21593.370395,-3607.390045,28384.414940,74.259174,-7.214780e+03,23541.623240,96227.046726,3.340393e+05,0,0,0,25003.349579,862.184468,998.702931,-171.780478,1527.694232,78.628843,-322.088397,760.081350,5548.209180,16561.573463,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
1,core_front_9d_rule_0001,all_qualified_trades,2022,521,80,2022-01-20,2022-12-12,12,33,22.554702,0.892514,9.178802e+06,17617.661731,24823.610979,-108475.796818,35371.772564,5.668845,-1.213894e+06,-510586.535163,-851762.028286,-1.119570e+06,10,5,0,409657.091558,786.290003,1066.055302,-7782.261885,1978.114770,4.931846,-55545.022099,-25710.022310,-40701.663776,-51948.701006,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
2,core_front_9d_rule_0001,all_qualified_trades,2023,21,8,2023-03-13,2023-10-19,12,30,17.285714,1.000000,3.925858e+05,18694.560080,18782.454977,12815.804660,23438.457453,inf,0.000000e+00,82494.078617,180160.932713,3.727453e+05,0,0,0,23890.298490,1137.633261,1123.411904,738.125423,1653.370542,inf,0.000000,4680.895783,9772.979516,22236.927949,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
3,core_front_9d_rule_0001,all_qualified_trades,2024,101,24,2024-08-02,2024-12-18,12,33,24.504950,0.940594,1.369539e+06,13559.789639,14743.901854,-12048.089968,28845.059994,26.535988,-2.409618e+04,19590.945161,71816.644756,1.691292e+05,0,0,0,57460.266310,568.913528,567.989641,-669.338332,1617.071545,21.277023,-1243.056901,382.442930,2033.985609,5488.362638,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
4,core_front_9d_rule_0001,all_qualified_trades,2025,192,43,2025-03-04,2025-11-20,12,33,25.265625,0.963542,2.855671e+06,14873.285925,14766.743116,-92588.332880,45095.398744,10.445328,-2.926175e+05,-285758.580619,-284321.767855,9.454786e+04,3,0,0,121832.033880,634.541843,661.260645,-4430.458987,2839.785902,9.960017,-12787.352083,-12460.737257,-12362.932080,7556.420941,192,2.855671e+06,634.541843,-92588.332880,0,0.000000,NaN,NaN,core_front_9d_rule_test,front_ex_9d,Exclude 9D from Core Front; use Front rule for...,False,excluded,0.7,0.65,68.0,NaN,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,core_front_9d_rule_0004,one_trade_per_date_best_rank,2022,80,80,2022-01-20,2022-12-12,12,33,25.275000,0.875000,1.395954e+06,17449.428122,27990.080453,-108475.796818,35371.772564,4.037250,-2.032432e+05,-203243.246113,-102046.681023,1.271079e+05,4,1,0,39805.381963,497.567275,956.842391,-7782.261885,1753.796831,2.163436,-15408.255776,-12884.419731,-10137.316884,-2352.722492,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
68,core_front_9d_rule_0004,one_trade_per_date_best_rank,2023,8,8,2023-03-13,2023-10-19,12,18,12.750000,1.000000,1.258567e+05,15732.089009,15747.692517,12815.804660,19840.446501,inf,0.000000e+00,73721.612770,125856.712074,1.258567e+05,0,0,0,10118.996628,1264.874578,1312.307710,738.125423,1653.370542,inf,0.000000,5774.405019,10118.996628,10118.996628,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
69,core_front_9d_rule_0004,one_trade_per_date_best_rank,2024,24,24,2024-08-02,2024-12-18,9,33,23.875000,1.000000,3.637083e+05,15154.512908,14721.382686,9860.085556,28845.059994,inf,0.000000e+00,63926.805679,133015.245012,2.933588e+05,0,0,0,16134.228748,672.259531,588.199965,520.807163,1161.157587,inf,0.000000,2667.516524,5469.947313,11956.166575,0,0.000000e+00,NaN,NaN,0,0.000000,NaN,NaN,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
70,core_front_9d_rule_0004,one_trade_per_date_best_rank,2025,43,43,2025-03-04,2025-11-20,9,33,25.046512,0.930233,5.228572e+05,12159.469037,12905.675307,-53165.507841,45095.398744,6.054574,-9.372300e+04,-24290.975840,72049.958797,2.207315e+05,1,0,0,20594.368632,478.938805,490.611603,-4430.458987,3784.000307,4.183340,-5659.474007,-1182.241562,3405.421992,8667.343599,43,5.228572e+05,478.938805,-53165.507841,0,0.000000,NaN,NaN,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5
71,core_front_9d_rule_0004,one_trade_per_date_best_rank,2026,30,30,2026-02-05,2026-04-29,12,33,25.200000,0.600000,7.369870e+04,2456.623311,14438.094391,-45195.769858,30382.251113,1.250705,-2.108649e+05,-133637.734923,-153217.135578,-1.413605e+05,0,0,0,-3835.762004,-127.858733,624.024686,-2877.753862,1276.401763,0.773696,-14430.351444,-6806.448761,-9561.165181,-12324.157650,0,0.000000e+00,NaN,NaN,30,73698.699338,-127.858733,-45195.769858,core_front_9d_rule_test,front_conditional_9d,Allow 9D only if 9D forecast vol > 20.0; use F...,True,conditional_higher_forecast_vol_floor,0.7,0.65,68.0,20.0,0.7,0.65,68.0,14.5,0.7,0.7,68.0,10.0,0.7,0.7,70.0,8.5

Pass diagnostics:

              candidate_id  pass_rows_all_dates  pass_rows_with_outcomes  Front_pass_rows_with_outcomes  Middle_pass_rows_with_outcomes  Back_pass_rows_with_outcomes  tenor_9_included  tenor_9_pass_rows_with_outcomes  tenor_12_pass_rows_with_outcomes  tenor_15_pass_rows_with_outcomes  front_9d_forecast_vol_pct_min
0  core_front_9d_rule_0001                 1064                     1064                            209                             406                           449             False                                0                               107                               102                            NaN
1  core_front_9d_rule_0002                 1139                     1139                            284                             406                           449              True                               75                               107                               102                           16.0
2  core_front_9d_rule_0003                 1101                     1101                            246                             406                           449              True                               37                               107                               102                           18.0
3  core_front_9d_rule_0004                 1075                     1075                            220                             406                           449              True                               11                               107                               102                           20.0

Saved outputs:
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\10_core_front_9d_rule_sweep_candidate_summary_20260704_222153.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\10_core_front_9d_rule_sweep_by_bucket_20260704_222153.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\10_core_front_9d_rule_sweep_by_tenor_20260704_222153.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\10_core_front_9d_rule_sweep_by_year_20260704_222153.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\10_core_front_9d_rule_sweep_candidate_pass_diagnostics_20260704_222153.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\10_core_front_9d_rule_sweep_ex9d_vs_conditional_comparison_20260704_222153.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\10_core_front_9d_rule_sweep_selected_trade_panel_20260704_222153.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\10_core_front_9d_rule_sweep_validation_20260704_222153.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\10_core_front_9d_rule_sweep_manifest_20260704_222153.json

CELL 12 PASSED

In [15]:
# ======================================================================================
# Cell 13 — Middle weakness diagnostic and candidate design
# ======================================================================================
#
# Objective:
#   With Front provisionally set from Cell 12, diagnose the remaining Middle weakness
#   and create a small Middle-focused candidate design for a later sweep.
#
# Provisional Front rule from Cell 12:
#   9D:
#       model_vrp_log > 0.70
#       model_vrp_z   > 0.65
#       RSI14         < 68
#       forecast vol  > 20.0
#
#   12D / 15D:
#       model_vrp_log > 0.70
#       model_vrp_z   > 0.65
#       RSI14         < 68
#       forecast vol  > 14.5
#
# Current Middle rule to diagnose:
#   18D / 21D / 24D:
#       model_vrp_log > 0.70
#       model_vrp_z   > 0.70
#       RSI14         < 68
#       forecast vol  > 10.0
#
# Fixed Back:
#   Back remains locked unchanged.
#
# Diagnostic questions:
#   1. Is Middle weakness concentrated in 18D, 21D, or 24D?
#   2. Is the Middle 2026 problem caused by low forecast vol, high RSI, weak VRP,
#      or all Middle tenors broadly?
#   3. What small Middle candidate set should be swept next?
#
# Candidate design only:
#   middle_rule_0001: current Middle rule
#   middle_rule_0002: Middle FV floor 11.5
#   middle_rule_0003: Middle FV floor 13.0
#   middle_rule_0004: Middle FV floor 14.5
#   middle_rule_0005: Middle RSI < 66
#   middle_rule_0006: Middle FV floor 13.0 and RSI < 66
#
# Important:
#   This cell does NOT sweep the new Middle candidates.
#   This cell does NOT select final thresholds.
#   This cell does NOT change sizing.
#   This cell does NOT lock production.
#   No Secondary.
# ======================================================================================

from pathlib import Path
from datetime import datetime
import json
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 280)
pd.set_option("display.width", 460)

# ======================================================================================
# 0. Fallback config
# ======================================================================================

if "PROJECT_ROOT" not in globals():
    PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

if "NEW_BRANCH" not in globals():
    NEW_BRANCH = "vrp_unified_fds_core_signal_threshold_research_v1"

if "OUT_PROCESSED_DIR" not in globals():
    OUT_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / NEW_BRANCH
    OUT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

if "OUT_AUDIT_DIR" not in globals():
    OUT_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / NEW_BRANCH
    OUT_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

CELL13_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

if "LOCKED_MODEL_SPEC" not in globals():
    LOCKED_MODEL_SPEC = "unified_fds_no_min_return"

if "ALL_TENORS" not in globals():
    ALL_TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

if "TENOR_BUCKET_MAP" not in globals():
    TENOR_BUCKET_MAP = {
        9: "Front",
        12: "Front",
        15: "Front",
        18: "Middle",
        21: "Middle",
        24: "Middle",
        27: "Back",
        30: "Back",
        33: "Back",
    }

if "BUCKET_ORDER_MAP" not in globals():
    BUCKET_ORDER_MAP = {
        "Front": 1,
        "Middle": 2,
        "Back": 3,
    }

if "LOCKED_BACK_CORE_THRESHOLDS" not in globals():
    LOCKED_BACK_CORE_THRESHOLDS = {
        "model_vrp_log": 0.70,
        "model_vrp_z_3m": 0.70,
        "model_vrp_z_1y": 0.70,
        "RSI14_max": 70.0,
        "forecast_vol_pct_min": 8.5,
    }

PROVISIONAL_FRONT_CANDIDATE_ID = "core_front_9d_rule_0004"
PRIMARY_SELECTION_UNIVERSE = "one_trade_per_bucket_per_date_best_rank"
ALL_QUALIFIED_UNIVERSE = "all_qualified_trades"

MIDDLE_CANDIDATE_FAMILY = "core_middle_rule_test"

# ======================================================================================
# 1. Helpers
# ======================================================================================

def latest_file(directory: Path, pattern: str, required: bool = True) -> Path | None:
    matches = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if matches:
        return matches[0]
    if required:
        raise FileNotFoundError(f"No file found in {directory} matching {pattern}")
    return None


def profit_factor_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").dropna()
    gross_profit = float(pnl[pnl > 0].sum())
    gross_loss = float(pnl[pnl < 0].sum())

    if gross_loss < 0:
        return gross_profit / abs(gross_loss)
    if gross_profit > 0:
        return np.inf
    return np.nan


def max_drawdown_from_pnl(pnl: pd.Series) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)

    if len(pnl) == 0:
        return np.nan

    cumulative = pnl.cumsum()
    running_max = cumulative.cummax()
    drawdown = cumulative - running_max

    return float(drawdown.min())


def worst_rolling_sum(pnl: pd.Series, window: int) -> float:
    pnl = pd.to_numeric(pnl, errors="coerce").fillna(0.0)

    if len(pnl) == 0:
        return np.nan

    if len(pnl) < window:
        return float(pnl.sum())

    return float(pnl.rolling(window=window, min_periods=window).sum().min())


def threshold_dict(model_vrp_log: float, model_vrp_z: float, rsi_max: float, forecast_vol_pct_min: float) -> dict:
    return {
        "model_vrp_log": float(model_vrp_log),
        "model_vrp_z": float(model_vrp_z),
        "model_vrp_z_3m": float(model_vrp_z),
        "model_vrp_z_1y": float(model_vrp_z),
        "RSI14_max": float(rsi_max),
        "forecast_vol_pct_min": float(forecast_vol_pct_min),
    }


def summarize_trades(df: pd.DataFrame, group_cols: list[str], diagnostic_label: str) -> pd.DataFrame:
    d = df.copy()

    if d.empty:
        return pd.DataFrame()

    d["trade_date"] = pd.to_datetime(d["trade_date"], errors="coerce").dt.normalize()

    numeric_cols = [
        "tenor",
        "normalized_pnl_dollars",
        "normalized_pnl_per_day",
        "win",
        "forecast_vol_pct",
        "model_vrp_log",
        "model_vrp_z_3m",
        "model_vrp_z_1y",
        "RSI14",
        "middle_min_z",
    ]

    for c in numeric_cols:
        if c in d.columns:
            d[c] = pd.to_numeric(d[c], errors="coerce")

    d = d[
        d["normalized_pnl_dollars"].notna()
        & d["normalized_pnl_per_day"].notna()
    ].copy()

    if d.empty:
        return pd.DataFrame()

    d = d.sort_values(["trade_date", "tenor"]).copy()

    rows = []

    for keys, g in d.groupby(group_cols, dropna=False):
        if not isinstance(keys, tuple):
            keys = (keys,)

        row = {
            "diagnostic_label": diagnostic_label,
        }

        for col, key in zip(group_cols, keys):
            row[col] = key

        pnl = pd.to_numeric(g["normalized_pnl_dollars"], errors="coerce")
        pnl_day = pd.to_numeric(g["normalized_pnl_per_day"], errors="coerce")
        wins = pd.to_numeric(g["win"], errors="coerce") if "win" in g.columns else pd.Series(np.nan, index=g.index)

        y2025 = g[g["trade_date"].dt.year == 2025].copy()
        y2026 = g[g["trade_date"].dt.year == 2026].copy()

        row.update({
            "trades": int(len(g)),
            "unique_trade_dates": int(g["trade_date"].nunique()),
            "date_min": g["trade_date"].min(),
            "date_max": g["trade_date"].max(),
            "tenor_min": int(g["tenor"].min()) if "tenor" in g.columns and g["tenor"].notna().any() else np.nan,
            "tenor_max": int(g["tenor"].max()) if "tenor" in g.columns and g["tenor"].notna().any() else np.nan,
            "avg_tenor": float(g["tenor"].mean()) if "tenor" in g.columns and g["tenor"].notna().any() else np.nan,
            "win_rate": float(wins.mean()) if wins.notna().sum() else np.nan,

            "total_pnl": float(pnl.sum()),
            "avg_pnl": float(pnl.mean()),
            "median_pnl": float(pnl.median()),
            "worst_trade": float(pnl.min()),
            "best_trade": float(pnl.max()),
            "profit_factor": profit_factor_from_pnl(pnl),
            "selected_trade_drawdown": max_drawdown_from_pnl(pnl),
            "worst_5_trade_sum": worst_rolling_sum(pnl, 5),
            "worst_10_trade_sum": worst_rolling_sum(pnl, 10),
            "worst_20_trade_sum": worst_rolling_sum(pnl, 20),
            "trades_le_neg_50k": int((pnl <= -50_000).sum()),
            "trades_le_neg_100k": int((pnl <= -100_000).sum()),
            "trades_le_neg_150k": int((pnl <= -150_000).sum()),

            "total_pnl_per_day_sum": float(pnl_day.sum()),
            "avg_pnl_per_day": float(pnl_day.mean()),
            "median_pnl_per_day": float(pnl_day.median()),
            "worst_trade_pnl_per_day": float(pnl_day.min()),
            "best_trade_pnl_per_day": float(pnl_day.max()),
            "profit_factor_pnl_per_day": profit_factor_from_pnl(pnl_day),
            "pnl_per_day_drawdown": max_drawdown_from_pnl(pnl_day),
            "worst_5_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 5),
            "worst_10_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 10),
            "worst_20_trade_pnl_per_day_sum": worst_rolling_sum(pnl_day, 20),

            "trades_2025": int(len(y2025)),
            "pnl_2025": float(y2025["normalized_pnl_dollars"].sum()) if len(y2025) else 0.0,
            "avg_pnl_per_day_2025": float(y2025["normalized_pnl_per_day"].mean()) if len(y2025) else np.nan,
            "worst_trade_2025": float(y2025["normalized_pnl_dollars"].min()) if len(y2025) else np.nan,

            "trades_2026": int(len(y2026)),
            "pnl_2026": float(y2026["normalized_pnl_dollars"].sum()) if len(y2026) else 0.0,
            "avg_pnl_per_day_2026": float(y2026["normalized_pnl_per_day"].mean()) if len(y2026) else np.nan,
            "worst_trade_2026": float(y2026["normalized_pnl_dollars"].min()) if len(y2026) else np.nan,
        })

        for signal_col in ["forecast_vol_pct", "RSI14", "model_vrp_log", "model_vrp_z_3m", "model_vrp_z_1y", "middle_min_z"]:
            if signal_col in g.columns:
                row[f"avg_{signal_col}"] = float(pd.to_numeric(g[signal_col], errors="coerce").mean())
                row[f"min_{signal_col}"] = float(pd.to_numeric(g[signal_col], errors="coerce").min())
                row[f"max_{signal_col}"] = float(pd.to_numeric(g[signal_col], errors="coerce").max())

        rows.append(row)

    return pd.DataFrame(rows)


def attach_rule_columns(summary_df: pd.DataFrame, grid_wide: pd.DataFrame) -> pd.DataFrame:
    if summary_df.empty:
        return summary_df

    cols = [
        "candidate_id",
        "candidate_family",
        "candidate_subfamily",
        "candidate_description",

        "front_9d_model_vrp_log",
        "front_9d_model_vrp_z",
        "front_9d_RSI14_max",
        "front_9d_forecast_vol_pct_min",
        "front_12_15_model_vrp_log",
        "front_12_15_model_vrp_z",
        "front_12_15_RSI14_max",
        "front_12_15_forecast_vol_pct_min",

        "middle_model_vrp_log",
        "middle_model_vrp_z",
        "middle_RSI14_max",
        "middle_forecast_vol_pct_min",

        "back_model_vrp_log",
        "back_model_vrp_z",
        "back_RSI14_max",
        "back_forecast_vol_pct_min",
    ]

    available = [c for c in cols if c in grid_wide.columns]

    return summary_df.merge(
        grid_wide[available].drop_duplicates("candidate_id"),
        on="candidate_id",
        how="left",
        validate="many_to_one",
    )


# ======================================================================================
# 2. Load inputs
# ======================================================================================

signal_panel_path = latest_file(
    OUT_PROCESSED_DIR,
    "01_unified_fds_signal_base_panel_*.parquet",
    required=True,
)

cell12_selected_trade_panel_path = latest_file(
    OUT_PROCESSED_DIR,
    "10_core_front_9d_rule_sweep_selected_trade_panel_*.parquet",
    required=True,
)

cell12_candidate_summary_path = latest_file(
    OUT_AUDIT_DIR,
    "10_core_front_9d_rule_sweep_candidate_summary_*.csv",
    required=True,
)

cell12_by_bucket_path = latest_file(
    OUT_AUDIT_DIR,
    "10_core_front_9d_rule_sweep_by_bucket_*.csv",
    required=True,
)

cell12_by_tenor_path = latest_file(
    OUT_AUDIT_DIR,
    "10_core_front_9d_rule_sweep_by_tenor_*.csv",
    required=True,
)

cell12_by_year_path = latest_file(
    OUT_AUDIT_DIR,
    "10_core_front_9d_rule_sweep_by_year_*.csv",
    required=True,
)

signal = pd.read_parquet(signal_panel_path)
selected_panel = pd.read_parquet(cell12_selected_trade_panel_path)
cell12_summary = pd.read_csv(cell12_candidate_summary_path)
cell12_by_bucket = pd.read_csv(cell12_by_bucket_path)
cell12_by_tenor = pd.read_csv(cell12_by_tenor_path)
cell12_by_year = pd.read_csv(cell12_by_year_path)

signal["trade_date"] = pd.to_datetime(signal["trade_date"], errors="coerce").dt.normalize()
selected_panel["trade_date"] = pd.to_datetime(selected_panel["trade_date"], errors="coerce").dt.normalize()

for df in [signal, selected_panel]:
    for c in [
        "tenor",
        "tenor_bucket_order",
        "model_vrp_log",
        "model_vrp_z_3m",
        "model_vrp_z_1y",
        "RSI14",
        "forecast_vol_pct",
        "normalized_pnl_dollars",
        "normalized_pnl_per_day",
        "win",
    ]:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

# Focus on the provisional Cell 12 winner: 9D allowed only if FV > 20.0.
provisional_panel = selected_panel[
    selected_panel["candidate_id"].eq(PROVISIONAL_FRONT_CANDIDATE_ID)
].copy()

provisional_all_qualified = provisional_panel[
    provisional_panel["selection_universe"].eq(ALL_QUALIFIED_UNIVERSE)
].copy()

provisional_primary = provisional_panel[
    provisional_panel["selection_universe"].eq(PRIMARY_SELECTION_UNIVERSE)
].copy()

middle_all_qualified = provisional_all_qualified[
    provisional_all_qualified["tenor_bucket"].eq("Middle")
].copy()

middle_primary = provisional_primary[
    provisional_primary["tenor_bucket"].eq("Middle")
].copy()

for df in [middle_all_qualified, middle_primary]:
    df["middle_min_z"] = df[["model_vrp_z_3m", "model_vrp_z_1y"]].min(axis=1)

# ======================================================================================
# 3. Middle diagnostics under provisional Front rule
# ======================================================================================

# Basic Middle diagnostics.
middle_by_tenor_all = summarize_trades(
    middle_all_qualified,
    group_cols=["selection_universe", "tenor", "tenor_bucket", "tenor_bucket_order"],
    diagnostic_label="middle_all_qualified_by_tenor",
)

middle_by_tenor_primary = summarize_trades(
    middle_primary,
    group_cols=["selection_universe", "tenor", "tenor_bucket", "tenor_bucket_order"],
    diagnostic_label="middle_primary_by_tenor",
)

middle_by_tenor = pd.concat(
    [middle_by_tenor_all, middle_by_tenor_primary],
    ignore_index=True,
)

middle_all_year = middle_all_qualified.copy()
middle_all_year["year"] = middle_all_year["trade_date"].dt.year.astype(int)

middle_primary_year = middle_primary.copy()
middle_primary_year["year"] = middle_primary_year["trade_date"].dt.year.astype(int)

middle_by_year = pd.concat(
    [
        summarize_trades(
            middle_all_year,
            group_cols=["selection_universe", "year"],
            diagnostic_label="middle_all_qualified_by_year",
        ),
        summarize_trades(
            middle_primary_year,
            group_cols=["selection_universe", "year"],
            diagnostic_label="middle_primary_by_year",
        ),
    ],
    ignore_index=True,
)

middle_by_tenor_year = pd.concat(
    [
        summarize_trades(
            middle_all_year,
            group_cols=["selection_universe", "tenor", "year"],
            diagnostic_label="middle_all_qualified_by_tenor_year",
        ),
        summarize_trades(
            middle_primary_year,
            group_cols=["selection_universe", "tenor", "year"],
            diagnostic_label="middle_primary_by_tenor_year",
        ),
    ],
    ignore_index=True,
)

# State diagnostics.
middle_state = pd.concat(
    [
        middle_all_qualified.assign(state_source="all_qualified"),
        middle_primary.assign(state_source="primary_selected"),
    ],
    ignore_index=True,
)

middle_state["middle_min_z"] = middle_state[["model_vrp_z_3m", "model_vrp_z_1y"]].min(axis=1)

middle_state["forecast_vol_state"] = pd.cut(
    middle_state["forecast_vol_pct"],
    bins=[-np.inf, 10.0, 11.5, 13.0, 14.5, 16.0, 18.0, np.inf],
    labels=["<=10.0", "10.0-11.5", "11.5-13.0", "13.0-14.5", "14.5-16.0", "16.0-18.0", ">18.0"],
    include_lowest=True,
)

middle_state["RSI14_state"] = pd.cut(
    middle_state["RSI14"],
    bins=[-np.inf, 60.0, 64.0, 66.0, 68.0, 70.0, np.inf],
    labels=["<=60", "60-64", "64-66", "66-68", "68-70", ">70"],
    include_lowest=True,
)

middle_state["model_vrp_log_state"] = pd.cut(
    middle_state["model_vrp_log"],
    bins=[-np.inf, 0.70, 0.75, 0.80, 0.90, 1.00, np.inf],
    labels=["<=0.70", "0.70-0.75", "0.75-0.80", "0.80-0.90", "0.90-1.00", ">1.00"],
    include_lowest=True,
)

middle_state["middle_min_z_state"] = pd.cut(
    middle_state["middle_min_z"],
    bins=[-np.inf, 0.70, 0.80, 1.00, 1.25, 1.50, np.inf],
    labels=["<=0.70", "0.70-0.80", "0.80-1.00", "1.00-1.25", "1.25-1.50", ">1.50"],
    include_lowest=True,
)

middle_state_forecast_vol = summarize_trades(
    middle_state,
    group_cols=["state_source", "forecast_vol_state"],
    diagnostic_label="middle_by_forecast_vol_state",
)

middle_state_rsi = summarize_trades(
    middle_state,
    group_cols=["state_source", "RSI14_state"],
    diagnostic_label="middle_by_RSI14_state",
)

middle_state_vrp_log = summarize_trades(
    middle_state,
    group_cols=["state_source", "model_vrp_log_state"],
    diagnostic_label="middle_by_model_vrp_log_state",
)

middle_state_min_z = summarize_trades(
    middle_state,
    group_cols=["state_source", "middle_min_z_state"],
    diagnostic_label="middle_by_min_z_state",
)

middle_state_diagnostics = pd.concat(
    [
        middle_state_forecast_vol,
        middle_state_rsi,
        middle_state_vrp_log,
        middle_state_min_z,
    ],
    ignore_index=True,
)

# 2026 Middle detail for inspection.
middle_2026_detail = middle_primary[
    middle_primary["trade_date"].dt.year.eq(2026)
].copy()

middle_2026_detail = middle_2026_detail[
    [
        c for c in [
            "candidate_id",
            "selection_universe",
            "trade_date",
            "tenor",
            "tenor_bucket",
            "normalized_pnl_dollars",
            "normalized_pnl_per_day",
            "win",
            "forecast_vol_pct",
            "RSI14",
            "model_vrp_log",
            "model_vrp_z_3m",
            "model_vrp_z_1y",
            "middle_min_z",
            "implied_vol_pct",
            "forecast_vol_pct",
            "model_vrp_ratio",
        ]
        if c in middle_2026_detail.columns
    ]
].sort_values(["trade_date", "tenor"]).reset_index(drop=True)

# ======================================================================================
# 4. Build Middle candidate design
# ======================================================================================

FRONT_9D_RULE = threshold_dict(
    model_vrp_log=0.70,
    model_vrp_z=0.65,
    rsi_max=68.0,
    forecast_vol_pct_min=20.0,
)

FRONT_12_15_RULE = threshold_dict(
    model_vrp_log=0.70,
    model_vrp_z=0.65,
    rsi_max=68.0,
    forecast_vol_pct_min=14.5,
)

BACK_RULE = threshold_dict(
    model_vrp_log=LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"],
    model_vrp_z=LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"],
    rsi_max=LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"],
    forecast_vol_pct_min=LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"],
)

middle_candidate_rules = [
    {
        "candidate_id": "core_middle_rule_0001",
        "candidate_subfamily": "current_middle",
        "candidate_description": "Current Middle rule: log > 0.70, z > 0.70, RSI < 68, forecast vol > 10.0.",
        "middle_rule": threshold_dict(0.70, 0.70, 68.0, 10.0),
    },
    {
        "candidate_id": "core_middle_rule_0002",
        "candidate_subfamily": "middle_higher_forecast_vol",
        "candidate_description": "Middle forecast-vol floor > 11.5.",
        "middle_rule": threshold_dict(0.70, 0.70, 68.0, 11.5),
    },
    {
        "candidate_id": "core_middle_rule_0003",
        "candidate_subfamily": "middle_higher_forecast_vol",
        "candidate_description": "Middle forecast-vol floor > 13.0.",
        "middle_rule": threshold_dict(0.70, 0.70, 68.0, 13.0),
    },
    {
        "candidate_id": "core_middle_rule_0004",
        "candidate_subfamily": "middle_higher_forecast_vol",
        "candidate_description": "Middle forecast-vol floor > 14.5.",
        "middle_rule": threshold_dict(0.70, 0.70, 68.0, 14.5),
    },
    {
        "candidate_id": "core_middle_rule_0005",
        "candidate_subfamily": "middle_tighter_RSI",
        "candidate_description": "Middle RSI < 66.",
        "middle_rule": threshold_dict(0.70, 0.70, 66.0, 10.0),
    },
    {
        "candidate_id": "core_middle_rule_0006",
        "candidate_subfamily": "middle_higher_forecast_vol_and_tighter_RSI",
        "candidate_description": "Middle forecast-vol floor > 13.0 and RSI < 66.",
        "middle_rule": threshold_dict(0.70, 0.70, 66.0, 13.0),
    },
]

wide_rows = []

for spec in middle_candidate_rules:
    m = spec["middle_rule"]

    wide_rows.append({
        "candidate_id": spec["candidate_id"],
        "candidate_family": MIDDLE_CANDIDATE_FAMILY,
        "candidate_subfamily": spec["candidate_subfamily"],
        "candidate_description": spec["candidate_description"],
        "locked_model_spec": LOCKED_MODEL_SPEC,

        "front_9d_include": True,
        "front_9d_model_vrp_log": FRONT_9D_RULE["model_vrp_log"],
        "front_9d_model_vrp_z": FRONT_9D_RULE["model_vrp_z"],
        "front_9d_RSI14_max": FRONT_9D_RULE["RSI14_max"],
        "front_9d_forecast_vol_pct_min": FRONT_9D_RULE["forecast_vol_pct_min"],

        "front_12_15_include": True,
        "front_12_15_model_vrp_log": FRONT_12_15_RULE["model_vrp_log"],
        "front_12_15_model_vrp_z": FRONT_12_15_RULE["model_vrp_z"],
        "front_12_15_RSI14_max": FRONT_12_15_RULE["RSI14_max"],
        "front_12_15_forecast_vol_pct_min": FRONT_12_15_RULE["forecast_vol_pct_min"],

        "middle_include": True,
        "middle_model_vrp_log": m["model_vrp_log"],
        "middle_model_vrp_z": m["model_vrp_z"],
        "middle_RSI14_max": m["RSI14_max"],
        "middle_forecast_vol_pct_min": m["forecast_vol_pct_min"],

        "back_include": True,
        "back_model_vrp_log": BACK_RULE["model_vrp_log"],
        "back_model_vrp_z": BACK_RULE["model_vrp_z"],
        "back_RSI14_max": BACK_RULE["RSI14_max"],
        "back_forecast_vol_pct_min": BACK_RULE["forecast_vol_pct_min"],
    })

candidate_grid_wide = pd.DataFrame(wide_rows)

candidate_grid_wide["front_fixed_to_cell12_9d_fv20_rule"] = (
    (candidate_grid_wide["front_9d_forecast_vol_pct_min"] == 20.0)
    & (candidate_grid_wide["front_12_15_forecast_vol_pct_min"] == 14.5)
    & (candidate_grid_wide["front_9d_model_vrp_z"] == 0.65)
    & (candidate_grid_wide["front_12_15_model_vrp_z"] == 0.65)
)

candidate_grid_wide["back_locked"] = (
    (candidate_grid_wide["back_model_vrp_log"] == LOCKED_BACK_CORE_THRESHOLDS["model_vrp_log"])
    & (candidate_grid_wide["back_model_vrp_z"] == LOCKED_BACK_CORE_THRESHOLDS["model_vrp_z_3m"])
    & (candidate_grid_wide["back_RSI14_max"] == LOCKED_BACK_CORE_THRESHOLDS["RSI14_max"])
    & (candidate_grid_wide["back_forecast_vol_pct_min"] == LOCKED_BACK_CORE_THRESHOLDS["forecast_vol_pct_min"])
)

long_rows = []

for _, row in candidate_grid_wide.iterrows():
    for tenor in ALL_TENORS:
        bucket = TENOR_BUCKET_MAP[int(tenor)]

        if bucket == "Front" and tenor == 9:
            rule_scope = "front_9d"
            rule_type = "fixed_cell12_9d_fv20_rule"
            model_vrp_log = row["front_9d_model_vrp_log"]
            model_vrp_z = row["front_9d_model_vrp_z"]
            rsi_max = row["front_9d_RSI14_max"]
            fv_floor = row["front_9d_forecast_vol_pct_min"]

        elif bucket == "Front" and tenor in [12, 15]:
            rule_scope = "front_12_15"
            rule_type = "fixed_cell12_front_12_15_rule"
            model_vrp_log = row["front_12_15_model_vrp_log"]
            model_vrp_z = row["front_12_15_model_vrp_z"]
            rsi_max = row["front_12_15_RSI14_max"]
            fv_floor = row["front_12_15_forecast_vol_pct_min"]

        elif bucket == "Middle":
            rule_scope = "middle"
            rule_type = "candidate_middle_rule"
            model_vrp_log = row["middle_model_vrp_log"]
            model_vrp_z = row["middle_model_vrp_z"]
            rsi_max = row["middle_RSI14_max"]
            fv_floor = row["middle_forecast_vol_pct_min"]

        elif bucket == "Back":
            rule_scope = "back"
            rule_type = "locked_back_rule"
            model_vrp_log = row["back_model_vrp_log"]
            model_vrp_z = row["back_model_vrp_z"]
            rsi_max = row["back_RSI14_max"]
            fv_floor = row["back_forecast_vol_pct_min"]

        else:
            raise ValueError(f"Unexpected tenor/bucket combination: tenor={tenor}, bucket={bucket}")

        long_rows.append({
            "candidate_id": row["candidate_id"],
            "candidate_family": row["candidate_family"],
            "candidate_subfamily": row["candidate_subfamily"],
            "locked_model_spec": row["locked_model_spec"],
            "tenor": int(tenor),
            "tenor_bucket": bucket,
            "tenor_bucket_order": BUCKET_ORDER_MAP[bucket],
            "rule_scope": rule_scope,
            "rule_type": rule_type,
            "include_tenor": True,

            "model_vrp_log": float(model_vrp_log),
            "model_vrp_z": float(model_vrp_z),
            "model_vrp_z_3m": float(model_vrp_z),
            "model_vrp_z_1y": float(model_vrp_z),
            "RSI14_max": float(rsi_max),
            "forecast_vol_pct_min": float(fv_floor),

            "is_front_9d": bucket == "Front" and tenor == 9,
            "is_front_12_15": bucket == "Front" and tenor in [12, 15],
            "is_middle_candidate_rule": bucket == "Middle",
            "is_back_locked": bucket == "Back",
        })

candidate_grid_long = (
    pd.DataFrame(long_rows)
    .sort_values(["candidate_id", "tenor"])
    .reset_index(drop=True)
)

# Attach design rule columns to diagnostics where useful.
middle_by_tenor["candidate_id"] = PROVISIONAL_FRONT_CANDIDATE_ID
middle_by_year["candidate_id"] = PROVISIONAL_FRONT_CANDIDATE_ID
middle_by_tenor_year["candidate_id"] = PROVISIONAL_FRONT_CANDIDATE_ID
middle_state_diagnostics["candidate_id"] = PROVISIONAL_FRONT_CANDIDATE_ID
middle_2026_detail["candidate_id"] = PROVISIONAL_FRONT_CANDIDATE_ID

# ======================================================================================
# 5. Diagnostic conclusion
# ======================================================================================

middle_primary_2026 = middle_by_year[
    middle_by_year["diagnostic_label"].eq("middle_primary_by_year")
    & middle_by_year["year"].eq(2026)
].copy()

middle_2026_avg = (
    float(middle_primary_2026["avg_pnl_per_day"].iloc[0])
    if not middle_primary_2026.empty
    else np.nan
)

middle_primary_by_tenor_2026 = middle_by_tenor_year[
    middle_by_tenor_year["diagnostic_label"].eq("middle_primary_by_tenor_year")
    & middle_by_tenor_year["year"].eq(2026)
].copy()

worst_middle_2026_tenor = np.nan
worst_middle_2026_avg = np.nan

if not middle_primary_by_tenor_2026.empty:
    worst_row = middle_primary_by_tenor_2026.sort_values("avg_pnl_per_day").iloc[0]
    worst_middle_2026_tenor = int(worst_row["tenor"])
    worst_middle_2026_avg = float(worst_row["avg_pnl_per_day"])

diagnostic_conclusion = pd.DataFrame([
    {
        "diagnostic": "provisional_front_candidate_loaded",
        "status": "PASS" if not provisional_panel.empty else "FAIL",
        "detail": f"candidate_id={PROVISIONAL_FRONT_CANDIDATE_ID}; rows={len(provisional_panel):,}",
    },
    {
        "diagnostic": "middle_primary_2026_avg_pnl_per_day",
        "status": "WARN" if pd.notna(middle_2026_avg) and middle_2026_avg < 0 else "PASS",
        "detail": f"middle_primary_2026_avg_pnl_per_day={middle_2026_avg}",
    },
    {
        "diagnostic": "worst_middle_2026_tenor",
        "status": "INFO",
        "detail": f"worst_middle_2026_tenor={worst_middle_2026_tenor}; avg_pnl_per_day={worst_middle_2026_avg}",
    },
    {
        "diagnostic": "middle_candidate_design_count",
        "status": "PASS" if len(candidate_grid_wide) == 6 else "FAIL",
        "detail": f"candidate_count={len(candidate_grid_wide):,}",
    },
    {
        "diagnostic": "no_middle_sweep_performed",
        "status": "PASS",
        "detail": "Cell 13 creates Middle candidate design only. Cell 14 should sweep.",
    },
])

# ======================================================================================
# 6. Save outputs
# ======================================================================================

middle_by_tenor_path = OUT_AUDIT_DIR / f"11_middle_weakness_current_middle_by_tenor_{CELL13_TIMESTAMP}.csv"
middle_by_year_path = OUT_AUDIT_DIR / f"11_middle_weakness_current_middle_by_year_{CELL13_TIMESTAMP}.csv"
middle_by_tenor_year_path = OUT_AUDIT_DIR / f"11_middle_weakness_current_middle_by_tenor_year_{CELL13_TIMESTAMP}.csv"
middle_state_diagnostics_path = OUT_AUDIT_DIR / f"11_middle_weakness_current_middle_state_diagnostics_{CELL13_TIMESTAMP}.csv"
middle_2026_detail_path = OUT_AUDIT_DIR / f"11_middle_weakness_current_middle_2026_trade_detail_{CELL13_TIMESTAMP}.csv"
diagnostic_conclusion_path = OUT_AUDIT_DIR / f"11_middle_weakness_diagnostic_conclusion_{CELL13_TIMESTAMP}.csv"

wide_csv_path = OUT_AUDIT_DIR / f"11_core_middle_rule_candidate_grid_wide_{CELL13_TIMESTAMP}.csv"
wide_parquet_path = OUT_PROCESSED_DIR / f"11_core_middle_rule_candidate_grid_wide_{CELL13_TIMESTAMP}.parquet"
long_csv_path = OUT_AUDIT_DIR / f"11_core_middle_rule_candidate_grid_long_{CELL13_TIMESTAMP}.csv"
long_parquet_path = OUT_PROCESSED_DIR / f"11_core_middle_rule_candidate_grid_long_{CELL13_TIMESTAMP}.parquet"
ranges_path = OUT_AUDIT_DIR / f"11_core_middle_rule_candidate_grid_ranges_{CELL13_TIMESTAMP}.json"
validation_path = OUT_AUDIT_DIR / f"11_core_middle_rule_candidate_grid_validation_{CELL13_TIMESTAMP}.csv"
manifest_path = OUT_AUDIT_DIR / f"11_core_middle_rule_candidate_grid_manifest_{CELL13_TIMESTAMP}.json"

middle_by_tenor.to_csv(middle_by_tenor_path, index=False)
middle_by_year.to_csv(middle_by_year_path, index=False)
middle_by_tenor_year.to_csv(middle_by_tenor_year_path, index=False)
middle_state_diagnostics.to_csv(middle_state_diagnostics_path, index=False)
middle_2026_detail.to_csv(middle_2026_detail_path, index=False)
diagnostic_conclusion.to_csv(diagnostic_conclusion_path, index=False)

candidate_grid_wide.to_csv(wide_csv_path, index=False)
candidate_grid_wide.to_parquet(wide_parquet_path, index=False)
candidate_grid_long.to_csv(long_csv_path, index=False)
candidate_grid_long.to_parquet(long_parquet_path, index=False)

grid_ranges = {
    "candidate_family": MIDDLE_CANDIDATE_FAMILY,
    "provisional_front_candidate_id": PROVISIONAL_FRONT_CANDIDATE_ID,
    "front_9d_rule": FRONT_9D_RULE,
    "front_12_15_rule": FRONT_12_15_RULE,
    "middle_candidate_rules": [
        {
            "candidate_id": spec["candidate_id"],
            "candidate_subfamily": spec["candidate_subfamily"],
            "candidate_description": spec["candidate_description"],
            "middle_rule": spec["middle_rule"],
        }
        for spec in middle_candidate_rules
    ],
    "back_rule": BACK_RULE,
}

with open(ranges_path, "w", encoding="utf-8") as f:
    json.dump(grid_ranges, f, indent=2, default=str)

# ======================================================================================
# 7. Validation
# ======================================================================================

validation_rows = []

def add_validation(check, status, detail):
    validation_rows.append({
        "check": check,
        "status": status,
        "detail": detail,
    })

required_selected_cols = [
    "candidate_id",
    "selection_universe",
    "trade_date",
    "tenor",
    "tenor_bucket",
    "tenor_bucket_order",
    "normalized_pnl_dollars",
    "normalized_pnl_per_day",
    "win",
    "forecast_vol_pct",
    "RSI14",
    "model_vrp_log",
    "model_vrp_z_3m",
    "model_vrp_z_1y",
]

missing_selected_cols = [c for c in required_selected_cols if c not in selected_panel.columns]

candidate_count = len(candidate_grid_wide)
expected_candidate_count = 6

long_row_count = len(candidate_grid_long)
expected_long_row_count = candidate_count * len(ALL_TENORS)

bad_z_equality = candidate_grid_long[
    candidate_grid_long["model_vrp_z_3m"].ne(candidate_grid_long["model_vrp_z_1y"])
]

bad_front_9d = candidate_grid_long[
    candidate_grid_long["is_front_9d"]
    & (
        candidate_grid_long["model_vrp_log"].ne(FRONT_9D_RULE["model_vrp_log"])
        | candidate_grid_long["model_vrp_z"].ne(FRONT_9D_RULE["model_vrp_z"])
        | candidate_grid_long["RSI14_max"].ne(FRONT_9D_RULE["RSI14_max"])
        | candidate_grid_long["forecast_vol_pct_min"].ne(FRONT_9D_RULE["forecast_vol_pct_min"])
    )
]

bad_front_12_15 = candidate_grid_long[
    candidate_grid_long["is_front_12_15"]
    & (
        candidate_grid_long["model_vrp_log"].ne(FRONT_12_15_RULE["model_vrp_log"])
        | candidate_grid_long["model_vrp_z"].ne(FRONT_12_15_RULE["model_vrp_z"])
        | candidate_grid_long["RSI14_max"].ne(FRONT_12_15_RULE["RSI14_max"])
        | candidate_grid_long["forecast_vol_pct_min"].ne(FRONT_12_15_RULE["forecast_vol_pct_min"])
    )
]

bad_back = candidate_grid_long[
    candidate_grid_long["is_back_locked"]
    & (
        candidate_grid_long["model_vrp_log"].ne(BACK_RULE["model_vrp_log"])
        | candidate_grid_long["model_vrp_z"].ne(BACK_RULE["model_vrp_z"])
        | candidate_grid_long["RSI14_max"].ne(BACK_RULE["RSI14_max"])
        | candidate_grid_long["forecast_vol_pct_min"].ne(BACK_RULE["forecast_vol_pct_min"])
    )
]

middle_fv_values = sorted(
    candidate_grid_wide["middle_forecast_vol_pct_min"].dropna().unique().tolist()
)
middle_rsi_values = sorted(
    candidate_grid_wide["middle_RSI14_max"].dropna().unique().tolist()
)

trade_metric_cols = [
    "trades",
    "win_rate",
    "total_pnl",
    "avg_pnl",
    "avg_pnl_per_day",
    "profit_factor",
    "worst_trade",
    "pnl_per_day_drawdown",
]
unexpected_trade_cols = [
    c for c in trade_metric_cols
    if c in candidate_grid_wide.columns or c in candidate_grid_long.columns
]

add_validation(
    "signal_panel_loaded",
    "PASS" if len(signal) > 0 else "FAIL",
    f"rows={len(signal):,}; path={signal_panel_path}",
)

add_validation(
    "cell12_selected_trade_panel_loaded",
    "PASS" if len(selected_panel) > 0 else "FAIL",
    f"rows={len(selected_panel):,}; path={cell12_selected_trade_panel_path}",
)

add_validation(
    "required_selected_columns_available",
    "PASS" if not missing_selected_cols else "FAIL",
    f"missing={missing_selected_cols}",
)

add_validation(
    "provisional_front_candidate_available",
    "PASS" if not provisional_panel.empty else "FAIL",
    f"candidate_id={PROVISIONAL_FRONT_CANDIDATE_ID}; rows={len(provisional_panel):,}",
)

add_validation(
    "middle_primary_diagnostics_created",
    "PASS" if not middle_by_tenor.empty and not middle_by_year.empty else "FAIL",
    f"by_tenor_rows={len(middle_by_tenor):,}; by_year_rows={len(middle_by_year):,}",
)

add_validation(
    "middle_2026_detail_created",
    "PASS" if len(middle_2026_detail) > 0 else "WARN",
    f"rows={len(middle_2026_detail):,}",
)

add_validation(
    "middle_state_diagnostics_created",
    "PASS" if not middle_state_diagnostics.empty else "WARN",
    f"rows={len(middle_state_diagnostics):,}",
)

add_validation(
    "middle_candidate_grid_count",
    "PASS" if candidate_count == expected_candidate_count else "FAIL",
    f"candidate_count={candidate_count:,}; expected={expected_candidate_count:,}",
)

add_validation(
    "long_grid_has_all_tenors_per_candidate",
    "PASS" if long_row_count == expected_long_row_count else "FAIL",
    f"long_rows={long_row_count:,}; expected={expected_long_row_count:,}",
)

add_validation(
    "front_9d_fixed_to_fv20",
    "PASS" if bad_front_9d.empty else "FAIL",
    f"bad_rows={len(bad_front_9d):,}",
)

add_validation(
    "front_12_15_fixed",
    "PASS" if bad_front_12_15.empty else "FAIL",
    f"bad_rows={len(bad_front_12_15):,}",
)

add_validation(
    "back_locked",
    "PASS" if bad_back.empty else "FAIL",
    f"bad_rows={len(bad_back):,}",
)

add_validation(
    "middle_candidate_fv_values",
    "PASS" if middle_fv_values == [10.0, 11.5, 13.0, 14.5] else "FAIL",
    f"found={middle_fv_values}",
)

add_validation(
    "middle_candidate_rsi_values",
    "PASS" if middle_rsi_values == [66.0, 68.0] else "FAIL",
    f"found={middle_rsi_values}",
)

add_validation(
    "z_3m_equals_z_1y_within_rules",
    "PASS" if bad_z_equality.empty else "FAIL",
    f"bad_rows={len(bad_z_equality):,}",
)

add_validation(
    "no_trade_metrics_in_candidate_design",
    "PASS" if not unexpected_trade_cols else "FAIL",
    f"unexpected_trade_metric_cols={unexpected_trade_cols}",
)

add_validation(
    "no_new_middle_sweep",
    "PASS",
    "Cell 13 creates Middle candidate design only.",
)

add_validation(
    "no_final_candidate_selection",
    "PASS",
    "No final thresholds selected.",
)

add_validation(
    "no_secondary",
    "PASS",
    "Core only.",
)

add_validation(
    "no_sizing_changes",
    "PASS",
    "No sizing fields included.",
)

add_validation(
    "no_production_lock",
    "PASS",
    "No production threshold lock performed.",
)

validation = pd.DataFrame(validation_rows)
validation.to_csv(validation_path, index=False)

failures = validation[validation["status"] == "FAIL"]

manifest = {
    "notebook": "07_unified_fds_core_signal_threshold_research_v1.ipynb",
    "cell": "Cell 13 — Middle weakness diagnostic and candidate design",
    "timestamp": CELL13_TIMESTAMP,
    "locked_model_spec": LOCKED_MODEL_SPEC,
    "provisional_front_candidate_id": PROVISIONAL_FRONT_CANDIDATE_ID,
    "middle_candidate_family": MIDDLE_CANDIDATE_FAMILY,
    "candidate_count": int(candidate_count),
    "long_grid_rows": int(long_row_count),
    "signal_panel_path": str(signal_panel_path),
    "cell12_selected_trade_panel_path": str(cell12_selected_trade_panel_path),
    "cell12_candidate_summary_path": str(cell12_candidate_summary_path),
    "cell12_by_bucket_path": str(cell12_by_bucket_path),
    "cell12_by_tenor_path": str(cell12_by_tenor_path),
    "cell12_by_year_path": str(cell12_by_year_path),
    "middle_by_tenor_path": str(middle_by_tenor_path),
    "middle_by_year_path": str(middle_by_year_path),
    "middle_by_tenor_year_path": str(middle_by_tenor_year_path),
    "middle_state_diagnostics_path": str(middle_state_diagnostics_path),
    "middle_2026_detail_path": str(middle_2026_detail_path),
    "diagnostic_conclusion_path": str(diagnostic_conclusion_path),
    "wide_csv_path": str(wide_csv_path),
    "wide_parquet_path": str(wide_parquet_path),
    "long_csv_path": str(long_csv_path),
    "long_parquet_path": str(long_parquet_path),
    "ranges_path": str(ranges_path),
    "validation_path": str(validation_path),
    "front_9d_rule": FRONT_9D_RULE,
    "front_12_15_rule": FRONT_12_15_RULE,
    "back_rule": BACK_RULE,
    "middle_candidate_rules": [
        {
            "candidate_id": spec["candidate_id"],
            "candidate_subfamily": spec["candidate_subfamily"],
            "candidate_description": spec["candidate_description"],
            "middle_rule": spec["middle_rule"],
        }
        for spec in middle_candidate_rules
    ],
    "hard_constraints": [
        "Front fixed to Cell 12 provisional decision: 9D FV > 20, 12D/15D FV > 14.5.",
        "Back locked unchanged.",
        "Middle candidate design only.",
        "No Middle sweep in Cell 13.",
        "No final threshold selection.",
        "No Secondary.",
        "No sizing changes.",
        "No production lock.",
    ],
}

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2, default=str)

if not failures.empty:
    display(validation)
    raise RuntimeError("Cell 13 validation failed. Review validation output above.")

# ======================================================================================
# 8. Display review
# ======================================================================================

print("=" * 100)
print("Cell 13 — Middle weakness diagnostic and candidate design")
print("=" * 100)
print(f"Signal panel:                         {signal_panel_path}")
print(f"Cell 12 selected trade panel:          {cell12_selected_trade_panel_path}")
print(f"Provisional Front candidate:           {PROVISIONAL_FRONT_CANDIDATE_ID}")
print(f"Middle all-qualified rows reviewed:    {len(middle_all_qualified):,}")
print(f"Middle primary rows reviewed:          {len(middle_primary):,}")
print(f"Middle 2026 primary rows reviewed:     {len(middle_2026_detail):,}")
print(f"Middle candidate count:                {candidate_count:,}")
print(f"Long candidate grid rows:              {long_row_count:,}")
print("Front fixed:                           True")
print("Back locked:                           True")
print("No Middle sweep:                       True")
print("No final candidate selection:          True")
print("No Secondary:                          True")
print("No sizing changes:                     True")
print("No production lock:                    True")

print()
print("Validation:")
display(validation)

print()
print("Diagnostic conclusions:")
display(diagnostic_conclusion)

print()
print("Middle diagnostics by tenor:")
display(middle_by_tenor)

print()
print("Middle diagnostics by year:")
display(middle_by_year)

print()
print("Middle diagnostics by tenor/year:")
display(middle_by_tenor_year)

print()
print("Middle state diagnostics:")
display(middle_state_diagnostics)

print()
print("Middle 2026 primary selected trade detail:")
display(middle_2026_detail)

print()
print("Middle candidate grid — wide:")
display(candidate_grid_wide)

print()
print("Middle candidate grid — long:")
display(candidate_grid_long)

print()
print("Saved outputs:")
for p in [
    middle_by_tenor_path,
    middle_by_year_path,
    middle_by_tenor_year_path,
    middle_state_diagnostics_path,
    middle_2026_detail_path,
    diagnostic_conclusion_path,
    wide_csv_path,
    wide_parquet_path,
    long_csv_path,
    long_parquet_path,
    ranges_path,
    validation_path,
    manifest_path,
]:
    print(f"  {p}")

print("\nCELL 13 PASSED")

C:\Users\patri\AppData\Local\Temp\ipykernel_21560\808355830.py:222: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for keys, g in d.groupby(group_cols, dropna=False):
C:\Users\patri\AppData\Local\Temp\ipykernel_21560\808355830.py:222: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for keys, g in d.groupby(group_cols, dropna=False):
C:\Users\patri\AppData\Local\Temp\ipykernel_21560\808355830.py:222: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for keys, g in d.groupby(group_cols, dropna=False):

====================================================================================================
Cell 13 — Middle weakness diagnostic and candidate design
====================================================================================================
Signal panel:                         C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\01_unified_fds_signal_base_panel_20200102_20260701_20260704_211636.parquet
Cell 12 selected trade panel:          C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\10_core_front_9d_rule_sweep_selected_trade_panel_20260704_222153.parquet
Provisional Front candidate:           core_front_9d_rule_0004
Middle all-qualified rows reviewed:    406
Middle primary rows reviewed:          149
Middle 2026 primary rows reviewed:     29
Middle candidate count:                6
Long candidate grid rows:              54
Front fixed:                           True
Back locked:                           True
No Middle sweep:                       True
No final candidate selection:          True
No Secondary:                          True
No sizing changes:                     True
No production lock:                    True

Validation:

C:\Users\patri\AppData\Local\Temp\ipykernel_21560\808355830.py:222: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for keys, g in d.groupby(group_cols, dropna=False):

                                     check status                                             detail
0                      signal_panel_loaded   PASS  rows=14,688; path=C:\Users\patri\vrp_project\d...
1       cell12_selected_trade_panel_loaded   PASS  rows=6,831; path=C:\Users\patri\vrp_project\da...
2      required_selected_columns_available   PASS                                         missing=[]
3    provisional_front_candidate_available   PASS   candidate_id=core_front_9d_rule_0004; rows=1,685
4       middle_primary_diagnostics_created   PASS                   by_tenor_rows=6; by_year_rows=12
5               middle_2026_detail_created   PASS                                            rows=29
6         middle_state_diagnostics_created   PASS                                            rows=40
7              middle_candidate_grid_count   PASS                      candidate_count=6; expected=6
8   long_grid_has_all_tenors_per_candidate   PASS                          long_rows=54; expected=54
9                   front_9d_fixed_to_fv20   PASS                                         bad_rows=0
10                       front_12_15_fixed   PASS                                         bad_rows=0
11                             back_locked   PASS                                         bad_rows=0
12              middle_candidate_fv_values   PASS                     found=[10.0, 11.5, 13.0, 14.5]
13             middle_candidate_rsi_values   PASS                                 found=[66.0, 68.0]
14           z_3m_equals_z_1y_within_rules   PASS                                         bad_rows=0
15    no_trade_metrics_in_candidate_design   PASS                    unexpected_trade_metric_cols=[]
16                     no_new_middle_sweep   PASS      Cell 13 creates Middle candidate design only.
17            no_final_candidate_selection   PASS                      No final thresholds selected.
18                            no_secondary   PASS                                         Core only.
19                       no_sizing_changes   PASS                         No sizing fields included.
20                      no_production_lock   PASS            No production threshold lock performed.

Diagnostic conclusions:

                            diagnostic status                                             detail
0   provisional_front_candidate_loaded   PASS   candidate_id=core_front_9d_rule_0004; rows=1,685
1  middle_primary_2026_avg_pnl_per_day   WARN  middle_primary_2026_avg_pnl_per_day=-275.81018...
2              worst_middle_2026_tenor   INFO  worst_middle_2026_tenor=18; avg_pnl_per_day=-6...
3        middle_candidate_design_count   PASS                                  candidate_count=6
4            no_middle_sweep_performed   PASS  Cell 13 creates Middle candidate design only. ...

Middle diagnostics by tenor:

,diagnostic_label,selection_universe,tenor,tenor_bucket,tenor_bucket_order,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,avg_forecast_vol_pct,min_forecast_vol_pct,max_forecast_vol_pct,avg_RSI14,min_RSI14,max_RSI14,avg_model_vrp_log,min_model_vrp_log,max_model_vrp_log,avg_model_vrp_z_3m,min_model_vrp_z_3m,max_model_vrp_z_3m,avg_model_vrp_z_1y,min_model_vrp_z_1y,max_model_vrp_z_1y,avg_middle_min_z,min_middle_min_z,max_middle_min_z,candidate_id
0,middle_all_qualified_by_tenor,all_qualified_trades,18,Middle,2,136,136,2021-11-24,2026-04-29,18,18,18.0,0.845588,1.475143e+06,10846.640334,17482.133127,-108475.796818,38031.055016,3.507062,-388526.041944,-197285.561652,-358351.426266,-311461.162391,1,1,0,81952.393636,602.591130,971.229618,-6026.433157,2112.836390,3.507062,-21584.780108,-10960.308981,-19908.412570,-17303.397911,17,266370.737792,870.492607,6005.032657,29,-138442.807121,-265.216106,-45195.769858,16.288259,10.485959,40.256955,45.524603,21.362549,67.986764,0.969275,0.701002,1.411423,1.609936,0.721510,4.706726,1.661413,0.749543,4.724766,1.420945,0.721510,4.706726,core_front_9d_rule_0004
1,middle_all_qualified_by_tenor,all_qualified_trades,21,Middle,2,133,133,2021-11-24,2026-04-29,21,21,21.0,0.834586,1.639575e+06,12327.628876,20221.414273,-108475.796818,42988.137121,3.571958,-355922.057117,-232923.170187,-336696.705037,-238955.001712,3,1,0,78074.982884,587.029946,962.924489,-5165.514134,2047.054149,3.571958,-16948.669387,-11091.579533,-16033.176430,-11378.809605,18,304725.379601,806.151798,-6858.911357,29,-38824.225026,-63.750780,-56809.083631,16.433182,10.198805,39.348374,45.532515,21.362549,67.986764,0.949458,0.714245,1.366911,1.610245,0.707622,5.229617,1.725705,0.721130,5.293032,1.438225,0.707622,5.229617,core_front_9d_rule_0004
2,middle_all_qualified_by_tenor,all_qualified_trades,24,Middle,2,137,137,2021-11-24,2026-04-29,24,24,24.0,0.839416,1.731273e+06,12637.028509,20248.487481,-92579.572354,42988.137121,3.614121,-356133.708504,-250626.850425,-336908.356424,-238387.242084,4,0,0,72136.371071,526.542855,843.686978,-3857.482181,1791.172380,3.614121,-14838.904521,-10442.785434,-14037.848184,-9932.801754,21,355832.058718,706.015990,-6858.911357,29,-20588.386201,-29.581015,-57319.352129,16.226558,10.107217,37.957610,46.147030,21.362549,67.986764,0.947382,0.703388,1.346525,1.614125,0.723957,5.381476,1.759015,0.752793,5.625044,1.443525,0.723957,5.381476,core_front_9d_rule_0004
3,middle_primary_by_tenor,one_trade_per_bucket_per_date_best_rank,18,Middle,2,54,54,2021-12-03,2026-03-25,18,18,18.0,0.740741,2.046359e+05,3789.554584,12641.588528,-108475.796818,25912.875855,1.460678,-315930.254948,-202522.266450,-315930.254948,-239409.369941,1,1,0,11368.663752,210.530810,702.310474,-6026.433157,1439.604214,1.460678,-17551.680830,-11251.237025,-17551.680830,-13300.520552,6,60950.563003,564.357065,6005.032657,18,-225068.948261,-694.657248,-45195.769858,15.162066,10.968784,20.662663,47.686658,25.808804,66.434105,0.958589,0.708579,1.288759,1.661407,0.741547,3.193014,1.564000,0.788692,3.080389,1.386738,0.741547,2.343601,core_front_9d_rule_0004
4,middle_primary_by_tenor,one_trade_per_bucket_per_date_best_rank,21,Middle,2,25,25,2021-12-01,2026-04-29,21,21,21.0,0.960000,3.987075e+05,15948.301588,18720.325571,-33182.394118,28179.541598,13.015635,-33182.394118,28166.045377,114624.158683,307501.033557,0,0,0,18986.073319,759.442933,891.444075,-1580.114006,1341.882933,13.015635,-1580.114006,1341.240256,5458.293271,14642.906360,7,127030.264488,864.151459,10440.842371,6,47374.991856,375.991999,-33182.394118,15.294476,10.277772,19.229675,49.161480,26.914078,66.880743,0.991714,0.726998,1.366911,1.775799,0.764696,3.509786,1.989921,1.085055,3.106651,1.670489,0.764696,2.906640,core_front_9d_rule_0004
5,middle_primary_by_tenor,one_trade_per_bucket_per_date_best_rank,24,Middle,2,70,70,2021-11-24,2026-03-30,24,24,24.0,0.885714,1.221898e+06,17455.690380,24257.585415,-48027.465092,42988.137121,7.596626,-48027.465092,-17563.867069,84062.019309,232583.964589,0,0,0,50912.430276,727.320433,1010.732726,-2001.144379,1791.172380,7.596626,-2001.144379,-731.827795,3502.584138,9690.998525,9,176846.421045,818.733431,10805.456045,5,53985.195231,449.876627,-39413.392878,17.192668,10.107217,37.957610,44.355670,21.362549,67.986764,0.946381,0.717721,1.339895,1.572113,0.723957,5.381476,1.841072,0.752793,5.625044,1.450402,0.723957,5.381476,core_front_9d_rule_0004

Middle diagnostics by year:

,diagnostic_label,selection_universe,year,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,avg_forecast_vol_pct,min_forecast_vol_pct,max_forecast_vol_pct,avg_RSI14,min_RSI14,max_RSI14,avg_model_vrp_log,min_model_vrp_log,max_model_vrp_log,avg_model_vrp_z_3m,min_model_vrp_z_3m,max_model_vrp_z_3m,avg_model_vrp_z_1y,min_model_vrp_z_1y,max_model_vrp_z_1y,avg_middle_min_z,min_middle_min_z,max_middle_min_z,candidate_id
0,middle_all_qualified_by_year,all_qualified_trades,2021,11,4,2021-11-24,2021-12-06,18,24,20.727273,0.818182,1.802100e+05,16382.729364,21593.370395,-3607.390045,24281.524668,25.977895,-7.214780e+03,49516.873875,159237.261461,180210.023005,0,0,0,8885.780684,807.798244,1010.959353,-171.780478,1223.614730,28.588019,-322.088397,2637.106470,7887.077754,8885.780684,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,16.157872,10.637736,19.229675,48.456267,37.494900,65.867281,1.047690,0.860922,1.220460,2.245560,1.240172,2.767565,1.269364,0.725768,1.783759,1.269364,0.725768,1.783759,core_front_9d_rule_0004
1,middle_all_qualified_by_year,all_qualified_trades,2022,195,69,2022-01-20,2022-11-01,18,24,21.000000,0.902564,3.262533e+06,16730.940374,24290.781986,-108475.796818,31848.877315,5.607286,-5.265937e+05,-387844.309642,-519811.154884,-415126.870548,3,2,0,157262.772001,806.475754,1148.170244,-6026.433157,1547.835029,5.732183,-25043.123155,-19045.459664,-24693.231746,-20140.234201,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,17.795971,13.097864,21.673512,42.448193,24.320664,63.839106,0.995809,0.758841,1.379234,1.459638,0.707622,2.690735,1.629650,0.721130,3.656931,1.337198,0.707622,2.516498,core_front_9d_rule_0004
2,middle_all_qualified_by_year,all_qualified_trades,2023,8,4,2023-03-15,2023-10-13,18,24,20.250000,1.000000,1.560274e+05,19503.423195,20221.414273,13286.257619,23438.457453,inf,0.000000e+00,96802.102035,156027.385560,156027.385560,0,0,0,7719.320569,964.915071,978.964121,738.125423,1123.411904,inf,0.000000,4589.514455,7719.320569,7719.320569,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,16.361306,13.420701,17.660504,45.210981,40.186566,47.757990,0.788175,0.726339,0.846920,2.326608,1.707730,3.193014,0.879855,0.753781,1.116829,0.879855,0.753781,1.116829,core_front_9d_rule_0004
3,middle_all_qualified_by_year,all_qualified_trades,2024,49,21,2024-08-02,2024-12-18,18,24,21.000000,0.877551,5.181471e+05,10574.430460,12960.918374,-12048.089968,27418.232160,10.661207,-2.770751e+04,-23402.705891,3567.126326,100869.310876,0,0,0,24558.320979,501.190224,595.281180,-669.338332,1347.559621,9.666330,-1393.529040,-1214.162150,-218.146436,4159.246475,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,13.763906,10.968784,21.594673,57.829644,30.554982,67.986764,0.831946,0.703388,1.239655,1.877788,0.962000,5.381476,2.539665,1.679667,5.625044,1.875988,0.962000,5.381476,core_front_9d_rule_0004
4,middle_all_qualified_by_year,all_qualified_trades,2025,56,22,2025-03-06,2025-11-20,18,24,21.214286,0.964286,9.269282e+05,16552.288859,17394.299167,-6858.911357,42988.137121,68.571086,-1.371782e+04,53606.378030,110945.184858,252591.531015,0,0,0,44135.442464,788.132901,813.181918,-326.614827,2112.836390,73.069302,-612.402800,2468.422892,5229.709944,11945.101608,56,926928.176111,788.132901,-6858.911357,0,0.000000,NaN,NaN,15.808004,10.107217,40.256955,51.503304,21.362549,66.434105,0.851237,0.701002,1.091028,1.576840,0.737061,2.791976,1.773277,1.088075,2.904290,1.496685,0.737061,2.730321,core_front_9d_rule_0004
5,middle_all_qualified_by_year,all_qualified_trades,2026,87,29,2026-02-19,2026-04-29,18,24,21.000000,0.586207,-1.978554e+05,-2274.200211,11780.691433,-57319.352129,25332.139502,0.821021,-1.096344e+06,-246564.815560,-465211.507187,-804340.738820,5,0,0,-10397.889108,-119.515967,628.036825,-2705.194459,1335.493151,0.806150,-53136.915156,-11402.948802,-21690.181700,-38674.703212,0,0.000000,NaN,NaN,87,-197855.418348,-119.515967,-57319.352129,14.773952,10.485959,18.329432,42.291627,27.717242,66.880743,1.005094,0.720125,1.411423,1.678057,0.721510,3.535008,1.539372,0.773498,2.906640,1.434507,0.721510,2.906640,core_front_9d_rule_0004
6,middle_primary_by_year,one_trade_per_bucket_per_date_best_rank,2021,4,4,2021-11-24,2021-12-06,18,24,20.250000,0.750000,6.023810e+04,15059.525620,19791.234022,-3607.390045,24263.024480,17.698528,0.000000e+00,60238.102479,60238.102479,60238.102479,0,0,0,3204.100202,801.025050,1077.388216,-150.307919,1199.631689,22.316909,0.000000,3204.100202,3204.100202,3204.100202,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,16.261487,11.301584,19.229675,48.438328,37.494900,65.867281,1.051506,0.924555,1.220460,2.219163,1.327322,2.767565,1.265839,0.827066,1.783759,1.265839,0.827066,1.783759,core_front_9d_rule_0004
7,middle_primary_by_year,one_trade_per_bucket_per_date_best_rank,2022,69,69,2022-01-20,2022-11-01,18,24,22.173913,0.884058,1.200349e+06,17396.364909,24875.282519,-108475.796818,31848.877315,5.575692,-1.553076e+05,-141751.618548,-50633.204103,113798.647860,1,1,0,53297.009945,772.420434,1102.805400,-6026.433157,1439.604214,5.213535,-8007.473681,-7442.642095,-3536.331097,3715.071504,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,17.729846,13.097864,21.366542,42.798967,24.320664,63.839106,1.005814,0.778303,1.339895,1.491292,0.723957,2.690735,1.674274,0.752793,3.656931,1.366404,0.723957,2.516498,core_front_9d_rule_0004
8,middle_primary_by_year,one_trade_per_bucket_per_date_best_rank,2023,4,4,2023-03-15,2023-10-13,18,18,18.000000,1.000000,6.995399e+04,17488.498030,18223.160113,13286.257619,20221.414273,inf,0.000000e+00,69953.992119,69953.992119,69953.992119,0,0,0,3886.332895,971.583224,1012.397784,738.125423,1123.411904,inf,0.000000,3886.332895,3886.332895,3886.332895,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,15.970486,13.420701,17.660504,44.520317,40.186566,47.757990,0.791174,0.726339,0.846920,2.205840,1.707730,3.193014,0.924537,0.788692,1.116829,0.924537,0.788692,1.116829,core_front_9d_rule_0004
9,middle_primary_by_year,one_trade_per_bucket_per_date_best_rank,2024,21,21,2024-08-02,2024-12-18,18,24,21.571429,0.952381,2.535821e+05,12075.335865,12960.918374,-3611.331326,27418.232160,71.218440,-3.611331e+03,24196.890212,89757.227680,236636.577943,0,0,0,12074.416157,574.972198,595.281180,-150.472139,1142.426340,81.243534,-150.472139,1008.203759,3928.151966,11133.000867,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,13.900971,10.968784,21.321611,57.344593,30.554982,67.986764,0.833951,0.708579,1.229427,1.918881,1.041358,5.381476,2.590521,1.679667,5.625044,1.914679,1.041358,5.381476,core_front_9d_rule_0004
10,middle_primary_by_year,one_trade_per_bucket_per_date_best_rank,2025,22,22,2025-03-06,2025-11-20,18,24,21.409091,1.000000,3.648272e+05,16583.056752,17751.178944,6005.032657,42988.137121,inf,0.000000e+00,49542.160008,123279.053710,315834.078759,0,0,0,16803.803480,763.809249,777.192118,333.612925,1791.172380,inf,0.000000,2519.402616,5951.934603,14679.018174,22,364827.248536,763.809249,6005.032657,0,0.000000,NaN,NaN,15.226019,10.107217,37.957610,52.425295,21.362549,66.434105,0.853891,0.717721,1.071148,1.543543,0.741547,2.791976,1.763360,1.088075,2.904290,1.472529,0.741547,2.730321,core_front_9d_rule_0004
11,middle_primary_by_year,one_trade_per_bucket_per_date_best_rank,2026,29,29,2026-02-19,2026-04-29,18,24,19.655172,0.551724,-1.237088e+05,-4265.819351,8645.779319,-45195.769858,25332.139502,0.685275,-3.842881e+05,-197285.561652,-358351.426266,-299518.482265,0,0,0,-7998.495331,-275.810184,480.321073,-2510.876103,1078.064482,0.619597,-20538.580680,-10696.956646,-19097.652002,-16233.914720,0,0.000000,NaN,NaN,29,-123708.761175,-275.810184,-45195.769858,14.669660,10.833435,18.163660,42.291627,27.717242,66.880743,1.025270,0.758954,1.366911,1.700182,0.764696,3.509786,1.572338,0.833267,2.906640,1.466447,0.764696,2.906640,core_front_9d_rule_0004

Middle diagnostics by tenor/year:

,diagnostic_label,selection_universe,tenor,year,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,avg_forecast_vol_pct,min_forecast_vol_pct,max_forecast_vol_pct,avg_RSI14,min_RSI14,max_RSI14,avg_model_vrp_log,min_model_vrp_log,max_model_vrp_log,avg_model_vrp_z_3m,min_model_vrp_z_3m,max_model_vrp_z_3m,avg_model_vrp_z_1y,min_model_vrp_z_1y,max_model_vrp_z_1y,avg_middle_min_z,min_middle_min_z,max_middle_min_z,candidate_id
0,middle_all_qualified_by_tenor_year,all_qualified_trades,18,2021,4,4,2021-11-24,2021-12-06,18,18,18.0,1.000000,7.205110e+04,18012.774382,19791.234022,10443.564340,22025.065145,inf,0.000000,72051.097527,72051.097527,72051.097527,0,0,0,4002.838752,1000.709688,1099.513001,580.198019,1223.614730,inf,0.000000,4002.838752,4002.838752,4002.838752,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,16.018458,10.637736,18.921408,48.438328,37.494900,65.867281,1.063933,0.924555,1.220460,2.151043,1.327322,2.767565,1.256534,0.827066,1.783759,1.256534,0.827066,1.783759,core_front_9d_rule_0004
1,middle_all_qualified_by_tenor_year,all_qualified_trades,18,2022,65,65,2022-01-20,2022-11-01,18,18,18.0,0.938462,1.066816e+06,16412.549934,22246.736532,-108475.796818,27861.030522,7.779720,-144236.317520,-138720.372907,-96365.610823,109915.335399,1,1,0,59267.541430,911.808330,1235.929807,-6026.433157,1547.835029,7.779720,-8013.128751,-7706.687384,-5353.645046,6106.407522,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,17.739589,13.097864,21.604638,42.797998,24.320664,63.839106,1.010136,0.797764,1.379234,1.451958,0.751588,2.463940,1.579806,0.749543,3.498021,1.313275,0.749543,2.463940,core_front_9d_rule_0004
2,middle_all_qualified_by_tenor_year,all_qualified_trades,18,2023,4,4,2023-03-15,2023-10-13,18,18,18.0,1.000000,6.995399e+04,17488.498030,18223.160113,13286.257619,20221.414273,inf,0.000000,69953.992119,69953.992119,69953.992119,0,0,0,3886.332895,971.583224,1012.397784,738.125423,1123.411904,inf,0.000000,3886.332895,3886.332895,3886.332895,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,15.970486,13.420701,17.660504,44.520317,40.186566,47.757990,0.791174,0.726339,0.846920,2.205840,1.707730,3.193014,0.924537,0.788692,1.116829,0.924537,0.788692,1.116829,core_front_9d_rule_0004
3,middle_all_qualified_by_tenor_year,all_qualified_trades,18,2024,17,17,2024-08-02,2024-12-18,18,18,18.0,0.764706,1.383943e+05,8140.842317,12145.583005,-12048.089968,24256.073177,4.644613,-37972.290754,-27070.085449,30837.642009,138394.319397,0,0,0,7688.573300,452.269018,674.754611,-669.338332,1347.559621,4.644613,-2109.571709,-1503.893636,1713.202334,7688.573300,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,13.965814,10.968784,21.569051,55.809157,30.554982,67.986764,0.821196,0.708579,1.239655,1.829757,1.100601,4.706726,2.277589,1.679667,4.724766,1.824567,1.100601,4.706726,core_front_9d_rule_0004
4,middle_all_qualified_by_tenor_year,all_qualified_trades,18,2025,17,17,2025-03-06,2025-11-20,18,18,18.0,1.000000,2.663707e+05,15668.866929,16070.946570,6005.032657,38031.055016,inf,0.000000,53580.512840,135368.531384,266370.737792,0,0,0,14798.374322,870.492607,892.830365,333.612925,2112.836390,inf,0.000000,2976.695158,7520.473966,14798.374322,17,266370.737792,870.492607,6005.032657,0,0.000000,NaN,NaN,16.116230,11.198785,40.256955,50.731103,21.362549,66.434105,0.864943,0.701002,1.091028,1.616277,0.741547,2.660324,1.800361,1.088075,2.883443,1.540035,0.741547,2.660324,core_front_9d_rule_0004
5,middle_all_qualified_by_tenor_year,all_qualified_trades,18,2026,29,29,2026-02-19,2026-04-29,18,18,18.0,0.551724,-1.384428e+05,-4773.889901,8645.779319,-45195.769858,24038.876720,0.647790,-384288.142473,-197285.561652,-358351.426266,-299518.482265,0,0,0,-7691.267062,-265.216106,480.321073,-2510.876103,1335.493151,0.647790,-21349.341248,-10960.308981,-19908.412570,-16639.915681,0,0.000000,NaN,NaN,29,-138442.807121,-265.216106,-45195.769858,14.578600,10.485959,18.130129,42.291627,27.717242,66.880743,1.037165,0.758954,1.411423,1.674621,0.721510,3.408964,1.559150,0.833267,2.897417,1.447004,0.721510,2.897417,core_front_9d_rule_0004
6,middle_all_qualified_by_tenor_year,all_qualified_trades,21,2021,4,4,2021-11-24,2021-12-06,21,21,21.0,0.750000,6.322177e+04,15805.441594,21283.065969,-3607.390045,24263.024480,18.525625,0.000000,63221.766374,63221.766374,63221.766374,0,0,0,3010.560304,752.640076,1013.479332,-171.780478,1155.382118,18.525625,0.000000,3010.560304,3010.560304,3010.560304,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,16.406758,11.109893,19.229675,48.438328,37.494900,65.867281,1.018800,0.860922,1.159147,2.178334,1.240172,2.716434,1.223035,0.725768,1.706777,1.223035,0.725768,1.706777,core_front_9d_rule_0004
7,middle_all_qualified_by_tenor_year,all_qualified_trades,21,2022,65,65,2022-01-20,2022-10-28,21,21,21.0,0.892308,1.093175e+06,16818.082249,24988.294957,-108475.796818,31529.479464,5.220027,-184537.625570,-178499.387958,-72855.539125,75612.375915,1,1,0,52055.968866,800.861059,1189.918807,-5165.514134,1501.403784,5.220027,-8787.505980,-8499.970855,-3469.311387,3600.589329,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,17.871570,13.366763,21.673512,42.404673,24.320664,63.839106,0.983832,0.758841,1.342111,1.457720,0.707622,2.559596,1.638592,0.721130,3.601647,1.341574,0.707622,2.501104,core_front_9d_rule_0004
8,middle_all_qualified_by_tenor_year,all_qualified_trades,21,2023,2,2,2023-03-17,2023-03-20,21,21,21.0,1.000000,4.142818e+04,20714.087565,20714.087565,20221.414273,21206.760857,inf,0.000000,41428.175131,41428.175131,41428.175131,0,0,0,1972.770244,986.385122,986.385122,962.924489,1009.845755,inf,0.000000,1972.770244,1972.770244,1972.770244,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,16.727892,16.508456,16.947327,45.901646,44.045301,47.757990,0.780701,0.765077,0.796325,2.212717,2.048863,2.376571,0.837278,0.778145,0.896412,0.837278,0.778145,0.896412,core_front_9d_rule_0004
9,middle_all_qualified_by_tenor_year,all_qualified_trades,21,2024,15,15,2024-08-05,2024-12-18,21,21,21.0,0.933333,1.758482e+05,11723.213219,13010.423746,-12048.089968,24256.073177,15.595525,-12048.089968,35711.085770,101073.494403,175848.198292,0,0,0,8373.723728,558.248249,619.543988,-573.718570,1155.051104,15.595525,-573.718570,1700.527894,4813.023543,8373.723728,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,13.915682,11.281533,21.594673,57.755866,30.554982,67.986764,0.837000,0.714245,1.218385,1.906940,0.962000,5.229617,2.633559,1.702903,5.293032,1.906940,0.962000,5.229617,core_front_9d_rule_0004
10,middle_all_qualified_by_tenor_year,all_qualified_trades,21,2025,18,18,2025-03-06,2025-11-20,21,21,21.0,0.944444,3.047254e+05,16929.187756,18092.651891,-6858.911357,42988.137121,45.427660,0.000000,59293.811149,151007.872466,304725.379601,0,0,0,14510.732362,806.151798,861.554852,-326.614827,2047.054149,45.427660,0.000000,2823.514817,7190.851070,14510.732362,18,304725.379601,806.151798,-6858.911357,0,0.000000,NaN,NaN,15.827466,10.198805,39.348374,51.176054,21.362549,66.434105,0.853909,0.732318,1.071148,1.604796,0.737061,2.730321,1.802567,1.142672,2.904290,1.519277,0.737061,2.730321,core_front_9d_rule_0004
11,middle_all_qualified_by_tenor_year,all_qualified_trades,21,2026,29,29,2026-02-19,2026-04-29,21,21,21.0,0.586207,-3.882423e+04,-1338.766380,14372.163389,-56809.083631,24038.876720,0.890919,-338359.840294,-232923.170187,-336696.705037,-216267.297018,2,0,0,-1848.772620,-63.750780,684.388733,-2705.194459,1144.708415,0.890919,-16112.373347,-11091.579533,-16033.176430,-10298.442715,0,0.000000,NaN,NaN,29,-38824.225026,-63.750780,-56809.083631,14.870646,10.833435,18.329432,42.291627,27.717242,66.880743,0.991958,0.720125,1.366911,1.682126,0.764696,3.509786,1.534276,0.787645,2.906640,1.433237,0.764696,2.906640,core_front_9d_rule_0004
12,middle_all_qualified_by_tenor_year,all_qualified_trades,24,2021,3,3,2021-11-24,2021-12-03,24,24,24.0,0.666667,4.493716e+04,14979.053035,24263.024480,-3607.390045,24281.524668,13.456973,0.000000,44937.159104,44937.159104,44937.159104,0,0,0,1872.381629,624.127210,1010.959353,-150.307919,1011.730195,13.456973,0.000000,1872.381629,1872.381629,1872.381629,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,16.011909,11.301584,19.094979,48.504104,37.494900,65.867281,1.064553,0.955058,1.137215,2.461217,2.094651,2.664899,1.348241,0.947092,1.621402,1.348241,0.947092,1.621402,core_front_9d_rule_0004
13,middle_all_qualified_by_tenor_year,all_qualified_trades,24,2022,65,65,2022-01-20,2022-10-27,24,24,24.0,0.876923,1.102542e+06,16962.188937,25469.027924,-92579.572354,31848.877315,4.779373,-197819.722192,-184263.764146,-63905.857769,93714.869826,1,0,0,45939.261705,706.757872,1061.209497,-3857.482181,1327.036555,4.779373,-8242.488425,-7677.656839,-2662.744074,3904.786243,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,17.776753,13.438341,21.366542,42.141909,24.320664,63.839106,0.993459,0.778303,1.339895,1.469237,0.723957,2.690735,1.670551,0.752793,3.656931,1.356745,0.723957,2.516498,core_front_9d_rule_0004
14,middle_all_qualified_by_tenor_year,all_qualified_trades,24,2023,2,2,2023-03-17,2023-03-20,24,24,24.0,1.000000,4.464522e+04,22322.609155,22322.609155,21206.760857,23438.457453,inf,0.000000,44645.218310,44645.218310,44645.218310,0,0,0,1860.217430,930.108715,930.108715,883.615036,976.602394,inf,0.000000,1860.217430,1860.217430,1860.217430,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,16.776360,16.577033,16.975687,45.901646,44.045301,47.757990,0.789650,0.769505,0.809795,2.682035,2.426844,2.937226,0.833069,0.753781,0.912357,0.833069,0.753781,0.912357,core_front_9d_rule_0004
15,middle_all_qualified_by_tenor_year,all_qualified_trades,24,2024,17,17,2024-08-05,2024-10-30,24,24,24.0,0.941176,2.039046e+05,11994.386755,13757.861635,-3611.331326,27418.232160,57.462439,-3611.331326,24196.890212,91354.044584,203904.574830,0,0,0,8496.023951,499.766115,573.244235,-150.472139,1142.426340,57.462439,-150.472139,1008.203759,3806.418524,8496.023951,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,13.428079,11.422491,21.321611,59.915229,30.554982,67.986764,0.838235,0.703388,1.229427,1.900097,1.041358,5.381476,2.718892,1.927981,5.625044,1.900097,1.041358,5.381476,core_front_9d_rule_0004
16,middle_all_qualified_by_tenor_year,all_qualified_trades,24,2025,21,21,2025-03-06,2025-11-20,24,24,24.0,0.952381,3.558321e+05,16944.383748,18058.670277,-6858.911357,42988.137121,52.878795,0.000000,58129.949879,142398.565307,335583.571237,0,0,0,14826.335780,706.015990,752.444595,-285.787973,1791.172380,52.878795,0.000000,2422.081245,5933.273554,13982.648802,21,355832.058718,706.015990,-6858.911357,0,0.000000,NaN,NaN,15.541807,10.107217,37.957610,52.408919,21.362549,66.434105,0.837851,0.717721,1.027281,1.520954,0.749146,2.791976,1.726245,1.120023,2.725191,1.442228,0.749146,2.591572,core_front_9d_rule_0004
17,middle_all_qualified_by_tenor_year,all_qualified_trades,24,2026,29,29,2026-02-19,2026-04-29,24,24,24.0,0.620690,-2.058839e+04,-709.944352,14504.025393,-57319.352129,25332.139502,0.942244,-338571.491680,-250626.850425,-336908.356424,-204124.070126,3,0,0,-857.849425,-29.581015,604.334391,-2388.306339,1055.505813,0.942244,-14107.145487,-10442.785434,-14037.848184,-8505.169589,0,0.000000,NaN,NaN,29,-20588.386201,-29.581015,-57319.352129,14.872611,10.991842,18.163660,42.291627,27.717242,66.880743,0.986158,0.722232,1.346525,1.677425,0.752270,3.535008,1.524690,0.773498,2.898805,1.423280,0.752270,2.898805,core_front_9d_rule_0004
18,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,18,2021,2,2,2021-12-03,2021-12-06,18,18,18.0,1.000000,3.958247e+04,19791.234022,19791.234022,17989.097649,21593.370395,inf,0.000000,39582.468043,39582.468043,39582.468043,0,0,0,2199.026002,1099.513001,1099.513001,999.394314,1199.631689,inf,0.000000,2199.026002,2199.026002,2199.026002,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,17.257345,17.209869,17.304820,45.195565,42.150131,48.241000,1.072508,0.924555,1.220460,2.047443,1.327322,2.767565,1.305412,0.827066,1.783759,1.305412,0.827066,1.783759,core_front_9d_rule_0004
19,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,18,2022,17,17,2022-01-24,2022-11-01,18,18,18.0,0.823529,1.674069e+05,9847.463495,21591.020615,-108475.796818,25912.875855,2.352969,-122481.340642,-102716.226706,3611.218618,167406.879419,1,1,0,9300.382190,547.081305,1199.501145,-6026.433157,1439.604214,2.352969,-6804.518925,-5706.457039,200.623257,9300.382190,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,16.463882,13.097864,19.966860,50.408695,25.808804,63.839106,1.049659,0.800880,1.288759,1.519985,0.751588,2.256970,1.584155,0.802440,2.604146,1.375221,0.751588,2.256970,core_front_9d_rule_0004
20,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,18,2023,4,4,2023-03-15,2023-10-13,18,18,18.0,1.000000,6.995399e+04,17488.498030,18223.160113,13286.257619,20221.414273,inf,0.000000,69953.992119,69953.992119,69953.992119,0,0,0,3886.332895,971.583224,1012.397784,738.125423,1123.411904,inf,0.000000,3886.332895,3886.332895,3886.332895,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,15.970486,13.420701,17.660504,44.520317,40.186566,47.757990,0.791174,0.726339,0.846920,2.205840,1.707730,3.193014,0.924537,0.788692,1.116829,0.924537,0.788692,1.116829,core_front_9d_rule_0004
21,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,18,2024,7,7,2024-08-02,2024-12-18,18,18,18.0,1.000000,9.181099e+04,13115.856173,12322.258682,10715.061247,16945.475221,inf,0.000000,62842.684826,91810.993213,91810.993213,0,0,0,5100.610734,728.658676,684.569927,595.281180,941.415290,inf,0.000000,3491.260268,5100.610734,5100.610734,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,14.529620,10.968784,20.662663,53.238942,37.561571,64.006230,0.804891,0.708579,1.015270,1.658718,1.117842,2.343601,2.149917,1.679667,3.080389,1.646114,1.117842,2.343601,core_front_9d_rule_0004
22,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,18,2025,6,6,2025-03-06,2025-10-16,18,18,18.0,1.000000,6.095056e+04,10158.427167,10698.691528,6005.032657,15613.049794,inf,0.000000,45337.513208,60950.563003,60950.563003,0,0,0,3386.142389,564.357065,594.371752,333.612925,867.391655,inf,0.000000,2518.750734,3386.142389,3386.142389,6,60950.563003,564.357065,6005.032657,0,0.000000,NaN,NaN,13.005505,11.198785,17.427237,53.344337,33.946232,66.434105,0.822108,0.728107,1.023856,1.297171,0.741547,2.222767,1.530334,1.088075,1.826998,1.231210,0.741547,1.826998,core_front_9d_rule_0004
23,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,18,2026,18,18,2026-02-19,2026-03-25,18,18,18.0,0.388889,-2.250689e+05,-12503.830459,-9474.803824,-45195.769858,19405.160683,0.297698,-311692.355477,-202522.266450,-315930.254948,-225068.948261,0,0,0,-12503.830459,-694.657248,-526.377990,-2510.876103,1078.064482,0.297698,-17316.241971,-11251.237025,-17551.680830,-12503.830459,0,0.000000,NaN,NaN,18,-225068.948261,-694.657248,-45195.769858,14.484920,11.688019,16.159551,42.051150,34.947365,51.244097,1.002388,0.758954,1.188592,1.753552,0.996408,2.997128,1.499164,0.833267,2.111185,1.460338,0.833267,2.111185,core_front_9d_rule_0004
24,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,21,2021,1,1,2021-12-01,2021-12-01,21,21,21.0,1.000000,2.426302e+04,24263.024480,24263.024480,24263.024480,24263.024480,inf,0.000000,24263.024480,24263.024480,24263.024480,0,0,0,1155.382118,1155.382118,1155.382118,1155.382118,1155.382118,inf,0.000000,1155.382118,1155.382118,1155.382118,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,19.229675,19.229675,19.229675,37.494900,37.494900,37.494900,1.105951,1.105951,1.105951,2.687113,2.687113,2.687113,1.505439,1.505439,1.505439,1.505439,1.505439,1.505439,core_front_9d_rule_0004
25,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,21,2022,8,8,2022-01-20,2022-10-21,21,21,21.0,1.000000,1.608374e+05,20104.670939,23754.668928,4280.379525,28179.541598,inf,0.000000,84863.511092,160837.367511,160837.367511,0,0,0,7658.922262,957.365283,1131.174711,203.827596,1341.882933,inf,0.000000,4041.119576,7658.922262,7658.922262,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,17.432334,16.072547,18.384269,41.601177,26.914078,51.140002,1.012996,0.788745,1.183585,1.553248,1.056191,1.972983,1.823153,1.085055,2.569527,1.472183,1.056191,1.972983,core_front_9d_rule_0004
26,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,21,2024,3,3,2024-09-17,2024-10-30,21,21,21.0,1.000000,3.920189e+04,13067.297123,12396.264410,11944.102311,14861.524648,inf,0.000000,39201.891369,39201.891369,39201.891369,0,0,0,1866.756732,622.252244,590.298305,568.766777,707.691650,inf,0.000000,1866.756732,1866.756732,1866.756732,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,12.504618,12.133041,12.853819,60.259812,56.054373,65.698324,0.832743,0.726998,1.008236,1.810459,1.273078,2.088166,2.583886,2.040964,3.106651,1.810459,1.273078,2.088166,core_front_9d_rule_0004
27,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,21,2025,7,7,2025-04-28,2025-11-20,21,21,21.0,1.000000,1.270303e+05,18147.180641,19432.062725,10440.842371,20644.400206,inf,0.000000,87665.538711,127030.264488,127030.264488,0,0,0,6049.060214,864.151459,925.336320,497.182970,983.066676,inf,0.000000,4174.549462,6049.060214,6049.060214,7,127030.264488,864.151459,10440.842371,0,0.000000,NaN,NaN,14.894771,10.277772,17.042284,53.746385,34.883491,63.090898,0.905090,0.738538,1.071148,1.923823,0.775279,2.730321,2.093157,1.142672,2.904290,1.897262,0.775279,2.730321,core_front_9d_rule_0004
28,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,21,2026,6,6,2026-03-06,2026-04-29,21,21,21.0,0.833333,4.737499e+04,7895.831976,14438.094391,-33182.394118,21022.087549,2.427715,0.000000,32870.966463,47374.991856,47374.991856,0,0,0,2255.951993,375.991999,687.528304,-1580.114006,1001.051788,2.427715,0.000000,1565.284117,2255.951993,2255.951993,0,0.000000,NaN,NaN,6,47374.991856,375.991999,-33182.394118,13.649382,10.833435,16.363520,50.288094,33.149995,66.880743,1.124847,0.948292,1.366911,1.730623,0.764696,3.509786,1.875602,1.212828,2.906640,1.627852,0.764696,2.906640,core_front_9d_rule_0004
29,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,24,2021,1,1,2021-11-24,2021-11-24,24,24,24.0,0.000000,-3.607390e+03,-3607.390045,-3607.390045,-3607.390045,-3607.390045,0.000000,0.000000,-3607.390045,-3607.390045,-3607.390045,0,0,0,-150.307919,-150.307919,-150.307919,-150.307919,-150.307919,0.000000,0.000000,-150.307919,-150.307919,-150.307919,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,11.301584,11.301584,11.301584,65.867281,65.867281,65.867281,0.955058,0.955058,0.955058,2.094651,2.094651,2.094651,0.947092,0.947092,0.947092,0.947092,0.947092,0.947092,core_front_9d_rule_0004
30,middle_primary_by_tenor_year,one_trade_per_bucket_per_date_best_rank,24,2022,44,44,2022-01-26,2022-10-19,24,24,24.0,0.886364,8.721049e+05,19820.566632,26118.009978,-48027.465092,31848.877315,7.292303,-48027.465092,-17563.867069,109928.882744,313627.001530,0,0,0,36337.705492,825.856943,1088.250416,-2001.144379,1327.036555,7.292303,-2001.144379,-731.827795,4580.370114,13067.791730,0,0.000000,NaN,NaN,0,0.000000,NaN,NaN,18.273061,15.571345,21.366542,40.076625,24.320664,61.733862,0.987568,0.778303,1.339895,1.468942,0.723957,2.690735,1.682023,0.752793,3.656931,1.343765,0.723957,2.516498,core_front_9d_rule_0004

Middle state diagnostics:

,diagnostic_label,state_source,forecast_vol_state,trades,unique_trade_dates,date_min,date_max,tenor_min,tenor_max,avg_tenor,win_rate,total_pnl,avg_pnl,median_pnl,worst_trade,best_trade,profit_factor,selected_trade_drawdown,worst_5_trade_sum,worst_10_trade_sum,worst_20_trade_sum,trades_le_neg_50k,trades_le_neg_100k,trades_le_neg_150k,total_pnl_per_day_sum,avg_pnl_per_day,median_pnl_per_day,worst_trade_pnl_per_day,best_trade_pnl_per_day,profit_factor_pnl_per_day,pnl_per_day_drawdown,worst_5_trade_pnl_per_day_sum,worst_10_trade_pnl_per_day_sum,worst_20_trade_pnl_per_day_sum,trades_2025,pnl_2025,avg_pnl_per_day_2025,worst_trade_2025,trades_2026,pnl_2026,avg_pnl_per_day_2026,worst_trade_2026,avg_forecast_vol_pct,min_forecast_vol_pct,max_forecast_vol_pct,avg_RSI14,min_RSI14,max_RSI14,avg_model_vrp_log,min_model_vrp_log,max_model_vrp_log,avg_model_vrp_z_3m,min_model_vrp_z_3m,max_model_vrp_z_3m,avg_model_vrp_z_1y,min_model_vrp_z_1y,max_model_vrp_z_1y,avg_middle_min_z,min_middle_min_z,max_middle_min_z,RSI14_state,model_vrp_log_state,middle_min_z_state,candidate_id
0,middle_by_forecast_vol_state,all_qualified,10.0-11.5,21,11,2021-11-24,2026-04-29,18,24,20.857143,0.904762,2.176270e+05,10363.191119,11036.618960,-3607.390045,14504.025393,31.164054,-7.214780e+03,29308.904567,82612.775789,203122.988115,0,0,0,10614.007465,505.428927,582.576464,-171.780478,690.667876,33.953710,-322.088397,1590.862033,4132.227218,10009.673073,9,93409.944445,507.203504,6898.478535,6,81150.302861,646.352647,11617.233865,10.867874,10.107217,11.422491,64.035460,52.495555,66.880743,0.911229,0.728107,1.073259,1.317358,0.721510,2.343601,1.576146,0.925540,3.080389,1.162093,0.721510,2.343601,NaN,NaN,NaN,core_front_9d_rule_0004
1,middle_by_forecast_vol_state,all_qualified,11.5-13.0,38,17,2024-09-17,2026-03-02,18,24,21.236842,0.657895,1.337093e+04,351.866476,12145.583005,-57319.352129,14861.524648,1.043496,-2.537742e+05,-201900.804997,-215725.162308,-85240.716429,1,0,0,-499.487052,-13.144396,555.045315,-2388.306339,707.691650,0.967259,-12421.977414,-9745.967012,-10760.704697,-4770.041549,6,76095.025465,566.183225,12548.493702,7,-253774.237411,-1774.568202,-57319.352129,12.311915,11.546899,12.967018,60.053848,48.384049,67.986764,0.828661,0.703388,1.116638,1.763703,0.989303,3.073027,2.100439,0.920647,3.248824,1.607650,0.920647,2.353106,NaN,NaN,NaN,core_front_9d_rule_0004
2,middle_by_forecast_vol_state,all_qualified,13.0-14.5,45,22,2022-03-21,2026-04-07,18,24,20.733333,0.488889,-4.787180e+05,-10638.177184,-3391.255199,-56809.083631,21022.087549,0.376203,-6.721173e+05,-246564.815560,-466854.354023,-636554.302588,4,0,0,-22724.432108,-504.987380,-161.488343,-2705.194459,1013.406010,0.384871,-32737.534627,-11798.124605,-22760.893449,-30916.035431,2,35562.994500,910.749598,16130.931775,21,-611831.813815,-1421.293167,-56809.083631,13.749473,13.025074,14.444365,52.777151,42.396310,63.839106,0.924995,0.720125,1.410388,1.875897,0.804190,3.193014,1.817668,0.773498,2.904290,1.542869,0.773498,2.730321,NaN,NaN,NaN,core_front_9d_rule_0004
3,middle_by_forecast_vol_state,all_qualified,14.5-16.0,62,27,2022-03-21,2026-04-06,18,24,21.096774,0.774194,3.145576e+05,5073.510349,17236.804997,-108475.796818,23364.485981,1.643130,-3.095312e+05,-282419.249898,-214203.003571,-56400.978608,3,2,0,15240.266904,245.810757,810.672862,-6026.433157,1298.026999,1.647728,-15049.429472,-13839.076075,-10154.419975,-2856.504454,23,413540.752528,851.892179,14248.032288,27,77156.543206,136.538379,-33182.394118,15.259120,14.513530,15.980893,48.066315,34.947365,61.733862,0.938342,0.701002,1.411423,1.528628,0.724581,3.535008,1.599984,0.758099,2.906640,1.409055,0.724581,2.906640,NaN,NaN,NaN,core_front_9d_rule_0004
4,middle_by_forecast_vol_state,all_qualified,16.0-18.0,139,53,2021-12-03,2026-03-27,18,24,21.021583,0.964029,2.758613e+06,19846.134751,22259.473390,-48027.465092,29474.420756,23.678739,-9.605493e+04,-26471.995133,85060.019733,275629.512564,0,0,0,132628.673137,954.163116,1060.323448,-2287.022147,1465.591899,24.854981,-4288.166526,-1046.876744,4202.094548,13289.334493,13,184312.129916,677.494564,-6858.911357,23,440036.562028,912.059660,8645.779319,16.933814,16.029066,17.970445,42.953384,24.320664,59.487241,1.008438,0.715778,1.379234,1.663384,0.707695,2.937226,1.726925,0.721130,3.656931,1.441125,0.707695,2.516498,NaN,NaN,NaN,core_front_9d_rule_0004
5,middle_by_forecast_vol_state,all_qualified,>18.0,101,37,2021-12-01,2026-03-30,18,24,21.000000,0.920792,2.020540e+06,20005.349439,24910.556057,-44692.201363,42988.137121,11.342442,-1.230053e+05,-110928.869791,-32962.409670,177213.006611,0,0,0,96904.719246,959.452666,1185.840531,-2128.200065,2112.836390,11.730512,-5858.205249,-5235.212479,-1400.677329,8570.949143,3,124007.329257,1983.687639,38031.055016,3,69407.224783,1109.740176,22037.542641,19.892919,18.055899,40.256955,35.811080,21.362549,48.334077,0.963276,0.714245,1.239655,1.476863,0.707622,5.381476,1.608946,0.751210,5.625044,1.383107,0.707622,5.381476,NaN,NaN,NaN,core_front_9d_rule_0004
6,middle_by_forecast_vol_state,primary_selected,10.0-11.5,11,11,2021-11-24,2026-04-29,18,24,20.454545,0.909091,1.097547e+05,9977.700313,10911.006712,-3607.390045,14504.025393,31.424962,0.000000e+00,37455.422178,95250.678055,109754.703447,0,0,0,5524.569525,502.233593,582.576464,-150.307919,690.667876,37.755013,0.000000,1980.883649,4833.901649,5524.569525,7,72163.646029,516.464415,6898.478535,2,28876.188781,687.528304,14372.163389,10.902980,10.107217,11.387067,62.838817,52.495555,66.880743,0.880394,0.728107,1.042162,1.291595,0.741547,2.343601,1.549829,0.947092,3.080389,1.187272,0.741547,2.343601,NaN,NaN,NaN,core_front_9d_rule_0004
7,middle_by_forecast_vol_state,primary_selected,11.5-13.0,12,12,2024-09-17,2026-03-02,18,24,21.250000,0.750000,4.808975e+04,4007.479013,12270.923708,-39615.671891,14861.524648,1.695303,-6.555239e+04,-26149.016035,25430.584601,48089.748159,0,0,0,1644.143211,137.011934,585.709776,-2200.870661,707.691650,1.433551,-3641.799339,-1669.054772,480.095254,1644.143211,0,0.000000,NaN,NaN,2,-65552.388098,-1820.899669,-39615.671891,12.482146,11.688019,12.967018,60.325816,48.647576,67.986764,0.870649,0.708579,1.116638,1.951084,1.273078,2.997128,2.456896,1.366751,3.248824,1.814948,1.273078,2.353106,NaN,NaN,NaN,core_front_9d_rule_0004
8,middle_by_forecast_vol_state,primary_selected,13.0-14.5,21,21,2022-03-21,2026-04-07,18,24,20.000000,0.523810,-1.637705e+05,-7798.596762,1251.676786,-45195.769858,21022.087549,0.441404,-2.897913e+05,-202522.266450,-270359.197003,-184792.619561,0,0,0,-9477.176781,-451.294132,62.585894,-2510.876103,1001.051788,0.397912,-15552.106195,-11251.237025,-14626.769875,-10478.228569,1,19432.062725,925.336320,19432.062725,10,-268769.172179,-1455.105441,-45195.769858,13.748624,13.095311,14.444365,52.188867,42.396310,63.839106,0.932404,0.726339,1.366911,1.915020,0.804190,3.193014,1.828263,0.833267,2.904290,1.561152,0.804190,2.730321,NaN,NaN,NaN,core_front_9d_rule_0004
9,middle_by_forecast_vol_state,primary_selected,14.5-16.0,20,20,2022-07-26,2026-04-06,18,24,20.250000,0.850000,1.372318e+05,6861.590931,17285.730930,-108475.796818,23364.485981,1.938652,-1.084758e+05,-37091.375336,53567.382644,137231.818613,1,1,0,6090.755412,304.537771,805.392143,-6026.433157,1298.026999,1.775011,-6026.433157,-2363.904367,1817.231928,6090.755412,8,146609.175699,833.990495,15613.049794,7,27714.018251,238.248658,-33182.394118,15.373368,14.663067,15.969213,48.362705,34.947365,61.733862,0.939306,0.720180,1.362698,1.472969,0.787836,3.509786,1.606180,0.877893,2.906640,1.389666,0.787836,2.906640,NaN,NaN,NaN,core_front_9d_rule_0004
10,middle_by_forecast_vol_state,primary_selected,16.0-18.0,50,50,2021-12-03,2026-03-27,18,24,21.360000,0.960000,9.518270e+05,19036.539693,22306.832725,-48027.465092,29474.420756,16.892010,-4.802747e+04,46959.569648,160724.665332,360695.167316,0,0,0,44875.859565,897.517191,1025.390594,-2001.144379,1439.604214,17.868311,-2001.144379,2084.111001,7050.140260,15562.363791,5,83634.226964,760.023982,6005.032657,7,128690.452569,870.865055,8645.779319,16.912071,16.065319,17.970445,43.483336,24.320664,59.487241,1.004328,0.715778,1.339895,1.672724,0.723957,2.767565,1.739351,0.752793,3.656931,1.455869,0.723957,2.516498,NaN,NaN,NaN,core_front_9d_rule_0004
11,middle_by_forecast_vol_state,primary_selected,>18.0,35,35,2021-12-01,2026-03-30,18,24,22.971429,0.885714,7.421091e+05,21203.116887,26513.576347,-44692.201363,42988.137121,9.193652,-4.587903e+04,2449.358808,129786.024427,331903.578901,0,0,0,32609.016416,931.686183,1142.426340,-1862.175057,1791.172380,9.640894,-1911.626164,309.028314,6248.865782,14627.881810,1,42988.137121,1791.172380,42988.137121,1,25332.139502,1055.505813,25332.139502,19.802561,18.077315,37.957610,35.899700,21.362549,48.334077,0.973947,0.751548,1.229427,1.520781,0.732019,5.381476,1.687529,0.802440,5.625044,1.427541,0.732019,5.381476,NaN,NaN,NaN,core_front_9d_rule_0004
12,middle_by_RSI14_state,all_qualified,NaN,351,127,2021-12-01,2026-04-07,18,24,20.948718,0.851852,4.509214e+06,12846.764915,20885.059529,-108475.796818,42988.137121,3.603475,-1.100582e+06,-387844.309642,-465211.507187,-804340.738820,8,2,0,216457.739115,616.688715,999.394314,-6026.433157,2112.836390,3.599192,-53372.354016,-19045.459664,-21690.181700,-38674.703212,45,804321.170658,855.570531,-6858.911357,81,-279005.721208,-176.246975,-57319.352129,16.965913,11.274182,40.256955,42.850793,21.362549,59.633904,0.971497,0.701002,1.411423,1.628719,0.707622,5.381476,1.696120,0.721130,5.625044,1.441644,0.707622,5.381476,<=60,NaN,NaN,core_front_9d_rule_0004
13,middle_by_RSI14_state,all_qualified,NaN,28,11,2022-08-02,2025-09-10,18,24,21.321429,0.714286,1.016020e+05,3628.643233,10440.842371,-32569.576286,17403.249421,1.838072,-9.405715e+04,-90665.899079,-62769.641969,-3632.821691,0,0,0,4746.938786,169.533528,473.392027,-1357.065679,966.847190,1.840872,-4135.488434,-3947.085368,-2624.222434,-275.430299,2,20881.684742,466.109034,10440.842371,0,0.000000,NaN,NaN,12.847594,10.277772,15.571345,62.558940,60.003919,63.911999,0.842732,0.736383,1.015270,1.616007,0.749146,2.343601,1.966254,0.758099,3.223647,1.507793,0.749146,2.343601,60-64,NaN,NaN,core_front_9d_rule_0004
14,middle_by_RSI14_state,all_qualified,NaN,15,7,2021-11-24,2025-09-24,18,24,21.800000,0.800000,1.320628e+05,8804.183594,11584.867060,-3611.331326,13631.751390,13.198540,-1.082611e+04,12013.717335,73369.518105,132062.753917,0,0,0,6234.452622,415.630175,531.197014,-171.780478,674.754611,14.192918,-472.560535,634.248787,3648.697652,6234.452622,6,69729.854772,533.150078,10805.456045,0,0.000000,NaN,NaN,11.577857,10.107217,12.967018,64.891482,64.006230,65.867281,0.832383,0.703388,0.972561,1.477787,1.075799,2.094651,1.713284,0.925540,2.473796,1.260416,0.925540,1.744815,64-66,NaN,NaN,core_front_9d_rule_0004
15,middle_by_RSI14_state,all_qualified,NaN,12,4,2024-10-14,2026-04-29,18,24,21.000000,0.833333,1.031114e+05,8592.615188,12548.493702,-12048.089968,14504.025393,5.279159,-1.204809e+04,9412.585691,74103.331468,103111.382254,0,0,0,4724.617067,393.718089,598.193730,-669.338332,690.667876,4.800805,-573.718570,323.647283,3429.614800,4724.617067,3,31995.465939,501.216677,6898.478535,6,81150.302861,646.352647,11617.233865,11.284924,10.485959,12.275641,66.971886,66.434105,67.986764,0.901072,0.729650,1.073259,1.262821,0.721510,2.353106,1.696959,1.181972,3.248824,1.262821,0.721510,2.353106,66-68,NaN,NaN,core_front_9d_rule_0004
16,middle_by_RSI14_state,primary_selected,NaN,127,127,2021-12-01,2026-04-07,18,24,21.236220,0.842520,1.635600e+06,12878.742029,20416.371883,-108475.796818,42988.137121,3.508553,-3.885260e+05,-197285.561652,-358351.426266,-302908.024370,1,1,0,72498.404425,570.853578,1001.051788,-6026.433157,1791.172380,3.164972,-20774.019539,-10696.956646,-19097.652002,-16788.785812,17,314060.985564,845.723299,6005.032657,27,-152584.949956,-347.168590,-45195.769858,16.831290,11.274182,37.957610,43.299340,21.362549,59.633904,0.974627,0.708579,1.366911,1.649335,0.723957,5.381476,1.728563,0.752793,5.625044,1.462475,0.723957,5.381476,<=60,NaN,NaN,core_front_9d_rule_0004
17,middle_by_RSI14_state,primary_selected,NaN,11,11,2022-08-02,2025-09-10,18,24,22.090909,0.909091,8.905505e+04,8095.913400,10440.842371,-3391.255199,14066.438990,27.260202,-3.391255e+03,11606.849734,75499.089358,89055.047405,0,0,0,3914.200961,355.836451,497.182970,-188.403067,684.569927,21.775675,-188.403067,453.902372,3349.369376,3914.200961,1,10440.842371,497.182970,10440.842371,0,0.000000,NaN,NaN,12.833518,10.277772,15.571345,62.576475,60.003919,63.911999,0.851839,0.737249,1.015270,1.676406,0.775279,2.343601,2.110959,0.877893,3.223647,1.575869,0.775279,2.343601,60-64,NaN,NaN,core_front_9d_rule_0004
18,middle_by_RSI14_state,primary_selected,NaN,7,7,2021-11-24,2025-09-24,18,24,21.857143,0.714286,5.075007e+04,7250.009730,11036.618960,-3611.331326,12396.264410,8.030340,-3.611331e+03,28359.745005,50750.068111,50750.068111,0,0,0,2510.348487,358.621212,482.702794,-150.472139,674.754611,9.346127,-150.472139,1577.418357,2510.348487,2510.348487,3,33426.942066,515.358542,10805.456045,0,0.000000,NaN,NaN,11.514589,10.107217,12.967018,64.824070,64.006230,65.867281,0.848854,0.726998,0.955058,1.535231,1.146184,2.094651,1.836985,0.947092,2.473796,1.371294,0.947092,1.744815,64-66,NaN,NaN,core_front_9d_rule_0004
19,middle_by_RSI14_state,primary_selected,NaN,4,4,2024-10-14,2026-04-29,18,24,21.000000,1.000000,4.983646e+04,12459.115177,14216.978390,6898.478535,14504.025393,inf,0.000000e+00,49836.460707,49836.460707,49836.460707,0,0,0,2344.213474,586.053369,635.148395,383.248808,690.667876,inf,0.000000,2344.213474,2344.213474,2344.213474,1,6898.478535,383.248808,6898.478535,2,28876.188781,687.528304,14372.163389,11.313872,10.833435,12.275641,66.971886,66.434105,67.986764,0.928368,0.775177,1.042162,1.376582,0.764696,2.353106,1.868017,1.212828,3.248824,1.376582,0.764696,2.353106,66-68,NaN,NaN,core_front_9d_rule_0004
20,middle_by_model_vrp_log_state,all_qualified,NaN,31,22,2023-10-13,2026-02-23,18,24,21.774194,0.838710,2.712617e+05,8750.378800,12396.264410,-30436.912727,42988.137121,4.421602,-6.556135e+04,-44679.661633,16401.158776,149648.868441,0,0,0,13097.339067,422.494809,582.576464,-1268.204697,2047.054149,4.797802,-2836.259771,-1904.041702,937.215301,7026.630814,14,179254.562051,588.589645,-6858.911357,3,-65561.346374,-945.419924,-30436.912727,14.673645,10.277772,39.348374,54.505908,21.362549,66.434105,0.730474,0.701002,0.749468,1.439466,0.741547,3.193014,1.623701,0.773498,2.536688,1.255805,0.741547,2.147668,NaN,0.70-0.75,NaN,core_front_9d_rule_0004
21,middle_by_model_vrp_log_state,all_qualified,NaN,45,30,2022-01-20,2026-02-27,18,24,20.600000,0.688889,1.541154e+05,3424.787436,11944.102311,-48027.465092,42988.137121,1.458811,-1.368849e+05,-136884.863962,-74270.596895,-28731.899963,0,0,0,7709.634307,171.325207,578.361095,-2287.022147,2112.836390,1.478825,-6630.162154,-6630.162154,-3582.082933,-1237.892080,12,224210.567607,903.678170,6005.032657,5,-136884.863962,-1326.032431,-39413.392878,15.784602,11.198785,40.256955,51.277535,21.362549,67.986764,0.776324,0.751548,0.799080,1.573220,0.707622,2.791976,1.583143,0.721130,2.714217,1.299090,0.707622,2.088166,NaN,0.75-0.80,NaN,core_front_9d_rule_0004
22,middle_by_model_vrp_log_state,all_qualified,NaN,93,47,2021-12-06,2026-03-19,18,24,21.000000,0.827957,1.060430e+06,11402.478468,19405.160683,-56809.083631,29493.521275,3.727118,-2.183175e+05,-192380.768242,-165690.808555,6650.350025,2,0,0,51212.787048,550.675130,924.055271,-2705.194459,1401.169021,3.820784,-10322.789219,-9087.707495,-8068.663659,214.324296,10,178137.562653,852.313176,10911.006712,15,-68906.498661,-246.815358,-56809.083631,16.640064,11.274182,21.673512,46.333575,27.204875,67.986764,0.849151,0.800880,0.897821,1.318294,0.732019,2.937226,1.263205,0.725768,2.794452,1.092617,0.725768,2.244236,NaN,0.80-0.90,NaN,core_front_9d_rule_0004
23,middle_by_model_vrp_log_state,all_qualified,NaN,82,42,2021-11-24,2026-04-28,18,24,21.292683,0.902439,1.093057e+06,13329.966339,19494.314194,-108475.796818,29011.264011,4.530968,-2.570121e+05,-233030.349190,-115976.227540,73582.167024,2,1,0,52404.882443,639.083932,946.869235,-5165.514134,1472.976464,4.718665,-11521.065261,-10521.825079,-5027.029582,4419.906379,12,199944.750637,776.437833,10805.456045,15,208465.251147,631.535115,-25936.716207,15.891702,10.107217,20.240546,47.720964,31.841521,67.986764,0.949499,0.903911,0.999191,1.436862,0.721510,2.690735,1.576136,0.827066,3.248824,1.268990,0.721510,2.619148,NaN,0.90-1.00,NaN,core_front_9d_rule_0004
24,middle_by_model_vrp_log_state,all_qualified,NaN,155,61,2021-12-01,2026-04-29,18,24,20.825806,0.858065,2.267126e+06,14626.617529,23916.576520,-108475.796818,31848.877315,3.926974,-6.538814e+05,-226643.973810,-425587.978910,-643962.272631,4,1,0,107739.104725,695.090998,1102.805400,-6026.433157,1547.835029,3.773777,-32142.214193,-10472.412752,-20414.345273,-31728.917363,8,145380.733163,901.332955,15613.049794,49,-134967.960497,-136.780888,-57319.352129,16.825931,10.485959,21.594673,40.967741,24.320664,66.585933,1.119234,1.000751,1.411423,1.925205,0.884321,5.381476,2.117152,1.204376,5.625044,1.801521,0.884321,5.381476,NaN,>1.00,NaN,core_front_9d_rule_0004
25,middle_by_model_vrp_log_state,primary_selected,NaN,11,11,2023-10-13,2025-09-10,18,24,21.272727,1.000000,1.302635e+05,11842.133372,12396.264410,1502.061450,19202.248344,inf,0.000000e+00,42458.579581,116977.209472,130263.467092,0,0,0,6277.929211,570.720837,595.281180,62.585894,941.415290,inf,0.000000,1991.715066,5539.803788,6277.929211,4,57573.154670,651.668358,10440.842371,0,0.000000,NaN,NaN,13.554160,10.277772,16.450897,56.575749,38.774717,65.698324,0.727435,0.708579,0.744904,1.498615,0.741547,3.193014,1.721028,1.088075,2.315119,1.301851,0.741547,2.147668,NaN,0.70-0.75,NaN,core_front_9d_rule_0004
26,middle_by_model_vrp_log_state,primary_selected,NaN,18,18,2022-01-20,2026-02-27,18,24,20.666667,0.777778,1.081038e+05,6005.764299,11490.360636,-48027.465092,42988.137121,2.134470,-4.802747e+04,-8588.420602,47880.900718,108103.757386,0,0,0,5901.200262,327.844459,590.956137,-2001.144379,1791.172380,2.464579,-2001.144379,-65.660960,2946.015501,5901.200262,6,102776.367094,804.705331,6005.032657,2,-43651.292349,-938.831781,-39413.392878,16.087727,11.198785,37.957610,50.629667,21.362549,66.434105,0.779462,0.751548,0.799080,1.628845,0.723957,2.791976,1.704548,0.752793,2.714217,1.413982,0.723957,2.088166,NaN,0.75-0.80,NaN,core_front_9d_rule_0004
27,middle_by_model_vrp_log_state,primary_selected,NaN,30,30,2022-02-11,2026-03-17,18,24,21.900000,0.766667,3.213805e+05,10712.682134,18980.521575,-44692.201363,29493.521275,3.435960,-5.736871e+04,-28331.066347,49513.937322,182010.117306,0,0,0,14083.506037,469.450201,804.931689,-2134.394384,1228.896720,3.221007,-3187.150365,-1825.706929,1586.523543,7876.332820,4,67674.361299,742.826704,10911.006712,3,-57368.706564,-1062.383455,-38419.098915,16.481605,11.274182,21.366542,47.333336,27.204875,64.006230,0.850422,0.800880,0.897821,1.347297,0.732019,2.110050,1.295430,0.797229,2.712518,1.074659,0.732019,1.774170,NaN,0.80-0.90,NaN,core_front_9d_rule_0004
28,middle_by_model_vrp_log_state,primary_selected,NaN,32,32,2021-11-24,2026-04-28,18,24,22.031250,0.906250,5.165718e+05,16142.868088,19910.766283,-25936.716207,29011.264011,11.554438,-2.593672e+04,14674.978799,95168.646122,319193.548158,0,0,0,23142.525752,723.203930,988.412340,-1440.928678,1241.899559,10.644539,-1440.928678,253.485025,4008.806394,14394.666278,5,81509.765473,728.129917,10805.456045,7,59017.431764,387.802958,-25936.716207,15.861029,10.107217,20.237515,47.109419,31.841521,67.986764,0.944081,0.904951,0.999191,1.454839,0.751588,2.690735,1.588115,0.827066,3.248824,1.296526,0.751588,2.619148,NaN,0.90-1.00,NaN,core_front_9d_rule_0004

Middle 2026 primary selected trade detail:

               candidate_id                       selection_universe trade_date  tenor tenor_bucket  normalized_pnl_dollars  normalized_pnl_per_day  win  forecast_vol_pct      RSI14  model_vrp_log  model_vrp_z_3m  model_vrp_z_1y  middle_min_z  implied_vol_pct  forecast_vol_pct  model_vrp_ratio
0   core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-02-19     18       Middle            -4237.899471             -235.438859  0.0         13.731894  46.444609       0.758954        1.407083        0.833267      0.833267        20.069437         13.731894         2.136041
1   core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-02-20     18       Middle           -25936.716207            -1440.928678  0.0         11.688019  51.244097       0.918587        2.006216        1.366751      1.366751        18.501615         11.688019         2.505748
2   core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-02-23     18       Middle           -14406.785858             -800.376992  0.0         14.187907  44.737667       0.808229        1.591969        0.983769      0.983769        21.253137         14.187907         2.243930
3   core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-02-27     24       Middle           -39413.392878            -1642.224703  0.0         13.262775  48.384049       0.778521        1.833185        0.949348      0.949348        19.574380         13.262775         2.178248
4   core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-02     18       Middle           -39615.671891            -2200.870661  0.0         12.132121  48.647576       1.116638        2.997128        2.002964      2.002964        21.203701         12.132121         3.054568
5   core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-03     18       Middle           -29210.915071            -1622.828615  0.0         13.584563  43.035216       1.133938        2.824338        2.036353      2.036353        23.948434         13.584563         3.107870
6   core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-04     18       Middle           -38419.098915            -2134.394384  0.0         13.517579  48.264262       0.889232        1.757265        1.198309      1.198309        21.085950         13.517579         2.433260
7   core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-05     18       Middle           -32473.930236            -1804.107235  0.0         13.549945  45.000430       1.098570        2.463583        1.885468      1.885468        23.468697         13.549945         2.999873
8   core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-06     21       Middle           -33182.394118            -1580.114006  0.0         15.470518  38.453183       1.362698        3.509786        2.906640      2.906640        30.578135         15.470518         3.906720
9   core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-09     18       Middle           -45195.769858            -2510.876103  0.0         14.398488  43.879944       1.186551        2.377619        2.111185      2.111185        26.059927         14.398488         3.275764
10  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-10     18       Middle           -42977.344179            -2387.630232  0.0         14.431079  42.825712       1.188592        2.248642        2.096352      2.096352        26.145578         14.431079         3.282456
11  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-11     18       Middle           -43456.123262            -2414.229070  0.0         14.444365  42.396310       1.081937        1.817105        1.730875      1.730875        24.810645         14.444365         2.950389
12  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-12     18       Middle             8645.779319              480.321073  1.0         16.159551  35.443933       1.131864        1.896928        1.873636      1.873636        28.458396         16.159551         3.101432
13  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-13     21       Middle            13613.904306              648.281157  1.0         16.363520  33.149995       1.059233        1.765249        1.751764      1.751764        27.789856         16.363520         2.884159
14  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-16     18       Middle              162.701623                9.038979  1.0         15.345755  40.089497       0.925495        1.194953        1.188556      1.188556        24.375690         15.345755         2.523117
15  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-17     18       Middle            -4542.821791             -252.378988  0.0         14.664093  41.710099       0.865800        0.996408        0.993892      0.993892        22.607958         14.664093         2.376907
16  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-18     18       Middle            11304.662853              628.036825  1.0         15.888700  35.977956       0.913355        1.095806        1.134463      1.095806        25.085388         15.888700         2.492671
17  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-19     18       Middle            19405.160683             1078.064482  1.0         15.506099  34.947365       0.905850        1.041103        1.102037      1.041103        24.389638         15.506099         2.474034
18  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-20     24       Middle            21363.317800              890.138242  1.0         16.536777  29.884326       1.012657        1.447716        1.561740      1.447716        27.437620         16.536777         2.752905
19  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-23     18       Middle            19054.854885             1058.603049  1.0         16.122370  37.186678       1.033144        1.305817        1.475451      1.305817        27.025465         16.122370         2.809885
20  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-24     18       Middle            19309.465451             1072.748081  1.0         16.065319  35.857438       1.073374        1.371012        1.586375      1.371012        27.477008         16.065319         2.925231
21  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-25     18       Middle            17521.503664              973.416870  1.0         15.310704  39.231918       1.012873        1.170966        1.385250      1.170966        25.406085         15.310704         2.753500
22  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-26     24       Middle            22664.254087              944.343920  1.0         17.152847  33.164094       0.997612        1.239748        1.458671      1.239748        28.246516         17.152847         2.711798
23  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-27     24       Middle            24038.876720             1001.619863  1.0         17.679228  28.658202       1.119109        1.578137        1.846497      1.578137        30.936745         17.679228         3.062123
24  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-03-30     24       Middle            25332.139502             1055.505813  1.0         18.163660  27.717242       1.032857        1.258812        1.542980      1.258812        30.442856         18.163660         2.809080
25  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-04-06     21       Middle            17045.205336              811.676445  1.0         14.860222  48.153896       0.969786        1.016187        1.309809      1.016187        24.133024         14.860222         2.637381
26  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-04-07     21       Middle            21022.087549             1001.051788  1.0         13.420972  48.504814       1.366911        2.224907        2.552146      2.224907        26.583058         13.420972         3.923214
27  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-04-28     21       Middle            14372.163389              684.388733  1.0         10.947626  66.880743       0.948292        0.764696        1.212828      0.764696        17.588906         10.947626         2.581296
28  core_front_9d_rule_0004  one_trade_per_bucket_per_date_best_rank 2026-04-29     21       Middle            14504.025393              690.667876  1.0         10.833435  66.585933       1.042162        1.102915        1.520425      1.102915        18.241845         10.833435         2.835340

Middle candidate grid — wide:

,candidate_id,candidate_family,candidate_subfamily,candidate_description,locked_model_spec,front_9d_include,front_9d_model_vrp_log,front_9d_model_vrp_z,front_9d_RSI14_max,front_9d_forecast_vol_pct_min,front_12_15_include,front_12_15_model_vrp_log,front_12_15_model_vrp_z,front_12_15_RSI14_max,front_12_15_forecast_vol_pct_min,middle_include,middle_model_vrp_log,middle_model_vrp_z,middle_RSI14_max,middle_forecast_vol_pct_min,back_include,back_model_vrp_log,back_model_vrp_z,back_RSI14_max,back_forecast_vol_pct_min,front_fixed_to_cell12_9d_fv20_rule,back_locked
0,core_middle_rule_0001,core_middle_rule_test,current_middle,"Current Middle rule: log > 0.70, z > 0.70, RSI...",unified_fds_no_min_return,True,0.7,0.65,68.0,20.0,True,0.7,0.65,68.0,14.5,True,0.7,0.7,68.0,10.0,True,0.7,0.7,70.0,8.5,True,True
1,core_middle_rule_0002,core_middle_rule_test,middle_higher_forecast_vol,Middle forecast-vol floor > 11.5.,unified_fds_no_min_return,True,0.7,0.65,68.0,20.0,True,0.7,0.65,68.0,14.5,True,0.7,0.7,68.0,11.5,True,0.7,0.7,70.0,8.5,True,True
2,core_middle_rule_0003,core_middle_rule_test,middle_higher_forecast_vol,Middle forecast-vol floor > 13.0.,unified_fds_no_min_return,True,0.7,0.65,68.0,20.0,True,0.7,0.65,68.0,14.5,True,0.7,0.7,68.0,13.0,True,0.7,0.7,70.0,8.5,True,True
3,core_middle_rule_0004,core_middle_rule_test,middle_higher_forecast_vol,Middle forecast-vol floor > 14.5.,unified_fds_no_min_return,True,0.7,0.65,68.0,20.0,True,0.7,0.65,68.0,14.5,True,0.7,0.7,68.0,14.5,True,0.7,0.7,70.0,8.5,True,True
4,core_middle_rule_0005,core_middle_rule_test,middle_tighter_RSI,Middle RSI < 66.,unified_fds_no_min_return,True,0.7,0.65,68.0,20.0,True,0.7,0.65,68.0,14.5,True,0.7,0.7,66.0,10.0,True,0.7,0.7,70.0,8.5,True,True
5,core_middle_rule_0006,core_middle_rule_test,middle_higher_forecast_vol_and_tighter_RSI,Middle forecast-vol floor > 13.0 and RSI < 66.,unified_fds_no_min_return,True,0.7,0.65,68.0,20.0,True,0.7,0.65,68.0,14.5,True,0.7,0.7,66.0,13.0,True,0.7,0.7,70.0,8.5,True,True

Middle candidate grid — long:

             candidate_id       candidate_family                         candidate_subfamily          locked_model_spec  tenor tenor_bucket  tenor_bucket_order   rule_scope                      rule_type  include_tenor  model_vrp_log  model_vrp_z  model_vrp_z_3m  model_vrp_z_1y  RSI14_max  forecast_vol_pct_min  is_front_9d  is_front_12_15  is_middle_candidate_rule  is_back_locked
0   core_middle_rule_0001  core_middle_rule_test                              current_middle  unified_fds_no_min_return      9        Front                   1     front_9d      fixed_cell12_9d_fv20_rule           True            0.7         0.65            0.65            0.65       68.0                  20.0         True           False                     False           False
1   core_middle_rule_0001  core_middle_rule_test                              current_middle  unified_fds_no_min_return     12        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
2   core_middle_rule_0001  core_middle_rule_test                              current_middle  unified_fds_no_min_return     15        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
3   core_middle_rule_0001  core_middle_rule_test                              current_middle  unified_fds_no_min_return     18       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False                      True           False
4   core_middle_rule_0001  core_middle_rule_test                              current_middle  unified_fds_no_min_return     21       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False                      True           False
5   core_middle_rule_0001  core_middle_rule_test                              current_middle  unified_fds_no_min_return     24       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  10.0        False           False                      True           False
6   core_middle_rule_0001  core_middle_rule_test                              current_middle  unified_fds_no_min_return     27         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
7   core_middle_rule_0001  core_middle_rule_test                              current_middle  unified_fds_no_min_return     30         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
8   core_middle_rule_0001  core_middle_rule_test                              current_middle  unified_fds_no_min_return     33         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
9   core_middle_rule_0002  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return      9        Front                   1     front_9d      fixed_cell12_9d_fv20_rule           True            0.7         0.65            0.65            0.65       68.0                  20.0         True           False                     False           False
10  core_middle_rule_0002  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     12        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
11  core_middle_rule_0002  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     15        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
12  core_middle_rule_0002  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     18       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  11.5        False           False                      True           False
13  core_middle_rule_0002  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     21       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  11.5        False           False                      True           False
14  core_middle_rule_0002  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     24       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  11.5        False           False                      True           False
15  core_middle_rule_0002  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     27         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
16  core_middle_rule_0002  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     30         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
17  core_middle_rule_0002  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     33         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
18  core_middle_rule_0003  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return      9        Front                   1     front_9d      fixed_cell12_9d_fv20_rule           True            0.7         0.65            0.65            0.65       68.0                  20.0         True           False                     False           False
19  core_middle_rule_0003  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     12        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
20  core_middle_rule_0003  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     15        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
21  core_middle_rule_0003  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     18       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  13.0        False           False                      True           False
22  core_middle_rule_0003  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     21       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  13.0        False           False                      True           False
23  core_middle_rule_0003  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     24       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  13.0        False           False                      True           False
24  core_middle_rule_0003  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     27         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
25  core_middle_rule_0003  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     30         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
26  core_middle_rule_0003  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     33         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
27  core_middle_rule_0004  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return      9        Front                   1     front_9d      fixed_cell12_9d_fv20_rule           True            0.7         0.65            0.65            0.65       68.0                  20.0         True           False                     False           False
28  core_middle_rule_0004  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     12        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
29  core_middle_rule_0004  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     15        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
30  core_middle_rule_0004  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     18       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  14.5        False           False                      True           False
31  core_middle_rule_0004  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     21       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  14.5        False           False                      True           False
32  core_middle_rule_0004  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     24       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       68.0                  14.5        False           False                      True           False
33  core_middle_rule_0004  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     27         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
34  core_middle_rule_0004  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     30         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
35  core_middle_rule_0004  core_middle_rule_test                  middle_higher_forecast_vol  unified_fds_no_min_return     33         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
36  core_middle_rule_0005  core_middle_rule_test                          middle_tighter_RSI  unified_fds_no_min_return      9        Front                   1     front_9d      fixed_cell12_9d_fv20_rule           True            0.7         0.65            0.65            0.65       68.0                  20.0         True           False                     False           False
37  core_middle_rule_0005  core_middle_rule_test                          middle_tighter_RSI  unified_fds_no_min_return     12        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
38  core_middle_rule_0005  core_middle_rule_test                          middle_tighter_RSI  unified_fds_no_min_return     15        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
39  core_middle_rule_0005  core_middle_rule_test                          middle_tighter_RSI  unified_fds_no_min_return     18       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       66.0                  10.0        False           False                      True           False
40  core_middle_rule_0005  core_middle_rule_test                          middle_tighter_RSI  unified_fds_no_min_return     21       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       66.0                  10.0        False           False                      True           False
41  core_middle_rule_0005  core_middle_rule_test                          middle_tighter_RSI  unified_fds_no_min_return     24       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       66.0                  10.0        False           False                      True           False
42  core_middle_rule_0005  core_middle_rule_test                          middle_tighter_RSI  unified_fds_no_min_return     27         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
43  core_middle_rule_0005  core_middle_rule_test                          middle_tighter_RSI  unified_fds_no_min_return     30         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
44  core_middle_rule_0005  core_middle_rule_test                          middle_tighter_RSI  unified_fds_no_min_return     33         Back                   3         back               locked_back_rule           True            0.7         0.70            0.70            0.70       70.0                   8.5        False           False                     False            True
45  core_middle_rule_0006  core_middle_rule_test  middle_higher_forecast_vol_and_tighter_RSI  unified_fds_no_min_return      9        Front                   1     front_9d      fixed_cell12_9d_fv20_rule           True            0.7         0.65            0.65            0.65       68.0                  20.0         True           False                     False           False
46  core_middle_rule_0006  core_middle_rule_test  middle_higher_forecast_vol_and_tighter_RSI  unified_fds_no_min_return     12        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
47  core_middle_rule_0006  core_middle_rule_test  middle_higher_forecast_vol_and_tighter_RSI  unified_fds_no_min_return     15        Front                   1  front_12_15  fixed_cell12_front_12_15_rule           True            0.7         0.65            0.65            0.65       68.0                  14.5        False            True                     False           False
48  core_middle_rule_0006  core_middle_rule_test  middle_higher_forecast_vol_and_tighter_RSI  unified_fds_no_min_return     18       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       66.0                  13.0        False           False                      True           False
49  core_middle_rule_0006  core_middle_rule_test  middle_higher_forecast_vol_and_tighter_RSI  unified_fds_no_min_return     21       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       66.0                  13.0        False           False                      True           False
50  core_middle_rule_0006  core_middle_rule_test  middle_higher_forecast_vol_and_tighter_RSI  unified_fds_no_min_return     24       Middle                   2       middle          candidate_middle_rule           True            0.7         0.70            0.70            0.70       66.0                  13.0        False           False                      True           False

Saved outputs:
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\11_middle_weakness_current_middle_by_tenor_20260704_222837.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\11_middle_weakness_current_middle_by_year_20260704_222837.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\11_middle_weakness_current_middle_by_tenor_year_20260704_222837.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\11_middle_weakness_current_middle_state_diagnostics_20260704_222837.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\11_middle_weakness_current_middle_2026_trade_detail_20260704_222837.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\11_middle_weakness_diagnostic_conclusion_20260704_222837.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\11_core_middle_rule_candidate_grid_wide_20260704_222837.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\11_core_middle_rule_candidate_grid_wide_20260704_222837.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\11_core_middle_rule_candidate_grid_long_20260704_222837.csv
  C:\Users\patri\vrp_project\data\processed\vrp_unified_fds_core_signal_threshold_research_v1\11_core_middle_rule_candidate_grid_long_20260704_222837.parquet
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\11_core_middle_rule_candidate_grid_ranges_20260704_222837.json
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\11_core_middle_rule_candidate_grid_validation_20260704_222837.csv
  C:\Users\patri\vrp_project\data\audit\vrp_unified_fds_core_signal_threshold_research_v1\11_core_middle_rule_candidate_grid_manifest_20260704_222837.json

CELL 13 PASSED