In [1]:
# Cell 1: Clean setup and canonical Corsi/HAR parameter-sweep panel
#
# Purpose:
#   Start a clean parameter-sweep workbook using only:
#
#       har_total_simple as the forecast denominator
#
#   This cell:
#       1. Finds the latest Corsi/HAR OOS signal panel.
#       2. Finds the latest naked ATM put outcome file.
#       3. Joins outcomes onto date x tenor rows.
#       4. Adds RSI14 and RV21D from the production feature panel if needed.
#       5. Creates clean, renamed columns for the new sweep.
#       6. Saves the clean panel for this workbook.
#
# Important:
#   No parameters are tested in this cell.
#   No filters are removed.
#   No signal decision is made here.

from pathlib import Path
import numpy as np
import pandas as pd


# -----------------------------
# 1. Project paths
# -----------------------------

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

CORSI_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "forecast_model_corsi_v1"
CORSI_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "forecast_model_corsi_v1"

PARAM_SWEEP_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "corsi_parameter_sweep_clean"
PARAM_SWEEP_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "corsi_parameter_sweep_clean"

PRODUCTION_FEATURE_PANEL_PATH = PROJECT_ROOT / "data" / "processed" / "production_feature_panel_v0_1.parquet"

PARAM_SWEEP_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
PARAM_SWEEP_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

RUN_TIMESTAMP = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")

print("Corsi parameter sweep clean setup")
print(f"Project root:              {PROJECT_ROOT}")
print(f"Corsi processed dir:        {CORSI_PROCESSED_DIR}")
print(f"Corsi audit dir:            {CORSI_AUDIT_DIR}")
print(f"Sweep processed dir:        {PARAM_SWEEP_PROCESSED_DIR}")
print(f"Sweep audit dir:            {PARAM_SWEEP_AUDIT_DIR}")
print(f"Run timestamp:              {RUN_TIMESTAMP}")


# -----------------------------
# 2. Locate latest Corsi OOS signal panel
# -----------------------------

signal_panel_candidates = sorted(
    CORSI_PROCESSED_DIR.glob("corsi_cell12_oos_forecast_vrp_signal_panel_*.parquet")
)

if not signal_panel_candidates:
    raise FileNotFoundError(
        f"No Corsi OOS signal panel found in {CORSI_PROCESSED_DIR}"
    )

SIGNAL_PANEL_PATH = signal_panel_candidates[-1]

print()
print("Selected Corsi signal panel:")
print(SIGNAL_PANEL_PATH)

signal_raw = pd.read_parquet(SIGNAL_PANEL_PATH).copy()

signal_raw.columns = [str(c).strip() for c in signal_raw.columns]

print()
print("Raw Corsi signal panel summary:")
display(pd.DataFrame([{
    "rows": len(signal_raw),
    "columns": len(signal_raw.columns),
    "first_date": pd.to_datetime(signal_raw["date"]).min() if "date" in signal_raw.columns else pd.NaT,
    "last_date": pd.to_datetime(signal_raw["date"]).max() if "date" in signal_raw.columns else pd.NaT,
    "unique_dates": signal_raw["date"].nunique() if "date" in signal_raw.columns else np.nan,
    "unique_tenors": signal_raw["tenor"].nunique() if "tenor" in signal_raw.columns else np.nan,
}]))


# -----------------------------
# 3. Locate latest outcome file
# -----------------------------

outcome_discovery_candidates = sorted(
    CORSI_AUDIT_DIR.glob("corsi_cell11_trade_outcome_file_discovery_*.csv")
)

if not outcome_discovery_candidates:
    raise FileNotFoundError(
        f"No Cell 11 outcome discovery file found in {CORSI_AUDIT_DIR}"
    )

OUTCOME_DISCOVERY_PATH = outcome_discovery_candidates[-1]

print()
print("Selected outcome discovery file:")
print(OUTCOME_DISCOVERY_PATH)

outcome_discovery = pd.read_csv(OUTCOME_DISCOVERY_PATH)
outcome_discovery.columns = [str(c).strip() for c in outcome_discovery.columns]

display(outcome_discovery)

# The discovery file schema may use either:
#   old names: chosen_file / outcome_col / outcome_kind
#   new names: path / chosen_outcome_col / chosen_outcome_kind
#
# Handle both explicitly.

file_col = "chosen_file" if "chosen_file" in outcome_discovery.columns else "path"
chosen_col_col = "outcome_col" if "outcome_col" in outcome_discovery.columns else "chosen_outcome_col"
chosen_kind_col = "outcome_kind" if "outcome_kind" in outcome_discovery.columns else "chosen_outcome_kind"

required_discovery_cols = [
    file_col,
    "date_col",
    "trade_date_col",
    "tenor_col",
    chosen_col_col,
    chosen_kind_col,
]

missing_discovery_cols = [
    c for c in required_discovery_cols
    if c not in outcome_discovery.columns
]

if missing_discovery_cols:
    raise ValueError(f"Outcome discovery file missing required columns: {missing_discovery_cols}")

preferred = outcome_discovery.copy()

# Keep only eligible rows if the column exists.
if "eligible_for_backtest" in preferred.columns:
    preferred = preferred.loc[preferred["eligible_for_backtest"].astype(bool)].copy()

if preferred.empty:
    raise ValueError("No eligible outcome files found in outcome discovery file.")

preferred["_preferred_outcome_col"] = preferred[chosen_col_col].eq("normalized_pnl_dollars")
preferred["_preferred_outcome_kind"] = preferred[chosen_kind_col].eq("pnl")

if "score" in preferred.columns:
    preferred["_score"] = pd.to_numeric(preferred["score"], errors="coerce")
else:
    preferred["_score"] = 0.0

preferred = preferred.sort_values(
    ["_preferred_outcome_col", "_preferred_outcome_kind", "_score"],
    ascending=[False, False, False],
)

chosen_outcome_row = preferred.iloc[0].to_dict()

OUTCOME_PATH = Path(chosen_outcome_row[file_col])
OUTCOME_DATE_COL = chosen_outcome_row.get("date_col", "trade_date")
OUTCOME_TRADE_DATE_COL = chosen_outcome_row.get("trade_date_col", "trade_date")
OUTCOME_TENOR_COL = chosen_outcome_row.get("tenor_col", "tenor")
OUTCOME_VALUE_COL = chosen_outcome_row.get(chosen_col_col, "normalized_pnl_dollars")

print()
print("Chosen outcome file:")
print(OUTCOME_PATH)
print(f"date_col:        {OUTCOME_DATE_COL}")
print(f"trade_date_col:  {OUTCOME_TRADE_DATE_COL}")
print(f"tenor_col:       {OUTCOME_TENOR_COL}")
print(f"outcome_col:     {OUTCOME_VALUE_COL}")

outcome_raw = (
    pd.read_parquet(OUTCOME_PATH)
    if OUTCOME_PATH.suffix.lower() == ".parquet"
    else pd.read_csv(OUTCOME_PATH)
)

outcome_raw.columns = [str(c).strip() for c in outcome_raw.columns]

required_outcome_cols = [OUTCOME_TRADE_DATE_COL, OUTCOME_TENOR_COL, OUTCOME_VALUE_COL]
missing_outcome_cols = [c for c in required_outcome_cols if c not in outcome_raw.columns]

if missing_outcome_cols:
    raise ValueError(f"Outcome file missing required columns: {missing_outcome_cols}")

outcome = outcome_raw[
    [OUTCOME_TRADE_DATE_COL, OUTCOME_TENOR_COL, OUTCOME_VALUE_COL]
].copy()

outcome = outcome.rename(columns={
    OUTCOME_TRADE_DATE_COL: "trade_date",
    OUTCOME_TENOR_COL: "tenor",
    OUTCOME_VALUE_COL: "outcome_value",
})

outcome["trade_date"] = pd.to_numeric(outcome["trade_date"], errors="coerce").astype("Int64")
outcome["tenor"] = pd.to_numeric(outcome["tenor"], errors="coerce").astype("Int64")
outcome["outcome_value"] = pd.to_numeric(outcome["outcome_value"], errors="coerce")

outcome = outcome.dropna(subset=["trade_date", "tenor"])
outcome["trade_date"] = outcome["trade_date"].astype(int)
outcome["tenor"] = outcome["tenor"].astype(int)

duplicate_outcome_rows = outcome.duplicated(["trade_date", "tenor"]).sum()

if duplicate_outcome_rows:
    raise ValueError(f"Outcome file has duplicate trade_date x tenor rows: {duplicate_outcome_rows}")

print()
print("Outcome table summary:")
display(pd.DataFrame([{
    "rows": len(outcome),
    "first_trade_date": outcome["trade_date"].min(),
    "last_trade_date": outcome["trade_date"].max(),
    "unique_trade_dates": outcome["trade_date"].nunique(),
    "unique_tenors": outcome["tenor"].nunique(),
    "duplicate_trade_date_tenor_rows": duplicate_outcome_rows,
    "outcome_non_null_rows": int(outcome["outcome_value"].notna().sum()),
}]))


# -----------------------------
# 4. Normalize signal panel and standardize har_total_simple columns
# -----------------------------

signal = signal_raw.copy()
signal.columns = [str(c).strip() for c in signal.columns]

print()
print("Corsi signal panel columns related to model / forecast / VRP / score:")
diagnostic_cols = [
    c for c in signal.columns
    if any(x in c.lower() for x in ["model", "forecast", "vrp", "score", "z_3m", "z_1y", "har"])
]
display(pd.DataFrame({"column": diagnostic_cols}))

base_required_cols = [
    "date",
    "trade_date",
    "tenor",
    "implied_variance",
    "vix_style_vol",
]

missing_base_cols = [c for c in base_required_cols if c not in signal.columns]

if missing_base_cols:
    raise ValueError(f"Corsi signal panel missing base required columns: {missing_base_cols}")

# Normalize date / tenor keys first.
signal["date"] = pd.to_datetime(signal["date"])
signal["trade_date"] = pd.to_numeric(signal["trade_date"], errors="coerce").astype("Int64")
signal["tenor"] = pd.to_numeric(signal["tenor"], errors="coerce").astype("Int64")

signal = signal.dropna(subset=["trade_date", "tenor"]).copy()
signal["trade_date"] = signal["trade_date"].astype(int)
signal["tenor"] = signal["tenor"].astype(int)

valid_tenors = [9, 12, 15, 18, 21, 24, 27, 30, 33]
signal = signal.loc[signal["tenor"].isin(valid_tenors)].copy()

# Tenor bucket.
# Do this with explicit loc assignment instead of np.select
# to avoid string / NaN dtype promotion issues in newer numpy.
signal["tenor_bucket"] = pd.NA
signal.loc[signal["tenor"].isin([9, 12, 15]), "tenor_bucket"] = "front"
signal.loc[signal["tenor"].isin([18, 21, 24]), "tenor_bucket"] = "middle"
signal.loc[signal["tenor"].isin([27, 30, 33]), "tenor_bucket"] = "back"

signal = signal.replace([np.inf, -np.inf], np.nan)


# -----------------------------
# 4A. Confirm this is a wide panel, not a long model panel
# -----------------------------

model_col_candidates = [
    "model_label",
    "forecast_model",
    "model_name",
    "candidate_model",
]

model_col = next((c for c in model_col_candidates if c in signal.columns), None)

if model_col is not None:
    print()
    print(f"Detected model column: {model_col}")
    model_values = sorted(signal[model_col].dropna().astype(str).unique())
    display(pd.DataFrame({model_col: model_values}))

    model_lower = signal[model_col].astype(str).str.lower()

    har_total_mask = (
        model_lower.eq("har_total")
        | model_lower.eq("har_total_simple")
        | model_lower.str.contains("har_total_simple", na=False)
        | (
            model_lower.str.contains("har_total", na=False)
            & ~model_lower.str.contains("implied", na=False)
        )
    )

    if har_total_mask.any():
        before_rows = len(signal)
        signal = signal.loc[har_total_mask].copy()
        after_rows = len(signal)

        print()
        print(f"Filtered to har_total / har_total_simple rows: {after_rows:,} of {before_rows:,}")
    else:
        raise ValueError(
            f"Found model column '{model_col}', but no har_total / har_total_simple rows were detected."
        )
else:
    print()
    print("No model-label column detected. Treating panel as wide model panel.")


# -----------------------------
# 4B. Standardize har_total_simple forecast / VRP / z-score columns
# -----------------------------

def first_existing_col(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    return None


col_map = {
    "forecast_variance_har_total": first_existing_col(signal, [
        "forecast_variance_har_total_oos",
        "forecast_variance_har_total",
        "har_total_forecast_variance",
    ]),
    "forecast_vol_har_total": first_existing_col(signal, [
        "forecast_vol_har_total_oos",
        "forecast_vol_har_total",
        "har_total_forecast_vol",
    ]),
    "vrp_log_har_total": first_existing_col(signal, [
        "vrp_log_har_total_oos",
        "vrp_log_har_total",
        "score_har_total_raw_vrp_log",
        "har_total_vrp_log",
    ]),
    "vrp_z_3m_har_total": first_existing_col(signal, [
        "vrp_z_3m_har_total_oos_window",
        "vrp_z_3m_har_total",
        "score_har_total_z_3m",
        "har_total_vrp_z_3m",
    ]),
    "vrp_z_1y_har_total": first_existing_col(signal, [
        "vrp_z_1y_har_total_oos_window",
        "vrp_z_1y_har_total",
        "score_har_total_z_1y",
        "har_total_vrp_z_1y",
    ]),
}

print()
print("har_total_simple column mapping:")
display(pd.DataFrame([
    {"standard_column": k, "source_column": v}
    for k, v in col_map.items()
]))

missing_mapped_cols = [k for k, v in col_map.items() if v is None]

if missing_mapped_cols:
    raise ValueError(
        "Could not map required har_total_simple columns. "
        f"Missing standard columns: {missing_mapped_cols}. "
        "The diagnostic column table above shows what exists in the file."
    )

# Create the standard column names expected by the rest of Cell 1.
for standard_col, source_col in col_map.items():
    signal[standard_col] = pd.to_numeric(signal[source_col], errors="coerce")

# If forecast vol is missing, recompute from variance.
if signal["forecast_vol_har_total"].isna().all():
    signal["forecast_vol_har_total"] = np.sqrt(signal["forecast_variance_har_total"]) * 100.0

# Hard check: the denominator must be positive.
bad_forecast_rows = signal["forecast_variance_har_total"].le(0).sum()

if bad_forecast_rows:
    raise ValueError(f"Non-positive har_total forecast variance rows detected: {bad_forecast_rows}")

# Hard check: one row per trade_date x tenor.
duplicate_signal_rows = signal.duplicated(["trade_date", "tenor"]).sum()

if duplicate_signal_rows:
    dup_sample = (
        signal.loc[signal.duplicated(["trade_date", "tenor"], keep=False)]
        .sort_values(["trade_date", "tenor"])
        .head(20)
    )
    display(dup_sample)
    raise ValueError(f"Signal panel has duplicate trade_date x tenor rows after har_total standardization: {duplicate_signal_rows}")

print()
print("Standardized har_total_simple signal panel summary:")
display(pd.DataFrame([{
    "rows": len(signal),
    "first_date": signal["date"].min(),
    "last_date": signal["date"].max(),
    "unique_dates": signal["date"].nunique(),
    "unique_tenors": signal["tenor"].nunique(),
    "forecast_variance_non_null": int(signal["forecast_variance_har_total"].notna().sum()),
    "forecast_vol_non_null": int(signal["forecast_vol_har_total"].notna().sum()),
    "vrp_log_non_null": int(signal["vrp_log_har_total"].notna().sum()),
    "z_3m_non_null": int(signal["vrp_z_3m_har_total"].notna().sum()),
    "z_1y_non_null": int(signal["vrp_z_1y_har_total"].notna().sum()),
}]))

# -----------------------------
# 5. Add RSI14 / RV21D from production feature panel if needed
# -----------------------------

needs_prod_join = ("rsi14" not in signal.columns) or ("rv21d" not in signal.columns)

if needs_prod_join:
    if not PRODUCTION_FEATURE_PANEL_PATH.exists():
        raise FileNotFoundError(
            f"Need rsi14/rv21d but production feature panel does not exist: {PRODUCTION_FEATURE_PANEL_PATH}"
        )

    print()
    print("Adding RSI14 / RV21D from production feature panel:")
    print(PRODUCTION_FEATURE_PANEL_PATH)

    prod = pd.read_parquet(PRODUCTION_FEATURE_PANEL_PATH).copy()
    prod.columns = [str(c).strip() for c in prod.columns]

    prod["trade_date"] = pd.to_numeric(prod["trade_date"], errors="coerce").astype("Int64")
    prod["tenor"] = pd.to_numeric(prod["tenor"], errors="coerce").astype("Int64")

    prod = prod.dropna(subset=["trade_date", "tenor"])
    prod["trade_date"] = prod["trade_date"].astype(int)
    prod["tenor"] = prod["tenor"].astype(int)

    prod_cols = [
        "trade_date",
        "tenor",
        "spx_close",
        "spx_log_return",
        "rv21d",
        "rsi14",
    ]

    prod_cols = [c for c in prod_cols if c in prod.columns]

    prod_state = prod[prod_cols].drop_duplicates(["trade_date", "tenor"]).copy()

    # Drop any overlapping state columns first so the join is clean.
    overlap_cols = [c for c in prod_state.columns if c in signal.columns and c not in ["trade_date", "tenor"]]
    if overlap_cols:
        signal = signal.drop(columns=overlap_cols)

    signal = signal.merge(
        prod_state,
        on=["trade_date", "tenor"],
        how="left",
        validate="one_to_one",
    )

else:
    print()
    print("RSI14 and RV21D already present in Corsi signal panel.")


# -----------------------------
# 6. Join outcomes and filter to available outcome range
# -----------------------------

outcome_min_trade_date = int(outcome["trade_date"].min())
outcome_max_trade_date = int(outcome["trade_date"].max())

signal_before_outcome_filter_rows = len(signal)

signal = signal.loc[
    signal["trade_date"].between(outcome_min_trade_date, outcome_max_trade_date)
].copy()

signal_after_outcome_filter_rows = len(signal)

panel = signal.merge(
    outcome,
    on=["trade_date", "tenor"],
    how="left",
    validate="one_to_one",
)

panel["has_outcome"] = panel["outcome_value"].notna()


# -----------------------------
# 7. Build clean canonical columns
# -----------------------------

clean_panel = pd.DataFrame({
    "date": panel["date"],
    "trade_date": panel["trade_date"],
    "tenor": panel["tenor"],
    "tenor_bucket": panel["tenor_bucket"],

    "implied_variance": pd.to_numeric(panel["implied_variance"], errors="coerce"),
    "vix_style_vol": pd.to_numeric(panel["vix_style_vol"], errors="coerce"),

    "forecast_model": "har_total_simple",
    "forecast_variance": pd.to_numeric(panel["forecast_variance_har_total"], errors="coerce"),
    "forecast_vol": pd.to_numeric(panel["forecast_vol_har_total"], errors="coerce"),

    "vrp_log": pd.to_numeric(panel["vrp_log_har_total"], errors="coerce"),
    "vrp_z_3m": pd.to_numeric(panel["vrp_z_3m_har_total"], errors="coerce"),
    "vrp_z_1y": pd.to_numeric(panel["vrp_z_1y_har_total"], errors="coerce"),

    "rv21d": pd.to_numeric(panel["rv21d"], errors="coerce"),
    "rsi14": pd.to_numeric(panel["rsi14"], errors="coerce"),

    "outcome_value": pd.to_numeric(panel["outcome_value"], errors="coerce"),
    "has_outcome": panel["has_outcome"].astype(bool),
})

# Optional state columns if available.
for optional_col in ["spx_close", "spx_log_return"]:
    if optional_col in panel.columns:
        clean_panel[optional_col] = pd.to_numeric(panel[optional_col], errors="coerce")

clean_panel = clean_panel.replace([np.inf, -np.inf], np.nan)

clean_panel["is_parameter_sweep_eligible"] = (
    clean_panel["tenor"].isin(valid_tenors)
    & clean_panel["tenor_bucket"].notna()
    & clean_panel["implied_variance"].gt(0)
    & clean_panel["forecast_variance"].gt(0)
    & clean_panel["vrp_log"].notna()
    & clean_panel["vrp_z_3m"].notna()
    & clean_panel["vrp_z_1y"].notna()
    & clean_panel["rv21d"].notna()
    & clean_panel["rsi14"].notna()
    & clean_panel["has_outcome"]
)

duplicate_clean_rows = clean_panel.duplicated(["trade_date", "tenor"]).sum()

if duplicate_clean_rows:
    raise ValueError(f"Clean panel has duplicate trade_date x tenor rows: {duplicate_clean_rows}")


# -----------------------------
# 8. Validation summaries
# -----------------------------

summary = pd.DataFrame([{
    "raw_signal_rows": len(signal_raw),
    "signal_rows_before_outcome_filter": signal_before_outcome_filter_rows,
    "signal_rows_after_outcome_filter": signal_after_outcome_filter_rows,
    "clean_panel_rows": len(clean_panel),
    "first_date": clean_panel["date"].min(),
    "last_date": clean_panel["date"].max(),
    "unique_dates": clean_panel["date"].nunique(),
    "unique_tenors": clean_panel["tenor"].nunique(),
    "outcome_rows": int(clean_panel["has_outcome"].sum()),
    "outcome_coverage_pct": float(clean_panel["has_outcome"].mean()),
    "sweep_eligible_rows": int(clean_panel["is_parameter_sweep_eligible"].sum()),
    "sweep_eligible_pct": float(clean_panel["is_parameter_sweep_eligible"].mean()),
    "duplicate_trade_date_tenor_rows": int(duplicate_clean_rows),
}])

availability = []

for col in [
    "implied_variance",
    "vix_style_vol",
    "forecast_variance",
    "forecast_vol",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rv21d",
    "rsi14",
    "outcome_value",
]:
    availability.append({
        "column": col,
        "non_null_rows": int(clean_panel[col].notna().sum()),
        "non_null_pct": float(clean_panel[col].notna().mean()),
        "min": clean_panel[col].min(skipna=True),
        "median": clean_panel[col].median(skipna=True),
        "max": clean_panel[col].max(skipna=True),
    })

availability = pd.DataFrame(availability)

bucket_summary = (
    clean_panel
    .groupby("tenor_bucket")
    .agg(
        rows=("date", "size"),
        unique_dates=("date", "nunique"),
        unique_tenors=("tenor", "nunique"),
        outcome_rows=("has_outcome", "sum"),
        eligible_rows=("is_parameter_sweep_eligible", "sum"),
        mean_vrp_log=("vrp_log", "mean"),
        median_vrp_log=("vrp_log", "median"),
        mean_z_3m=("vrp_z_3m", "mean"),
        mean_z_1y=("vrp_z_1y", "mean"),
        mean_rv21d=("rv21d", "mean"),
        mean_rsi14=("rsi14", "mean"),
    )
    .reset_index()
)

print()
print("Clean panel summary:")
display(summary)

print()
print("Column availability / distribution:")
display(availability)

print()
print("Bucket summary:")
display(bucket_summary)

print()
print("Sample clean panel:")
display(clean_panel.head(20))


# -----------------------------
# 9. Save clean panel and audit files
# -----------------------------

safe_start = clean_panel["date"].min().strftime("%Y%m%d")
safe_end = clean_panel["date"].max().strftime("%Y%m%d")

clean_panel_path = (
    PARAM_SWEEP_PROCESSED_DIR
    / f"02_corsi_parameter_sweep_clean_panel_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.parquet"
)

summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell1_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

availability_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell1_availability_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

bucket_summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell1_bucket_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

clean_panel.to_parquet(clean_panel_path, index=False)
summary.to_csv(summary_path, index=False)
availability.to_csv(availability_path, index=False)
bucket_summary.to_csv(bucket_summary_path, index=False)

print()
print("Cell 1 outputs saved:")
print(f"Clean panel:          {clean_panel_path}")
print(f"Summary:              {summary_path}")
print(f"Availability:         {availability_path}")
print(f"Bucket summary:       {bucket_summary_path}")

print()
print("Cell 1 complete.")

Corsi parameter sweep clean setup
Project root:              C:\Users\patri\vrp_project
Corsi processed dir:        C:\Users\patri\vrp_project\data\processed\forecast_model_corsi_v1
Corsi audit dir:            C:\Users\patri\vrp_project\data\audit\forecast_model_corsi_v1
Sweep processed dir:        C:\Users\patri\vrp_project\data\processed\corsi_parameter_sweep_clean
Sweep audit dir:            C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean
Run timestamp:              20260704_085138

Selected Corsi signal panel:
C:\Users\patri\vrp_project\data\processed\forecast_model_corsi_v1\corsi_cell12_oos_forecast_vrp_signal_panel_20200102_20260623_utp_cta_20260703_211350.parquet

Raw Corsi signal panel summary:

    rows  columns first_date  last_date  unique_dates  unique_tenors
0  14565       65 2020-01-02 2026-06-23          1626              9

Selected outcome discovery file:
C:\Users\patri\vrp_project\data\audit\forecast_model_corsi_v1\corsi_cell11_trade_outcome_file_discovery_20180724_20260610_utp_cta_20260703_211350.csv

,path,rows_est,columns,date_col,trade_date_col,tenor_col,pnl_cols,return_cols,chosen_outcome_col,chosen_outcome_kind,has_outcome_col,coverage_pct_sample,score,eligible_for_backtest,read_error,parse_error
0,C:\Users\patri\vrp_project\data\processed\put_...,18099,55,trade_date,trade_date,tenor,"short_option_pnl_points, normalized_pnl_dollar...",NaN,normalized_pnl_dollars,pnl,True,1.0,122.0,True,NaN,NaN
1,C:\Users\patri\vrp_project\data\processed\put_...,18099,79,trade_date,trade_date,tenor,"short_option_pnl_points, normalized_pnl_dollar...",NaN,normalized_pnl_dollars,pnl,True,1.0,116.0,True,NaN,NaN
2,C:\Users\patri\vrp_project\data\processed\stag...,18144,48,date,trade_date,target_days,NaN,"trailing_num_returns, forward_num_returns, spx...",spx_log_return,return,True,1.0,104.0,True,NaN,NaN
3,C:\Users\patri\vrp_project\data\processed\stag...,18144,48,date,trade_date,target_days,NaN,"trailing_num_returns, forward_num_returns, spx...",spx_log_return,return,True,1.0,104.0,True,NaN,NaN
4,C:\Users\patri\vrp_project\data\processed\stag...,18144,57,date,trade_date,tenor,NaN,"spx_log_return, trailing_num_returns, forward_...",spx_log_return,return,True,1.0,104.0,True,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,C:\Users\patri\vrp_project\data\audit\locked_2...,682,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,-100.0,False,NaN,NaN
275,C:\Users\patri\vrp_project\data\audit\locked_2...,16,11,NaN,NaN,avg_selected_tenor,"avg_pnl_per_day, total_pnl, worst_trade_pnl, w...",NaN,total_pnl,pnl,True,NaN,-100.0,False,NaN,NaN
276,C:\Users\patri\vrp_project\data\audit\locked_2...,6,10,overlap_trade_dates,NaN,same_selected_tenor_dates,NaN,NaN,NaN,NaN,False,0.0,-100.0,False,NaN,NaN
277,C:\Users\patri\vrp_project\data\audit\locked_2...,2500,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,-100.0,False,NaN,NaN
278,C:\Users\patri\vrp_project\data\audit\locked_2...,7240,36,NaN,NaN,NaN,"mean_sized_pnl_per_day, median_sized_pnl_per_d...",NaN,mean_sized_pnl_per_day,pnl,True,NaN,-100.0,False,NaN,NaN

Chosen outcome file:
C:\Users\patri\vrp_project\data\processed\put_candidate_universe_pricing_v0_1.parquet
date_col:        trade_date
trade_date_col:  trade_date
tenor_col:       tenor
outcome_col:     normalized_pnl_dollars

Outcome table summary:

,rows,first_trade_date,last_trade_date,unique_trade_dates,unique_tenors,duplicate_trade_date_tenor_rows,outcome_non_null_rows
0,18099,20180625,20260625,2011,9,0,17946

Corsi signal panel columns related to model / forecast / VRP / score:

                                        column
0                            forecast_variance
1                                 forecast_vol
2                              vrp_log_current
3                  vrp_z_3m_current_production
4                  vrp_z_1y_current_production
5            forecast_variance_har_implied_oos
6              forecast_variance_har_total_oos
7                 forecast_vol_har_implied_oos
8                   forecast_vol_har_total_oos
9                      vrp_log_har_implied_oos
10                       vrp_log_har_total_oos
11                           vrp_ratio_current
12                   vrp_ratio_har_implied_oos
13                     vrp_ratio_har_total_oos
14                 vrp_variance_spread_current
15         vrp_variance_spread_har_implied_oos
16           vrp_variance_spread_har_total_oos
17          vrp_log_current_mean_3m_oos_window
18           vrp_log_current_std_3m_oos_window
19                 vrp_z_3m_current_oos_window
20          vrp_log_current_mean_1y_oos_window
21           vrp_log_current_std_1y_oos_window
22                 vrp_z_1y_current_oos_window
23  vrp_log_har_implied_oos_mean_3m_oos_window
24   vrp_log_har_implied_oos_std_3m_oos_window
25             vrp_z_3m_har_implied_oos_window
26  vrp_log_har_implied_oos_mean_1y_oos_window
27   vrp_log_har_implied_oos_std_1y_oos_window
28             vrp_z_1y_har_implied_oos_window
29    vrp_log_har_total_oos_mean_3m_oos_window
30     vrp_log_har_total_oos_std_3m_oos_window
31               vrp_z_3m_har_total_oos_window
32    vrp_log_har_total_oos_mean_1y_oos_window
33     vrp_log_har_total_oos_std_1y_oos_window
34               vrp_z_1y_har_total_oos_window
35                   score_current_raw_vrp_log
36                          score_current_z_3m
37                          score_current_z_1y
38                   score_current_max_z_3m_1y
39                   score_current_avg_z_3m_1y
40                   score_current_min_z_3m_1y
41               score_har_implied_raw_vrp_log
42                      score_har_implied_z_3m
43                      score_har_implied_z_1y
44               score_har_implied_max_z_3m_1y
45               score_har_implied_avg_z_3m_1y
46               score_har_implied_min_z_3m_1y
47                 score_har_total_raw_vrp_log
48                        score_har_total_z_3m
49                        score_har_total_z_1y
50                 score_har_total_max_z_3m_1y
51                 score_har_total_avg_z_3m_1y
52                 score_har_total_min_z_3m_1y

No model-label column detected. Treating panel as wide model panel.

har_total_simple column mapping:

               standard_column                    source_column
0  forecast_variance_har_total  forecast_variance_har_total_oos
1       forecast_vol_har_total       forecast_vol_har_total_oos
2            vrp_log_har_total            vrp_log_har_total_oos
3           vrp_z_3m_har_total    vrp_z_3m_har_total_oos_window
4           vrp_z_1y_har_total    vrp_z_1y_har_total_oos_window

Standardized har_total_simple signal panel summary:

,rows,first_date,last_date,unique_dates,unique_tenors,forecast_variance_non_null,forecast_vol_non_null,vrp_log_non_null,z_3m_non_null,z_1y_non_null
0,14565,2020-01-02,2026-06-23,1626,9,14565,14565,14565,14304,13440

Adding RSI14 / RV21D from production feature panel:
C:\Users\patri\vrp_project\data\processed\production_feature_panel_v0_1.parquet

Clean panel summary:

,raw_signal_rows,signal_rows_before_outcome_filter,signal_rows_after_outcome_filter,clean_panel_rows,first_date,last_date,unique_dates,unique_tenors,outcome_rows,outcome_coverage_pct,sweep_eligible_rows,sweep_eligible_pct,duplicate_trade_date_tenor_rows
0,14565,14565,14565,14565,2020-01-02,2026-06-23,1626,9,14499,0.995469,13374,0.918229,0

Column availability / distribution:

,column,non_null_rows,non_null_pct,min,median,max
0,implied_variance,14565,1.000000,0.008055,0.034007,1.146081
1,vix_style_vol,14565,1.000000,8.974699,18.440924,107.055162
2,forecast_variance,14565,1.000000,0.004954,0.019311,0.180214
3,forecast_vol,14565,1.000000,7.038218,13.896564,42.451580
4,vrp_log,14565,1.000000,-0.805063,0.550446,2.106911
5,vrp_z_3m,14304,0.982080,-4.542029,0.021842,4.129260
6,vrp_z_1y,13440,0.922760,-4.660686,-0.113547,4.328655
7,rv21d,14565,1.000000,5.418121,13.928748,97.555150
8,rsi14,14565,1.000000,19.164013,57.271438,82.900307
9,outcome_value,14499,0.995469,-306182.537690,10531.711636,85703.628889

Bucket summary:

,tenor_bucket,rows,unique_dates,unique_tenors,outcome_rows,eligible_rows,mean_vrp_log,median_vrp_log,mean_z_3m,mean_z_1y,mean_rv21d,mean_rsi14
0,back,4837,1615,3,4815,4440,0.600850,0.549459,0.017983,-0.125573,17.068347,55.683280
1,front,4873,1626,3,4852,4477,0.594017,0.556620,-0.007766,-0.134758,17.046819,55.673881
2,middle,4855,1620,3,4832,4457,0.592551,0.543285,0.011142,-0.129286,17.051588,55.683432

Sample clean panel:

,date,trade_date,tenor,tenor_bucket,implied_variance,vix_style_vol,forecast_model,forecast_variance,forecast_vol,vrp_log,vrp_z_3m,vrp_z_1y,rv21d,rsi14,outcome_value,has_outcome,spx_close,spx_log_return,is_parameter_sweep_eligible
0,2020-01-02,20200102,9,front,0.011050,10.511905,har_total_simple,0.010737,10.361778,0.028769,NaN,NaN,7.084495,75.483183,4266.617555,True,3257.85,0.008344,False
1,2020-01-02,20200102,12,front,0.012187,11.039263,har_total_simple,0.011029,10.501803,0.099823,NaN,NaN,7.084495,75.483183,6445.968967,True,3257.85,0.008344,False
2,2020-01-02,20200102,15,front,0.012860,11.340214,har_total_simple,0.011279,10.620104,0.131213,NaN,NaN,7.084495,75.483183,6445.968967,True,3257.85,0.008344,False
3,2020-01-02,20200102,18,middle,0.013239,11.505885,har_total_simple,0.011507,10.727108,0.140169,NaN,NaN,7.084495,75.483183,6445.968967,True,3257.85,0.008344,False
4,2020-01-02,20200102,21,middle,0.013509,11.622776,har_total_simple,0.011712,10.822217,0.142731,NaN,NaN,7.084495,75.483183,8256.979296,True,3257.85,0.008344,False
5,2020-01-02,20200102,24,middle,0.014163,11.900700,har_total_simple,0.011904,10.910424,0.173757,NaN,NaN,7.084495,75.483183,8256.979296,True,3257.85,0.008344,False
6,2020-01-02,20200102,27,back,0.014872,12.194919,har_total_simple,0.011945,10.929427,0.219121,NaN,NaN,7.084495,75.483183,1418.113173,True,3257.85,0.008344,False
7,2020-01-02,20200102,30,back,0.015482,12.442864,har_total_simple,0.012117,11.007830,0.245081,NaN,NaN,7.084495,75.483183,1418.113173,True,3257.85,0.008344,False
8,2020-01-02,20200102,33,back,0.016062,12.673517,har_total_simple,0.012283,11.082960,0.268211,NaN,NaN,7.084495,75.483183,12308.731218,True,3257.85,0.008344,False
9,2020-01-03,20200103,9,front,0.016851,12.981207,har_total_simple,0.018259,13.512570,-0.080235,NaN,NaN,7.152270,65.738991,4853.393511,True,3234.85,-0.007085,False
10,2020-01-03,20200103,12,front,0.017392,13.187857,har_total_simple,0.018756,13.695174,-0.075494,NaN,NaN,7.152270,65.738991,7110.066927,True,3234.85,-0.007085,False
11,2020-01-03,20200103,15,front,0.017795,13.339849,har_total_simple,0.019181,13.849447,-0.074979,NaN,NaN,7.152270,65.738991,7110.066927,True,3234.85,-0.007085,False
12,2020-01-03,20200103,18,middle,0.018153,13.473389,har_total_simple,0.019569,13.988988,-0.075108,NaN,NaN,7.152270,65.738991,9335.827009,True,3234.85,-0.007085,False
13,2020-01-03,20200103,21,middle,0.018409,13.567971,har_total_simple,0.019918,14.113018,-0.078771,NaN,NaN,7.152270,65.738991,9335.827009,True,3234.85,-0.007085,False
14,2020-01-03,20200103,24,middle,0.019191,13.853168,har_total_simple,0.020244,14.228047,-0.053402,NaN,NaN,7.152270,65.738991,9335.827009,True,3234.85,-0.007085,False
15,2020-01-03,20200103,27,back,0.019799,14.070993,har_total_simple,0.020314,14.252829,-0.025680,NaN,NaN,7.152270,65.738991,10269.409710,True,3234.85,-0.007085,False
16,2020-01-03,20200103,30,back,0.020285,14.242613,har_total_simple,0.020607,14.355071,-0.015730,NaN,NaN,7.152270,65.738991,10269.409710,True,3234.85,-0.007085,False
17,2020-01-03,20200103,33,back,0.020682,14.381397,har_total_simple,0.020889,14.453047,-0.009940,NaN,NaN,7.152270,65.738991,13138.167148,True,3234.85,-0.007085,False
18,2020-01-06,20200106,9,front,0.015154,12.310232,har_total_simple,0.015133,12.301548,0.001411,NaN,NaN,7.011519,67.953032,6253.311483,True,3246.28,0.003527,False
19,2020-01-06,20200106,12,front,0.015421,12.418318,har_total_simple,0.015545,12.467787,-0.007951,NaN,NaN,7.011519,67.953032,6253.311483,True,3246.28,0.003527,False

Cell 1 outputs saved:
Clean panel:          C:\Users\patri\vrp_project\data\processed\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_panel_20200102_20260623_20260704_085138.parquet
Summary:              C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell1_summary_20200102_20260623_20260704_085138.csv
Availability:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell1_availability_20200102_20260623_20260704_085138.csv
Bucket summary:       C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell1_bucket_summary_20200102_20260623_20260704_085138.csv

Cell 1 complete.

In [2]:
# Cell 2: Define Phase 1 starting parameter grid only
#
# Approved scope:
#   - Define the Phase 1 Core and Secondary parameter grids.
#   - Enforce bucket-shape constraints.
#   - Save the grid/spec files for later testing.
#
# Not included in this cell:
#   - No outcome testing.
#   - No candidate-pool audit.
#   - No Core/Secondary combination.
#   - No tenor selection.
#   - No sizing.
#   - No final ranking.
#
# Denominator:
#   har_total_simple
#
# Parameters included:
#   VRP log
#   3m z-score
#   1y z-score
#   RSI cap
#   RV21D floor
#
# Phase 1 rule:
#   3m z-score threshold = 1y z-score threshold within each bucket.

from pathlib import Path
import itertools
import pandas as pd


# -----------------------------
# 1. Paths
# -----------------------------

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

PARAM_SWEEP_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "corsi_parameter_sweep_clean"
PARAM_SWEEP_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

RUN_TIMESTAMP = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")

print("Cell 2: Define Phase 1 starting parameter grid only")
print(f"Project root:      {PROJECT_ROOT}")
print(f"Audit dir:         {PARAM_SWEEP_AUDIT_DIR}")
print(f"Run timestamp:     {RUN_TIMESTAMP}")


# -----------------------------
# 2. Approved Phase 1 grid
# -----------------------------
#
# Format:
#   (Front, Middle, Back)
#
# Rules:
#   VRP log:    Front <= Middle <= Back
#   z-score:    Front <= Middle <= Back
#   RV21D:      Front <= Middle <= Back
#   RSI cap:    Front >= Middle >= Back
#
# Phase 1:
#   z_3m threshold = z_1y threshold within each bucket


# ===== Core grid =====

CORE_VRP_TRIPLES = [
    (0.70, 0.80, 0.90),
    (0.80, 0.90, 1.00),
    (0.80, 1.00, 1.10),
    (0.90, 1.00, 1.20),
]

CORE_Z_TRIPLES = [
    (0.50, 0.75, 0.75),
    (0.50, 0.75, 1.00),
    (0.75, 1.00, 1.25),
    (1.00, 1.00, 1.50),
]

CORE_RSI_TRIPLES = [
    (72, 70, 68),
    (70, 68, 66),
    (68, 66, 64),
]

CORE_RV21D_TRIPLES = [
    (6.5, 6.5, 6.5),
    (7.5, 7.5, 7.5),
    (8.5, 8.5, 8.5),
    (8.5, 9.0, 10.0),
]


# ===== Secondary grid =====

SECONDARY_VRP_TRIPLES = [
    (0.50, 0.60, 0.70),
    (0.60, 0.70, 0.80),
    (0.60, 0.80, 0.90),
    (0.70, 0.80, 1.00),
]

SECONDARY_Z_TRIPLES = [
    (0.25, 0.50, 0.50),
    (0.25, 0.50, 0.75),
    (0.50, 0.75, 1.00),
    (0.75, 1.00, 1.25),
]

SECONDARY_RSI_TRIPLES = [
    (76, 74, 72),
    (74, 72, 70),
    (72, 70, 68),
]

SECONDARY_RV21D_TRIPLES = [
    (5.5, 5.5, 5.5),
    (6.5, 6.5, 6.5),
    (7.5, 7.5, 7.5),
    (6.5, 7.5, 8.5),
]


# -----------------------------
# 3. Validation helpers
# -----------------------------

def validate_bucket_shape(vrp_triple, z_triple, rsi_triple, rv21d_triple):
    """
    Enforce approved bucket-shape rules.

    Richness / strictness:
        Front <= Middle <= Back

    RSI cap:
        Front >= Middle >= Back
    """
    checks = {
        "vrp_front_le_middle_le_back": vrp_triple[0] <= vrp_triple[1] <= vrp_triple[2],
        "z_front_le_middle_le_back": z_triple[0] <= z_triple[1] <= z_triple[2],
        "rv21d_front_le_middle_le_back": rv21d_triple[0] <= rv21d_triple[1] <= rv21d_triple[2],
        "rsi_front_ge_middle_ge_back": rsi_triple[0] >= rsi_triple[1] >= rsi_triple[2],
    }

    return all(checks.values()), checks


def build_layer_specs(
    role,
    vrp_triples,
    z_triples,
    rsi_triples,
    rv21d_triples,
):
    rows = []

    for spec_num, (vrp, z, rsi, rv21d) in enumerate(
        itertools.product(vrp_triples, z_triples, rsi_triples, rv21d_triples),
        start=1,
    ):
        is_valid, checks = validate_bucket_shape(vrp, z, rsi, rv21d)

        if not is_valid:
            raise ValueError(
                f"Invalid {role} spec #{spec_num}: "
                f"vrp={vrp}, z={z}, rsi={rsi}, rv21d={rv21d}, checks={checks}"
            )

        spec_id = (
            f"{role.lower()}_phase1_"
            f"vrp_{vrp[0]:.2f}_{vrp[1]:.2f}_{vrp[2]:.2f}_"
            f"z_{z[0]:.2f}_{z[1]:.2f}_{z[2]:.2f}_"
            f"rsi_{int(rsi[0])}_{int(rsi[1])}_{int(rsi[2])}_"
            f"rv21d_{rv21d[0]:.1f}_{rv21d[1]:.1f}_{rv21d[2]:.1f}"
        )

        rows.append({
            "spec_id": spec_id,
            "role": role,
            "phase": "phase1_starting_grid",
            "forecast_denominator": "har_total_simple",

            "front_vrp_log_min": vrp[0],
            "middle_vrp_log_min": vrp[1],
            "back_vrp_log_min": vrp[2],

            "front_z_3m_min": z[0],
            "middle_z_3m_min": z[1],
            "back_z_3m_min": z[2],

            "front_z_1y_min": z[0],
            "middle_z_1y_min": z[1],
            "back_z_1y_min": z[2],

            "front_rsi14_max": rsi[0],
            "middle_rsi14_max": rsi[1],
            "back_rsi14_max": rsi[2],

            "front_rv21d_min": rv21d[0],
            "middle_rv21d_min": rv21d[1],
            "back_rv21d_min": rv21d[2],

            "phase1_z_3m_equals_z_1y": True,
        })

    return pd.DataFrame(rows)


# -----------------------------
# 4. Build approved specs
# -----------------------------

core_specs = build_layer_specs(
    role="Core",
    vrp_triples=CORE_VRP_TRIPLES,
    z_triples=CORE_Z_TRIPLES,
    rsi_triples=CORE_RSI_TRIPLES,
    rv21d_triples=CORE_RV21D_TRIPLES,
)

secondary_specs = build_layer_specs(
    role="Secondary",
    vrp_triples=SECONDARY_VRP_TRIPLES,
    z_triples=SECONDARY_Z_TRIPLES,
    rsi_triples=SECONDARY_RSI_TRIPLES,
    rv21d_triples=SECONDARY_RV21D_TRIPLES,
)

all_specs = pd.concat([core_specs, secondary_specs], ignore_index=True)


# -----------------------------
# 5. Summary
# -----------------------------

grid_summary = pd.DataFrame([
    {
        "role": "Core",
        "vrp_triples": len(CORE_VRP_TRIPLES),
        "z_triples": len(CORE_Z_TRIPLES),
        "rsi_triples": len(CORE_RSI_TRIPLES),
        "rv21d_triples": len(CORE_RV21D_TRIPLES),
        "total_specs": len(core_specs),
    },
    {
        "role": "Secondary",
        "vrp_triples": len(SECONDARY_VRP_TRIPLES),
        "z_triples": len(SECONDARY_Z_TRIPLES),
        "rsi_triples": len(SECONDARY_RSI_TRIPLES),
        "rv21d_triples": len(SECONDARY_RV21D_TRIPLES),
        "total_specs": len(secondary_specs),
    },
    {
        "role": "Total",
        "vrp_triples": None,
        "z_triples": None,
        "rsi_triples": None,
        "rv21d_triples": None,
        "total_specs": len(all_specs),
    },
])

print()
print("Phase 1 grid summary:")
display(grid_summary)

print()
print("Core specs sample:")
display(core_specs.head(10))

print()
print("Secondary specs sample:")
display(secondary_specs.head(10))


# -----------------------------
# 6. Save outputs
# -----------------------------

core_specs_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell2_core_phase1_specs_{RUN_TIMESTAMP}.csv"
)

secondary_specs_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell2_secondary_phase1_specs_{RUN_TIMESTAMP}.csv"
)

all_specs_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell2_all_phase1_specs_{RUN_TIMESTAMP}.csv"
)

grid_summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell2_phase1_grid_summary_{RUN_TIMESTAMP}.csv"
)

core_specs.to_csv(core_specs_path, index=False)
secondary_specs.to_csv(secondary_specs_path, index=False)
all_specs.to_csv(all_specs_path, index=False)
grid_summary.to_csv(grid_summary_path, index=False)

print()
print("Cell 2 outputs saved:")
print(f"Core specs:          {core_specs_path}")
print(f"Secondary specs:     {secondary_specs_path}")
print(f"All specs:           {all_specs_path}")
print(f"Grid summary:        {grid_summary_path}")

print()
print("Cell 2 complete.")

Cell 2: Define Phase 1 starting parameter grid only
Project root:      C:\Users\patri\vrp_project
Audit dir:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean
Run timestamp:     20260704_085147

Phase 1 grid summary:

        role  vrp_triples  z_triples  rsi_triples  rv21d_triples  total_specs
0       Core          4.0        4.0          3.0            4.0          192
1  Secondary          4.0        4.0          3.0            4.0          192
2      Total          NaN        NaN          NaN            NaN          384

Core specs sample:

,spec_id,role,phase,forecast_denominator,front_vrp_log_min,middle_vrp_log_min,back_vrp_log_min,front_z_3m_min,middle_z_3m_min,back_z_3m_min,front_z_1y_min,middle_z_1y_min,back_z_1y_min,front_rsi14_max,middle_rsi14_max,back_rsi14_max,front_rv21d_min,middle_rv21d_min,back_rv21d_min,phase1_z_3m_equals_z_1y
0,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,Core,phase1_starting_grid,har_total_simple,0.7,0.8,0.9,0.5,0.75,0.75,0.5,0.75,0.75,72,70,68,6.5,6.5,6.5,True
1,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,Core,phase1_starting_grid,har_total_simple,0.7,0.8,0.9,0.5,0.75,0.75,0.5,0.75,0.75,72,70,68,7.5,7.5,7.5,True
2,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,Core,phase1_starting_grid,har_total_simple,0.7,0.8,0.9,0.5,0.75,0.75,0.5,0.75,0.75,72,70,68,8.5,8.5,8.5,True
3,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,Core,phase1_starting_grid,har_total_simple,0.7,0.8,0.9,0.5,0.75,0.75,0.5,0.75,0.75,72,70,68,8.5,9.0,10.0,True
4,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,Core,phase1_starting_grid,har_total_simple,0.7,0.8,0.9,0.5,0.75,0.75,0.5,0.75,0.75,70,68,66,6.5,6.5,6.5,True
5,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,Core,phase1_starting_grid,har_total_simple,0.7,0.8,0.9,0.5,0.75,0.75,0.5,0.75,0.75,70,68,66,7.5,7.5,7.5,True
6,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,Core,phase1_starting_grid,har_total_simple,0.7,0.8,0.9,0.5,0.75,0.75,0.5,0.75,0.75,70,68,66,8.5,8.5,8.5,True
7,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,Core,phase1_starting_grid,har_total_simple,0.7,0.8,0.9,0.5,0.75,0.75,0.5,0.75,0.75,70,68,66,8.5,9.0,10.0,True
8,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,Core,phase1_starting_grid,har_total_simple,0.7,0.8,0.9,0.5,0.75,0.75,0.5,0.75,0.75,68,66,64,6.5,6.5,6.5,True
9,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,Core,phase1_starting_grid,har_total_simple,0.7,0.8,0.9,0.5,0.75,0.75,0.5,0.75,0.75,68,66,64,7.5,7.5,7.5,True

Secondary specs sample:

,spec_id,role,phase,forecast_denominator,front_vrp_log_min,middle_vrp_log_min,back_vrp_log_min,front_z_3m_min,middle_z_3m_min,back_z_3m_min,front_z_1y_min,middle_z_1y_min,back_z_1y_min,front_rsi14_max,middle_rsi14_max,back_rsi14_max,front_rv21d_min,middle_rv21d_min,back_rv21d_min,phase1_z_3m_equals_z_1y
0,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...,Secondary,phase1_starting_grid,har_total_simple,0.5,0.6,0.7,0.25,0.5,0.5,0.25,0.5,0.5,76,74,72,5.5,5.5,5.5,True
1,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...,Secondary,phase1_starting_grid,har_total_simple,0.5,0.6,0.7,0.25,0.5,0.5,0.25,0.5,0.5,76,74,72,6.5,6.5,6.5,True
2,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...,Secondary,phase1_starting_grid,har_total_simple,0.5,0.6,0.7,0.25,0.5,0.5,0.25,0.5,0.5,76,74,72,7.5,7.5,7.5,True
3,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...,Secondary,phase1_starting_grid,har_total_simple,0.5,0.6,0.7,0.25,0.5,0.5,0.25,0.5,0.5,76,74,72,6.5,7.5,8.5,True
4,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...,Secondary,phase1_starting_grid,har_total_simple,0.5,0.6,0.7,0.25,0.5,0.5,0.25,0.5,0.5,74,72,70,5.5,5.5,5.5,True
5,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...,Secondary,phase1_starting_grid,har_total_simple,0.5,0.6,0.7,0.25,0.5,0.5,0.25,0.5,0.5,74,72,70,6.5,6.5,6.5,True
6,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...,Secondary,phase1_starting_grid,har_total_simple,0.5,0.6,0.7,0.25,0.5,0.5,0.25,0.5,0.5,74,72,70,7.5,7.5,7.5,True
7,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...,Secondary,phase1_starting_grid,har_total_simple,0.5,0.6,0.7,0.25,0.5,0.5,0.25,0.5,0.5,74,72,70,6.5,7.5,8.5,True
8,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...,Secondary,phase1_starting_grid,har_total_simple,0.5,0.6,0.7,0.25,0.5,0.5,0.25,0.5,0.5,72,70,68,5.5,5.5,5.5,True
9,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...,Secondary,phase1_starting_grid,har_total_simple,0.5,0.6,0.7,0.25,0.5,0.5,0.25,0.5,0.5,72,70,68,6.5,6.5,6.5,True

Cell 2 outputs saved:
Core specs:          C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell2_core_phase1_specs_20260704_085147.csv
Secondary specs:     C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell2_secondary_phase1_specs_20260704_085147.csv
All specs:           C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell2_all_phase1_specs_20260704_085147.csv
Grid summary:        C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell2_phase1_grid_summary_20260704_085147.csv

Cell 2 complete.

In [5]:
# Cell 3: Phase 1 full Core x Secondary sweep using old locked-process selection logic
#
# Approved scope:
#   - Test every Core spec x Secondary spec combination.
#   - Use har_total_simple denominator.
#   - Use all parameters:
#       VRP log
#       3m z-score
#       1y z-score
#       RSI cap
#       RV21D floor
#   - Phase 1 keeps 3m z threshold = 1y z threshold within each bucket.
#   - Core first, Secondary second.
#   - Select at most one tenor per date.
#
# Old-model-aligned tenor selection:
#   1. Compute conditional tenor stats from the relevant candidate universe.
#   2. Find highest conditional win probability among qualifying tenors.
#   3. Keep tenors within 25 bps of best conditional win probability.
#   4. Choose highest conditional average P&L/day.
#   5. Tie-break by conditional aggregate P&L/day.
#   6. Tie-break by conditional win probability.
#   7. Tie-break by longer tenor.
#
# Secondary conditional stats:
#   For each Core x Secondary combination, Secondary stats are calculated only on:
#       dates where that Core spec has no qualifying Core tenor
#       AND that Secondary spec qualifies.
#
# P&L/day:
#   normalized_pnl_dollars / actual_dte if actual_dte is available.
#   Falls back to normalized_pnl_dollars / tenor if actual_dte is unavailable.
#
# Minimum conditional observation rule:
#   Tenors with >= 20 conditional observations are preferred.
#   Low-sample tenors are only considered if all qualifying tenors are low-sample.
#
# Important:
#   This is a full-sample descriptive sweep for parameter discovery / plateau finding.
#   It is not final walk-forward validation.

from pathlib import Path
import numpy as np
import pandas as pd


# -----------------------------
# 1. Paths / load latest files
# -----------------------------

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

PARAM_SWEEP_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "corsi_parameter_sweep_clean"
PARAM_SWEEP_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "corsi_parameter_sweep_clean"
CORSI_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "forecast_model_corsi_v1"

PARAM_SWEEP_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

RUN_TIMESTAMP = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")

clean_panel_candidates = sorted(
    PARAM_SWEEP_PROCESSED_DIR.glob("02_corsi_parameter_sweep_clean_panel_*.parquet")
)

spec_candidates = sorted(
    PARAM_SWEEP_AUDIT_DIR.glob("02_corsi_parameter_sweep_clean_cell2_all_phase1_specs_*.csv")
)

if not clean_panel_candidates:
    raise FileNotFoundError(f"No clean panel found in {PARAM_SWEEP_PROCESSED_DIR}")

if not spec_candidates:
    raise FileNotFoundError(f"No Cell 2 all-specs file found in {PARAM_SWEEP_AUDIT_DIR}")

CLEAN_PANEL_PATH = clean_panel_candidates[-1]
ALL_SPECS_PATH = spec_candidates[-1]

print("Cell 3: Phase 1 full Core x Secondary sweep")
print(f"Clean panel path: {CLEAN_PANEL_PATH}")
print(f"All specs path:   {ALL_SPECS_PATH}")
print(f"Run timestamp:    {RUN_TIMESTAMP}")

panel = pd.read_parquet(CLEAN_PANEL_PATH).copy()
all_specs = pd.read_csv(ALL_SPECS_PATH).copy()

panel["date"] = pd.to_datetime(panel["date"]).dt.normalize()
panel["trade_date"] = pd.to_numeric(panel["trade_date"], errors="coerce").astype(int)
panel["tenor"] = pd.to_numeric(panel["tenor"], errors="coerce").astype(int)

required_panel_cols = [
    "date",
    "trade_date",
    "tenor",
    "tenor_bucket",
    "forecast_model",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rsi14",
    "rv21d",
    "outcome_value",
    "has_outcome",
    "is_parameter_sweep_eligible",
]

missing_panel_cols = [c for c in required_panel_cols if c not in panel.columns]

if missing_panel_cols:
    raise ValueError(f"Clean panel missing required columns: {missing_panel_cols}")

required_spec_cols = [
    "spec_id",
    "role",
    "forecast_denominator",

    "front_vrp_log_min",
    "middle_vrp_log_min",
    "back_vrp_log_min",

    "front_z_3m_min",
    "middle_z_3m_min",
    "back_z_3m_min",

    "front_z_1y_min",
    "middle_z_1y_min",
    "back_z_1y_min",

    "front_rsi14_max",
    "middle_rsi14_max",
    "back_rsi14_max",

    "front_rv21d_min",
    "middle_rv21d_min",
    "back_rv21d_min",
]

missing_spec_cols = [c for c in required_spec_cols if c not in all_specs.columns]

if missing_spec_cols:
    raise ValueError(f"Specs file missing required columns: {missing_spec_cols}")


# -----------------------------
# 2. Add actual_dte if available
# -----------------------------

def first_existing_col(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    return None


def load_actual_dte_lookup():
    """
    Locate the same outcome universe used by Cell 1 and pull actual_dte if available.
    """
    outcome_discovery_candidates = sorted(
        CORSI_AUDIT_DIR.glob("corsi_cell11_trade_outcome_file_discovery_*.csv")
    )

    if not outcome_discovery_candidates:
        return None, "no_outcome_discovery_file"

    discovery_path = outcome_discovery_candidates[-1]
    discovery = pd.read_csv(discovery_path)
    discovery.columns = [str(c).strip() for c in discovery.columns]

    file_col = "chosen_file" if "chosen_file" in discovery.columns else "path"

    if file_col not in discovery.columns:
        return None, "discovery_missing_path_column"

    preferred = discovery.copy()

    if "eligible_for_backtest" in preferred.columns:
        preferred = preferred.loc[preferred["eligible_for_backtest"].astype(bool)].copy()

    if preferred.empty:
        return None, "no_eligible_outcome_files"

    if "score" in preferred.columns:
        preferred["_score"] = pd.to_numeric(preferred["score"], errors="coerce")
    else:
        preferred["_score"] = 0.0

    if "chosen_outcome_col" in preferred.columns:
        preferred["_preferred_pnl"] = preferred["chosen_outcome_col"].eq("normalized_pnl_dollars")
    elif "outcome_col" in preferred.columns:
        preferred["_preferred_pnl"] = preferred["outcome_col"].eq("normalized_pnl_dollars")
    else:
        preferred["_preferred_pnl"] = False

    preferred = preferred.sort_values(
        ["_preferred_pnl", "_score"],
        ascending=[False, False],
    )

    for _, row in preferred.iterrows():
        path = Path(row[file_col])

        if not path.exists():
            continue

        try:
            raw = pd.read_parquet(path) if path.suffix.lower() == ".parquet" else pd.read_csv(path)
        except Exception:
            continue

        raw.columns = [str(c).strip() for c in raw.columns]

        trade_date_col = first_existing_col(raw, ["trade_date", "trade_dt", "date"])
        tenor_col = first_existing_col(raw, ["tenor", "entry_tenor", "target_tenor"])
        actual_dte_col = first_existing_col(raw, ["actual_dte"])

        if trade_date_col is None or tenor_col is None or actual_dte_col is None:
            continue

        lookup = raw[[trade_date_col, tenor_col, actual_dte_col]].copy()
        lookup = lookup.rename(columns={
            trade_date_col: "trade_date",
            tenor_col: "tenor",
            actual_dte_col: "actual_dte_from_outcomes",
        })

        lookup["trade_date"] = pd.to_numeric(lookup["trade_date"], errors="coerce").astype("Int64")
        lookup["tenor"] = pd.to_numeric(lookup["tenor"], errors="coerce").astype("Int64")
        lookup["actual_dte_from_outcomes"] = pd.to_numeric(
            lookup["actual_dte_from_outcomes"],
            errors="coerce",
        )

        lookup = lookup.dropna(subset=["trade_date", "tenor"])
        lookup["trade_date"] = lookup["trade_date"].astype(int)
        lookup["tenor"] = lookup["tenor"].astype(int)

        lookup = lookup.drop_duplicates(["trade_date", "tenor"])

        return lookup, str(path)

    return None, "actual_dte_not_found_in_outcome_files"


if "actual_dte" not in panel.columns:
    actual_dte_lookup, actual_dte_source = load_actual_dte_lookup()

    if actual_dte_lookup is not None:
        panel = panel.merge(
            actual_dte_lookup,
            on=["trade_date", "tenor"],
            how="left",
            validate="many_to_one",
        )
        panel["actual_dte"] = panel["actual_dte_from_outcomes"]
        panel = panel.drop(columns=["actual_dte_from_outcomes"])
    else:
        panel["actual_dte"] = np.nan
else:
    actual_dte_source = "clean_panel_existing_actual_dte"

panel["actual_dte"] = pd.to_numeric(panel["actual_dte"], errors="coerce")

panel["actual_dte_for_pnl_day"] = panel["actual_dte"]

fallback_mask = panel["actual_dte_for_pnl_day"].isna() | panel["actual_dte_for_pnl_day"].le(0)

panel.loc[fallback_mask, "actual_dte_for_pnl_day"] = panel.loc[fallback_mask, "tenor"]

panel["pnl_per_day"] = panel["outcome_value"] / panel["actual_dte_for_pnl_day"]

print()
print("Actual DTE source:")
print(actual_dte_source)

print()
print("Actual DTE availability:")
display(pd.DataFrame([{
    "rows": len(panel),
    "actual_dte_non_null": int(panel["actual_dte"].notna().sum()),
    "actual_dte_non_null_pct": float(panel["actual_dte"].notna().mean()),
    "fallback_to_tenor_rows": int(fallback_mask.sum()),
    "fallback_to_tenor_pct": float(fallback_mask.mean()),
}]))


# -----------------------------
# 3. Build complete eligible matrix panel
# -----------------------------

TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

TENOR_BUCKET_MAP = {
    9: "front",
    12: "front",
    15: "front",
    18: "middle",
    21: "middle",
    24: "middle",
    27: "back",
    30: "back",
    33: "back",
}

BUCKETS = ["front", "middle", "back"]
WIN_BAND = 0.0025
MIN_CONDITIONAL_OBS = 20

eligible = panel.loc[panel["is_parameter_sweep_eligible"].astype(bool)].copy()
eligible = eligible.replace([np.inf, -np.inf], np.nan)

needed_for_matrix = [
    "trade_date",
    "date",
    "tenor",
    "tenor_bucket",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rsi14",
    "rv21d",
    "outcome_value",
    "actual_dte_for_pnl_day",
    "pnl_per_day",
]

eligible = eligible.dropna(subset=needed_for_matrix).copy()

eligible = eligible.loc[
    eligible["tenor"].isin(TENORS)
    & eligible["actual_dte_for_pnl_day"].gt(0)
].copy()

duplicate_rows = eligible.duplicated(["trade_date", "tenor"]).sum()

if duplicate_rows:
    raise ValueError(f"Eligible panel has duplicate trade_date x tenor rows: {duplicate_rows}")

date_counts = eligible.groupby("trade_date")["tenor"].nunique()

complete_dates = date_counts.loc[date_counts.eq(len(TENORS))].index.tolist()

eligible = eligible.loc[eligible["trade_date"].isin(complete_dates)].copy()

eligible_dates = sorted(eligible["trade_date"].unique())
num_dates = len(eligible_dates)
num_tenors = len(TENORS)

date_lookup = (
    eligible[["trade_date", "date"]]
    .drop_duplicates("trade_date")
    .set_index("trade_date")
    .loc[eligible_dates]
)

date_array = date_lookup["date"].to_numpy()

def pivot_matrix(col, dtype=float):
    mat = (
        eligible
        .pivot(index="trade_date", columns="tenor", values=col)
        .reindex(index=eligible_dates, columns=TENORS)
    )

    if mat.isna().any().any():
        missing = int(mat.isna().sum().sum())
        raise ValueError(f"Matrix for {col} has missing cells after complete-date filter: {missing}")

    return mat.to_numpy(dtype=dtype)

vrp_mat = pivot_matrix("vrp_log")
z3m_mat = pivot_matrix("vrp_z_3m")
z1y_mat = pivot_matrix("vrp_z_1y")
rsi_mat = pivot_matrix("rsi14")
rv21d_mat = pivot_matrix("rv21d")
pnl_mat = pivot_matrix("outcome_value")
actual_dte_mat = pivot_matrix("actual_dte_for_pnl_day")
pnl_per_day_mat = pivot_matrix("pnl_per_day")

win_mat = (pnl_mat > 0).astype(float)
valid_outcome_mat = np.isfinite(pnl_mat) & np.isfinite(pnl_per_day_mat) & np.isfinite(actual_dte_mat)

tenor_array = np.array(TENORS, dtype=int)
tenor_bucket_array = np.array([TENOR_BUCKET_MAP[int(t)] for t in tenor_array], dtype=object)

core_specs = all_specs.loc[all_specs["role"].eq("Core")].copy().reset_index(drop=True)
secondary_specs = all_specs.loc[all_specs["role"].eq("Secondary")].copy().reset_index(drop=True)

print()
print("Cell 3 input summary:")
display(pd.DataFrame([{
    "eligible_rows_after_complete_date_filter": len(eligible),
    "eligible_dates": num_dates,
    "first_date": pd.to_datetime(date_array.min()),
    "last_date": pd.to_datetime(date_array.max()),
    "unique_tenors": num_tenors,
    "core_specs": len(core_specs),
    "secondary_specs": len(secondary_specs),
    "full_model_combinations": len(core_specs) * len(secondary_specs),
    "win_band_bps": WIN_BAND * 10000,
    "min_conditional_obs": MIN_CONDITIONAL_OBS,
    "forecast_model": ", ".join(sorted(eligible["forecast_model"].astype(str).unique())),
}]))


# -----------------------------
# 4. Matrix helper functions
# -----------------------------

def threshold_array_for_spec(spec_row, field_suffix):
    """
    Example field_suffix:
        vrp_log_min
        z_3m_min
        z_1y_min
        rsi14_max
        rv21d_min
    """
    vals = []

    for tenor in TENORS:
        bucket = TENOR_BUCKET_MAP[int(tenor)]
        vals.append(float(spec_row[f"{bucket}_{field_suffix}"]))

    return np.array(vals, dtype=float)


def build_pass_matrix(spec_row):
    vrp_threshold = threshold_array_for_spec(spec_row, "vrp_log_min")
    z3m_threshold = threshold_array_for_spec(spec_row, "z_3m_min")
    z1y_threshold = threshold_array_for_spec(spec_row, "z_1y_min")
    rsi_cap = threshold_array_for_spec(spec_row, "rsi14_max")
    rv21d_floor = threshold_array_for_spec(spec_row, "rv21d_min")

    return (
        (vrp_mat >= vrp_threshold[None, :])
        & (z3m_mat >= z3m_threshold[None, :])
        & (z1y_mat >= z1y_threshold[None, :])
        & (rsi_mat <= rsi_cap[None, :])
        & (rv21d_mat >= rv21d_floor[None, :])
        & valid_outcome_mat
    )


def compute_conditional_stats(pass_matrix, date_mask, layer, spec_id, core_spec_id=None, secondary_spec_id=None):
    rows = []

    date_mask = np.asarray(date_mask, dtype=bool)

    for col_idx, tenor in enumerate(TENORS):
        candidate_mask = pass_matrix[:, col_idx] & date_mask & valid_outcome_mat[:, col_idx]
        candidate_count = int(candidate_mask.sum())

        if candidate_count == 0:
            row = {
                "layer": layer,
                "spec_id": spec_id,
                "core_spec_id": core_spec_id,
                "secondary_spec_id": secondary_spec_id,
                "tenor": int(tenor),
                "tenor_bucket": TENOR_BUCKET_MAP[int(tenor)],
                "conditional_obs": 0,
                "conditional_win_probability": np.nan,
                "conditional_avg_pnl_per_day": np.nan,
                "conditional_median_pnl_per_day": np.nan,
                "conditional_aggregate_pnl_per_day": np.nan,
                "conditional_avg_pnl_per_trade": np.nan,
                "conditional_total_pnl": 0.0,
                "conditional_worst_trade_pnl": np.nan,
                "conditional_worst_pnl_per_day": np.nan,
                "conditional_avg_actual_dte": np.nan,
                "conditional_sample_ok": False,
            }
            rows.append(row)
            continue

        pnl = pnl_mat[candidate_mask, col_idx]
        pnl_day = pnl_per_day_mat[candidate_mask, col_idx]
        dte = actual_dte_mat[candidate_mask, col_idx]

        total_dte = np.nansum(dte)

        if total_dte > 0:
            aggregate_pnl_per_day = np.nansum(pnl) / total_dte
        else:
            aggregate_pnl_per_day = np.nan

        row = {
            "layer": layer,
            "spec_id": spec_id,
            "core_spec_id": core_spec_id,
            "secondary_spec_id": secondary_spec_id,
            "tenor": int(tenor),
            "tenor_bucket": TENOR_BUCKET_MAP[int(tenor)],
            "conditional_obs": candidate_count,
            "conditional_win_probability": float(np.nanmean(pnl > 0)),
            "conditional_avg_pnl_per_day": float(np.nanmean(pnl_day)),
            "conditional_median_pnl_per_day": float(np.nanmedian(pnl_day)),
            "conditional_aggregate_pnl_per_day": float(aggregate_pnl_per_day),
            "conditional_avg_pnl_per_trade": float(np.nanmean(pnl)),
            "conditional_total_pnl": float(np.nansum(pnl)),
            "conditional_worst_trade_pnl": float(np.nanmin(pnl)),
            "conditional_worst_pnl_per_day": float(np.nanmin(pnl_day)),
            "conditional_avg_actual_dte": float(np.nanmean(dte)),
            "conditional_sample_ok": candidate_count >= MIN_CONDITIONAL_OBS,
        }

        rows.append(row)

    return pd.DataFrame(rows)


def select_cols_from_pass_and_stats(pass_matrix, stats_df, date_mask):
    """
    Vectorized old-model-aligned selector.

    Ranking:
      1. Prefer tenors with conditional_obs >= MIN_CONDITIONAL_OBS.
      2. Find best conditional win probability among qualifying tenors.
      3. Keep tenors within WIN_BAND of that best win probability.
      4. Select highest conditional average P&L/day.
      5. Tie-break by conditional aggregate P&L/day.
      6. Tie-break by conditional win probability.
      7. Tie-break by longer tenor.
    """
    date_mask = np.asarray(date_mask, dtype=bool)

    active_pass = pass_matrix & date_mask[:, None]

    stats_df = stats_df.sort_values("tenor").reset_index(drop=True)

    conditional_obs = stats_df["conditional_obs"].to_numpy(dtype=float)
    conditional_win = stats_df["conditional_win_probability"].to_numpy(dtype=float)
    conditional_avg_pnl_day = stats_df["conditional_avg_pnl_per_day"].to_numpy(dtype=float)
    conditional_agg_pnl_day = stats_df["conditional_aggregate_pnl_per_day"].to_numpy(dtype=float)

    has_stats = (
        (conditional_obs > 0)
        & np.isfinite(conditional_win)
        & np.isfinite(conditional_avg_pnl_day)
        & np.isfinite(conditional_agg_pnl_day)
    )

    sample_ok = conditional_obs >= MIN_CONDITIONAL_OBS

    active = active_pass & has_stats[None, :]

    active_sample_ok = active & sample_ok[None, :]
    row_has_sample_ok = active_sample_ok.any(axis=1)

    ranking_universe = np.where(
        row_has_sample_ok[:, None],
        active_sample_ok,
        active,
    )

    win_masked = np.where(
        ranking_universe,
        conditional_win[None, :],
        -np.inf,
    )

    best_win = win_masked.max(axis=1)
    row_has_any = np.isfinite(best_win)

    inside_win_band = (
        ranking_universe
        & row_has_any[:, None]
        & (conditional_win[None, :] >= (best_win[:, None] - WIN_BAND))
    )

    selected_col = np.full(num_dates, -1, dtype=int)

    best_avg = np.full(num_dates, -np.inf)
    best_agg = np.full(num_dates, -np.inf)
    best_win_for_tie = np.full(num_dates, -np.inf)
    best_tenor = np.full(num_dates, -np.inf)

    for col_idx, tenor in enumerate(TENORS):
        cand = inside_win_band[:, col_idx]

        avg_val = conditional_avg_pnl_day[col_idx]
        agg_val = conditional_agg_pnl_day[col_idx]
        win_val = conditional_win[col_idx]
        tenor_val = float(tenor)

        better = (
            cand
            & (
                (avg_val > best_avg)
                | (
                    (avg_val == best_avg)
                    & (agg_val > best_agg)
                )
                | (
                    (avg_val == best_avg)
                    & (agg_val == best_agg)
                    & (win_val > best_win_for_tie)
                )
                | (
                    (avg_val == best_avg)
                    & (agg_val == best_agg)
                    & (win_val == best_win_for_tie)
                    & (tenor_val > best_tenor)
                )
            )
        )

        selected_col[better] = col_idx
        best_avg[better] = avg_val
        best_agg[better] = agg_val
        best_win_for_tie[better] = win_val
        best_tenor[better] = tenor_val

    return selected_col


def profit_factor(values):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]

    if values.size == 0:
        return np.nan

    gains = values[values > 0].sum()
    losses = values[values < 0].sum()

    if losses < 0:
        return gains / abs(losses)

    if gains > 0 and losses == 0:
        return np.inf

    return np.nan


def summarize_selected_cols(selected_cols, prefix):
    selected_cols = np.asarray(selected_cols, dtype=int)
    date_idx = np.where(selected_cols >= 0)[0]

    if date_idx.size == 0:
        return {
            f"{prefix}_trades": 0,
            f"{prefix}_frequency": 0.0,
            f"{prefix}_win_rate": np.nan,
            f"{prefix}_total_pnl": 0.0,
            f"{prefix}_avg_pnl_per_trade": np.nan,
            f"{prefix}_avg_pnl_per_day": np.nan,
            f"{prefix}_exposure_day_weighted_pnl_per_day": np.nan,
            f"{prefix}_profit_factor": np.nan,
            f"{prefix}_worst_trade_pnl": np.nan,
            f"{prefix}_worst_pnl_per_day": np.nan,
            f"{prefix}_best_trade_pnl": np.nan,
            f"{prefix}_avg_actual_dte": np.nan,
            f"{prefix}_avg_selected_tenor": np.nan,
        }

    cols = selected_cols[date_idx]

    pnl = pnl_mat[date_idx, cols]
    pnl_day = pnl_per_day_mat[date_idx, cols]
    dte = actual_dte_mat[date_idx, cols]
    selected_tenors = tenor_array[cols]

    total_dte = np.nansum(dte)

    if total_dte > 0:
        exposure_day_weighted_pnl_per_day = np.nansum(pnl) / total_dte
    else:
        exposure_day_weighted_pnl_per_day = np.nan

    return {
        f"{prefix}_trades": int(date_idx.size),
        f"{prefix}_frequency": float(date_idx.size / num_dates) if num_dates else np.nan,
        f"{prefix}_win_rate": float(np.nanmean(pnl > 0)),
        f"{prefix}_total_pnl": float(np.nansum(pnl)),
        f"{prefix}_avg_pnl_per_trade": float(np.nanmean(pnl)),
        f"{prefix}_avg_pnl_per_day": float(np.nanmean(pnl_day)),
        f"{prefix}_exposure_day_weighted_pnl_per_day": float(exposure_day_weighted_pnl_per_day),
        f"{prefix}_profit_factor": float(profit_factor(pnl)),
        f"{prefix}_worst_trade_pnl": float(np.nanmin(pnl)),
        f"{prefix}_worst_pnl_per_day": float(np.nanmin(pnl_day)),
        f"{prefix}_best_trade_pnl": float(np.nanmax(pnl)),
        f"{prefix}_avg_actual_dte": float(np.nanmean(dte)),
        f"{prefix}_avg_selected_tenor": float(np.nanmean(selected_tenors)),
    }


def bucket_metrics(selected_cols):
    selected_cols = np.asarray(selected_cols, dtype=int)
    date_idx = np.where(selected_cols >= 0)[0]

    out = {}

    for bucket in BUCKETS:
        out[f"{bucket}_selected_trades"] = 0
        out[f"{bucket}_selected_win_rate"] = np.nan
        out[f"{bucket}_selected_avg_pnl_per_day"] = np.nan
        out[f"{bucket}_selected_total_pnl"] = 0.0

    if date_idx.size == 0:
        return out

    cols = selected_cols[date_idx]
    selected_buckets = tenor_bucket_array[cols]

    for bucket in BUCKETS:
        bucket_mask = selected_buckets == bucket

        if not bucket_mask.any():
            continue

        bucket_date_idx = date_idx[bucket_mask]
        bucket_cols = cols[bucket_mask]

        pnl = pnl_mat[bucket_date_idx, bucket_cols]
        pnl_day = pnl_per_day_mat[bucket_date_idx, bucket_cols]

        out[f"{bucket}_selected_trades"] = int(bucket_mask.sum())
        out[f"{bucket}_selected_win_rate"] = float(np.nanmean(pnl > 0))
        out[f"{bucket}_selected_avg_pnl_per_day"] = float(np.nanmean(pnl_day))
        out[f"{bucket}_selected_total_pnl"] = float(np.nansum(pnl))

    return out


# -----------------------------
# 5. Precompute Core selections and Secondary pass matrices
# -----------------------------

core_objects = {}
core_layer_summary_rows = []
core_conditional_stats_rows = []

print()
print("Building Core pass matrices, conditional stats, and selections...")

all_dates_mask = np.ones(num_dates, dtype=bool)

for i, (_, spec_row) in enumerate(core_specs.iterrows(), start=1):
    spec_id = spec_row["spec_id"]

    pass_matrix = build_pass_matrix(spec_row)
    core_any_date = pass_matrix.any(axis=1)

    stats = compute_conditional_stats(
        pass_matrix=pass_matrix,
        date_mask=all_dates_mask,
        layer="Core",
        spec_id=spec_id,
        core_spec_id=spec_id,
        secondary_spec_id=None,
    )

    selected_cols = select_cols_from_pass_and_stats(
        pass_matrix=pass_matrix,
        stats_df=stats,
        date_mask=all_dates_mask,
    )

    core_objects[spec_id] = {
        "pass_matrix": pass_matrix,
        "core_any_date": core_any_date,
        "selected_cols": selected_cols,
        "stats": stats,
    }

    core_summary = {
        "spec_id": spec_id,
        "role": "Core",
        "candidate_dates": int(core_any_date.sum()),
        "candidate_frequency": float(core_any_date.sum() / num_dates) if num_dates else np.nan,
        **summarize_selected_cols(selected_cols, "core_layer"),
    }

    core_layer_summary_rows.append(core_summary)
    core_conditional_stats_rows.append(stats)

    if i % 25 == 0 or i == len(core_specs):
        print(f"Core specs processed: {i:,} / {len(core_specs):,}")

core_layer_summary = pd.DataFrame(core_layer_summary_rows)
core_conditional_stats = pd.concat(core_conditional_stats_rows, ignore_index=True)

print()
print("Building Secondary pass matrices...")

secondary_pass_matrices = {}

for i, (_, spec_row) in enumerate(secondary_specs.iterrows(), start=1):
    spec_id = spec_row["spec_id"]
    secondary_pass_matrices[spec_id] = build_pass_matrix(spec_row)

    if i % 25 == 0 or i == len(secondary_specs):
        print(f"Secondary specs processed: {i:,} / {len(secondary_specs):,}")

print()
print("Core layer summary:")

core_layer_summary_display = pd.DataFrame([{
    "specs": core_layer_summary["spec_id"].nunique(),

    "min_candidate_frequency": core_layer_summary["candidate_frequency"].min(),
    "median_candidate_frequency": core_layer_summary["candidate_frequency"].median(),
    "max_candidate_frequency": core_layer_summary["candidate_frequency"].max(),

    "min_core_layer_win_rate": core_layer_summary["core_layer_win_rate"].min(),
    "median_core_layer_win_rate": core_layer_summary["core_layer_win_rate"].median(),
    "max_core_layer_win_rate": core_layer_summary["core_layer_win_rate"].max(),

    "min_core_layer_avg_pnl_per_day": core_layer_summary["core_layer_avg_pnl_per_day"].min(),
    "median_core_layer_avg_pnl_per_day": core_layer_summary["core_layer_avg_pnl_per_day"].median(),
    "max_core_layer_avg_pnl_per_day": core_layer_summary["core_layer_avg_pnl_per_day"].max(),
}])

display(core_layer_summary_display)


# -----------------------------
# 6. Full Core x Secondary model sweep
# -----------------------------

model_summary_rows = []
secondary_conditional_stats_rows = []

core_ids = core_specs["spec_id"].tolist()
secondary_ids = secondary_specs["spec_id"].tolist()

total_combinations = len(core_ids) * len(secondary_ids)
combo_counter = 0

print()
print(f"Running full model combinations: {total_combinations:,}")

for core_id in core_ids:
    core_obj = core_objects[core_id]

    core_selected_cols = core_obj["selected_cols"]
    core_any_date = core_obj["core_any_date"]

    no_core_date_mask = ~core_any_date

    for secondary_id in secondary_ids:
        combo_counter += 1

        secondary_pass_matrix = secondary_pass_matrices[secondary_id]

        secondary_stats = compute_conditional_stats(
            pass_matrix=secondary_pass_matrix,
            date_mask=no_core_date_mask,
            layer="Secondary",
            spec_id=secondary_id,
            core_spec_id=core_id,
            secondary_spec_id=secondary_id,
        )

        secondary_selected_cols = select_cols_from_pass_and_stats(
            pass_matrix=secondary_pass_matrix,
            stats_df=secondary_stats,
            date_mask=no_core_date_mask,
        )

        combined_selected_cols = np.where(
            core_selected_cols >= 0,
            core_selected_cols,
            secondary_selected_cols,
        )

        secondary_candidate_date_count = int((secondary_pass_matrix & no_core_date_mask[:, None]).any(axis=1).sum())

        row = {
            "core_spec_id": core_id,
            "secondary_spec_id": secondary_id,

            "secondary_candidate_dates_after_core_filter": secondary_candidate_date_count,
            "secondary_candidate_frequency_after_core_filter": (
                float(secondary_candidate_date_count / num_dates) if num_dates else np.nan
            ),

            **summarize_selected_cols(combined_selected_cols, "overall"),
            **summarize_selected_cols(core_selected_cols, "core"),
            **summarize_selected_cols(secondary_selected_cols, "secondary"),
            **bucket_metrics(combined_selected_cols),
        }

        model_summary_rows.append(row)

        # Save secondary conditional stats for audit.
        # This is combo-dependent because Secondary can only operate where that Core spec has no pass.
        secondary_conditional_stats_rows.append(secondary_stats)

    if combo_counter % (25 * len(secondary_ids)) == 0 or combo_counter == total_combinations:
        print(f"Full models processed: {combo_counter:,} / {total_combinations:,}")

model_summary = pd.DataFrame(model_summary_rows)

secondary_conditional_stats = pd.concat(
    secondary_conditional_stats_rows,
    ignore_index=True,
)

conditional_stats = pd.concat(
    [core_conditional_stats, secondary_conditional_stats],
    ignore_index=True,
)


# -----------------------------
# 7. Add parameter columns and target flags
# -----------------------------

core_param_cols = [
    c for c in core_specs.columns
    if c not in ["role", "phase", "forecast_denominator"]
]

secondary_param_cols = [
    c for c in secondary_specs.columns
    if c not in ["role", "phase", "forecast_denominator"]
]

core_params_for_merge = core_specs[core_param_cols].copy()
secondary_params_for_merge = secondary_specs[secondary_param_cols].copy()

core_params_for_merge = core_params_for_merge.add_prefix("core_param_")
secondary_params_for_merge = secondary_params_for_merge.add_prefix("secondary_param_")

model_summary = model_summary.merge(
    core_params_for_merge,
    left_on="core_spec_id",
    right_on="core_param_spec_id",
    how="left",
    validate="many_to_one",
)

model_summary = model_summary.merge(
    secondary_params_for_merge,
    left_on="secondary_spec_id",
    right_on="secondary_param_spec_id",
    how="left",
    validate="many_to_one",
)

model_summary["meets_core_win_85"] = model_summary["core_win_rate"].ge(0.85)
model_summary["meets_overall_win_80"] = model_summary["overall_win_rate"].ge(0.80)
model_summary["meets_frequency_33"] = model_summary["overall_frequency"].gt(0.33)

model_summary["meets_all_targets"] = (
    model_summary["meets_core_win_85"]
    & model_summary["meets_overall_win_80"]
    & model_summary["meets_frequency_33"]
)

# Review rank only. This is not a final model decision.
model_summary = model_summary.sort_values(
    [
        "meets_all_targets",
        "overall_win_rate",
        "core_win_rate",
        "overall_avg_pnl_per_day",
        "overall_frequency",
        "overall_total_pnl",
        "overall_worst_trade_pnl",
    ],
    ascending=[
        False,
        False,
        False,
        False,
        False,
        False,
        False,
    ],
).reset_index(drop=True)

model_summary["review_rank"] = np.arange(1, len(model_summary) + 1)


# -----------------------------
# 8. Display review output
# -----------------------------

print()
print("Full model summary:")
display(pd.DataFrame([{
    "full_models": len(model_summary),
    "models_meeting_all_targets": int(model_summary["meets_all_targets"].sum()),
    "models_core_win_85": int(model_summary["meets_core_win_85"].sum()),
    "models_overall_win_80": int(model_summary["meets_overall_win_80"].sum()),
    "models_frequency_33": int(model_summary["meets_frequency_33"].sum()),

    "max_overall_frequency": model_summary["overall_frequency"].max(),
    "median_overall_frequency": model_summary["overall_frequency"].median(),

    "max_overall_win_rate": model_summary["overall_win_rate"].max(),
    "median_overall_win_rate": model_summary["overall_win_rate"].median(),

    "max_core_win_rate": model_summary["core_win_rate"].max(),
    "median_core_win_rate": model_summary["core_win_rate"].median(),

    "max_overall_avg_pnl_per_day": model_summary["overall_avg_pnl_per_day"].max(),
    "median_overall_avg_pnl_per_day": model_summary["overall_avg_pnl_per_day"].median(),
}]))

review_cols = [
    "review_rank",
    "meets_all_targets",

    "overall_trades",
    "overall_frequency",
    "overall_win_rate",
    "overall_avg_pnl_per_day",
    "overall_exposure_day_weighted_pnl_per_day",
    "overall_total_pnl",
    "overall_profit_factor",
    "overall_worst_trade_pnl",
    "overall_worst_pnl_per_day",
    "overall_avg_actual_dte",
    "overall_avg_selected_tenor",

    "core_trades",
    "core_frequency",
    "core_win_rate",
    "core_avg_pnl_per_day",
    "core_exposure_day_weighted_pnl_per_day",
    "core_total_pnl",
    "core_worst_trade_pnl",
    "core_avg_actual_dte",
    "core_avg_selected_tenor",

    "secondary_trades",
    "secondary_frequency",
    "secondary_win_rate",
    "secondary_avg_pnl_per_day",
    "secondary_exposure_day_weighted_pnl_per_day",
    "secondary_total_pnl",
    "secondary_worst_trade_pnl",
    "secondary_avg_actual_dte",
    "secondary_avg_selected_tenor",

    "front_selected_trades",
    "front_selected_win_rate",
    "front_selected_avg_pnl_per_day",

    "middle_selected_trades",
    "middle_selected_win_rate",
    "middle_selected_avg_pnl_per_day",

    "back_selected_trades",
    "back_selected_win_rate",
    "back_selected_avg_pnl_per_day",

    "core_spec_id",
    "secondary_spec_id",
]

print()
print("Top full models by review rank:")
display(model_summary[review_cols].head(50))

print()
print("Top models meeting all targets:")
display(
    model_summary
    .loc[model_summary["meets_all_targets"], review_cols]
    .head(50)
)

print()
print("Highest-frequency models with overall win rate >= 80% and core win rate >= 85%:")
display(
    model_summary
    .loc[
        model_summary["overall_win_rate"].ge(0.80)
        & model_summary["core_win_rate"].ge(0.85),
        review_cols
    ]
    .sort_values(
        [
            "overall_frequency",
            "overall_win_rate",
            "overall_avg_pnl_per_day",
            "overall_total_pnl",
        ],
        ascending=[False, False, False, False],
    )
    .head(50)
)

print()
print("Highest average P&L/day models meeting all targets:")
display(
    model_summary
    .loc[model_summary["meets_all_targets"], review_cols]
    .sort_values(
        [
            "overall_avg_pnl_per_day",
            "overall_win_rate",
            "overall_frequency",
            "overall_total_pnl",
        ],
        ascending=[False, False, False, False],
    )
    .head(50)
)


# -----------------------------
# 9. Save outputs
# -----------------------------

safe_start = pd.to_datetime(date_array.min()).strftime("%Y%m%d")
safe_end = pd.to_datetime(date_array.max()).strftime("%Y%m%d")

core_layer_summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell3_core_layer_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

conditional_stats_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell3_conditional_stats_old_process_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

model_summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell3_full_model_summary_old_process_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

top_models_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell3_top_models_old_process_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

target_models_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell3_models_meeting_targets_old_process_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

high_frequency_win_models_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell3_high_frequency_win_models_old_process_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_layer_summary.to_csv(core_layer_summary_path, index=False)
conditional_stats.to_csv(conditional_stats_path, index=False)
model_summary.to_csv(model_summary_path, index=False)
model_summary.head(500).to_csv(top_models_path, index=False)

model_summary.loc[
    model_summary["meets_all_targets"]
].to_csv(target_models_path, index=False)

model_summary.loc[
    model_summary["overall_win_rate"].ge(0.80)
    & model_summary["core_win_rate"].ge(0.85)
].sort_values(
    [
        "overall_frequency",
        "overall_win_rate",
        "overall_avg_pnl_per_day",
        "overall_total_pnl",
    ],
    ascending=[False, False, False, False],
).to_csv(high_frequency_win_models_path, index=False)

print()
print("Cell 3 outputs saved:")
print(f"Core layer summary:        {core_layer_summary_path}")
print(f"Conditional stats:         {conditional_stats_path}")
print(f"Full model summary:        {model_summary_path}")
print(f"Top models:                {top_models_path}")
print(f"Target models:             {target_models_path}")
print(f"High frequency win models: {high_frequency_win_models_path}")

print()
print("Cell 3 complete.")

Cell 3: Phase 1 full Core x Secondary sweep
Clean panel path: C:\Users\patri\vrp_project\data\processed\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_panel_20200102_20260623_20260704_085138.parquet
All specs path:   C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell2_all_phase1_specs_20260704_085147.csv
Run timestamp:    20260704_090941

Actual DTE source:
C:\Users\patri\vrp_project\data\processed\put_candidate_universe_pricing_v0_1.parquet

Actual DTE availability:

,rows,actual_dte_non_null,actual_dte_non_null_pct,fallback_to_tenor_rows,fallback_to_tenor_pct
0,14565,14565,1.0,0,0.0

Cell 3 input summary:

,eligible_rows_after_complete_date_filter,eligible_dates,first_date,last_date,unique_tenors,core_specs,secondary_specs,full_model_combinations,win_band_bps,min_conditional_obs,forecast_model
0,13302,1478,2020-07-01,2026-05-19,9,192,192,36864,25.0,20,har_total_simple

Building Core pass matrices, conditional stats, and selections...
Core specs processed: 25 / 192
Core specs processed: 50 / 192
Core specs processed: 75 / 192
Core specs processed: 100 / 192
Core specs processed: 125 / 192
Core specs processed: 150 / 192
Core specs processed: 175 / 192
Core specs processed: 192 / 192

Building Secondary pass matrices...
Secondary specs processed: 25 / 192
Secondary specs processed: 50 / 192
Secondary specs processed: 75 / 192
Secondary specs processed: 100 / 192
Secondary specs processed: 125 / 192
Secondary specs processed: 150 / 192
Secondary specs processed: 175 / 192
Secondary specs processed: 192 / 192

Core layer summary:

,specs,min_candidate_frequency,median_candidate_frequency,max_candidate_frequency,min_core_layer_win_rate,median_core_layer_win_rate,max_core_layer_win_rate,min_core_layer_avg_pnl_per_day,median_core_layer_avg_pnl_per_day,max_core_layer_avg_pnl_per_day
0,192,0.071719,0.12111,0.200947,0.707965,0.764262,0.803704,310.975356,373.234552,440.881021

Running full model combinations: 36,864
Full models processed: 4,800 / 36,864
Full models processed: 9,600 / 36,864
Full models processed: 14,400 / 36,864
Full models processed: 19,200 / 36,864
Full models processed: 24,000 / 36,864
Full models processed: 28,800 / 36,864
Full models processed: 33,600 / 36,864
Full models processed: 36,864 / 36,864

Full model summary:

,full_models,models_meeting_all_targets,models_core_win_85,models_overall_win_80,models_frequency_33,max_overall_frequency,median_overall_frequency,max_overall_win_rate,median_overall_win_rate,max_core_win_rate,median_core_win_rate,max_overall_avg_pnl_per_day,median_overall_avg_pnl_per_day
0,36864,0,0,3,384,0.336265,0.233424,0.801858,0.750988,0.803704,0.764262,419.623044,264.390287

Top full models by review rank:

,review_rank,meets_all_targets,overall_trades,overall_frequency,overall_win_rate,overall_avg_pnl_per_day,overall_exposure_day_weighted_pnl_per_day,overall_total_pnl,overall_profit_factor,overall_worst_trade_pnl,...,front_selected_win_rate,front_selected_avg_pnl_per_day,middle_selected_trades,middle_selected_win_rate,middle_selected_avg_pnl_per_day,back_selected_trades,back_selected_win_rate,back_selected_avg_pnl_per_day,core_spec_id,secondary_spec_id
0,1,False,323,0.218539,0.801858,345.533106,398.173146,2.464294e+06,2.593327,-108475.796818,...,0.709302,195.232541,79,0.860759,483.217635,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
1,2,False,316,0.213802,0.800633,344.251337,397.314587,2.423222e+06,2.578518,-108475.796818,...,0.704819,188.373993,78,0.858974,482.824830,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
2,3,False,320,0.216509,0.800000,344.380842,397.334853,2.429703e+06,2.570961,-108475.796818,...,0.709302,195.232541,76,0.855263,483.800912,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
3,4,False,294,0.198917,0.799320,370.557947,411.004867,2.378896e+06,2.708883,-108475.796818,...,0.700637,230.379844,57,0.877193,553.292131,80,0.937500,515.459368,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
4,5,False,303,0.205007,0.798680,371.317049,409.560866,2.445488e+06,2.743652,-108475.796818,...,0.696774,231.530282,76,0.855263,483.800912,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
5,6,False,325,0.219892,0.796923,343.768255,392.266970,2.470890e+06,2.595099,-108475.796818,...,0.702381,194.625301,80,0.850000,471.015723,77,0.948052,536.965902,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
6,7,False,289,0.195535,0.795848,368.152548,409.406664,2.327886e+06,2.672240,-108475.796818,...,0.694805,224.468708,57,0.877193,553.292131,78,0.935897,516.541718,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
7,8,False,318,0.215156,0.795597,343.891460,400.140843,2.374036e+06,2.541071,-108475.796818,...,0.708108,198.523504,60,0.883333,549.049589,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
8,9,False,318,0.215156,0.795597,342.455698,391.338011,2.429818e+06,2.580327,-108475.796818,...,0.697531,187.574915,79,0.848101,470.473435,77,0.948052,536.965902,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
9,10,False,318,0.215156,0.795597,348.184822,398.125785,2.332221e+06,2.504420,-108475.796818,...,0.723757,217.757296,87,0.862069,485.113281,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
10,11,False,298,0.201624,0.795302,365.695583,403.616546,2.403940e+06,2.725501,-108475.796818,...,0.688742,223.834237,60,0.866667,527.181494,87,0.931034,500.545106,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
11,12,False,317,0.214479,0.794953,343.217660,399.581937,2.362328e+06,2.533472,-108475.796818,...,0.708108,198.523504,60,0.866667,537.002450,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
12,13,False,317,0.214479,0.794953,348.931114,398.303238,2.360743e+06,2.533929,-108475.796818,...,0.701754,195.430551,81,0.864198,498.543137,65,0.953846,566.316071,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
13,14,False,312,0.211096,0.794872,343.792281,400.005102,2.343630e+06,2.532786,-108475.796818,...,0.705556,195.500232,59,0.881356,548.906596,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
14,15,False,307,0.207713,0.794788,326.452856,384.925436,2.259512e+06,2.415474,-108475.796818,...,0.702857,160.845011,60,0.866667,537.002450,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
15,16,False,331,0.223951,0.794562,321.804060,376.573182,2.390863e+06,2.416458,-108475.796818,...,0.701087,154.184205,61,0.885246,582.995690,86,0.930233,495.168758,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
16,17,False,287,0.194181,0.794425,371.388184,414.453274,2.322182e+06,2.691759,-108475.796818,...,0.692308,223.427217,59,0.864407,540.351865,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
17,18,False,311,0.210419,0.794212,341.737472,399.159543,2.337877e+06,2.529024,-108475.796818,...,0.702247,189.043357,61,0.868852,537.338248,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
18,19,False,311,0.210419,0.794212,346.513226,392.676358,2.270455e+06,2.455952,-108475.796818,...,0.724138,220.423260,87,0.850575,463.311710,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
19,20,False,296,0.200271,0.793919,369.779786,411.460884,2.370838e+06,2.716604,-108475.796818,...,0.695122,229.161081,58,0.879310,550.613427,74,0.945946,539.686766,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
20,21,False,291,0.196888,0.793814,367.593735,407.935464,2.343181e+06,2.683870,-108475.796818,...,0.691275,223.600433,70,0.842857,482.861562,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
21,22,False,320,0.216509,0.793750,332.181106,377.250175,2.259729e+06,2.396494,-108475.796818,...,0.710983,198.610825,90,0.855556,473.300857,57,0.947368,514.757967,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
22,23,False,320,0.216509,0.793750,342.489637,383.711627,2.388221e+06,2.509968,-108475.796818,...,0.698795,193.919066,69,0.855072,515.127249,85,0.929412,492.498103,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
23,24,False,315,0.213126,0.793651,342.705271,399.290775,2.339445e+06,2.518617,-108475.796818,...,0.708108,198.523504,57,0.877193,553.292131,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
24,25,False,315,0.213126,0.793651,347.039522,397.238914,2.297630e+06,2.482107,-108475.796818,...,0.723757,217.757296,84,0.857143,485.708710,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
25,26,False,310,0.209743,0.793548,341.041508,398.589828,2.326170e+06,2.521367,-108475.796818,...,0.702247,189.043357,60,0.866667,537.002450,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
26,27,False,310,0.209743,0.793548,347.701265,397.408148,2.319671e+06,2.518599,-108475.796818,...,0.696970,188.537636,80,0.862500,498.351720,65,0.953846,566.316071,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
27,28,False,334,0.225981,0.793413,317.050401,378.751669,2.396362e+06,2.424831,-108475.796818,...,0.708543,160.828232,62,0.870968,539.445851,73,0.958904,554.032508,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
28,29,False,300,0.202977,0.793333,375.733115,410.827354,2.384442e+06,2.709410,-108475.796818,...,0.688312,230.697375,81,0.864198,498.543137,65,0.953846,566.316071,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
29,30,False,329,0.222598,0.793313,338.912662,386.689621,2.345659e+06,2.432192,-108475.796818,...,0.722826,218.408621,94,0.851064,442.764492,51,0.941176,582.259163,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
30,31,False,314,0.212449,0.792994,342.021256,398.721727,2.327737e+06,2.511017,-108475.796818,...,0.708108,198.523504,57,0.859649,540.610933,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
31,32,False,314,0.212449,0.792994,288.468319,360.751499,2.199502e+06,2.343395,-108475.796818,...,0.717647,143.365588,76,0.828947,410.536465,68,0.941176,514.796044,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
32,33,False,285,0.192828,0.792982,370.538107,414.019275,2.304431e+06,2.678828,-108475.796818,...,0.690323,221.080805,58,0.862069,542.807462,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
33,34,False,309,0.209066,0.792880,342.582097,399.142423,2.309039e+06,2.510163,-108475.796818,...,0.705556,195.500232,56,0.875000,553.217238,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
34,35,False,304,0.205683,0.792763,325.051654,383.871866,2.224921e+06,2.393805,-108475.796818,...,0.702857,160.845011,56,0.875000,553.217238,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
35,36,False,323,0.218539,0.792570,314.273270,378.126627,2.323210e+06,2.388335,-108475.796818,...,0.703704,149.088554,61,0.868852,539.150108,73,0.958904,554.032508,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
36,37,False,323,0.218539,0.792570,386.636114,430.446909,2.544802e+06,2.894299,-108475.796818,...,0.703030,280.732498,86,0.872093,499.668557,72,0.902778,494.320928,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
37,38,False,318,0.215156,0.792453,314.766730,378.513679,2.287358e+06,2.375925,-108475.796818,...,0.702703,148.277298,59,0.881356,548.906596,74,0.945946,544.311228,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
38,39,False,313,0.211773,0.792332,339.001860,397.248030,2.318340e+06,2.509231,-108475.796818,...,0.704918,190.613496,57,0.877193,553.292131,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
39,40,False,313,0.211773,0.792332,337.593333,396.986097,2.332690e+06,2.518574,-108475.796818,...,0.700000,183.533761,61,0.868852,537.338248,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
40,41,False,313,0.211773,0.792332,330.588445,376.043495,2.218657e+06,2.380935,-108475.796818,...,0.706587,191.914721,89,0.853933,472.845176,57,0.947368,514.757967,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
41,42,False,313,0.211773,0.792332,344.838712,390.328483,2.339629e+06,2.518037,-108475.796818,...,0.693750,186.754067,88,0.852273,468.674108,65,0.953846,566.316071,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
42,43,False,308,0.208390,0.792208,340.503344,398.285746,2.303286e+06,2.506400,-108475.796818,...,0.702247,189.043357,57,0.877193,553.292131,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
43,44,False,308,0.208390,0.792208,339.071951,398.014301,2.317637e+06,2.515786,-108475.796818,...,0.697143,181.734428,61,0.868852,537.338248,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
44,45,False,308,0.208390,0.792208,345.758697,396.304522,2.256558e+06,2.466501,-108475.796818,...,0.720000,212.023750,83,0.855422,485.369580,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
45,46,False,303,0.205007,0.792079,297.991438,372.181416,2.124039e+06,2.367903,-108475.796818,...,0.725714,156.707376,80,0.825000,414.937566,48,0.979167,618.179369,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
46,47,False,327,0.221245,0.792049,315.272070,378.569803,2.350540e+06,2.406757,-108475.796818,...,0.703125,152.103911,62,0.870968,539.445851,73,0.958904,554.032508,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
47,48,False,298,0.201624,0.791946,371.166152,411.215065,2.370244e+06,2.702657,-108475.796818,...,0.694611,233.438766,59,0.864407,538.478586,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
48,49,False,298,0.201624,0.791946,324.698746,398.938339,2.138708e+06,2.506494,-108475.796818,...,0.731844,205.505810,71,0.816901,426.789809,48,0.979167,618.179369,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
49,50,False,298,0.201624,0.791946,374.579349,410.179997,2.313415e+06,2.645247,-108475.796818,...,0.713415,254.397971,84,0.857143,485.708710,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...

Top models meeting all targets:

Empty DataFrame
Columns: [review_rank, meets_all_targets, overall_trades, overall_frequency, overall_win_rate, overall_avg_pnl_per_day, overall_exposure_day_weighted_pnl_per_day, overall_total_pnl, overall_profit_factor, overall_worst_trade_pnl, overall_worst_pnl_per_day, overall_avg_actual_dte, overall_avg_selected_tenor, core_trades, core_frequency, core_win_rate, core_avg_pnl_per_day, core_exposure_day_weighted_pnl_per_day, core_total_pnl, core_worst_trade_pnl, core_avg_actual_dte, core_avg_selected_tenor, secondary_trades, secondary_frequency, secondary_win_rate, secondary_avg_pnl_per_day, secondary_exposure_day_weighted_pnl_per_day, secondary_total_pnl, secondary_worst_trade_pnl, secondary_avg_actual_dte, secondary_avg_selected_tenor, front_selected_trades, front_selected_win_rate, front_selected_avg_pnl_per_day, middle_selected_trades, middle_selected_win_rate, middle_selected_avg_pnl_per_day, back_selected_trades, back_selected_win_rate, back_selected_avg_pnl_per_day, core_spec_id, secondary_spec_id]
Index: []

[0 rows x 42 columns]

Highest-frequency models with overall win rate >= 80% and core win rate >= 85%:

Empty DataFrame
Columns: [review_rank, meets_all_targets, overall_trades, overall_frequency, overall_win_rate, overall_avg_pnl_per_day, overall_exposure_day_weighted_pnl_per_day, overall_total_pnl, overall_profit_factor, overall_worst_trade_pnl, overall_worst_pnl_per_day, overall_avg_actual_dte, overall_avg_selected_tenor, core_trades, core_frequency, core_win_rate, core_avg_pnl_per_day, core_exposure_day_weighted_pnl_per_day, core_total_pnl, core_worst_trade_pnl, core_avg_actual_dte, core_avg_selected_tenor, secondary_trades, secondary_frequency, secondary_win_rate, secondary_avg_pnl_per_day, secondary_exposure_day_weighted_pnl_per_day, secondary_total_pnl, secondary_worst_trade_pnl, secondary_avg_actual_dte, secondary_avg_selected_tenor, front_selected_trades, front_selected_win_rate, front_selected_avg_pnl_per_day, middle_selected_trades, middle_selected_win_rate, middle_selected_avg_pnl_per_day, back_selected_trades, back_selected_win_rate, back_selected_avg_pnl_per_day, core_spec_id, secondary_spec_id]
Index: []

[0 rows x 42 columns]

Highest average P&L/day models meeting all targets:

Empty DataFrame
Columns: [review_rank, meets_all_targets, overall_trades, overall_frequency, overall_win_rate, overall_avg_pnl_per_day, overall_exposure_day_weighted_pnl_per_day, overall_total_pnl, overall_profit_factor, overall_worst_trade_pnl, overall_worst_pnl_per_day, overall_avg_actual_dte, overall_avg_selected_tenor, core_trades, core_frequency, core_win_rate, core_avg_pnl_per_day, core_exposure_day_weighted_pnl_per_day, core_total_pnl, core_worst_trade_pnl, core_avg_actual_dte, core_avg_selected_tenor, secondary_trades, secondary_frequency, secondary_win_rate, secondary_avg_pnl_per_day, secondary_exposure_day_weighted_pnl_per_day, secondary_total_pnl, secondary_worst_trade_pnl, secondary_avg_actual_dte, secondary_avg_selected_tenor, front_selected_trades, front_selected_win_rate, front_selected_avg_pnl_per_day, middle_selected_trades, middle_selected_win_rate, middle_selected_avg_pnl_per_day, back_selected_trades, back_selected_win_rate, back_selected_avg_pnl_per_day, core_spec_id, secondary_spec_id]
Index: []

[0 rows x 42 columns]

Cell 3 outputs saved:
Core layer summary:        C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell3_core_layer_summary_20200701_20260519_20260704_090941.csv
Conditional stats:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell3_conditional_stats_old_process_20200701_20260519_20260704_090941.csv
Full model summary:        C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell3_full_model_summary_old_process_20200701_20260519_20260704_090941.csv
Top models:                C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell3_top_models_old_process_20200701_20260519_20260704_090941.csv
Target models:             C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell3_models_meeting_targets_old_process_20200701_20260519_20260704_090941.csv
High frequency win models: C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell3_high_frequency_win_models_old_process_20200701_20260519_20260704_090941.csv

Cell 3 complete.

In [6]:
# Cell 4: Phase 1 diagnostic breakdown
#
# Approved scope:
#   Diagnose Cell 3 results only.
#
# This cell answers:
#   1. Which Core specs came closest to 85% win rate?
#   2. Which parameter triples helped or hurt Core win rate?
#   3. Is the Core problem front / middle / back?
#   4. Which full models nearly met targets?
#   5. How did top models perform by year?
#   6. Where are losses concentrated?
#
# This cell does NOT:
#   - Create new parameter grids.
#   - Change thresholds.
#   - Lock a model.
#   - Run sizing.
#   - Run walk-forward validation.

from pathlib import Path
import numpy as np
import pandas as pd


# -----------------------------
# 1. Paths / load latest files
# -----------------------------

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

PARAM_SWEEP_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "corsi_parameter_sweep_clean"
PARAM_SWEEP_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "corsi_parameter_sweep_clean"
CORSI_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "forecast_model_corsi_v1"

RUN_TIMESTAMP = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")

clean_panel_candidates = sorted(
    PARAM_SWEEP_PROCESSED_DIR.glob("02_corsi_parameter_sweep_clean_panel_*.parquet")
)

spec_candidates = sorted(
    PARAM_SWEEP_AUDIT_DIR.glob("02_corsi_parameter_sweep_clean_cell2_all_phase1_specs_*.csv")
)

model_summary_candidates = sorted(
    PARAM_SWEEP_AUDIT_DIR.glob("02_corsi_parameter_sweep_clean_cell3_full_model_summary_old_process_*.csv")
)

core_layer_summary_candidates = sorted(
    PARAM_SWEEP_AUDIT_DIR.glob("02_corsi_parameter_sweep_clean_cell3_core_layer_summary_*.csv")
)

conditional_stats_candidates = sorted(
    PARAM_SWEEP_AUDIT_DIR.glob("02_corsi_parameter_sweep_clean_cell3_conditional_stats_old_process_*.csv")
)

if not clean_panel_candidates:
    raise FileNotFoundError("No clean panel found.")

if not spec_candidates:
    raise FileNotFoundError("No Cell 2 specs file found.")

if not model_summary_candidates:
    raise FileNotFoundError("No Cell 3 full model summary file found.")

if not core_layer_summary_candidates:
    raise FileNotFoundError("No Cell 3 core layer summary file found.")

if not conditional_stats_candidates:
    raise FileNotFoundError("No Cell 3 conditional stats file found.")

CLEAN_PANEL_PATH = clean_panel_candidates[-1]
ALL_SPECS_PATH = spec_candidates[-1]
MODEL_SUMMARY_PATH = model_summary_candidates[-1]
CORE_LAYER_SUMMARY_PATH = core_layer_summary_candidates[-1]
CONDITIONAL_STATS_PATH = conditional_stats_candidates[-1]

print("Cell 4: Phase 1 diagnostic breakdown")
print(f"Clean panel:             {CLEAN_PANEL_PATH}")
print(f"All specs:               {ALL_SPECS_PATH}")
print(f"Cell 3 model summary:    {MODEL_SUMMARY_PATH}")
print(f"Cell 3 core summary:     {CORE_LAYER_SUMMARY_PATH}")
print(f"Cell 3 conditional stats:{CONDITIONAL_STATS_PATH}")
print(f"Run timestamp:           {RUN_TIMESTAMP}")

panel = pd.read_parquet(CLEAN_PANEL_PATH).copy()
all_specs = pd.read_csv(ALL_SPECS_PATH).copy()
model_summary = pd.read_csv(MODEL_SUMMARY_PATH).copy()
core_layer_summary = pd.read_csv(CORE_LAYER_SUMMARY_PATH).copy()
conditional_stats = pd.read_csv(CONDITIONAL_STATS_PATH).copy()

panel["date"] = pd.to_datetime(panel["date"]).dt.normalize()
panel["trade_date"] = pd.to_numeric(panel["trade_date"], errors="coerce").astype(int)
panel["tenor"] = pd.to_numeric(panel["tenor"], errors="coerce").astype(int)

core_specs = all_specs.loc[all_specs["role"].eq("Core")].copy()
secondary_specs = all_specs.loc[all_specs["role"].eq("Secondary")].copy()

print()
print("Loaded input summary:")
display(pd.DataFrame([{
    "clean_panel_rows": len(panel),
    "all_specs": len(all_specs),
    "core_specs": len(core_specs),
    "secondary_specs": len(secondary_specs),
    "full_models": len(model_summary),
    "core_layer_summary_rows": len(core_layer_summary),
    "conditional_stats_rows": len(conditional_stats),
}]))


# -----------------------------
# 2. Merge Core params onto Core layer summary
# -----------------------------

core_diag = core_layer_summary.merge(
    core_specs,
    on="spec_id",
    how="left",
    validate="one_to_one",
)

# Useful composite labels for grouping.
core_diag["vrp_triple"] = (
    core_diag["front_vrp_log_min"].map("{:.2f}".format)
    + " / "
    + core_diag["middle_vrp_log_min"].map("{:.2f}".format)
    + " / "
    + core_diag["back_vrp_log_min"].map("{:.2f}".format)
)

core_diag["z_triple"] = (
    core_diag["front_z_3m_min"].map("{:.2f}".format)
    + " / "
    + core_diag["middle_z_3m_min"].map("{:.2f}".format)
    + " / "
    + core_diag["back_z_3m_min"].map("{:.2f}".format)
)

core_diag["rsi_triple"] = (
    core_diag["front_rsi14_max"].astype(int).astype(str)
    + " / "
    + core_diag["middle_rsi14_max"].astype(int).astype(str)
    + " / "
    + core_diag["back_rsi14_max"].astype(int).astype(str)
)

core_diag["rv21d_triple"] = (
    core_diag["front_rv21d_min"].map("{:.1f}".format)
    + " / "
    + core_diag["middle_rv21d_min"].map("{:.1f}".format)
    + " / "
    + core_diag["back_rv21d_min"].map("{:.1f}".format)
)

core_diag["core_win_gap_to_85"] = 0.85 - core_diag["core_layer_win_rate"]
core_diag["core_win_80_plus"] = core_diag["core_layer_win_rate"].ge(0.80)
core_diag["core_win_82_plus"] = core_diag["core_layer_win_rate"].ge(0.82)
core_diag["core_win_85_plus"] = core_diag["core_layer_win_rate"].ge(0.85)


# -----------------------------
# 3. Core specs closest to 85%
# -----------------------------

core_review_cols = [
    "spec_id",
    "candidate_frequency",
    "core_layer_trades",
    "core_layer_frequency",
    "core_layer_win_rate",
    "core_win_gap_to_85",
    "core_layer_avg_pnl_per_day",
    "core_layer_exposure_day_weighted_pnl_per_day",
    "core_layer_total_pnl",
    "core_layer_profit_factor",
    "core_layer_worst_trade_pnl",
    "core_layer_worst_pnl_per_day",
    "core_layer_avg_actual_dte",
    "core_layer_avg_selected_tenor",
    "vrp_triple",
    "z_triple",
    "rsi_triple",
    "rv21d_triple",
]

print()
print("Core specs closest to 85% win rate:")
display(
    core_diag[core_review_cols]
    .sort_values(
        [
            "core_layer_win_rate",
            "core_layer_avg_pnl_per_day",
            "core_layer_frequency",
            "core_layer_total_pnl",
        ],
        ascending=[False, False, False, False],
    )
    .head(50)
)


# -----------------------------
# 4. Core parameter-group diagnostics
# -----------------------------

def parameter_group_summary(df, group_col):
    out = (
        df
        .groupby(group_col)
        .agg(
            specs=("spec_id", "nunique"),
            max_core_win_rate=("core_layer_win_rate", "max"),
            median_core_win_rate=("core_layer_win_rate", "median"),
            min_core_win_gap_to_85=("core_win_gap_to_85", "min"),
            max_core_frequency=("core_layer_frequency", "max"),
            median_core_frequency=("core_layer_frequency", "median"),
            max_core_avg_pnl_per_day=("core_layer_avg_pnl_per_day", "max"),
            median_core_avg_pnl_per_day=("core_layer_avg_pnl_per_day", "median"),
            max_core_total_pnl=("core_layer_total_pnl", "max"),
            specs_core_win_80_plus=("core_win_80_plus", "sum"),
            specs_core_win_82_plus=("core_win_82_plus", "sum"),
            specs_core_win_85_plus=("core_win_85_plus", "sum"),
        )
        .reset_index()
        .sort_values(
            [
                "max_core_win_rate",
                "median_core_win_rate",
                "max_core_avg_pnl_per_day",
            ],
            ascending=[False, False, False],
        )
    )
    return out


core_by_vrp = parameter_group_summary(core_diag, "vrp_triple")
core_by_z = parameter_group_summary(core_diag, "z_triple")
core_by_rsi = parameter_group_summary(core_diag, "rsi_triple")
core_by_rv21d = parameter_group_summary(core_diag, "rv21d_triple")

print()
print("Core win rate by VRP triple:")
display(core_by_vrp)

print()
print("Core win rate by z-score triple:")
display(core_by_z)

print()
print("Core win rate by RSI cap triple:")
display(core_by_rsi)

print()
print("Core win rate by RV21D floor triple:")
display(core_by_rv21d)


# -----------------------------
# 5. Core conditional stats by tenor / bucket
# -----------------------------

core_conditional = conditional_stats.loc[
    conditional_stats["layer"].eq("Core")
].copy()

# Keep only top Core specs by Core win rate for focused diagnostics.
top_core_ids = (
    core_diag
    .sort_values(
        [
            "core_layer_win_rate",
            "core_layer_avg_pnl_per_day",
            "core_layer_frequency",
        ],
        ascending=[False, False, False],
    )
    .head(25)["spec_id"]
    .tolist()
)

top_core_conditional = core_conditional.loc[
    core_conditional["spec_id"].isin(top_core_ids)
].copy()

print()
print("Top Core specs: conditional tenor stats:")
display(
    top_core_conditional[
        [
            "spec_id",
            "tenor",
            "tenor_bucket",
            "conditional_obs",
            "conditional_sample_ok",
            "conditional_win_probability",
            "conditional_avg_pnl_per_day",
            "conditional_aggregate_pnl_per_day",
            "conditional_total_pnl",
            "conditional_worst_trade_pnl",
            "conditional_worst_pnl_per_day",
            "conditional_avg_actual_dte",
        ]
    ]
    .sort_values(
        [
            "spec_id",
            "conditional_win_probability",
            "conditional_avg_pnl_per_day",
            "tenor",
        ],
        ascending=[True, False, False, False],
    )
)

core_conditional_by_bucket = (
    top_core_conditional
    .groupby("tenor_bucket")
    .agg(
        rows=("spec_id", "size"),
        median_conditional_obs=("conditional_obs", "median"),
        max_conditional_obs=("conditional_obs", "max"),
        median_win_probability=("conditional_win_probability", "median"),
        max_win_probability=("conditional_win_probability", "max"),
        median_avg_pnl_per_day=("conditional_avg_pnl_per_day", "median"),
        max_avg_pnl_per_day=("conditional_avg_pnl_per_day", "max"),
        worst_trade_pnl=("conditional_worst_trade_pnl", "min"),
    )
    .reset_index()
    .sort_values("median_win_probability", ascending=False)
)

print()
print("Top Core specs: conditional stats by bucket:")
display(core_conditional_by_bucket)


# -----------------------------
# 6. Top full models / near-target models
# -----------------------------

model_summary["overall_win_gap_to_80"] = 0.80 - model_summary["overall_win_rate"]
model_summary["core_win_gap_to_85"] = 0.85 - model_summary["core_win_rate"]
model_summary["frequency_gap_to_33"] = 0.33 - model_summary["overall_frequency"]

model_summary["near_target_score"] = (
    model_summary["overall_win_gap_to_80"].clip(lower=0)
    + model_summary["core_win_gap_to_85"].clip(lower=0)
    + model_summary["frequency_gap_to_33"].clip(lower=0)
)

near_target_cols = [
    "review_rank",
    "near_target_score",
    "meets_all_targets",
    "overall_trades",
    "overall_frequency",
    "frequency_gap_to_33",
    "overall_win_rate",
    "overall_win_gap_to_80",
    "core_win_rate",
    "core_win_gap_to_85",
    "overall_avg_pnl_per_day",
    "overall_exposure_day_weighted_pnl_per_day",
    "overall_total_pnl",
    "overall_profit_factor",
    "overall_worst_trade_pnl",
    "core_trades",
    "core_frequency",
    "core_avg_pnl_per_day",
    "core_total_pnl",
    "secondary_trades",
    "secondary_frequency",
    "secondary_win_rate",
    "secondary_avg_pnl_per_day",
    "secondary_total_pnl",
    "front_selected_trades",
    "front_selected_win_rate",
    "front_selected_avg_pnl_per_day",
    "middle_selected_trades",
    "middle_selected_win_rate",
    "middle_selected_avg_pnl_per_day",
    "back_selected_trades",
    "back_selected_win_rate",
    "back_selected_avg_pnl_per_day",
    "core_spec_id",
    "secondary_spec_id",
]

print()
print("Top models closest to all targets:")
display(
    model_summary[near_target_cols]
    .sort_values(
        [
            "near_target_score",
            "overall_win_rate",
            "core_win_rate",
            "overall_frequency",
            "overall_avg_pnl_per_day",
        ],
        ascending=[True, False, False, False, False],
    )
    .head(50)
)

print()
print("Highest-frequency models with overall win rate >= 79%:")
display(
    model_summary
    .loc[model_summary["overall_win_rate"].ge(0.79), near_target_cols]
    .sort_values(
        [
            "overall_frequency",
            "overall_win_rate",
            "overall_avg_pnl_per_day",
        ],
        ascending=[False, False, False],
    )
    .head(50)
)

print()
print("Highest overall win-rate models:")
display(
    model_summary[near_target_cols]
    .sort_values(
        [
            "overall_win_rate",
            "overall_avg_pnl_per_day",
            "overall_frequency",
        ],
        ascending=[False, False, False],
    )
    .head(50)
)


# -----------------------------
# 7. Reconstruct selected trades for top models for year / loss diagnostics
# -----------------------------

# This section reconstructs selected rows for a small set of top models only.
# It repeats the Cell 3 old-process logic, but only for diagnostics.

def first_existing_col(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    return None


def load_actual_dte_lookup():
    outcome_discovery_candidates = sorted(
        CORSI_AUDIT_DIR.glob("corsi_cell11_trade_outcome_file_discovery_*.csv")
    )

    if not outcome_discovery_candidates:
        return None

    discovery_path = outcome_discovery_candidates[-1]
    discovery = pd.read_csv(discovery_path)
    discovery.columns = [str(c).strip() for c in discovery.columns]

    file_col = "chosen_file" if "chosen_file" in discovery.columns else "path"

    if file_col not in discovery.columns:
        return None

    preferred = discovery.copy()

    if "eligible_for_backtest" in preferred.columns:
        preferred = preferred.loc[preferred["eligible_for_backtest"].astype(bool)].copy()

    if preferred.empty:
        return None

    if "score" in preferred.columns:
        preferred["_score"] = pd.to_numeric(preferred["score"], errors="coerce")
    else:
        preferred["_score"] = 0.0

    if "chosen_outcome_col" in preferred.columns:
        preferred["_preferred_pnl"] = preferred["chosen_outcome_col"].eq("normalized_pnl_dollars")
    elif "outcome_col" in preferred.columns:
        preferred["_preferred_pnl"] = preferred["outcome_col"].eq("normalized_pnl_dollars")
    else:
        preferred["_preferred_pnl"] = False

    preferred = preferred.sort_values(
        ["_preferred_pnl", "_score"],
        ascending=[False, False],
    )

    for _, row in preferred.iterrows():
        path = Path(row[file_col])

        if not path.exists():
            continue

        try:
            raw = pd.read_parquet(path) if path.suffix.lower() == ".parquet" else pd.read_csv(path)
        except Exception:
            continue

        raw.columns = [str(c).strip() for c in raw.columns]

        trade_date_col = first_existing_col(raw, ["trade_date", "trade_dt", "date"])
        tenor_col = first_existing_col(raw, ["tenor", "entry_tenor", "target_tenor"])
        actual_dte_col = first_existing_col(raw, ["actual_dte"])

        if trade_date_col is None or tenor_col is None or actual_dte_col is None:
            continue

        lookup = raw[[trade_date_col, tenor_col, actual_dte_col]].copy()
        lookup = lookup.rename(columns={
            trade_date_col: "trade_date",
            tenor_col: "tenor",
            actual_dte_col: "actual_dte",
        })

        lookup["trade_date"] = pd.to_numeric(lookup["trade_date"], errors="coerce").astype("Int64")
        lookup["tenor"] = pd.to_numeric(lookup["tenor"], errors="coerce").astype("Int64")
        lookup["actual_dte"] = pd.to_numeric(lookup["actual_dte"], errors="coerce")

        lookup = lookup.dropna(subset=["trade_date", "tenor"])
        lookup["trade_date"] = lookup["trade_date"].astype(int)
        lookup["tenor"] = lookup["tenor"].astype(int)

        lookup = lookup.drop_duplicates(["trade_date", "tenor"])

        return lookup

    return None


diagnostic_panel = panel.copy()

if "actual_dte" not in diagnostic_panel.columns:
    actual_dte_lookup = load_actual_dte_lookup()

    if actual_dte_lookup is not None:
        diagnostic_panel = diagnostic_panel.merge(
            actual_dte_lookup,
            on=["trade_date", "tenor"],
            how="left",
            validate="many_to_one",
        )
    else:
        diagnostic_panel["actual_dte"] = np.nan

diagnostic_panel["actual_dte"] = pd.to_numeric(diagnostic_panel["actual_dte"], errors="coerce")
diagnostic_panel["actual_dte_for_pnl_day"] = diagnostic_panel["actual_dte"]

fallback_mask = (
    diagnostic_panel["actual_dte_for_pnl_day"].isna()
    | diagnostic_panel["actual_dte_for_pnl_day"].le(0)
)

diagnostic_panel.loc[fallback_mask, "actual_dte_for_pnl_day"] = diagnostic_panel.loc[fallback_mask, "tenor"]
diagnostic_panel["pnl_per_day"] = diagnostic_panel["outcome_value"] / diagnostic_panel["actual_dte_for_pnl_day"]
diagnostic_panel["year"] = diagnostic_panel["date"].dt.year

TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]
TENOR_BUCKET_MAP = {
    9: "front",
    12: "front",
    15: "front",
    18: "middle",
    21: "middle",
    24: "middle",
    27: "back",
    30: "back",
    33: "back",
}
BUCKETS = ["front", "middle", "back"]
WIN_BAND = 0.0025
MIN_CONDITIONAL_OBS = 20

eligible = diagnostic_panel.loc[
    diagnostic_panel["is_parameter_sweep_eligible"].astype(bool)
].copy()

eligible = eligible.replace([np.inf, -np.inf], np.nan)

needed_for_matrix = [
    "trade_date",
    "date",
    "year",
    "tenor",
    "tenor_bucket",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rsi14",
    "rv21d",
    "outcome_value",
    "actual_dte_for_pnl_day",
    "pnl_per_day",
]

eligible = eligible.dropna(subset=needed_for_matrix).copy()
eligible = eligible.loc[eligible["tenor"].isin(TENORS)].copy()

date_counts = eligible.groupby("trade_date")["tenor"].nunique()
complete_dates = date_counts.loc[date_counts.eq(len(TENORS))].index.tolist()
eligible = eligible.loc[eligible["trade_date"].isin(complete_dates)].copy()

eligible_dates = sorted(eligible["trade_date"].unique())
num_dates = len(eligible_dates)
num_tenors = len(TENORS)

date_meta = (
    eligible[["trade_date", "date", "year"]]
    .drop_duplicates("trade_date")
    .set_index("trade_date")
    .loc[eligible_dates]
)

date_array = date_meta["date"].to_numpy()
year_array = date_meta["year"].to_numpy()

def pivot_matrix(col, dtype=float):
    mat = (
        eligible
        .pivot(index="trade_date", columns="tenor", values=col)
        .reindex(index=eligible_dates, columns=TENORS)
    )

    if mat.isna().any().any():
        raise ValueError(f"Missing matrix cells for {col}")

    return mat.to_numpy(dtype=dtype)

vrp_mat = pivot_matrix("vrp_log")
z3m_mat = pivot_matrix("vrp_z_3m")
z1y_mat = pivot_matrix("vrp_z_1y")
rsi_mat = pivot_matrix("rsi14")
rv21d_mat = pivot_matrix("rv21d")
pnl_mat = pivot_matrix("outcome_value")
pnl_per_day_mat = pivot_matrix("pnl_per_day")
actual_dte_mat = pivot_matrix("actual_dte_for_pnl_day")

tenor_array = np.array(TENORS, dtype=int)
tenor_bucket_array = np.array([TENOR_BUCKET_MAP[int(t)] for t in tenor_array], dtype=object)
valid_outcome_mat = np.isfinite(pnl_mat) & np.isfinite(pnl_per_day_mat)

def threshold_array_for_spec(spec_row, field_suffix):
    vals = []
    for tenor in TENORS:
        bucket = TENOR_BUCKET_MAP[int(tenor)]
        vals.append(float(spec_row[f"{bucket}_{field_suffix}"]))
    return np.array(vals, dtype=float)

def build_pass_matrix(spec_row):
    vrp_threshold = threshold_array_for_spec(spec_row, "vrp_log_min")
    z3m_threshold = threshold_array_for_spec(spec_row, "z_3m_min")
    z1y_threshold = threshold_array_for_spec(spec_row, "z_1y_min")
    rsi_cap = threshold_array_for_spec(spec_row, "rsi14_max")
    rv21d_floor = threshold_array_for_spec(spec_row, "rv21d_min")

    return (
        (vrp_mat >= vrp_threshold[None, :])
        & (z3m_mat >= z3m_threshold[None, :])
        & (z1y_mat >= z1y_threshold[None, :])
        & (rsi_mat <= rsi_cap[None, :])
        & (rv21d_mat >= rv21d_floor[None, :])
        & valid_outcome_mat
    )

def compute_stats_for_selection(pass_matrix, date_mask):
    rows = []
    date_mask = np.asarray(date_mask, dtype=bool)

    for col_idx, tenor in enumerate(TENORS):
        candidate_mask = pass_matrix[:, col_idx] & date_mask
        count = int(candidate_mask.sum())

        if count == 0:
            rows.append({
                "tenor": int(tenor),
                "conditional_obs": 0,
                "conditional_win_probability": np.nan,
                "conditional_avg_pnl_per_day": np.nan,
                "conditional_aggregate_pnl_per_day": np.nan,
            })
            continue

        pnl = pnl_mat[candidate_mask, col_idx]
        pnl_day = pnl_per_day_mat[candidate_mask, col_idx]
        dte = actual_dte_mat[candidate_mask, col_idx]

        rows.append({
            "tenor": int(tenor),
            "conditional_obs": count,
            "conditional_win_probability": float(np.nanmean(pnl > 0)),
            "conditional_avg_pnl_per_day": float(np.nanmean(pnl_day)),
            "conditional_aggregate_pnl_per_day": float(np.nansum(pnl) / np.nansum(dte)),
        })

    return pd.DataFrame(rows)

def select_cols(pass_matrix, stats_df, date_mask):
    date_mask = np.asarray(date_mask, dtype=bool)
    active_pass = pass_matrix & date_mask[:, None]

    stats_df = stats_df.sort_values("tenor").reset_index(drop=True)

    obs = stats_df["conditional_obs"].to_numpy(dtype=float)
    win = stats_df["conditional_win_probability"].to_numpy(dtype=float)
    avg_day = stats_df["conditional_avg_pnl_per_day"].to_numpy(dtype=float)
    agg_day = stats_df["conditional_aggregate_pnl_per_day"].to_numpy(dtype=float)

    has_stats = (
        (obs > 0)
        & np.isfinite(win)
        & np.isfinite(avg_day)
        & np.isfinite(agg_day)
    )

    sample_ok = obs >= MIN_CONDITIONAL_OBS

    active = active_pass & has_stats[None, :]
    active_sample_ok = active & sample_ok[None, :]
    row_has_sample_ok = active_sample_ok.any(axis=1)

    ranking_universe = np.where(row_has_sample_ok[:, None], active_sample_ok, active)

    win_masked = np.where(ranking_universe, win[None, :], -np.inf)
    best_win = win_masked.max(axis=1)
    row_has_any = np.isfinite(best_win)

    inside_band = (
        ranking_universe
        & row_has_any[:, None]
        & (win[None, :] >= best_win[:, None] - WIN_BAND)
    )

    selected_col = np.full(num_dates, -1, dtype=int)

    best_avg = np.full(num_dates, -np.inf)
    best_agg = np.full(num_dates, -np.inf)
    best_win_for_tie = np.full(num_dates, -np.inf)
    best_tenor = np.full(num_dates, -np.inf)

    for col_idx, tenor in enumerate(TENORS):
        cand = inside_band[:, col_idx]

        avg_val = avg_day[col_idx]
        agg_val = agg_day[col_idx]
        win_val = win[col_idx]
        tenor_val = float(tenor)

        better = (
            cand
            & (
                (avg_val > best_avg)
                | ((avg_val == best_avg) & (agg_val > best_agg))
                | ((avg_val == best_avg) & (agg_val == best_agg) & (win_val > best_win_for_tie))
                | ((avg_val == best_avg) & (agg_val == best_agg) & (win_val == best_win_for_tie) & (tenor_val > best_tenor))
            )
        )

        selected_col[better] = col_idx
        best_avg[better] = avg_val
        best_agg[better] = agg_val
        best_win_for_tie[better] = win_val
        best_tenor[better] = tenor_val

    return selected_col

def selected_trade_frame(core_spec_id, secondary_spec_id):
    core_row = core_specs.loc[core_specs["spec_id"].eq(core_spec_id)].iloc[0]
    secondary_row = secondary_specs.loc[secondary_specs["spec_id"].eq(secondary_spec_id)].iloc[0]

    core_pass = build_pass_matrix(core_row)
    all_dates_mask = np.ones(num_dates, dtype=bool)
    core_stats = compute_stats_for_selection(core_pass, all_dates_mask)
    core_selected_cols = select_cols(core_pass, core_stats, all_dates_mask)

    core_any_date = core_pass.any(axis=1)
    no_core_date_mask = ~core_any_date

    secondary_pass = build_pass_matrix(secondary_row)
    secondary_stats = compute_stats_for_selection(secondary_pass, no_core_date_mask)
    secondary_selected_cols = select_cols(secondary_pass, secondary_stats, no_core_date_mask)

    combined_cols = np.where(core_selected_cols >= 0, core_selected_cols, secondary_selected_cols)

    rows = []

    for date_idx, col_idx in enumerate(combined_cols):
        if col_idx < 0:
            continue

        layer = "Core" if core_selected_cols[date_idx] >= 0 else "Secondary"
        tenor = int(tenor_array[col_idx])

        rows.append({
            "trade_date": int(eligible_dates[date_idx]),
            "date": pd.to_datetime(date_array[date_idx]),
            "year": int(year_array[date_idx]),
            "layer": layer,
            "tenor": tenor,
            "tenor_bucket": TENOR_BUCKET_MAP[tenor],
            "outcome_value": float(pnl_mat[date_idx, col_idx]),
            "pnl_per_day": float(pnl_per_day_mat[date_idx, col_idx]),
            "actual_dte": float(actual_dte_mat[date_idx, col_idx]),
            "vrp_log": float(vrp_mat[date_idx, col_idx]),
            "vrp_z_3m": float(z3m_mat[date_idx, col_idx]),
            "vrp_z_1y": float(z1y_mat[date_idx, col_idx]),
            "rsi14": float(rsi_mat[date_idx, col_idx]),
            "rv21d": float(rv21d_mat[date_idx, col_idx]),
            "core_spec_id": core_spec_id,
            "secondary_spec_id": secondary_spec_id,
        })

    return pd.DataFrame(rows)

# Top 20 by review rank plus top 20 closest-to-target.
top_model_pairs = (
    pd.concat([
        model_summary.sort_values("review_rank").head(20),
        model_summary.sort_values(
            [
                "near_target_score",
                "overall_win_rate",
                "core_win_rate",
                "overall_frequency",
                "overall_avg_pnl_per_day",
            ],
            ascending=[True, False, False, False, False],
        ).head(20),
    ])
    [["core_spec_id", "secondary_spec_id"]]
    .drop_duplicates()
    .head(30)
)

selected_trade_frames = []

for _, pair in top_model_pairs.iterrows():
    selected_trade_frames.append(
        selected_trade_frame(
            core_spec_id=pair["core_spec_id"],
            secondary_spec_id=pair["secondary_spec_id"],
        )
    )

selected_diagnostics = pd.concat(selected_trade_frames, ignore_index=True)

year_summary = (
    selected_diagnostics
    .groupby(["core_spec_id", "secondary_spec_id", "year"])
    .agg(
        trades=("trade_date", "count"),
        win_rate=("outcome_value", lambda x: float((x > 0).mean())),
        total_pnl=("outcome_value", "sum"),
        avg_pnl_per_day=("pnl_per_day", "mean"),
        worst_trade_pnl=("outcome_value", "min"),
        core_trades=("layer", lambda x: int((x == "Core").sum())),
        secondary_trades=("layer", lambda x: int((x == "Secondary").sum())),
        front_trades=("tenor_bucket", lambda x: int((x == "front").sum())),
        middle_trades=("tenor_bucket", lambda x: int((x == "middle").sum())),
        back_trades=("tenor_bucket", lambda x: int((x == "back").sum())),
    )
    .reset_index()
)

loss_diagnostics = selected_diagnostics.loc[
    selected_diagnostics["outcome_value"] < 0
].copy()

loss_by_bucket_layer = (
    loss_diagnostics
    .groupby(["layer", "tenor_bucket"])
    .agg(
        losses=("trade_date", "count"),
        avg_loss=("outcome_value", "mean"),
        worst_loss=("outcome_value", "min"),
        avg_loss_per_day=("pnl_per_day", "mean"),
        median_vrp_log=("vrp_log", "median"),
        median_z_3m=("vrp_z_3m", "median"),
        median_z_1y=("vrp_z_1y", "median"),
        median_rsi14=("rsi14", "median"),
        median_rv21d=("rv21d", "median"),
    )
    .reset_index()
    .sort_values(["layer", "losses"], ascending=[True, False])
)

loss_by_year = (
    loss_diagnostics
    .groupby(["year", "layer", "tenor_bucket"])
    .agg(
        losses=("trade_date", "count"),
        total_loss=("outcome_value", "sum"),
        worst_loss=("outcome_value", "min"),
        avg_loss_per_day=("pnl_per_day", "mean"),
    )
    .reset_index()
    .sort_values(["year", "total_loss"], ascending=[True, True])
)

worst_selected_trades = (
    selected_diagnostics
    .sort_values("outcome_value")
    .head(100)
)

print()
print("Year-by-year performance for top diagnostic models:")
display(year_summary.head(100))

print()
print("Loss diagnostics by layer / bucket for top diagnostic models:")
display(loss_by_bucket_layer)

print()
print("Loss diagnostics by year / layer / bucket for top diagnostic models:")
display(loss_by_year.head(100))

print()
print("Worst selected trades across top diagnostic models:")
display(worst_selected_trades.head(100))


# -----------------------------
# 8. Save outputs
# -----------------------------

safe_start = eligible["date"].min().strftime("%Y%m%d")
safe_end = eligible["date"].max().strftime("%Y%m%d")

core_diag_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell4_core_diag_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_vrp_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell4_core_by_vrp_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_z_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell4_core_by_z_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_rsi_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell4_core_by_rsi_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_rv21d_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell4_core_by_rv21d_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

near_target_models_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell4_near_target_models_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

year_summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell4_year_summary_top_models_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

loss_by_bucket_layer_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell4_loss_by_bucket_layer_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

loss_by_year_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell4_loss_by_year_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

worst_trades_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell4_worst_selected_trades_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_diag.to_csv(core_diag_path, index=False)
core_by_vrp.to_csv(core_by_vrp_path, index=False)
core_by_z.to_csv(core_by_z_path, index=False)
core_by_rsi.to_csv(core_by_rsi_path, index=False)
core_by_rv21d.to_csv(core_by_rv21d_path, index=False)

model_summary[near_target_cols].sort_values(
    [
        "near_target_score",
        "overall_win_rate",
        "core_win_rate",
        "overall_frequency",
        "overall_avg_pnl_per_day",
    ],
    ascending=[True, False, False, False, False],
).to_csv(near_target_models_path, index=False)

year_summary.to_csv(year_summary_path, index=False)
loss_by_bucket_layer.to_csv(loss_by_bucket_layer_path, index=False)
loss_by_year.to_csv(loss_by_year_path, index=False)
worst_selected_trades.to_csv(worst_trades_path, index=False)

print()
print("Cell 4 outputs saved:")
print(f"Core diagnostic:          {core_diag_path}")
print(f"Core by VRP:              {core_by_vrp_path}")
print(f"Core by z-score:          {core_by_z_path}")
print(f"Core by RSI:              {core_by_rsi_path}")
print(f"Core by RV21D:            {core_by_rv21d_path}")
print(f"Near-target models:       {near_target_models_path}")
print(f"Year summary top models:  {year_summary_path}")
print(f"Loss by bucket/layer:     {loss_by_bucket_layer_path}")
print(f"Loss by year:             {loss_by_year_path}")
print(f"Worst selected trades:    {worst_trades_path}")

print()
print("Cell 4 complete.")

Cell 4: Phase 1 diagnostic breakdown
Clean panel:             C:\Users\patri\vrp_project\data\processed\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_panel_20200102_20260623_20260704_085138.parquet
All specs:               C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell2_all_phase1_specs_20260704_085147.csv
Cell 3 model summary:    C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell3_full_model_summary_old_process_20200701_20260519_20260704_090941.csv
Cell 3 core summary:     C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell3_core_layer_summary_20200701_20260519_20260704_090941.csv
Cell 3 conditional stats:C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell3_conditional_stats_old_process_20200701_20260519_20260704_090941.csv
Run timestamp:           20260704_092202

Loaded input summary:

,clean_panel_rows,all_specs,core_specs,secondary_specs,full_models,core_layer_summary_rows,conditional_stats_rows
0,14565,384,192,192,36864,192,333504

Core specs closest to 85% win rate:

,spec_id,candidate_frequency,core_layer_trades,core_layer_frequency,core_layer_win_rate,core_win_gap_to_85,core_layer_avg_pnl_per_day,core_layer_exposure_day_weighted_pnl_per_day,core_layer_total_pnl,core_layer_profit_factor,core_layer_worst_trade_pnl,core_layer_worst_pnl_per_day,core_layer_avg_actual_dte,core_layer_avg_selected_tenor,vrp_triple,z_triple,rsi_triple,rv21d_triple
6,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,0.182679,270,0.182679,0.803704,0.046296,389.906415,429.522773,2.286350e+06,2.740716,-108475.796818,-6026.433157,19.714815,19.388889,0.70 / 0.80 / 0.90,0.50 / 0.75 / 0.75,70 / 68 / 66,8.5 / 8.5 / 8.5
54,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,0.140731,208,0.140731,0.802885,0.047115,384.433523,458.121069,1.853100e+06,2.807476,-108475.796818,-11224.939578,19.447115,19.514423,0.80 / 0.90 / 1.00,0.50 / 0.75 / 0.75,70 / 68 / 66,8.5 / 8.5 / 8.5
66,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,0.138701,205,0.138701,0.800000,0.050000,387.452421,457.677056,1.776245e+06,2.732514,-108475.796818,-11224.939578,18.931707,18.936585,0.80 / 0.90 / 1.00,0.50 / 0.75 / 1.00,70 / 68 / 66,8.5 / 8.5 / 8.5
2,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,0.185386,274,0.185386,0.795620,0.054380,380.769989,418.040672,2.284592e+06,2.719853,-108475.796818,-6026.433157,19.945255,19.653285,0.70 / 0.80 / 0.90,0.50 / 0.75 / 0.75,72 / 70 / 68,8.5 / 8.5 / 8.5
7,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,0.178620,264,0.178620,0.795455,0.054545,393.181871,430.875218,2.141881e+06,2.626253,-108475.796818,-6026.433157,18.829545,18.465909,0.70 / 0.80 / 0.90,0.50 / 0.75 / 0.75,70 / 68 / 66,8.5 / 9.0 / 10.0
55,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,0.138024,204,0.138024,0.794118,0.055882,387.748904,458.460242,1.732521e+06,2.683935,-108475.796818,-11224.939578,18.524510,18.352941,0.80 / 0.90 / 1.00,0.50 / 0.75 / 0.75,70 / 68 / 66,8.5 / 9.0 / 10.0
18,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,0.180650,267,0.180650,0.794007,0.055993,374.402595,406.281162,2.081785e+06,2.503133,-108475.796818,-6026.433157,19.191011,18.988764,0.70 / 0.80 / 0.90,0.50 / 0.75 / 1.00,70 / 68 / 66,8.5 / 8.5 / 8.5
67,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,0.137348,203,0.137348,0.793103,0.056897,389.794760,456.773298,1.689148e+06,2.641778,-108475.796818,-11224.939578,18.216749,18.029557,0.80 / 0.90 / 1.00,0.50 / 0.75 / 1.00,70 / 68 / 66,8.5 / 9.0 / 10.0
42,core_phase1_vrp_0.70_0.80_0.90_z_1.00_1.00_1.5...,0.110961,164,0.110961,0.792683,0.057317,427.586115,445.944468,1.386441e+06,2.766968,-108475.796818,-6026.433157,18.957317,18.841463,0.70 / 0.80 / 0.90,1.00 / 1.00 / 1.50,70 / 68 / 66,8.5 / 8.5 / 8.5
62,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,0.140054,207,0.140054,0.792271,0.057729,374.496844,444.544858,1.765732e+06,2.699869,-108475.796818,-11224.939578,19.188406,19.217391,0.80 / 0.90 / 1.00,0.50 / 0.75 / 1.00,72 / 70 / 68,8.5 / 8.5 / 8.5
10,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,0.175237,259,0.175237,0.791506,0.058494,394.020196,431.505365,2.166157e+06,2.669041,-108475.796818,-6026.433157,19.382239,18.938224,0.70 / 0.80 / 0.90,0.50 / 0.75 / 0.75,68 / 66 / 64,8.5 / 8.5 / 8.5
50,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,0.142760,211,0.142760,0.791469,0.058531,369.205667,440.299531,1.843094e+06,2.767840,-108475.796818,-11224.939578,19.838863,19.890995,0.80 / 0.90 / 1.00,0.50 / 0.75 / 0.75,72 / 70 / 68,8.5 / 8.5 / 8.5
30,core_phase1_vrp_0.70_0.80_0.90_z_0.75_1.00_1.2...,0.148173,219,0.148173,0.789954,0.060046,398.966076,420.990255,1.697433e+06,2.531063,-108475.796818,-6026.433157,18.410959,18.150685,0.70 / 0.80 / 0.90,0.75 / 1.00 / 1.25,70 / 68 / 66,8.5 / 8.5 / 8.5
150,core_phase1_vrp_0.90_1.00_1.20_z_0.50_0.75_0.7...,0.099459,147,0.099459,0.789116,0.060884,428.953822,512.733706,1.345413e+06,2.846564,-85507.285161,-7773.389560,17.850340,17.551020,0.90 / 1.00 / 1.20,0.50 / 0.75 / 0.75,70 / 68 / 66,8.5 / 8.5 / 8.5
58,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,0.134641,199,0.134641,0.788945,0.061055,384.428003,458.899525,1.752996e+06,2.709134,-108475.796818,-11224.939578,19.195980,19.251256,0.80 / 0.90 / 1.00,0.50 / 0.75 / 0.75,68 / 66 / 64,8.5 / 8.5 / 8.5
14,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,0.182679,270,0.182679,0.788889,0.061111,366.830041,397.260222,2.077671e+06,2.484287,-108475.796818,-6026.433157,19.370370,19.200000,0.70 / 0.80 / 0.90,0.50 / 0.75 / 1.00,72 / 70 / 68,8.5 / 8.5 / 8.5
11,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,0.172530,255,0.172530,0.788235,0.061765,398.956319,434.696243,2.066981e+06,2.592624,-108475.796818,-6026.433157,18.647059,18.105882,0.70 / 0.80 / 0.90,0.50 / 0.75 / 0.75,68 / 66 / 64,8.5 / 9.0 / 10.0
3,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,0.181326,268,0.181326,0.787313,0.062687,386.501484,422.496110,2.142478e+06,2.608495,-108475.796818,-6026.433157,18.921642,18.582090,0.70 / 0.80 / 0.90,0.50 / 0.75 / 0.75,72 / 70 / 68,8.5 / 9.0 / 10.0
19,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,0.177943,263,0.177943,0.787072,0.062928,376.626467,405.931438,1.970797e+06,2.419295,-108475.796818,-6026.433157,18.460076,18.216730,0.70 / 0.80 / 0.90,0.50 / 0.75 / 1.00,70 / 68 / 66,8.5 / 9.0 / 10.0
59,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,0.133288,197,0.133288,0.786802,0.063198,388.003322,460.724279,1.680722e+06,2.638668,-108475.796818,-11224.939578,18.517766,18.441624,0.80 / 0.90 / 1.00,0.50 / 0.75 / 0.75,68 / 66 / 64,8.5 / 9.0 / 10.0
70,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,0.133288,197,0.133288,0.786802,0.063198,387.696886,458.064929,1.688427e+06,2.646181,-108475.796818,-11224.939578,18.710660,18.715736,0.80 / 0.90 / 1.00,0.50 / 0.75 / 1.00,68 / 66 / 64,8.5 / 8.5 / 8.5
102,core_phase1_vrp_0.80_1.00_1.10_z_0.50_0.75_0.7...,0.139378,206,0.139378,0.786408,0.063592,378.187563,444.076782,1.595124e+06,2.458847,-108475.796818,-11224.939578,17.436893,16.849515,0.80 / 1.00 / 1.10,0.50 / 0.75 / 0.75,70 / 68 / 66,8.5 / 8.5 / 8.5
71,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,0.132612,196,0.132612,0.785714,0.064286,393.275415,459.349919,1.622424e+06,2.581829,-108475.796818,-11224.939578,18.020408,17.739796,0.80 / 0.90 / 1.00,0.50 / 0.75 / 1.00,68 / 66 / 64,8.5 / 9.0 / 10.0
63,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,0.138701,205,0.138701,0.785366,0.064634,379.538442,447.685133,1.677476e+06,2.609310,-108475.796818,-11224.939578,18.278049,18.102439,0.80 / 0.90 / 1.00,0.50 / 0.75 / 1.00,72 / 70 / 68,8.5 / 9.0 / 10.0
78,core_phase1_vrp_0.80_0.90_1.00_z_0.75_1.00_1.2...,0.119756,177,0.119756,0.785311,0.064689,390.762702,449.407915,1.436757e+06,2.585643,-108475.796818,-11224.939578,18.062147,17.932203,0.80 / 0.90 / 1.00,0.75 / 1.00 / 1.25,70 / 68 / 66,8.5 / 8.5 / 8.5
38,core_phase1_vrp_0.70_0.80_0.90_z_1.00_1.00_1.5...,0.112991,167,0.112991,0.784431,0.065569,415.044869,432.130249,1.385842e+06,2.733476,-108475.796818,-6026.433157,19.203593,19.131737,0.70 / 0.80 / 0.90,1.00 / 1.00 / 1.50,72 / 70 / 68,8.5 / 8.5 / 8.5
40,core_phase1_vrp_0.70_0.80_0.90_z_1.00_1.00_1.5...,0.119080,176,0.119080,0.784091,0.065909,413.395051,425.387151,1.436532e+06,2.765198,-108475.796818,-6026.433157,19.187500,19.125000,0.70 / 0.80 / 0.90,1.00 / 1.00 / 1.50,70 / 68 / 66,6.5 / 6.5 / 6.5
26,core_phase1_vrp_0.70_0.80_0.90_z_0.75_1.00_1.2...,0.149526,221,0.149526,0.782805,0.067195,386.722342,407.023980,1.685486e+06,2.500241,-108475.796818,-6026.433157,18.737557,18.488688,0.70 / 0.80 / 0.90,0.75 / 1.00 / 1.25,72 / 70 / 68,8.5 / 8.5 / 8.5
51,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,0.140054,207,0.140054,0.782609,0.067391,375.225360,444.365326,1.717028e+06,2.641236,-108475.796818,-11224.939578,18.666667,18.492754,0.80 / 0.90 / 1.00,0.50 / 0.75 / 0.75,72 / 70 / 68,8.5 / 9.0 / 10.0
22,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,0.173884,257,0.173884,0.782101,0.067899,377.212094,401.735334,1.979752e+06,2.431782,-108475.796818,-6026.433157,19.175097,18.922179,0.70 / 0.80 / 0.90,0.50 / 0.75 / 1.00,68 / 66 / 64,8.5 / 8.5 / 8.5
15,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,0.179973,266,0.179973,0.781955,0.068045,371.573331,400.221614,1.971492e+06,2.404808,-108475.796818,-6026.433157,18.518797,18.293233,0.70 / 0.80 / 0.90,0.50 / 0.75 / 1.00,72 / 70 / 68,8.5 / 9.0 / 10.0
4,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,0.197564,292,0.197564,0.780822,0.069178,402.028417,433.388894,2.370204e+06,2.916614,-108475.796818,-6026.433157,18.729452,18.688356,0.70 / 0.80 / 0.90,0.50 / 0.75 / 0.75,70 / 68 / 66,6.5 / 6.5 / 6.5
5,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,0.194181,287,0.194181,0.780488,0.069512,359.503767,384.884680,2.198846e+06,2.515983,-108475.796818,-6026.433157,19.905923,19.484321,0.70 / 0.80 / 0.90,0.50 / 0.75 / 0.75,70 / 68 / 66,7.5 / 7.5 / 7.5
41,core_phase1_vrp_0.70_0.80_0.90_z_1.00_1.00_1.5...,0.117050,173,0.117050,0.780347,0.069653,411.914243,423.876650,1.399641e+06,2.719866,-108475.796818,-6026.433157,19.086705,18.988439,0.70 / 0.80 / 0.90,1.00 / 1.00 / 1.50,70 / 68 / 66,7.5 / 7.5 / 7.5
31,core_phase1_vrp_0.70_0.80_0.90_z_0.75_1.00_1.2...,0.147497,218,0.147497,0.779817,0.070183,395.661791,411.947638,1.591354e+06,2.418849,-108475.796818,-6026.433157,17.720183,17.435780,0.70 / 0.80 / 0.90,0.75 / 1.00 / 1.25,70 / 68 / 66,8.5 / 9.0 / 10.0
23,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,0.171854,254,0.171854,0.779528,0.070472,384.603362,408.826885,1.890824e+06,2.380814,-108475.796818,-6026.433157,18.208661,17.728346,0.70 / 0.80 / 0.90,0.50 / 0.75 / 1.00,68 / 66 / 64,8.5 / 9.0 / 10.0
90,core_phase1_vrp_0.80_0.90_1.00_z_1.00_1.00_1.5...,0.094723,140,0.094723,0.778571,0.071429,381.669177,446.010281,1.099415e+06,2.522376,-108475.796818,-11224.939578,17.607143,17.571429,0.80 / 0.90 / 1.00,1.00 / 1.00 / 1.50,70 / 68 / 66,8.5 / 8.5 / 8.5
114,core_phase1_vrp_0.80_1.00_1.10_z_0.50_0.75_1.0...,0.137348,203,0.137348,0.778325,0.071675,383.025393,443.313189,1.494852e+06,2.362642,-108475.796818,-11224.939578,16.610837,16.123153,0.80 / 1.00 / 1.10,0.50 / 0.75 / 1.00,70 / 68 / 66,8.5 / 8.5 / 8.5
103,core_phase1_vrp_0.80_1.00_1.10_z_0.50_0.75_0.7...,0.137348,203,0.137348,0.778325,0.071675,378.242610,442.353647,1.523908e+06,2.389128,-108475.796818,-11224.939578,16.970443,16.389163,0.80 / 1.00 / 1.10,0.50 / 0.75 / 0.75,70 / 68 / 66,8.5 / 9.0 / 10.0
151,core_phase1_vrp_0.90_1.00_1.20_z_0.50_0.75_0.7...,0.097429,144,0.097429,0.777778,0.072222,440.387977,523.541729,1.260165e+06,2.721032,-85507.285161,-7773.389560,16.715278,16.479167,0.90 / 1.00 / 1.20,0.50 / 0.75 / 0.75,70 / 68 / 66,8.5 / 9.0 / 10.0
162,core_phase1_vrp_0.90_1.00_1.20_z_0.50_0.75_1.0...,0.097429,144,0.097429,0.777778,0.072222,435.288278,517.680310,1.255375e+06,2.714490,-85507.285161,-7773.389560,16.840278,16.687500,0.90 / 1.00 / 1.20,0.50 / 0.75 / 1.00,70 / 68 / 66,8.5 / 8.5 / 8.5
43,core_phase1_vrp_0.70_0.80_0.90_z_1.00_1.00_1.5...,0.109608,162,0.109608,0.777778,0.072222,423.854671,432.471136,1.261951e+06,2.597427,-108475.796818,-6026.433157,18.012346,17.851852,0.70 / 0.80 / 0.90,1.00 / 1.00 / 1.50,70 / 68 / 66,8.5 / 9.0 / 10.0
36,core_phase1_vrp_0.70_0.80_0.90_z_1.00_1.00_1.5...,0.121786,180,0.121786,0.777778,0.072222,405.409527,416.120852,1.458920e+06,2.760658,-108475.796818,-6026.433157,19.477778,19.466667,0.70 / 0.80 / 0.90,1.00 / 1.00 / 1.50,72 / 70 / 68,6.5 / 6.5 / 6.5
1,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,0.197564,292,0.197564,0.777397,0.072603,355.584877,374.224449,2.207924e+06,2.487609,-108475.796818,-6026.433157,20.205479,19.818493,0.70 / 0.80 / 0.90,0.50 / 0.75 / 0.75,72 / 70 / 68,7.5 / 7.5 / 7.5
27,core_phase1_vrp_0.70_0.80_0.90_z_0.75_1.00_1.2...,0.148850,220,0.148850,0.777273,0.072727,390.514682,408.545186,1.611711e+06,2.429978,-108475.796818,-6026.433157,17.931818,17.618182,0.70 / 0.80 / 0.90,0.75 / 1.00 / 1.25,72 / 70 / 68,8.5 / 9.0 / 10.0
115,core_phase1_vrp_0.80_1.00_1.10_z_0.50_0.75_1.0...,0.136671,202,0.136671,0.777228,0.072772,384.894061,444.300154,1.475965e+06,2.345425,-108475.796818,-11224.939578,16.445545,15.905941,0.80 / 1.00 / 1.10,0.50 / 0.75 / 1.00,70 / 68 / 66,8.5 / 9.0 / 10.0
146,core_phase1_vrp_0.90_1.00_1.20_z_0.50_0.75_0.7...,0.100135,148,0.100135,0.777027,0.072973,417.289842,496.789629,1.335371e+06,2.830000,-85507.285161,-7773.389560,18.162162,17.878378,0.90 / 1.00 / 1.20,0.50 / 0.75 / 0.75,72 / 70 / 68,8.5 / 8.5 / 8.5
91,core_phase1_vrp_0.80_0.90_1.00_z_1.00_1.00_1.5...,0.094046,139,0.094046,0.776978,0.073022,386.958426,456.227152,1.076696e+06,2.515772,-108475.796818,-11224.939578,16.978417,16.834532,0.80 / 0.90 / 1.00,1.00 / 1.00 / 1.50,70 / 68 / 66,8.5 / 9.0 / 10.0
88,core_phase1_vrp_0.80_0.90_1.00_z_1.00_1.00_1.5...,0.102842,152,0.102842,0.776316,0.073684,374.393515,435.548680,1.199501e+06,2.609265,-108475.796818,-11224.939578,18.118421,18.039474,0.80 / 0.90 / 1.00,1.00 / 1.00 / 1.50,70 / 68 / 66,6.5 / 6.5 / 6.5
163,core_phase1_vrp_0.90_1.00_1.20_z_0.50_0.75_1.0...,0.096752,143,0.096752,0.776224,0.073776,438.293410,520.626438,1.236488e+06,2.688695,-85507.285161,-7773.389560,16.608392,16.384615,0.90 / 1.00 / 1.20,0.50 / 0.75 / 1.00,70 / 68 / 66,8.5 / 9.0 / 10.0

Core win rate by VRP triple:

,vrp_triple,specs,max_core_win_rate,median_core_win_rate,min_core_win_gap_to_85,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_80_plus,specs_core_win_82_plus,specs_core_win_85_plus
0,0.70 / 0.80 / 0.90,48,0.803704,0.777335,0.046296,0.200947,0.166441,427.586115,390.177673,2.370204e+06,1,0,0
1,0.80 / 0.90 / 1.00,48,0.802885,0.768724,0.047115,0.158322,0.132273,394.060419,371.115970,1.859394e+06,2,0,0
3,0.90 / 1.00 / 1.20,48,0.789116,0.736023,0.060884,0.113667,0.092355,440.881021,382.960902,1.345413e+06,0,0,0
2,0.80 / 1.00 / 1.10,48,0.786408,0.750000,0.063592,0.156969,0.131258,387.629970,347.783625,1.595124e+06,0,0,0

Core win rate by z-score triple:

,z_triple,specs,max_core_win_rate,median_core_win_rate,min_core_win_gap_to_85,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_80_plus,specs_core_win_82_plus,specs_core_win_85_plus
0,0.50 / 0.75 / 0.75,48,0.803704,0.772992,0.046296,0.200947,0.142422,440.881021,371.662549,2.370204e+06,2,0,0
1,0.50 / 0.75 / 1.00,48,0.800000,0.766667,0.050000,0.197564,0.140392,438.682271,374.930436,2.185858e+06,1,0,0
3,1.00 / 1.00 / 1.50,48,0.792683,0.754715,0.057317,0.121786,0.094723,427.586115,374.022198,1.458920e+06,0,0,0
2,0.75 / 1.00 / 1.25,48,0.789954,0.754663,0.060046,0.161028,0.120433,405.210167,368.531029,1.697433e+06,0,0,0

Core win rate by RSI cap triple:

,rsi_triple,specs,max_core_win_rate,median_core_win_rate,min_core_win_gap_to_85,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_80_plus,specs_core_win_82_plus,specs_core_win_85_plus
1,70 / 68 / 66,64,0.803704,0.771187,0.046296,0.197564,0.123139,440.387977,378.182355,2.370204e+06,3,0,0
2,72 / 70 / 68,64,0.795620,0.765237,0.054380,0.200947,0.124831,433.055797,366.601830,2.363238e+06,0,0,0
0,68 / 66 / 64,64,0.791506,0.756973,0.058494,0.186739,0.118065,440.881021,374.310840,2.298072e+06,0,0,0

Core win rate by RV21D floor triple:

,rv21d_triple,specs,max_core_win_rate,median_core_win_rate,min_core_win_gap_to_85,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_80_plus,specs_core_win_82_plus,specs_core_win_85_plus
2,8.5 / 8.5 / 8.5,48,0.803704,0.775445,0.046296,0.185386,0.118742,436.518595,383.726698,2.286350e+06,3,0,0
3,8.5 / 9.0 / 10.0,48,0.795455,0.769419,0.054545,0.181326,0.118742,440.881021,387.501380,2.142478e+06,0,0,0
0,6.5 / 6.5 / 6.5,48,0.784091,0.751116,0.065909,0.200947,0.129905,423.374099,356.676759,2.370204e+06,0,0,0
1,7.5 / 7.5 / 7.5,48,0.780488,0.751190,0.069512,0.197564,0.127199,419.896419,357.012248,2.296404e+06,0,0,0

Top Core specs: conditional tenor stats:

,spec_id,tenor,tenor_bucket,conditional_obs,conditional_sample_ok,conditional_win_probability,conditional_avg_pnl_per_day,conditional_aggregate_pnl_per_day,conditional_total_pnl,conditional_worst_trade_pnl,conditional_worst_pnl_per_day,conditional_avg_actual_dte
97,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,30,back,55,True,0.945455,559.530782,564.241955,9.394629e+05,-85194.299611,-2839.809987,30.272727
98,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,33,back,55,True,0.945455,504.362489,503.250574,8.877340e+05,-85194.299611,-2839.809987,32.072727
96,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,27,back,59,True,0.915254,556.217160,550.192721,8.770072e+05,-85194.299611,-2839.809987,27.016949
94,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,21,middle,103,True,0.864078,555.062339,551.837904,1.244394e+06,-49418.522467,-2353.262975,21.893204
95,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,24,middle,85,True,0.858824,482.286807,489.249725,9.643112e+05,-49418.522467,-2353.262975,23.188235
...,...,...,...,...,...,...,...,...,...,...,...,...
1354,core_phase1_vrp_0.90_1.00_1.20_z_0.50_0.75_0.7...,21,middle,47,True,0.893617,690.075210,686.912392,6.979030e+05,-36678.482468,-1528.270103,21.617021
1353,core_phase1_vrp_0.90_1.00_1.20_z_0.50_0.75_0.7...,18,middle,51,True,0.843137,692.363005,675.893012,6.083037e+05,-42977.344179,-2528.079069,17.647059
1352,core_phase1_vrp_0.90_1.00_1.20_z_0.50_0.75_0.7...,15,front,94,True,0.808511,672.183469,675.812017,1.017097e+06,-43456.123262,-2716.007704,16.010638
1351,core_phase1_vrp_0.90_1.00_1.20_z_0.50_0.75_0.7...,12,front,102,True,0.754902,653.896072,646.904065,7.562309e+05,-85507.285161,-7773.389560,11.460784
1350,core_phase1_vrp_0.90_1.00_1.20_z_0.50_0.75_0.7...,9,front,115,True,0.704348,576.218513,575.337293,6.104329e+05,-85507.285161,-7773.389560,9.226087

Top Core specs: conditional stats by bucket:

,tenor_bucket,rows,median_conditional_obs,max_conditional_obs,median_win_probability,max_win_probability,median_avg_pnl_per_day,max_avg_pnl_per_day,worst_trade_pnl
0,back,75,33.0,70,0.940299,1.000000,576.620624,740.236998,-85194.299611
2,middle,75,76.0,118,0.843137,0.906977,527.472712,692.363005,-108475.796818
1,front,75,164.0,233,0.750000,0.808511,448.483472,672.183469,-108475.796818

Top models closest to all targets:

,review_rank,near_target_score,meets_all_targets,overall_trades,overall_frequency,frequency_gap_to_33,overall_win_rate,overall_win_gap_to_80,core_win_rate,core_win_gap_to_85,...,front_selected_win_rate,front_selected_avg_pnl_per_day,middle_selected_trades,middle_selected_win_rate,middle_selected_avg_pnl_per_day,back_selected_trades,back_selected_win_rate,back_selected_avg_pnl_per_day,core_spec_id,secondary_spec_id
5009,5010,0.081140,False,485,0.328146,0.001854,0.767010,0.032990,0.803704,0.046296,...,0.696296,38.509841,127,0.803150,357.464496,88,0.931818,487.712193,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
6378,6379,0.081709,False,497,0.336265,-0.006265,0.764588,0.035412,0.803704,0.046296,...,0.693431,37.936715,134,0.798507,348.034425,89,0.932584,486.407080,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
7492,7493,0.085264,False,485,0.328146,0.001854,0.762887,0.037113,0.803704,0.046296,...,0.694245,44.381783,134,0.798507,348.034425,73,0.958904,546.902393,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
9119,9120,0.085560,False,489,0.330853,-0.000853,0.760736,0.039264,0.803704,0.046296,...,0.688406,-51.153631,124,0.798387,374.563574,89,0.932584,486.407080,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10942,10943,0.088564,False,497,0.336265,-0.006265,0.758551,0.041449,0.802885,0.047115,...,0.702899,-52.744316,156,0.782051,292.127626,65,0.938462,509.382106,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
5618,5619,0.089770,False,474,0.320704,0.009296,0.765823,0.034177,0.803704,0.046296,...,0.697080,45.040631,127,0.803150,357.464496,73,0.958904,546.902393,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
6379,6380,0.089792,False,497,0.336265,-0.006265,0.764588,0.035412,0.795620,0.054380,...,0.686347,30.487906,88,0.840909,433.096071,138,0.869565,380.465310,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
8226,8227,0.090206,False,479,0.324087,0.005913,0.762004,0.037996,0.803704,0.046296,...,0.692308,-7.667635,70,0.871429,529.817016,84,0.940476,500.516709,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10806,10807,0.090206,False,485,0.328146,0.001854,0.758763,0.041237,0.802885,0.047115,...,0.704380,-52.245548,149,0.785235,297.538844,62,0.935484,516.402376,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10807,10808,0.090206,False,485,0.328146,0.001854,0.758763,0.041237,0.802885,0.047115,...,0.707143,-42.215442,113,0.787611,322.730639,92,0.880435,397.380569,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
8227,8228,0.091025,False,479,0.324087,0.005913,0.762004,0.037996,0.802885,0.047115,...,0.720798,34.179737,68,0.808824,443.355215,60,0.950000,531.050173,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10943,10944,0.091449,False,497,0.336265,-0.006265,0.758551,0.041449,0.800000,0.050000,...,0.703971,-49.739190,165,0.793939,320.065136,55,0.927273,475.760663,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
12600,12601,0.091449,False,485,0.328146,0.001854,0.756701,0.043299,0.803704,0.046296,...,0.685714,-27.497576,66,0.818182,457.524363,104,0.932692,481.337467,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
6177,6178,0.091451,False,485,0.328146,0.001854,0.764948,0.035052,0.795455,0.054545,...,0.706093,58.178246,140,0.814286,368.021728,66,0.909091,487.416928,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
7792,7793,0.091970,False,497,0.336265,-0.006265,0.762575,0.037425,0.795455,0.054545,...,0.703180,57.345348,147,0.809524,358.922883,67,0.910448,485.687677,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
14584,14585,0.092514,False,489,0.330853,-0.000853,0.754601,0.045399,0.802885,0.047115,...,0.707143,-36.528106,146,0.767123,267.806122,63,0.936508,514.103244,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
8953,8954,0.092557,False,477,0.322733,0.007267,0.761006,0.038994,0.803704,0.046296,...,0.695971,41.726051,119,0.789916,348.427606,85,0.929412,494.905424,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
8954,8955,0.092557,False,477,0.322733,0.007267,0.761006,0.038994,0.803704,0.046296,...,0.692857,-40.647480,124,0.798387,374.563574,73,0.958904,546.902393,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10808,10809,0.093091,False,485,0.328146,0.001854,0.758763,0.041237,0.800000,0.050000,...,0.703297,-54.292185,158,0.797468,326.405859,54,0.925926,477.690359,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10809,10810,0.093091,False,485,0.328146,0.001854,0.758763,0.041237,0.800000,0.050000,...,0.708185,-39.290562,121,0.801653,357.564319,83,0.867470,361.753643,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
7493,7494,0.093347,False,485,0.328146,0.001854,0.762887,0.037113,0.795620,0.054380,...,0.689139,30.955878,125,0.800000,364.704762,93,0.924731,477.548866,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
9120,9121,0.093643,False,489,0.330853,-0.000853,0.760736,0.039264,0.795620,0.054380,...,0.681319,-59.526885,86,0.860465,486.707331,130,0.861538,378.949248,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
8228,8229,0.093909,False,479,0.324087,0.005913,0.762004,0.037996,0.800000,0.050000,...,0.722380,39.549694,77,0.831169,485.545357,49,0.938776,493.471408,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
7495,7496,0.094960,False,485,0.328146,0.001854,0.762887,0.037113,0.794007,0.055993,...,0.697417,41.244770,140,0.807143,362.077884,74,0.918919,447.929530,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
14585,14586,0.095399,False,489,0.330853,-0.000853,0.754601,0.045399,0.800000,0.050000,...,0.709220,-29.304665,155,0.780645,298.958269,52,0.923077,475.107559,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
9213,9214,0.095429,False,497,0.336265,-0.006265,0.760563,0.039437,0.794007,0.055993,...,0.694545,40.633947,147,0.802721,353.262079,75,0.920000,446.911231,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
7238,7239,0.095649,False,469,0.317321,0.012679,0.763326,0.036674,0.803704,0.046296,...,0.690852,47.647563,69,0.884058,548.881488,83,0.939759,502.070440,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
12445,12446,0.096749,False,477,0.322733,0.007267,0.756813,0.043187,0.803704,0.046296,...,0.693009,-10.026397,75,0.840000,472.095085,73,0.958904,546.902393,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10108,10109,0.096918,False,474,0.320704,0.009296,0.759494,0.040506,0.802885,0.047115,...,0.706522,-46.609908,149,0.785235,297.538844,49,0.979592,607.009825,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10810,10811,0.097471,False,485,0.328146,0.001854,0.758763,0.041237,0.795620,0.054380,...,0.687273,37.111630,100,0.800000,367.415692,110,0.900000,427.704412,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10811,10812,0.097636,False,485,0.328146,0.001854,0.758763,0.041237,0.795455,0.054545,...,0.703833,63.317802,105,0.809524,385.586879,93,0.870968,401.282576,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
8794,8795,0.097782,False,469,0.317321,0.012679,0.761194,0.038806,0.803704,0.046296,...,0.691176,36.532972,118,0.796610,366.251890,79,0.949367,532.579641,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
8795,8796,0.097782,False,469,0.317321,0.012679,0.761194,0.038806,0.803704,0.046296,...,0.693252,-4.730246,70,0.871429,529.817016,73,0.958904,546.902393,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
8796,8797,0.098601,False,469,0.317321,0.012679,0.761194,0.038806,0.802885,0.047115,...,0.721591,36.781275,68,0.808824,443.355215,49,0.979592,607.009825,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
8320,8321,0.099203,False,466,0.315291,0.014709,0.761803,0.038197,0.803704,0.046296,...,0.697080,45.040631,119,0.789916,348.427606,73,0.958904,546.902393,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
12910,12911,0.099343,False,497,0.336265,-0.006265,0.756539,0.043461,0.794118,0.055882,...,0.713311,-6.757695,153,0.784314,268.178188,51,0.921569,511.789937,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
12747,12748,0.099346,False,489,0.330853,-0.000853,0.756646,0.043354,0.794007,0.055993,...,0.689531,-48.154247,137,0.802920,377.655444,75,0.920000,446.911231,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
12386,12387,0.099398,False,473,0.320027,0.009973,0.756871,0.043129,0.803704,0.046296,...,0.688172,24.557298,99,0.777778,377.818167,95,0.936842,487.918522,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
9059,9060,0.099523,False,485,0.328146,0.001854,0.760825,0.039175,0.791506,0.058494,...,0.684211,23.439786,138,0.811594,370.653643,81,0.925926,492.298947,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
14442,14443,0.099665,False,477,0.322733,0.007267,0.754717,0.045283,0.802885,0.047115,...,0.709220,-31.123844,146,0.767123,267.806122,49,0.979592,607.009825,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
14443,14444,0.099665,False,477,0.322733,0.007267,0.754717,0.045283,0.802885,0.047115,...,0.707581,-38.883958,139,0.769784,272.381813,61,0.934426,522.730619,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10109,10110,0.099803,False,474,0.320704,0.009296,0.759494,0.040506,0.800000,0.050000,...,0.707581,-43.626928,158,0.797468,326.405859,39,0.974359,584.627719,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10944,10945,0.099943,False,497,0.336265,-0.006265,0.758551,0.041449,0.791506,0.058494,...,0.681481,23.081429,145,0.806897,361.302239,82,0.926829,490.826486,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
14586,14587,0.099944,False,489,0.330853,-0.000853,0.754601,0.045399,0.795455,0.054545,...,0.696113,-36.246889,139,0.798561,351.270200,67,0.910448,485.687677,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
7793,7794,0.100111,False,497,0.336265,-0.006265,0.762575,0.037425,0.787313,0.062687,...,0.699647,53.832001,95,0.842105,444.989391,119,0.848739,360.609349,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
7012,7013,0.100129,False,474,0.320704,0.009296,0.763713,0.036287,0.795455,0.054545,...,0.706714,64.223344,140,0.814286,368.021728,51,0.941176,572.053313,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
12911,12912,0.100357,False,497,0.336265,-0.006265,0.756539,0.043461,0.793103,0.056897,...,0.713311,-6.757695,159,0.792453,293.533971,45,0.911111,471.735975,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
9715,9716,0.100376,False,479,0.324087,0.005913,0.759916,0.040084,0.795620,0.054380,...,0.686520,-15.191826,66,0.863636,525.313660,94,0.936170,482.742100,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10512,10513,0.100733,False,469,0.317321,0.012679,0.759062,0.040938,0.802885,0.047115,...,0.714286,18.116146,67,0.820896,461.698302,59,0.949153,533.753445,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
8955,8956,0.100806,False,477,0.322733,0.007267,0.761006,0.038994,0.795455,0.054545,...,0.706093,58.178246,132,0.803030,360.514666,66,0.909091,487.416928,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...

Highest-frequency models with overall win rate >= 79%:

,review_rank,near_target_score,meets_all_targets,overall_trades,overall_frequency,frequency_gap_to_33,overall_win_rate,overall_win_gap_to_80,core_win_rate,core_win_gap_to_85,...,front_selected_win_rate,front_selected_avg_pnl_per_day,middle_selected_trades,middle_selected_win_rate,middle_selected_avg_pnl_per_day,back_selected_trades,back_selected_win_rate,back_selected_avg_pnl_per_day,core_spec_id,secondary_spec_id
53,54,0.165379,False,336,0.227334,0.102666,0.791667,0.008333,0.795620,0.054380,...,0.695402,141.697954,84,0.845238,442.257103,78,0.948718,537.663392,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
27,28,0.156902,False,334,0.225981,0.104019,0.793413,0.006587,0.803704,0.046296,...,0.708543,160.828232,62,0.870968,539.445851,73,0.958904,554.032508,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
70,71,0.187864,False,334,0.225981,0.104019,0.790419,0.009581,0.775735,0.074265,...,0.698225,240.019325,92,0.869565,483.199827,73,0.904110,495.650369,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
15,16,0.169981,False,331,0.223951,0.106049,0.794562,0.005438,0.791506,0.058494,...,0.701087,154.184205,61,0.885246,582.995690,86,0.930233,495.168758,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
29,30,0.168634,False,329,0.222598,0.107402,0.793313,0.006687,0.795455,0.054545,...,0.722826,218.408621,94,0.851064,442.764492,51,0.941176,582.259163,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
76,77,0.163425,False,329,0.222598,0.107402,0.790274,0.009726,0.803704,0.046296,...,0.701031,177.508534,62,0.870968,539.445851,73,0.958904,554.032508,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
46,47,0.163002,False,327,0.221245,0.108755,0.792049,0.007951,0.803704,0.046296,...,0.703125,152.103911,62,0.870968,539.445851,73,0.958904,554.032508,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
5,6,0.167565,False,325,0.219892,0.110108,0.796923,0.003077,0.795620,0.054380,...,0.702381,194.625301,80,0.850000,471.015723,77,0.948052,536.965902,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
0,1,0.157758,False,323,0.218539,0.111461,0.801858,-0.001858,0.803704,0.046296,...,0.709302,195.232541,79,0.860759,483.217635,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
36,37,0.193156,False,323,0.218539,0.111461,0.792570,0.007430,0.775735,0.074265,...,0.703030,280.732498,86,0.872093,499.668557,72,0.902778,494.320928,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
35,36,0.165188,False,323,0.218539,0.111461,0.792570,0.007430,0.803704,0.046296,...,0.703704,149.088554,61,0.868852,539.150108,73,0.958904,554.032508,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
58,59,0.182648,False,321,0.217185,0.112815,0.791277,0.008723,0.788889,0.061111,...,0.704142,198.087138,92,0.847826,462.320008,60,0.950000,507.127503,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
2,3,0.159788,False,320,0.216509,0.113491,0.800000,0.000000,0.803704,0.046296,...,0.709302,195.232541,76,0.855263,483.800912,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
22,23,0.178235,False,320,0.216509,0.113491,0.793750,0.006250,0.791506,0.058494,...,0.698795,193.919066,69,0.855072,515.127249,85,0.929412,492.498103,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
21,22,0.175734,False,320,0.216509,0.113491,0.793750,0.006250,0.794007,0.055993,...,0.710983,198.610825,90,0.855556,473.300857,57,0.947368,514.757967,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
67,68,0.197131,False,320,0.216509,0.113491,0.790625,0.009375,0.775735,0.074265,...,0.702381,274.574711,80,0.875000,525.450153,72,0.902778,494.320928,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
66,67,0.185553,False,320,0.216509,0.113491,0.790625,0.009375,0.787313,0.062687,...,0.722222,220.384913,88,0.852273,482.194251,52,0.923077,566.615838,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
65,66,0.177246,False,320,0.216509,0.113491,0.790625,0.009375,0.795620,0.054380,...,0.700000,196.166503,62,0.870968,526.423971,78,0.935897,527.961952,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
9,10,0.173792,False,318,0.215156,0.114844,0.795597,0.004403,0.795455,0.054545,...,0.723757,217.757296,87,0.862069,485.113281,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
7,8,0.165543,False,318,0.215156,0.114844,0.795597,0.004403,0.803704,0.046296,...,0.708108,198.523504,60,0.883333,549.049589,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
8,9,0.173626,False,318,0.215156,0.114844,0.795597,0.004403,0.795620,0.054380,...,0.697531,187.574915,79,0.848101,470.473435,77,0.948052,536.965902,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
37,38,0.168688,False,318,0.215156,0.114844,0.792453,0.007547,0.803704,0.046296,...,0.702703,148.277298,59,0.881356,548.906596,74,0.945946,544.311228,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
12,13,0.179063,False,317,0.214479,0.115521,0.794953,0.005047,0.791506,0.058494,...,0.701754,195.430551,81,0.864198,498.543137,65,0.953846,566.316071,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
11,12,0.166865,False,317,0.214479,0.115521,0.794953,0.005047,0.803704,0.046296,...,0.708108,198.523504,60,0.866667,537.002450,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
52,53,0.185488,False,317,0.214479,0.115521,0.791798,0.008202,0.788235,0.061765,...,0.712644,215.514823,74,0.864865,516.262688,69,0.913043,495.675175,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
51,52,0.179715,False,317,0.214479,0.115521,0.791798,0.008202,0.794007,0.055993,...,0.710983,198.610825,87,0.850575,473.468429,57,0.947368,514.757967,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
1,2,0.162494,False,316,0.213802,0.116198,0.800633,-0.000633,0.803704,0.046296,...,0.704819,188.373993,78,0.858974,482.824830,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
61,62,0.199323,False,316,0.213802,0.116198,0.791139,0.008861,0.775735,0.074265,...,0.698113,276.798414,85,0.870588,499.501641,72,0.902778,494.320928,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
24,25,0.177769,False,315,0.213126,0.116874,0.793651,0.006349,0.795455,0.054545,...,0.723757,217.757296,84,0.857143,485.708710,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
23,24,0.169520,False,315,0.213126,0.116874,0.793651,0.006349,0.803704,0.046296,...,0.708108,198.523504,57,0.877193,553.292131,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
30,31,0.170853,False,314,0.212449,0.117551,0.792994,0.007006,0.803704,0.046296,...,0.708108,198.523504,57,0.859649,540.610933,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
31,32,0.171672,False,314,0.212449,0.117551,0.792994,0.007006,0.802885,0.047115,...,0.717647,143.365588,76,0.828947,410.536465,68,0.941176,514.796044,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
41,42,0.184389,False,313,0.211773,0.118227,0.792332,0.007668,0.791506,0.058494,...,0.693750,186.754067,88,0.852273,468.674108,65,0.953846,566.316071,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
38,39,0.172191,False,313,0.211773,0.118227,0.792332,0.007668,0.803704,0.046296,...,0.704918,190.613496,57,0.877193,553.292131,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
39,40,0.172191,False,313,0.211773,0.118227,0.792332,0.007668,0.803704,0.046296,...,0.700000,183.533761,61,0.868852,537.338248,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
40,41,0.181888,False,313,0.211773,0.118227,0.792332,0.007668,0.794007,0.055993,...,0.706587,191.914721,89,0.853933,472.845176,57,0.947368,514.757967,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
13,14,0.170328,False,312,0.211096,0.118904,0.794872,0.005128,0.803704,0.046296,...,0.705556,195.500232,59,0.881356,548.906596,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
18,19,0.179914,False,311,0.210419,0.119581,0.794212,0.005788,0.795455,0.054545,...,0.724138,220.423260,87,0.850575,463.311710,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
17,18,0.171665,False,311,0.210419,0.119581,0.794212,0.005788,0.803704,0.046296,...,0.702247,189.043357,61,0.868852,537.338248,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
63,64,0.178584,False,311,0.210419,0.119581,0.790997,0.009003,0.800000,0.050000,...,0.719298,147.086699,83,0.843373,452.645549,57,0.929825,479.354730,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
26,27,0.185203,False,310,0.209743,0.120257,0.793548,0.006452,0.791506,0.058494,...,0.696970,188.537636,80,0.862500,498.351720,65,0.953846,566.316071,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
25,26,0.173005,False,310,0.209743,0.120257,0.793548,0.006452,0.803704,0.046296,...,0.702247,189.043357,60,0.866667,537.002450,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
75,76,0.191699,False,310,0.209743,0.120257,0.790323,0.009677,0.788235,0.061765,...,0.708333,209.462291,94,0.861702,473.332750,48,0.937500,594.260462,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
74,75,0.176231,False,310,0.209743,0.120257,0.790323,0.009677,0.803704,0.046296,...,0.700000,183.533761,57,0.877193,553.292131,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
33,34,0.174350,False,309,0.209066,0.120934,0.792880,0.007120,0.803704,0.046296,...,0.705556,195.500232,56,0.875000,553.217238,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
44,45,0.183948,False,308,0.208390,0.121610,0.792208,0.007792,0.795455,0.054545,...,0.720000,212.023750,83,0.855422,485.369580,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
42,43,0.175699,False,308,0.208390,0.121610,0.792208,0.007792,0.803704,0.046296,...,0.702247,189.043357,57,0.877193,553.292131,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
43,44,0.175699,False,308,0.208390,0.121610,0.792208,0.007792,0.803704,0.046296,...,0.697143,181.734428,61,0.868852,537.338248,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
14,15,0.173795,False,307,0.207713,0.122287,0.794788,0.005212,0.803704,0.046296,...,0.702857,160.845011,60,0.866667,537.002450,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
57,58,0.200268,False,307,0.207713,0.122287,0.791531,0.008469,0.780488,0.069512,...,0.701987,246.462753,74,0.864865,508.818485,82,0.890244,454.305998,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.50_0.7...

Highest overall win-rate models:

,review_rank,near_target_score,meets_all_targets,overall_trades,overall_frequency,frequency_gap_to_33,overall_win_rate,overall_win_gap_to_80,core_win_rate,core_win_gap_to_85,...,front_selected_win_rate,front_selected_avg_pnl_per_day,middle_selected_trades,middle_selected_win_rate,middle_selected_avg_pnl_per_day,back_selected_trades,back_selected_win_rate,back_selected_avg_pnl_per_day,core_spec_id,secondary_spec_id
0,1,0.157758,False,323,0.218539,0.111461,0.801858,-0.001858,0.803704,0.046296,...,0.709302,195.232541,79,0.860759,483.217635,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
1,2,0.162494,False,316,0.213802,0.116198,0.800633,-0.000633,0.803704,0.046296,...,0.704819,188.373993,78,0.858974,482.824830,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
2,3,0.159788,False,320,0.216509,0.113491,0.800000,0.000000,0.803704,0.046296,...,0.709302,195.232541,76,0.855263,483.800912,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
3,4,0.178059,False,294,0.198917,0.131083,0.799320,0.000680,0.803704,0.046296,...,0.700637,230.379844,57,0.877193,553.292131,80,0.937500,515.459368,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
4,5,0.172610,False,303,0.205007,0.124993,0.798680,0.001320,0.803704,0.046296,...,0.696774,231.530282,76,0.855263,483.800912,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
5,6,0.167565,False,325,0.219892,0.110108,0.796923,0.003077,0.795620,0.054380,...,0.702381,194.625301,80,0.850000,471.015723,77,0.948052,536.965902,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
6,7,0.184914,False,289,0.195535,0.134465,0.795848,0.004152,0.803704,0.046296,...,0.694805,224.468708,57,0.877193,553.292131,78,0.935897,516.541718,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
9,10,0.173792,False,318,0.215156,0.114844,0.795597,0.004403,0.795455,0.054545,...,0.723757,217.757296,87,0.862069,485.113281,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
7,8,0.165543,False,318,0.215156,0.114844,0.795597,0.004403,0.803704,0.046296,...,0.708108,198.523504,60,0.883333,549.049589,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
8,9,0.173626,False,318,0.215156,0.114844,0.795597,0.004403,0.795620,0.054380,...,0.697531,187.574915,79,0.848101,470.473435,77,0.948052,536.965902,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
10,11,0.187454,False,298,0.201624,0.128376,0.795302,0.004698,0.795620,0.054380,...,0.688742,223.834237,60,0.866667,527.181494,87,0.931034,500.545106,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
12,13,0.179063,False,317,0.214479,0.115521,0.794953,0.005047,0.791506,0.058494,...,0.701754,195.430551,81,0.864198,498.543137,65,0.953846,566.316071,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
11,12,0.166865,False,317,0.214479,0.115521,0.794953,0.005047,0.803704,0.046296,...,0.708108,198.523504,60,0.866667,537.002450,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
13,14,0.170328,False,312,0.211096,0.118904,0.794872,0.005128,0.803704,0.046296,...,0.705556,195.500232,59,0.881356,548.906596,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
14,15,0.173795,False,307,0.207713,0.122287,0.794788,0.005212,0.803704,0.046296,...,0.702857,160.845011,60,0.866667,537.002450,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
15,16,0.169981,False,331,0.223951,0.106049,0.794562,0.005438,0.791506,0.058494,...,0.701087,154.184205,61,0.885246,582.995690,86,0.930233,495.168758,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
16,17,0.187690,False,287,0.194181,0.135819,0.794425,0.005575,0.803704,0.046296,...,0.692308,223.427217,59,0.864407,540.351865,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
18,19,0.179914,False,311,0.210419,0.119581,0.794212,0.005788,0.795455,0.054545,...,0.724138,220.423260,87,0.850575,463.311710,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
17,18,0.171665,False,311,0.210419,0.119581,0.794212,0.005788,0.803704,0.046296,...,0.702247,189.043357,61,0.868852,537.338248,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
19,20,0.182107,False,296,0.200271,0.129729,0.793919,0.006081,0.803704,0.046296,...,0.695122,229.161081,58,0.879310,550.613427,74,0.945946,539.686766,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
20,21,0.185594,False,291,0.196888,0.133112,0.793814,0.006186,0.803704,0.046296,...,0.691275,223.600433,70,0.842857,482.861562,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
22,23,0.178235,False,320,0.216509,0.113491,0.793750,0.006250,0.791506,0.058494,...,0.698795,193.919066,69,0.855072,515.127249,85,0.929412,492.498103,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
21,22,0.175734,False,320,0.216509,0.113491,0.793750,0.006250,0.794007,0.055993,...,0.710983,198.610825,90,0.855556,473.300857,57,0.947368,514.757967,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
24,25,0.177769,False,315,0.213126,0.116874,0.793651,0.006349,0.795455,0.054545,...,0.723757,217.757296,84,0.857143,485.708710,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
23,24,0.169520,False,315,0.213126,0.116874,0.793651,0.006349,0.803704,0.046296,...,0.708108,198.523504,57,0.877193,553.292131,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
26,27,0.185203,False,310,0.209743,0.120257,0.793548,0.006452,0.791506,0.058494,...,0.696970,188.537636,80,0.862500,498.351720,65,0.953846,566.316071,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
25,26,0.173005,False,310,0.209743,0.120257,0.793548,0.006452,0.803704,0.046296,...,0.702247,189.043357,60,0.866667,537.002450,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
27,28,0.156902,False,334,0.225981,0.104019,0.793413,0.006587,0.803704,0.046296,...,0.708543,160.828232,62,0.870968,539.445851,73,0.958904,554.032508,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
28,29,0.192184,False,300,0.202977,0.127023,0.793333,0.006667,0.791506,0.058494,...,0.688312,230.697375,81,0.864198,498.543137,65,0.953846,566.316071,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
29,30,0.168634,False,329,0.222598,0.107402,0.793313,0.006687,0.795455,0.054545,...,0.722826,218.408621,94,0.851064,442.764492,51,0.941176,582.259163,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
30,31,0.170853,False,314,0.212449,0.117551,0.792994,0.007006,0.803704,0.046296,...,0.708108,198.523504,57,0.859649,540.610933,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
31,32,0.171672,False,314,0.212449,0.117551,0.792994,0.007006,0.802885,0.047115,...,0.717647,143.365588,76,0.828947,410.536465,68,0.941176,514.796044,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
32,33,0.190486,False,285,0.192828,0.137172,0.792982,0.007018,0.803704,0.046296,...,0.690323,221.080805,58,0.862069,542.807462,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
33,34,0.174350,False,309,0.209066,0.120934,0.792880,0.007120,0.803704,0.046296,...,0.705556,195.500232,56,0.875000,553.217238,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
34,35,0.177850,False,304,0.205683,0.124317,0.792763,0.007237,0.803704,0.046296,...,0.702857,160.845011,56,0.875000,553.217238,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
36,37,0.193156,False,323,0.218539,0.111461,0.792570,0.007430,0.775735,0.074265,...,0.703030,280.732498,86,0.872093,499.668557,72,0.902778,494.320928,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
35,36,0.165188,False,323,0.218539,0.111461,0.792570,0.007430,0.803704,0.046296,...,0.703704,149.088554,61,0.868852,539.150108,73,0.958904,554.032508,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
37,38,0.168688,False,318,0.215156,0.114844,0.792453,0.007547,0.803704,0.046296,...,0.702703,148.277298,59,0.881356,548.906596,74,0.945946,544.311228,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
41,42,0.184389,False,313,0.211773,0.118227,0.792332,0.007668,0.791506,0.058494,...,0.693750,186.754067,88,0.852273,468.674108,65,0.953846,566.316071,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
38,39,0.172191,False,313,0.211773,0.118227,0.792332,0.007668,0.803704,0.046296,...,0.704918,190.613496,57,0.877193,553.292131,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
39,40,0.172191,False,313,0.211773,0.118227,0.792332,0.007668,0.803704,0.046296,...,0.700000,183.533761,61,0.868852,537.338248,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
40,41,0.181888,False,313,0.211773,0.118227,0.792332,0.007668,0.794007,0.055993,...,0.706587,191.914721,89,0.853933,472.845176,57,0.947368,514.757967,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_1.0...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
44,45,0.183948,False,308,0.208390,0.121610,0.792208,0.007792,0.795455,0.054545,...,0.720000,212.023750,83,0.855422,485.369580,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
42,43,0.175699,False,308,0.208390,0.121610,0.792208,0.007792,0.803704,0.046296,...,0.702247,189.043357,57,0.877193,553.292131,73,0.945205,543.666586,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
43,44,0.175699,False,308,0.208390,0.121610,0.792208,0.007792,0.803704,0.046296,...,0.697143,181.734428,61,0.868852,537.338248,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
45,46,0.180029,False,303,0.205007,0.124993,0.792079,0.007921,0.802885,0.047115,...,0.725714,156.707376,80,0.825000,414.937566,48,0.979167,618.179369,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
46,47,0.163002,False,327,0.221245,0.108755,0.792049,0.007951,0.803704,0.046296,...,0.703125,152.103911,62,0.870968,539.445851,73,0.958904,554.032508,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...
49,50,0.190975,False,298,0.201624,0.128376,0.791946,0.008054,0.795455,0.054545,...,0.713415,254.397971,84,0.857143,485.708710,50,0.940000,582.076944,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
47,48,0.182726,False,298,0.201624,0.128376,0.791946,0.008054,0.803704,0.046296,...,0.694611,233.438766,59,0.864407,538.478586,72,0.958333,553.513930,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.70_0.80_1.00_z_0.75_1.0...
48,49,0.183545,False,298,0.201624,0.128376,0.791946,0.008054,0.802885,0.047115,...,0.731844,205.505810,71,0.816901,426.789809,48,0.979167,618.179369,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...

Year-by-year performance for top diagnostic models:

,core_spec_id,secondary_spec_id,year,trades,win_rate,total_pnl,avg_pnl_per_day,worst_trade_pnl,core_trades,secondary_trades,front_trades,middle_trades,back_trades
0,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...,2020,24,0.958333,524553.510088,863.827753,-19487.360567,22,2,5,6,13
1,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...,2021,28,0.821429,223219.012931,553.694973,-23729.930996,19,9,17,2,9
2,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...,2022,73,0.698630,250331.150560,157.216074,-108475.796818,73,0,45,17,11
3,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...,2023,40,0.850000,337217.313731,578.867644,-37485.731715,30,10,29,7,4
4,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.75_1.0...,2024,64,0.828125,496770.196758,371.224704,-37323.230285,40,24,40,6,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...,2024,55,0.890909,536534.135946,497.002740,-17160.183108,41,14,29,5,21
96,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...,2025,66,0.742424,239919.846737,24.992896,-99982.493610,50,16,42,15,9
97,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...,2026,32,0.750000,248476.047244,311.940740,-45195.769858,30,2,14,9,9
98,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...,2020,24,0.958333,524619.046533,868.328720,-19487.360567,23,1,6,4,14
99,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...,2021,28,0.821429,243098.341272,547.423579,-14407.593649,21,7,18,2,8

Loss diagnostics by layer / bucket for top diagnostic models:

,layer,tenor_bucket,losses,avg_loss,worst_loss,avg_loss_per_day,median_vrp_log,median_z_3m,median_z_1y,median_rsi14,median_rv21d
1,Core,front,1233,-22926.093687,-108475.796818,-1638.222579,0.761434,1.015037,0.830067,42.424410,17.200139
2,Core,middle,219,-27783.548699,-108475.796818,-1413.794681,0.880727,1.606724,1.108263,52.629750,14.699063
0,Core,back,88,-47979.075445,-85194.299611,-1651.296857,0.922526,1.848508,1.623179,51.383575,18.281227
4,Secondary,front,591,-27224.500131,-110915.496005,-2586.780285,0.653086,0.792659,0.524678,47.944351,13.042160
5,Secondary,middle,209,-19570.516849,-59809.805464,-846.606654,1.070410,1.051520,1.003756,62.017409,8.375802
3,Secondary,back,53,-17304.462233,-37862.365771,-568.398786,1.129141,0.893596,1.278250,66.132343,7.765878

Loss diagnostics by year / layer / bucket for top diagnostic models:

,year,layer,tenor_bucket,losses,total_loss,worst_loss,avg_loss_per_day
1,2020,Core,front,30,-5.846208e+05,-19487.360567,-1299.157371
3,2020,Secondary,middle,7,-1.319861e+05,-18855.158235,-785.631593
2,2020,Core,middle,4,-4.038668e+03,-1009.666898,-48.079376
0,2020,Core,back,4,-3.898969e+02,-97.474236,-3.361181
7,2021,Secondary,middle,114,-1.111896e+06,-23729.930996,-425.951713
5,2021,Secondary,back,40,-5.177680e+05,-27243.282335,-440.049329
4,2021,Core,front,30,-4.322278e+05,-14407.593649,-960.506243
6,2021,Secondary,front,28,-3.496757e+05,-21369.054483,-979.716966
9,2022,Core,front,513,-1.497353e+07,-108475.796818,-1951.140314
10,2022,Core,middle,90,-4.353145e+06,-108475.796818,-2542.861450
11,2022,Secondary,front,123,-4.225148e+06,-68908.014794,-3611.112998
8,2022,Core,back,57,-3.060879e+06,-85194.299611,-1821.760286
12,2022,Secondary,middle,18,-7.990086e+05,-59809.805464,-1872.099733
16,2023,Secondary,front,144,-2.907893e+06,-48913.602660,-1601.005953
13,2023,Core,front,91,-9.481331e+05,-27085.362641,-942.712370
17,2023,Secondary,middle,8,-2.655130e+05,-33189.124809,-1382.880200
14,2023,Core,middle,27,-7.743021e+04,-2867.785457,-159.321414
15,2023,Secondary,back,1,-3.318912e+04,-33189.124809,-1382.880200
21,2024,Secondary,front,123,-1.479548e+06,-37323.230285,-1065.401292
18,2024,Core,front,61,-7.033814e+05,-17160.183108,-864.039879
22,2024,Secondary,middle,24,-5.340418e+05,-45784.921065,-987.442482
19,2024,Core,middle,32,-3.432783e+05,-11744.034592,-625.968389
20,2024,Secondary,back,10,-2.933177e+05,-33193.930647,-865.358365
24,2025,Core,front,337,-7.153475e+06,-78574.577043,-1779.728660
27,2025,Secondary,front,119,-6.232682e+06,-110915.496005,-5207.422078
23,2025,Core,back,27,-1.160890e+06,-42995.910616,-1535.568236
28,2025,Secondary,middle,27,-7.857757e+05,-59316.999667,-1271.693136
25,2025,Core,middle,3,-1.482556e+05,-49418.522467,-2353.262975
26,2025,Secondary,back,1,-3.786237e+04,-37862.365771,-1514.494631
29,2026,Core,front,171,-3.472501e+06,-45195.769858,-1245.273293
30,2026,Core,middle,63,-1.158449e+06,-30436.912727,-780.614788
32,2026,Secondary,front,54,-8.947322e+05,-38419.098915,-1405.846872
33,2026,Secondary,middle,11,-4.620172e+05,-49958.754011,-1826.154832
31,2026,Secondary,back,1,-3.499934e+04,-34999.344959,-972.204027

Worst selected trades across top diagnostic models:

,trade_date,date,year,layer,tenor,tenor_bucket,outcome_value,pnl_per_day,actual_dte,vrp_log,vrp_z_3m,vrp_z_1y,rsi14,rv21d,core_spec_id,secondary_spec_id
10946,20250325,2025-03-25,2025,Secondary,12,front,-110915.496005,-11091.549601,10.0,0.515474,0.764735,0.413949,49.722178,20.886771,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
8036,20250325,2025-03-25,2025,Secondary,12,front,-110915.496005,-11091.549601,10.0,0.515474,0.764735,0.413949,49.722178,20.886771,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
6563,20250325,2025-03-25,2025,Secondary,12,front,-110915.496005,-11091.549601,10.0,0.515474,0.764735,0.413949,49.722178,20.886771,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
10466,20250325,2025-03-25,2025,Secondary,12,front,-110915.496005,-11091.549601,10.0,0.515474,0.764735,0.413949,49.722178,20.886771,core_phase1_vrp_0.80_0.90_1.00_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
7054,20250325,2025-03-25,2025,Secondary,12,front,-110915.496005,-11091.549601,10.0,0.515474,0.764735,0.413949,49.722178,20.886771,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2893,20220824,2022-08-24,2022,Core,30,back,-85194.299611,-2839.809987,30.0,0.922526,2.662252,1.319919,51.383575,18.281227,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
3827,20220824,2022-08-24,2022,Core,30,back,-85194.299611,-2839.809987,30.0,0.922526,2.662252,1.319919,51.383575,18.281227,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.80_0.90_z_0.75_1.0...
8792,20220824,2022-08-24,2022,Core,30,back,-85194.299611,-2839.809987,30.0,0.922526,2.662252,1.319919,51.383575,18.281227,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.50_0.60_0.70_z_0.25_0.5...
5383,20220824,2022-08-24,2022,Core,30,back,-85194.299611,-2839.809987,30.0,0.922526,2.662252,1.319919,51.383575,18.281227,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...
2579,20220824,2022-08-24,2022,Core,30,back,-85194.299611,-2839.809987,30.0,0.922526,2.662252,1.319919,51.383575,18.281227,core_phase1_vrp_0.70_0.80_0.90_z_0.50_0.75_0.7...,secondary_phase1_vrp_0.60_0.70_0.80_z_0.75_1.0...

Cell 4 outputs saved:
Core diagnostic:          C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell4_core_diag_20200701_20260519_20260704_092202.csv
Core by VRP:              C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell4_core_by_vrp_20200701_20260519_20260704_092202.csv
Core by z-score:          C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell4_core_by_z_20200701_20260519_20260704_092202.csv
Core by RSI:              C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell4_core_by_rsi_20200701_20260519_20260704_092202.csv
Core by RV21D:            C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell4_core_by_rv21d_20200701_20260519_20260704_092202.csv
Near-target models:       C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell4_near_target_models_20200701_20260519_20260704_092202.csv
Year summary top models:  C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell4_year_summary_top_models_20200701_20260519_20260704_092202.csv
Loss by bucket/layer:     C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell4_loss_by_bucket_layer_20200701_20260519_20260704_092202.csv
Loss by year:             C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell4_loss_by_year_20200701_20260519_20260704_092202.csv
Worst selected trades:    C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell4_worst_selected_trades_20200701_20260519_20260704_092202.csv

Cell 4 complete.

In [7]:
# Cell 5: Core-only revised Phase 1 sweep
#
# Approved scope:
#   - Core only.
#   - No Secondary.
#   - No sizing.
#   - No final lock.
#   - Use all Core parameters:
#       VRP log
#       3m z-score
#       1y z-score
#       RSI cap
#       RV21D floor
#
# User-approved grid:
#   Front 9D / 12D / 15D:
#       VRP:   [0.60, 0.70]
#       z:     [0.40, 0.50, 0.60]
#       RSI:   [68, 70, 72]
#       RV21D: [6.5, 7.0, 7.5, 8.5]
#
#   Middle 18D / 21D / 24D:
#       VRP:   [0.70, 0.80]
#       z:     [0.60, 0.70, 0.80]
#       RSI:   [66, 68, 70]
#       RV21D: [7.0, 7.5, 8.5]
#
#   Back 27D / 30D / 33D:
#       VRP:   [0.70, 0.80, 0.90]
#       z:     [0.60, 0.70, 0.80]
#       RSI:   [66, 68]
#       RV21D: [7.0, 7.5, 8.5]
#
# Constraints:
#   - 3m z-score threshold = 1y z-score threshold within each bucket.
#   - For VRP / z / RV21D:
#         Front <= Middle <= Back
#   - For RSI cap:
#         Front >= Middle >= Back
#
# Core selection logic:
#   - Apply thresholds across all 9 tenors.
#   - If no tenor passes on a date: no trade.
#   - If multiple tenors pass: select one tenor using old-process logic:
#       1. Prefer tenors with conditional sample size >= 20.
#       2. Highest conditional win probability.
#       3. Keep tenors within 25 bps of best win probability.
#       4. Highest conditional average P&L/day.
#       5. Highest conditional aggregate P&L/day.
#       6. Highest conditional win probability.
#       7. Longer tenor.
#
# P&L/day:
#   normalized_pnl_dollars / actual_dte if actual_dte is available.
#   Falls back to normalized_pnl_dollars / tenor if actual_dte is unavailable.
#
# Target:
#   Core win rate >= 85%, with highest frequency possible.

from pathlib import Path
import itertools
import numpy as np
import pandas as pd


# -----------------------------
# 1. Paths / load latest clean panel
# -----------------------------

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

PARAM_SWEEP_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "corsi_parameter_sweep_clean"
PARAM_SWEEP_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "corsi_parameter_sweep_clean"
CORSI_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "forecast_model_corsi_v1"

PARAM_SWEEP_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

RUN_TIMESTAMP = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")

clean_panel_candidates = sorted(
    PARAM_SWEEP_PROCESSED_DIR.glob("02_corsi_parameter_sweep_clean_panel_*.parquet")
)

if not clean_panel_candidates:
    raise FileNotFoundError(f"No clean panel found in {PARAM_SWEEP_PROCESSED_DIR}")

CLEAN_PANEL_PATH = clean_panel_candidates[-1]

print("Cell 5: Core-only revised Phase 1 sweep")
print(f"Clean panel path: {CLEAN_PANEL_PATH}")
print(f"Run timestamp:    {RUN_TIMESTAMP}")

panel = pd.read_parquet(CLEAN_PANEL_PATH).copy()

panel["date"] = pd.to_datetime(panel["date"]).dt.normalize()
panel["trade_date"] = pd.to_numeric(panel["trade_date"], errors="coerce").astype(int)
panel["tenor"] = pd.to_numeric(panel["tenor"], errors="coerce").astype(int)

required_panel_cols = [
    "date",
    "trade_date",
    "tenor",
    "tenor_bucket",
    "forecast_model",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rsi14",
    "rv21d",
    "outcome_value",
    "has_outcome",
    "is_parameter_sweep_eligible",
]

missing_panel_cols = [c for c in required_panel_cols if c not in panel.columns]

if missing_panel_cols:
    raise ValueError(f"Clean panel missing required columns: {missing_panel_cols}")


# -----------------------------
# 2. Actual DTE helper
# -----------------------------

def first_existing_col(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    return None


def load_actual_dte_lookup():
    """
    Locate the same outcome universe used by Cell 1 and pull actual_dte if available.
    """
    outcome_discovery_candidates = sorted(
        CORSI_AUDIT_DIR.glob("corsi_cell11_trade_outcome_file_discovery_*.csv")
    )

    if not outcome_discovery_candidates:
        return None, "no_outcome_discovery_file"

    discovery_path = outcome_discovery_candidates[-1]
    discovery = pd.read_csv(discovery_path)
    discovery.columns = [str(c).strip() for c in discovery.columns]

    file_col = "chosen_file" if "chosen_file" in discovery.columns else "path"

    if file_col not in discovery.columns:
        return None, "discovery_missing_path_column"

    preferred = discovery.copy()

    if "eligible_for_backtest" in preferred.columns:
        preferred = preferred.loc[preferred["eligible_for_backtest"].astype(bool)].copy()

    if preferred.empty:
        return None, "no_eligible_outcome_files"

    if "score" in preferred.columns:
        preferred["_score"] = pd.to_numeric(preferred["score"], errors="coerce")
    else:
        preferred["_score"] = 0.0

    if "chosen_outcome_col" in preferred.columns:
        preferred["_preferred_pnl"] = preferred["chosen_outcome_col"].eq("normalized_pnl_dollars")
    elif "outcome_col" in preferred.columns:
        preferred["_preferred_pnl"] = preferred["outcome_col"].eq("normalized_pnl_dollars")
    else:
        preferred["_preferred_pnl"] = False

    preferred = preferred.sort_values(
        ["_preferred_pnl", "_score"],
        ascending=[False, False],
    )

    for _, row in preferred.iterrows():
        path = Path(row[file_col])

        if not path.exists():
            continue

        try:
            raw = pd.read_parquet(path) if path.suffix.lower() == ".parquet" else pd.read_csv(path)
        except Exception:
            continue

        raw.columns = [str(c).strip() for c in raw.columns]

        trade_date_col = first_existing_col(raw, ["trade_date", "trade_dt", "date"])
        tenor_col = first_existing_col(raw, ["tenor", "entry_tenor", "target_tenor"])
        actual_dte_col = first_existing_col(raw, ["actual_dte"])

        if trade_date_col is None or tenor_col is None or actual_dte_col is None:
            continue

        lookup = raw[[trade_date_col, tenor_col, actual_dte_col]].copy()
        lookup = lookup.rename(columns={
            trade_date_col: "trade_date",
            tenor_col: "tenor",
            actual_dte_col: "actual_dte_from_outcomes",
        })

        lookup["trade_date"] = pd.to_numeric(lookup["trade_date"], errors="coerce").astype("Int64")
        lookup["tenor"] = pd.to_numeric(lookup["tenor"], errors="coerce").astype("Int64")
        lookup["actual_dte_from_outcomes"] = pd.to_numeric(
            lookup["actual_dte_from_outcomes"],
            errors="coerce",
        )

        lookup = lookup.dropna(subset=["trade_date", "tenor"])
        lookup["trade_date"] = lookup["trade_date"].astype(int)
        lookup["tenor"] = lookup["tenor"].astype(int)

        lookup = lookup.drop_duplicates(["trade_date", "tenor"])

        return lookup, str(path)

    return None, "actual_dte_not_found_in_outcome_files"


if "actual_dte" not in panel.columns:
    actual_dte_lookup, actual_dte_source = load_actual_dte_lookup()

    if actual_dte_lookup is not None:
        panel = panel.merge(
            actual_dte_lookup,
            on=["trade_date", "tenor"],
            how="left",
            validate="many_to_one",
        )
        panel["actual_dte"] = panel["actual_dte_from_outcomes"]
        panel = panel.drop(columns=["actual_dte_from_outcomes"])
    else:
        panel["actual_dte"] = np.nan
else:
    actual_dte_source = "clean_panel_existing_actual_dte"

panel["actual_dte"] = pd.to_numeric(panel["actual_dte"], errors="coerce")
panel["actual_dte_for_pnl_day"] = panel["actual_dte"]

fallback_mask = (
    panel["actual_dte_for_pnl_day"].isna()
    | panel["actual_dte_for_pnl_day"].le(0)
)

panel.loc[fallback_mask, "actual_dte_for_pnl_day"] = panel.loc[fallback_mask, "tenor"]
panel["pnl_per_day"] = panel["outcome_value"] / panel["actual_dte_for_pnl_day"]

print()
print("Actual DTE source:")
print(actual_dte_source)

print()
print("Actual DTE availability:")
display(pd.DataFrame([{
    "rows": len(panel),
    "actual_dte_non_null": int(panel["actual_dte"].notna().sum()),
    "actual_dte_non_null_pct": float(panel["actual_dte"].notna().mean()),
    "fallback_to_tenor_rows": int(fallback_mask.sum()),
    "fallback_to_tenor_pct": float(fallback_mask.mean()),
}]))


# -----------------------------
# 3. Build Core-only revised grid
# -----------------------------

FRONT_GRID = {
    "vrp": [0.60, 0.70],
    "z": [0.40, 0.50, 0.60],
    "rsi": [68, 70, 72],
    "rv21d": [6.5, 7.0, 7.5, 8.5],
}

MIDDLE_GRID = {
    "vrp": [0.70, 0.80],
    "z": [0.60, 0.70, 0.80],
    "rsi": [66, 68, 70],
    "rv21d": [7.0, 7.5, 8.5],
}

BACK_GRID = {
    "vrp": [0.70, 0.80, 0.90],
    "z": [0.60, 0.70, 0.80],
    "rsi": [66, 68],
    "rv21d": [7.0, 7.5, 8.5],
}


def valid_increasing_triples(front_vals, middle_vals, back_vals):
    triples = []

    for f, m, b in itertools.product(front_vals, middle_vals, back_vals):
        if f <= m <= b:
            triples.append((f, m, b))

    return triples


def valid_rsi_triples(front_vals, middle_vals, back_vals):
    triples = []

    for f, m, b in itertools.product(front_vals, middle_vals, back_vals):
        if f >= m >= b:
            triples.append((f, m, b))

    return triples


CORE_VRP_TRIPLES = valid_increasing_triples(
    FRONT_GRID["vrp"],
    MIDDLE_GRID["vrp"],
    BACK_GRID["vrp"],
)

CORE_Z_TRIPLES = valid_increasing_triples(
    FRONT_GRID["z"],
    MIDDLE_GRID["z"],
    BACK_GRID["z"],
)

CORE_RSI_TRIPLES = valid_rsi_triples(
    FRONT_GRID["rsi"],
    MIDDLE_GRID["rsi"],
    BACK_GRID["rsi"],
)

CORE_RV21D_TRIPLES = valid_increasing_triples(
    FRONT_GRID["rv21d"],
    MIDDLE_GRID["rv21d"],
    BACK_GRID["rv21d"],
)

spec_rows = []

for spec_num, (vrp, z, rsi, rv21d) in enumerate(
    itertools.product(
        CORE_VRP_TRIPLES,
        CORE_Z_TRIPLES,
        CORE_RSI_TRIPLES,
        CORE_RV21D_TRIPLES,
    ),
    start=1,
):
    spec_id = (
        f"core_revised_phase1_"
        f"vrp_{vrp[0]:.2f}_{vrp[1]:.2f}_{vrp[2]:.2f}_"
        f"z_{z[0]:.2f}_{z[1]:.2f}_{z[2]:.2f}_"
        f"rsi_{int(rsi[0])}_{int(rsi[1])}_{int(rsi[2])}_"
        f"rv21d_{rv21d[0]:.1f}_{rv21d[1]:.1f}_{rv21d[2]:.1f}"
    )

    spec_rows.append({
        "spec_id": spec_id,
        "role": "Core",
        "phase": "core_only_revised_phase1",
        "forecast_denominator": "har_total_simple",

        "front_vrp_log_min": vrp[0],
        "middle_vrp_log_min": vrp[1],
        "back_vrp_log_min": vrp[2],

        "front_z_3m_min": z[0],
        "middle_z_3m_min": z[1],
        "back_z_3m_min": z[2],

        "front_z_1y_min": z[0],
        "middle_z_1y_min": z[1],
        "back_z_1y_min": z[2],

        "front_rsi14_max": rsi[0],
        "middle_rsi14_max": rsi[1],
        "back_rsi14_max": rsi[2],

        "front_rv21d_min": rv21d[0],
        "middle_rv21d_min": rv21d[1],
        "back_rv21d_min": rv21d[2],

        "phase1_z_3m_equals_z_1y": True,
    })

core_specs = pd.DataFrame(spec_rows)

grid_summary = pd.DataFrame([{
    "valid_vrp_triples": len(CORE_VRP_TRIPLES),
    "valid_z_triples": len(CORE_Z_TRIPLES),
    "valid_rsi_triples": len(CORE_RSI_TRIPLES),
    "valid_rv21d_triples": len(CORE_RV21D_TRIPLES),
    "total_core_specs": len(core_specs),
}])

print()
print("Revised Core-only grid summary:")
display(grid_summary)

print()
print("Revised Core specs sample:")
display(core_specs.head(20))


# -----------------------------
# 4. Build complete eligible matrix panel
# -----------------------------

TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

TENOR_BUCKET_MAP = {
    9: "front",
    12: "front",
    15: "front",
    18: "middle",
    21: "middle",
    24: "middle",
    27: "back",
    30: "back",
    33: "back",
}

BUCKETS = ["front", "middle", "back"]
WIN_BAND = 0.0025
MIN_CONDITIONAL_OBS = 20

eligible = panel.loc[panel["is_parameter_sweep_eligible"].astype(bool)].copy()
eligible = eligible.replace([np.inf, -np.inf], np.nan)

needed_for_matrix = [
    "trade_date",
    "date",
    "tenor",
    "tenor_bucket",
    "forecast_model",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rsi14",
    "rv21d",
    "outcome_value",
    "actual_dte_for_pnl_day",
    "pnl_per_day",
]

eligible = eligible.dropna(subset=needed_for_matrix).copy()

eligible = eligible.loc[
    eligible["tenor"].isin(TENORS)
    & eligible["actual_dte_for_pnl_day"].gt(0)
].copy()

duplicate_rows = eligible.duplicated(["trade_date", "tenor"]).sum()

if duplicate_rows:
    raise ValueError(f"Eligible panel has duplicate trade_date x tenor rows: {duplicate_rows}")

date_counts = eligible.groupby("trade_date")["tenor"].nunique()
complete_dates = date_counts.loc[date_counts.eq(len(TENORS))].index.tolist()

eligible = eligible.loc[eligible["trade_date"].isin(complete_dates)].copy()

eligible_dates = sorted(eligible["trade_date"].unique())
num_dates = len(eligible_dates)
num_tenors = len(TENORS)

date_lookup = (
    eligible[["trade_date", "date"]]
    .drop_duplicates("trade_date")
    .set_index("trade_date")
    .loc[eligible_dates]
)

date_array = date_lookup["date"].to_numpy()


def pivot_matrix(col, dtype=float):
    mat = (
        eligible
        .pivot(index="trade_date", columns="tenor", values=col)
        .reindex(index=eligible_dates, columns=TENORS)
    )

    if mat.isna().any().any():
        missing = int(mat.isna().sum().sum())
        raise ValueError(f"Matrix for {col} has missing cells after complete-date filter: {missing}")

    return mat.to_numpy(dtype=dtype)


vrp_mat = pivot_matrix("vrp_log")
z3m_mat = pivot_matrix("vrp_z_3m")
z1y_mat = pivot_matrix("vrp_z_1y")
rsi_mat = pivot_matrix("rsi14")
rv21d_mat = pivot_matrix("rv21d")
pnl_mat = pivot_matrix("outcome_value")
actual_dte_mat = pivot_matrix("actual_dte_for_pnl_day")
pnl_per_day_mat = pivot_matrix("pnl_per_day")

valid_outcome_mat = (
    np.isfinite(pnl_mat)
    & np.isfinite(pnl_per_day_mat)
    & np.isfinite(actual_dte_mat)
)

tenor_array = np.array(TENORS, dtype=int)
tenor_bucket_array = np.array([TENOR_BUCKET_MAP[int(t)] for t in tenor_array], dtype=object)

print()
print("Cell 5 input summary:")
display(pd.DataFrame([{
    "eligible_rows_after_complete_date_filter": len(eligible),
    "eligible_dates": num_dates,
    "first_date": pd.to_datetime(date_array.min()),
    "last_date": pd.to_datetime(date_array.max()),
    "unique_tenors": num_tenors,
    "core_specs_to_test": len(core_specs),
    "win_band_bps": WIN_BAND * 10000,
    "min_conditional_obs": MIN_CONDITIONAL_OBS,
    "forecast_model": ", ".join(sorted(eligible["forecast_model"].astype(str).unique())),
}]))


# -----------------------------
# 5. Matrix helper functions
# -----------------------------

def threshold_array_for_spec(spec_row, field_suffix):
    vals = []

    for tenor in TENORS:
        bucket = TENOR_BUCKET_MAP[int(tenor)]
        vals.append(float(spec_row[f"{bucket}_{field_suffix}"]))

    return np.array(vals, dtype=float)


def build_pass_matrix(spec_row):
    vrp_threshold = threshold_array_for_spec(spec_row, "vrp_log_min")
    z3m_threshold = threshold_array_for_spec(spec_row, "z_3m_min")
    z1y_threshold = threshold_array_for_spec(spec_row, "z_1y_min")
    rsi_cap = threshold_array_for_spec(spec_row, "rsi14_max")
    rv21d_floor = threshold_array_for_spec(spec_row, "rv21d_min")

    return (
        (vrp_mat >= vrp_threshold[None, :])
        & (z3m_mat >= z3m_threshold[None, :])
        & (z1y_mat >= z1y_threshold[None, :])
        & (rsi_mat <= rsi_cap[None, :])
        & (rv21d_mat >= rv21d_floor[None, :])
        & valid_outcome_mat
    )


def compute_conditional_arrays(pass_matrix):
    """
    Conditional stats by tenor for a single Core spec.
    """
    obs = pass_matrix.sum(axis=0).astype(float)

    wins = ((pnl_mat > 0) & pass_matrix).sum(axis=0).astype(float)

    total_pnl = np.where(
        obs > 0,
        np.where(pass_matrix, pnl_mat, 0.0).sum(axis=0),
        0.0,
    )

    total_pnl_day = np.where(
        obs > 0,
        np.where(pass_matrix, pnl_per_day_mat, 0.0).sum(axis=0),
        np.nan,
    )

    total_dte = np.where(
        obs > 0,
        np.where(pass_matrix, actual_dte_mat, 0.0).sum(axis=0),
        np.nan,
    )

    win_prob = np.divide(
        wins,
        obs,
        out=np.full_like(obs, np.nan, dtype=float),
        where=obs > 0,
    )

    avg_pnl_per_day = np.divide(
        total_pnl_day,
        obs,
        out=np.full_like(obs, np.nan, dtype=float),
        where=obs > 0,
    )

    avg_pnl_per_trade = np.divide(
        total_pnl,
        obs,
        out=np.full_like(obs, np.nan, dtype=float),
        where=obs > 0,
    )

    aggregate_pnl_per_day = np.divide(
        total_pnl,
        total_dte,
        out=np.full_like(obs, np.nan, dtype=float),
        where=total_dte > 0,
    )

    worst_trade = np.full(num_tenors, np.nan)
    worst_pnl_day = np.full(num_tenors, np.nan)
    avg_actual_dte = np.full(num_tenors, np.nan)

    for col_idx in range(num_tenors):
        mask = pass_matrix[:, col_idx]

        if mask.any():
            worst_trade[col_idx] = np.nanmin(pnl_mat[mask, col_idx])
            worst_pnl_day[col_idx] = np.nanmin(pnl_per_day_mat[mask, col_idx])
            avg_actual_dte[col_idx] = np.nanmean(actual_dte_mat[mask, col_idx])

    sample_ok = obs >= MIN_CONDITIONAL_OBS

    return {
        "obs": obs,
        "wins": wins,
        "win_prob": win_prob,
        "avg_pnl_per_day": avg_pnl_per_day,
        "aggregate_pnl_per_day": aggregate_pnl_per_day,
        "avg_pnl_per_trade": avg_pnl_per_trade,
        "total_pnl": total_pnl,
        "worst_trade": worst_trade,
        "worst_pnl_day": worst_pnl_day,
        "avg_actual_dte": avg_actual_dte,
        "sample_ok": sample_ok,
    }


def select_cols_from_pass_and_stats(pass_matrix, stats):
    """
    Old-process-aligned selector.

    Ranking:
      1. Prefer tenors with conditional_obs >= MIN_CONDITIONAL_OBS.
      2. Highest conditional win probability.
      3. Keep tenors within WIN_BAND of best conditional win probability.
      4. Highest conditional average P&L/day.
      5. Highest conditional aggregate P&L/day.
      6. Highest conditional win probability.
      7. Longer tenor.
    """
    obs = stats["obs"]
    win = stats["win_prob"]
    avg_day = stats["avg_pnl_per_day"]
    agg_day = stats["aggregate_pnl_per_day"]
    sample_ok = stats["sample_ok"]

    has_stats = (
        (obs > 0)
        & np.isfinite(win)
        & np.isfinite(avg_day)
        & np.isfinite(agg_day)
    )

    active = pass_matrix & has_stats[None, :]

    active_sample_ok = active & sample_ok[None, :]
    row_has_sample_ok = active_sample_ok.any(axis=1)

    ranking_universe = np.where(
        row_has_sample_ok[:, None],
        active_sample_ok,
        active,
    )

    win_masked = np.where(
        ranking_universe,
        win[None, :],
        -np.inf,
    )

    best_win = win_masked.max(axis=1)
    row_has_any = np.isfinite(best_win)

    inside_win_band = (
        ranking_universe
        & row_has_any[:, None]
        & (win[None, :] >= (best_win[:, None] - WIN_BAND))
    )

    selected_col = np.full(num_dates, -1, dtype=int)

    best_avg = np.full(num_dates, -np.inf)
    best_agg = np.full(num_dates, -np.inf)
    best_win_for_tie = np.full(num_dates, -np.inf)
    best_tenor = np.full(num_dates, -np.inf)

    for col_idx, tenor in enumerate(TENORS):
        cand = inside_win_band[:, col_idx]

        avg_val = avg_day[col_idx]
        agg_val = agg_day[col_idx]
        win_val = win[col_idx]
        tenor_val = float(tenor)

        better = (
            cand
            & (
                (avg_val > best_avg)
                | (
                    (avg_val == best_avg)
                    & (agg_val > best_agg)
                )
                | (
                    (avg_val == best_avg)
                    & (agg_val == best_agg)
                    & (win_val > best_win_for_tie)
                )
                | (
                    (avg_val == best_avg)
                    & (agg_val == best_agg)
                    & (win_val == best_win_for_tie)
                    & (tenor_val > best_tenor)
                )
            )
        )

        selected_col[better] = col_idx
        best_avg[better] = avg_val
        best_agg[better] = agg_val
        best_win_for_tie[better] = win_val
        best_tenor[better] = tenor_val

    return selected_col


def profit_factor(values):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]

    if values.size == 0:
        return np.nan

    gains = values[values > 0].sum()
    losses = values[values < 0].sum()

    if losses < 0:
        return gains / abs(losses)

    if gains > 0 and losses == 0:
        return np.inf

    return np.nan


def summarize_selected_cols(selected_cols, prefix):
    selected_cols = np.asarray(selected_cols, dtype=int)
    date_idx = np.where(selected_cols >= 0)[0]

    if date_idx.size == 0:
        return {
            f"{prefix}_trades": 0,
            f"{prefix}_frequency": 0.0,
            f"{prefix}_win_rate": np.nan,
            f"{prefix}_total_pnl": 0.0,
            f"{prefix}_avg_pnl_per_trade": np.nan,
            f"{prefix}_avg_pnl_per_day": np.nan,
            f"{prefix}_exposure_day_weighted_pnl_per_day": np.nan,
            f"{prefix}_profit_factor": np.nan,
            f"{prefix}_worst_trade_pnl": np.nan,
            f"{prefix}_worst_pnl_per_day": np.nan,
            f"{prefix}_best_trade_pnl": np.nan,
            f"{prefix}_avg_actual_dte": np.nan,
            f"{prefix}_avg_selected_tenor": np.nan,
        }

    cols = selected_cols[date_idx]

    pnl = pnl_mat[date_idx, cols]
    pnl_day = pnl_per_day_mat[date_idx, cols]
    dte = actual_dte_mat[date_idx, cols]
    selected_tenors = tenor_array[cols]

    total_dte = np.nansum(dte)

    if total_dte > 0:
        exposure_day_weighted_pnl_per_day = np.nansum(pnl) / total_dte
    else:
        exposure_day_weighted_pnl_per_day = np.nan

    return {
        f"{prefix}_trades": int(date_idx.size),
        f"{prefix}_frequency": float(date_idx.size / num_dates) if num_dates else np.nan,
        f"{prefix}_win_rate": float(np.nanmean(pnl > 0)),
        f"{prefix}_total_pnl": float(np.nansum(pnl)),
        f"{prefix}_avg_pnl_per_trade": float(np.nanmean(pnl)),
        f"{prefix}_avg_pnl_per_day": float(np.nanmean(pnl_day)),
        f"{prefix}_exposure_day_weighted_pnl_per_day": float(exposure_day_weighted_pnl_per_day),
        f"{prefix}_profit_factor": float(profit_factor(pnl)),
        f"{prefix}_worst_trade_pnl": float(np.nanmin(pnl)),
        f"{prefix}_worst_pnl_per_day": float(np.nanmin(pnl_day)),
        f"{prefix}_best_trade_pnl": float(np.nanmax(pnl)),
        f"{prefix}_avg_actual_dte": float(np.nanmean(dte)),
        f"{prefix}_avg_selected_tenor": float(np.nanmean(selected_tenors)),
    }


def bucket_metrics(selected_cols):
    selected_cols = np.asarray(selected_cols, dtype=int)
    date_idx = np.where(selected_cols >= 0)[0]

    out = {}

    for bucket in BUCKETS:
        out[f"{bucket}_selected_trades"] = 0
        out[f"{bucket}_selected_win_rate"] = np.nan
        out[f"{bucket}_selected_avg_pnl_per_day"] = np.nan
        out[f"{bucket}_selected_exposure_day_weighted_pnl_per_day"] = np.nan
        out[f"{bucket}_selected_total_pnl"] = 0.0
        out[f"{bucket}_selected_worst_trade_pnl"] = np.nan

    if date_idx.size == 0:
        return out

    cols = selected_cols[date_idx]
    selected_buckets = tenor_bucket_array[cols]

    for bucket in BUCKETS:
        bucket_mask = selected_buckets == bucket

        if not bucket_mask.any():
            continue

        bucket_date_idx = date_idx[bucket_mask]
        bucket_cols = cols[bucket_mask]

        pnl = pnl_mat[bucket_date_idx, bucket_cols]
        pnl_day = pnl_per_day_mat[bucket_date_idx, bucket_cols]
        dte = actual_dte_mat[bucket_date_idx, bucket_cols]

        total_dte = np.nansum(dte)

        out[f"{bucket}_selected_trades"] = int(bucket_mask.sum())
        out[f"{bucket}_selected_win_rate"] = float(np.nanmean(pnl > 0))
        out[f"{bucket}_selected_avg_pnl_per_day"] = float(np.nanmean(pnl_day))
        out[f"{bucket}_selected_exposure_day_weighted_pnl_per_day"] = (
            float(np.nansum(pnl) / total_dte) if total_dte > 0 else np.nan
        )
        out[f"{bucket}_selected_total_pnl"] = float(np.nansum(pnl))
        out[f"{bucket}_selected_worst_trade_pnl"] = float(np.nanmin(pnl))

    return out


def append_conditional_rows(rows, spec_id, stats):
    for col_idx, tenor in enumerate(TENORS):
        rows.append({
            "spec_id": spec_id,
            "role": "Core",
            "tenor": int(tenor),
            "tenor_bucket": TENOR_BUCKET_MAP[int(tenor)],
            "conditional_obs": int(stats["obs"][col_idx]),
            "conditional_wins": int(stats["wins"][col_idx]),
            "conditional_win_probability": stats["win_prob"][col_idx],
            "conditional_avg_pnl_per_day": stats["avg_pnl_per_day"][col_idx],
            "conditional_aggregate_pnl_per_day": stats["aggregate_pnl_per_day"][col_idx],
            "conditional_avg_pnl_per_trade": stats["avg_pnl_per_trade"][col_idx],
            "conditional_total_pnl": stats["total_pnl"][col_idx],
            "conditional_worst_trade_pnl": stats["worst_trade"][col_idx],
            "conditional_worst_pnl_per_day": stats["worst_pnl_day"][col_idx],
            "conditional_avg_actual_dte": stats["avg_actual_dte"][col_idx],
            "conditional_sample_ok": bool(stats["sample_ok"][col_idx]),
        })


# -----------------------------
# 6. Run revised Core-only sweep
# -----------------------------

summary_rows = []
conditional_rows = []

total_specs = len(core_specs)

print()
print(f"Running Core-only revised sweep: {total_specs:,} specs")

for i, (_, spec_row) in enumerate(core_specs.iterrows(), start=1):
    spec_id = spec_row["spec_id"]

    pass_matrix = build_pass_matrix(spec_row)
    candidate_dates = pass_matrix.any(axis=1)
    candidate_rows = int(pass_matrix.sum())

    stats = compute_conditional_arrays(pass_matrix)
    selected_cols = select_cols_from_pass_and_stats(pass_matrix, stats)

    row = {
        "spec_id": spec_id,
        "role": "Core",
        "phase": "core_only_revised_phase1",
        "candidate_rows": candidate_rows,
        "candidate_dates": int(candidate_dates.sum()),
        "candidate_frequency": float(candidate_dates.sum() / num_dates) if num_dates else np.nan,

        "front_vrp_log_min": spec_row["front_vrp_log_min"],
        "middle_vrp_log_min": spec_row["middle_vrp_log_min"],
        "back_vrp_log_min": spec_row["back_vrp_log_min"],

        "front_z_3m_min": spec_row["front_z_3m_min"],
        "middle_z_3m_min": spec_row["middle_z_3m_min"],
        "back_z_3m_min": spec_row["back_z_3m_min"],

        "front_z_1y_min": spec_row["front_z_1y_min"],
        "middle_z_1y_min": spec_row["middle_z_1y_min"],
        "back_z_1y_min": spec_row["back_z_1y_min"],

        "front_rsi14_max": spec_row["front_rsi14_max"],
        "middle_rsi14_max": spec_row["middle_rsi14_max"],
        "back_rsi14_max": spec_row["back_rsi14_max"],

        "front_rv21d_min": spec_row["front_rv21d_min"],
        "middle_rv21d_min": spec_row["middle_rv21d_min"],
        "back_rv21d_min": spec_row["back_rv21d_min"],
    }

    row.update(summarize_selected_cols(selected_cols, "core"))
    row.update(bucket_metrics(selected_cols))

    summary_rows.append(row)
    append_conditional_rows(conditional_rows, spec_id, stats)

    if i % 1000 == 0 or i == total_specs:
        print(f"Core specs processed: {i:,} / {total_specs:,}")

core_summary = pd.DataFrame(summary_rows)
conditional_stats = pd.DataFrame(conditional_rows)


# -----------------------------
# 7. Add labels / flags / rankings
# -----------------------------

core_summary["vrp_triple"] = (
    core_summary["front_vrp_log_min"].map("{:.2f}".format)
    + " / "
    + core_summary["middle_vrp_log_min"].map("{:.2f}".format)
    + " / "
    + core_summary["back_vrp_log_min"].map("{:.2f}".format)
)

core_summary["z_triple"] = (
    core_summary["front_z_3m_min"].map("{:.2f}".format)
    + " / "
    + core_summary["middle_z_3m_min"].map("{:.2f}".format)
    + " / "
    + core_summary["back_z_3m_min"].map("{:.2f}".format)
)

core_summary["rsi_triple"] = (
    core_summary["front_rsi14_max"].astype(int).astype(str)
    + " / "
    + core_summary["middle_rsi14_max"].astype(int).astype(str)
    + " / "
    + core_summary["back_rsi14_max"].astype(int).astype(str)
)

core_summary["rv21d_triple"] = (
    core_summary["front_rv21d_min"].map("{:.1f}".format)
    + " / "
    + core_summary["middle_rv21d_min"].map("{:.1f}".format)
    + " / "
    + core_summary["back_rv21d_min"].map("{:.1f}".format)
)

core_summary["meets_core_win_85"] = core_summary["core_win_rate"].ge(0.85)
core_summary["meets_core_win_82"] = core_summary["core_win_rate"].ge(0.82)
core_summary["meets_core_win_80"] = core_summary["core_win_rate"].ge(0.80)

core_summary["core_win_gap_to_85"] = 0.85 - core_summary["core_win_rate"]

core_summary = core_summary.sort_values(
    [
        "meets_core_win_85",
        "core_frequency",
        "core_win_rate",
        "core_avg_pnl_per_day",
        "core_total_pnl",
        "core_worst_trade_pnl",
    ],
    ascending=[
        False,
        False,
        False,
        False,
        False,
        False,
    ],
).reset_index(drop=True)

core_summary["frequency_rank_with_targets_first"] = np.arange(1, len(core_summary) + 1)

core_summary_by_win = core_summary.sort_values(
    [
        "core_win_rate",
        "core_frequency",
        "core_avg_pnl_per_day",
        "core_total_pnl",
    ],
    ascending=[False, False, False, False],
).reset_index(drop=True)

core_summary_by_win["win_rate_rank"] = np.arange(1, len(core_summary_by_win) + 1)


# -----------------------------
# 8. Parameter group diagnostics
# -----------------------------

def parameter_group_summary(df, group_col):
    out = (
        df
        .groupby(group_col)
        .agg(
            specs=("spec_id", "nunique"),
            max_core_win_rate=("core_win_rate", "max"),
            median_core_win_rate=("core_win_rate", "median"),
            max_core_frequency=("core_frequency", "max"),
            median_core_frequency=("core_frequency", "median"),
            max_core_avg_pnl_per_day=("core_avg_pnl_per_day", "max"),
            median_core_avg_pnl_per_day=("core_avg_pnl_per_day", "median"),
            max_core_total_pnl=("core_total_pnl", "max"),
            specs_core_win_85_plus=("meets_core_win_85", "sum"),
            specs_core_win_82_plus=("meets_core_win_82", "sum"),
            specs_core_win_80_plus=("meets_core_win_80", "sum"),
        )
        .reset_index()
        .sort_values(
            [
                "max_core_win_rate",
                "max_core_frequency",
                "max_core_avg_pnl_per_day",
            ],
            ascending=[False, False, False],
        )
    )

    return out


core_by_vrp = parameter_group_summary(core_summary, "vrp_triple")
core_by_z = parameter_group_summary(core_summary, "z_triple")
core_by_rsi = parameter_group_summary(core_summary, "rsi_triple")
core_by_rv21d = parameter_group_summary(core_summary, "rv21d_triple")


# -----------------------------
# 9. Display outputs
# -----------------------------

print()
print("Core-only revised sweep summary:")
display(pd.DataFrame([{
    "core_specs_tested": len(core_summary),
    "specs_core_win_85_plus": int(core_summary["meets_core_win_85"].sum()),
    "specs_core_win_82_plus": int(core_summary["meets_core_win_82"].sum()),
    "specs_core_win_80_plus": int(core_summary["meets_core_win_80"].sum()),
    "max_core_win_rate": core_summary["core_win_rate"].max(),
    "median_core_win_rate": core_summary["core_win_rate"].median(),
    "max_core_frequency": core_summary["core_frequency"].max(),
    "median_core_frequency": core_summary["core_frequency"].median(),
    "max_core_avg_pnl_per_day": core_summary["core_avg_pnl_per_day"].max(),
    "median_core_avg_pnl_per_day": core_summary["core_avg_pnl_per_day"].median(),
}]))

review_cols = [
    "frequency_rank_with_targets_first",
    "win_rate_rank" if "win_rate_rank" in core_summary.columns else "spec_id",
    "meets_core_win_85",
    "core_trades",
    "core_frequency",
    "core_win_rate",
    "core_win_gap_to_85",
    "core_avg_pnl_per_day",
    "core_exposure_day_weighted_pnl_per_day",
    "core_total_pnl",
    "core_profit_factor",
    "core_worst_trade_pnl",
    "core_worst_pnl_per_day",
    "core_avg_actual_dte",
    "core_avg_selected_tenor",

    "front_selected_trades",
    "front_selected_win_rate",
    "front_selected_avg_pnl_per_day",
    "front_selected_total_pnl",
    "front_selected_worst_trade_pnl",

    "middle_selected_trades",
    "middle_selected_win_rate",
    "middle_selected_avg_pnl_per_day",
    "middle_selected_total_pnl",
    "middle_selected_worst_trade_pnl",

    "back_selected_trades",
    "back_selected_win_rate",
    "back_selected_avg_pnl_per_day",
    "back_selected_total_pnl",
    "back_selected_worst_trade_pnl",

    "vrp_triple",
    "z_triple",
    "rsi_triple",
    "rv21d_triple",
    "spec_id",
]

# Make a clean review frame with both ranks attached.
core_review = core_summary.merge(
    core_summary_by_win[["spec_id", "win_rate_rank"]],
    on="spec_id",
    how="left",
    validate="one_to_one",
)

review_cols = [
    "frequency_rank_with_targets_first",
    "win_rate_rank",
    "meets_core_win_85",
    "core_trades",
    "core_frequency",
    "core_win_rate",
    "core_win_gap_to_85",
    "core_avg_pnl_per_day",
    "core_exposure_day_weighted_pnl_per_day",
    "core_total_pnl",
    "core_profit_factor",
    "core_worst_trade_pnl",
    "core_worst_pnl_per_day",
    "core_avg_actual_dte",
    "core_avg_selected_tenor",

    "front_selected_trades",
    "front_selected_win_rate",
    "front_selected_avg_pnl_per_day",
    "front_selected_total_pnl",
    "front_selected_worst_trade_pnl",

    "middle_selected_trades",
    "middle_selected_win_rate",
    "middle_selected_avg_pnl_per_day",
    "middle_selected_total_pnl",
    "middle_selected_worst_trade_pnl",

    "back_selected_trades",
    "back_selected_win_rate",
    "back_selected_avg_pnl_per_day",
    "back_selected_total_pnl",
    "back_selected_worst_trade_pnl",

    "vrp_triple",
    "z_triple",
    "rsi_triple",
    "rv21d_triple",
    "spec_id",
]

print()
print("Top Core specs by win rate:")
display(
    core_review
    .sort_values(
        [
            "core_win_rate",
            "core_frequency",
            "core_avg_pnl_per_day",
            "core_total_pnl",
        ],
        ascending=[False, False, False, False],
    )
    [review_cols]
    .head(100)
)

print()
print("Top Core specs with win rate >= 85%, ranked by frequency:")
display(
    core_review
    .loc[core_review["meets_core_win_85"], review_cols]
    .sort_values(
        [
            "core_frequency",
            "core_win_rate",
            "core_avg_pnl_per_day",
            "core_total_pnl",
        ],
        ascending=[False, False, False, False],
    )
    .head(100)
)

print()
print("Top Core specs with win rate >= 85%, ranked by average P&L/day:")
display(
    core_review
    .loc[core_review["meets_core_win_85"], review_cols]
    .sort_values(
        [
            "core_avg_pnl_per_day",
            "core_frequency",
            "core_win_rate",
            "core_total_pnl",
        ],
        ascending=[False, False, False, False],
    )
    .head(100)
)

print()
print("Highest-frequency Core specs with win rate >= 82%:")
display(
    core_review
    .loc[core_review["core_win_rate"].ge(0.82), review_cols]
    .sort_values(
        [
            "core_frequency",
            "core_win_rate",
            "core_avg_pnl_per_day",
            "core_total_pnl",
        ],
        ascending=[False, False, False, False],
    )
    .head(100)
)

print()
print("Core parameter diagnostics by VRP triple:")
display(core_by_vrp)

print()
print("Core parameter diagnostics by z-score triple:")
display(core_by_z)

print()
print("Core parameter diagnostics by RSI cap triple:")
display(core_by_rsi)

print()
print("Core parameter diagnostics by RV21D floor triple:")
display(core_by_rv21d)


# -----------------------------
# 10. Save outputs
# -----------------------------

safe_start = pd.to_datetime(date_array.min()).strftime("%Y%m%d")
safe_end = pd.to_datetime(date_array.max()).strftime("%Y%m%d")

core_specs_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell5_core_only_revised_specs_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

grid_summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell5_core_only_revised_grid_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell5_core_only_revised_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

conditional_stats_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell5_core_only_revised_conditional_stats_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

top_by_win_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell5_core_only_revised_top_by_win_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

target_by_frequency_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell5_core_only_revised_win85_by_frequency_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

target_by_pnl_day_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell5_core_only_revised_win85_by_pnl_day_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_vrp_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell5_core_only_revised_by_vrp_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_z_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell5_core_only_revised_by_z_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_rsi_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell5_core_only_revised_by_rsi_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_rv21d_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell5_core_only_revised_by_rv21d_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_specs.to_csv(core_specs_path, index=False)
grid_summary.to_csv(grid_summary_path, index=False)
core_review.to_csv(core_summary_path, index=False)
conditional_stats.to_csv(conditional_stats_path, index=False)

core_review.sort_values(
    [
        "core_win_rate",
        "core_frequency",
        "core_avg_pnl_per_day",
        "core_total_pnl",
    ],
    ascending=[False, False, False, False],
).head(1000).to_csv(top_by_win_path, index=False)

core_review.loc[
    core_review["meets_core_win_85"]
].sort_values(
    [
        "core_frequency",
        "core_win_rate",
        "core_avg_pnl_per_day",
        "core_total_pnl",
    ],
    ascending=[False, False, False, False],
).to_csv(target_by_frequency_path, index=False)

core_review.loc[
    core_review["meets_core_win_85"]
].sort_values(
    [
        "core_avg_pnl_per_day",
        "core_frequency",
        "core_win_rate",
        "core_total_pnl",
    ],
    ascending=[False, False, False, False],
).to_csv(target_by_pnl_day_path, index=False)

core_by_vrp.to_csv(core_by_vrp_path, index=False)
core_by_z.to_csv(core_by_z_path, index=False)
core_by_rsi.to_csv(core_by_rsi_path, index=False)
core_by_rv21d.to_csv(core_by_rv21d_path, index=False)

print()
print("Cell 5 outputs saved:")
print(f"Core specs:                  {core_specs_path}")
print(f"Grid summary:                {grid_summary_path}")
print(f"Core summary:                {core_summary_path}")
print(f"Conditional stats:           {conditional_stats_path}")
print(f"Top by win rate:             {top_by_win_path}")
print(f"Win >=85 by frequency:       {target_by_frequency_path}")
print(f"Win >=85 by P&L/day:         {target_by_pnl_day_path}")
print(f"Core by VRP:                 {core_by_vrp_path}")
print(f"Core by z-score:             {core_by_z_path}")
print(f"Core by RSI:                 {core_by_rsi_path}")
print(f"Core by RV21D:               {core_by_rv21d_path}")

print()
print("Cell 5 complete.")

Cell 5: Core-only revised Phase 1 sweep
Clean panel path: C:\Users\patri\vrp_project\data\processed\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_panel_20200102_20260623_20260704_085138.parquet
Run timestamp:    20260704_094614

Actual DTE source:
C:\Users\patri\vrp_project\data\processed\put_candidate_universe_pricing_v0_1.parquet

Actual DTE availability:

,rows,actual_dte_non_null,actual_dte_non_null_pct,fallback_to_tenor_rows,fallback_to_tenor_pct
0,14565,14565,1.0,0,0.0

Revised Core-only grid summary:

,valid_vrp_triples,valid_z_triples,valid_rsi_triples,valid_rv21d_triples,total_core_specs
0,10,18,13,16,37440

Revised Core specs sample:

,spec_id,role,phase,forecast_denominator,front_vrp_log_min,middle_vrp_log_min,back_vrp_log_min,front_z_3m_min,middle_z_3m_min,back_z_3m_min,front_z_1y_min,middle_z_1y_min,back_z_1y_min,front_rsi14_max,middle_rsi14_max,back_rsi14_max,front_rv21d_min,middle_rv21d_min,back_rv21d_min,phase1_z_3m_equals_z_1y
0,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,6.5,7.0,7.0,True
1,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,6.5,7.0,7.5,True
2,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,6.5,7.0,8.5,True
3,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,6.5,7.5,7.5,True
4,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,6.5,7.5,8.5,True
5,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,6.5,8.5,8.5,True
6,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,7.0,7.0,7.0,True
7,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,7.0,7.0,7.5,True
8,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,7.0,7.0,8.5,True
9,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,7.0,7.5,7.5,True
10,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,7.0,7.5,8.5,True
11,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,7.0,8.5,8.5,True
12,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,7.5,7.5,7.5,True
13,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,7.5,7.5,8.5,True
14,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,7.5,8.5,8.5,True
15,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,66,66,8.5,8.5,8.5,True
16,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,68,66,6.5,7.0,7.0,True
17,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,68,66,6.5,7.0,7.5,True
18,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,68,66,6.5,7.0,8.5,True
19,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.40_...,Core,core_only_revised_phase1,har_total_simple,0.6,0.7,0.7,0.4,0.6,0.6,0.4,0.6,0.6,68,68,66,6.5,7.5,7.5,True

Cell 5 input summary:

,eligible_rows_after_complete_date_filter,eligible_dates,first_date,last_date,unique_tenors,core_specs_to_test,win_band_bps,min_conditional_obs,forecast_model
0,13302,1478,2020-07-01,2026-05-19,9,37440,25.0,20,har_total_simple

Running Core-only revised sweep: 37,440 specs
Core specs processed: 1,000 / 37,440
Core specs processed: 2,000 / 37,440
Core specs processed: 3,000 / 37,440
Core specs processed: 4,000 / 37,440
Core specs processed: 5,000 / 37,440
Core specs processed: 6,000 / 37,440
Core specs processed: 7,000 / 37,440
Core specs processed: 8,000 / 37,440
Core specs processed: 9,000 / 37,440
Core specs processed: 10,000 / 37,440
Core specs processed: 11,000 / 37,440
Core specs processed: 12,000 / 37,440
Core specs processed: 13,000 / 37,440
Core specs processed: 14,000 / 37,440
Core specs processed: 15,000 / 37,440
Core specs processed: 16,000 / 37,440
Core specs processed: 17,000 / 37,440
Core specs processed: 18,000 / 37,440
Core specs processed: 19,000 / 37,440
Core specs processed: 20,000 / 37,440
Core specs processed: 21,000 / 37,440
Core specs processed: 22,000 / 37,440
Core specs processed: 23,000 / 37,440
Core specs processed: 24,000 / 37,440
Core specs processed: 25,000 / 37,440
Core specs processed: 26,000 / 37,440
Core specs processed: 27,000 / 37,440
Core specs processed: 28,000 / 37,440
Core specs processed: 29,000 / 37,440
Core specs processed: 30,000 / 37,440
Core specs processed: 31,000 / 37,440
Core specs processed: 32,000 / 37,440
Core specs processed: 33,000 / 37,440
Core specs processed: 34,000 / 37,440
Core specs processed: 35,000 / 37,440
Core specs processed: 36,000 / 37,440
Core specs processed: 37,000 / 37,440
Core specs processed: 37,440 / 37,440

Core-only revised sweep summary:

,core_specs_tested,specs_core_win_85_plus,specs_core_win_82_plus,specs_core_win_80_plus,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day
0,37440,0,0,1641,0.818815,0.780268,0.246279,0.20636,426.867271,318.191905

Top Core specs by win rate:

,frequency_rank_with_targets_first,win_rate_rank,meets_core_win_85,core_trades,core_frequency,core_win_rate,core_win_gap_to_85,core_avg_pnl_per_day,core_exposure_day_weighted_pnl_per_day,core_total_pnl,...,back_selected_trades,back_selected_win_rate,back_selected_avg_pnl_per_day,back_selected_total_pnl,back_selected_worst_trade_pnl,vrp_triple,z_triple,rsi_triple,rv21d_triple,spec_id
29781,29782,1,False,287,0.194181,0.818815,0.031185,322.966019,378.665784,2.168240e+06,...,104,0.932692,530.209207,1.509542e+06,-85194.299611,0.60 / 0.70 / 0.70,0.60 / 0.80 / 0.80,70 / 68 / 66,8.5 / 8.5 / 8.5,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.60_...
27540,27541,2,False,291,0.196888,0.817869,0.032131,321.258919,376.205119,2.175594e+06,...,104,0.932692,530.209207,1.509542e+06,-85194.299611,0.60 / 0.70 / 0.70,0.60 / 0.80 / 0.80,72 / 68 / 66,8.5 / 8.5 / 8.5,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.60_...
28178,28179,3,False,290,0.196211,0.817241,0.032759,298.131951,364.606063,2.348792e+06,...,118,0.906780,459.355058,1.723186e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.70 / 0.70,70 / 68 / 66,8.5 / 8.5 / 8.5,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.60_...
28758,28759,4,False,289,0.195535,0.816609,0.033391,299.457504,358.180853,2.106103e+06,...,104,0.932692,530.209207,1.509542e+06,-85194.299611,0.60 / 0.70 / 0.70,0.60 / 0.70 / 0.80,70 / 68 / 66,8.5 / 8.5 / 8.5,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.60_...
25561,25562,5,False,294,0.198917,0.816327,0.033673,296.780148,362.539803,2.356146e+06,...,118,0.906780,459.355058,1.723186e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.70 / 0.70,72 / 68 / 66,8.5 / 8.5 / 8.5,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.60_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27546,27547,96,False,291,0.196888,0.810997,0.039003,307.784628,388.024046,2.280417e+06,...,88,0.943182,535.129126,1.403169e+06,-85194.299611,0.60 / 0.80 / 0.90,0.60 / 0.60 / 0.60,70 / 68 / 68,8.5 / 8.5 / 8.5,core_revised_phase1_vrp_0.60_0.80_0.90_z_0.60_...
27547,27548,97,False,291,0.196888,0.810997,0.039003,307.605164,379.543160,2.179337e+06,...,103,0.922330,513.576978,1.429436e+06,-85194.299611,0.60 / 0.80 / 0.80,0.60 / 0.60 / 0.70,70 / 68 / 68,8.5 / 8.5 / 8.5,core_revised_phase1_vrp_0.60_0.80_0.80_z_0.60_...
27548,27549,98,False,291,0.196888,0.810997,0.039003,305.880758,374.629856,2.117783e+06,...,97,0.927835,524.276609,1.372073e+06,-85194.299611,0.60 / 0.80 / 0.80,0.60 / 0.70 / 0.70,72 / 68 / 66,8.5 / 8.5 / 8.5,core_revised_phase1_vrp_0.60_0.80_0.80_z_0.60_...
27549,27550,99,False,291,0.196888,0.810997,0.039003,300.442797,372.798121,2.137624e+06,...,110,0.927273,520.244991,1.540106e+06,-85194.299611,0.60 / 0.80 / 0.80,0.60 / 0.60 / 0.60,70 / 66 / 66,8.5 / 8.5 / 8.5,core_revised_phase1_vrp_0.60_0.80_0.80_z_0.60_...
27550,27551,100,False,291,0.196888,0.810997,0.039003,296.826143,353.280776,2.141941e+06,...,124,0.903226,467.080834,1.576238e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.70 / 0.70,70 / 70 / 68,8.5 / 8.5 / 8.5,core_revised_phase1_vrp_0.60_0.70_0.70_z_0.60_...

Top Core specs with win rate >= 85%, ranked by frequency:

Empty DataFrame
Columns: [frequency_rank_with_targets_first, win_rate_rank, meets_core_win_85, core_trades, core_frequency, core_win_rate, core_win_gap_to_85, core_avg_pnl_per_day, core_exposure_day_weighted_pnl_per_day, core_total_pnl, core_profit_factor, core_worst_trade_pnl, core_worst_pnl_per_day, core_avg_actual_dte, core_avg_selected_tenor, front_selected_trades, front_selected_win_rate, front_selected_avg_pnl_per_day, front_selected_total_pnl, front_selected_worst_trade_pnl, middle_selected_trades, middle_selected_win_rate, middle_selected_avg_pnl_per_day, middle_selected_total_pnl, middle_selected_worst_trade_pnl, back_selected_trades, back_selected_win_rate, back_selected_avg_pnl_per_day, back_selected_total_pnl, back_selected_worst_trade_pnl, vrp_triple, z_triple, rsi_triple, rv21d_triple, spec_id]
Index: []

[0 rows x 35 columns]

Top Core specs with win rate >= 85%, ranked by average P&L/day:

Empty DataFrame
Columns: [frequency_rank_with_targets_first, win_rate_rank, meets_core_win_85, core_trades, core_frequency, core_win_rate, core_win_gap_to_85, core_avg_pnl_per_day, core_exposure_day_weighted_pnl_per_day, core_total_pnl, core_profit_factor, core_worst_trade_pnl, core_worst_pnl_per_day, core_avg_actual_dte, core_avg_selected_tenor, front_selected_trades, front_selected_win_rate, front_selected_avg_pnl_per_day, front_selected_total_pnl, front_selected_worst_trade_pnl, middle_selected_trades, middle_selected_win_rate, middle_selected_avg_pnl_per_day, middle_selected_total_pnl, middle_selected_worst_trade_pnl, back_selected_trades, back_selected_win_rate, back_selected_avg_pnl_per_day, back_selected_total_pnl, back_selected_worst_trade_pnl, vrp_triple, z_triple, rsi_triple, rv21d_triple, spec_id]
Index: []

[0 rows x 35 columns]

Highest-frequency Core specs with win rate >= 82%:

Empty DataFrame
Columns: [frequency_rank_with_targets_first, win_rate_rank, meets_core_win_85, core_trades, core_frequency, core_win_rate, core_win_gap_to_85, core_avg_pnl_per_day, core_exposure_day_weighted_pnl_per_day, core_total_pnl, core_profit_factor, core_worst_trade_pnl, core_worst_pnl_per_day, core_avg_actual_dte, core_avg_selected_tenor, front_selected_trades, front_selected_win_rate, front_selected_avg_pnl_per_day, front_selected_total_pnl, front_selected_worst_trade_pnl, middle_selected_trades, middle_selected_win_rate, middle_selected_avg_pnl_per_day, middle_selected_total_pnl, middle_selected_worst_trade_pnl, back_selected_trades, back_selected_win_rate, back_selected_avg_pnl_per_day, back_selected_total_pnl, back_selected_worst_trade_pnl, vrp_triple, z_triple, rsi_triple, rv21d_triple, spec_id]
Index: []

[0 rows x 35 columns]

Core parameter diagnostics by VRP triple:

,vrp_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_82_plus,specs_core_win_80_plus
0,0.60 / 0.70 / 0.70,3744,0.818815,0.781538,0.246279,0.221245,371.037824,283.467329,2.525182e+06,0,0,267
5,0.70 / 0.70 / 0.70,3744,0.816092,0.780000,0.218539,0.198917,424.648081,333.969401,2.558791e+06,0,0,190
2,0.60 / 0.70 / 0.90,3744,0.815972,0.780255,0.244926,0.219892,370.857473,286.254379,2.406549e+06,0,0,188
3,0.60 / 0.80 / 0.80,3744,0.815068,0.783862,0.244926,0.219892,359.054585,300.464104,2.466948e+06,0,0,210
1,0.60 / 0.70 / 0.80,3744,0.814685,0.779456,0.244926,0.220568,372.896981,283.974208,2.431083e+06,0,0,145
4,0.60 / 0.80 / 0.90,3744,0.813793,0.782991,0.243572,0.218539,362.080215,302.624541,2.531663e+06,0,0,180
7,0.70 / 0.70 / 0.90,3744,0.813187,0.778169,0.216509,0.197564,424.838531,334.997491,2.438595e+06,0,0,153
6,0.70 / 0.70 / 0.80,3744,0.811538,0.777385,0.216509,0.197564,426.867271,332.741736,2.463130e+06,0,0,118
8,0.70 / 0.80 / 0.80,3744,0.811321,0.780303,0.213802,0.196211,411.573265,347.664957,2.468276e+06,0,0,112
9,0.70 / 0.80 / 0.90,3744,0.809886,0.778571,0.211773,0.194181,415.266908,349.889183,2.537057e+06,0,0,78

Core parameter diagnostics by z-score triple:

,z_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_82_plus,specs_core_win_80_plus
17,0.60 / 0.80 / 0.80,2080,0.818815,0.791971,0.211773,0.191475,394.711196,330.455674,2.376159e+06,0,0,316
15,0.60 / 0.70 / 0.70,2080,0.817241,0.785714,0.213802,0.194181,378.167205,311.493405,2.434773e+06,0,0,181
16,0.60 / 0.70 / 0.80,2080,0.816609,0.786441,0.213126,0.193505,375.670464,309.259390,2.239660e+06,0,0,183
9,0.50 / 0.70 / 0.70,2080,0.815217,0.775385,0.225981,0.203654,412.185373,339.779465,2.552162e+06,0,0,71
12,0.60 / 0.60 / 0.60,2080,0.815068,0.784810,0.220568,0.200271,378.528842,306.134424,2.415060e+06,0,0,163
13,0.60 / 0.60 / 0.70,2080,0.813149,0.782772,0.217862,0.198241,379.692596,312.116802,2.471717e+06,0,0,151
14,0.60 / 0.60 / 0.80,2080,0.812500,0.783871,0.217185,0.196888,377.209142,308.678529,2.321345e+06,0,0,151
6,0.50 / 0.60 / 0.60,2080,0.811388,0.782178,0.232070,0.209743,410.919924,335.997974,2.537057e+06,0,0,97
11,0.50 / 0.80 / 0.80,2080,0.810909,0.780186,0.225981,0.202977,426.867271,360.479970,2.520718e+06,0,0,46
10,0.50 / 0.70 / 0.80,2080,0.810909,0.773700,0.225981,0.203654,404.021288,333.883106,2.402272e+06,0,0,37
7,0.50 / 0.60 / 0.70,2080,0.810714,0.780000,0.229364,0.207037,412.363062,340.066708,2.558791e+06,0,0,81
0,0.40 / 0.60 / 0.60,2080,0.810398,0.780255,0.246279,0.217185,364.152433,301.256405,2.527313e+06,0,0,38
1,0.40 / 0.60 / 0.70,2080,0.808642,0.778135,0.243572,0.214479,365.062772,303.654106,2.483630e+06,0,0,27
8,0.50 / 0.60 / 0.80,2080,0.806452,0.778443,0.229364,0.206360,404.219579,333.819944,2.468276e+06,0,0,52
3,0.40 / 0.70 / 0.70,2080,0.806338,0.773770,0.241543,0.211773,364.555829,302.769375,2.490930e+06,0,0,17
2,0.40 / 0.60 / 0.80,2080,0.805556,0.776812,0.243572,0.214479,357.475904,298.250252,2.466948e+06,0,0,20
5,0.40 / 0.80 / 0.80,2080,0.803077,0.779720,0.241543,0.211434,379.326655,321.895237,2.484322e+06,0,0,8
4,0.40 / 0.70 / 0.80,2080,0.802120,0.772216,0.241543,0.211434,356.622531,297.777576,2.392528e+06,0,0,2

Core parameter diagnostics by RSI cap triple:

,rsi_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_82_plus,specs_core_win_80_plus
4,70 / 68 / 66,2880,0.818815,0.783394,0.240189,0.205683,418.980007,321.757054,2.537010e+06,0,0,247
9,72 / 68 / 66,2880,0.817869,0.780731,0.245602,0.209743,413.234618,317.790003,2.540427e+06,0,0,219
5,70 / 68 / 68,2880,0.815972,0.780822,0.240866,0.207037,418.014924,319.353736,2.533640e+06,0,0,141
6,70 / 70 / 66,2880,0.815331,0.782007,0.240189,0.206360,413.170746,318.244793,2.555374e+06,0,0,152
10,72 / 68 / 68,2880,0.815068,0.778146,0.246279,0.210419,412.282621,315.218436,2.537057e+06,0,0,131
11,72 / 70 / 66,2880,0.814433,0.779365,0.245602,0.209743,407.542286,313.782441,2.558791e+06,0,0,138
3,70 / 66 / 66,2880,0.814035,0.783951,0.238160,0.204330,420.739932,320.595674,2.511640e+06,0,0,121
8,72 / 66 / 66,2880,0.813149,0.781350,0.243572,0.207713,414.931299,316.630180,2.515057e+06,0,0,104
1,68 / 68 / 66,2880,0.812950,0.779661,0.232070,0.198241,424.994439,321.438558,2.501411e+06,0,0,107
7,70 / 70 / 68,2880,0.812500,0.779287,0.240866,0.207037,411.208121,315.313391,2.530808e+06,0,0,90
12,72 / 70 / 68,2880,0.811644,0.776667,0.246279,0.210419,405.587168,311.722606,2.534225e+06,0,0,71
2,68 / 68 / 68,2880,0.810036,0.777049,0.232747,0.199594,423.991442,318.964998,2.498042e+06,0,0,69
0,68 / 66 / 66,2880,0.807971,0.780069,0.230041,0.196888,426.867271,320.968670,2.476042e+06,0,0,51

Core parameter diagnostics by RV21D floor triple:

,rv21d_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_82_plus,specs_core_win_80_plus
15,8.5 / 8.5 / 8.5,2340,0.818815,0.799296,0.229364,0.194181,400.361119,328.444275,2.519449e+06,0,0,1139
14,7.5 / 8.5 / 8.5,2340,0.810631,0.788396,0.240189,0.203654,423.334796,316.370122,2.538957e+06,0,0,260
1,6.5 / 7.0 / 7.5,2340,0.807190,0.778481,0.246279,0.208390,412.872326,314.636766,2.494276e+06,0,0,16
0,6.5 / 7.0 / 7.0,2340,0.807190,0.778481,0.246279,0.208390,412.651656,314.441762,2.495948e+06,0,0,16
7,7.0 / 7.0 / 7.5,2340,0.807190,0.780120,0.244926,0.208390,420.693765,319.427826,2.519046e+06,0,0,16
6,7.0 / 7.0 / 7.0,2340,0.807190,0.780120,0.244926,0.208390,420.472304,319.198559,2.520718e+06,0,0,16
2,6.5 / 7.0 / 8.5,2340,0.805921,0.775920,0.245602,0.207713,410.498937,314.601994,2.511016e+06,0,0,14
8,7.0 / 7.0 / 8.5,2340,0.805921,0.777778,0.244249,0.207037,418.339973,319.634419,2.535786e+06,0,0,14
5,6.5 / 8.5 / 8.5,2340,0.805921,0.785714,0.243572,0.206360,418.995671,323.795793,2.534021e+06,0,0,59
11,7.0 / 8.5 / 8.5,2340,0.805921,0.787478,0.242219,0.205683,426.867271,329.309843,2.558791e+06,0,0,66
12,7.5 / 7.5 / 7.5,2340,0.805281,0.778947,0.242896,0.206360,418.137525,305.731942,2.461410e+06,0,0,13
13,7.5 / 7.5 / 8.5,2340,0.803987,0.776271,0.242219,0.205007,415.766008,306.369114,2.475238e+06,0,0,8
3,6.5 / 7.5 / 7.5,2340,0.800654,0.777049,0.246279,0.208390,413.918282,314.694732,2.485264e+06,0,0,2
9,7.0 / 7.5 / 7.5,2340,0.800654,0.778523,0.244926,0.208390,421.687774,318.297617,2.510034e+06,0,0,2
4,6.5 / 7.5 / 8.5,2340,0.799353,0.774411,0.245602,0.207713,411.565507,315.048663,2.497978e+06,0,0,0
10,7.0 / 7.5 / 8.5,2340,0.799353,0.775811,0.244249,0.207037,419.354345,318.221911,2.522748e+06,0,0,0

Cell 5 outputs saved:
Core specs:                  C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell5_core_only_revised_specs_20200701_20260519_20260704_094614.csv
Grid summary:                C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell5_core_only_revised_grid_summary_20200701_20260519_20260704_094614.csv
Core summary:                C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell5_core_only_revised_summary_20200701_20260519_20260704_094614.csv
Conditional stats:           C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell5_core_only_revised_conditional_stats_20200701_20260519_20260704_094614.csv
Top by win rate:             C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell5_core_only_revised_top_by_win_20200701_20260519_20260704_094614.csv
Win >=85 by frequency:       C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell5_core_only_revised_win85_by_frequency_20200701_20260519_20260704_094614.csv
Win >=85 by P&L/day:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell5_core_only_revised_win85_by_pnl_day_20200701_20260519_20260704_094614.csv
Core by VRP:                 C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell5_core_only_revised_by_vrp_20200701_20260519_20260704_094614.csv
Core by z-score:             C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell5_core_only_revised_by_z_20200701_20260519_20260704_094614.csv
Core by RSI:                 C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell5_core_only_revised_by_rsi_20200701_20260519_20260704_094614.csv
Core by RV21D:               C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell5_core_only_revised_by_rv21d_20200701_20260519_20260704_094614.csv

Cell 5 complete.

In [8]:
# Cell 6: Core-only revised Phase 2 sweep
#
# Approved scope:
#   - Core only.
#   - No Secondary.
#   - No sizing.
#   - No final lock.
#   - 3m z-score and 1y z-score are still tied within each bucket.
#
# Goal:
#   - Find Core parameter sets with win rate >= 85%.
#   - Then maximize Core frequency.
#   - Also report selection frequency and average P&L by exact selected tenor/DTE.
#
# User-approved grid:
#
#   Front 9D / 12D / 15D:
#       VRP:   [0.60, 0.70]
#       z:     [0.60, 0.70, 0.80]
#       RSI:   [69, 70, 71]
#       RV21D: [8.0, 8.5]
#
#   Middle 18D / 21D / 24D:
#       VRP:   [0.70]
#       z:     [0.75, 0.80]
#       RSI:   [67, 68, 69]
#       RV21D: [8.0, 8.5]
#
#   Back 27D / 30D / 33D:
#       VRP:   [0.70]
#       z:     [0.75, 0.80]
#       RSI:   [65, 66, 68]
#       RV21D: [8.0, 8.5]
#
# Constraints:
#   - For VRP / z / RV21D:
#         Front <= Middle <= Back
#   - For RSI cap:
#         Front >= Middle >= Back
#
# Expected valid grid size:
#   - VRP triples:   2
#   - z triples:     7
#   - RSI triples:   24
#   - RV21D triples: 4
#   - Total specs:   1,344
#
# Core selection logic:
#   - Apply thresholds across all 9 tenors.
#   - If no tenor passes on a date: no trade.
#   - If multiple tenors pass: select one tenor using old-process logic:
#       1. Prefer tenors with conditional sample size >= 20.
#       2. Highest conditional win probability.
#       3. Keep tenors within 25 bps of best win probability.
#       4. Highest conditional average P&L/day.
#       5. Highest conditional aggregate P&L/day.
#       6. Highest conditional win probability.
#       7. Longer tenor.
#
# P&L/day:
#   normalized_pnl_dollars / actual_dte if actual_dte is available.
#   Falls back to normalized_pnl_dollars / tenor if actual_dte is unavailable.

from pathlib import Path
import itertools
import numpy as np
import pandas as pd


# -----------------------------
# 1. Paths / load latest clean panel
# -----------------------------

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

PARAM_SWEEP_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "corsi_parameter_sweep_clean"
PARAM_SWEEP_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "corsi_parameter_sweep_clean"
CORSI_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "forecast_model_corsi_v1"

PARAM_SWEEP_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

RUN_TIMESTAMP = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")

clean_panel_candidates = sorted(
    PARAM_SWEEP_PROCESSED_DIR.glob("02_corsi_parameter_sweep_clean_panel_*.parquet")
)

if not clean_panel_candidates:
    raise FileNotFoundError(f"No clean panel found in {PARAM_SWEEP_PROCESSED_DIR}")

CLEAN_PANEL_PATH = clean_panel_candidates[-1]

print("Cell 6: Core-only revised Phase 2 sweep")
print(f"Clean panel path: {CLEAN_PANEL_PATH}")
print(f"Run timestamp:    {RUN_TIMESTAMP}")

panel = pd.read_parquet(CLEAN_PANEL_PATH).copy()

panel["date"] = pd.to_datetime(panel["date"]).dt.normalize()
panel["trade_date"] = pd.to_numeric(panel["trade_date"], errors="coerce").astype(int)
panel["tenor"] = pd.to_numeric(panel["tenor"], errors="coerce").astype(int)

required_panel_cols = [
    "date",
    "trade_date",
    "tenor",
    "tenor_bucket",
    "forecast_model",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rsi14",
    "rv21d",
    "outcome_value",
    "has_outcome",
    "is_parameter_sweep_eligible",
]

missing_panel_cols = [c for c in required_panel_cols if c not in panel.columns]

if missing_panel_cols:
    raise ValueError(f"Clean panel missing required columns: {missing_panel_cols}")


# -----------------------------
# 2. Actual DTE helper
# -----------------------------

def first_existing_col(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    return None


def load_actual_dte_lookup():
    outcome_discovery_candidates = sorted(
        CORSI_AUDIT_DIR.glob("corsi_cell11_trade_outcome_file_discovery_*.csv")
    )

    if not outcome_discovery_candidates:
        return None, "no_outcome_discovery_file"

    discovery_path = outcome_discovery_candidates[-1]
    discovery = pd.read_csv(discovery_path)
    discovery.columns = [str(c).strip() for c in discovery.columns]

    file_col = "chosen_file" if "chosen_file" in discovery.columns else "path"

    if file_col not in discovery.columns:
        return None, "discovery_missing_path_column"

    preferred = discovery.copy()

    if "eligible_for_backtest" in preferred.columns:
        preferred = preferred.loc[preferred["eligible_for_backtest"].astype(bool)].copy()

    if preferred.empty:
        return None, "no_eligible_outcome_files"

    if "score" in preferred.columns:
        preferred["_score"] = pd.to_numeric(preferred["score"], errors="coerce")
    else:
        preferred["_score"] = 0.0

    if "chosen_outcome_col" in preferred.columns:
        preferred["_preferred_pnl"] = preferred["chosen_outcome_col"].eq("normalized_pnl_dollars")
    elif "outcome_col" in preferred.columns:
        preferred["_preferred_pnl"] = preferred["outcome_col"].eq("normalized_pnl_dollars")
    else:
        preferred["_preferred_pnl"] = False

    preferred = preferred.sort_values(
        ["_preferred_pnl", "_score"],
        ascending=[False, False],
    )

    for _, row in preferred.iterrows():
        path = Path(row[file_col])

        if not path.exists():
            continue

        try:
            raw = pd.read_parquet(path) if path.suffix.lower() == ".parquet" else pd.read_csv(path)
        except Exception:
            continue

        raw.columns = [str(c).strip() for c in raw.columns]

        trade_date_col = first_existing_col(raw, ["trade_date", "trade_dt", "date"])
        tenor_col = first_existing_col(raw, ["tenor", "entry_tenor", "target_tenor"])
        actual_dte_col = first_existing_col(raw, ["actual_dte"])

        if trade_date_col is None or tenor_col is None or actual_dte_col is None:
            continue

        lookup = raw[[trade_date_col, tenor_col, actual_dte_col]].copy()
        lookup = lookup.rename(columns={
            trade_date_col: "trade_date",
            tenor_col: "tenor",
            actual_dte_col: "actual_dte_from_outcomes",
        })

        lookup["trade_date"] = pd.to_numeric(lookup["trade_date"], errors="coerce").astype("Int64")
        lookup["tenor"] = pd.to_numeric(lookup["tenor"], errors="coerce").astype("Int64")
        lookup["actual_dte_from_outcomes"] = pd.to_numeric(
            lookup["actual_dte_from_outcomes"],
            errors="coerce",
        )

        lookup = lookup.dropna(subset=["trade_date", "tenor"])
        lookup["trade_date"] = lookup["trade_date"].astype(int)
        lookup["tenor"] = lookup["tenor"].astype(int)
        lookup = lookup.drop_duplicates(["trade_date", "tenor"])

        return lookup, str(path)

    return None, "actual_dte_not_found_in_outcome_files"


if "actual_dte" not in panel.columns:
    actual_dte_lookup, actual_dte_source = load_actual_dte_lookup()

    if actual_dte_lookup is not None:
        panel = panel.merge(
            actual_dte_lookup,
            on=["trade_date", "tenor"],
            how="left",
            validate="many_to_one",
        )
        panel["actual_dte"] = panel["actual_dte_from_outcomes"]
        panel = panel.drop(columns=["actual_dte_from_outcomes"])
    else:
        panel["actual_dte"] = np.nan
else:
    actual_dte_source = "clean_panel_existing_actual_dte"

panel["actual_dte"] = pd.to_numeric(panel["actual_dte"], errors="coerce")
panel["actual_dte_for_pnl_day"] = panel["actual_dte"]

fallback_mask = (
    panel["actual_dte_for_pnl_day"].isna()
    | panel["actual_dte_for_pnl_day"].le(0)
)

panel.loc[fallback_mask, "actual_dte_for_pnl_day"] = panel.loc[fallback_mask, "tenor"]
panel["pnl_per_day"] = panel["outcome_value"] / panel["actual_dte_for_pnl_day"]

print()
print("Actual DTE source:")
print(actual_dte_source)

print()
print("Actual DTE availability:")
display(pd.DataFrame([{
    "rows": len(panel),
    "actual_dte_non_null": int(panel["actual_dte"].notna().sum()),
    "actual_dte_non_null_pct": float(panel["actual_dte"].notna().mean()),
    "fallback_to_tenor_rows": int(fallback_mask.sum()),
    "fallback_to_tenor_pct": float(fallback_mask.mean()),
}]))


# -----------------------------
# 3. Build Core-only Phase 2 grid
# -----------------------------

FRONT_GRID = {
    "vrp": [0.60, 0.70],
    "z": [0.60, 0.70, 0.80],
    "rsi": [69, 70, 71],
    "rv21d": [8.0, 8.5],
}

MIDDLE_GRID = {
    "vrp": [0.70],
    "z": [0.75, 0.80],
    "rsi": [67, 68, 69],
    "rv21d": [8.0, 8.5],
}

BACK_GRID = {
    "vrp": [0.70],
    "z": [0.75, 0.80],
    "rsi": [65, 66, 68],
    "rv21d": [8.0, 8.5],
}


def valid_increasing_triples(front_vals, middle_vals, back_vals):
    return [
        (f, m, b)
        for f, m, b in itertools.product(front_vals, middle_vals, back_vals)
        if f <= m <= b
    ]


def valid_rsi_triples(front_vals, middle_vals, back_vals):
    return [
        (f, m, b)
        for f, m, b in itertools.product(front_vals, middle_vals, back_vals)
        if f >= m >= b
    ]


CORE_VRP_TRIPLES = valid_increasing_triples(
    FRONT_GRID["vrp"],
    MIDDLE_GRID["vrp"],
    BACK_GRID["vrp"],
)

CORE_Z_TRIPLES = valid_increasing_triples(
    FRONT_GRID["z"],
    MIDDLE_GRID["z"],
    BACK_GRID["z"],
)

CORE_RSI_TRIPLES = valid_rsi_triples(
    FRONT_GRID["rsi"],
    MIDDLE_GRID["rsi"],
    BACK_GRID["rsi"],
)

CORE_RV21D_TRIPLES = valid_increasing_triples(
    FRONT_GRID["rv21d"],
    MIDDLE_GRID["rv21d"],
    BACK_GRID["rv21d"],
)

spec_rows = []

for spec_num, (vrp, z, rsi, rv21d) in enumerate(
    itertools.product(
        CORE_VRP_TRIPLES,
        CORE_Z_TRIPLES,
        CORE_RSI_TRIPLES,
        CORE_RV21D_TRIPLES,
    ),
    start=1,
):
    spec_id = (
        f"core_phase2_"
        f"vrp_{vrp[0]:.2f}_{vrp[1]:.2f}_{vrp[2]:.2f}_"
        f"z_{z[0]:.2f}_{z[1]:.2f}_{z[2]:.2f}_"
        f"rsi_{int(rsi[0])}_{int(rsi[1])}_{int(rsi[2])}_"
        f"rv21d_{rv21d[0]:.1f}_{rv21d[1]:.1f}_{rv21d[2]:.1f}"
    )

    spec_rows.append({
        "spec_id": spec_id,
        "role": "Core",
        "phase": "core_only_phase2",
        "forecast_denominator": "har_total_simple",

        "front_vrp_log_min": vrp[0],
        "middle_vrp_log_min": vrp[1],
        "back_vrp_log_min": vrp[2],

        "front_z_3m_min": z[0],
        "middle_z_3m_min": z[1],
        "back_z_3m_min": z[2],

        "front_z_1y_min": z[0],
        "middle_z_1y_min": z[1],
        "back_z_1y_min": z[2],

        "front_rsi14_max": rsi[0],
        "middle_rsi14_max": rsi[1],
        "back_rsi14_max": rsi[2],

        "front_rv21d_min": rv21d[0],
        "middle_rv21d_min": rv21d[1],
        "back_rv21d_min": rv21d[2],

        "phase_z_3m_equals_z_1y": True,
    })

core_specs = pd.DataFrame(spec_rows)

grid_summary = pd.DataFrame([{
    "valid_vrp_triples": len(CORE_VRP_TRIPLES),
    "valid_z_triples": len(CORE_Z_TRIPLES),
    "valid_rsi_triples": len(CORE_RSI_TRIPLES),
    "valid_rv21d_triples": len(CORE_RV21D_TRIPLES),
    "total_core_specs": len(core_specs),
}])

print()
print("Core-only Phase 2 grid summary:")
display(grid_summary)

print()
print("Core-only Phase 2 specs sample:")
display(core_specs.head(20))


# -----------------------------
# 4. Build complete eligible matrix panel
# -----------------------------

TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

TENOR_BUCKET_MAP = {
    9: "front",
    12: "front",
    15: "front",
    18: "middle",
    21: "middle",
    24: "middle",
    27: "back",
    30: "back",
    33: "back",
}

BUCKETS = ["front", "middle", "back"]
WIN_BAND = 0.0025
MIN_CONDITIONAL_OBS = 20

eligible = panel.loc[panel["is_parameter_sweep_eligible"].astype(bool)].copy()
eligible = eligible.replace([np.inf, -np.inf], np.nan)

needed_for_matrix = [
    "trade_date",
    "date",
    "tenor",
    "tenor_bucket",
    "forecast_model",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rsi14",
    "rv21d",
    "outcome_value",
    "actual_dte_for_pnl_day",
    "pnl_per_day",
]

eligible = eligible.dropna(subset=needed_for_matrix).copy()

eligible = eligible.loc[
    eligible["tenor"].isin(TENORS)
    & eligible["actual_dte_for_pnl_day"].gt(0)
].copy()

duplicate_rows = eligible.duplicated(["trade_date", "tenor"]).sum()

if duplicate_rows:
    raise ValueError(f"Eligible panel has duplicate trade_date x tenor rows: {duplicate_rows}")

date_counts = eligible.groupby("trade_date")["tenor"].nunique()
complete_dates = date_counts.loc[date_counts.eq(len(TENORS))].index.tolist()

eligible = eligible.loc[eligible["trade_date"].isin(complete_dates)].copy()

eligible_dates = sorted(eligible["trade_date"].unique())
num_dates = len(eligible_dates)
num_tenors = len(TENORS)

date_lookup = (
    eligible[["trade_date", "date"]]
    .drop_duplicates("trade_date")
    .set_index("trade_date")
    .loc[eligible_dates]
)

date_array = date_lookup["date"].to_numpy()


def pivot_matrix(col, dtype=float):
    mat = (
        eligible
        .pivot(index="trade_date", columns="tenor", values=col)
        .reindex(index=eligible_dates, columns=TENORS)
    )

    if mat.isna().any().any():
        missing = int(mat.isna().sum().sum())
        raise ValueError(f"Matrix for {col} has missing cells after complete-date filter: {missing}")

    return mat.to_numpy(dtype=dtype)


vrp_mat = pivot_matrix("vrp_log")
z3m_mat = pivot_matrix("vrp_z_3m")
z1y_mat = pivot_matrix("vrp_z_1y")
rsi_mat = pivot_matrix("rsi14")
rv21d_mat = pivot_matrix("rv21d")
pnl_mat = pivot_matrix("outcome_value")
actual_dte_mat = pivot_matrix("actual_dte_for_pnl_day")
pnl_per_day_mat = pivot_matrix("pnl_per_day")

valid_outcome_mat = (
    np.isfinite(pnl_mat)
    & np.isfinite(pnl_per_day_mat)
    & np.isfinite(actual_dte_mat)
)

tenor_array = np.array(TENORS, dtype=int)
tenor_bucket_array = np.array([TENOR_BUCKET_MAP[int(t)] for t in tenor_array], dtype=object)

print()
print("Cell 6 input summary:")
display(pd.DataFrame([{
    "eligible_rows_after_complete_date_filter": len(eligible),
    "eligible_dates": num_dates,
    "first_date": pd.to_datetime(date_array.min()),
    "last_date": pd.to_datetime(date_array.max()),
    "unique_tenors": num_tenors,
    "core_specs_to_test": len(core_specs),
    "win_band_bps": WIN_BAND * 10000,
    "min_conditional_obs": MIN_CONDITIONAL_OBS,
    "forecast_model": ", ".join(sorted(eligible["forecast_model"].astype(str).unique())),
}]))


# -----------------------------
# 5. Matrix helper functions
# -----------------------------

def threshold_array_for_spec(spec_row, field_suffix):
    vals = []

    for tenor in TENORS:
        bucket = TENOR_BUCKET_MAP[int(tenor)]
        vals.append(float(spec_row[f"{bucket}_{field_suffix}"]))

    return np.array(vals, dtype=float)


def build_pass_matrix(spec_row):
    vrp_threshold = threshold_array_for_spec(spec_row, "vrp_log_min")
    z3m_threshold = threshold_array_for_spec(spec_row, "z_3m_min")
    z1y_threshold = threshold_array_for_spec(spec_row, "z_1y_min")
    rsi_cap = threshold_array_for_spec(spec_row, "rsi14_max")
    rv21d_floor = threshold_array_for_spec(spec_row, "rv21d_min")

    return (
        (vrp_mat >= vrp_threshold[None, :])
        & (z3m_mat >= z3m_threshold[None, :])
        & (z1y_mat >= z1y_threshold[None, :])
        & (rsi_mat <= rsi_cap[None, :])
        & (rv21d_mat >= rv21d_floor[None, :])
        & valid_outcome_mat
    )


def compute_conditional_arrays(pass_matrix):
    obs = pass_matrix.sum(axis=0).astype(float)
    wins = ((pnl_mat > 0) & pass_matrix).sum(axis=0).astype(float)

    total_pnl = np.where(
        obs > 0,
        np.where(pass_matrix, pnl_mat, 0.0).sum(axis=0),
        0.0,
    )

    total_pnl_day = np.where(
        obs > 0,
        np.where(pass_matrix, pnl_per_day_mat, 0.0).sum(axis=0),
        np.nan,
    )

    total_dte = np.where(
        obs > 0,
        np.where(pass_matrix, actual_dte_mat, 0.0).sum(axis=0),
        np.nan,
    )

    win_prob = np.divide(
        wins,
        obs,
        out=np.full_like(obs, np.nan, dtype=float),
        where=obs > 0,
    )

    avg_pnl_per_day = np.divide(
        total_pnl_day,
        obs,
        out=np.full_like(obs, np.nan, dtype=float),
        where=obs > 0,
    )

    avg_pnl_per_trade = np.divide(
        total_pnl,
        obs,
        out=np.full_like(obs, np.nan, dtype=float),
        where=obs > 0,
    )

    aggregate_pnl_per_day = np.divide(
        total_pnl,
        total_dte,
        out=np.full_like(obs, np.nan, dtype=float),
        where=total_dte > 0,
    )

    worst_trade = np.full(num_tenors, np.nan)
    worst_pnl_day = np.full(num_tenors, np.nan)
    avg_actual_dte = np.full(num_tenors, np.nan)

    for col_idx in range(num_tenors):
        mask = pass_matrix[:, col_idx]

        if mask.any():
            worst_trade[col_idx] = np.nanmin(pnl_mat[mask, col_idx])
            worst_pnl_day[col_idx] = np.nanmin(pnl_per_day_mat[mask, col_idx])
            avg_actual_dte[col_idx] = np.nanmean(actual_dte_mat[mask, col_idx])

    sample_ok = obs >= MIN_CONDITIONAL_OBS

    return {
        "obs": obs,
        "wins": wins,
        "win_prob": win_prob,
        "avg_pnl_per_day": avg_pnl_per_day,
        "aggregate_pnl_per_day": aggregate_pnl_per_day,
        "avg_pnl_per_trade": avg_pnl_per_trade,
        "total_pnl": total_pnl,
        "worst_trade": worst_trade,
        "worst_pnl_day": worst_pnl_day,
        "avg_actual_dte": avg_actual_dte,
        "sample_ok": sample_ok,
    }


def select_cols_from_pass_and_stats(pass_matrix, stats):
    obs = stats["obs"]
    win = stats["win_prob"]
    avg_day = stats["avg_pnl_per_day"]
    agg_day = stats["aggregate_pnl_per_day"]
    sample_ok = stats["sample_ok"]

    has_stats = (
        (obs > 0)
        & np.isfinite(win)
        & np.isfinite(avg_day)
        & np.isfinite(agg_day)
    )

    active = pass_matrix & has_stats[None, :]

    active_sample_ok = active & sample_ok[None, :]
    row_has_sample_ok = active_sample_ok.any(axis=1)

    ranking_universe = np.where(
        row_has_sample_ok[:, None],
        active_sample_ok,
        active,
    )

    win_masked = np.where(
        ranking_universe,
        win[None, :],
        -np.inf,
    )

    best_win = win_masked.max(axis=1)
    row_has_any = np.isfinite(best_win)

    inside_win_band = (
        ranking_universe
        & row_has_any[:, None]
        & (win[None, :] >= (best_win[:, None] - WIN_BAND))
    )

    selected_col = np.full(num_dates, -1, dtype=int)

    best_avg = np.full(num_dates, -np.inf)
    best_agg = np.full(num_dates, -np.inf)
    best_win_for_tie = np.full(num_dates, -np.inf)
    best_tenor = np.full(num_dates, -np.inf)

    for col_idx, tenor in enumerate(TENORS):
        cand = inside_win_band[:, col_idx]

        avg_val = avg_day[col_idx]
        agg_val = agg_day[col_idx]
        win_val = win[col_idx]
        tenor_val = float(tenor)

        better = (
            cand
            & (
                (avg_val > best_avg)
                | ((avg_val == best_avg) & (agg_val > best_agg))
                | ((avg_val == best_avg) & (agg_val == best_agg) & (win_val > best_win_for_tie))
                | ((avg_val == best_avg) & (agg_val == best_agg) & (win_val == best_win_for_tie) & (tenor_val > best_tenor))
            )
        )

        selected_col[better] = col_idx
        best_avg[better] = avg_val
        best_agg[better] = agg_val
        best_win_for_tie[better] = win_val
        best_tenor[better] = tenor_val

    return selected_col


def profit_factor(values):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]

    if values.size == 0:
        return np.nan

    gains = values[values > 0].sum()
    losses = values[values < 0].sum()

    if losses < 0:
        return gains / abs(losses)

    if gains > 0 and losses == 0:
        return np.inf

    return np.nan


def summarize_selected_cols(selected_cols, prefix):
    selected_cols = np.asarray(selected_cols, dtype=int)
    date_idx = np.where(selected_cols >= 0)[0]

    if date_idx.size == 0:
        return {
            f"{prefix}_trades": 0,
            f"{prefix}_frequency": 0.0,
            f"{prefix}_win_rate": np.nan,
            f"{prefix}_total_pnl": 0.0,
            f"{prefix}_avg_pnl_per_trade": np.nan,
            f"{prefix}_avg_pnl_per_day": np.nan,
            f"{prefix}_exposure_day_weighted_pnl_per_day": np.nan,
            f"{prefix}_profit_factor": np.nan,
            f"{prefix}_worst_trade_pnl": np.nan,
            f"{prefix}_worst_pnl_per_day": np.nan,
            f"{prefix}_best_trade_pnl": np.nan,
            f"{prefix}_avg_actual_dte": np.nan,
            f"{prefix}_avg_selected_tenor": np.nan,
        }

    cols = selected_cols[date_idx]

    pnl = pnl_mat[date_idx, cols]
    pnl_day = pnl_per_day_mat[date_idx, cols]
    dte = actual_dte_mat[date_idx, cols]
    selected_tenors = tenor_array[cols]

    total_dte = np.nansum(dte)

    if total_dte > 0:
        exposure_day_weighted_pnl_per_day = np.nansum(pnl) / total_dte
    else:
        exposure_day_weighted_pnl_per_day = np.nan

    return {
        f"{prefix}_trades": int(date_idx.size),
        f"{prefix}_frequency": float(date_idx.size / num_dates) if num_dates else np.nan,
        f"{prefix}_win_rate": float(np.nanmean(pnl > 0)),
        f"{prefix}_total_pnl": float(np.nansum(pnl)),
        f"{prefix}_avg_pnl_per_trade": float(np.nanmean(pnl)),
        f"{prefix}_avg_pnl_per_day": float(np.nanmean(pnl_day)),
        f"{prefix}_exposure_day_weighted_pnl_per_day": float(exposure_day_weighted_pnl_per_day),
        f"{prefix}_profit_factor": float(profit_factor(pnl)),
        f"{prefix}_worst_trade_pnl": float(np.nanmin(pnl)),
        f"{prefix}_worst_pnl_per_day": float(np.nanmin(pnl_day)),
        f"{prefix}_best_trade_pnl": float(np.nanmax(pnl)),
        f"{prefix}_avg_actual_dte": float(np.nanmean(dte)),
        f"{prefix}_avg_selected_tenor": float(np.nanmean(selected_tenors)),
    }


def bucket_metrics(selected_cols):
    selected_cols = np.asarray(selected_cols, dtype=int)
    date_idx = np.where(selected_cols >= 0)[0]

    out = {}

    for bucket in BUCKETS:
        out[f"{bucket}_selected_trades"] = 0
        out[f"{bucket}_selected_win_rate"] = np.nan
        out[f"{bucket}_selected_avg_pnl_per_trade"] = np.nan
        out[f"{bucket}_selected_avg_pnl_per_day"] = np.nan
        out[f"{bucket}_selected_exposure_day_weighted_pnl_per_day"] = np.nan
        out[f"{bucket}_selected_total_pnl"] = 0.0
        out[f"{bucket}_selected_worst_trade_pnl"] = np.nan

    if date_idx.size == 0:
        return out

    cols = selected_cols[date_idx]
    selected_buckets = tenor_bucket_array[cols]

    for bucket in BUCKETS:
        bucket_mask = selected_buckets == bucket

        if not bucket_mask.any():
            continue

        bucket_date_idx = date_idx[bucket_mask]
        bucket_cols = cols[bucket_mask]

        pnl = pnl_mat[bucket_date_idx, bucket_cols]
        pnl_day = pnl_per_day_mat[bucket_date_idx, bucket_cols]
        dte = actual_dte_mat[bucket_date_idx, bucket_cols]

        total_dte = np.nansum(dte)

        out[f"{bucket}_selected_trades"] = int(bucket_mask.sum())
        out[f"{bucket}_selected_win_rate"] = float(np.nanmean(pnl > 0))
        out[f"{bucket}_selected_avg_pnl_per_trade"] = float(np.nanmean(pnl))
        out[f"{bucket}_selected_avg_pnl_per_day"] = float(np.nanmean(pnl_day))
        out[f"{bucket}_selected_exposure_day_weighted_pnl_per_day"] = (
            float(np.nansum(pnl) / total_dte) if total_dte > 0 else np.nan
        )
        out[f"{bucket}_selected_total_pnl"] = float(np.nansum(pnl))
        out[f"{bucket}_selected_worst_trade_pnl"] = float(np.nanmin(pnl))

    return out


def tenor_selection_metrics(selected_cols, spec_id):
    selected_cols = np.asarray(selected_cols, dtype=int)
    date_idx_all = np.where(selected_cols >= 0)[0]

    rows = []

    for col_idx, tenor in enumerate(TENORS):
        tenor_mask = selected_cols == col_idx
        date_idx = np.where(tenor_mask)[0]

        if date_idx.size == 0:
            rows.append({
                "spec_id": spec_id,
                "selected_tenor": int(tenor),
                "selected_tenor_bucket": TENOR_BUCKET_MAP[int(tenor)],
                "selected_trades": 0,
                "selected_frequency_total_dates": 0.0,
                "selected_share_of_trades": 0.0,
                "selected_win_rate": np.nan,
                "selected_avg_pnl_per_trade": np.nan,
                "selected_avg_pnl_per_day": np.nan,
                "selected_exposure_day_weighted_pnl_per_day": np.nan,
                "selected_total_pnl": 0.0,
                "selected_worst_trade_pnl": np.nan,
                "selected_worst_pnl_per_day": np.nan,
                "selected_avg_actual_dte": np.nan,
            })
            continue

        pnl = pnl_mat[date_idx, col_idx]
        pnl_day = pnl_per_day_mat[date_idx, col_idx]
        dte = actual_dte_mat[date_idx, col_idx]

        total_dte = np.nansum(dte)

        rows.append({
            "spec_id": spec_id,
            "selected_tenor": int(tenor),
            "selected_tenor_bucket": TENOR_BUCKET_MAP[int(tenor)],
            "selected_trades": int(date_idx.size),
            "selected_frequency_total_dates": float(date_idx.size / num_dates) if num_dates else np.nan,
            "selected_share_of_trades": float(date_idx.size / date_idx_all.size) if date_idx_all.size else 0.0,
            "selected_win_rate": float(np.nanmean(pnl > 0)),
            "selected_avg_pnl_per_trade": float(np.nanmean(pnl)),
            "selected_avg_pnl_per_day": float(np.nanmean(pnl_day)),
            "selected_exposure_day_weighted_pnl_per_day": (
                float(np.nansum(pnl) / total_dte) if total_dte > 0 else np.nan
            ),
            "selected_total_pnl": float(np.nansum(pnl)),
            "selected_worst_trade_pnl": float(np.nanmin(pnl)),
            "selected_worst_pnl_per_day": float(np.nanmin(pnl_day)),
            "selected_avg_actual_dte": float(np.nanmean(dte)),
        })

    return rows


def append_conditional_rows(rows, spec_id, stats):
    for col_idx, tenor in enumerate(TENORS):
        rows.append({
            "spec_id": spec_id,
            "role": "Core",
            "tenor": int(tenor),
            "tenor_bucket": TENOR_BUCKET_MAP[int(tenor)],
            "conditional_obs": int(stats["obs"][col_idx]),
            "conditional_wins": int(stats["wins"][col_idx]),
            "conditional_win_probability": stats["win_prob"][col_idx],
            "conditional_avg_pnl_per_day": stats["avg_pnl_per_day"][col_idx],
            "conditional_aggregate_pnl_per_day": stats["aggregate_pnl_per_day"][col_idx],
            "conditional_avg_pnl_per_trade": stats["avg_pnl_per_trade"][col_idx],
            "conditional_total_pnl": stats["total_pnl"][col_idx],
            "conditional_worst_trade_pnl": stats["worst_trade"][col_idx],
            "conditional_worst_pnl_per_day": stats["worst_pnl_day"][col_idx],
            "conditional_avg_actual_dte": stats["avg_actual_dte"][col_idx],
            "conditional_sample_ok": bool(stats["sample_ok"][col_idx]),
        })


# -----------------------------
# 6. Run Core-only Phase 2 sweep
# -----------------------------

summary_rows = []
conditional_rows = []
tenor_selection_rows = []

total_specs = len(core_specs)

print()
print(f"Running Core-only Phase 2 sweep: {total_specs:,} specs")

for i, (_, spec_row) in enumerate(core_specs.iterrows(), start=1):
    spec_id = spec_row["spec_id"]

    pass_matrix = build_pass_matrix(spec_row)
    candidate_dates = pass_matrix.any(axis=1)
    candidate_rows = int(pass_matrix.sum())

    stats = compute_conditional_arrays(pass_matrix)
    selected_cols = select_cols_from_pass_and_stats(pass_matrix, stats)

    row = {
        "spec_id": spec_id,
        "role": "Core",
        "phase": "core_only_phase2",
        "candidate_rows": candidate_rows,
        "candidate_dates": int(candidate_dates.sum()),
        "candidate_frequency": float(candidate_dates.sum() / num_dates) if num_dates else np.nan,

        "front_vrp_log_min": spec_row["front_vrp_log_min"],
        "middle_vrp_log_min": spec_row["middle_vrp_log_min"],
        "back_vrp_log_min": spec_row["back_vrp_log_min"],

        "front_z_3m_min": spec_row["front_z_3m_min"],
        "middle_z_3m_min": spec_row["middle_z_3m_min"],
        "back_z_3m_min": spec_row["back_z_3m_min"],

        "front_z_1y_min": spec_row["front_z_1y_min"],
        "middle_z_1y_min": spec_row["middle_z_1y_min"],
        "back_z_1y_min": spec_row["back_z_1y_min"],

        "front_rsi14_max": spec_row["front_rsi14_max"],
        "middle_rsi14_max": spec_row["middle_rsi14_max"],
        "back_rsi14_max": spec_row["back_rsi14_max"],

        "front_rv21d_min": spec_row["front_rv21d_min"],
        "middle_rv21d_min": spec_row["middle_rv21d_min"],
        "back_rv21d_min": spec_row["back_rv21d_min"],
    }

    row.update(summarize_selected_cols(selected_cols, "core"))
    row.update(bucket_metrics(selected_cols))

    summary_rows.append(row)
    append_conditional_rows(conditional_rows, spec_id, stats)
    tenor_selection_rows.extend(tenor_selection_metrics(selected_cols, spec_id))

    if i % 250 == 0 or i == total_specs:
        print(f"Core specs processed: {i:,} / {total_specs:,}")

core_summary = pd.DataFrame(summary_rows)
conditional_stats = pd.DataFrame(conditional_rows)
tenor_selection_summary = pd.DataFrame(tenor_selection_rows)


# -----------------------------
# 7. Add labels / flags / rankings
# -----------------------------

core_summary["vrp_triple"] = (
    core_summary["front_vrp_log_min"].map("{:.2f}".format)
    + " / "
    + core_summary["middle_vrp_log_min"].map("{:.2f}".format)
    + " / "
    + core_summary["back_vrp_log_min"].map("{:.2f}".format)
)

core_summary["z_triple"] = (
    core_summary["front_z_3m_min"].map("{:.2f}".format)
    + " / "
    + core_summary["middle_z_3m_min"].map("{:.2f}".format)
    + " / "
    + core_summary["back_z_3m_min"].map("{:.2f}".format)
)

core_summary["rsi_triple"] = (
    core_summary["front_rsi14_max"].astype(int).astype(str)
    + " / "
    + core_summary["middle_rsi14_max"].astype(int).astype(str)
    + " / "
    + core_summary["back_rsi14_max"].astype(int).astype(str)
)

core_summary["rv21d_triple"] = (
    core_summary["front_rv21d_min"].map("{:.1f}".format)
    + " / "
    + core_summary["middle_rv21d_min"].map("{:.1f}".format)
    + " / "
    + core_summary["back_rv21d_min"].map("{:.1f}".format)
)

core_summary["meets_core_win_85"] = core_summary["core_win_rate"].ge(0.85)
core_summary["meets_core_win_82"] = core_summary["core_win_rate"].ge(0.82)
core_summary["meets_core_win_80"] = core_summary["core_win_rate"].ge(0.80)

core_summary["core_win_gap_to_85"] = 0.85 - core_summary["core_win_rate"]

core_summary_by_win = core_summary.sort_values(
    [
        "core_win_rate",
        "core_frequency",
        "core_avg_pnl_per_day",
        "core_total_pnl",
    ],
    ascending=[False, False, False, False],
).reset_index(drop=True)

core_summary_by_win["win_rate_rank"] = np.arange(1, len(core_summary_by_win) + 1)

core_summary_by_frequency_targets_first = core_summary.sort_values(
    [
        "meets_core_win_85",
        "core_frequency",
        "core_win_rate",
        "core_avg_pnl_per_day",
        "core_total_pnl",
        "core_worst_trade_pnl",
    ],
    ascending=[False, False, False, False, False, False],
).reset_index(drop=True)

core_summary_by_frequency_targets_first["frequency_rank_with_targets_first"] = (
    np.arange(1, len(core_summary_by_frequency_targets_first) + 1)
)

core_review = core_summary.merge(
    core_summary_by_win[["spec_id", "win_rate_rank"]],
    on="spec_id",
    how="left",
    validate="one_to_one",
)

core_review = core_review.merge(
    core_summary_by_frequency_targets_first[["spec_id", "frequency_rank_with_targets_first"]],
    on="spec_id",
    how="left",
    validate="one_to_one",
)


# -----------------------------
# 8. Parameter group diagnostics
# -----------------------------

def parameter_group_summary(df, group_col):
    out = (
        df
        .groupby(group_col)
        .agg(
            specs=("spec_id", "nunique"),
            max_core_win_rate=("core_win_rate", "max"),
            median_core_win_rate=("core_win_rate", "median"),
            max_core_frequency=("core_frequency", "max"),
            median_core_frequency=("core_frequency", "median"),
            max_core_avg_pnl_per_day=("core_avg_pnl_per_day", "max"),
            median_core_avg_pnl_per_day=("core_avg_pnl_per_day", "median"),
            max_core_total_pnl=("core_total_pnl", "max"),
            specs_core_win_85_plus=("meets_core_win_85", "sum"),
            specs_core_win_82_plus=("meets_core_win_82", "sum"),
            specs_core_win_80_plus=("meets_core_win_80", "sum"),
        )
        .reset_index()
        .sort_values(
            [
                "max_core_win_rate",
                "max_core_frequency",
                "max_core_avg_pnl_per_day",
            ],
            ascending=[False, False, False],
        )
    )

    return out


core_by_vrp = parameter_group_summary(core_review, "vrp_triple")
core_by_z = parameter_group_summary(core_review, "z_triple")
core_by_rsi = parameter_group_summary(core_review, "rsi_triple")
core_by_rv21d = parameter_group_summary(core_review, "rv21d_triple")


# -----------------------------
# 9. Tenor diagnostics for top specs
# -----------------------------

def tenor_table_for_specs(spec_ids):
    out = tenor_selection_summary.loc[
        tenor_selection_summary["spec_id"].isin(spec_ids)
    ].merge(
        core_review[
            [
                "spec_id",
                "win_rate_rank",
                "frequency_rank_with_targets_first",
                "core_trades",
                "core_frequency",
                "core_win_rate",
                "core_avg_pnl_per_day",
                "core_total_pnl",
                "vrp_triple",
                "z_triple",
                "rsi_triple",
                "rv21d_triple",
            ]
        ],
        on="spec_id",
        how="left",
        validate="many_to_one",
    )

    return out.sort_values(
        ["win_rate_rank", "selected_tenor"],
        ascending=[True, True],
    )


top_win_spec_ids = (
    core_review
    .sort_values(
        ["core_win_rate", "core_frequency", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(20)["spec_id"]
    .tolist()
)

target_frequency_spec_ids = (
    core_review
    .loc[core_review["meets_core_win_85"]]
    .sort_values(
        ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(20)["spec_id"]
    .tolist()
)

above_82_frequency_spec_ids = (
    core_review
    .loc[core_review["core_win_rate"].ge(0.82)]
    .sort_values(
        ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(20)["spec_id"]
    .tolist()
)

tenor_top_win = tenor_table_for_specs(top_win_spec_ids)
tenor_target_frequency = tenor_table_for_specs(target_frequency_spec_ids)
tenor_above_82_frequency = tenor_table_for_specs(above_82_frequency_spec_ids)


# -----------------------------
# 10. Display outputs
# -----------------------------

print()
print("Core-only Phase 2 sweep summary:")
display(pd.DataFrame([{
    "core_specs_tested": len(core_review),
    "specs_core_win_85_plus": int(core_review["meets_core_win_85"].sum()),
    "specs_core_win_82_plus": int(core_review["meets_core_win_82"].sum()),
    "specs_core_win_80_plus": int(core_review["meets_core_win_80"].sum()),
    "max_core_win_rate": core_review["core_win_rate"].max(),
    "median_core_win_rate": core_review["core_win_rate"].median(),
    "max_core_frequency": core_review["core_frequency"].max(),
    "median_core_frequency": core_review["core_frequency"].median(),
    "max_core_avg_pnl_per_day": core_review["core_avg_pnl_per_day"].max(),
    "median_core_avg_pnl_per_day": core_review["core_avg_pnl_per_day"].median(),
}]))

review_cols = [
    "frequency_rank_with_targets_first",
    "win_rate_rank",
    "meets_core_win_85",
    "core_trades",
    "core_frequency",
    "core_win_rate",
    "core_win_gap_to_85",
    "core_avg_pnl_per_trade",
    "core_avg_pnl_per_day",
    "core_exposure_day_weighted_pnl_per_day",
    "core_total_pnl",
    "core_profit_factor",
    "core_worst_trade_pnl",
    "core_worst_pnl_per_day",
    "core_avg_actual_dte",
    "core_avg_selected_tenor",

    "front_selected_trades",
    "front_selected_win_rate",
    "front_selected_avg_pnl_per_trade",
    "front_selected_avg_pnl_per_day",
    "front_selected_total_pnl",
    "front_selected_worst_trade_pnl",

    "middle_selected_trades",
    "middle_selected_win_rate",
    "middle_selected_avg_pnl_per_trade",
    "middle_selected_avg_pnl_per_day",
    "middle_selected_total_pnl",
    "middle_selected_worst_trade_pnl",

    "back_selected_trades",
    "back_selected_win_rate",
    "back_selected_avg_pnl_per_trade",
    "back_selected_avg_pnl_per_day",
    "back_selected_total_pnl",
    "back_selected_worst_trade_pnl",

    "vrp_triple",
    "z_triple",
    "rsi_triple",
    "rv21d_triple",
    "spec_id",
]

tenor_cols = [
    "win_rate_rank",
    "frequency_rank_with_targets_first",
    "core_trades",
    "core_frequency",
    "core_win_rate",
    "core_avg_pnl_per_day",
    "core_total_pnl",

    "selected_tenor",
    "selected_tenor_bucket",
    "selected_trades",
    "selected_frequency_total_dates",
    "selected_share_of_trades",
    "selected_win_rate",
    "selected_avg_pnl_per_trade",
    "selected_avg_pnl_per_day",
    "selected_exposure_day_weighted_pnl_per_day",
    "selected_total_pnl",
    "selected_worst_trade_pnl",
    "selected_worst_pnl_per_day",
    "selected_avg_actual_dte",

    "vrp_triple",
    "z_triple",
    "rsi_triple",
    "rv21d_triple",
    "spec_id",
]

print()
print("Top Core specs by win rate:")
display(
    core_review
    .sort_values(
        ["core_win_rate", "core_frequency", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    [review_cols]
    .head(100)
)

print()
print("Top Core specs with win rate >= 85%, ranked by frequency:")
display(
    core_review
    .loc[core_review["meets_core_win_85"], review_cols]
    .sort_values(
        ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(100)
)

print()
print("Top Core specs with win rate >= 85%, ranked by average P&L/day:")
display(
    core_review
    .loc[core_review["meets_core_win_85"], review_cols]
    .sort_values(
        ["core_avg_pnl_per_day", "core_frequency", "core_win_rate", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(100)
)

print()
print("Highest-frequency Core specs with win rate >= 82%:")
display(
    core_review
    .loc[core_review["core_win_rate"].ge(0.82), review_cols]
    .sort_values(
        ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(100)
)

print()
print("Tenor / DTE selection diagnostics for top Core specs by win rate:")
display(tenor_top_win[tenor_cols].head(180))

print()
print("Tenor / DTE selection diagnostics for Core specs with win rate >= 85%, ranked by frequency:")
display(tenor_target_frequency[tenor_cols].head(180))

print()
print("Tenor / DTE selection diagnostics for highest-frequency Core specs with win rate >= 82%:")
display(tenor_above_82_frequency[tenor_cols].head(180))

print()
print("Core parameter diagnostics by VRP triple:")
display(core_by_vrp)

print()
print("Core parameter diagnostics by z-score triple:")
display(core_by_z)

print()
print("Core parameter diagnostics by RSI cap triple:")
display(core_by_rsi)

print()
print("Core parameter diagnostics by RV21D floor triple:")
display(core_by_rv21d)


# -----------------------------
# 11. Save outputs
# -----------------------------

safe_start = pd.to_datetime(date_array.min()).strftime("%Y%m%d")
safe_end = pd.to_datetime(date_array.max()).strftime("%Y%m%d")

core_specs_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_specs_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

grid_summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_grid_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

conditional_stats_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_conditional_stats_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

tenor_selection_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_tenor_selection_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

top_by_win_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_top_by_win_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

target_by_frequency_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_win85_by_frequency_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

target_by_pnl_day_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_win85_by_pnl_day_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

above_82_frequency_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_win82_by_frequency_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

tenor_top_win_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_tenor_top_by_win_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

tenor_target_frequency_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_tenor_win85_by_frequency_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

tenor_above_82_frequency_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_tenor_win82_by_frequency_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_vrp_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_by_vrp_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_z_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_by_z_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_rsi_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_by_rsi_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_rv21d_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell6_core_only_phase2_by_rv21d_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_specs.to_csv(core_specs_path, index=False)
grid_summary.to_csv(grid_summary_path, index=False)
core_review.to_csv(core_summary_path, index=False)
conditional_stats.to_csv(conditional_stats_path, index=False)
tenor_selection_summary.to_csv(tenor_selection_path, index=False)

core_review.sort_values(
    ["core_win_rate", "core_frequency", "core_avg_pnl_per_day", "core_total_pnl"],
    ascending=[False, False, False, False],
).head(1000).to_csv(top_by_win_path, index=False)

core_review.loc[
    core_review["meets_core_win_85"]
].sort_values(
    ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
    ascending=[False, False, False, False],
).to_csv(target_by_frequency_path, index=False)

core_review.loc[
    core_review["meets_core_win_85"]
].sort_values(
    ["core_avg_pnl_per_day", "core_frequency", "core_win_rate", "core_total_pnl"],
    ascending=[False, False, False, False],
).to_csv(target_by_pnl_day_path, index=False)

core_review.loc[
    core_review["core_win_rate"].ge(0.82)
].sort_values(
    ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
    ascending=[False, False, False, False],
).to_csv(above_82_frequency_path, index=False)

tenor_top_win.to_csv(tenor_top_win_path, index=False)
tenor_target_frequency.to_csv(tenor_target_frequency_path, index=False)
tenor_above_82_frequency.to_csv(tenor_above_82_frequency_path, index=False)

core_by_vrp.to_csv(core_by_vrp_path, index=False)
core_by_z.to_csv(core_by_z_path, index=False)
core_by_rsi.to_csv(core_by_rsi_path, index=False)
core_by_rv21d.to_csv(core_by_rv21d_path, index=False)

print()
print("Cell 6 outputs saved:")
print(f"Core specs:                    {core_specs_path}")
print(f"Grid summary:                  {grid_summary_path}")
print(f"Core summary:                  {core_summary_path}")
print(f"Conditional stats:             {conditional_stats_path}")
print(f"Tenor selection summary:       {tenor_selection_path}")
print(f"Top by win rate:               {top_by_win_path}")
print(f"Win >=85 by frequency:         {target_by_frequency_path}")
print(f"Win >=85 by P&L/day:           {target_by_pnl_day_path}")
print(f"Win >=82 by frequency:         {above_82_frequency_path}")
print(f"Tenor top by win:              {tenor_top_win_path}")
print(f"Tenor win >=85 by frequency:   {tenor_target_frequency_path}")
print(f"Tenor win >=82 by frequency:   {tenor_above_82_frequency_path}")
print(f"Core by VRP:                   {core_by_vrp_path}")
print(f"Core by z-score:               {core_by_z_path}")
print(f"Core by RSI:                   {core_by_rsi_path}")
print(f"Core by RV21D:                 {core_by_rv21d_path}")

print()
print("Cell 6 complete.")

Cell 6: Core-only revised Phase 2 sweep
Clean panel path: C:\Users\patri\vrp_project\data\processed\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_panel_20200102_20260623_20260704_085138.parquet
Run timestamp:    20260704_100154

Actual DTE source:
C:\Users\patri\vrp_project\data\processed\put_candidate_universe_pricing_v0_1.parquet

Actual DTE availability:

,rows,actual_dte_non_null,actual_dte_non_null_pct,fallback_to_tenor_rows,fallback_to_tenor_pct
0,14565,14565,1.0,0,0.0

Core-only Phase 2 grid summary:

,valid_vrp_triples,valid_z_triples,valid_rsi_triples,valid_rv21d_triples,total_core_specs
0,2,7,24,4,1344

Core-only Phase 2 specs sample:

,spec_id,role,phase,forecast_denominator,front_vrp_log_min,middle_vrp_log_min,back_vrp_log_min,front_z_3m_min,middle_z_3m_min,back_z_3m_min,front_z_1y_min,middle_z_1y_min,back_z_1y_min,front_rsi14_max,middle_rsi14_max,back_rsi14_max,front_rv21d_min,middle_rv21d_min,back_rv21d_min,phase_z_3m_equals_z_1y
0,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,67,65,8.0,8.0,8.0,True
1,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,67,65,8.0,8.0,8.5,True
2,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,67,65,8.0,8.5,8.5,True
3,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,67,65,8.5,8.5,8.5,True
4,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,67,66,8.0,8.0,8.0,True
5,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,67,66,8.0,8.0,8.5,True
6,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,67,66,8.0,8.5,8.5,True
7,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,67,66,8.5,8.5,8.5,True
8,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,65,8.0,8.0,8.0,True
9,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,65,8.0,8.0,8.5,True
10,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,65,8.0,8.5,8.5,True
11,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,65,8.5,8.5,8.5,True
12,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,66,8.0,8.0,8.0,True
13,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,66,8.0,8.0,8.5,True
14,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,66,8.0,8.5,8.5,True
15,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,66,8.5,8.5,8.5,True
16,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,68,8.0,8.0,8.0,True
17,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,68,8.0,8.0,8.5,True
18,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,68,8.0,8.5,8.5,True
19,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...,Core,core_only_phase2,har_total_simple,0.6,0.7,0.7,0.6,0.75,0.75,0.6,0.75,0.75,69,68,68,8.5,8.5,8.5,True

Cell 6 input summary:

,eligible_rows_after_complete_date_filter,eligible_dates,first_date,last_date,unique_tenors,core_specs_to_test,win_band_bps,min_conditional_obs,forecast_model
0,13302,1478,2020-07-01,2026-05-19,9,1344,25.0,20,har_total_simple

Running Core-only Phase 2 sweep: 1,344 specs
Core specs processed: 250 / 1,344
Core specs processed: 500 / 1,344
Core specs processed: 750 / 1,344
Core specs processed: 1,000 / 1,344
Core specs processed: 1,250 / 1,344
Core specs processed: 1,344 / 1,344

Core-only Phase 2 sweep summary:

,core_specs_tested,specs_core_win_85_plus,specs_core_win_82_plus,specs_core_win_80_plus,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day
0,1344,0,303,1344,0.829268,0.815686,0.200271,0.177943,432.567309,378.702796

Top Core specs by win rate:

,frequency_rank_with_targets_first,win_rate_rank,meets_core_win_85,core_trades,core_frequency,core_win_rate,core_win_gap_to_85,core_avg_pnl_per_trade,core_avg_pnl_per_day,core_exposure_day_weighted_pnl_per_day,...,back_selected_win_rate,back_selected_avg_pnl_per_trade,back_selected_avg_pnl_per_day,back_selected_total_pnl,back_selected_worst_trade_pnl,vrp_triple,z_triple,rsi_triple,rv21d_triple,spec_id
1003,1111,1,False,246,0.166441,0.829268,0.020732,10159.239096,431.673362,469.769327,...,0.914286,14744.438955,485.545755,1.548166e+06,-92579.572354,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.5 / 8.5 / 8.5,core_phase2_vrp_0.70_0.70_0.70_z_0.70_0.75_0.7...
1035,1112,2,False,246,0.166441,0.829268,0.020732,10159.239096,431.673362,469.769327,...,0.914286,14744.438955,485.545755,1.548166e+06,-92579.572354,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,71 / 68 / 65,8.5 / 8.5 / 8.5,core_phase2_vrp_0.70_0.70_0.70_z_0.70_0.75_0.7...
1007,1113,3,False,246,0.166441,0.829268,0.020732,10159.446386,430.308560,467.931813,...,0.916667,14620.051058,482.001257,1.578966e+06,-92579.572354,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 66,8.5 / 8.5 / 8.5,core_phase2_vrp_0.70_0.70_0.70_z_0.70_0.75_0.7...
1039,1114,4,False,246,0.166441,0.829268,0.020732,10159.446386,430.308560,467.931813,...,0.916667,14620.051058,482.001257,1.578966e+06,-92579.572354,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,71 / 68 / 66,8.5 / 8.5 / 8.5,core_phase2_vrp_0.70_0.70_0.70_z_0.70_0.75_0.7...
1002,961,5,False,251,0.169824,0.828685,0.021315,10067.215274,432.567309,468.807242,...,0.914286,14744.438955,485.545755,1.548166e+06,-92579.572354,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase2_vrp_0.70_0.70_0.70_z_0.70_0.75_0.7...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1262,1330,96,False,228,0.154263,0.824561,0.025439,9244.522077,412.680249,443.643661,...,0.932692,14514.825977,530.209207,1.509542e+06,-85194.299611,0.70 / 0.70 / 0.70,0.80 / 0.80 / 0.80,69 / 68 / 66,8.0 / 8.5 / 8.5,core_phase2_vrp_0.70_0.70_0.70_z_0.80_0.80_0.8...
618,1153,97,False,245,0.165765,0.824490,0.025510,8642.836680,380.813573,418.229308,...,0.930693,14641.014629,535.326000,1.478742e+06,-85194.299611,0.60 / 0.70 / 0.70,0.80 / 0.80 / 0.80,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.80_0.80_0.8...
650,1154,98,False,245,0.165765,0.824490,0.025510,8642.836680,380.813573,418.229308,...,0.930693,14641.014629,535.326000,1.478742e+06,-85194.299611,0.60 / 0.70 / 0.70,0.80 / 0.80 / 0.80,71 / 68 / 65,8.0 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.80_0.80_0.8...
622,1155,99,False,245,0.165765,0.824490,0.025510,8643.044816,379.443201,416.511798,...,0.932692,14514.825977,530.209207,1.509542e+06,-85194.299611,0.60 / 0.70 / 0.70,0.80 / 0.80 / 0.80,70 / 68 / 66,8.0 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.80_0.80_0.8...
654,1156,100,False,245,0.165765,0.824490,0.025510,8643.044816,379.443201,416.511798,...,0.932692,14514.825977,530.209207,1.509542e+06,-85194.299611,0.60 / 0.70 / 0.70,0.80 / 0.80 / 0.80,71 / 68 / 66,8.0 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.80_0.80_0.8...

Top Core specs with win rate >= 85%, ranked by frequency:

Empty DataFrame
Columns: [frequency_rank_with_targets_first, win_rate_rank, meets_core_win_85, core_trades, core_frequency, core_win_rate, core_win_gap_to_85, core_avg_pnl_per_trade, core_avg_pnl_per_day, core_exposure_day_weighted_pnl_per_day, core_total_pnl, core_profit_factor, core_worst_trade_pnl, core_worst_pnl_per_day, core_avg_actual_dte, core_avg_selected_tenor, front_selected_trades, front_selected_win_rate, front_selected_avg_pnl_per_trade, front_selected_avg_pnl_per_day, front_selected_total_pnl, front_selected_worst_trade_pnl, middle_selected_trades, middle_selected_win_rate, middle_selected_avg_pnl_per_trade, middle_selected_avg_pnl_per_day, middle_selected_total_pnl, middle_selected_worst_trade_pnl, back_selected_trades, back_selected_win_rate, back_selected_avg_pnl_per_trade, back_selected_avg_pnl_per_day, back_selected_total_pnl, back_selected_worst_trade_pnl, vrp_triple, z_triple, rsi_triple, rv21d_triple, spec_id]
Index: []

[0 rows x 39 columns]

Top Core specs with win rate >= 85%, ranked by average P&L/day:

Empty DataFrame
Columns: [frequency_rank_with_targets_first, win_rate_rank, meets_core_win_85, core_trades, core_frequency, core_win_rate, core_win_gap_to_85, core_avg_pnl_per_trade, core_avg_pnl_per_day, core_exposure_day_weighted_pnl_per_day, core_total_pnl, core_profit_factor, core_worst_trade_pnl, core_worst_pnl_per_day, core_avg_actual_dte, core_avg_selected_tenor, front_selected_trades, front_selected_win_rate, front_selected_avg_pnl_per_trade, front_selected_avg_pnl_per_day, front_selected_total_pnl, front_selected_worst_trade_pnl, middle_selected_trades, middle_selected_win_rate, middle_selected_avg_pnl_per_trade, middle_selected_avg_pnl_per_day, middle_selected_total_pnl, middle_selected_worst_trade_pnl, back_selected_trades, back_selected_win_rate, back_selected_avg_pnl_per_trade, back_selected_avg_pnl_per_day, back_selected_total_pnl, back_selected_worst_trade_pnl, vrp_triple, z_triple, rsi_triple, rv21d_triple, spec_id]
Index: []

[0 rows x 39 columns]

Highest-frequency Core specs with win rate >= 82%:

,frequency_rank_with_targets_first,win_rate_rank,meets_core_win_85,core_trades,core_frequency,core_win_rate,core_win_gap_to_85,core_avg_pnl_per_trade,core_avg_pnl_per_day,core_exposure_day_weighted_pnl_per_day,...,back_selected_win_rate,back_selected_avg_pnl_per_trade,back_selected_avg_pnl_per_day,back_selected_total_pnl,back_selected_worst_trade_pnl,vrp_triple,z_triple,rsi_triple,rv21d_triple,spec_id
42,37,294,False,295,0.199594,0.820339,0.029661,8206.737866,329.507742,393.976838,...,0.914286,14744.438955,485.545755,1.548166e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...
74,38,295,False,295,0.199594,0.820339,0.029661,8206.737866,329.507742,393.976838,...,0.914286,14744.438955,485.545755,1.548166e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,71 / 68 / 65,8.0 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...
46,39,296,False,295,0.199594,0.820339,0.029661,8206.910726,328.369637,392.643312,...,0.916667,14620.051058,482.001257,1.578966e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,70 / 68 / 66,8.0 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...
78,40,297,False,295,0.199594,0.820339,0.029661,8206.910726,328.369637,392.643312,...,0.916667,14620.051058,482.001257,1.578966e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,71 / 68 / 66,8.0 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...
40,41,298,False,295,0.199594,0.820339,0.029661,8256.130532,328.093097,392.262604,...,0.908257,14284.928685,471.016824,1.557057e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.0 / 8.0,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,681,259,False,263,0.177943,0.821293,0.028707,8305.032714,354.504277,403.812831,...,0.927273,14195.392641,519.550485,1.561493e+06,-85194.299611,0.60 / 0.70 / 0.70,0.70 / 0.80 / 0.80,70 / 68 / 68,8.5 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.80_0.8...
563,682,260,False,263,0.177943,0.821293,0.028707,8305.032714,354.504277,403.812831,...,0.927273,14195.392641,519.550485,1.561493e+06,-85194.299611,0.60 / 0.70 / 0.70,0.70 / 0.80 / 0.80,71 / 68 / 68,8.5 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.80_0.8...
539,683,261,False,263,0.177943,0.821293,0.028707,8322.012729,353.756975,405.463014,...,0.932692,14514.825977,530.209207,1.509542e+06,-85194.299611,0.60 / 0.70 / 0.70,0.70 / 0.80 / 0.80,70 / 69 / 66,8.5 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.80_0.8...
571,684,262,False,263,0.177943,0.821293,0.028707,8322.012729,353.756975,405.463014,...,0.932692,14514.825977,530.209207,1.509542e+06,-85194.299611,0.60 / 0.70 / 0.70,0.70 / 0.80 / 0.80,71 / 69 / 66,8.5 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.80_0.8...
439,685,263,False,263,0.177943,0.821293,0.028707,8394.329813,349.761572,407.401502,...,0.930693,14641.014629,535.326000,1.478742e+06,-85194.299611,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.80,70 / 69 / 65,8.5 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.75_0.8...

Tenor / DTE selection diagnostics for top Core specs by win rate:

,win_rate_rank,frequency_rank_with_targets_first,core_trades,core_frequency,core_win_rate,core_avg_pnl_per_day,core_total_pnl,selected_tenor,selected_tenor_bucket,selected_trades,...,selected_exposure_day_weighted_pnl_per_day,selected_total_pnl,selected_worst_trade_pnl,selected_worst_pnl_per_day,selected_avg_actual_dte,vrp_triple,z_triple,rsi_triple,rv21d_triple,spec_id
81,1,1111,246,0.166441,0.829268,431.673362,2.499173e+06,9,front,33,...,296.354230,9.216617e+04,-37774.103836,-4721.762979,9.424242,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.5 / 8.5 / 8.5,core_phase2_vrp_0.70_0.70_0.70_z_0.70_0.75_0.7...
82,1,1111,246,0.166441,0.829268,431.673362,2.499173e+06,12,front,26,...,270.065253,7.831892e+04,-40422.157434,-3345.245133,11.153846,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.5 / 8.5 / 8.5,core_phase2_vrp_0.70_0.70_0.70_z_0.70_0.75_0.7...
83,1,1111,246,0.166441,0.829268,431.673362,2.499173e+06,15,front,45,...,448.017457,3.306369e+05,-45195.769858,-2515.924957,16.400000,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.5 / 8.5 / 8.5,core_phase2_vrp_0.70_0.70_0.70_z_0.70_0.75_0.7...
84,1,1111,246,0.166441,0.829268,431.673362,2.499173e+06,18,middle,0,...,NaN,0.000000e+00,NaN,NaN,NaN,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.5 / 8.5 / 8.5,core_phase2_vrp_0.70_0.70_0.70_z_0.70_0.75_0.7...
85,1,1111,246,0.166441,0.829268,431.673362,2.499173e+06,21,middle,16,...,435.410905,1.541355e+05,-76881.908203,-3342.691661,22.125000,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.5 / 8.5 / 8.5,core_phase2_vrp_0.70_0.70_0.70_z_0.70_0.75_0.7...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,20,730,262,0.177267,0.828244,360.716253,2.406241e+06,21,middle,16,...,435.410905,1.541355e+05,-76881.908203,-3342.691661,22.125000,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.75,71 / 68 / 66,8.5 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.75_0.7...
68,20,730,262,0.177267,0.828244,360.716253,2.406241e+06,24,middle,18,...,635.493679,2.650009e+05,-33735.351540,-1606.445311,23.166667,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.75,71 / 68 / 66,8.5 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.75_0.7...
69,20,730,262,0.177267,0.828244,360.716253,2.406241e+06,27,back,7,...,66.689704,1.253766e+04,-92579.572354,-3703.182894,26.857143,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.75,71 / 68 / 66,8.5 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.75_0.7...
70,20,730,262,0.177267,0.828244,360.716253,2.406241e+06,30,back,99,...,516.407473,1.540443e+06,-85194.299611,-2839.809987,30.131313,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.75,71 / 68 / 66,8.5 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.75_0.7...
71,20,730,262,0.177267,0.828244,360.716253,2.406241e+06,33,back,2,...,433.072643,2.598436e+04,11972.721943,399.090731,30.000000,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.75,71 / 68 / 66,8.5 / 8.5 / 8.5,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.75_0.7...

Tenor / DTE selection diagnostics for Core specs with win rate >= 85%, ranked by frequency:

Empty DataFrame
Columns: [win_rate_rank, frequency_rank_with_targets_first, core_trades, core_frequency, core_win_rate, core_avg_pnl_per_day, core_total_pnl, selected_tenor, selected_tenor_bucket, selected_trades, selected_frequency_total_dates, selected_share_of_trades, selected_win_rate, selected_avg_pnl_per_trade, selected_avg_pnl_per_day, selected_exposure_day_weighted_pnl_per_day, selected_total_pnl, selected_worst_trade_pnl, selected_worst_pnl_per_day, selected_avg_actual_dte, vrp_triple, z_triple, rsi_triple, rv21d_triple, spec_id]
Index: []

[0 rows x 25 columns]

Tenor / DTE selection diagnostics for highest-frequency Core specs with win rate >= 82%:

,win_rate_rank,frequency_rank_with_targets_first,core_trades,core_frequency,core_win_rate,core_avg_pnl_per_day,core_total_pnl,selected_tenor,selected_tenor_bucket,selected_trades,...,selected_exposure_day_weighted_pnl_per_day,selected_total_pnl,selected_worst_trade_pnl,selected_worst_pnl_per_day,selected_avg_actual_dte,vrp_triple,z_triple,rsi_triple,rv21d_triple,spec_id
108,25,337,270,0.182679,0.825926,362.088158,2.455173e+06,9,front,32,...,6.573044,2.044217e+03,-99982.493610,-11109.165957,9.718750,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.0 / 8.0,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.75_0.7...
109,25,337,270,0.182679,0.825926,362.088158,2.455173e+06,12,front,21,...,325.780345,7.949040e+04,-40422.157434,-2694.810496,11.619048,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.0 / 8.0,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.75_0.7...
110,25,337,270,0.182679,0.825926,362.088158,2.455173e+06,15,front,68,...,306.612277,3.409529e+05,-78761.670342,-4633.039432,16.352941,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.0 / 8.0,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.75_0.7...
111,25,337,270,0.182679,0.825926,362.088158,2.455173e+06,18,middle,0,...,NaN,0.000000e+00,NaN,NaN,NaN,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.0 / 8.0,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.75_0.7...
112,25,337,270,0.182679,0.825926,362.088158,2.455173e+06,21,middle,17,...,449.114979,1.693163e+05,-76881.908203,-3342.691661,22.176471,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.0 / 8.0,core_phase2_vrp_0.60_0.70_0.70_z_0.70_0.75_0.7...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,301,44,295,0.199594,0.820339,326.954992,2.435610e+06,21,middle,17,...,449.114979,1.693163e+05,-76881.908203,-3342.691661,22.176471,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,71 / 68 / 66,8.0 / 8.0 / 8.0,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...
86,301,44,295,0.199594,0.820339,326.954992,2.435610e+06,24,middle,20,...,593.886900,2.755635e+05,-33735.351540,-1606.445311,23.200000,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,71 / 68 / 66,8.0 / 8.0 / 8.0,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...
87,301,44,295,0.199594,0.820339,326.954992,2.435610e+06,27,back,8,...,64.939481,1.402693e+04,-92579.572354,-3703.182894,27.000000,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,71 / 68 / 66,8.0 / 8.0 / 8.0,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...
88,301,44,295,0.199594,0.820339,326.954992,2.435610e+06,30,back,102,...,503.855913,1.547845e+06,-85194.299611,-2839.809987,30.117647,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,71 / 68 / 66,8.0 / 8.0 / 8.0,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...
89,301,44,295,0.199594,0.820339,326.954992,2.435610e+06,33,back,2,...,433.072643,2.598436e+04,11972.721943,399.090731,30.000000,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,71 / 68 / 66,8.0 / 8.0 / 8.0,core_phase2_vrp_0.60_0.70_0.70_z_0.60_0.75_0.7...

Core parameter diagnostics by VRP triple:

,vrp_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_82_plus,specs_core_win_80_plus
1,0.70 / 0.70 / 0.70,672,0.829268,0.815126,0.182679,0.171516,432.567309,403.084527,2.536852e+06,0,157,672
0,0.60 / 0.70 / 0.70,672,0.828358,0.815972,0.200271,0.183018,380.813573,350.169902,2.458217e+06,0,146,672

Core parameter diagnostics by z-score triple:

,z_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_82_plus,specs_core_win_80_plus
3,0.70 / 0.75 / 0.75,192,0.829268,0.822222,0.184032,0.172530,432.567309,389.321006,2.536852e+06,0,126,192
6,0.80 / 0.80 / 0.80,192,0.828326,0.817224,0.169824,0.161028,414.152798,387.623951,2.178738e+06,0,53,192
5,0.70 / 0.80 / 0.80,192,0.825203,0.818350,0.184032,0.172530,429.220408,388.104840,2.335773e+06,0,56,192
4,0.70 / 0.75 / 0.80,192,0.825203,0.818350,0.184032,0.172530,423.696376,382.799336,2.354843e+06,0,56,192
0,0.60 / 0.75 / 0.75,192,0.822300,0.814126,0.200271,0.186062,396.967193,354.758598,2.486080e+06,0,12,192
2,0.60 / 0.80 / 0.80,192,0.818815,0.810409,0.200271,0.186062,393.748526,353.672629,2.285001e+06,0,0,192
1,0.60 / 0.75 / 0.80,192,0.818815,0.810409,0.200271,0.186062,388.443318,349.014741,2.304072e+06,0,0,192

Core parameter diagnostics by RSI cap triple:

,rsi_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_82_plus,specs_core_win_80_plus
10,70 / 68 / 65,56,0.829268,0.820131,0.199594,0.181326,432.567309,383.488801,2.533807e+06,0,28,56
18,71 / 68 / 65,56,0.829268,0.820131,0.199594,0.181326,432.567309,383.488801,2.533807e+06,0,28,56
11,70 / 68 / 66,56,0.829268,0.820131,0.199594,0.181326,431.229694,382.177232,2.533858e+06,0,28,56
19,71 / 68 / 66,56,0.829268,0.820131,0.199594,0.181326,431.229694,382.177232,2.533858e+06,0,28,56
12,70 / 68 / 68,56,0.825911,0.817111,0.200271,0.182003,427.636439,379.005794,2.536017e+06,0,17,56
20,71 / 68 / 68,56,0.825911,0.817111,0.200271,0.182003,427.636439,379.005794,2.536017e+06,0,17,56
13,70 / 69 / 65,56,0.825911,0.816872,0.199594,0.182003,428.352749,380.478891,2.534642e+06,0,17,56
21,71 / 69 / 65,56,0.825911,0.816872,0.199594,0.182003,428.352749,380.478891,2.534642e+06,0,17,56
14,70 / 69 / 66,56,0.825911,0.816872,0.199594,0.182003,427.020443,379.175199,2.534693e+06,0,17,56
22,71 / 69 / 66,56,0.825911,0.816872,0.199594,0.182003,427.020443,379.175199,2.534693e+06,0,17,56
2,69 / 68 / 65,56,0.825726,0.816714,0.196211,0.177943,430.795486,382.023032,2.497923e+06,0,17,56
3,69 / 68 / 66,56,0.825726,0.816714,0.196211,0.177943,429.430685,380.685280,2.497974e+06,0,17,56
8,70 / 67 / 65,56,0.823770,0.814899,0.198241,0.179973,427.475159,378.648760,2.476103e+06,0,7,56
16,71 / 67 / 65,56,0.823770,0.814899,0.198241,0.179973,427.475159,378.648760,2.476103e+06,0,7,56
9,70 / 67 / 66,56,0.823770,0.814899,0.198241,0.179973,426.126801,377.326843,2.476154e+06,0,7,56
17,71 / 67 / 66,56,0.823770,0.814899,0.198241,0.179973,426.126801,377.326843,2.476154e+06,0,7,56
15,70 / 69 / 68,56,0.822581,0.813939,0.200271,0.182679,423.458027,376.034192,2.536852e+06,0,5,56
23,71 / 69 / 68,56,0.822581,0.813939,0.200271,0.182679,423.458027,376.034192,2.536852e+06,0,5,56
4,69 / 68 / 68,56,0.822314,0.813394,0.196888,0.178620,425.771975,377.456519,2.500133e+06,0,5,56
5,69 / 69 / 65,56,0.822314,0.813511,0.196211,0.178620,428.934137,378.960613,2.498758e+06,0,5,56
6,69 / 69 / 66,56,0.822314,0.813511,0.196211,0.178620,427.574861,377.631060,2.498809e+06,0,5,56
0,69 / 67 / 65,56,0.820084,0.811091,0.194858,0.176590,425.584467,377.073668,2.440101e+06,0,1,56
1,69 / 67 / 66,56,0.820084,0.811091,0.194858,0.176590,424.208478,375.725148,2.440152e+06,0,1,56
7,69 / 69 / 68,56,0.818930,0.810501,0.196888,0.179296,423.938387,374.433905,2.500968e+06,0,0,56

Core parameter diagnostics by RV21D floor triple:

,rv21d_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_82_plus,specs_core_win_80_plus
3,8.5 / 8.5 / 8.5,336,0.829268,0.818182,0.194858,0.175237,431.673362,376.192830,2.503340e+06,0,112,336
2,8.0 / 8.5 / 8.5,336,0.828685,0.818182,0.200271,0.179635,432.567309,380.067665,2.531038e+06,0,127,336
0,8.0 / 8.0 / 8.0,336,0.826087,0.815789,0.200271,0.179973,426.269040,374.262849,2.534693e+06,0,56,336
1,8.0 / 8.0 / 8.5,336,0.822222,0.812000,0.200271,0.179973,426.222051,372.669034,2.536852e+06,0,8,336

Cell 6 outputs saved:
Core specs:                    C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_specs_20200701_20260519_20260704_100154.csv
Grid summary:                  C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_grid_summary_20200701_20260519_20260704_100154.csv
Core summary:                  C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_summary_20200701_20260519_20260704_100154.csv
Conditional stats:             C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_conditional_stats_20200701_20260519_20260704_100154.csv
Tenor selection summary:       C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_tenor_selection_summary_20200701_20260519_20260704_100154.csv
Top by win rate:               C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_top_by_win_20200701_20260519_20260704_100154.csv
Win >=85 by frequency:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_win85_by_frequency_20200701_20260519_20260704_100154.csv
Win >=85 by P&L/day:           C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_win85_by_pnl_day_20200701_20260519_20260704_100154.csv
Win >=82 by frequency:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_win82_by_frequency_20200701_20260519_20260704_100154.csv
Tenor top by win:              C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_tenor_top_by_win_20200701_20260519_20260704_100154.csv
Tenor win >=85 by frequency:   C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_tenor_win85_by_frequency_20200701_20260519_20260704_100154.csv
Tenor win >=82 by frequency:   C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_tenor_win82_by_frequency_20200701_20260519_20260704_100154.csv
Core by VRP:                   C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_by_vrp_20200701_20260519_20260704_100154.csv
Core by z-score:               C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_by_z_20200701_20260519_20260704_100154.csv
Core by RSI:                   C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_by_rsi_20200701_20260519_20260704_100154.csv
Core by RV21D:                 C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell6_core_only_phase2_by_rv21d_20200701_20260519_20260704_100154.csv

Cell 6 complete.

In [9]:
# Cell 7: Core-only Phase 3 sweep — untied z-scores
#
# Approved scope:
#   - Core only.
#   - No Secondary.
#   - No sizing.
#   - No final lock.
#   - 3m z-score and 1y z-score are tested independently.
#   - Tenor selection uses strict highest conditional win probability first.
#   - No 25 bps win-rate band.
#
# Goal:
#   - Core win rate >= 85%.
#   - Then maximize Core frequency.
#   - Then evaluate P&L/day and exact DTE / tenor selection mix.
#
# User-approved grid:
#
#   Front 9D / 12D / 15D:
#       VRP:      0.60 locked
#       3m z:     [0.50, 0.60, 0.70]
#       1y z:     [0.50, 0.60, 0.70]
#       RSI:      70 locked
#       RV21D:    [7.5, 8.0]
#
#   Middle 18D / 21D / 24D:
#       VRP:      0.70 locked
#       3m z:     [0.70, 0.75, 0.80]
#       1y z:     [0.70, 0.75, 0.80]
#       RSI:      68 locked
#       RV21D:    8.5 locked
#
#   Back 27D / 30D / 33D:
#       VRP:      0.70 locked
#       3m z:     [0.70, 0.75, 0.80]
#       1y z:     [0.70, 0.75, 0.80]
#       RSI:      [65, 66, 67]
#       RV21D:    8.5 locked
#
# Constraints:
#   - Front 3m z <= Middle 3m z <= Back 3m z
#   - Front 1y z <= Middle 1y z <= Back 1y z
#   - Front VRP <= Middle VRP <= Back VRP
#   - Front RV21D <= Middle RV21D <= Back RV21D
#   - Front RSI >= Middle RSI >= Back RSI
#
# Expected valid grid size:
#   - VRP triples:       1
#   - 3m z triples:      18
#   - 1y z triples:      18
#   - RSI triples:       3
#   - RV21D triples:     2
#   - Total Core specs:  1,944
#
# Tenor selection rule when multiple tenors pass:
#   1. Prefer tenors with conditional sample size >= 20.
#   2. Highest conditional win probability.
#   3. Highest conditional average P&L/day.
#   4. Highest conditional aggregate P&L/day.
#   5. Longer tenor.
#
# P&L/day:
#   normalized_pnl_dollars / actual_dte if actual_dte is available.
#   Falls back to normalized_pnl_dollars / tenor if actual_dte is unavailable.

from pathlib import Path
import itertools
import numpy as np
import pandas as pd


# -----------------------------
# 1. Paths / load latest clean panel
# -----------------------------

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

PARAM_SWEEP_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "corsi_parameter_sweep_clean"
PARAM_SWEEP_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "corsi_parameter_sweep_clean"
CORSI_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "forecast_model_corsi_v1"

PARAM_SWEEP_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

RUN_TIMESTAMP = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")

clean_panel_candidates = sorted(
    PARAM_SWEEP_PROCESSED_DIR.glob("02_corsi_parameter_sweep_clean_panel_*.parquet")
)

if not clean_panel_candidates:
    raise FileNotFoundError(f"No clean panel found in {PARAM_SWEEP_PROCESSED_DIR}")

CLEAN_PANEL_PATH = clean_panel_candidates[-1]

print("Cell 7: Core-only Phase 3 sweep — untied z-scores")
print(f"Clean panel path: {CLEAN_PANEL_PATH}")
print(f"Run timestamp:    {RUN_TIMESTAMP}")

panel = pd.read_parquet(CLEAN_PANEL_PATH).copy()

panel["date"] = pd.to_datetime(panel["date"]).dt.normalize()
panel["trade_date"] = pd.to_numeric(panel["trade_date"], errors="coerce").astype(int)
panel["tenor"] = pd.to_numeric(panel["tenor"], errors="coerce").astype(int)

required_panel_cols = [
    "date",
    "trade_date",
    "tenor",
    "tenor_bucket",
    "forecast_model",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rsi14",
    "rv21d",
    "outcome_value",
    "has_outcome",
    "is_parameter_sweep_eligible",
]

missing_panel_cols = [c for c in required_panel_cols if c not in panel.columns]

if missing_panel_cols:
    raise ValueError(f"Clean panel missing required columns: {missing_panel_cols}")


# -----------------------------
# 2. Actual DTE helper
# -----------------------------

def first_existing_col(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    return None


def load_actual_dte_lookup():
    outcome_discovery_candidates = sorted(
        CORSI_AUDIT_DIR.glob("corsi_cell11_trade_outcome_file_discovery_*.csv")
    )

    if not outcome_discovery_candidates:
        return None, "no_outcome_discovery_file"

    discovery_path = outcome_discovery_candidates[-1]
    discovery = pd.read_csv(discovery_path)
    discovery.columns = [str(c).strip() for c in discovery.columns]

    file_col = "chosen_file" if "chosen_file" in discovery.columns else "path"

    if file_col not in discovery.columns:
        return None, "discovery_missing_path_column"

    preferred = discovery.copy()

    if "eligible_for_backtest" in preferred.columns:
        preferred = preferred.loc[preferred["eligible_for_backtest"].astype(bool)].copy()

    if preferred.empty:
        return None, "no_eligible_outcome_files"

    if "score" in preferred.columns:
        preferred["_score"] = pd.to_numeric(preferred["score"], errors="coerce")
    else:
        preferred["_score"] = 0.0

    if "chosen_outcome_col" in preferred.columns:
        preferred["_preferred_pnl"] = preferred["chosen_outcome_col"].eq("normalized_pnl_dollars")
    elif "outcome_col" in preferred.columns:
        preferred["_preferred_pnl"] = preferred["outcome_col"].eq("normalized_pnl_dollars")
    else:
        preferred["_preferred_pnl"] = False

    preferred = preferred.sort_values(
        ["_preferred_pnl", "_score"],
        ascending=[False, False],
    )

    for _, row in preferred.iterrows():
        path = Path(row[file_col])

        if not path.exists():
            continue

        try:
            raw = pd.read_parquet(path) if path.suffix.lower() == ".parquet" else pd.read_csv(path)
        except Exception:
            continue

        raw.columns = [str(c).strip() for c in raw.columns]

        trade_date_col = first_existing_col(raw, ["trade_date", "trade_dt", "date"])
        tenor_col = first_existing_col(raw, ["tenor", "entry_tenor", "target_tenor"])
        actual_dte_col = first_existing_col(raw, ["actual_dte"])

        if trade_date_col is None or tenor_col is None or actual_dte_col is None:
            continue

        lookup = raw[[trade_date_col, tenor_col, actual_dte_col]].copy()
        lookup = lookup.rename(columns={
            trade_date_col: "trade_date",
            tenor_col: "tenor",
            actual_dte_col: "actual_dte_from_outcomes",
        })

        lookup["trade_date"] = pd.to_numeric(lookup["trade_date"], errors="coerce").astype("Int64")
        lookup["tenor"] = pd.to_numeric(lookup["tenor"], errors="coerce").astype("Int64")
        lookup["actual_dte_from_outcomes"] = pd.to_numeric(
            lookup["actual_dte_from_outcomes"],
            errors="coerce",
        )

        lookup = lookup.dropna(subset=["trade_date", "tenor"])
        lookup["trade_date"] = lookup["trade_date"].astype(int)
        lookup["tenor"] = lookup["tenor"].astype(int)
        lookup = lookup.drop_duplicates(["trade_date", "tenor"])

        return lookup, str(path)

    return None, "actual_dte_not_found_in_outcome_files"


if "actual_dte" not in panel.columns:
    actual_dte_lookup, actual_dte_source = load_actual_dte_lookup()

    if actual_dte_lookup is not None:
        panel = panel.merge(
            actual_dte_lookup,
            on=["trade_date", "tenor"],
            how="left",
            validate="many_to_one",
        )
        panel["actual_dte"] = panel["actual_dte_from_outcomes"]
        panel = panel.drop(columns=["actual_dte_from_outcomes"])
    else:
        panel["actual_dte"] = np.nan
else:
    actual_dte_source = "clean_panel_existing_actual_dte"

panel["actual_dte"] = pd.to_numeric(panel["actual_dte"], errors="coerce")
panel["actual_dte_for_pnl_day"] = panel["actual_dte"]

fallback_mask = (
    panel["actual_dte_for_pnl_day"].isna()
    | panel["actual_dte_for_pnl_day"].le(0)
)

panel.loc[fallback_mask, "actual_dte_for_pnl_day"] = panel.loc[fallback_mask, "tenor"]
panel["pnl_per_day"] = panel["outcome_value"] / panel["actual_dte_for_pnl_day"]

print()
print("Actual DTE source:")
print(actual_dte_source)

print()
print("Actual DTE availability:")
display(pd.DataFrame([{
    "rows": len(panel),
    "actual_dte_non_null": int(panel["actual_dte"].notna().sum()),
    "actual_dte_non_null_pct": float(panel["actual_dte"].notna().mean()),
    "fallback_to_tenor_rows": int(fallback_mask.sum()),
    "fallback_to_tenor_pct": float(fallback_mask.mean()),
}]))


# -----------------------------
# 3. Build Core-only Phase 3 grid
# -----------------------------

FRONT_GRID = {
    "vrp": [0.60],
    "z_3m": [0.50, 0.60, 0.70],
    "z_1y": [0.50, 0.60, 0.70],
    "rsi": [70],
    "rv21d": [7.5, 8.0],
}

MIDDLE_GRID = {
    "vrp": [0.70],
    "z_3m": [0.70, 0.75, 0.80],
    "z_1y": [0.70, 0.75, 0.80],
    "rsi": [68],
    "rv21d": [8.5],
}

BACK_GRID = {
    "vrp": [0.70],
    "z_3m": [0.70, 0.75, 0.80],
    "z_1y": [0.70, 0.75, 0.80],
    "rsi": [65, 66, 67],
    "rv21d": [8.5],
}


def valid_increasing_triples(front_vals, middle_vals, back_vals):
    return [
        (f, m, b)
        for f, m, b in itertools.product(front_vals, middle_vals, back_vals)
        if f <= m <= b
    ]


def valid_rsi_triples(front_vals, middle_vals, back_vals):
    return [
        (f, m, b)
        for f, m, b in itertools.product(front_vals, middle_vals, back_vals)
        if f >= m >= b
    ]


CORE_VRP_TRIPLES = valid_increasing_triples(
    FRONT_GRID["vrp"],
    MIDDLE_GRID["vrp"],
    BACK_GRID["vrp"],
)

CORE_Z3M_TRIPLES = valid_increasing_triples(
    FRONT_GRID["z_3m"],
    MIDDLE_GRID["z_3m"],
    BACK_GRID["z_3m"],
)

CORE_Z1Y_TRIPLES = valid_increasing_triples(
    FRONT_GRID["z_1y"],
    MIDDLE_GRID["z_1y"],
    BACK_GRID["z_1y"],
)

CORE_RSI_TRIPLES = valid_rsi_triples(
    FRONT_GRID["rsi"],
    MIDDLE_GRID["rsi"],
    BACK_GRID["rsi"],
)

CORE_RV21D_TRIPLES = valid_increasing_triples(
    FRONT_GRID["rv21d"],
    MIDDLE_GRID["rv21d"],
    BACK_GRID["rv21d"],
)

spec_rows = []

for spec_num, (vrp, z3m, z1y, rsi, rv21d) in enumerate(
    itertools.product(
        CORE_VRP_TRIPLES,
        CORE_Z3M_TRIPLES,
        CORE_Z1Y_TRIPLES,
        CORE_RSI_TRIPLES,
        CORE_RV21D_TRIPLES,
    ),
    start=1,
):
    spec_id = (
        f"core_phase3_"
        f"vrp_{vrp[0]:.2f}_{vrp[1]:.2f}_{vrp[2]:.2f}_"
        f"z3m_{z3m[0]:.2f}_{z3m[1]:.2f}_{z3m[2]:.2f}_"
        f"z1y_{z1y[0]:.2f}_{z1y[1]:.2f}_{z1y[2]:.2f}_"
        f"rsi_{int(rsi[0])}_{int(rsi[1])}_{int(rsi[2])}_"
        f"rv21d_{rv21d[0]:.1f}_{rv21d[1]:.1f}_{rv21d[2]:.1f}"
    )

    spec_rows.append({
        "spec_id": spec_id,
        "role": "Core",
        "phase": "core_only_phase3_untied_z",
        "forecast_denominator": "har_total_simple",

        "front_vrp_log_min": vrp[0],
        "middle_vrp_log_min": vrp[1],
        "back_vrp_log_min": vrp[2],

        "front_z_3m_min": z3m[0],
        "middle_z_3m_min": z3m[1],
        "back_z_3m_min": z3m[2],

        "front_z_1y_min": z1y[0],
        "middle_z_1y_min": z1y[1],
        "back_z_1y_min": z1y[2],

        "front_rsi14_max": rsi[0],
        "middle_rsi14_max": rsi[1],
        "back_rsi14_max": rsi[2],

        "front_rv21d_min": rv21d[0],
        "middle_rv21d_min": rv21d[1],
        "back_rv21d_min": rv21d[2],

        "phase_z_3m_equals_z_1y": False,
    })

core_specs = pd.DataFrame(spec_rows)

grid_summary = pd.DataFrame([{
    "valid_vrp_triples": len(CORE_VRP_TRIPLES),
    "valid_z_3m_triples": len(CORE_Z3M_TRIPLES),
    "valid_z_1y_triples": len(CORE_Z1Y_TRIPLES),
    "valid_rsi_triples": len(CORE_RSI_TRIPLES),
    "valid_rv21d_triples": len(CORE_RV21D_TRIPLES),
    "total_core_specs": len(core_specs),
}])

print()
print("Core-only Phase 3 grid summary:")
display(grid_summary)

print()
print("Core-only Phase 3 specs sample:")
display(core_specs.head(20))


# -----------------------------
# 4. Build complete eligible matrix panel
# -----------------------------

TENORS = [9, 12, 15, 18, 21, 24, 27, 30, 33]

TENOR_BUCKET_MAP = {
    9: "front",
    12: "front",
    15: "front",
    18: "middle",
    21: "middle",
    24: "middle",
    27: "back",
    30: "back",
    33: "back",
}

BUCKETS = ["front", "middle", "back"]
MIN_CONDITIONAL_OBS = 20

eligible = panel.loc[panel["is_parameter_sweep_eligible"].astype(bool)].copy()
eligible = eligible.replace([np.inf, -np.inf], np.nan)

needed_for_matrix = [
    "trade_date",
    "date",
    "tenor",
    "tenor_bucket",
    "forecast_model",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rsi14",
    "rv21d",
    "outcome_value",
    "actual_dte_for_pnl_day",
    "pnl_per_day",
]

eligible = eligible.dropna(subset=needed_for_matrix).copy()

eligible = eligible.loc[
    eligible["tenor"].isin(TENORS)
    & eligible["actual_dte_for_pnl_day"].gt(0)
].copy()

duplicate_rows = eligible.duplicated(["trade_date", "tenor"]).sum()

if duplicate_rows:
    raise ValueError(f"Eligible panel has duplicate trade_date x tenor rows: {duplicate_rows}")

date_counts = eligible.groupby("trade_date")["tenor"].nunique()
complete_dates = date_counts.loc[date_counts.eq(len(TENORS))].index.tolist()

eligible = eligible.loc[eligible["trade_date"].isin(complete_dates)].copy()

eligible_dates = sorted(eligible["trade_date"].unique())
num_dates = len(eligible_dates)
num_tenors = len(TENORS)

date_lookup = (
    eligible[["trade_date", "date"]]
    .drop_duplicates("trade_date")
    .set_index("trade_date")
    .loc[eligible_dates]
)

date_array = date_lookup["date"].to_numpy()


def pivot_matrix(col, dtype=float):
    mat = (
        eligible
        .pivot(index="trade_date", columns="tenor", values=col)
        .reindex(index=eligible_dates, columns=TENORS)
    )

    if mat.isna().any().any():
        missing = int(mat.isna().sum().sum())
        raise ValueError(f"Matrix for {col} has missing cells after complete-date filter: {missing}")

    return mat.to_numpy(dtype=dtype)


vrp_mat = pivot_matrix("vrp_log")
z3m_mat = pivot_matrix("vrp_z_3m")
z1y_mat = pivot_matrix("vrp_z_1y")
rsi_mat = pivot_matrix("rsi14")
rv21d_mat = pivot_matrix("rv21d")
pnl_mat = pivot_matrix("outcome_value")
actual_dte_mat = pivot_matrix("actual_dte_for_pnl_day")
pnl_per_day_mat = pivot_matrix("pnl_per_day")

valid_outcome_mat = (
    np.isfinite(pnl_mat)
    & np.isfinite(pnl_per_day_mat)
    & np.isfinite(actual_dte_mat)
)

tenor_array = np.array(TENORS, dtype=int)
tenor_bucket_array = np.array([TENOR_BUCKET_MAP[int(t)] for t in tenor_array], dtype=object)

print()
print("Cell 7 input summary:")
display(pd.DataFrame([{
    "eligible_rows_after_complete_date_filter": len(eligible),
    "eligible_dates": num_dates,
    "first_date": pd.to_datetime(date_array.min()),
    "last_date": pd.to_datetime(date_array.max()),
    "unique_tenors": num_tenors,
    "core_specs_to_test": len(core_specs),
    "min_conditional_obs": MIN_CONDITIONAL_OBS,
    "forecast_model": ", ".join(sorted(eligible["forecast_model"].astype(str).unique())),
    "selection_rule": "strict_highest_conditional_win_probability_no_25bp_band",
}]))


# -----------------------------
# 5. Matrix helper functions
# -----------------------------

def threshold_array_for_spec(spec_row, field_suffix):
    vals = []

    for tenor in TENORS:
        bucket = TENOR_BUCKET_MAP[int(tenor)]
        vals.append(float(spec_row[f"{bucket}_{field_suffix}"]))

    return np.array(vals, dtype=float)


def build_pass_matrix(spec_row):
    vrp_threshold = threshold_array_for_spec(spec_row, "vrp_log_min")
    z3m_threshold = threshold_array_for_spec(spec_row, "z_3m_min")
    z1y_threshold = threshold_array_for_spec(spec_row, "z_1y_min")
    rsi_cap = threshold_array_for_spec(spec_row, "rsi14_max")
    rv21d_floor = threshold_array_for_spec(spec_row, "rv21d_min")

    return (
        (vrp_mat >= vrp_threshold[None, :])
        & (z3m_mat >= z3m_threshold[None, :])
        & (z1y_mat >= z1y_threshold[None, :])
        & (rsi_mat <= rsi_cap[None, :])
        & (rv21d_mat >= rv21d_floor[None, :])
        & valid_outcome_mat
    )


def compute_conditional_arrays(pass_matrix):
    obs = pass_matrix.sum(axis=0).astype(float)
    wins = ((pnl_mat > 0) & pass_matrix).sum(axis=0).astype(float)

    total_pnl = np.where(
        obs > 0,
        np.where(pass_matrix, pnl_mat, 0.0).sum(axis=0),
        0.0,
    )

    total_pnl_day = np.where(
        obs > 0,
        np.where(pass_matrix, pnl_per_day_mat, 0.0).sum(axis=0),
        np.nan,
    )

    total_dte = np.where(
        obs > 0,
        np.where(pass_matrix, actual_dte_mat, 0.0).sum(axis=0),
        np.nan,
    )

    win_prob = np.divide(
        wins,
        obs,
        out=np.full_like(obs, np.nan, dtype=float),
        where=obs > 0,
    )

    avg_pnl_per_day = np.divide(
        total_pnl_day,
        obs,
        out=np.full_like(obs, np.nan, dtype=float),
        where=obs > 0,
    )

    avg_pnl_per_trade = np.divide(
        total_pnl,
        obs,
        out=np.full_like(obs, np.nan, dtype=float),
        where=obs > 0,
    )

    aggregate_pnl_per_day = np.divide(
        total_pnl,
        total_dte,
        out=np.full_like(obs, np.nan, dtype=float),
        where=total_dte > 0,
    )

    worst_trade = np.full(num_tenors, np.nan)
    worst_pnl_day = np.full(num_tenors, np.nan)
    avg_actual_dte = np.full(num_tenors, np.nan)

    for col_idx in range(num_tenors):
        mask = pass_matrix[:, col_idx]

        if mask.any():
            worst_trade[col_idx] = np.nanmin(pnl_mat[mask, col_idx])
            worst_pnl_day[col_idx] = np.nanmin(pnl_per_day_mat[mask, col_idx])
            avg_actual_dte[col_idx] = np.nanmean(actual_dte_mat[mask, col_idx])

    sample_ok = obs >= MIN_CONDITIONAL_OBS

    return {
        "obs": obs,
        "wins": wins,
        "win_prob": win_prob,
        "avg_pnl_per_day": avg_pnl_per_day,
        "aggregate_pnl_per_day": aggregate_pnl_per_day,
        "avg_pnl_per_trade": avg_pnl_per_trade,
        "total_pnl": total_pnl,
        "worst_trade": worst_trade,
        "worst_pnl_day": worst_pnl_day,
        "avg_actual_dte": avg_actual_dte,
        "sample_ok": sample_ok,
    }


def select_cols_from_pass_and_stats(pass_matrix, stats):
    """
    Strict selection rule:
      1. Prefer sample_ok tenors if any passing sample_ok tenor exists on date.
      2. Highest conditional win probability.
      3. Highest conditional average P&L/day.
      4. Highest conditional aggregate P&L/day.
      5. Longer tenor.
    """
    obs = stats["obs"]
    win = stats["win_prob"]
    avg_day = stats["avg_pnl_per_day"]
    agg_day = stats["aggregate_pnl_per_day"]
    sample_ok = stats["sample_ok"]

    has_stats = (
        (obs > 0)
        & np.isfinite(win)
        & np.isfinite(avg_day)
        & np.isfinite(agg_day)
    )

    active = pass_matrix & has_stats[None, :]

    active_sample_ok = active & sample_ok[None, :]
    row_has_sample_ok = active_sample_ok.any(axis=1)

    ranking_universe = np.where(
        row_has_sample_ok[:, None],
        active_sample_ok,
        active,
    )

    selected_col = np.full(num_dates, -1, dtype=int)

    best_win = np.full(num_dates, -np.inf)
    best_avg = np.full(num_dates, -np.inf)
    best_agg = np.full(num_dates, -np.inf)
    best_tenor = np.full(num_dates, -np.inf)

    for col_idx, tenor in enumerate(TENORS):
        cand = ranking_universe[:, col_idx]

        win_val = win[col_idx]
        avg_val = avg_day[col_idx]
        agg_val = agg_day[col_idx]
        tenor_val = float(tenor)

        better = (
            cand
            & (
                (win_val > best_win)
                | ((win_val == best_win) & (avg_val > best_avg))
                | ((win_val == best_win) & (avg_val == best_avg) & (agg_val > best_agg))
                | ((win_val == best_win) & (avg_val == best_avg) & (agg_val == best_agg) & (tenor_val > best_tenor))
            )
        )

        selected_col[better] = col_idx
        best_win[better] = win_val
        best_avg[better] = avg_val
        best_agg[better] = agg_val
        best_tenor[better] = tenor_val

    return selected_col


def profit_factor(values):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]

    if values.size == 0:
        return np.nan

    gains = values[values > 0].sum()
    losses = values[values < 0].sum()

    if losses < 0:
        return gains / abs(losses)

    if gains > 0 and losses == 0:
        return np.inf

    return np.nan


def summarize_selected_cols(selected_cols, prefix):
    selected_cols = np.asarray(selected_cols, dtype=int)
    date_idx = np.where(selected_cols >= 0)[0]

    if date_idx.size == 0:
        return {
            f"{prefix}_trades": 0,
            f"{prefix}_frequency": 0.0,
            f"{prefix}_win_rate": np.nan,
            f"{prefix}_total_pnl": 0.0,
            f"{prefix}_avg_pnl_per_trade": np.nan,
            f"{prefix}_avg_pnl_per_day": np.nan,
            f"{prefix}_exposure_day_weighted_pnl_per_day": np.nan,
            f"{prefix}_profit_factor": np.nan,
            f"{prefix}_worst_trade_pnl": np.nan,
            f"{prefix}_worst_pnl_per_day": np.nan,
            f"{prefix}_best_trade_pnl": np.nan,
            f"{prefix}_avg_actual_dte": np.nan,
            f"{prefix}_avg_selected_tenor": np.nan,
        }

    cols = selected_cols[date_idx]

    pnl = pnl_mat[date_idx, cols]
    pnl_day = pnl_per_day_mat[date_idx, cols]
    dte = actual_dte_mat[date_idx, cols]
    selected_tenors = tenor_array[cols]

    total_dte = np.nansum(dte)

    exposure_day_weighted_pnl_per_day = (
        np.nansum(pnl) / total_dte if total_dte > 0 else np.nan
    )

    return {
        f"{prefix}_trades": int(date_idx.size),
        f"{prefix}_frequency": float(date_idx.size / num_dates) if num_dates else np.nan,
        f"{prefix}_win_rate": float(np.nanmean(pnl > 0)),
        f"{prefix}_total_pnl": float(np.nansum(pnl)),
        f"{prefix}_avg_pnl_per_trade": float(np.nanmean(pnl)),
        f"{prefix}_avg_pnl_per_day": float(np.nanmean(pnl_day)),
        f"{prefix}_exposure_day_weighted_pnl_per_day": float(exposure_day_weighted_pnl_per_day),
        f"{prefix}_profit_factor": float(profit_factor(pnl)),
        f"{prefix}_worst_trade_pnl": float(np.nanmin(pnl)),
        f"{prefix}_worst_pnl_per_day": float(np.nanmin(pnl_day)),
        f"{prefix}_best_trade_pnl": float(np.nanmax(pnl)),
        f"{prefix}_avg_actual_dte": float(np.nanmean(dte)),
        f"{prefix}_avg_selected_tenor": float(np.nanmean(selected_tenors)),
    }


def bucket_metrics(selected_cols):
    selected_cols = np.asarray(selected_cols, dtype=int)
    date_idx = np.where(selected_cols >= 0)[0]

    out = {}

    for bucket in BUCKETS:
        out[f"{bucket}_selected_trades"] = 0
        out[f"{bucket}_selected_win_rate"] = np.nan
        out[f"{bucket}_selected_avg_pnl_per_trade"] = np.nan
        out[f"{bucket}_selected_avg_pnl_per_day"] = np.nan
        out[f"{bucket}_selected_exposure_day_weighted_pnl_per_day"] = np.nan
        out[f"{bucket}_selected_total_pnl"] = 0.0
        out[f"{bucket}_selected_worst_trade_pnl"] = np.nan

    if date_idx.size == 0:
        return out

    cols = selected_cols[date_idx]
    selected_buckets = tenor_bucket_array[cols]

    for bucket in BUCKETS:
        bucket_mask = selected_buckets == bucket

        if not bucket_mask.any():
            continue

        bucket_date_idx = date_idx[bucket_mask]
        bucket_cols = cols[bucket_mask]

        pnl = pnl_mat[bucket_date_idx, bucket_cols]
        pnl_day = pnl_per_day_mat[bucket_date_idx, bucket_cols]
        dte = actual_dte_mat[bucket_date_idx, bucket_cols]

        total_dte = np.nansum(dte)

        out[f"{bucket}_selected_trades"] = int(bucket_mask.sum())
        out[f"{bucket}_selected_win_rate"] = float(np.nanmean(pnl > 0))
        out[f"{bucket}_selected_avg_pnl_per_trade"] = float(np.nanmean(pnl))
        out[f"{bucket}_selected_avg_pnl_per_day"] = float(np.nanmean(pnl_day))
        out[f"{bucket}_selected_exposure_day_weighted_pnl_per_day"] = (
            float(np.nansum(pnl) / total_dte) if total_dte > 0 else np.nan
        )
        out[f"{bucket}_selected_total_pnl"] = float(np.nansum(pnl))
        out[f"{bucket}_selected_worst_trade_pnl"] = float(np.nanmin(pnl))

    return out


def tenor_selection_metrics(selected_cols, spec_id):
    selected_cols = np.asarray(selected_cols, dtype=int)
    date_idx_all = np.where(selected_cols >= 0)[0]

    rows = []

    for col_idx, tenor in enumerate(TENORS):
        date_idx = np.where(selected_cols == col_idx)[0]

        if date_idx.size == 0:
            rows.append({
                "spec_id": spec_id,
                "selected_tenor": int(tenor),
                "selected_tenor_bucket": TENOR_BUCKET_MAP[int(tenor)],
                "selected_trades": 0,
                "selected_frequency_total_dates": 0.0,
                "selected_share_of_trades": 0.0,
                "selected_win_rate": np.nan,
                "selected_avg_pnl_per_trade": np.nan,
                "selected_avg_pnl_per_day": np.nan,
                "selected_exposure_day_weighted_pnl_per_day": np.nan,
                "selected_total_pnl": 0.0,
                "selected_worst_trade_pnl": np.nan,
                "selected_worst_pnl_per_day": np.nan,
                "selected_avg_actual_dte": np.nan,
            })
            continue

        pnl = pnl_mat[date_idx, col_idx]
        pnl_day = pnl_per_day_mat[date_idx, col_idx]
        dte = actual_dte_mat[date_idx, col_idx]

        total_dte = np.nansum(dte)

        rows.append({
            "spec_id": spec_id,
            "selected_tenor": int(tenor),
            "selected_tenor_bucket": TENOR_BUCKET_MAP[int(tenor)],
            "selected_trades": int(date_idx.size),
            "selected_frequency_total_dates": float(date_idx.size / num_dates) if num_dates else np.nan,
            "selected_share_of_trades": float(date_idx.size / date_idx_all.size) if date_idx_all.size else 0.0,
            "selected_win_rate": float(np.nanmean(pnl > 0)),
            "selected_avg_pnl_per_trade": float(np.nanmean(pnl)),
            "selected_avg_pnl_per_day": float(np.nanmean(pnl_day)),
            "selected_exposure_day_weighted_pnl_per_day": (
                float(np.nansum(pnl) / total_dte) if total_dte > 0 else np.nan
            ),
            "selected_total_pnl": float(np.nansum(pnl)),
            "selected_worst_trade_pnl": float(np.nanmin(pnl)),
            "selected_worst_pnl_per_day": float(np.nanmin(pnl_day)),
            "selected_avg_actual_dte": float(np.nanmean(dte)),
        })

    return rows


def append_conditional_rows(rows, spec_id, stats):
    for col_idx, tenor in enumerate(TENORS):
        rows.append({
            "spec_id": spec_id,
            "role": "Core",
            "tenor": int(tenor),
            "tenor_bucket": TENOR_BUCKET_MAP[int(tenor)],
            "conditional_obs": int(stats["obs"][col_idx]),
            "conditional_wins": int(stats["wins"][col_idx]),
            "conditional_win_probability": stats["win_prob"][col_idx],
            "conditional_avg_pnl_per_day": stats["avg_pnl_per_day"][col_idx],
            "conditional_aggregate_pnl_per_day": stats["aggregate_pnl_per_day"][col_idx],
            "conditional_avg_pnl_per_trade": stats["avg_pnl_per_trade"][col_idx],
            "conditional_total_pnl": stats["total_pnl"][col_idx],
            "conditional_worst_trade_pnl": stats["worst_trade"][col_idx],
            "conditional_worst_pnl_per_day": stats["worst_pnl_day"][col_idx],
            "conditional_avg_actual_dte": stats["avg_actual_dte"][col_idx],
            "conditional_sample_ok": bool(stats["sample_ok"][col_idx]),
        })


def selected_trade_detail_rows(selected_cols, spec_row):
    selected_cols = np.asarray(selected_cols, dtype=int)
    date_idx = np.where(selected_cols >= 0)[0]

    rows = []

    for idx in date_idx:
        col_idx = selected_cols[idx]
        tenor = int(tenor_array[col_idx])

        rows.append({
            "spec_id": spec_row["spec_id"],
            "date": pd.to_datetime(date_array[idx]),
            "trade_date": int(eligible_dates[idx]),
            "selected_tenor": tenor,
            "selected_tenor_bucket": TENOR_BUCKET_MAP[tenor],

            "outcome_value": float(pnl_mat[idx, col_idx]),
            "pnl_per_day": float(pnl_per_day_mat[idx, col_idx]),
            "actual_dte": float(actual_dte_mat[idx, col_idx]),

            "vrp_log": float(vrp_mat[idx, col_idx]),
            "vrp_z_3m": float(z3m_mat[idx, col_idx]),
            "vrp_z_1y": float(z1y_mat[idx, col_idx]),
            "rsi14": float(rsi_mat[idx, col_idx]),
            "rv21d": float(rv21d_mat[idx, col_idx]),

            "front_vrp_log_min": spec_row["front_vrp_log_min"],
            "middle_vrp_log_min": spec_row["middle_vrp_log_min"],
            "back_vrp_log_min": spec_row["back_vrp_log_min"],

            "front_z_3m_min": spec_row["front_z_3m_min"],
            "middle_z_3m_min": spec_row["middle_z_3m_min"],
            "back_z_3m_min": spec_row["back_z_3m_min"],

            "front_z_1y_min": spec_row["front_z_1y_min"],
            "middle_z_1y_min": spec_row["middle_z_1y_min"],
            "back_z_1y_min": spec_row["back_z_1y_min"],

            "front_rsi14_max": spec_row["front_rsi14_max"],
            "middle_rsi14_max": spec_row["middle_rsi14_max"],
            "back_rsi14_max": spec_row["back_rsi14_max"],

            "front_rv21d_min": spec_row["front_rv21d_min"],
            "middle_rv21d_min": spec_row["middle_rv21d_min"],
            "back_rv21d_min": spec_row["back_rv21d_min"],
        })

    return rows


# -----------------------------
# 6. Run Core-only Phase 3 sweep
# -----------------------------

summary_rows = []
conditional_rows = []
tenor_selection_rows = []

# Store selected cols for top-detail reconstruction later without recomputing all if possible.
selected_cols_by_spec = {}

total_specs = len(core_specs)

print()
print(f"Running Core-only Phase 3 sweep: {total_specs:,} specs")

for i, (_, spec_row) in enumerate(core_specs.iterrows(), start=1):
    spec_id = spec_row["spec_id"]

    pass_matrix = build_pass_matrix(spec_row)
    candidate_dates = pass_matrix.any(axis=1)
    candidate_rows = int(pass_matrix.sum())

    stats = compute_conditional_arrays(pass_matrix)
    selected_cols = select_cols_from_pass_and_stats(pass_matrix, stats)

    selected_cols_by_spec[spec_id] = selected_cols

    row = {
        "spec_id": spec_id,
        "role": "Core",
        "phase": "core_only_phase3_untied_z",
        "candidate_rows": candidate_rows,
        "candidate_dates": int(candidate_dates.sum()),
        "candidate_frequency": float(candidate_dates.sum() / num_dates) if num_dates else np.nan,

        "front_vrp_log_min": spec_row["front_vrp_log_min"],
        "middle_vrp_log_min": spec_row["middle_vrp_log_min"],
        "back_vrp_log_min": spec_row["back_vrp_log_min"],

        "front_z_3m_min": spec_row["front_z_3m_min"],
        "middle_z_3m_min": spec_row["middle_z_3m_min"],
        "back_z_3m_min": spec_row["back_z_3m_min"],

        "front_z_1y_min": spec_row["front_z_1y_min"],
        "middle_z_1y_min": spec_row["middle_z_1y_min"],
        "back_z_1y_min": spec_row["back_z_1y_min"],

        "front_rsi14_max": spec_row["front_rsi14_max"],
        "middle_rsi14_max": spec_row["middle_rsi14_max"],
        "back_rsi14_max": spec_row["back_rsi14_max"],

        "front_rv21d_min": spec_row["front_rv21d_min"],
        "middle_rv21d_min": spec_row["middle_rv21d_min"],
        "back_rv21d_min": spec_row["back_rv21d_min"],
    }

    row.update(summarize_selected_cols(selected_cols, "core"))
    row.update(bucket_metrics(selected_cols))

    summary_rows.append(row)
    append_conditional_rows(conditional_rows, spec_id, stats)
    tenor_selection_rows.extend(tenor_selection_metrics(selected_cols, spec_id))

    if i % 250 == 0 or i == total_specs:
        print(f"Core specs processed: {i:,} / {total_specs:,}")

core_summary = pd.DataFrame(summary_rows)
conditional_stats = pd.DataFrame(conditional_rows)
tenor_selection_summary = pd.DataFrame(tenor_selection_rows)


# -----------------------------
# 7. Add labels / flags / rankings
# -----------------------------

core_summary["vrp_triple"] = (
    core_summary["front_vrp_log_min"].map("{:.2f}".format)
    + " / "
    + core_summary["middle_vrp_log_min"].map("{:.2f}".format)
    + " / "
    + core_summary["back_vrp_log_min"].map("{:.2f}".format)
)

core_summary["z_3m_triple"] = (
    core_summary["front_z_3m_min"].map("{:.2f}".format)
    + " / "
    + core_summary["middle_z_3m_min"].map("{:.2f}".format)
    + " / "
    + core_summary["back_z_3m_min"].map("{:.2f}".format)
)

core_summary["z_1y_triple"] = (
    core_summary["front_z_1y_min"].map("{:.2f}".format)
    + " / "
    + core_summary["middle_z_1y_min"].map("{:.2f}".format)
    + " / "
    + core_summary["back_z_1y_min"].map("{:.2f}".format)
)

core_summary["rsi_triple"] = (
    core_summary["front_rsi14_max"].astype(int).astype(str)
    + " / "
    + core_summary["middle_rsi14_max"].astype(int).astype(str)
    + " / "
    + core_summary["back_rsi14_max"].astype(int).astype(str)
)

core_summary["rv21d_triple"] = (
    core_summary["front_rv21d_min"].map("{:.1f}".format)
    + " / "
    + core_summary["middle_rv21d_min"].map("{:.1f}".format)
    + " / "
    + core_summary["back_rv21d_min"].map("{:.1f}".format)
)

core_summary["meets_core_win_85"] = core_summary["core_win_rate"].ge(0.85)
core_summary["meets_core_win_83"] = core_summary["core_win_rate"].ge(0.83)
core_summary["meets_core_win_82"] = core_summary["core_win_rate"].ge(0.82)
core_summary["meets_core_win_80"] = core_summary["core_win_rate"].ge(0.80)

core_summary["core_win_gap_to_85"] = 0.85 - core_summary["core_win_rate"]

core_summary_by_win = core_summary.sort_values(
    [
        "core_win_rate",
        "core_frequency",
        "core_avg_pnl_per_day",
        "core_total_pnl",
    ],
    ascending=[False, False, False, False],
).reset_index(drop=True)

core_summary_by_win["win_rate_rank"] = np.arange(1, len(core_summary_by_win) + 1)

core_summary_by_frequency_targets_first = core_summary.sort_values(
    [
        "meets_core_win_85",
        "core_frequency",
        "core_win_rate",
        "core_avg_pnl_per_day",
        "core_total_pnl",
        "core_worst_trade_pnl",
    ],
    ascending=[False, False, False, False, False, False],
).reset_index(drop=True)

core_summary_by_frequency_targets_first["frequency_rank_with_targets_first"] = (
    np.arange(1, len(core_summary_by_frequency_targets_first) + 1)
)

core_review = core_summary.merge(
    core_summary_by_win[["spec_id", "win_rate_rank"]],
    on="spec_id",
    how="left",
    validate="one_to_one",
)

core_review = core_review.merge(
    core_summary_by_frequency_targets_first[["spec_id", "frequency_rank_with_targets_first"]],
    on="spec_id",
    how="left",
    validate="one_to_one",
)


# -----------------------------
# 8. Parameter group diagnostics
# -----------------------------

def parameter_group_summary(df, group_col):
    out = (
        df
        .groupby(group_col)
        .agg(
            specs=("spec_id", "nunique"),
            max_core_win_rate=("core_win_rate", "max"),
            median_core_win_rate=("core_win_rate", "median"),
            max_core_frequency=("core_frequency", "max"),
            median_core_frequency=("core_frequency", "median"),
            max_core_avg_pnl_per_day=("core_avg_pnl_per_day", "max"),
            median_core_avg_pnl_per_day=("core_avg_pnl_per_day", "median"),
            max_core_total_pnl=("core_total_pnl", "max"),
            specs_core_win_85_plus=("meets_core_win_85", "sum"),
            specs_core_win_83_plus=("meets_core_win_83", "sum"),
            specs_core_win_82_plus=("meets_core_win_82", "sum"),
            specs_core_win_80_plus=("meets_core_win_80", "sum"),
        )
        .reset_index()
        .sort_values(
            [
                "max_core_win_rate",
                "max_core_frequency",
                "max_core_avg_pnl_per_day",
            ],
            ascending=[False, False, False],
        )
    )

    return out


core_by_vrp = parameter_group_summary(core_review, "vrp_triple")
core_by_z3m = parameter_group_summary(core_review, "z_3m_triple")
core_by_z1y = parameter_group_summary(core_review, "z_1y_triple")
core_by_rsi = parameter_group_summary(core_review, "rsi_triple")
core_by_rv21d = parameter_group_summary(core_review, "rv21d_triple")


# -----------------------------
# 9. Tenor diagnostics and selected trade detail
# -----------------------------

def tenor_table_for_specs(spec_ids):
    out = tenor_selection_summary.loc[
        tenor_selection_summary["spec_id"].isin(spec_ids)
    ].merge(
        core_review[
            [
                "spec_id",
                "win_rate_rank",
                "frequency_rank_with_targets_first",
                "core_trades",
                "core_frequency",
                "core_win_rate",
                "core_avg_pnl_per_day",
                "core_total_pnl",
                "vrp_triple",
                "z_3m_triple",
                "z_1y_triple",
                "rsi_triple",
                "rv21d_triple",
            ]
        ],
        on="spec_id",
        how="left",
        validate="many_to_one",
    )

    return out.sort_values(
        ["win_rate_rank", "selected_tenor"],
        ascending=[True, True],
    )


top_win_spec_ids = (
    core_review
    .sort_values(
        ["core_win_rate", "core_frequency", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(20)["spec_id"]
    .tolist()
)

target_frequency_spec_ids = (
    core_review
    .loc[core_review["meets_core_win_85"]]
    .sort_values(
        ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(20)["spec_id"]
    .tolist()
)

above_83_frequency_spec_ids = (
    core_review
    .loc[core_review["core_win_rate"].ge(0.83)]
    .sort_values(
        ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(20)["spec_id"]
    .tolist()
)

above_82_frequency_spec_ids = (
    core_review
    .loc[core_review["core_win_rate"].ge(0.82)]
    .sort_values(
        ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(20)["spec_id"]
    .tolist()
)

tenor_top_win = tenor_table_for_specs(top_win_spec_ids)
tenor_target_frequency = tenor_table_for_specs(target_frequency_spec_ids)
tenor_above_83_frequency = tenor_table_for_specs(above_83_frequency_spec_ids)
tenor_above_82_frequency = tenor_table_for_specs(above_82_frequency_spec_ids)

detail_spec_ids = list(dict.fromkeys(
    top_win_spec_ids
    + target_frequency_spec_ids
    + above_83_frequency_spec_ids
    + above_82_frequency_spec_ids
))

selected_trade_detail = []

spec_lookup = core_specs.set_index("spec_id")

for spec_id in detail_spec_ids:
    selected_cols = selected_cols_by_spec[spec_id]
    spec_row = spec_lookup.loc[spec_id].copy()
    spec_row["spec_id"] = spec_id
    selected_trade_detail.extend(selected_trade_detail_rows(selected_cols, spec_row))

selected_trade_detail = pd.DataFrame(selected_trade_detail)


# -----------------------------
# 10. Display outputs
# -----------------------------

print()
print("Core-only Phase 3 sweep summary:")
display(pd.DataFrame([{
    "core_specs_tested": len(core_review),
    "specs_core_win_85_plus": int(core_review["meets_core_win_85"].sum()),
    "specs_core_win_83_plus": int(core_review["meets_core_win_83"].sum()),
    "specs_core_win_82_plus": int(core_review["meets_core_win_82"].sum()),
    "specs_core_win_80_plus": int(core_review["meets_core_win_80"].sum()),
    "max_core_win_rate": core_review["core_win_rate"].max(),
    "median_core_win_rate": core_review["core_win_rate"].median(),
    "max_core_frequency": core_review["core_frequency"].max(),
    "median_core_frequency": core_review["core_frequency"].median(),
    "max_core_avg_pnl_per_day": core_review["core_avg_pnl_per_day"].max(),
    "median_core_avg_pnl_per_day": core_review["core_avg_pnl_per_day"].median(),
}]))

review_cols = [
    "frequency_rank_with_targets_first",
    "win_rate_rank",
    "meets_core_win_85",
    "core_trades",
    "core_frequency",
    "core_win_rate",
    "core_win_gap_to_85",
    "core_avg_pnl_per_trade",
    "core_avg_pnl_per_day",
    "core_exposure_day_weighted_pnl_per_day",
    "core_total_pnl",
    "core_profit_factor",
    "core_worst_trade_pnl",
    "core_worst_pnl_per_day",
    "core_avg_actual_dte",
    "core_avg_selected_tenor",

    "front_selected_trades",
    "front_selected_win_rate",
    "front_selected_avg_pnl_per_trade",
    "front_selected_avg_pnl_per_day",
    "front_selected_total_pnl",
    "front_selected_worst_trade_pnl",

    "middle_selected_trades",
    "middle_selected_win_rate",
    "middle_selected_avg_pnl_per_trade",
    "middle_selected_avg_pnl_per_day",
    "middle_selected_total_pnl",
    "middle_selected_worst_trade_pnl",

    "back_selected_trades",
    "back_selected_win_rate",
    "back_selected_avg_pnl_per_trade",
    "back_selected_avg_pnl_per_day",
    "back_selected_total_pnl",
    "back_selected_worst_trade_pnl",

    "vrp_triple",
    "z_3m_triple",
    "z_1y_triple",
    "rsi_triple",
    "rv21d_triple",
    "spec_id",
]

tenor_cols = [
    "win_rate_rank",
    "frequency_rank_with_targets_first",
    "core_trades",
    "core_frequency",
    "core_win_rate",
    "core_avg_pnl_per_day",
    "core_total_pnl",

    "selected_tenor",
    "selected_tenor_bucket",
    "selected_trades",
    "selected_frequency_total_dates",
    "selected_share_of_trades",
    "selected_win_rate",
    "selected_avg_pnl_per_trade",
    "selected_avg_pnl_per_day",
    "selected_exposure_day_weighted_pnl_per_day",
    "selected_total_pnl",
    "selected_worst_trade_pnl",
    "selected_worst_pnl_per_day",
    "selected_avg_actual_dte",

    "vrp_triple",
    "z_3m_triple",
    "z_1y_triple",
    "rsi_triple",
    "rv21d_triple",
    "spec_id",
]

print()
print("Top Core specs by win rate:")
display(
    core_review
    .sort_values(
        ["core_win_rate", "core_frequency", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    [review_cols]
    .head(100)
)

print()
print("Top Core specs with win rate >= 85%, ranked by frequency:")
display(
    core_review
    .loc[core_review["meets_core_win_85"], review_cols]
    .sort_values(
        ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(100)
)

print()
print("Highest-frequency Core specs with win rate >= 83%:")
display(
    core_review
    .loc[core_review["core_win_rate"].ge(0.83), review_cols]
    .sort_values(
        ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(100)
)

print()
print("Highest-frequency Core specs with win rate >= 82%:")
display(
    core_review
    .loc[core_review["core_win_rate"].ge(0.82), review_cols]
    .sort_values(
        ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
        ascending=[False, False, False, False],
    )
    .head(100)
)

print()
print("Tenor / DTE selection diagnostics for top Core specs by win rate:")
display(tenor_top_win[tenor_cols].head(180))

print()
print("Tenor / DTE selection diagnostics for Core specs with win rate >= 85%, ranked by frequency:")
display(tenor_target_frequency[tenor_cols].head(180))

print()
print("Tenor / DTE selection diagnostics for highest-frequency Core specs with win rate >= 83%:")
display(tenor_above_83_frequency[tenor_cols].head(180))

print()
print("Tenor / DTE selection diagnostics for highest-frequency Core specs with win rate >= 82%:")
display(tenor_above_82_frequency[tenor_cols].head(180))

print()
print("Core parameter diagnostics by VRP triple:")
display(core_by_vrp)

print()
print("Core parameter diagnostics by 3m z-score triple:")
display(core_by_z3m)

print()
print("Core parameter diagnostics by 1y z-score triple:")
display(core_by_z1y)

print()
print("Core parameter diagnostics by RSI cap triple:")
display(core_by_rsi)

print()
print("Core parameter diagnostics by RV21D floor triple:")
display(core_by_rv21d)

print()
print("Selected trade detail sample for top specs:")
display(selected_trade_detail.head(100))


# -----------------------------
# 11. Save outputs
# -----------------------------

safe_start = pd.to_datetime(date_array.min()).strftime("%Y%m%d")
safe_end = pd.to_datetime(date_array.max()).strftime("%Y%m%d")

core_specs_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_specs_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

grid_summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_grid_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_summary_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

conditional_stats_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_conditional_stats_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

tenor_selection_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_tenor_selection_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

selected_trade_detail_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_selected_trade_detail_top_specs_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

top_by_win_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_top_by_win_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

target_by_frequency_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_win85_by_frequency_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

above_83_frequency_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_win83_by_frequency_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

above_82_frequency_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_win82_by_frequency_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

tenor_top_win_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_tenor_top_by_win_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

tenor_target_frequency_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_tenor_win85_by_frequency_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

tenor_above_83_frequency_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_tenor_win83_by_frequency_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

tenor_above_82_frequency_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_tenor_win82_by_frequency_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_vrp_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_by_vrp_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_z3m_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_by_z3m_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_z1y_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_by_z1y_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_rsi_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_by_rsi_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_by_rv21d_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_by_rv21d_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

core_specs.to_csv(core_specs_path, index=False)
grid_summary.to_csv(grid_summary_path, index=False)
core_review.to_csv(core_summary_path, index=False)
conditional_stats.to_csv(conditional_stats_path, index=False)
tenor_selection_summary.to_csv(tenor_selection_path, index=False)
selected_trade_detail.to_csv(selected_trade_detail_path, index=False)

core_review.sort_values(
    ["core_win_rate", "core_frequency", "core_avg_pnl_per_day", "core_total_pnl"],
    ascending=[False, False, False, False],
).head(1000).to_csv(top_by_win_path, index=False)

core_review.loc[
    core_review["meets_core_win_85"]
].sort_values(
    ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
    ascending=[False, False, False, False],
).to_csv(target_by_frequency_path, index=False)

core_review.loc[
    core_review["core_win_rate"].ge(0.83)
].sort_values(
    ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
    ascending=[False, False, False, False],
).to_csv(above_83_frequency_path, index=False)

core_review.loc[
    core_review["core_win_rate"].ge(0.82)
].sort_values(
    ["core_frequency", "core_win_rate", "core_avg_pnl_per_day", "core_total_pnl"],
    ascending=[False, False, False, False],
).to_csv(above_82_frequency_path, index=False)

tenor_top_win.to_csv(tenor_top_win_path, index=False)
tenor_target_frequency.to_csv(tenor_target_frequency_path, index=False)
tenor_above_83_frequency.to_csv(tenor_above_83_frequency_path, index=False)
tenor_above_82_frequency.to_csv(tenor_above_82_frequency_path, index=False)

core_by_vrp.to_csv(core_by_vrp_path, index=False)
core_by_z3m.to_csv(core_by_z3m_path, index=False)
core_by_z1y.to_csv(core_by_z1y_path, index=False)
core_by_rsi.to_csv(core_by_rsi_path, index=False)
core_by_rv21d.to_csv(core_by_rv21d_path, index=False)

print()
print("Cell 7 outputs saved:")
print(f"Core specs:                    {core_specs_path}")
print(f"Grid summary:                  {grid_summary_path}")
print(f"Core summary:                  {core_summary_path}")
print(f"Conditional stats:             {conditional_stats_path}")
print(f"Tenor selection summary:       {tenor_selection_path}")
print(f"Selected trade detail:         {selected_trade_detail_path}")
print(f"Top by win rate:               {top_by_win_path}")
print(f"Win >=85 by frequency:         {target_by_frequency_path}")
print(f"Win >=83 by frequency:         {above_83_frequency_path}")
print(f"Win >=82 by frequency:         {above_82_frequency_path}")
print(f"Tenor top by win:              {tenor_top_win_path}")
print(f"Tenor win >=85 by frequency:   {tenor_target_frequency_path}")
print(f"Tenor win >=83 by frequency:   {tenor_above_83_frequency_path}")
print(f"Tenor win >=82 by frequency:   {tenor_above_82_frequency_path}")
print(f"Core by VRP:                   {core_by_vrp_path}")
print(f"Core by 3m z-score:            {core_by_z3m_path}")
print(f"Core by 1y z-score:            {core_by_z1y_path}")
print(f"Core by RSI:                   {core_by_rsi_path}")
print(f"Core by RV21D:                 {core_by_rv21d_path}")

print()
print("Cell 7 complete.")

Cell 7: Core-only Phase 3 sweep — untied z-scores
Clean panel path: C:\Users\patri\vrp_project\data\processed\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_panel_20200102_20260623_20260704_085138.parquet
Run timestamp:    20260704_101706

Actual DTE source:
C:\Users\patri\vrp_project\data\processed\put_candidate_universe_pricing_v0_1.parquet

Actual DTE availability:

,rows,actual_dte_non_null,actual_dte_non_null_pct,fallback_to_tenor_rows,fallback_to_tenor_pct
0,14565,14565,1.0,0,0.0

Core-only Phase 3 grid summary:

,valid_vrp_triples,valid_z_3m_triples,valid_z_1y_triples,valid_rsi_triples,valid_rv21d_triples,total_core_specs
0,1,18,18,3,2,1944

Core-only Phase 3 specs sample:

,spec_id,role,phase,forecast_denominator,front_vrp_log_min,middle_vrp_log_min,back_vrp_log_min,front_z_3m_min,middle_z_3m_min,back_z_3m_min,front_z_1y_min,middle_z_1y_min,back_z_1y_min,front_rsi14_max,middle_rsi14_max,back_rsi14_max,front_rv21d_min,middle_rv21d_min,back_rv21d_min,phase_z_3m_equals_z_1y
0,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.70,70,68,65,7.5,8.5,8.5,False
1,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.70,70,68,65,8.0,8.5,8.5,False
2,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.70,70,68,66,7.5,8.5,8.5,False
3,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.70,70,68,66,8.0,8.5,8.5,False
4,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.70,70,68,67,7.5,8.5,8.5,False
5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.70,70,68,67,8.0,8.5,8.5,False
6,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.75,70,68,65,7.5,8.5,8.5,False
7,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.75,70,68,65,8.0,8.5,8.5,False
8,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.75,70,68,66,7.5,8.5,8.5,False
9,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.75,70,68,66,8.0,8.5,8.5,False
10,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.75,70,68,67,7.5,8.5,8.5,False
11,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.75,70,68,67,8.0,8.5,8.5,False
12,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.80,70,68,65,7.5,8.5,8.5,False
13,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.80,70,68,65,8.0,8.5,8.5,False
14,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.80,70,68,66,7.5,8.5,8.5,False
15,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.80,70,68,66,8.0,8.5,8.5,False
16,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.80,70,68,67,7.5,8.5,8.5,False
17,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.70,0.80,70,68,67,8.0,8.5,8.5,False
18,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.75,0.75,70,68,65,7.5,8.5,8.5,False
19,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...,Core,core_only_phase3_untied_z,har_total_simple,0.6,0.7,0.7,0.5,0.7,0.7,0.5,0.75,0.75,70,68,65,8.0,8.5,8.5,False

Cell 7 input summary:

,eligible_rows_after_complete_date_filter,eligible_dates,first_date,last_date,unique_tenors,core_specs_to_test,min_conditional_obs,forecast_model,selection_rule
0,13302,1478,2020-07-01,2026-05-19,9,1944,20,har_total_simple,strict_highest_conditional_win_probability_no_...

Running Core-only Phase 3 sweep: 1,944 specs
Core specs processed: 250 / 1,944
Core specs processed: 500 / 1,944
Core specs processed: 750 / 1,944
Core specs processed: 1,000 / 1,944
Core specs processed: 1,250 / 1,944
Core specs processed: 1,500 / 1,944
Core specs processed: 1,750 / 1,944
Core specs processed: 1,944 / 1,944

Core-only Phase 3 sweep summary:

,core_specs_tested,specs_core_win_85_plus,specs_core_win_83_plus,specs_core_win_82_plus,specs_core_win_80_plus,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day
0,1944,0,0,267,1581,0.828996,0.811323,0.217185,0.201624,378.467721,328.016536

Top Core specs by win rate:

,frequency_rank_with_targets_first,win_rate_rank,meets_core_win_85,core_trades,core_frequency,core_win_rate,core_win_gap_to_85,core_avg_pnl_per_trade,core_avg_pnl_per_day,core_exposure_day_weighted_pnl_per_day,...,back_selected_avg_pnl_per_trade,back_selected_avg_pnl_per_day,back_selected_total_pnl,back_selected_worst_trade_pnl,vrp_triple,z_3m_triple,z_1y_triple,rsi_triple,rv21d_triple,spec_id
1603,1900,1,False,269,0.182003,0.828996,0.021004,9196.171985,366.987325,427.765911,...,14985.591578,494.061362,1.543516e+06,-92579.572354,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
1387,1901,2,False,269,0.182003,0.828996,0.021004,9201.620806,366.772697,427.501899,...,14704.336032,486.099090,1.573364e+06,-92579.572354,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
1495,1902,3,False,269,0.182003,0.828996,0.021004,9201.620806,366.772697,427.501899,...,14744.438955,485.545755,1.548166e+06,-92579.572354,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.75,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
1605,1903,4,False,269,0.182003,0.828996,0.021004,9196.361552,365.739217,426.226957,...,14852.031666,490.208980,1.574315e+06,-92579.572354,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 66,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
1389,1904,5,False,269,0.182003,0.828996,0.021004,9201.810373,365.524589,425.965753,...,14583.303450,482.603947,1.604163e+06,-92579.572354,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.70,0.70 / 0.75 / 0.75,70 / 68 / 66,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1719,1944,96,False,268,0.181326,0.824627,0.025373,9127.919999,351.888264,411.209037,...,16207.514354,510.727415,1.717997e+06,-85194.299611,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.75,0.70 / 0.75 / 0.80,70 / 68 / 66,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.75_0...
1591,1861,97,False,272,0.184032,0.823529,0.026471,8675.793389,342.007513,400.988242,...,14985.591578,494.061362,1.543516e+06,-92579.572354,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.70 / 0.70 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
1375,1862,98,False,272,0.184032,0.823529,0.026471,8681.182112,341.795252,400.760613,...,14704.336032,486.099090,1.573364e+06,-92579.572354,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.70,0.70 / 0.70 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
1483,1863,99,False,272,0.184032,0.823529,0.026471,8681.182112,341.795252,400.760613,...,14744.438955,485.545755,1.548166e+06,-92579.572354,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.75,0.70 / 0.70 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
1593,1864,100,False,272,0.184032,0.823529,0.026471,8675.980865,340.773171,399.571079,...,14852.031666,490.208980,1.574315e+06,-92579.572354,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.70 / 0.70 / 0.75,70 / 68 / 66,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...

Top Core specs with win rate >= 85%, ranked by frequency:

Empty DataFrame
Columns: [frequency_rank_with_targets_first, win_rate_rank, meets_core_win_85, core_trades, core_frequency, core_win_rate, core_win_gap_to_85, core_avg_pnl_per_trade, core_avg_pnl_per_day, core_exposure_day_weighted_pnl_per_day, core_total_pnl, core_profit_factor, core_worst_trade_pnl, core_worst_pnl_per_day, core_avg_actual_dte, core_avg_selected_tenor, front_selected_trades, front_selected_win_rate, front_selected_avg_pnl_per_trade, front_selected_avg_pnl_per_day, front_selected_total_pnl, front_selected_worst_trade_pnl, middle_selected_trades, middle_selected_win_rate, middle_selected_avg_pnl_per_trade, middle_selected_avg_pnl_per_day, middle_selected_total_pnl, middle_selected_worst_trade_pnl, back_selected_trades, back_selected_win_rate, back_selected_avg_pnl_per_trade, back_selected_avg_pnl_per_day, back_selected_total_pnl, back_selected_worst_trade_pnl, vrp_triple, z_3m_triple, z_1y_triple, rsi_triple, rv21d_triple, spec_id]
Index: []

[0 rows x 40 columns]

Highest-frequency Core specs with win rate >= 83%:

Empty DataFrame
Columns: [frequency_rank_with_targets_first, win_rate_rank, meets_core_win_85, core_trades, core_frequency, core_win_rate, core_win_gap_to_85, core_avg_pnl_per_trade, core_avg_pnl_per_day, core_exposure_day_weighted_pnl_per_day, core_total_pnl, core_profit_factor, core_worst_trade_pnl, core_worst_pnl_per_day, core_avg_actual_dte, core_avg_selected_tenor, front_selected_trades, front_selected_win_rate, front_selected_avg_pnl_per_trade, front_selected_avg_pnl_per_day, front_selected_total_pnl, front_selected_worst_trade_pnl, middle_selected_trades, middle_selected_win_rate, middle_selected_avg_pnl_per_trade, middle_selected_avg_pnl_per_day, middle_selected_total_pnl, middle_selected_worst_trade_pnl, back_selected_trades, back_selected_win_rate, back_selected_avg_pnl_per_trade, back_selected_avg_pnl_per_day, back_selected_total_pnl, back_selected_worst_trade_pnl, vrp_triple, z_3m_triple, z_1y_triple, rsi_triple, rv21d_triple, spec_id]
Index: []

[0 rows x 40 columns]

Highest-frequency Core specs with win rate >= 82%:

,frequency_rank_with_targets_first,win_rate_rank,meets_core_win_85,core_trades,core_frequency,core_win_rate,core_win_gap_to_85,core_avg_pnl_per_trade,core_avg_pnl_per_day,core_exposure_day_weighted_pnl_per_day,...,back_selected_avg_pnl_per_trade,back_selected_avg_pnl_per_day,back_selected_total_pnl,back_selected_worst_trade_pnl,vrp_triple,z_3m_triple,z_1y_triple,rsi_triple,rv21d_triple,spec_id
1243,1135,244,False,295,0.199594,0.820339,0.029661,8191.613303,330.237519,394.148740,...,14985.591578,494.061362,1.543516e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.80 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.60_0.80_0...
1135,1136,245,False,295,0.199594,0.820339,0.029661,8201.769281,329.703454,394.187347,...,14985.591578,494.061362,1.543516e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.60_0.75_0...
1027,1137,246,False,295,0.199594,0.820339,0.029661,8206.737866,329.507742,393.976838,...,14744.438955,485.545755,1.548166e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.60_0.75_0...
919,1138,247,False,295,0.199594,0.820339,0.029661,8248.884346,329.313367,394.651457,...,14985.591578,494.061362,1.543516e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.70 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.60_0.70_0...
703,1139,248,False,295,0.199594,0.820339,0.029661,8253.852931,329.117656,394.441376,...,14704.336032,486.099090,1.573364e+06,-92579.572354,0.60 / 0.70 / 0.70,0.60 / 0.70 / 0.70,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.60_0.70_0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,1704,36,False,276,0.186739,0.826087,0.023913,9071.692583,361.099965,422.010307,...,14620.051058,482.001257,1.578966e+06,-92579.572354,0.60 / 0.70 / 0.70,0.50 / 0.70 / 0.75,0.70 / 0.75 / 0.75,70 / 68 / 66,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...
643,1705,127,False,276,0.186739,0.822464,0.027536,8290.759733,360.884766,410.890588,...,14807.342717,538.591944,1.495542e+06,-85194.299611,0.60 / 0.70 / 0.70,0.50 / 0.80 / 0.80,0.70 / 0.80 / 0.80,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.80_0...
319,1706,128,False,276,0.186739,0.822464,0.027536,8341.835612,360.452165,411.353695,...,14807.342717,538.591944,1.495542e+06,-85194.299611,0.60 / 0.70 / 0.70,0.50 / 0.70 / 0.80,0.70 / 0.80 / 0.80,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.70_0...
535,1707,129,False,276,0.186739,0.822464,0.027536,8301.614854,360.313935,410.912070,...,14807.342717,538.591944,1.495542e+06,-85194.299611,0.60 / 0.70 / 0.70,0.50 / 0.75 / 0.80,0.70 / 0.80 / 0.80,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.75_0...
645,1708,130,False,276,0.186739,0.822464,0.027536,8290.944492,359.668313,409.356114,...,14676.356139,533.380941,1.526341e+06,-85194.299611,0.60 / 0.70 / 0.70,0.50 / 0.80 / 0.80,0.70 / 0.80 / 0.80,70 / 68 / 66,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.50_0.80_0...

Tenor / DTE selection diagnostics for top Core specs by win rate:

,win_rate_rank,frequency_rank_with_targets_first,core_trades,core_frequency,core_win_rate,core_avg_pnl_per_day,core_total_pnl,selected_tenor,selected_tenor_bucket,selected_trades,...,selected_total_pnl,selected_worst_trade_pnl,selected_worst_pnl_per_day,selected_avg_actual_dte,vrp_triple,z_3m_triple,z_1y_triple,rsi_triple,rv21d_triple,spec_id
144,1,1900,269,0.182003,0.828996,366.987325,2.473770e+06,9,front,32,...,-3.745290e+03,-99982.493610,-11109.165957,9.625000,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
145,1,1900,269,0.182003,0.828996,366.987325,2.473770e+06,12,front,21,...,7.949040e+04,-40422.157434,-2694.810496,11.619048,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
146,1,1900,269,0.182003,0.828996,366.987325,2.473770e+06,15,front,55,...,2.850691e+05,-78761.670342,-4633.039432,16.309091,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
147,1,1900,269,0.182003,0.828996,366.987325,2.473770e+06,18,middle,15,...,6.121775e+04,-40254.799314,-2515.924957,17.400000,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
148,1,1900,269,0.182003,0.828996,366.987325,2.473770e+06,21,middle,18,...,1.776778e+05,-76881.908203,-3342.691661,22.388889,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,20,1928,268,0.181326,0.828358,365.979497,2.438812e+06,21,middle,16,...,1.541355e+05,-76881.908203,-3342.691661,22.125000,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.75_0...
167,20,1928,268,0.181326,0.828358,365.979497,2.438812e+06,24,middle,23,...,2.989337e+05,-33735.351540,-1606.445311,23.043478,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.75_0...
168,20,1928,268,0.181326,0.828358,365.979497,2.438812e+06,27,back,6,...,1.986023e+04,-92579.572354,-3703.182894,27.333333,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.75_0...
169,20,1928,268,0.181326,0.828358,365.979497,2.438812e+06,30,back,94,...,1.474520e+06,-85194.299611,-2839.809987,30.138298,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.75_0...
170,20,1928,268,0.181326,0.828358,365.979497,2.438812e+06,33,back,3,...,4.913617e+04,11447.380926,369.270352,31.000000,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.80,0.70 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.75_0...

Tenor / DTE selection diagnostics for Core specs with win rate >= 85%, ranked by frequency:

Empty DataFrame
Columns: [win_rate_rank, frequency_rank_with_targets_first, core_trades, core_frequency, core_win_rate, core_avg_pnl_per_day, core_total_pnl, selected_tenor, selected_tenor_bucket, selected_trades, selected_frequency_total_dates, selected_share_of_trades, selected_win_rate, selected_avg_pnl_per_trade, selected_avg_pnl_per_day, selected_exposure_day_weighted_pnl_per_day, selected_total_pnl, selected_worst_trade_pnl, selected_worst_pnl_per_day, selected_avg_actual_dte, vrp_triple, z_3m_triple, z_1y_triple, rsi_triple, rv21d_triple, spec_id]
Index: []

[0 rows x 26 columns]

Tenor / DTE selection diagnostics for highest-frequency Core specs with win rate >= 83%:

Empty DataFrame
Columns: [win_rate_rank, frequency_rank_with_targets_first, core_trades, core_frequency, core_win_rate, core_avg_pnl_per_day, core_total_pnl, selected_tenor, selected_tenor_bucket, selected_trades, selected_frequency_total_dates, selected_share_of_trades, selected_win_rate, selected_avg_pnl_per_trade, selected_avg_pnl_per_day, selected_exposure_day_weighted_pnl_per_day, selected_total_pnl, selected_worst_trade_pnl, selected_worst_pnl_per_day, selected_avg_actual_dte, vrp_triple, z_3m_triple, z_1y_triple, rsi_triple, rv21d_triple, spec_id]
Index: []

[0 rows x 26 columns]

Tenor / DTE selection diagnostics for highest-frequency Core specs with win rate >= 82%:

,win_rate_rank,frequency_rank_with_targets_first,core_trades,core_frequency,core_win_rate,core_avg_pnl_per_day,core_total_pnl,selected_tenor,selected_tenor_bucket,selected_trades,...,selected_total_pnl,selected_worst_trade_pnl,selected_worst_pnl_per_day,selected_avg_actual_dte,vrp_triple,z_3m_triple,z_1y_triple,rsi_triple,rv21d_triple,spec_id
144,229,1252,290,0.196211,0.820690,325.038722,2.412970e+06,9,front,30,...,-1.783063e+04,-99982.493610,-11109.165957,9.633333,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
145,229,1252,290,0.196211,0.820690,325.038722,2.412970e+06,12,front,28,...,-2.780579e+04,-60819.972574,-4054.664838,11.678571,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
146,229,1252,290,0.196211,0.820690,325.038722,2.412970e+06,15,front,71,...,3.456507e+05,-78761.670342,-4633.039432,16.211268,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
147,229,1252,290,0.196211,0.820690,325.038722,2.412970e+06,18,middle,15,...,6.121775e+04,-40254.799314,-2515.924957,17.400000,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
148,229,1252,290,0.196211,0.820690,325.038722,2.412970e+06,21,middle,18,...,1.776778e+05,-76881.908203,-3342.691661,22.388889,0.60 / 0.70 / 0.70,0.70 / 0.70 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,263,1280,289,0.195535,0.820069,323.958976,2.378012e+06,21,middle,16,...,1.541355e+05,-76881.908203,-3342.691661,22.125000,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.75_0...
167,263,1280,289,0.195535,0.820069,323.958976,2.378012e+06,24,middle,23,...,2.989337e+05,-33735.351540,-1606.445311,23.043478,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.75_0...
168,263,1280,289,0.195535,0.820069,323.958976,2.378012e+06,27,back,6,...,1.986023e+04,-92579.572354,-3703.182894,27.333333,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.75_0...
169,263,1280,289,0.195535,0.820069,323.958976,2.378012e+06,30,back,94,...,1.474520e+06,-85194.299611,-2839.809987,30.138298,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.75_0...
170,263,1280,289,0.195535,0.820069,323.958976,2.378012e+06,33,back,3,...,4.913617e+04,11447.380926,369.270352,31.000000,0.60 / 0.70 / 0.70,0.70 / 0.75 / 0.80,0.60 / 0.75 / 0.75,70 / 68 / 65,8.0 / 8.5 / 8.5,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.75_0...

Core parameter diagnostics by VRP triple:

,vrp_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_83_plus,specs_core_win_82_plus,specs_core_win_80_plus
0,0.60 / 0.70 / 0.70,1944,0.828996,0.811323,0.217185,0.201624,378.467721,328.016536,2.587287e+06,0,0,267,1581

Core parameter diagnostics by 3m z-score triple:

,z_3m_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_83_plus,specs_core_win_82_plus,specs_core_win_80_plus
14,0.70 / 0.70 / 0.80,108,0.828996,0.812184,0.209743,0.199594,371.283566,320.935889,2.530905e+06,0,0,18,92
12,0.70 / 0.70 / 0.70,108,0.828996,0.812184,0.209743,0.199594,371.092391,319.086073,2.532940e+06,0,0,18,92
13,0.70 / 0.70 / 0.75,108,0.828996,0.812184,0.209743,0.199594,371.092391,318.100634,2.540535e+06,0,0,18,92
11,0.60 / 0.80 / 0.80,108,0.828467,0.811981,0.213802,0.202977,378.467721,336.095836,2.543429e+06,0,0,18,89
10,0.60 / 0.75 / 0.80,108,0.828467,0.811981,0.213802,0.202977,377.956198,335.534119,2.546425e+06,0,0,18,89
9,0.60 / 0.75 / 0.75,108,0.828467,0.811981,0.213802,0.202977,377.768747,333.906495,2.556054e+06,0,0,18,89
8,0.60 / 0.70 / 0.80,108,0.828467,0.811981,0.213802,0.202977,375.958988,335.123835,2.565358e+06,0,0,18,89
6,0.60 / 0.70 / 0.70,108,0.828467,0.811981,0.213802,0.202977,375.771537,334.337820,2.567393e+06,0,0,18,89
7,0.60 / 0.70 / 0.75,108,0.828467,0.811981,0.213802,0.202977,375.771537,333.497689,2.574987e+06,0,0,18,89
17,0.70 / 0.80 / 0.80,108,0.828358,0.811546,0.209066,0.198917,371.674983,320.366388,2.491532e+06,0,0,17,91
16,0.70 / 0.75 / 0.80,108,0.828358,0.811546,0.209066,0.198917,371.151564,319.800665,2.494528e+06,0,0,17,91
15,0.70 / 0.75 / 0.75,108,0.828358,0.811546,0.209066,0.198917,370.959754,316.709899,2.504157e+06,0,0,17,91
5,0.50 / 0.80 / 0.80,108,0.826087,0.810492,0.217185,0.205007,373.479055,330.254988,2.555728e+06,0,0,9,83
4,0.50 / 0.75 / 0.80,108,0.826087,0.810492,0.217185,0.205007,372.975702,329.698249,2.558724e+06,0,0,9,83
3,0.50 / 0.75 / 0.75,108,0.826087,0.810492,0.217185,0.205007,372.791246,327.607111,2.568354e+06,0,0,9,83
2,0.50 / 0.70 / 0.80,108,0.826087,0.810492,0.217185,0.205007,371.010397,329.291602,2.577658e+06,0,0,9,83
0,0.50 / 0.70 / 0.70,108,0.826087,0.810492,0.217185,0.205007,370.825940,327.692927,2.579693e+06,0,0,9,83
1,0.50 / 0.70 / 0.75,108,0.826087,0.810492,0.217185,0.205007,370.825940,327.196121,2.587287e+06,0,0,9,83

Core parameter diagnostics by 1y z-score triple:

,z_1y_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_83_plus,specs_core_win_82_plus,specs_core_win_80_plus
15,0.70 / 0.75 / 0.75,108,0.828996,0.822461,0.191475,0.186739,371.819085,359.480690,2.504357e+06,0,0,78,108
17,0.70 / 0.80 / 0.80,108,0.825279,0.818838,0.191475,0.186739,369.171290,355.995932,2.493079e+06,0,0,48,108
16,0.70 / 0.75 / 0.80,108,0.825279,0.818838,0.191475,0.186739,364.685951,351.413153,2.511951e+06,0,0,48,108
13,0.70 / 0.70 / 0.75,108,0.823529,0.817202,0.193505,0.188769,347.237842,335.446900,2.390402e+06,0,0,45,108
12,0.70 / 0.70 / 0.70,108,0.821168,0.814944,0.194858,0.190122,340.483659,327.681924,2.436977e+06,0,0,24,108
9,0.60 / 0.75 / 0.75,108,0.820690,0.815121,0.206360,0.201286,330.237519,320.665837,2.461293e+06,0,0,24,108
14,0.70 / 0.70 / 0.80,108,0.819853,0.813618,0.193505,0.188769,340.181963,327.224540,2.397996e+06,0,0,0,108
7,0.60 / 0.70 / 0.75,108,0.818493,0.813017,0.207713,0.202639,312.369182,302.885759,2.366187e+06,0,0,0,108
11,0.60 / 0.80 / 0.80,108,0.817241,0.811760,0.206360,0.201286,327.778211,316.789496,2.450015e+06,0,0,0,108
10,0.60 / 0.75 / 0.80,108,0.817241,0.811760,0.206360,0.201286,323.612168,312.534819,2.468887e+06,0,0,0,108
6,0.60 / 0.70 / 0.70,108,0.815700,0.810311,0.208390,0.203315,306.858290,296.082937,2.411200e+06,0,0,0,108
8,0.60 / 0.70 / 0.80,108,0.815068,0.809678,0.207713,0.202639,305.788446,294.934997,2.373781e+06,0,0,0,108
3,0.50 / 0.75 / 0.75,108,0.808442,0.800950,0.217185,0.210758,378.467721,362.959104,2.579693e+06,0,0,0,54
5,0.50 / 0.80 / 0.80,108,0.805195,0.797740,0.217185,0.210758,377.061978,360.033536,2.581351e+06,0,0,0,48
4,0.50 / 0.75 / 0.80,108,0.805195,0.797740,0.217185,0.210758,372.122012,355.091017,2.587287e+06,0,0,0,48
1,0.50 / 0.70 / 0.75,108,0.805195,0.799358,0.217185,0.210758,351.641148,336.177371,2.453532e+06,0,0,0,48
0,0.50 / 0.70 / 0.70,108,0.805195,0.801917,0.217185,0.210758,350.300847,333.060498,2.512952e+06,0,0,0,63
2,0.50 / 0.70 / 0.80,108,0.801948,0.796147,0.217185,0.210758,345.295439,328.250580,2.461126e+06,0,0,0,24

Core parameter diagnostics by RSI cap triple:

,rsi_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_83_plus,specs_core_win_82_plus,specs_core_win_80_plus
0,70 / 68 / 65,648,0.828996,0.812500,0.216509,0.201624,378.467721,329.207680,2.587287e+06,0,0,108,540
1,70 / 68 / 66,648,0.828996,0.812500,0.216509,0.201624,377.377653,327.932423,2.585077e+06,0,0,108,540
2,70 / 68 / 67,648,0.825926,0.809836,0.217185,0.202300,375.523387,327.141708,2.579693e+06,0,0,51,501

Core parameter diagnostics by RV21D floor triple:

,rv21d_triple,specs,max_core_win_rate,median_core_win_rate,max_core_frequency,median_core_frequency,max_core_avg_pnl_per_day,median_core_avg_pnl_per_day,max_core_total_pnl,specs_core_win_85_plus,specs_core_win_83_plus,specs_core_win_82_plus,specs_core_win_80_plus
1,8.0 / 8.5 / 8.5,972,0.828996,0.815436,0.212449,0.200609,378.467721,338.889529,2.587287e+06,0,0,243,918
0,7.5 / 8.5 / 8.5,972,0.821818,0.809211,0.217185,0.204668,360.268843,319.623381,2.546824e+06,0,0,24,663

Selected trade detail sample for top specs:

,spec_id,date,trade_date,selected_tenor,selected_tenor_bucket,outcome_value,pnl_per_day,actual_dte,vrp_log,vrp_z_3m,...,back_z_3m_min,front_z_1y_min,middle_z_1y_min,back_z_1y_min,front_rsi14_max,middle_rsi14_max,back_rsi14_max,front_rv21d_min,middle_rv21d_min,back_rv21d_min
0,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...,2020-07-27,20200727,33,back,23677.151086,739.910971,32.0,1.506651,0.881128,...,0.8,0.7,0.75,0.75,70,68,65,8.0,8.5,8.5
1,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...,2020-07-28,20200728,30,back,23489.640944,757.730353,31.0,1.520873,0.937214,...,0.8,0.7,0.75,0.75,70,68,65,8.0,8.5,8.5
2,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...,2020-08-19,20200819,24,middle,7547.002089,328.130526,23.0,1.567036,1.555944,...,0.8,0.7,0.75,0.75,70,68,65,8.0,8.5,8.5
3,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...,2020-08-21,20200821,15,front,11715.668382,836.833456,14.0,1.462593,0.993049,...,0.8,0.7,0.75,0.75,70,68,65,8.0,8.5,8.5
4,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...,2020-10-19,20201019,24,middle,27021.348616,1080.853945,25.0,1.399671,0.978145,...,0.8,0.7,0.75,0.75,70,68,65,8.0,8.5,8.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...,2022-10-26,20221026,18,middle,23364.485981,1460.280374,16.0,0.780646,0.837228,...,0.8,0.7,0.75,0.75,70,68,65,8.0,8.5,8.5
96,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...,2022-10-27,20221027,21,middle,24111.575132,1095.980688,22.0,0.745012,0.746331,...,0.8,0.7,0.75,0.75,70,68,65,8.0,8.5,8.5
97,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...,2022-10-28,20221028,30,back,26198.007721,935.643133,28.0,0.768543,0.989065,...,0.8,0.7,0.75,0.75,70,68,65,8.0,8.5,8.5
98,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...,2022-10-31,20221031,18,middle,21591.020615,1199.501145,18.0,0.810560,0.869521,...,0.8,0.7,0.75,0.75,70,68,65,8.0,8.5,8.5
99,core_phase3_vrp_0.60_0.70_0.70_z3m_0.70_0.70_0...,2022-11-01,20221101,12,front,19138.507819,1913.850782,10.0,0.843347,0.712063,...,0.8,0.7,0.75,0.75,70,68,65,8.0,8.5,8.5

Cell 7 outputs saved:
Core specs:                    C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_specs_20200701_20260519_20260704_101706.csv
Grid summary:                  C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_grid_summary_20200701_20260519_20260704_101706.csv
Core summary:                  C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_summary_20200701_20260519_20260704_101706.csv
Conditional stats:             C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_conditional_stats_20200701_20260519_20260704_101706.csv
Tenor selection summary:       C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_tenor_selection_summary_20200701_20260519_20260704_101706.csv
Selected trade detail:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_selected_trade_detail_top_specs_20200701_20260519_20260704_101706.csv
Top by win rate:               C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_top_by_win_20200701_20260519_20260704_101706.csv
Win >=85 by frequency:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_win85_by_frequency_20200701_20260519_20260704_101706.csv
Win >=83 by frequency:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_win83_by_frequency_20200701_20260519_20260704_101706.csv
Win >=82 by frequency:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_win82_by_frequency_20200701_20260519_20260704_101706.csv
Tenor top by win:              C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_tenor_top_by_win_20200701_20260519_20260704_101706.csv
Tenor win >=85 by frequency:   C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_tenor_win85_by_frequency_20200701_20260519_20260704_101706.csv
Tenor win >=83 by frequency:   C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_tenor_win83_by_frequency_20200701_20260519_20260704_101706.csv
Tenor win >=82 by frequency:   C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_tenor_win82_by_frequency_20200701_20260519_20260704_101706.csv
Core by VRP:                   C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_by_vrp_20200701_20260519_20260704_101706.csv
Core by 3m z-score:            C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_by_z3m_20200701_20260519_20260704_101706.csv
Core by 1y z-score:            C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_by_z1y_20200701_20260519_20260704_101706.csv
Core by RSI:                   C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_by_rsi_20200701_20260519_20260704_101706.csv
Core by RV21D:                 C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell7_core_only_phase3_untied_z_by_rv21d_20200701_20260519_20260704_101706.csv

Cell 7 complete.

In [10]:
# Cell 8: Z-score leakage audit
#
# Purpose:
#   Confirm whether stored VRP z-scores were calculated using:
#       A) prior-only rolling history: shift(1), correct for our use
#       B) inclusive rolling history: current value included in rolling mean/std
#
# This is audit-only:
#   - No parameter testing
#   - No model changes
#   - No signal changes
#   - No overwrite of clean panel
#
# Stored columns audited:
#   vrp_z_3m
#   vrp_z_1y
#
# Source VRP column:
#   vrp_log
#
# Expected correct formula:
#   z_t = (vrp_log_t - mean(vrp_log_{t-1...t-window})) / std(vrp_log_{t-1...t-window})

from pathlib import Path
import itertools
import numpy as np
import pandas as pd


# -----------------------------
# 1. Paths / load latest clean panel
# -----------------------------

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

PARAM_SWEEP_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "corsi_parameter_sweep_clean"
PARAM_SWEEP_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "corsi_parameter_sweep_clean"

PARAM_SWEEP_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

RUN_TIMESTAMP = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")

clean_panel_candidates = sorted(
    PARAM_SWEEP_PROCESSED_DIR.glob("02_corsi_parameter_sweep_clean_panel_*.parquet")
)

if not clean_panel_candidates:
    raise FileNotFoundError(f"No clean panel found in {PARAM_SWEEP_PROCESSED_DIR}")

CLEAN_PANEL_PATH = clean_panel_candidates[-1]

print("Cell 8: Z-score leakage audit")
print(f"Clean panel path: {CLEAN_PANEL_PATH}")
print(f"Run timestamp:    {RUN_TIMESTAMP}")

panel = pd.read_parquet(CLEAN_PANEL_PATH).copy()

panel["date"] = pd.to_datetime(panel["date"]).dt.normalize()
panel["trade_date"] = pd.to_numeric(panel["trade_date"], errors="coerce").astype(int)
panel["tenor"] = pd.to_numeric(panel["tenor"], errors="coerce").astype(int)

required_cols = [
    "date",
    "trade_date",
    "tenor",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
]

missing_cols = [c for c in required_cols if c not in panel.columns]

if missing_cols:
    raise ValueError(f"Panel missing required columns for z-score audit: {missing_cols}")

audit_df = (
    panel[required_cols]
    .copy()
    .replace([np.inf, -np.inf], np.nan)
    .sort_values(["tenor", "date", "trade_date"])
    .reset_index(drop=True)
)

print()
print("Stored z-score availability:")
display(pd.DataFrame([{
    "rows": len(audit_df),
    "vrp_log_non_null": int(audit_df["vrp_log"].notna().sum()),
    "vrp_z_3m_non_null": int(audit_df["vrp_z_3m"].notna().sum()),
    "vrp_z_1y_non_null": int(audit_df["vrp_z_1y"].notna().sum()),
    "vrp_z_3m_null": int(audit_df["vrp_z_3m"].isna().sum()),
    "vrp_z_1y_null": int(audit_df["vrp_z_1y"].isna().sum()),
    "first_date": audit_df["date"].min(),
    "last_date": audit_df["date"].max(),
    "unique_tenors": audit_df["tenor"].nunique(),
}]))


# -----------------------------
# 2. Recompute candidate z-scores
# -----------------------------

def compute_candidate_z(df, value_col, window, min_periods, convention, ddof):
    """
    convention:
        prior_only = rolling history uses group shift(1)
        inclusive  = rolling history includes current observation

    z_t always uses current value in numerator:
        current value - rolling mean
    """
    if convention == "prior_only_shift1":
        history = df.groupby("tenor")[value_col].shift(1)
    elif convention == "inclusive_current":
        history = df[value_col].copy()
    else:
        raise ValueError(f"Unknown convention: {convention}")

    roll_mean = (
        history
        .groupby(df["tenor"])
        .rolling(window=window, min_periods=min_periods)
        .mean()
        .reset_index(level=0, drop=True)
    )

    roll_std = (
        history
        .groupby(df["tenor"])
        .rolling(window=window, min_periods=min_periods)
        .std(ddof=ddof)
        .reset_index(level=0, drop=True)
    )

    z = (df[value_col] - roll_mean) / roll_std
    z = z.replace([np.inf, -np.inf], np.nan)

    return z


def evaluate_candidate(df, stored_col, candidate_z, horizon, convention, window, min_periods, ddof):
    stored = pd.to_numeric(df[stored_col], errors="coerce")
    cand = pd.to_numeric(candidate_z, errors="coerce")

    stored_finite = np.isfinite(stored)
    cand_finite = np.isfinite(cand)
    both = stored_finite & cand_finite

    diffs = stored[both] - cand[both]

    if both.sum() > 0:
        corr = np.corrcoef(stored[both], cand[both])[0, 1]
        mae = float(np.nanmean(np.abs(diffs)))
        rmse = float(np.sqrt(np.nanmean(np.square(diffs))))
        max_abs = float(np.nanmax(np.abs(diffs)))
        median_abs = float(np.nanmedian(np.abs(diffs)))
    else:
        corr = np.nan
        mae = np.nan
        rmse = np.nan
        max_abs = np.nan
        median_abs = np.nan

    null_mismatch = stored_finite.ne(cand_finite)

    return {
        "horizon": horizon,
        "stored_col": stored_col,
        "convention": convention,
        "window": window,
        "min_periods": min_periods,
        "ddof": ddof,

        "stored_non_null": int(stored_finite.sum()),
        "candidate_non_null": int(cand_finite.sum()),
        "overlap_non_null": int(both.sum()),
        "only_stored_non_null": int((stored_finite & ~cand_finite).sum()),
        "only_candidate_non_null": int((~stored_finite & cand_finite).sum()),
        "null_mismatch_count": int(null_mismatch.sum()),
        "null_mismatch_rate": float(null_mismatch.mean()),

        "corr": float(corr) if np.isfinite(corr) else np.nan,
        "mae": mae,
        "median_abs_error": median_abs,
        "rmse": rmse,
        "max_abs_error": max_abs,
    }


def evaluate_candidate_by_tenor(df, stored_col, candidate_z, horizon, convention, window, min_periods, ddof):
    tmp = df[["date", "trade_date", "tenor", stored_col]].copy()
    tmp["candidate_z"] = candidate_z

    rows = []

    for tenor, g in tmp.groupby("tenor", sort=True):
        stored = pd.to_numeric(g[stored_col], errors="coerce")
        cand = pd.to_numeric(g["candidate_z"], errors="coerce")

        stored_finite = np.isfinite(stored)
        cand_finite = np.isfinite(cand)
        both = stored_finite & cand_finite

        diffs = stored[both] - cand[both]

        if both.sum() > 0:
            corr = np.corrcoef(stored[both], cand[both])[0, 1]
            mae = float(np.nanmean(np.abs(diffs)))
            rmse = float(np.sqrt(np.nanmean(np.square(diffs))))
            max_abs = float(np.nanmax(np.abs(diffs)))
            median_abs = float(np.nanmedian(np.abs(diffs)))
        else:
            corr = np.nan
            mae = np.nan
            rmse = np.nan
            max_abs = np.nan
            median_abs = np.nan

        null_mismatch = stored_finite.ne(cand_finite)

        rows.append({
            "horizon": horizon,
            "stored_col": stored_col,
            "tenor": int(tenor),
            "convention": convention,
            "window": window,
            "min_periods": min_periods,
            "ddof": ddof,

            "rows": len(g),
            "stored_non_null": int(stored_finite.sum()),
            "candidate_non_null": int(cand_finite.sum()),
            "overlap_non_null": int(both.sum()),
            "only_stored_non_null": int((stored_finite & ~cand_finite).sum()),
            "only_candidate_non_null": int((~stored_finite & cand_finite).sum()),
            "null_mismatch_count": int(null_mismatch.sum()),
            "null_mismatch_rate": float(null_mismatch.mean()),

            "corr": float(corr) if np.isfinite(corr) else np.nan,
            "mae": mae,
            "median_abs_error": median_abs,
            "rmse": rmse,
            "max_abs_error": max_abs,
        })

    return pd.DataFrame(rows)


# Candidate search grids.
# Include likely production choices and nearby alternatives.
AUDIT_CONFIG = {
    "3m": {
        "stored_col": "vrp_z_3m",
        "windows": [60, 63, 64, 65],
        "min_periods": [20, 21, 30, 42, 60, 63],
    },
    "1y": {
        "stored_col": "vrp_z_1y",
        "windows": [250, 252, 253],
        "min_periods": [63, 90, 120, 126, 180, 252],
    },
}

CONVENTIONS = [
    "prior_only_shift1",
    "inclusive_current",
]

DDOF_OPTIONS = [0, 1]

candidate_rows = []
candidate_z_cache = {}

for horizon, cfg in AUDIT_CONFIG.items():
    stored_col = cfg["stored_col"]

    for convention, window, min_periods, ddof in itertools.product(
        CONVENTIONS,
        cfg["windows"],
        cfg["min_periods"],
        DDOF_OPTIONS,
    ):
        if min_periods > window:
            continue

        z = compute_candidate_z(
            audit_df,
            value_col="vrp_log",
            window=window,
            min_periods=min_periods,
            convention=convention,
            ddof=ddof,
        )

        key = (horizon, convention, window, min_periods, ddof)
        candidate_z_cache[key] = z

        candidate_rows.append(
            evaluate_candidate(
                audit_df,
                stored_col=stored_col,
                candidate_z=z,
                horizon=horizon,
                convention=convention,
                window=window,
                min_periods=min_periods,
                ddof=ddof,
            )
        )

candidate_results = pd.DataFrame(candidate_rows)

candidate_results["score"] = (
    candidate_results["null_mismatch_rate"].fillna(1.0) * 1_000_000
    + candidate_results["rmse"].fillna(1_000_000)
    + candidate_results["mae"].fillna(1_000_000)
)

candidate_results = candidate_results.sort_values(
    ["horizon", "score", "null_mismatch_count", "rmse", "mae", "max_abs_error"],
    ascending=[True, True, True, True, True, True],
).reset_index(drop=True)

best_candidates = (
    candidate_results
    .sort_values(["horizon", "score"], ascending=[True, True])
    .groupby("horizon", as_index=False)
    .head(1)
    .reset_index(drop=True)
)

print()
print("Best matching z-score convention by horizon:")
display(best_candidates)

print()
print("Top 20 candidate matches by horizon:")
display(
    candidate_results
    .groupby("horizon", as_index=False)
    .head(20)
    .reset_index(drop=True)
)


# -----------------------------
# 3. Per-tenor diagnostics for best candidates
# -----------------------------

best_by_tenor_tables = []

for _, row in best_candidates.iterrows():
    horizon = row["horizon"]
    stored_col = row["stored_col"]
    convention = row["convention"]
    window = int(row["window"])
    min_periods = int(row["min_periods"])
    ddof = int(row["ddof"])

    key = (horizon, convention, window, min_periods, ddof)
    z = candidate_z_cache[key]

    best_by_tenor_tables.append(
        evaluate_candidate_by_tenor(
            audit_df,
            stored_col=stored_col,
            candidate_z=z,
            horizon=horizon,
            convention=convention,
            window=window,
            min_periods=min_periods,
            ddof=ddof,
        )
    )

best_by_tenor = pd.concat(best_by_tenor_tables, ignore_index=True)

print()
print("Per-tenor diagnostics for best matching convention:")
display(best_by_tenor)


# -----------------------------
# 4. Hard conclusion
# -----------------------------

TOLERANCE_MAX_ABS = 1e-8
TOLERANCE_RMSE = 1e-10

conclusion_rows = []

for _, row in best_candidates.iterrows():
    horizon = row["horizon"]
    convention = row["convention"]
    window = int(row["window"])
    min_periods = int(row["min_periods"])
    ddof = int(row["ddof"])
    null_mismatch_count = int(row["null_mismatch_count"])
    rmse = float(row["rmse"])
    max_abs_error = float(row["max_abs_error"])

    exact_match = (
        null_mismatch_count == 0
        and np.isfinite(rmse)
        and np.isfinite(max_abs_error)
        and rmse <= TOLERANCE_RMSE
        and max_abs_error <= TOLERANCE_MAX_ABS
    )

    if exact_match and convention == "prior_only_shift1":
        status = "PASS_PRIOR_ONLY"
        interpretation = "Stored z-score matches prior-only rolling history. No current-value inclusion detected."
    elif exact_match and convention == "inclusive_current":
        status = "FAIL_INCLUSIVE_CURRENT"
        interpretation = "Stored z-score matches inclusive rolling history. Current value appears included in rolling mean/std."
    else:
        status = "NO_EXACT_MATCH"
        interpretation = "Stored z-score does not exactly match tested conventions. Review top candidates and source code."

    conclusion_rows.append({
        "horizon": horizon,
        "status": status,
        "best_convention": convention,
        "best_window": window,
        "best_min_periods": min_periods,
        "best_ddof": ddof,
        "null_mismatch_count": null_mismatch_count,
        "rmse": rmse,
        "max_abs_error": max_abs_error,
        "interpretation": interpretation,
    })

conclusion = pd.DataFrame(conclusion_rows)

print()
print("Z-score leakage audit conclusion:")
display(conclusion)


# -----------------------------
# 5. Save audit outputs
# -----------------------------

safe_start = audit_df["date"].min().strftime("%Y%m%d")
safe_end = audit_df["date"].max().strftime("%Y%m%d")

candidate_results_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell8_zscore_leakage_audit_candidates_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

best_candidates_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell8_zscore_leakage_audit_best_candidates_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

best_by_tenor_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell8_zscore_leakage_audit_best_by_tenor_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

conclusion_path = (
    PARAM_SWEEP_AUDIT_DIR
    / f"02_corsi_parameter_sweep_clean_cell8_zscore_leakage_audit_conclusion_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

candidate_results.to_csv(candidate_results_path, index=False)
best_candidates.to_csv(best_candidates_path, index=False)
best_by_tenor.to_csv(best_by_tenor_path, index=False)
conclusion.to_csv(conclusion_path, index=False)

print()
print("Cell 8 outputs saved:")
print(f"Candidate matches:       {candidate_results_path}")
print(f"Best candidates:         {best_candidates_path}")
print(f"Best by tenor:           {best_by_tenor_path}")
print(f"Conclusion:              {conclusion_path}")

print()
print("Cell 8 complete.")

Cell 8: Z-score leakage audit
Clean panel path: C:\Users\patri\vrp_project\data\processed\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_panel_20200102_20260623_20260704_085138.parquet
Run timestamp:    20260704_104426

Stored z-score availability:

,rows,vrp_log_non_null,vrp_z_3m_non_null,vrp_z_1y_non_null,vrp_z_3m_null,vrp_z_1y_null,first_date,last_date,unique_tenors
0,14565,14565,14304,13440,261,1125,2020-01-02,2026-06-23,9

Best matching z-score convention by horizon:

,horizon,stored_col,convention,window,min_periods,ddof,stored_non_null,candidate_non_null,overlap_non_null,only_stored_non_null,only_candidate_non_null,null_mismatch_count,null_mismatch_rate,corr,mae,median_abs_error,rmse,max_abs_error,score
0,1y,vrp_z_1y,inclusive_current,252,126,1,13440,13440,13440,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,3m,vrp_z_3m,inclusive_current,63,30,1,14304,14304,14304,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

Top 20 candidate matches by horizon:

,horizon,stored_col,convention,window,min_periods,ddof,stored_non_null,candidate_non_null,overlap_non_null,only_stored_non_null,only_candidate_non_null,null_mismatch_count,null_mismatch_rate,corr,mae,median_abs_error,rmse,max_abs_error,score
0,1y,vrp_z_1y,inclusive_current,252,126,1,13440,13440,13440,0,0,0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1y,vrp_z_1y,inclusive_current,252,126,0,13440,13440,13440,0,0,0,0.000000,1.000000,0.001607,0.001323,0.002065,0.009275,0.003672
2,1y,vrp_z_1y,inclusive_current,253,126,1,13440,13440,13440,0,0,0,0.000000,0.999983,0.003746,0.003059,0.005859,0.070908,0.009605
3,1y,vrp_z_1y,inclusive_current,253,126,0,13440,13440,13440,0,0,0,0.000000,0.999983,0.004507,0.004018,0.006137,0.067702,0.010644
4,1y,vrp_z_1y,inclusive_current,250,126,1,13440,13440,13440,0,0,0,0.000000,0.999944,0.007015,0.005640,0.010848,0.143547,0.017862
5,1y,vrp_z_1y,inclusive_current,250,126,0,13440,13440,13440,0,0,0,0.000000,0.999944,0.006937,0.004664,0.011244,0.148711,0.018181
6,1y,vrp_z_1y,prior_only_shift1,250,126,1,13440,13431,13431,9,0,9,0.000618,0.999951,0.007147,0.003287,0.014833,0.236390,617.941650
7,1y,vrp_z_1y,prior_only_shift1,252,126,1,13440,13431,13431,9,0,9,0.000618,0.999949,0.007776,0.005011,0.014508,0.226356,617.941955
8,1y,vrp_z_1y,prior_only_shift1,250,126,0,13440,13431,13431,9,0,9,0.000618,0.999951,0.008428,0.004184,0.016435,0.246214,617.944534
9,1y,vrp_z_1y,prior_only_shift1,252,126,0,13440,13431,13431,9,0,9,0.000618,0.999949,0.008983,0.005908,0.016046,0.236082,617.944699
10,1y,vrp_z_1y,prior_only_shift1,253,126,1,13440,13431,13431,9,0,9,0.000618,0.999914,0.010369,0.007741,0.016575,0.226701,617.946614
11,1y,vrp_z_1y,prior_only_shift1,253,126,0,13440,13431,13431,9,0,9,0.000618,0.999914,0.011456,0.008620,0.017877,0.236389,617.949003
12,1y,vrp_z_1y,prior_only_shift1,250,120,1,13440,13485,13440,0,45,45,0.003090,0.999951,0.007144,0.003287,0.014828,0.236390,3089.620324
13,1y,vrp_z_1y,prior_only_shift1,252,120,1,13440,13485,13440,0,45,45,0.003090,0.999949,0.007773,0.005006,0.014504,0.226356,3089.620629
14,1y,vrp_z_1y,prior_only_shift1,250,120,0,13440,13485,13440,0,45,45,0.003090,0.999951,0.008426,0.004185,0.016430,0.246214,3089.623208
15,1y,vrp_z_1y,prior_only_shift1,252,120,0,13440,13485,13440,0,45,45,0.003090,0.999949,0.008980,0.005907,0.016041,0.236082,3089.623373
16,1y,vrp_z_1y,prior_only_shift1,253,120,1,13440,13485,13440,0,45,45,0.003090,0.999914,0.010364,0.007736,0.016569,0.226701,3089.625285
17,1y,vrp_z_1y,prior_only_shift1,253,120,0,13440,13485,13440,0,45,45,0.003090,0.999914,0.011451,0.008614,0.017871,0.236389,3089.627674
18,1y,vrp_z_1y,inclusive_current,252,120,1,13440,13494,13440,0,54,54,0.003708,1.000000,0.000000,0.000000,0.000000,0.000000,3707.518023
19,1y,vrp_z_1y,inclusive_current,252,120,0,13440,13494,13440,0,54,54,0.003708,1.000000,0.001607,0.001323,0.002065,0.009275,3707.521695
20,3m,vrp_z_3m,inclusive_current,63,30,1,14304,14304,14304,0,0,0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,3m,vrp_z_3m,inclusive_current,63,30,0,14304,14304,14304,0,0,0,0.000000,1.000000,0.007088,0.005967,0.008979,0.048269,0.016067
22,3m,vrp_z_3m,inclusive_current,64,30,1,14304,14304,14304,0,0,0,0.000000,0.999828,0.014929,0.013318,0.020218,0.290459,0.035147
23,3m,vrp_z_3m,inclusive_current,64,30,0,14304,14304,14304,0,0,0,0.000000,0.999828,0.018478,0.017925,0.022586,0.282986,0.041064
24,3m,vrp_z_3m,inclusive_current,65,30,1,14304,14304,14304,0,0,0,0.000000,0.999500,0.025937,0.023151,0.034407,0.304238,0.060344
25,3m,vrp_z_3m,inclusive_current,65,30,0,14304,14304,14304,0,0,0,0.000000,0.999500,0.028786,0.026838,0.035874,0.297038,0.064660
26,3m,vrp_z_3m,inclusive_current,60,30,0,14304,14304,14304,0,0,0,0.000000,0.998866,0.037289,0.029363,0.052400,0.503488,0.089688
27,3m,vrp_z_3m,inclusive_current,60,30,1,14304,14304,14304,0,0,0,0.000000,0.998867,0.038474,0.033936,0.051749,0.483436,0.090223
28,3m,vrp_z_3m,prior_only_shift1,63,30,1,14304,14295,14295,9,0,9,0.000618,0.999118,0.034691,0.021856,0.067299,1.054203,618.021660
29,3m,vrp_z_3m,prior_only_shift1,60,30,1,14304,14295,14295,9,0,9,0.000618,0.998709,0.039081,0.022516,0.073548,1.162004,618.032299
30,3m,vrp_z_3m,prior_only_shift1,64,30,1,14304,14295,14295,9,0,9,0.000618,0.998858,0.043440,0.032752,0.071205,0.989798,618.034315
31,3m,vrp_z_3m,prior_only_shift1,63,30,0,14304,14295,14295,9,0,9,0.000618,0.999107,0.040412,0.025651,0.074639,1.099105,618.034721
32,3m,vrp_z_3m,prior_only_shift1,60,30,0,14304,14295,14295,9,0,9,0.000618,0.998699,0.043827,0.024788,0.080508,1.210140,618.044005
33,3m,vrp_z_3m,prior_only_shift1,64,30,0,14304,14295,14295,9,0,9,0.000618,0.998846,0.048445,0.036301,0.077993,1.031769,618.046108
34,3m,vrp_z_3m,prior_only_shift1,65,30,1,14304,14295,14295,9,0,9,0.000618,0.998515,0.051880,0.042483,0.076204,1.017911,618.047755
35,3m,vrp_z_3m,prior_only_shift1,65,30,0,14304,14295,14295,9,0,9,0.000618,0.998503,0.056556,0.046051,0.082410,1.059447,618.058636
36,3m,vrp_z_3m,prior_only_shift1,63,21,1,14304,14376,14304,0,72,72,0.004943,0.999118,0.034671,0.021849,0.067278,1.054203,4943.459313
37,3m,vrp_z_3m,prior_only_shift1,60,21,1,14304,14376,14304,0,72,72,0.004943,0.998709,0.039059,0.022500,0.073525,1.162004,4943.469947
38,3m,vrp_z_3m,prior_only_shift1,64,21,1,14304,14376,14304,0,72,72,0.004943,0.998858,0.043415,0.032730,0.071183,0.989798,4943.471962
39,3m,vrp_z_3m,prior_only_shift1,63,21,0,14304,14376,14304,0,72,72,0.004943,0.999107,0.040391,0.025621,0.074616,1.099105,4943.472371

Per-tenor diagnostics for best matching convention:

,horizon,stored_col,tenor,convention,window,min_periods,ddof,rows,stored_non_null,candidate_non_null,overlap_non_null,only_stored_non_null,only_candidate_non_null,null_mismatch_count,null_mismatch_rate,corr,mae,median_abs_error,rmse,max_abs_error
0,1y,vrp_z_1y,9,inclusive_current,252,126,1,1626,1501,1501,1501,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
1,1y,vrp_z_1y,12,inclusive_current,252,126,1,1624,1499,1499,1499,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
2,1y,vrp_z_1y,15,inclusive_current,252,126,1,1623,1498,1498,1498,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
3,1y,vrp_z_1y,18,inclusive_current,252,126,1,1620,1495,1495,1495,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
4,1y,vrp_z_1y,21,inclusive_current,252,126,1,1619,1494,1494,1494,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
5,1y,vrp_z_1y,24,inclusive_current,252,126,1,1616,1491,1491,1491,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
6,1y,vrp_z_1y,27,inclusive_current,252,126,1,1615,1490,1490,1490,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
7,1y,vrp_z_1y,30,inclusive_current,252,126,1,1612,1487,1487,1487,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
8,1y,vrp_z_1y,33,inclusive_current,252,126,1,1610,1485,1485,1485,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
9,3m,vrp_z_3m,9,inclusive_current,63,30,1,1626,1597,1597,1597,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
10,3m,vrp_z_3m,12,inclusive_current,63,30,1,1624,1595,1595,1595,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
11,3m,vrp_z_3m,15,inclusive_current,63,30,1,1623,1594,1594,1594,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
12,3m,vrp_z_3m,18,inclusive_current,63,30,1,1620,1591,1591,1591,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
13,3m,vrp_z_3m,21,inclusive_current,63,30,1,1619,1590,1590,1590,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
14,3m,vrp_z_3m,24,inclusive_current,63,30,1,1616,1587,1587,1587,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
15,3m,vrp_z_3m,27,inclusive_current,63,30,1,1615,1586,1586,1586,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
16,3m,vrp_z_3m,30,inclusive_current,63,30,1,1612,1583,1583,1583,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
17,3m,vrp_z_3m,33,inclusive_current,63,30,1,1610,1581,1581,1581,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0

Z-score leakage audit conclusion:

,horizon,status,best_convention,best_window,best_min_periods,best_ddof,null_mismatch_count,rmse,max_abs_error,interpretation
0,1y,FAIL_INCLUSIVE_CURRENT,inclusive_current,252,126,1,0,0.0,0.0,Stored z-score matches inclusive rolling histo...
1,3m,FAIL_INCLUSIVE_CURRENT,inclusive_current,63,30,1,0,0.0,0.0,Stored z-score matches inclusive rolling histo...

Cell 8 outputs saved:
Candidate matches:       C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell8_zscore_leakage_audit_candidates_20200102_20260623_20260704_104426.csv
Best candidates:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell8_zscore_leakage_audit_best_candidates_20200102_20260623_20260704_104426.csv
Best by tenor:           C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell8_zscore_leakage_audit_best_by_tenor_20200102_20260623_20260704_104426.csv
Conclusion:              C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_cell8_zscore_leakage_audit_conclusion_20200102_20260623_20260704_104426.csv

Cell 8 complete.

In [11]:
# Cell 9: Rebuild clean parameter sweep panel with prior-only z-scores
#
# Purpose:
#   Start a clean branch after discovering that the stored z-scores were inclusive-current.
#
# This cell:
#   1. Loads the latest existing clean panel.
#   2. Preserves old inclusive-current z-score columns.
#   3. Recomputes prior-only z-scores by tenor:
#        3m: window=63,  min_periods=30,  ddof=1, shift(1)
#        1y: window=252, min_periods=126, ddof=1, shift(1)
#   4. Replaces vrp_z_3m and vrp_z_1y with prior-only versions.
#   5. Recomputes parameter sweep eligibility.
#   6. Saves a new corrected panel in a new branch directory.
#   7. Saves diagnostics and an internal verification audit.
#
# This does NOT:
#   - Change har_total_simple forecast variance
#   - Change VRP log
#   - Change implied variance
#   - Change outcomes
#   - Change RSI / RV21D
#   - Run a parameter sweep
#   - Overwrite the old inclusive-current clean panel

from pathlib import Path
import numpy as np
import pandas as pd


# -----------------------------
# 1. Paths
# -----------------------------

PROJECT_ROOT = Path(r"C:\Users\patri\vrp_project")

OLD_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "corsi_parameter_sweep_clean"

NEW_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "corsi_parameter_sweep_prior_only_z"
NEW_AUDIT_DIR = PROJECT_ROOT / "data" / "audit" / "corsi_parameter_sweep_prior_only_z"

NEW_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
NEW_AUDIT_DIR.mkdir(parents=True, exist_ok=True)

RUN_TIMESTAMP = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")

clean_panel_candidates = sorted(
    OLD_PROCESSED_DIR.glob("02_corsi_parameter_sweep_clean_panel_*.parquet")
)

if not clean_panel_candidates:
    raise FileNotFoundError(f"No existing clean panel found in {OLD_PROCESSED_DIR}")

SOURCE_CLEAN_PANEL_PATH = clean_panel_candidates[-1]

print("Cell 9: Rebuild clean panel with prior-only z-scores")
print(f"Source clean panel: {SOURCE_CLEAN_PANEL_PATH}")
print(f"New processed dir:  {NEW_PROCESSED_DIR}")
print(f"New audit dir:      {NEW_AUDIT_DIR}")
print(f"Run timestamp:      {RUN_TIMESTAMP}")


# -----------------------------
# 2. Load panel
# -----------------------------

panel = pd.read_parquet(SOURCE_CLEAN_PANEL_PATH).copy()

panel["date"] = pd.to_datetime(panel["date"]).dt.normalize()
panel["trade_date"] = pd.to_numeric(panel["trade_date"], errors="coerce").astype(int)
panel["tenor"] = pd.to_numeric(panel["tenor"], errors="coerce").astype(int)

required_cols = [
    "date",
    "trade_date",
    "tenor",
    "tenor_bucket",
    "forecast_model",
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rsi14",
    "rv21d",
    "outcome_value",
    "has_outcome",
    "is_parameter_sweep_eligible",
]

missing_cols = [c for c in required_cols if c not in panel.columns]

if missing_cols:
    raise ValueError(f"Source panel missing required columns: {missing_cols}")

panel = panel.replace([np.inf, -np.inf], np.nan)

print()
print("Source panel summary:")
display(pd.DataFrame([{
    "rows": len(panel),
    "first_date": panel["date"].min(),
    "last_date": panel["date"].max(),
    "unique_dates": panel["trade_date"].nunique(),
    "unique_tenors": panel["tenor"].nunique(),
    "source_vrp_z_3m_non_null": int(panel["vrp_z_3m"].notna().sum()),
    "source_vrp_z_1y_non_null": int(panel["vrp_z_1y"].notna().sum()),
    "source_eligible_rows": int(panel["is_parameter_sweep_eligible"].astype(bool).sum()),
}]))


# -----------------------------
# 3. Preserve old inclusive-current z-scores
# -----------------------------

panel["vrp_z_3m_inclusive_current_old"] = panel["vrp_z_3m"]
panel["vrp_z_1y_inclusive_current_old"] = panel["vrp_z_1y"]
panel["is_parameter_sweep_eligible_inclusive_current_old"] = panel["is_parameter_sweep_eligible"]


# -----------------------------
# 4. Recompute prior-only z-scores
# -----------------------------

def compute_prior_only_z_by_tenor(df, value_col, window, min_periods, ddof):
    """
    For each tenor:
        z_t = (x_t - mean(x_{t-1}, ..., x_{t-window}))
              / std(x_{t-1}, ..., x_{t-window})

    Uses shift(1), so the current value is NOT included in rolling mean/std.
    """
    out = pd.Series(index=df.index, dtype=float)

    for tenor, g in df.groupby("tenor", sort=True):
        g = g.sort_values(["date", "trade_date"]).copy()

        x = pd.to_numeric(g[value_col], errors="coerce")
        history = x.shift(1)

        roll_mean = history.rolling(
            window=window,
            min_periods=min_periods,
        ).mean()

        roll_std = history.rolling(
            window=window,
            min_periods=min_periods,
        ).std(ddof=ddof)

        z = (x - roll_mean) / roll_std
        z = z.replace([np.inf, -np.inf], np.nan)

        out.loc[g.index] = z

    return out


panel = panel.sort_values(["tenor", "date", "trade_date"]).copy()

panel["vrp_z_3m_prior_only"] = compute_prior_only_z_by_tenor(
    panel,
    value_col="vrp_log",
    window=63,
    min_periods=30,
    ddof=1,
)

panel["vrp_z_1y_prior_only"] = compute_prior_only_z_by_tenor(
    panel,
    value_col="vrp_log",
    window=252,
    min_periods=126,
    ddof=1,
)

panel["vrp_z_3m"] = panel["vrp_z_3m_prior_only"]
panel["vrp_z_1y"] = panel["vrp_z_1y_prior_only"]


# -----------------------------
# 5. Recompute parameter sweep eligibility
# -----------------------------

eligibility_required_cols = [
    "vrp_log",
    "vrp_z_3m",
    "vrp_z_1y",
    "rsi14",
    "rv21d",
    "outcome_value",
]

for c in eligibility_required_cols:
    panel[c] = pd.to_numeric(panel[c], errors="coerce")

panel["has_outcome"] = panel["has_outcome"].astype(bool)

panel["is_parameter_sweep_eligible"] = (
    panel["has_outcome"]
    & panel[eligibility_required_cols].notna().all(axis=1)
)

panel = panel.sort_values(["date", "tenor"]).reset_index(drop=True)


# -----------------------------
# 6. Diagnostics: old vs new z-scores
# -----------------------------

def summarize_old_new_z(df, old_col, new_col, label):
    old = pd.to_numeric(df[old_col], errors="coerce")
    new = pd.to_numeric(df[new_col], errors="coerce")

    both = old.notna() & new.notna()
    diff = new[both] - old[both]

    return {
        "z_horizon": label,
        "old_col": old_col,
        "new_col": new_col,
        "rows": len(df),
        "old_non_null": int(old.notna().sum()),
        "new_non_null": int(new.notna().sum()),
        "overlap_non_null": int(both.sum()),
        "old_only_non_null": int((old.notna() & new.isna()).sum()),
        "new_only_non_null": int((old.isna() & new.notna()).sum()),
        "mean_old": float(old.mean()),
        "mean_new": float(new.mean()),
        "median_old": float(old.median()),
        "median_new": float(new.median()),
        "std_old": float(old.std(ddof=1)),
        "std_new": float(new.std(ddof=1)),
        "mean_new_minus_old": float(diff.mean()) if len(diff) else np.nan,
        "median_new_minus_old": float(diff.median()) if len(diff) else np.nan,
        "mean_abs_new_minus_old": float(diff.abs().mean()) if len(diff) else np.nan,
        "max_abs_new_minus_old": float(diff.abs().max()) if len(diff) else np.nan,
        "corr_old_new": float(old[both].corr(new[both])) if both.sum() > 1 else np.nan,
    }


z_comparison_summary = pd.DataFrame([
    summarize_old_new_z(
        panel,
        old_col="vrp_z_3m_inclusive_current_old",
        new_col="vrp_z_3m",
        label="3m",
    ),
    summarize_old_new_z(
        panel,
        old_col="vrp_z_1y_inclusive_current_old",
        new_col="vrp_z_1y",
        label="1y",
    ),
])

eligibility_summary = pd.DataFrame([{
    "rows": len(panel),
    "old_inclusive_eligible_rows": int(panel["is_parameter_sweep_eligible_inclusive_current_old"].astype(bool).sum()),
    "new_prior_only_eligible_rows": int(panel["is_parameter_sweep_eligible"].astype(bool).sum()),
    "eligible_rows_lost": int(
        panel["is_parameter_sweep_eligible_inclusive_current_old"].astype(bool).sum()
        - panel["is_parameter_sweep_eligible"].astype(bool).sum()
    ),
    "old_vrp_z_3m_non_null": int(panel["vrp_z_3m_inclusive_current_old"].notna().sum()),
    "new_vrp_z_3m_non_null": int(panel["vrp_z_3m"].notna().sum()),
    "old_vrp_z_1y_non_null": int(panel["vrp_z_1y_inclusive_current_old"].notna().sum()),
    "new_vrp_z_1y_non_null": int(panel["vrp_z_1y"].notna().sum()),
}])

by_tenor_summary_rows = []

for tenor, g in panel.groupby("tenor", sort=True):
    row = {
        "tenor": int(tenor),
        "rows": len(g),
        "old_eligible_rows": int(g["is_parameter_sweep_eligible_inclusive_current_old"].astype(bool).sum()),
        "new_eligible_rows": int(g["is_parameter_sweep_eligible"].astype(bool).sum()),
        "old_z_3m_non_null": int(g["vrp_z_3m_inclusive_current_old"].notna().sum()),
        "new_z_3m_non_null": int(g["vrp_z_3m"].notna().sum()),
        "old_z_1y_non_null": int(g["vrp_z_1y_inclusive_current_old"].notna().sum()),
        "new_z_1y_non_null": int(g["vrp_z_1y"].notna().sum()),
    }

    by_tenor_summary_rows.append(row)

by_tenor_summary = pd.DataFrame(by_tenor_summary_rows)

print()
print("Old inclusive-current z vs new prior-only z comparison:")
display(z_comparison_summary)

print()
print("Eligibility summary:")
display(eligibility_summary)

print()
print("Eligibility / z-score availability by tenor:")
display(by_tenor_summary)


# -----------------------------
# 7. Internal verification audit
# -----------------------------

def verify_prior_only_match(df, stored_col, value_col, window, min_periods, ddof, label):
    recomputed = compute_prior_only_z_by_tenor(
        df,
        value_col=value_col,
        window=window,
        min_periods=min_periods,
        ddof=ddof,
    )

    stored = pd.to_numeric(df[stored_col], errors="coerce")

    stored_finite = np.isfinite(stored)
    recomputed_finite = np.isfinite(recomputed)
    both = stored_finite & recomputed_finite

    diff = stored[both] - recomputed[both]

    if both.sum() > 0:
        rmse = float(np.sqrt(np.nanmean(np.square(diff))))
        max_abs_error = float(np.nanmax(np.abs(diff)))
        mae = float(np.nanmean(np.abs(diff)))
        corr = float(stored[both].corr(recomputed[both]))
    else:
        rmse = np.nan
        max_abs_error = np.nan
        mae = np.nan
        corr = np.nan

    null_mismatch_count = int(stored_finite.ne(recomputed_finite).sum())

    exact_match = (
        null_mismatch_count == 0
        and np.isfinite(rmse)
        and np.isfinite(max_abs_error)
        and rmse == 0.0
        and max_abs_error == 0.0
    )

    status = "PASS_PRIOR_ONLY" if exact_match else "FAIL_RECHECK"

    return {
        "z_horizon": label,
        "stored_col": stored_col,
        "convention": "prior_only_shift1",
        "window": window,
        "min_periods": min_periods,
        "ddof": ddof,
        "stored_non_null": int(stored_finite.sum()),
        "recomputed_non_null": int(recomputed_finite.sum()),
        "overlap_non_null": int(both.sum()),
        "null_mismatch_count": null_mismatch_count,
        "corr": corr,
        "mae": mae,
        "rmse": rmse,
        "max_abs_error": max_abs_error,
        "status": status,
    }


verification = pd.DataFrame([
    verify_prior_only_match(
        panel,
        stored_col="vrp_z_3m",
        value_col="vrp_log",
        window=63,
        min_periods=30,
        ddof=1,
        label="3m",
    ),
    verify_prior_only_match(
        panel,
        stored_col="vrp_z_1y",
        value_col="vrp_log",
        window=252,
        min_periods=126,
        ddof=1,
        label="1y",
    ),
])

print()
print("Prior-only z-score verification:")
display(verification)

if not verification["status"].eq("PASS_PRIOR_ONLY").all():
    raise ValueError("Prior-only z-score verification failed. Do not continue to sweeps.")


# -----------------------------
# 8. Save corrected panel and diagnostics
# -----------------------------

safe_start = panel["date"].min().strftime("%Y%m%d")
safe_end = panel["date"].max().strftime("%Y%m%d")

corrected_panel_path = (
    NEW_PROCESSED_DIR
    / f"03_corsi_parameter_sweep_prior_only_z_panel_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.parquet"
)

z_comparison_summary_path = (
    NEW_AUDIT_DIR
    / f"03_corsi_parameter_sweep_prior_only_z_cell9_z_comparison_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

eligibility_summary_path = (
    NEW_AUDIT_DIR
    / f"03_corsi_parameter_sweep_prior_only_z_cell9_eligibility_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

by_tenor_summary_path = (
    NEW_AUDIT_DIR
    / f"03_corsi_parameter_sweep_prior_only_z_cell9_by_tenor_summary_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

verification_path = (
    NEW_AUDIT_DIR
    / f"03_corsi_parameter_sweep_prior_only_z_cell9_prior_only_verification_{safe_start}_{safe_end}_{RUN_TIMESTAMP}.csv"
)

panel.to_parquet(corrected_panel_path, index=False)
z_comparison_summary.to_csv(z_comparison_summary_path, index=False)
eligibility_summary.to_csv(eligibility_summary_path, index=False)
by_tenor_summary.to_csv(by_tenor_summary_path, index=False)
verification.to_csv(verification_path, index=False)

print()
print("Cell 9 outputs saved:")
print(f"Corrected prior-only z panel: {corrected_panel_path}")
print(f"Z comparison summary:        {z_comparison_summary_path}")
print(f"Eligibility summary:         {eligibility_summary_path}")
print(f"By-tenor summary:            {by_tenor_summary_path}")
print(f"Prior-only verification:     {verification_path}")

print()
print("Cell 9 complete.")

Cell 9: Rebuild clean panel with prior-only z-scores
Source clean panel: C:\Users\patri\vrp_project\data\processed\corsi_parameter_sweep_clean\02_corsi_parameter_sweep_clean_panel_20200102_20260623_20260704_085138.parquet
New processed dir:  C:\Users\patri\vrp_project\data\processed\corsi_parameter_sweep_prior_only_z
New audit dir:      C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_prior_only_z
Run timestamp:      20260704_104831

Source panel summary:

,rows,first_date,last_date,unique_dates,unique_tenors,source_vrp_z_3m_non_null,source_vrp_z_1y_non_null,source_eligible_rows
0,14565,2020-01-02,2026-06-23,1626,9,14304,13440,13374

Old inclusive-current z vs new prior-only z comparison:

,z_horizon,old_col,new_col,rows,old_non_null,new_non_null,overlap_non_null,old_only_non_null,new_only_non_null,mean_old,mean_new,median_old,median_new,std_old,std_new,mean_new_minus_old,median_new_minus_old,mean_abs_new_minus_old,max_abs_new_minus_old,corr_old_new
0,3m,vrp_z_3m_inclusive_current_old,vrp_z_3m,14565,14304,14295,14295,9,0,0.007087,0.006522,0.021842,0.022975,1.086962,1.135762,-0.000637,0.000183,0.034691,1.054203,0.999118
1,1y,vrp_z_1y_inclusive_current_old,vrp_z_1y,14565,13440,13431,13431,9,0,-0.129884,-0.131333,-0.113547,-0.115075,1.015115,1.025501,-0.001027,-0.000760,0.007776,0.226356,0.999949

Eligibility summary:

,rows,old_inclusive_eligible_rows,new_prior_only_eligible_rows,eligible_rows_lost,old_vrp_z_3m_non_null,new_vrp_z_3m_non_null,old_vrp_z_1y_non_null,new_vrp_z_1y_non_null
0,14565,13374,13365,9,14304,14295,13440,13431

Eligibility / z-score availability by tenor:

,tenor,rows,old_eligible_rows,new_eligible_rows,old_z_3m_non_null,new_z_3m_non_null,old_z_1y_non_null,new_z_1y_non_null
0,9,1626,1495,1494,1597,1596,1501,1500
1,12,1624,1492,1491,1595,1594,1499,1498
2,15,1623,1490,1489,1594,1593,1498,1497
3,18,1620,1488,1487,1591,1590,1495,1494
4,21,1619,1485,1484,1590,1589,1494,1493
5,24,1616,1484,1483,1587,1586,1491,1490
6,27,1615,1481,1480,1586,1585,1490,1489
7,30,1612,1481,1480,1583,1582,1487,1486
8,33,1610,1478,1477,1581,1580,1485,1484

Prior-only z-score verification:

,z_horizon,stored_col,convention,window,min_periods,ddof,stored_non_null,recomputed_non_null,overlap_non_null,null_mismatch_count,corr,mae,rmse,max_abs_error,status
0,3m,vrp_z_3m,prior_only_shift1,63,30,1,14295,14295,14295,0,1.0,0.0,0.0,0.0,PASS_PRIOR_ONLY
1,1y,vrp_z_1y,prior_only_shift1,252,126,1,13431,13431,13431,0,1.0,0.0,0.0,0.0,PASS_PRIOR_ONLY

Cell 9 outputs saved:
Corrected prior-only z panel: C:\Users\patri\vrp_project\data\processed\corsi_parameter_sweep_prior_only_z\03_corsi_parameter_sweep_prior_only_z_panel_20200102_20260623_20260704_104831.parquet
Z comparison summary:        C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_prior_only_z\03_corsi_parameter_sweep_prior_only_z_cell9_z_comparison_summary_20200102_20260623_20260704_104831.csv
Eligibility summary:         C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_prior_only_z\03_corsi_parameter_sweep_prior_only_z_cell9_eligibility_summary_20200102_20260623_20260704_104831.csv
By-tenor summary:            C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_prior_only_z\03_corsi_parameter_sweep_prior_only_z_cell9_by_tenor_summary_20200102_20260623_20260704_104831.csv
Prior-only verification:     C:\Users\patri\vrp_project\data\audit\corsi_parameter_sweep_prior_only_z\03_corsi_parameter_sweep_prior_only_z_cell9_prior_only_verification_20200102_20260623_20260704_104831.csv

Cell 9 complete.